3scale/porta

portafly/src/components/data-list/BulkActionsWidget.tsx
portafly/src/components/data-list/BulkSelectorWidget.tsx
portafly/src/tests/components/data-list/__snapshots__/BulkActionsWidget.test.tsx.snap

Add missing ids to BulkSelector and BulkActions widgets

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock
app/controllers/provider/admin/dashboards_controller.rb
app/helpers/menu_helper.rb
app/helpers/provider/admin/dashboards_helper.rb
app/lib/logic/provider_settings.rb
app/models/alert.rb
app/models/cinstance.rb
app/models/service.rb
app/views/provider/admin/dashboards/_service_navigation.html.slim
config/webpacker.yml
test/helpers/menu_helper_test.rb
test/unit/logic/provider_settings_test.rb

Revert "[Dashboard] optimization"

---

db/migrate/20200617105046_add_new_column_to_accounts_bought_c_instances_count.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

First part of [THREESCALE-5328: Get the applications count for each account](https://issues.redhat.com/browse/THREESCALE-5328)
It's blocking #1939

Adds new column bought_cinstances_count to Accounts table

---

app/models/contract.rb

We do not need to have the same method twice 😝 
https://github.com/3scale/porta/blob/f7ff1025c4c37570082c4a35623a90dd33d85bc0/app/models/contract.rb#L251-L260
https://github.com/3scale/porta/blob/f7ff1025c4c37570082c4a35623a90dd33d85bc0/app/models/contract.rb#L305-L318

Remove repeated method: Contract#update_counter_cache?

---

app/models/account.rb
spec/support/api/context.rb

Fix spec/acceptance/api/account_spec.rb 

---

app/models/account/buyer_methods.rb
app/models/account/provider_methods.rb

This couple of small changes makes it easier to change and easier to debug https://github.com/3scale/porta/pull/1939

Refactor (mini) 2 methods in ProviderMethods to make it easier/quicker to ever change them or debug them.

---

db/migrate/20200617105046_add_new_column_to_accounts_bought_c_instances_count.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Revert "Adds new column bought_cinstances_count to Accounts table"

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock

Bump strong_migrations from 0.6.2 to 0.6.8

---

lib/tasks/openshift.rake

Remove daemon.stop after start 🤦‍♂️

[Fix] Sphinx starting in openshift

---

app/assets/stylesheets/provider/admin/_dashboard.scss

It's broken.
APIAP
NON APIAP
TBD

Fixes Service search in Dashboard for non APIAP

---

app/lib/backend_api_logic/proxy_extension.rb

Remove Proxy#legacy_api_backend

---

app/controllers/provider/admin/dashboard/service/navigations_controller.rb
app/helpers/provider/admin/dashboards_helper.rb
app/presenters/dashboard_widget_presenter.rb
app/views/provider/admin/dashboards/_service.html.slim
app/views/provider/admin/dashboards/widgets/_new_accounts.html.slim
app/views/provider/admin/dashboards/widgets/_service_hits.html.slim
app/views/provider/admin/dashboards/widgets/_service_integration_errors.html.slim
app/views/provider/admin/dashboards/widgets/_service_navigations.html.slim
config/routes.rb
features/old/menu/dashboard.feature
features/old/stats/provider_side.feature
features/step_definitions/dashboard_steps.rb

Performance problems with the dashboard.
https://issues.redhat.com/browse/THREESCALE-3592

[Dashboard] print ajax widget content once loaded

---

app/indices/account_index.rb
app/indices/cms_page_index.rb
app/indices/proxy_rules_index.rb
app/indices/topic_index.rb

Otherwise filtering would be impossible
Closes https://issues.redhat.com/browse/THREESCALE-5486

[sphinx] Integer type should be BigInt

---

portafly/package.json
portafly/src/components/AppLayout.tsx
portafly/src/components/Root.tsx
portafly/src/components/pages/accounts/AccountsIndexPage.tsx
portafly/src/components/pages/accounts/AccountsTable.tsx
portafly/src/components/shared/data-list/modals/DataListModal.tsx
portafly/src/tests/components/AppLayout.test.tsx
portafly/src/tests/components/shared/data-list/__snapshots__/SearchWidget.test.tsx.snap
portafly/src/tests/components/shared/data-list/examples/DataListTable.tsx
portafly/yarn.lock

Upgrades `@patternly/react-core` to the latest version and fixes broken component.

Upgrade @patternfly/react-core

---

portafly/doc/ux_specs/index.md
portafly/doc/ux_specs/product/applications/index.md

Update UX specs for Product > Applications index page
https://issues.redhat.com/browse/THREESCALE-4693

Update Product > Applications index page UX specs

---

portafly/doc/ux_specs/accounts/account_overview.md
portafly/doc/ux_specs/index.md

Add UX specs for Account overview page
https://issues.redhat.com/browse/THREESCALE-5421

Add UX specs for Account overview page

---

portafly/doc/ux_specs/accounts/account-applications-index.md
portafly/doc/ux_specs/index.md

Add UX specs for Account > Applications index page
https://issues.redhat.com/browse/THREESCALE-5423

Add UX specs for Account > Applications index page

---

app/decorators/account_decorator.rb
app/helpers/buyers/accounts_helper.rb
app/views/buyers/accounts/_search_results.html.slim
app/views/buyers/accounts/bulk/_selected_accounts.html.erb
app/views/buyers/accounts/show.html.slim
app/views/buyers/applications/bulk/_selected_applications.html.erb
app/views/buyers/service_contracts/bulk/_selected_contracts.html.erb
test/decorators/account_decorator_test.rb

part of [THREESCALE-5541](https://issues.redhat.com/browse/THREESCALE-5541)
Depends on https://github.com/3scale/porta/pull/2024. It is its base now because I see that the other PR would fail if this one is lacking.

Use AccountDecorator with admin_user_display_name

---

app/views/provider/admin/dashboards/widgets/_service_navigations.html.slim

The service navigations widget is not being loaded correctly. 
https://issues.redhat.com/browse/THREESCALE-5511

[dashboard#service_nagigations] fix ajax loading

---

portafly/doc/ux_specs/index.md
portafly/doc/ux_specs/product/overview.md

> Add UX specifications for the Product overview page
JIRA: https://issues.redhat.com/browse/THREESCALE-5420

ux specs for product overview page

---

app/assets/stylesheets/provider/themes/wizard.scss
app/views/provider/admin/onboarding/wizard/info/explain.html.slim
app/views/provider/admin/onboarding/wizard/request/new.html.slim

closes https://issues.redhat.com/browse/THREESCALE-5353
`/` is now visually part of request in intro screen:
**before:**
**after:**
`/` is now visually part of request in request screen:
**before:**
**after:**
(path is still pre-written in request and not part of api get method)

fix wizard (for apiap)

---

portafly/src/types/account.d.ts

🐛 Portafly - Fixes bug in typings

---

portafly/doc/ux_specs/accounts/account_applications_index.md
portafly/doc/ux_specs/accounts/account_overview.md
portafly/doc/ux_specs/accounts/index.md
portafly/doc/ux_specs/index.md
portafly/doc/ux_specs/product/overview.md

To fix some broken links in portafly docs
None
Click in the links

Fix broken links in portafly docs

---

portafly/doc/ux_specs/global_components/modal.md
portafly/doc/ux_specs/product/overview.md

Move UX specs for delete confirmation modal into global modal UX specs file

UX specs for delete confirmation modal

---

.circleci/config.yml
portafly/package.json
portafly/yarn.lock

`yarn build` is broken!
I took a look at the latest RCA and compared the package.json and configuration.
**TODO**

Fixes Portafly build script

---

app/models/proxy.rb
config/locales/en.yml
test/integration/user-management-api/services/proxy/policies_test.rb

https://issues.redhat.com/browse/THREESCALE-1059

[PoliciesConfig] validate json

---

portafly/doc/ux_specs/global_components/modal.md
portafly/doc/ux_specs/product/overview.md

* Add spec to remove API name from dialog title
* Add spec to trigger validation error on _onType_

[UX specs] Fixes to delete modal

---

portafly/src/tests/components/pages/accounts/utils/__snapshots__/accountsTableDataFactory.test.tsx.snap
portafly/src/tests/components/pages/applications/utils/__snapshots__/applicationsTableDataFactory.test.ts.snap

fix failing tests for https://github.com/3scale/porta/pull/2060

fix failing tests for #2060

---

db/migrate/20200622134955_remove_service_columns.rb
db/migrate/20200622162824_remove_access_token_columns.rb
db/migrate/20200622163332_remove_pricing_rule_columns.rb
db/migrate/20200622163431_remove_proxy_columns.rb
db/migrate/20200622163553_remove_user_columns.rb
db/migrate/20200629103209_remove_settings_end_user_columns.rb
db/migrate/20200629104436_remove_plans_end_user_columns.rb
db/migrate/20200629105653_remove_cinstances_end_user_columns.rb
db/migrate/20200629110238_remove_account_columns.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/models/access_token_test.rb

Depends on https://github.com/3scale/porta/pull/1978 & https://github.com/3scale/porta/pull/2002
Part of [THREESCALE-2635](https://issues.redhat.com/browse/THREESCALE-2635)

Remove columns from the DB for THREESCALE-2635

---

app/models/access_token.rb
app/models/account.rb
app/models/contract.rb
app/models/plan.rb
app/models/pricing_rule.rb
app/models/proxy.rb
app/models/service.rb
app/models/settings.rb
app/models/user.rb
test/unit/fields/fields_test.rb

Depends on https://github.com/3scale/porta/pull/1979
To be merged after actually having removed all the columns 😄 
Closes [THREESCALE-2635](https://issues.redhat.com/browse/THREESCALE-2635)

Remove all code of ignoring columns

---

.dockerignore

The following directories were added to .dockerignore, thus pereventing them from being copied when we do `ADD . ./`.
- portafly
- public/packs*
- flow-types
Portafly is not needed for porta and it has now its own Dockerfile and resources to be deployed as a separate component. As for the required files (e.g. `public/packs`), they will be regenerated in build time when we do `yarn install` and precompile the Rails assets.
```
$ docker images
REPOSITORY                    TAG                       IMAGE ID            CREATED             SIZE
system-os                     0.0.5                     e36eea1c7a67        10 minutes ago      7.76GB
centos/ruby-25-centos7        latest                    e480c055bd79        2 weeks ago         578MB
$ docker history system-os:0.0.5
IMAGE …
```

Container image size optimization

---

portafly/doc/ux_specs/product/edit_product.md

Add inline help UX specs for system name input field

[UX specs] Update Edit product page specs

---

portafly/doc/ux_specs/product/create_product.md

Add inline help specs for System name input field

[UX specs] Update Create product page specs

---

app/models/ability.rb
test/unit/abilities/ability_test.rb

I need for https://github.com/3scale/porta/pull/2099/ and many other PRs like that one.

Check can? the same way for Decorators as for their ActiveRecord Models

---

app/controllers/provider/admin/account/users_controller.rb
app/decorators/application_decorator.rb
app/decorators/paginating_decorator.rb
app/views/provider/admin/account/users/index.html.slim
test/integration/provider/admin/account/users_controller_test.rb

Provider::Admin::Account::Users#index => all users with td[1] display_name link

---

portafly/src/i18n/locales/en/product.yml
portafly/src/i18n/locales/en/product/edit_product.yml
portafly/src/i18n/locales/en/shared.yml

Microcopy for Product > Edit product
[THREESCALE-5640](https://issues.redhat.com/browse/THREESCALE-5640)

5640-Product_EditProduct microcopy for Product > Edit Product

---

app/controllers/buyers/users_controller.rb
app/views/buyers/users/edit.html.erb
app/views/buyers/users/index.html.erb
app/views/buyers/users/show.html.erb
test/integration/buyers/users_controller_test.rb

Move '.decorate' Views->Controller for 'admin_buyers_user*' paths

---

app/controllers/buyers/accounts/bulk/base_controller.rb
app/views/buyers/accounts/bulk/_selected_accounts.html.erb
test/integration/buyers/accounts/bulk/change_plans_controller_test.rb

Move '.decorate' from View to Controller for buyers/accounts/bulk/_selected_accounts

---

app/controllers/buyers/accounts_controller.rb
app/views/buyers/accounts/_search_results.html.slim
app/views/buyers/accounts/show.html.slim
test/integration/buyers/accounts_controller_test.rb

Move 'decorate' Views=>Controller for Buyers::AccountsController

---

app/controllers/buyers/users_controller.rb
app/lib/fields/fields.rb
app/views/buyers/users/edit.html.erb
app/views/buyers/users/index.html.erb
app/views/buyers/users/show.html.erb
test/integration/buyers/users_controller_test.rb

This request by Gui: https://github.com/3scale/porta/pull/2104#issuecomment-669966196

Get rid of InheritedResources for Buyers::UsersController

---

test/decorators/proxy_config_decorator_test.rb

Oops! _Copy&Paste_ consequences... 🙈

Rename test class to ProxyConfigDecoratorTest

---

app/controllers/application_controller.rb
app/controllers/provider/admin/user/base_controller.rb
app/lib/decorator_additions.rb
app/models/ability.rb
app/views/provider/admin/accounts/suspended.html.slim
app/views/provider/admin/onboarding/wizard/info/intro.html.slim
app/views/shared/_service_access.slim
app/views/shared/provider/_header.html.slim

Closes [THREESCALE-5812](https://issues.redhat.com/browse/THREESCALE-5812)
Review carefully, please. This can be risky 😄

Decorate current_user and current_account before reaching the views.

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock

Bump codecov to v0.2.6

---

app/views/provider/admin/onboarding/wizard/request/edit.html.slim
app/views/provider/admin/onboarding/wizard/request/new.html.slim

Wizard test screen displays double slash
https://issues.redhat.com/browse/THREESCALE-5768
1. Go to wizard page: `/p/admin/onboarding/wizard/intro`
2. Advance to the step "Use your Backend in your Product" (`http://provider-admin.example.com:3000/p/admin/onboarding/wizard/connect/new`)
3. Advance to next step: `p/admin/onboarding/wizard/request/new`
4. Go back to step 2 and try with different options: `""`, `"/"`, `"/something"`
**BEFORE:**
**AFTER:**

Remove double slash in wizard

---

portafly/doc/ux_specs/global_components/empty_states.md
portafly/doc/ux_specs/index.md

Add UX specs for Empty states
https://issues.redhat.com/browse/APPDUX-434

[UX specs] Empty states global components

---

portafly/doc/ux_specs/backend/add_backend_to_product.md
portafly/doc/ux_specs/index.md

Add UX specs for 'Add backend to product' page
https://issues.redhat.com/browse/APPDUX-434

[UX specs] Add backend to product page

---

app/controllers/admin/api/api_docs_services_controller.rb
config/routes.rb
doc/active_docs/Account Management API.json
test/integration/admin/api/api_docs_services_controller_test.rb

Closes [THREESCALE-5826](https://issues.redhat.com/browse/THREESCALE-5826)

[Admin API] ActiveDocs Spec Read

---

config/initializers/oracle.rb

Fix for https://app.circleci.com/pipelines/github/3scale/porta/13712/workflows/b9c2e0ba-0fda-4974-9a8e-a0e08c5efa53/jobs/184671
We'd better consider updating activerecord-oracle_enhanced-adapter soon anyway.

Fix OracleEnhancedAdapter log issue

---

portafly/src/i18n/locales/en/product.yml

UI Strings for Product > Applications index
[THREESCALE-4877](https://issues.redhat.com/browse/THREESCALE-4877)

4877-Product_ApplicationsIndex UI Strings

---

portafly/src/i18n/locales/en/account_settings/overview/edit_account_details.yml

> Lists UI Strings for Account settings > Overview > Edit account details
> `fixes #<4989>`
> None
- UI Strings Jira: [THREESCALE-4989](https://issues.redhat.com/browse/THREESCALE-4989)
- Most of the strings contain text similar to the mockup.
- For strings different to the mockup, you will see this tag: [PROPOSED]

4989-Account_Overview_Edit: Edit account details form.

---

INSTALL.md
config/examples/domain_substitution.yml

> The install.md file still refers to example.com, which is no longer in use. 
Hence replacing this with the new domain link.
> Closes [THREESCALE-5801](https://issues.redhat.com/browse/THREESCALE-5801)
> Run Porta locally and use the new links to access portals.

[Readme] Replacing domain link with 3scale.localhost

---

app/assets/javascripts/provider/cms_toolbar_v2.js

Fix a bug where is not possible to switch between draft and published versions in the Developer Portal.
https://issues.redhat.com/browse/THREESCALE-5935
Create a Draft and Published versions on any page in the dev portal, 
Go to the Dev Portal
You must be able to switch
**Draft:**
**Published:**

Bugfix: switch between draft and published in dev portal

---

script/oracle/install-instantclient-packages.sh

If one of the instantclient-basic or basiclite is already present,
then install it.
Otherwise install instantclient-basic

[oracle] Ability to install instantclient-basic

---

MAINTAINERS

2020-09 Update Maintainers

---

app/indices/topic_index.rb

closes https://issues.redhat.com/browse/THREESCALE-5939

[TopicIndex] get first 8M chars of sphinx_post_bodies

---

app/decorators/message_decorator.rb
app/decorators/message_recipient_decorator.rb

Closes https://issues.redhat.com/browse/THREESCALE-6105

THREESCALE-6105 Fix nil.decorate

---

app/assets/stylesheets/provider/_service_access.scss
app/helpers/whitelabel/admin/accounts/users_helper.rb
app/javascript/src/Users/components/FeaturesFieldset.jsx
app/javascript/src/Users/components/RoleRadioGroup.jsx
app/javascript/src/Users/components/ServicesFieldset.jsx
app/javascript/src/Users/utils/index.jsx
app/models/admin_section.rb
app/views/provider/admin/account/users/_form.html.erb
app/views/provider/admin/account/users/index.html.slim
config/locales/en.yml
features/users/permissions.feature
package.json
spec/javascripts/Users/components/FeaturesFieldset.spec.jsx
spec/javascripts/Users/components/ServicesFieldset.spec.jsx
test/unit/admin_section_test.rb
yarn.lock

The labels on the member permission page are vague and incomplete. Although our permissions system needs structural improvements, until that moment comes, it's better to be as clear and complete as possible what each permission checkbox does.
https://issues.redhat.com/browse/THREESCALE-6144
You need to have multiple users
Go to Account settings > Users > Listing
Create a new user or edit an existing one

Updating label for member permissions

---

app/controllers/provider/admin_controller.rb
app/models/onboarding.rb

This is a follow-up of https://github.com/3scale/porta/pull/2178
Removing remnant code from bubbles in onboarding model
The Onboarding model can't be totally removed because is needed for the wizard
https://issues.redhat.com/browse/THREESCALE-6040

Removing bubbles code from onboarding

---

test/integration/admin/api/services_controller_test.rb

This reverts commit 56f99c34ede3a7d63bd59981bbc448dfdaf8db81.
https://github.com/3scale/porta/pull/2156#discussion_r503959285

[Bugfix][Test][Oracle] Test IDs with 'select' + 'map' instead of 'pluck'

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock

1. Adds yabeda-rails for some standard Rails Prometheus metrics
2. Removes yabeda-prometheus, redundant since we've introduced yabeda-prometheus-mmap
- Total web requests received: `rails_requests_total`
- Web request duration: `rails_request_duration` (in seconds)
- Views rendering duration: `rails_view_runtime` (in seconds)
- DB request duration: `rails_db_runtime` (in seconds)
See https://github.com/yabeda-rb/yabeda-rails#metrics
Effectively, merging this PR will cause an increase of the number of metric counts served by the endpoint `http://localhost:#{prometheus_port}/yabeda-metrics` of the order of the number combinations between number of exposed routes (roughly number of Rails controllers ⨉ actions), number of response format (html, json, etc) and number of HTTP response codes of …

Rails Prometheus metrics with yabeda-rails

---

app/controllers/admin/api/account/proxy_configs_controller.rb
app/controllers/admin/api/services/proxy/configs_controller.rb
doc/active_docs/Account Management API.json

Documentation for the new endpoint of [THREESCALE-4528](https://issues.redhat.com/browse/THREESCALE-4528)

ActiveDocs for Proxy Configs List (Provider)

---

features/old/api/alerts.feature
features/old/api/plans/plan.feature
features/old/authorization/provider_plans_section.feature

Fixing cukes for https://github.com/3scale/porta/pull/2194

Fixing some more cukes

---

features/old/menu/dashboard.feature
features/step_definitions/applications/applications_steps.rb

> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`

More cukes

---

features/old/stats/provider_side.feature

> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`

Appdux 462 new dashboard fix cukes 03

---

features/old/accounts/invitations.feature

Cuke Fix features/old/accounts/invitations.feature:83

---

app/models/account.rb
test/unit/account_test.rb

Part of [THREESCALE-4483](https://issues.redhat.com/browse/THREESCALE-4483)

[Bugfix] NoMethodError: undefined method 'multiple_applications' for nil:NilClass

---

app/javascript/src/Dashboard/components/BackendsWidget.jsx
app/javascript/src/Dashboard/components/ProductsWidget.jsx

Rename Dashboard cards "recently updated" column

---

app/javascript/packs/vertical_nav.js
app/javascript/src/Navigation/components/VerticalNav.jsx
app/javascript/src/Navigation/styles/VerticalNav.scss
app/views/shared/provider/navigation/_vertical_nav.html.slim
spec/javascripts/Navigation/VerticalNav.spec.jsx

Needed signed commits, Ref #2229

Add current API title above left nav

---

app/models/account/buyer_methods.rb
app/models/cinstance.rb
app/models/contract.rb
app/models/user.rb
test/integration/buyers/accounts_controller_test.rb
test/unit/contract_test.rb

IMO this is what it should do.
I also took the chance to do a mini-refactor 😄 
If everyone agrees, I will add unit tests to cover all cases.

[Only some Unit Tests left] THREESCALE-1608 without member users accessing to buyers without cinstances

---

app/models/contract.rb
app/models/user.rb
test/unit/contract_test.rb

[Refactor] Contract.permitted_for(user)

---

lib/tasks/backend_api.rake
test/unit/tasks/backend_api_test.rb

Because https://github.com/3scale/porta/pull/2190/files#r517471267

Remove Rake task 'destroy_orphans'

---

app/helpers/users_helper.rb
app/models/admin_section.rb
app/views/provider/admin/account/users/_form.html.erb
app/views/provider/admin/account/users/index.html.slim
config/abilities/master_admin.rb
config/abilities/provider_admin.rb
config/locales/en.yml
test/integration/provider/admin/account/users_controller_test.rb
test/unit/admin_section_test.rb

Fix summary of provider users' permission groups

---

.codeclimate.yml
.rubocop.yml
.rubocop_todo.yml
Gemfile.base
Gemfile.lock
Gemfile.prod.lock

* Update outdated settings
* Removes deprecation warnings
* Includes necessary/useful gems for development

👷 Update Codeclimate and Ruby Linters

---

app/controllers/admin/api/account/proxy_configs_controller.rb
doc/active_docs/Account Management API.json

Improve the description as suggested in https://github.com/3scale/porta/pull/2241#discussion_r519886419 😄

[Doc][API] GET Account/ProxyConfigs: Find -> Filter

---

app/controllers/api/service_plans_controller.rb
app/controllers/buyers/base_controller.rb
app/controllers/buyers/service_contracts_controller.rb
app/models/user.rb
config/abilities/provider_member.rb
test/integration/admin/api/service_plans_controller_test.rb
test/integration/buyers/service_contracts_controller_test.rb

| Resource                                | Action                                         | Required permission | Service-level access control? |
|-----------------------------------------|------------------------------------------------|-----------------|---|
| ☑︎ service plans                         | index service plans                            | plans           | Y |
|                                         | change default service plan                    | plans           | Y |
|                                         | new service plan                               | plans           | Y |
|                                         | create service plan                            | plans           | Y |
|                                         | edit service plan …

Fix member permissions for service plans and service contracts

---

app/models/service.rb
test/unit/service_test.rb

Extracted from #2230 to make smaller PRs. I need for there, but even if we end up not needing this, it can be easily reverted on its own.

Add Service#accessible?

---

.circleci/config.yml

`-Z` Exit with 1 if not successful. Default will Exit with 0
https://docs.codecov.io/docs/about-the-codecov-bash-uploader

[codecov] return 1 if not successfull

---

jest.config.js
spec/javascripts/ActiveDocs/OAS3Autocomplete.spec.jsx

Adds missing js tests to OAS3 ActiveDocs like features: autocomplete and server injection
https://issues.redhat.com/browse/THREESCALE-6138
`yarn jest`
No QA needed

Adding js tests to OAS3 ActiveDocs features

---

app/controllers/admin/api/services_controller.rb
doc/active_docs/Account Management API.json

Related to [THREESCALE-4528](https://issues.redhat.com/browse/THREESCALE-4528)

Add pagination params to ApiDocs Service List endpoint

---

app/controllers/admin/api/services/proxy/configs_controller.rb
config/routes.rb
spec/acceptance/api/configs_spec.rb
test/integration/by_sso_token_test.rb
test/integration/user-management-api/services/proxy/configs_test.rb

Reverts 3scale/porta#2279
There are people using it and we will follow a longer but safer approach 😉

Revert "Delete API endpoint /admin/api/services/proxy/configs/:environment"

---

app/assets/stylesheets/provider/_settings_box.scss
app/presenters/api/integrations_show_presenter.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
test/unit/presenters/api/integrations_show_presenter_test.rb

Closes [THREESCALE-6470: Remove test_state_modifier method](https://issues.redhat.com/browse/THREESCALE-6470)

Remove test_state_modifier method and unused styles

---

Gemfile.base
Gemfile.lock

Unbelievably, it works without problems:

Bump Stripe to 5.28.0

---

app/controllers/api/integrations_controller.rb
app/models/proxy.rb
features/step_definitions/proxy_steps.rb
test/integration/api/integrations_controller_test.rb
test/unit/proxy_test.rb

Closes [THREESCALE-6467: Remove unused code branch](https://issues.redhat.com/browse/THREESCALE-6467).

Remove unused code

---

lib/tasks/payments.rake
test/unit/tasks/payments_test.rb

Closes [THREESCALE-6525](https://issues.redhat.com/browse/THREESCALE-6525)

Remove all traces of 'adyen' from the DB

---

config/examples/rolling_updates.yml

Part of [THREESCALE-6517](https://issues.redhat.com/browse/THREESCALE-6517)

Enable RU 'stripe_elements' for everyone in Development/Test environment by default

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock

Closes [THREESCALE-6522](https://issues.redhat.com/browse/THREESCALE-6522)

Bump Activemerchant to 1.113

---

config/docker/rolling_updates.yml
openshift/system/config/rolling_updates.yml

Part of [THREESCALE-6517](https://issues.redhat.com/browse/THREESCALE-6517)

Enable RU stripe_elements for on-prem

---

app/views/payment_gateways/_stripe.html.erb

* Improves/cleanup code
* Disables submit button if card info is invalid (evaluated by Stripe)
* Adds alert to show error feedback upon submission

Adds error feedback to Credit Card Details form

---

lib/developer_portal/app/controllers/developer_portal/admin/account/authorize_net_controller.rb

Solve the possible problems in https://github.com/3scale/porta/pull/2324#discussion_r554892061 . File number 8.

Use the same cim_gateway object inside DeveloperPortal::Admin::Account::AuthorizeNetController#hosted_success

---

app/models/payment_transaction.rb

[Refactor] Call logger once inside PaymentMethod#purchase!

---

app/lib/three_scale/spam_protection/protector.rb
app/lib/three_scale/spam_protection/session_store.rb

[Hotfix] NameError (uninitialized constant ThreeScale::SpamProtection::SessionStore)

---

app/helpers/payment_details_helper.rb
lib/developer_portal/app/views/developer_portal/main_layout.html.liquid
test/helpers/payment_details_helper_test.rb

1. Do not crash if the user/account has not logged in.
2. Add test.
I've noticed by reviewing this merged PR: https://github.com/3scale/porta/pull/2334

Polish PaymentDetailsHelper#stripe_billing_address_json.

---

app/lib/three_scale/money.rb

Closes [THREESCALE-6661](https://issues.redhat.com/browse/THREESCALE-6661)

[hotfix] Can't modify frozen String in ThreeScale::Money#inspect

---

app/services/finance/stripe_payment_intent_update_service.rb
test/unit/services/finance/stripe_payment_intent_update_service_test.rb

Prevents the following from happening:
Closes [THREESCALE-6664](https://issues.redhat.com/browse/THREESCALE-6664)

Make Stripe callback idempotent

---

app/helpers/menu_helper.rb
app/helpers/vertical_nav_helper.rb
app/javascript/packs/vertical_nav.js
app/javascript/src/Navigation/components/VerticalNav.jsx
app/views/shared/provider/navigation/_vertical_nav.html.slim
app/views/shared/provider/navigation/_vertical_nav_item.html.slim
features/old/menu/account_menu.feature
features/old/menu/api_menu.feature
features/old/menu/audience_menu.feature
features/old/menu/backend_api_menu.feature
features/old/menu/buyer.feature
features/step_definitions/menu_steps.rb

* clean up
* move dataset generation into helper
* fixes console warning
* fixes Flow types

Fixes/Cleanup in Vertical Nav

---

test/factories/payment_intent.rb

Static attributes will be removed in FactoryBot 5.0. Using dynamic attributes instead.

Fix PaymentIntent factory

---

app/helpers/payment_details_helper.rb
app/javascript/packs/braintree3DSecureCustomerForm.js
app/views/payment_gateways/_braintree_customer_form.html.erb
package.json
yarn.lock

To comply with SCA, we need to add `threeDSecure` support for **Braintree**
Fixes: https://issues.redhat.com/browse/THREESCALE-6495
Part of SCA Epic: https://issues.redhat.com/browse/THREESCALE-6515
**TODOS:**
This PR handles only the first step, next steps will be handled independently
**Update dependencies:**
```
yarn clean && yarn install
```
**Enable payments option:**
By starting rails server with flag `THREESCALE_PAYMENTS_ENABLED`:
```
UNICORN_WORKERS=8 THREESCALE_PAYMENTS_ENABLED=1 RAILS_LOG_TO_STDOUT=1 bundle exec rails server
```
Or, by setting `config.three_scale.payments.enabled = true` in `config/environments/development.rb `
**Get keys from Braintree:**
Go to …

Braintree 3DSecure: store credit card

---

app/indices/topic_index.rb
config/docker/thinking_sphinx.yml
config/thinking_sphinx.yml

It will probably break search in the forum UI but at least we are not going to consume memory for nothing
Not going to fix anything, forum should be dead anyway

[sphinxsearch] Remove topic from indexation

---

app/views/emails/invoice_messenger_unsuccessfully_charged_for_buyer.text.liquid

Closes https://issues.redhat.com/browse/THREESCALE-6682

Update email text for failed payments

---

app/indices/topic_index.rb
features/old/forums/search_highlighting.feature
features/old/forums/searching.feature
test/unit/queries/proxy_rule_query_test.rb

Do not index the topic in sphinx if a post is created or modified
Related to https://github.com/3scale/deploy/pull/700 and https://github.com/3scale/porta/pull/2366

[sphinx] Do not index topic from post

---

app/javascript/packs/OAS3Autocomplete.js
app/javascript/packs/braintree3DSecureCustomerForm.js
app/javascript/src/Stats/lib/chart_manager.jsx
app/javascript/src/utilities/json-utils.jsx

Webpack dev compilation is failing due to some `console.log()` and `console.warn()` 
Throwing `new Error()` when execution must be stopped, using `console.error()` when execution should continue.
Follow-up of https://github.com/3scale/porta/pull/2371

Removing console logs and warns

---

.circleci/config.yml

Thank you Codecov team! :rocket:

[codecov] Reenable it!

---

app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
app/javascript/src/Navigation/components/ContextSelector.jsx
app/javascript/src/Navigation/styles/ContextSelector.scss
app/javascript/src/patternflyStyles/pf4Base.css
app/views/shared/provider/_header.html.slim
spec/javascripts/Navigation/ActiveMenuTitle.spec.jsx
spec/javascripts/Navigation/ContextSelector.spec.jsx
spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap

Fixing broken tests for https://github.com/3scale/porta/pull/2365

Replace context selector classes with Patternfly equivalents

---

app/javascript/src/NewService/components/NewServiceForm.jsx
app/javascript/src/NewService/components/ServiceDiscoveryForm.jsx
app/javascript/src/NewService/components/ServiceManualForm.jsx
app/javascript/src/NewService/components/ServiceSourceForm.jsx
app/views/api/services/new.html.slim
spec/javascripts/Navigation/ActiveMenuTitle.spec.jsx
spec/javascripts/NewService/NewServiceForm.spec.jsx
spec/javascripts/NewService/ServiceDiscoveryForm.spec.jsx
spec/javascripts/NewService/ServiceManualForm.spec.jsx
spec/javascripts/NewService/ServiceSourceForm.spec.jsx

Removes trails of APIAP in React files and tests
https://issues.redhat.com/browse/THREESCALE-6765
All test should pass, and nothing should break ;)

Clean up trails of APIAP in React files and tests

---

app/javascript/src/BackendApis/components/IndexPage.js
app/javascript/src/Dashboard/components/BackendsWidget.jsx
app/javascript/src/Dashboard/components/ProductsWidget.jsx
app/javascript/src/NewService/components/FormElements/FormWrapper.jsx
app/javascript/src/Products/components/IndexPage.js
app/views/provider/admin/backend_apis/new.html.slim

Implements Pendo tracking
TODO:
https://issues.redhat.com/browse/THREESCALE-6729

Implement Pendo tracking

---

features/old/providers/settings/legal_terms.feature

These test hasn't being running for a while! The file defines "Scenario Outline" which is a template, but there are no values (examples) for that template so the test cases are not detected.

⚠️ Legal terms settings features not being run

---

.circleci/config.yml

Codecov has been pwned. For security reason we decided to rotate all SSH and API keys used
https://about.codecov.io/security-update/

[circleci] Rotate 3scale-ninjabot ssh keys

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock
doc/licenses/licenses.xml

The gem version has been yanked because of some licensing issues
https://github.com/mimemagicrb/mimemagic/issues/98

[gem] Update mimemagic because of license

---

app/lib/proxy_config_affecting_changes.rb
app/models/gateway_configuration.rb
test/unit/proxy_config_affecting_changes_test.rb

When `ClientID Token Claim` or `ClientID Token Claim Type` were changed it didn't show the promote to the new staging version. `Gateway_configuration` table wasn't tracked by the `proxy_config_affecting_changes` and this PR is fixing that.
https://issues.redhat.com/browse/THREESCALE-6468

[THREESCALE-6468] Adds proxy config affecting changes to the gateway_configuration

---

config/environments/preview.rb

Preview should be the same as production environment

[preview] Do not compile assets by the webserver

---

app/models/backend_api.rb

Remove non-APIAP logic from `BackendApi`. 🚨 Also fixes a rubocop warning.
[THREESCALE-7066: Clean up backend api model unused methods](https://issues.redhat.com/browse/THREESCALE-7066)

Clean up Backend API model

---

app/presenters/api/integrations_show_presenter.rb
app/views/api/integrations/show.html.slim
test/integration/api/integrations_controller_test.rb

[THREESCALE-7067: Clean up integrations show page](https://issues.redhat.com/browse/THREESCALE-7067)

Clean up APIAP traces in integrations show page

---

app/views/api/alerts/index.html.erb
app/views/shared/applications/_listing.html.slim
app/views/shared/proxy_rules/_body_section.html.slim

**Update Product** buttons at:
- apiconfig/services/{service_id}/alerts - Search
- /apiconfig/services/{service_id}/applications - Search
- /apiconfig/services/{service_id}/proxy_rules - Search
Using same format (button instead of input)
Follow-up of https://issues.redhat.com/browse/THREESCALE-6719
Requested by QE

Products: change more inputs to pf buttons

---

app/views/provider/admin/account/invitations/_form.html.erb

More PF buttons (Account settings).
Follow-up of https://issues.redhat.com/browse/THREESCALE-6721
Requested by QE

Account settings: change more inputs to pf buttons

---

app/views/buyers/accounts/new.html.erb

More PF buttons (Audience).
Follow-up of https://issues.redhat.com/browse/THREESCALE-6717
Requested by QE

Audience: change more inputs to pf buttons

---

features/old/accounts/bulk_operations.feature
features/old/accounts/notifications.feature
features/old/applications/providers/bulk_operations.feature
features/old/messages/provider_side.feature
features/old/services/subscriptions/bulk_operations.feature

Scenarios will be fixed/refactored according to: [THREESCALE-7195: Some Scenarios are failing in CircleCI breaking the master branch](https://issues.redhat.com/browse/THREESCALE-7195)

Disable some cucumber scenarios that are failing in CI

---

app/views/sites/emails/edit.html.erb
test/functional/sites/emails_controller_test.rb

Sanitize user input before rendering
https://issues.redhat.com/browse/THREESCALE-6785

Sanitize service name

---

app/lib/stats/storage.rb
app/lib/stats/views/usage.rb
test/unit/stats/views/usage_test.rb

Adds time range validation for different granularities in the stats.
The allowed range for the granularities:
- **hour** - 90 days
- **day** - 1 year
- **month** - 10 years
https://issues.redhat.com/browse/THREESCALE-6649

Adds time range validation for the stats

---

Gemfile
Gemfile.lock
config/environments/development.rb

Makes easy to enable `letter_opener` by a simple environment variable at runtime.
```
$ LETTER_OPENER=1 bundle exec sidekiq ...
```
No issue.
- export LETTER_OPENER=1
- bundle exec sidekiq ...
- in Porta web UI invire a user
- a browser tab should open with email content present

letter_opener made easy

---

app/controllers/api/integrations_controller.rb
config/locales/en.yml

THREESCALE-7134 removing APIcast v1 obsolete #async_update

---

app/assets/stylesheets/provider/_buttons.scss
app/views/admin/fields_definitions/edit.html.erb
app/views/admin/fields_definitions/new.html.erb
app/views/buyers/account_plans/new.html.erb
app/views/buyers/accounts/_search_results.html.slim
app/views/buyers/groups/show.html.erb
app/views/buyers/invitations/new.html.erb
app/views/finance/provider/invoices/index.html.erb
app/views/provider/admin/account/logos/edit.html.slim
app/views/provider/admin/cms/builtin_legal_terms/_buttons.html.erb
app/views/provider/admin/cms/files/new.html.erb
app/views/provider/admin/cms/groups/new.html.erb
app/views/provider/admin/cms/layouts/new.html.erb
app/views/provider/admin/cms/pages/new.html.erb
app/views/provider/admin/cms/partials/new.html.erb
app/views/provider/admin/cms/redirects/_form.html.erb
app/views/provider/admin/cms/sections/new.html.erb
app/views/provider/admin/cms/switches/_switch_toggle.html.erb
app/views/provider/admin/messages/outbox/new.html.erb
app/views/sites/dns/show.html.erb
app/views/sites/emails/edit.html.erb
app/views/sites/spam_protections/edit.html.erb

More PF buttons (Audience).
https://issues.redhat.com/browse/THREESCALE-6717

Audience: pf buttons (3rd round)

---

app/models/proxy.rb

THREESCALE-7134 async_deploy methods from Proxy

---

app/models/proxy.rb
test/unit/proxy_test.rb

THREESCALE-7134 remove sanbox config methods from Proxy

THREESCALE-7134 sandbox config methods in Proxy

---

app/forms/onboarding/request_form.rb
app/models/proxy.rb
app/services/proxy_deployment_service.rb
test/integration/user-management-api/services/proxies_test.rb
test/unit/proxy_test.rb
test/unit/services/proxy_deployment_service_test.rb

>PART of   [THREESCALE-7134](https://issues.redhat.com/browse/THREESCALE-7134) Removing v1_compatible

THREESCALE-7134  Removing v1_compatible

---

app/controllers/admin/api/fields_definitions_controller.rb
app/representers/fields_definition_representer.rb
app/representers/fields_definitions_representer.rb
config/routes.rb
doc/active_docs/Account Management API.json
spec/acceptance/api/fields_definition_spec.rb

This PR adds fields definition to the admin API.
https://issues.redhat.com/browse/THREESCALE-4082

Fields definition API

---

package.json
yarn.lock

We have fixed `swagger-ui` versions to 3.25.0 in https://github.com/3scale/porta/pull/2075, because of an issue with node version in our servers.
Issue is fixed and we can finally update packages safely!
None
```
rm -rf node_modules
yarn install
```

Update swagger-ui to 3.51.1+

---

SETUP_ORACLE.md

Updates oracle setup guide

---

app/models/account.rb
app/models/account/provider_methods.rb

Removes code part of the proxy conf columns.
https://issues.redhat.com/browse/THREESCALE-7134

[THREESCALE-7134] Remove proxy conf columns code part

---

app/views/api/services/forms/_usage_rules.html.slim
config/locales/en.yml

This PR is a follow up of [#2238 ](https://github.com/3scale/porta/pull/2238) that includes the suggested changes from [#2238 ](https://github.com/3scale/porta/pull/2238). 
Refer to original issues for complete description of current behaviour.
Fixes [THREESCALE-6295](https://issues.redhat.com/browse/THREESCALE-6295) and [THREESCALE-6296](https://issues.redhat.com/browse/THREESCALE-6296).
Please refer to [#2238 ](https://github.com/3scale/porta/pull/2238).
**Notes**:
There are no UI tests included. If we should include them @3scale/system-ux could you please let us know where we should write the tests? Thanks.

Usage rules fix

---

.circleci/config.yml
.gitmodules
INSTALL.md

Removes docker-gateway submodule and makes the porta submodule free.

Removes submodules from porta codebase

---

.circleci/config.yml
Dockerfile
openshift/system/Dockerfile

Upgrading to ruby 2.6
Unexpectedly passing mysql tests ... :tada: 
Needs https://github.com/3scale/system-builder/pull/27

Using ruby 2.6

---

Makefile

Add support in Makefile for running Oracle container with Podman.
Also add some Oracle related comments to codebase.

support running Oracle with Podman

---

app/views/buyers/service_contracts/edit.html.erb
app/views/buyers/users/edit.html.erb

Use patternfly buttons instead of inputs
Follow-up of https://issues.redhat.com/browse/THREESCALE-6717
https://issues.redhat.com/browse/THREESCALE-6717

Audience: more pf buttons

---

spec/javascripts/Stats/applications_selector.spec.js
spec/javascripts/Stats/applications_table.spec.js
spec/javascripts/Stats/chart_manager.spec.js
spec/javascripts/Stats/csv_link.spec.js
spec/javascripts/Stats/menu.spec.js
spec/javascripts/Stats/methods_table.spec.js
spec/javascripts/Stats/metrics_selector.spec.js
spec/javascripts/Stats/metrics_source.spec.js
spec/javascripts/Stats/state.spec.js
spec/javascripts/Stats/store.spec.js
spec/javascripts/Stats/top_apps_help_text.spec.js

Removing jQuery from js tests, when possible.
Some tests can't be updated right now, since the (legacy) components being tested depend a lot on jQuery. The proper way should be to refactor components and tests, removing jQuery from both.
Fixes https://issues.redhat.com/browse/THREESCALE-7344
Subtask of https://issues.redhat.com/browse/THREESCALE-7193
```
yarn jest
```

Removing jQuery from js tests, when possible

---

INSTALL.md

actualize Fedora installation instructions

---

app/javascript/packs/validateSignup.js
app/lib/three_scale/spam_protection/protector.rb
features/old/signup/spam_protection.feature
features/step_definitions/capcha_steps.rb
lib/developer_portal/app/views/developer_portal/signup/show.html.liquid
lib/developer_portal/lib/liquid/filters/rails_helpers.rb

Dev Portal Signup form is missing form validation and captcha checks, it's possible to send the form totally empty.
This PR adds:
- Form validation
- Captcha success checks
- Submit is disabled until form is valid and captcha is OK
- If captcha is disabled, it just checks form inputs are valid
https://issues.redhat.com/browse/THREESCALE-6695
**In Admin Portal**
Go to **Audience > Developer Portal > Spam Protection**
- Select "**Always**" and save
- You need to get your captcha keys (RECAPTCHA_PUBLIC_KEY and RECAPTCHA_PRIVATE_KEY) from Google, and use them as env vars
- See: https://www.google.com/recaptcha/admin/create, and https://access.redhat.com/documentation/en-us/red_hat_3scale_api_manag …

Adding form validation and captcha to Dev Portal signup form

---

Gemfile
Gemfile.lock

We should not add that to the Gemfile

Remove solargraph

---

Gemfile.lock

Fixing https://github.com/minitest-reporters/minitest-reporters/issues/305

[gem] Update minitest-reporters

---

app/models/plan.rb
test/remote/payment_gateways_test.rb
test/unit/plan_test.rb

**Summary**
```diff
- BigDecimal.new(...)
+ BigDecimal(...)
```
**JIRA**
[THREESCALE-7539: Resolve Cucumber deprecation warnings](https://issues.redhat.com/browse/THREESCALE-7539)

Fix BigDecimal deprecation

---

app/javascript/src/Plans/components/ApplicationPlansTableCard.jsx
app/javascript/src/Plans/components/DefaultPlanSelectCard.jsx
app/javascript/src/utilities/ajax.js

Refactor utils ajax 2

---

app/javascript/src/BackendApis/components/ProductsUsedListCard.jsx
app/javascript/src/Products/components/BackendsUsedListCard.jsx
app/views/api/services/cards/_backends_table.html.slim
app/views/provider/admin/backend_apis/show.html.slim

[THREESCALE-7044: [UI Strings] Improve list of Backends in Product overview page](https://issues.redhat.com/browse/THREESCALE-7044)

Product and Backend overview microcopy

---

app/models/account/provider_methods.rb

THREESCALE-5010 - upgrade rails. Order of declarations is stricter in 5.1 so we need to rearrange a little.

declarations order of Account model

---

app/representers/proxy_representer.rb
test/integration/admin/api/services/proxies_controller_test.rb

supercedes #2625 by adding a test. Also can't run tests for the other PR.
see https://issues.redhat.com/browse/THREESCALE-7605

[THREESCALE-7605] Fix type of policies config returned by the proxy

---

app/javascript/src/Navigation/components/ContextSelector.jsx
spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap

Removes the hash `#context-menu` from URLs, when opening the Context menu
https://issues.redhat.com/browse/THREESCALE-7648

Removing #context-menu from urls

---

public/images/3scale-logo-white.png
public/images/add.png
public/images/cross.png
public/images/email.png
public/images/img_close.png
public/images/long_bg.png
public/images/pencil.png
public/images/powered_by_logo.png
public/images/questionPassive.png
public/images/tick.png
public/images/v2/questionClose.png
public/images/v2/questionPassive.png
public/stylesheets/colorbox/colorbox.css

Those lead to nowhere ... pruning them

[public/assets] Removing non-existent symlinks

---

test/integration/master/api/finance/accounts/billing_jobs_controller_test.rb
test/integration/master/api/finance/billing_jobs_controller_test.rb
test/integration/master/api/providers_controller_integration_test.rb
test/integration/master/events_importer_test.rb
test/integration/master/providers/plans_controller_test.rb

Update/refactor tests at test/integration/master

---

test/integration/finance/api/invoices_controller_test.rb

Update/refactor tests at test/integration/finance

---

test/integration/user-management-api/account_plan_features_test.rb

Update/refactor test/integration/user-management-api/account_plan_features_test

---

test/integration/stats/api/applications_test.rb
test/integration/stats/applications_test.rb
test/integration/stats/authentication_test.rb
test/integration/stats/clients_test.rb
test/integration/stats/data/backend_apis_controller_test.rb
test/integration/stats/data/base_controller_test.rb
test/integration/stats/data/requests_to_api_test.rb
test/integration/stats/services_test.rb

Update/refactor tests at test/integration/stats

---

test/integration/developer_portal/admin/account/payment_details_base_controller_test.rb
test/integration/developer_portal/admin/applications/referrer_filters_controller_test.rb
test/integration/developer_portal/admin/applications_controller_test.rb
test/integration/developer_portal/signup_test.rb

Update/refactor tests at test/integration/developer_portal

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/initializers/browser_modern_rules.rb

Updates Browser gem to version `5.0.0`. It's a follow up  based on this PR https://github.com/3scale/porta/pull/2621

Updates Browser gem to version 5.0.0

---

test/integration/finance/api/invoices_controller_test.rb

Basically make them fail first with correct status code (2XX) when `onpremises: false`
`rails test test/integration/finance/api/invoices_controller_test.rb -n /MasterOnPremises/`
Otherwise the tests are testing nothing.
Also fixes other deprecation warning
Relates to https://github.com/3scale/porta/pull/2671

Make tests relevant

---

test/unit/application_keys_test.rb
test/unit/referrer_filters_test.rb

Leftover code that needs to be fixed.
https://github.com/3scale/porta/pull/2695

Fixes leftover deprecation of association reload

---

test/integration/user-management-api/accounts_test.rb

Update/refactor integrations/user-management-api/account_test

---

test/integration/user-management-api/active_docs_test.rb

Update/refactor integrations/user-management-api/active_docs_test

---

test/integration/user-management-api/account_plans_test.rb

Update/refactor integrations/user-management-api/account_plan_test

---

.github/workflows/fast-forward-candidate-branch.yml

So we are closer to automation for candidate release

Candidate button creates the new branch if it does not exist

---

.github/workflows/fast-forward-candidate-branch.yml

By default it will be candidate

Generalize the action to take stable as well

---

.github/workflows/fast-forward-candidate-branch.yml

Fix typo for fast forward action

---

test/integration/user-management-api/application_plan_features_test.rb
test/integration/user-management-api/application_plan_limits_test.rb
test/integration/user-management-api/application_plan_metric_limits_test.rb
test/integration/user-management-api/application_plan_metric_pricing_rules_test.rb
test/integration/user-management-api/application_plan_pricing_rules_test.rb
test/integration/user-management-api/application_plans_test.rb

Update/refactor integrations/user-management-api/application_plan tests 

---

app/models/profile.rb

Fixes profile model to throw abort when validation fails.

Fixes profile test which saves profile withou account

---

lib/developer_portal/lib/liquid/drops/message.rb
test/unit/liquid/drops/message_drop_test.rb

Guard from truncate on nil NilClass

---

Makefile

Makes sure that `docker start oracle-database` won't print errors if the container doesn't exist.
Also runs the container in detached mode.
Those changes are for better integration with porta-dev-tools

Run oracle database in detached mode 

---

test/unit/alert_test.rb

Fixed alert test

---

test/unit/rails_sqli_test.rb

Fixed error by replacing the removed method sanitize

replaced a removed method sanitize

---

test/unit/three_scale/api/responder_test.rb

[THREESCALE-5010] fix deprecated render :text in test

---

app/models/payment_intent.rb
db/migrate/20211109141544_remove_payment_intent_id.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Removes unused column and index from `payment_intent` table

Removes payment intent id column and index

---

test/integration/user-management-api/applications_test.rb

Update/refactor integrations/user-management-api/applications

---

app/models/message.rb
test/integration/notifications_test.rb
test/integration/provider/admin/applications/applications_controller_test.rb
test/unit/cinstance_test.rb
test/unit/events/importers/alert_importer_test.rb
test/unit/logic/plan_changes_test.rb
test/unit/message_test.rb
test/unit/messengers/plans_messenger_test.rb

Part of THREESCALE-7574 #comment we split it into multiple pull-request so it is easier to review

[email-async] Messages are sent asynchronously

---

app/models/proxy.rb
test/unit/proxy_test.rb

Public Base URL for a 3scale-managed gateway allows localhost domain
https://issues.redhat.com/browse/THREESCALE-7149

3scale-managed gateway allows localhost domain

---

app/views/provider/admin/backend_apis/forms/_naming.html.slim

Making required `Name` and `Private Base URL` fields in **New Backend** form, to prevent submitting empty form.
Main PR: https://github.com/3scale/porta/pull/2646

Make required Name and Private Base URL fields in New Backend form

---

app/controllers/stats/data/services_controller.rb
test/integration/stats/data/service_controller_test.rb

Fixes regression introduced by refactoring and upgrading everything to be rails 5.1 compatible.
https://issues.redhat.com/browse/THREESCALE-7884

[THREESCALE-7884] Fix service top applications endpoint

---

test/functional/finance/provider/line_items_controller_test.rb

This PR fix deprecated positional arguments in functional finance test.
Fixed rubocops

THREESCALE-7852 fixed functional finance test

---

test/functional/developer_portal/admin/account/account_plans_controller_test.rb
test/functional/developer_portal/admin/account/braintree_blue_controller_test.rb
test/functional/developer_portal/admin/account/ogone_controller_test.rb
test/functional/developer_portal/admin/account/plan_changes_controller_test.rb
test/functional/developer_portal/admin/applications/keys_controller_test.rb
test/functional/developer_portal/admin/contracts_controller_test.rb
test/functional/developer_portal/admin/messages/outbox_controller_test.rb
test/functional/developer_portal/admin/plans_widget_controller_not_requiring_credit_card_test.rb
test/functional/developer_portal/admin/plans_widget_controller_requiring_credit_card_test.rb
test/functional/developer_portal/admin/service_contracts_controller_test.rb
test/functional/developer_portal/search_controller_test.rb

This PR fix deprecated positional arguments in functional developer_portal test.
Fixed rubocops

THREESCALE-7852 Fixed functional developer_portal test cases

---

test/functional/admin/api/cms/templates_controller_test.rb
test/functional/admin/api/credit_cards_controller_test.rb
test/functional/admin/api/nginxes_controller_test.rb
test/functional/admin/api/services/mapping_rules_controller_test.rb
test/functional/admin/upgrade_notices_controller_test.rb

This PR fix deprecated positional arguments in functional admin test.
Fixed rubocops

THREESCALE-7852 fixed functional admin test

---

test/functional/partners/providers_controller_test.rb
test/functional/partners/users_controller_test.rb

This PR fix deprecated positional arguments in functional partners test.
Fixed rubocops

THREESCALE-7852 Fixed functional partners test

---

test/functional/stats/api/applications_controller_test.rb
test/functional/stats/api/services_controller_test.rb
test/functional/stats/response_code_controller_test.rb
test/functional/stats/usage_controller_test.rb

This PR fix deprecated positional arguments in functional stars test.
Fixed rubocops

THREESCALE-7852 Fixed functional stats test

---

test/functional/master/api/providers_controller_test.rb
test/functional/master/api/services_controller_test.rb
test/functional/master/devportal/auth_controller_test.rb

This PR fix deprecated positional arguments in functional master test.
Fixed rubocops

THREESCALE-7852 Fixed functional master test

---

app/javascript/src/NewApplication/components/ApplicationPlanSelect.jsx
app/javascript/src/NewApplication/components/BuyerSelect.jsx
app/javascript/src/NewApplication/components/NewApplicationForm.jsx
app/javascript/src/NewApplication/components/ProductSelect.jsx
app/javascript/src/NewApplication/components/ServicePlanSelect.jsx
app/views/api/applications/index.html.slim
app/views/api/applications/new.html.slim
app/views/buyers/applications/index.html.slim
app/views/buyers/applications/new.html.slim
app/views/provider/admin/applications/index.html.slim
app/views/provider/admin/applications/new.html.slim
app/views/shared/applications/_listing.html.slim
features/api/applications/index.feature
features/buyers/applications/index.feature
features/old/api/applications/create_application.feature
features/old/applications/buyers/application_management.feature
features/old/applications/providers/search.feature
features/old/buyers/applications/create_application.feature
features/old/provider/admin/applications/create_application.feature
features/step_definitions/applications/applications_steps.rb
script/stress-test/provider_clicking.rb
spec/javascripts/NewApplication/components/NewApplicationForm.spec.jsx

Updates strings and texts in Applications index and New Application form
[THREESCALE-7022: [UI Strings] Add 'Create new Application' flow to Audience > Applications index](https://issues.redhat.com/browse/THREESCALE-7022)
**Verification**

🌐 Updates "New Application" microcopy

---

test/functional/provider/admin/api_docs/specs_controller_test.rb
test/functional/provider/admin/cms/pages_controller_test.rb
test/functional/provider/admin/dashboard/new_accounts_controller_test.rb
test/functional/provider/admin/dashboard/potential_upgrades_controller_test.rb
test/functional/provider/admin/dashboard/service/integration_errors_controller_test.rb
test/functional/provider/admin/dashboard/service/top_traffic_controller_test.rb
test/functional/provider/admin/messages/bulk/trash_controller_test.rb
test/functional/provider/admin/messages/outbox_controller_test.rb
test/functional/provider/admin/onboarding/wizard/api_controller_test.rb
test/functional/provider/admin/user/notification_preferences_controller_test.rb
test/functional/provider/admin/user/personal_details_controller_test.rb
test/functional/provider/domains_controller_test.rb
test/functional/provider/passwords_controller_test.rb
test/functional/provider/signups_controller_test.rb

This PR fix deprecated positional arguments in functional provider test.
Fixed rubocops

THREESCALE-7852 Fixed functional provider test

---

test/integration/user-management-api/applications_test.rb

Revert "Update/refactor integrations/user-management-api/applications"

---

test/integration/user-management-api/buyers_users_test.rb

Update/refactor integrations/user-management-api/buyers_users

---

test/functional/forums/public/topics_controller_test.rb

This PR fix deprecated positional arguments in functional forums test.
Fixed rubocops

THREESCALE-7852 Fixed functional forums test

---

test/integration/admin/api_docs/account_api_docs_controller_test.rb
test/integration/admin/cms/switches_controller_test.rb

Fixes leftover in `integration/admin` tests that have different failures

[integration/admin] Fixing xhr and parameter name in tests

---

test/integration/developer_portal/invitation_signup_test.rb
test/integration/developer_portal/swagger/spec_controller_test.rb
test/integration/finance/api/line_items_controller_test.rb

Upgraded and fixed tests for developer and finance.

Upgrade integration/(developer/finance) tests

---

app/models/account/states.rb
test/integration/developer_portal/login_test.rb
test/unit/account/states_test.rb

[email-async] Account state changes will enqueue notification

---

test/integration/cms/api/templates_test.rb

Fixes and refactors template test. Part of rails upgrade.

[integration/cms] Fix and refactor of integration template test

---

test/integration/user-management-api/base_controller_test.rb
test/integration/user-management-api/credit_cards_test.rb
test/integration/user-management-api/messages_test.rb
test/integration/user-management-api/nginx_test.rb
test/integration/user-management-api/policies_test.rb
test/integration/user-management-api/provider_features_test.rb
test/integration/user-management-api/providers_test.rb
test/integration/user-management-api/service_features_test.rb
test/integration/user-management-api/service_metric_methods_test.rb
test/integration/user-management-api/service_metrics_test.rb
test/integration/user-management-api/service_plan_features_test.rb
test/integration/user-management-api/service_plans_test.rb
test/integration/user-management-api/services/mapping_rules_test.rb
test/integration/user-management-api/services/proxies_test.rb
test/integration/user-management-api/services/proxy/policies_test.rb
test/integration/user-management-api/services_test.rb
test/integration/user-management-api/signup_test.rb
test/integration/user-management-api/sso_tokens_test.rb
test/integration/user-management-api/users_test.rb
test/integration/user-management-api/web_hooks_failures_test.rb

Update/refactor rest of tests in integrations/user-management-api

---

app/controllers/stats/data/services_controller.rb
test/integration/stats/data/service_controller_test.rb

Fixes THREESCALE-7884 for 2.11.1 release.
https://issues.redhat.com/browse/THREESCALE-7884

[THREESCALE-7884] [2.11-stable] Fix service top applications endpoint

---

app/controllers/provider/signups_controller.rb

Permits all params for the signups_controller to be compatible with rails 5.1

[Rails 5.1] Permit all params in the signups_controller

---

app/controllers/admin/api/sso_tokens_controller.rb
app/controllers/api/errors_controller.rb
app/controllers/api/plan_copies_controller.rb
app/controllers/api/services_controller.rb
app/controllers/application_controller.rb
test/integration/api/access_tokens_test.rb
test/integration/api/alerts_controller_test.rb
test/integration/api/errors_controller_test.rb
test/integration/api/integrations_controller_test.rb
test/integration/api/metrics_controller_test.rb
test/integration/api/policies_controller_test.rb
test/integration/api/proxy_rules_controller_test.rb
test/integration/api/sso_tokens_controller_test.rb

Fixing integration/api tests for the upgrade

[integration/api] Fixing test for the upgrade

---

app/controllers/provider/admin/dashboard/widget_controller.rb
app/views/provider/admin/dashboards/widgets/_service_hits.html.slim
app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim
test/integration/provider/admin/keys_controller_test.rb
test/integration/provider/admin/referrer_filters_controller_test.rb
test/integration/provider/invoices_controller_test.rb

Fixes integration provider tests for rails 5.1 upgrade

Fixes integration provider tests for rails 5.1 upgrade

---

lib/developer_portal/app/controllers/developer_portal/admin/messages/outbox_controller.rb
test/functional/developer_portal/buyer/account_contracts_controller_test.rb
test/functional/developer_portal/buyer/stats_controller_test.rb
test/functional/developer_portal/cms/new_content_controller_test.rb
test/functional/developer_portal/login_controller_test.rb
test/functional/developer_portal/signup_controller_test.rb

Fixing functional tests for the upgrade of rails to 5.1

[functional/developer_portal] Fix functional developer portal tests for rails upgrade 5.1

---

test/integration/user-management-api/buyers_account_plan_change_test.rb
test/integration/user-management-api/buyers_account_plans_test.rb
test/integration/user-management-api/buyers_application_keys_test.rb
test/integration/user-management-api/buyers_application_plans_test.rb
test/integration/user-management-api/buyers_application_referrer_filters_test.rb
test/integration/user-management-api/buyers_applications_test.rb
test/integration/user-management-api/buyers_service_plans_test.rb

Update/refactor integrations/user-management-api/buyers

---

.codeclimate.yml
app/controllers/provider/admin/backend_apis_controller.rb
app/helpers/vertical_nav_helper.rb
test/helpers/vertical_nav_helper_test.rb

Fixed Internal error when creating new Backend.
**issue1**: https://issues.redhat.com/browse/THREESCALE-7194
**issue2**: https://issues.redhat.com/browse/THREESCALE-7479
**issue3:** https://issues.redhat.com/browse/THREESCALE-7523

THREESCALE-7194 Fixed New Backend API internal error

---

app/lib/stats/deprecated.rb
app/lib/stats/storage.rb
app/lib/stats/views/top.rb
app/lib/stats/views/usage.rb
app/lib/three_scale/hash_hacks.rb
app/models/configuration.rb
app/models/metric.rb
config/initializers/hash_hacks.rb
test/test_helpers/redis.rb
test/unit/three_scale/hash_hacks_test.rb

Removes as much code as possible from HashHacks. This is part of rails 5.1 upgrade because params are not Hash anymore.

Remove hash hacks

---

.codeclimate.yml

This PR enables the code climate issue

enabled codeclimate check

---

app/controllers/master/api/providers_controller.rb
app/controllers/provider/admin/accounts_controller.rb
app/controllers/provider/domains_controller.rb
app/lib/authentication/strategy/provider_oauth2.rb
app/models/api_docs/service.rb
test/integration/master/api/providers_controller_integration_test.rb
test/integration/provider/admin/accounts_controller_test.rb
test/unit/authentication/strategy/provider_oauth2_test.rb

Doing a single PR for every one of them would be overkill

[email-async] other asynchronous sending

---

test/integration/user-management-api/application_plans_test.rb

* test/integration/user-management-api/application_plans_test.rb

Remove `context` and `should` from application_plans_test

---

test/unit/account_test.rb

Remove `context` and `should` from account_test

---

app/views/provider/admin/cms/files/_form.html.erb
app/views/provider/admin/cms/pages/_form.html.erb
features/old/cms/pages.feature
features/provider/cms/files.feature
features/step_definitions/cms/files_steps.rb

- Adding a hint for the **Tag list** input, in Developer portal **Pages** and **Files**
- Add tests for both pages
Closes https://github.com/3scale/porta/pull/2790
Jira issues:
https://issues.redhat.com/browse/THREESCALE-7898
https://issues.redhat.com/browse/THREESCALE-7935
**Steps to reproduce:**
- Go to **Audience > Developer Portal > Content**
- Select a file (eg: mouse.jpg)
- Write some tags
- Click save

Add hint for Tag list input

---

app/controllers/master/api/finance/billing_jobs_controller.rb

Fixes usage of params in the billing jobs controller

[params] Fixes master/api/finance/billing_jobs_controller

---

app/controllers/provider/domains_controller.rb

Fixes usage of params in the provider domain controller

[params] Fixes provider domains controller

---

test/unit/profile_test.rb

Remove `context` and `should` and from profile_test

---

app/controllers/provider/admin/dashboard/service/base_controller.rb

Fixes usage of params in the dashboard service base controller

[params] Fixes dashboard service base controller

---

test/functional/finance/provider/settings_controller_test.rb
test/unit/metric_test.rb

easier to review with white spaces changes disabled

remove context test syntax

---

app/controllers/partners/base_controller.rb

Fixes usage of params in the partners base controller

[params] Fixes partners base controller

---

app/controllers/master/api/services_controller.rb

Fixes usage of params in the service controller

[params] Fixes master/api/services_controller

---

app/controllers/provider/sessions_controller.rb

Fixes usage of params in the provider session controller

[params] Fixes providers session controller

---

app/controllers/partners/providers_controller.rb

Fixes usage of params in the partners providers controller

[params] Fixes partner providers controller

---

app/controllers/provider/passwords_controller.rb

Fixes usage of params in the provider passwords controller

[params] Fixes provider passwords controller

---

.circleci/config.yml

THe quay context should be added as the secrets are shared there

Allow oracle nightly to be built

---

app/controllers/provider/admin/account/authentication_provider_flow_testing_controller.rb
app/controllers/provider/admin/account/authentication_provider_publishing_controller.rb
app/controllers/provider/admin/account/authentication_providers_controller.rb
app/controllers/provider/admin/account/data_exports_controller.rb
app/controllers/provider/admin/account/invoices_controller.rb
app/controllers/provider/admin/account/notifications_controller.rb
app/controllers/provider/admin/account/payment_gateways/braintree_blue_controller.rb

Fixes usage of params in the admin account controllers

[params] Fixes admin account controllers

---

test/unit/finance/bill_variable_for_plan_changed_test.rb

Nothing materially changes. Just trying to make test more descriptive of what it is doing.

minor variable cost test improvement

---

app/controllers/master/events/imports_controller.rb

Fixes usage of params in the imports controller

[params] Fixes events/imports_controller.rb

---

app/controllers/buyers/accounts_controller.rb

Fixes tests:
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-3
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-4

Update usage of redirect_back in accounts_controller

---

app/controllers/master/providers/base_controller.rb

Fixes usage of params in the base controller

[params] Fixes providers base controller

---

app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim

https://issues.redhat.com/browse/THREESCALE-7992

⚰️ Cleanup partial apicast

---

features/old/cms/pages.feature
features/step_definitions/cms/files_steps.rb

Replaces https://github.com/3scale/porta/pull/2860

tag check step to ignore order of tags

---

app/views/api/metrics/_link_to_mapping_rules.slim

https://issues.redhat.com/browse/THREESCALE-7991

⚰️ Remove link_to_mapping_rule

---

features/old/api/plans/default_plan.feature
features/old/cms/layouts.feature
features/old/cms/pages.feature
features/old/cms/partials.feature
features/old/providers/settings/legal_terms.feature
features/step_definitions/api/plan_steps.rb
features/step_definitions/cms/page_template_steps.rb

There was a couple of failures in master recently but the look random to me.
Build 34: https://app.circleci.com/pipelines/github/3scale/porta/19374/workflows/3f93ab16-0b3b-488a-9861-f6d982a26d69/jobs/230408/artifacts
Tests:
- TEST-features-old-signup-account_activation_emails.xml
- TEST-features-old-buyers-accounts-deleting.xml
- TEST-features-old-api-plans-default_plan.xml
Anyway I took the opportunity to update the related code a bit.

🥒 Update some cucumbers

---

app/controllers/provider/admin/cms/builtin_legal_terms_controller.rb

Fixes scenarios:
```
Scenario: Signup Licence
AfterStep hook at features/support/hooks.rb:59
Message:
unable to convert unpermitted parameters to hash (ActionController::UnfilteredParameters)
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/strong_parameters.rb:265:in `to_h'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/inheritance.rb:218:in `subclass_from_attributes'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/inheritance.rb:56:in `new'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/protected_attributes_continued-1.3.0/lib/active_record/mass_assignment_security/reflection.rb:8:in `build_association' …
```

[params] Builtin legal terms controller 

---

config/docker/database.yml
config/examples/database.yml
openshift/system/config/database.yml

See 
https://github.com/rsim/oracle-enhanced/#upgrade-rails-50-or-older-version-to-rails-51

prepare for oracle-enhanced 1.8+

---

doc/licenses/licenses.xml

Some licenses are out of date.
Ran:
```
bundle exec rails ci:license_finder:run
bundle exec rails ci:license_finder:report
bundle exec rails ci:license_finder:compliance
```

updates licenses XML

---

app/javascript/src/Common/components/SelectWithModal.jsx
app/javascript/src/Common/components/TableModal.jsx
app/javascript/src/NewApplication/components/ProductSelect.jsx
app/views/shared/applications/_listing.html.slim
spec/javascripts/Common/components/SelectWithModal.spec.jsx
spec/javascripts/Common/components/TableModal.spec.jsx

Fixes copy on
* Account > Applications
* Account > Applications > New
[THREESCALE-7020: [UI Strings] Improve Select in 'Create new Application' form](url)
Aforementioned pages should comply with:
https://docs.google.com/document/d/1EXxUn8nrKnyIH_2-x4KueKStapf46S3x3TYsoGKlBP0/edit#heading=h.jdtra5un7hn
Keep in mind most suggestions were already implemented

📝 Update Accounts Applications copy

---

app/controllers/admin/api/cms/templates_controller.rb
test/integration/cms/api/templates_test.rb

Cherry-pick from rails branch that can be merged to the master.

[Paras] Templates controller

---

app/lib/fields/provider.rb
lib/developer_portal/app/controllers/developer_portal/admin/service_contracts_controller.rb

Adds permitted parameters to the service contract controller.

[Params] Adds permit to the service contract controller

---

app/controllers/admin/api/messages_controller.rb
doc/active_docs/Account Management API.json
spec/acceptance/api/message_spec.rb

Permitting only parameters described in API documentation.
Cherry-pick from rails branch that can be merged to actual master.

Message controller parameters permit

---

app/models/payment_gateway_setting.rb

```
Started DELETE "/admin/api/accounts/34.json?access_token=thetoken" for 10.0.144.73 at 2022-02-04 15:09:15 +0000
Processing by Admin::Api::AccountsController#destroy as JSON
Parameters: {"access_token"=>"thetoken", "id"=>"34"}
PermissionEnforcer: level = rw
[ActiveJob] Enqueued ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper#1cf591ff8394aec8c980327b with args: [{"job_class"=>"SphinxAccountIndexationWorker", "job_id"=>"265fdcd5-3a89-47a7-bfad-485b41e9f901", "provider_job_id"=>nil, "queue_name"=>"default", "priority"=>nil, "arguments"=>[{"_aj_globalid"=>"gid://system/Account/34"}], "executions"=>0, "locale"=>"en"}]
[ActiveJob] Enqueued SphinxAccountIndexationWorker (Job ID: 265fdcd5-3a89-47a7-bfad-485b41e9f901) to Sidekiq(default) with arguments: #<GlobalID:0x000000000dbf6d70 …
```

Fix undefined method `symbolize_keys` ActionController::Parameters

---

app/assets/javascripts/master_application.js
app/assets/stylesheets/provider/_commons.scss
app/assets/stylesheets/provider/_header.scss
app/assets/stylesheets/provider/layouts/_main.scss
app/controllers/provider/admin/resources_controller.rb
app/javascript/packs/quick_starts_context.js
app/javascript/quickstarts/index.js
app/javascript/quickstarts/template.yaml
app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
app/javascript/src/Navigation/components/ContextSelector.jsx
app/javascript/src/QuickStarts/QuickStartsContext.jsx
app/views/layouts/provider.html.slim
app/views/provider/admin/resources/show.html.slim
app/views/shared/provider/_header.html.slim
config/routes.rb
config/webpack/environment.js
config/webpacker.yml
package.json
yarn.lock

Resubmitting the changes from https://github.com/3scale/porta/pull/2859 into this branch and using signed commits

quick starts

---

lib/generators/react_page/USAGE
lib/generators/react_page/react_page_generator.rb

A basic generator to create all boilerplate necessary for adding a new page made with React+Flow.

Generator for a React pages

---

app/events/base_event_store_event.rb
app/events/oidc/proxy_changed_event.rb
app/lib/redhat_customer_portal_support.rb
app/models/account/billing.rb
app/models/account/credit_card.rb
app/models/account/provider_domains.rb
app/models/proxy.rb
app/models/service.rb
lib/previously_changed.rb

reverts partially 8f8e86e65 and cb905d6f and 1256260b
Not certain this change is good so revert until it is investigated better.

revert unclear attribute_changed update

---

config/webpack/environment.js

Small update to maintain same format throughout the file.

🎨  updates environment.js format for consistency

---

app/lib/fields/extra_fields.rb
test/integration/admin/api/accounts_controller_test.rb
test/unit/extra_fields_test.rb

JIRA: [THREESCALE-8082: Expected string in extra_fields.rb](https://issues.redhat.com/browse/THREESCALE-8082)

🐛 Fix undefined method strip with extra_fields to_xml

---

test/unit/backend/model_extensions/metric_test.rb

In sphinx tests we search all classes for being indexed. If this test ran first, then there was an extra unexpected class `MetricWithFiber`. So now removing this class in `teardown`.

avoid sphinx indexing tests issues

---

app/javascript/src/LoginPage/loginForms/Login3scaleForm.jsx
spec/javascripts/LoginPage/__snapshots__/LoginPageWrapper.spec.jsx.snap

Autocomplete attribute is set to "on" for the credentials fields in the login page
https://issues.redhat.com/browse/THREESCALE-8115

THREESCALE-8115 added autocomplete off

---

.github/workflows/container-image.yml

after #2972 lets also build the image!

build community image

---

INSTALL.md

Updates Ruby and Node versions and updates outdated `brew` command.

Updates INSTALL.md

---

app/javascript/src/NewApplication/components/BuyerSelect.jsx
app/javascript/src/NewApplication/components/ServicePlanSelect.jsx
app/views/api/applications/new.html.slim
spec/javascripts/NewApplication/components/NewApplicationForm.spec.jsx

[THREESCALE-7019 [UI Strings] Add 'Create new Application' flow to Product > Applications index](https://issues.redhat.com/browse/THREESCALE-7019)
> Go to Applications > Listing.
> Confirm the strings matches the microcopy.
> Click Create application.
> Confirm the strings matches the microcopy.
Review [microcopy](https://docs.google.com/document/d/1h64Yp-mV2x7Xq3WX5Gz8jkwINjWIkTaIe_xWqDYrOM4/edit#).

[UI Strings] Add 'Create new Application' flow to Product > Applications index

---

.github/workflows/container-image.yml

test and optimize image build, follow up on #2979 
Please comment on the whole file, I merged the last one just to be able to try out.

Container image

---

app/javascript/src/Plans/components/DefaultPlanSelectCard.jsx
app/views/api/application_plans/index.html.slim
app/views/api/application_plans/new.html.erb
app/views/api/services/show.html.slim
features/old/api/metrics/default.feature
features/step_definitions/api/application_plans_steps.rb
spec/javascripts/Plans/components/DefaultPlanSelectCard.spec.jsx
test/integration/api/application_plans_controller_test.rb

[THREESCALE-7611 [UI Strings] Improve select default Application plan](https://issues.redhat.com/browse/THREESCALE-7611)
Go to Products > Application > Application Plans
Confirm the strings matches the microcopy.
> Go to Products > Application > Application Plans
> Confirm the strings matches the microcopy.
> Click on Create application plan.
> Confirm that title and submit button are "Create application plan".
Review [microcopy](https://docs.google.com/document/d/1LoX6R3sbuXL7u4yZoSPsXabzn61CFdz-vuV3fVY3d4c).
**Snapshots:**

[UI Strings] Improve select default Application plan

---

lib/tasks/sphinx.rake

eager loading of sphinx accounts indexing enqueue

---

app/javascript/src/BackendApis/components/AddBackendForm.jsx
app/javascript/src/BackendApis/components/BackendSelect.jsx
app/javascript/src/BackendApis/components/NewBackendForm.jsx
app/javascript/src/BackendApis/components/NewBackendModal.jsx
app/javascript/src/BackendApis/components/PrivateEndpointInput.jsx
app/javascript/src/BackendApis/components/SystemNameInput.jsx
app/models/backend_api_config.rb
app/views/api/backend_usages/index.html.slim
app/views/api/backend_usages/new.html.slim
features/step_definitions/backend_usages_steps.rb
test/models/backend_api_config_test.rb

[THREESCALE-7041 [UI Strings] Improve Select in 'Add Backend to Product' form](https://issues.redhat.com/browse/THREESCALE-7041?filter=-1)
1. Go to Products > Integration > Backends
2. Click on Add backend
3. Click on Select a backend select button
4. Click on Create a backend
Confirm the strings at all pages matches the microcopy.
**Snapshots:**

[UI Strings] Improve Select in 'Add Backend to Product' form

---

features/step_definitions/flash_steps.rb
features/step_definitions/plans_steps.rb

[THREESCALE-8549](https://issues.redhat.com/browse/THREESCALE-8549)	Fix random failure "failed Delete an account plan" in oracle

Fix "Delete Account" scenario failing in Oracle

---

features/step_definitions/flash_steps.rb
features/step_definitions/plans_steps.rb

Still not working!!!! 😫😫😫😫😫😫😫
Reverts 3scale/porta#3021

Revert "Fix "Delete Account" scenario failing in Oracle"

---

.circleci/config.yml

wrong image uri that I couldn't catch until it was merged to master

fix circleci basic image uri

---

Gemfile
Gemfile.lock
app/lib/three_scale/spam_protection/protector.rb
config/initializers/captchas.rb
features/developer_portal/login.feature
features/old/forums/posting.feature
features/step_definitions/capcha_steps.rb
features/step_definitions/liquid_steps.rb
features/step_definitions/session_steps.rb
features/support/hooks.rb
features/support/recaptcha_helper.rb
lib/developer_portal/app/controllers/developer_portal/login_controller.rb
lib/developer_portal/lib/liquid/forms/login.rb
test/integration/developer_portal/passwords_controller_test.rb
test/unit/three_scale/spam_protection_test.rb

This reverts commit 9029d87bc3db65f7d05edfaf2a92e348194b9e2c.
Conflicts:
features/developer_portal/login.feature
lib/developer_portal/app/controllers/developer_portal/login_controller.rb
[THREESCALE-6645: Developer portal lack of brute force protection on login](https://issues.redhat.com/browse/THREESCALE-6645)

Revert "Adds Recaptcha to Dev portal Login #2543"

---

features/old/messages/provider_side.feature

[THREESCALE-8534: Scenario: Sending a message fails because flash can't be seen](https://issues.redhat.com/browse/THREESCALE-8534)

Fix scenario "Sending a message" in oracle

---

INSTALL.md
config/environments/development.rb

It adds a new section to INSTALL.md to show how to enable the rails cache for development

Add info about Rails cache to INSTALL.md

---

app/inputs/codemirror_input.rb
app/inputs/price_input.rb

https://app.bugsnag.com/3scale-networks-sl/system/errors/63345eb91bdbe9000a4371b5

Fix `merge` being called with multiple arguments

---

Gemfile
Gemfile.lock
config/webpacker.yml
package.json
yarn.lock

This reverts commit 46d1a3913527aea4e8bf33a93f6933ed2d279b2b.

Revert "THREESCALE-7522: Update webpacker to 5.4.3"

---

openshift/system/Dockerfile
openshift/system/contrib/scl_enable

`scl_enable` was redundant between porta nad distgit repo. Lets use a single copy.

move distgit scl_enable here

---

app/helpers/payment_details_helper.rb
app/models/account/gateway.rb
lib/developer_portal/app/controllers/developer_portal/base_controller.rb
lib/developer_portal/lib/developer_portal/controller_methods/payment_paths_methods.rb
lib/developer_portal/lib/liquid/drops/urls.rb
test/unit/account/gateway_test.rb

Move `unacceptable_payment_gateway?` to module Account::Gateway

---

test/integration/buyers/accounts_controller_test.rb
test/unit/concerns/symbolize_test.rb

fix tests with Oracle and PostgreSQL

fix pgsql and oracle tests

---

test/integration/api/plan_copies_controller_test.rb
test/unit/concerns/symbolize_test.rb

follow-up on #3170 and fix a flaky test.

Db tests fix

---

lib/developer_portal/app/controllers/developer_portal/admin/account/braintree_blue_controller.rb

🐛 Remove duplicated flash message

---

app/javascript/src/PaymentGateways/braintree/BraintreeForm.tsx
app/javascript/src/PaymentGateways/braintree/braintree.ts
app/javascript/src/PaymentGateways/braintree/utils/formValidation.ts

Nothing should change, it's just a small refactoring.

🧠 🌴 Extract form validation

---

app/views/shared/_new_mapping_rules.html.slim
app/views/shared/proxy_rules/_body_section.html.slim
app/views/shared/proxy_rules/_header_section.html.slim

[THREESCALE-7024 [UI Strings] Improve UI for creating a Product Mapping rule](https://issues.redhat.com/browse/THREESCALE-7024)
1. Go to Products > Integration > Mapping rules
2. Confirm strings matches the microcopy
3. Click on Create mapping rule
4. Confirm strings matches the microcopy
5. Click on Select a method
6. Confirm strings matches the microcopy
Microcopy can be found [here](https://docs.google.com/document/d/1SMRaWeyERqZoWQ7Sh8-YTBGBY6i1Yo5xr6Rsyy7m0dw).
Snapshots: 

[UI Strings] Improve UI for creating a Product Mapping rule

---

README.md

Added the container ready badge as well space between badges as they looked ugly earlier

Container ready badge in README

---

app/models/cms/file.rb
app/models/cms/section.rb
app/representers/cms/builtin/static_page_representer.rb
app/representers/cms/file_representer.rb
app/representers/cms/files_representer.rb
app/representers/cms/layout_representer.rb
app/representers/cms/page_representer.rb
app/representers/cms/partial_representer.rb
app/representers/cms/portlet_representer.rb
app/representers/cms/section_representer.rb
app/representers/cms/sections_representer.rb
app/representers/cms/template_representer.rb
app/representers/cms/templates_representer.rb
spec/acceptance/api/cms_file_spec.rb
spec/acceptance/api/cms_layout_spec.rb
spec/acceptance/api/cms_page_spec.rb
spec/acceptance/api/cms_partial_spec.rb
spec/acceptance/api/cms_section_spec.rb
spec/acceptance/api/cms_template_spec.rb
spec/support/api/context.rb
test/functional/admin/api/cms/templates_controller_test.rb
test/integration/cms/api/files_test.rb
test/integration/cms/api/sections_test.rb
test/integration/cms/api/templates_test.rb

This PR updates the JSON responses for the CMS API following a new convention (please check the linked ticket).
[THREESCALE-9431](https://issues.redhat.com/browse/THREESCALE-9431)
The following endpoints should follow the new response format agreed on this PR's ticket counterpart.
| Verb | Endpoint | Controller#Action |
| ------- | ------- | ------- |
|GET|/admin/api/cms/sections|admin/api/cms/sections#index|
|POST|/admin/api/cms/sections|admin/api/cms/sections#create|
|GET|/admin/api/cms/sections/:id|admin/api/cms/sections#show|
|PATCH|/admin/api/cms/sections/:id|admin/api/cms/sections#update|
|PUT|/admin/api/cms/sections/:id|admin/api/cms/sections#update| …

CMS API: Update CMS API JSON responses

---

config/examples/rolling_updates.yml
config/examples/settings.yml
openshift/system/config/rolling_updates.yml
openshift/system/config/settings.yml

A follow-up for https://github.com/3scale/porta/pull/3225
Hopefully, it makes these config files easier to check and find settings in it.
There are NO functional changes, just reordering and removing some empty lines.

Sort keys in config files alphabetically

---

app/javascript/src/Dashboard/components/BackendsWidget.tsx
app/javascript/src/Dashboard/components/ProductsWidget.tsx

This class is already in `<Card />`.

💄 Remove dupe class `pf-c-card`

---

package.json
yarn.lock

It's referenced in `.postcssrc.yml` but postcss is not used.

🧹 Remove unused package `postcss-smart-import`

---

.eslintignore
tsconfig.json

It should've been part of #3290

🧹 Remove leftover reference to PF4Styles

---

openshift/system/Dockerfile

Just bringing in sync with 
https://github.com/3scale/3scale-operator/pull/803

/var/lib/searchd not sphinx

---

.browserslistrc
.gitignore
package.json
yarn.lock

$subject
And also Babel now requires a list of supported browsers (by means of browserslist).

⬆️ Upgrade babel packages

---

.babelrc
.circleci/asset_paths
.eslintrc
.gitignore
babel.config.js
config/webpack/development.js
config/webpack/environment.js
config/webpack/production.js
config/webpack/test.js
config/webpacker.yml
package.json
yarn.lock

Inspired by #3275 
But basically stripped off every braking change. The default config used by `webpacker 5` seems to be worse than what we have. And what we have works all right, so we're gonna leave it like that until we upgrade to `webpacker 6`.

❤️🐒 Maintain webpackers' config monkey-patching but use some defaults

---

app/controllers/provider/sessions_controller.rb
app/models/backend_api.rb
app/services/audit_log_service.rb
test/integration/provider/sessions_controller_test.rb
test/models/backend_api_test.rb
test/unit/services/audit_log_service_test.rb

This is the part of #3342 that is ready to merge.

add a little more auditing

---

features/asset_host/asset_host.feature
features/step_definitions/asset_host_steps.rb

Some tests were wrong, somehow they didn't fail in their branch. ¯\_(ツ)_/¯

Fix CDN cucumbers

---

app/javascript/src/ActiveDocs/ApiDocsForm.scss
app/javascript/src/ActiveDocs/ApiDocsForm.tsx
app/javascript/src/BackendApis/components/AddBackendForm.scss
app/javascript/src/BackendApis/components/NewBackendForm.tsx
app/javascript/src/EmailConfigurations/components/EditPage.scss
app/javascript/src/EmailConfigurations/components/EmailConfigurationForm.tsx
app/javascript/src/EmailConfigurations/components/NewPage.scss
app/javascript/src/MappingRules/components/NewMappingRule.scss
app/javascript/src/MappingRules/components/NewMappingRule.tsx
app/javascript/src/NewApplication/components/NewApplicationForm.scss
app/javascript/src/NewApplication/components/NewApplicationForm.tsx
app/javascript/src/Plans/components/DefaultPlanSelectCard.scss
app/javascript/src/Plans/components/DefaultPlanSelectCard.tsx

Patternfly React 4 introduced this property.
[THREESCALE-9643: Remove hardcoded max-width in favor of isWithLimited](https://issues.redhat.com/browse/THREESCALE-9643)

🦋 Use `isWidthLimited` instead of `max-width`

---

Gemfile
Gemfile.lock
app/lib/three_scale/semantic_form_builder.rb
app/views/provider/admin/user/notification_preferences/_form.html.slim
config/initializers/formtastic.rb
lib/templates/slim/scaffold/_form.html.slim
test/unit/three_scale/semantic_form_builder_test.rb

Upgrade  formtastic
https://issues.redhat.com/browse/THREESCALE-5661
**Special notes for your reviewer:**
Changelogs:
https://github.com/formtastic/formtastic/blob/3.0-stable/CHANGELOG
https://github.com/formtastic/formtastic/blob/4.0.0/CHANGELOG.md

THREESCALE-5661 upgrade formtastic

---

app/javascript/packs/plans_index.ts
app/javascript/src/Common/components/Select.tsx
app/javascript/src/Plans/components/AccountPlansIndexPage.tsx
features/buyers/account_plans.feature
features/step_definitions/plans/account_plans_steps.rb
features/step_definitions/web_steps.rb
spec/javascripts/Plans/components/__snapshots__/AccountPlansIndexPage.spec.tsx.snap

This was added for local testing #3381... and was left behind 😬

💩 Fix leftover hardcoded prop

---

package.json
yarn.lock

[THREESCALE-9691: Upgrade Patternfly react-table](https://issues.redhat.com/browse/THREESCALE-9691)

⬆️ Bump `@patternfly/react-table`

---

app/helpers/payment_details_helper.rb
app/lib/payment_gateways/stripe_crypt.rb
test/unit/lib/payment_gateways/stripe_crypt_test.rb

This PR Fix 
https://issues.redhat.com/browse/THREESCALE-8355

THREESCALE-8355 handled error at stripe

---

app/javascript/src/Stats/lib/chart.jsx
app/javascript/src/Stats/lib/metrics_selector.jsx
app/javascript/src/Stats/provider/stats_days_of_week.jsx
app/javascript/src/Stats/provider/stats_hours_of_day.jsx

Stats show hits as integers

---

app/assets/stylesheets/provider/_forms.scss

Fix [yet more] missing Patternfly styles

---

openshift/system/Dockerfile

This is a follow-up on #3196 but we delay it until operator can pick up
the change.

free the Sphinx 2/2

---

app/assets/stylesheets/provider/_commons.scss
app/assets/stylesheets/provider/_metrics.scss
app/assets/stylesheets/provider/_tables.scss
app/views/api/application_plans/edit.html.erb
app/views/api/plans/_features.html.erb
app/views/api/plans/_menu.erb
app/views/api/plans/_metrics.html.erb
app/views/buyers/account_plans/edit.html.erb

* Plan edit tables
* Custom plan header subtitle
* New Feature modal h2 header

💄 Fix [yet even more still!] missing and broken css

---

app/helpers/buttons_helper.rb
app/views/buyers/users/index.html.slim
app/views/buyers/users/show.html.erb

Reverts new buttons in #3428 :
* https://github.com/3scale/porta/pull/3428/files#diff-1c39dce0cd0fcf5e98477ca07c596778dd360dbd515903016f164233c5cc43ec
* https://github.com/3scale/porta/pull/3428/files#diff-221f7e0971814ba36afbb274c8acdebb04d3be59907111deae7de68c3085d095
Before (master):
After:

⏪ Revert PF4 buttons in Users table

---

app/javascript/packs/provider.scss

💄🦋 Add missing Overflow Menu stylesheet

---

app/assets/stylesheets/provider/_tables.scss
app/helpers/column_sorting_helper.rb
app/javascript/packs/provider.scss
app/views/buyers/accounts/_search_results.html.slim
features/old/accounts/bulk_operations/change_plans.feature
features/old/accounts/bulk_operations/change_states.feature
features/old/buyers/accounts/searching.feature
features/step_definitions/table_steps.rb

[THREESCALE-9764: PF4 to buyer accounts table header](https://issues.redhat.com/browse/THREESCALE-9764)
Before:
After:

🦋 Update Buyer accounts' table header

---

app/assets/stylesheets/provider/_buttons.scss
app/assets/stylesheets/provider/_commons.scss
app/assets/stylesheets/provider/admin/_dashboard.scss
app/helpers/search_helper.rb
app/javascript/packs/provider.scss
app/views/buyers/accounts/_empty_state.html.slim
app/views/buyers/accounts/_search_results.html.slim
config/locales/en.yml
features/buyers/accounts/index.feature
features/old/buyers/accounts/searching.feature
features/step_definitions/buyers_management/account_steps.rb
features/step_definitions/search_steps.rb
features/step_definitions/table_steps.rb

[THREESCALE-9767: Buyer accounts empty results](https://issues.redhat.com/browse/THREESCALE-9767)
* Current search query now is visible in the input.
* Clicking "Clear all filters" will reset the search.
Before:
After:

🦋 Buyer accounts' Empty state

---

db/migrate/20230707104807_add_index_to_api_docs_services_account_id.rb
db/migrate/20230707110416_add_index_to_payment_gateway_settings_account_id.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Adds missing indexes for the queries involved in the account deletion process.
[THREESCALE-9917](https://issues.redhat.com/browse/THREESCALE-9917) and [THREESCALE-9918](https://issues.redhat.com/browse/THREESCALE-9918)
-

Add missing indexes

---

features/old/services/subscriptions/bulk_operations/change_states.feature

This PR is raised to fix 
https://issues.redhat.com/browse/THREESCALE-8148
I have removed wip and this test doesn't fails on circle ci, So This PR can be merged directly.

THREESCALE-814  to check buyer subscription failure

---

features/old/accounts/bulk_operations.feature
features/old/services/subscriptions/bulk_operations.feature
features/step_definitions/applications/bulk_operations_steps.rb

**This PR Fixes @wip feature for BulkOperations for this file , which are failing in circle CI**
porta/features/old/accounts/bulk_operations.feature
https://issues.redhat.com/browse/THREESCALE-9757

THREESCALE-7195 remove wip to check faliure

---

features/old/login.feature

**This PR fix failure of wip feature of file**
/porta/features/old/login.feature
**Jira issue**
https://issues.redhat.com/browse/THREESCALE-9931
This test is removed as its an very old one 
https://github.com/3scale/system/commit/4dc4ecc4931734de692d1bf729d698c2f1ad342d

THREESCALE-9931 removed old test

---

app/javascript/src/Navigation/components/VerticalNav.scss

[THREESCALE-9832: Outdated configuration warning missalligned](https://issues.redhat.com/browse/THREESCALE-9832)

💄 fixes outdated integration config warning icon in nav

---

public/404.html
public/500.html
public/502.html

Small improvement on the error page template.
**Before:**
**After:**
-none-
-

Remove ul tag from the footer on error page

---

test/unit/liquid/drops/user_drop_test.rb

Adding a missing test for #3472

🧪 Add test for #using_password?

---

app/javascript/packs/provider.scss
app/views/admin/api_docs/base/index.html.slim
features/api/services/api_docs.feature
features/provider/admin/api_docs.feature

[THREESCALE-9785: PF4 Empty state](https://issues.redhat.com/browse/THREESCALE-9785)
Before:
After:

Active Docs Empty State

---

app/javascript/src/Stats/lib/chart.js
app/javascript/src/Stats/lib/metrics_selector.js
app/javascript/src/Stats/provider/stats_days_of_week.js
app/javascript/src/Stats/provider/stats_hours_of_day.js
spec/javascripts/Stats/lib/chart.spec.js
spec/javascripts/Stats/lib/metrics_selector.spec.js
spec/javascripts/Stats/lib/stats_days_of_week.spec.js
spec/javascripts/Stats/lib/stats_hours_of_day.spec.js

https://issues.redhat.com/browse/THREESCALE-8036
**Note for reviewer** **PR IS NOT READY FOR MERGE**
This JIRA demands fix on there pages of analytics
1. Traffic
2. Daily Averages
3. Hourly Averages
Fix will be similar kind of fix so I fixed one page first if looks good I can move to other pages
Here I am attaching screenshots of before and after for clarity
**Before Screenshot**
**After Screenshot**

THREESCALE-8036 fixed traffic analytics chart to show integers on y axis

---

features/old/api/metrics/default.feature

**This PR fix failure of wip feature of file**
porta/features/old/api/metrics/default.feature
**Jira issue**
https://issues.redhat.com/browse/THREESCALE-9987

THREESCALE-9987 fix default metrics after signup feature

---

features/old/public_site_access.feature

**This PR fix failure of wip feature of file**
/features/old/public_site_access.feature
**Jira issue**
https://issues.redhat.com/browse/THREESCALE-9960
I removed this test because they no longer exist, I tried reproducing them but no such links are seen  .
If anyone knows existence of this feature let me know how to reproduce.

THREESCALE-9960 removed old feature

---

app/assets/javascripts/sites/general_settings.js
app/assets/stylesheets/provider/_forms.scss
app/assets/stylesheets/provider/_theme.scss
app/assets/stylesheets/provider/sites/usage_rules.scss
app/helpers/admin/settings_helper.rb
app/helpers/sites/usage_rules_helper.rb
app/javascript/packs/provider.scss
app/views/api/services/forms/_usage_rules.html.slim
app/views/shared/_old_plan_change_settings.html.slim
app/views/shared/_plan_change_settings.html.slim
app/views/sites/usage_rules/_plan_change_radio.html.slim
app/views/sites/usage_rules/_settings_check.html.slim
app/views/sites/usage_rules/edit.html.slim
config/locales/en.yml
test/functional/sites/usage_rules_controller_test.rb

[THREESCALE-9949: Site Usare Rules](https://issues.redhat.com/browse/THREESCALE-9949)
Also fixes [THREESCALE-9833: Misaligned text for changing account and service plans](https://issues.redhat.com/browse/THREESCALE-9833)

🦋 Site Usage Rules with PF4

---

app/models/invoice.rb
features/old/accounts/invoices.feature
features/step_definitions/finance/invoicing_steps.rb
features/step_definitions/timehelpers_steps.rb
features/support/time_machine_helpers.rb

Some suggestions for the invoice years cucumbers. See comments inline.

Threescale 9592 invoice years suggestion

---

features/old/api/features.feature
features/step_definitions/api/application_plans_steps.rb
features/step_definitions/features_steps.rb
features/support/parameter_types.rb
features/support/paths.rb

Some suggestions to make the tests more consistent.

Update plan features cucumbers

---

app/javascript/src/Login/components/LoginForm.tsx
app/javascript/src/Login/components/LoginPage.tsx
spec/javascripts/Login/components/LoginForm.spec.tsx
spec/javascripts/Login/components/__snapshots__/LoginPage.spec.tsx.snap

[THREESCALE-10131: SSO Integration log in to admin portal checking username and password field on login page](https://issues.redhat.com/browse/THREESCALE-10131)

Remove autofocus from Login form

---

.circleci/config.yml
app/javascript/src/EmailConfigurations/components/EmailConfigurationsTable.tsx
app/presenters/provider/admin/account/email_configurations_presenter.rb
docker-compose.yml
features/provider/admin/account/email_configurations.feature
features/step_definitions/provider/admin/account/email_configurations_steps.rb

3scale on-premises already supports MySQL 8.0, and we're going to migrate SaaS soon also.

Update MySQL to 8.0 in CircleCI

---

app/models/billing_lock.rb
db/migrate/20230927012615_drop_billing_locks.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

part of THREESCALE-9665
supersedes #3425 because I want to test oracle as well

remove now redundant billing_locks table

---

INSTALL.md
fedora-manual-setup.md
osx-manual-setup.md

We upgraded CircleCI here: https://github.com/3scale/porta/pull/3575

Reference MySQL 8.0 in docs

---

app/views/finance/provider/invoices/index.html.erb
config/locales/en.yml
features/provider/finance/invoices.feature
features/step_definitions/finance/invoicing_steps.rb

[THREESCALE-9825: Invoices Empty state](https://issues.redhat.com/browse/THREESCALE-9825)

🦋 Implement EmptyState for Invoices

---

app/lib/fields/fields.rb
app/models/account.rb
app/models/cinstance.rb
app/models/fields_definition.rb
app/models/user.rb
features/old/applications/buyers/application_management.feature
features/old/applications/buyers/extra_fields.feature
features/old/applications/providers/managing.feature
features/step_definitions/api/application_plans_steps.rb
features/step_definitions/applications/applications_steps.rb
features/step_definitions/provider_steps.rb
spec/acceptance/api/application_spec.rb
test/integration/provider/admin/applications/applications_controller_test.rb
test/integration/user-management-api/buyers_applications_test.rb
test/mailers/notification_mailer_test.rb
test/unit/extra_fields_test.rb

Keep application 'description' field as optional

---

app/assets/stylesheets/provider/_finance.scss
app/assets/stylesheets/provider/_forms.scss
app/helpers/patternfly_components_helper.rb
app/inputs/patternfly_checkbox_input.rb
app/inputs/patternfly_input_input.rb
app/inputs/patternfly_select_input.rb
app/models/finance/postpaid_billing_strategy.rb
app/models/finance/prepaid_billing_strategy.rb
app/views/finance/provider/settings/show.html.slim
config/initializers/formtastic.rb
config/locales/en.yml
features/step_definitions/finance/settings_steps.rb

[THREESCALE-10237: Billing > Settings > Charging & Gateway](https://issues.redhat.com/browse/THREESCALE-10237)
New features:
- The deprecation warning is shown both in the page header and the gateway form section
Before:
After:

🦋 Update Billing Charging & Gateway settings

---

app/workers/sphinx_indexation_worker.rb
test/workers/sphinx_indexation_worker_test.rb

This is just an experimental fix but we need to get it in master to have a proper alpha build. Otherwise can't reproduce this intermittent problem.
Upstream information about the issue pat/thinking-sphinx#1219
Also need to figure out whether we need both exception types.

sometimes search indexing becomes broken

---

app/models/account.rb
lib/developer_portal/app/controllers/developer_portal/admin/messages/outbox_controller.rb
lib/developer_portal/app/controllers/developer_portal/admin/messages/trash_controller.rb
lib/developer_portal/lib/liquid/drops/message.rb

Fixes for https://github.com/3scale/porta/pull/3588

Fixes for trash and outbox controller on dev portal

---

app/workers/sphinx_indexation_worker.rb

Just have a method to validate that this was triggered.

logging when clearing searchd connection pool

---

features/buyers/accounts/show.feature

https://issues.redhat.com/browse/THREESCALE-10292

Threescale 10292 remove unwanted  code

---

features/old/accounts/accounts.feature

Completed old account feature test
https://issues.redhat.com/browse/THREESCALE-10294

Threescale 10294 complete account feature 

---

config/cucumber.yml
config/environments/test.rb
features/buyers/service_contracts/bulk_operations.feature
features/step_definitions/table_steps.rb
test/unit/stats/views/usage_hack_test.rb
test/unit/three_scale/email_configuration_interceptor_test.rb
test/unit/three_scale/json_validator_test.rb

Run all tests in random order

---

app/assets/stylesheets/provider/_forms.scss
app/lib/fields/patternfly_form_builder.rb
app/views/buyers/accounts/new.html.erb
features/buyers/accounts/new.feature
test/integration/buyers/accounts_controller_test.rb

[THREESCALE-10397: Audience > Accounts > New](https://issues.redhat.com/browse/THREESCALE-10397)
Before:
After:

🦋 New Buyer account page

---

features/buyers/accounts/index.feature

I think the only real solution is to not have rows with duplicated values.

🐘🥒 Update failing test in Postgres

---

test/unit/application_keys_test.rb

Expected to fix failure
https://app.circleci.com/pipelines/github/3scale/porta/26626/workflows/5abafd52-fd39-42d1-b4e9-37e5ed7c7933/jobs/299055/tests

[test] more precise time calculations

---

app/controllers/buyers/accounts_controller.rb
app/views/buyers/accounts/edit.html.slim
config/locales/en.yml
features/buyers/accounts/edit.feature
features/buyers/accounts/new.feature

[THREESCALE-10449: Audience > Accounts > Edit](https://issues.redhat.com/browse/THREESCALE-10449)
Before:
After:

🦋 Buyer accounts edit

---

doc/active_docs/account_management_api.json

to fix  some incorrect specifications in Account Management API specs
https://issues.redhat.com/browse/THREESCALE-10398

THREESCALE-10398 fix account management api spec

---

lib/three_scale/metrics/yabeda.rb

Reduce the metrics we report to Prometheus from Rails, based on what we discussed with @slopezz and also on the metrics that are needed to populate the System dashboard that we create in the [3scale-operator](https://github.com/3scale/3scale-operator/blob/e9989eecb03b57047818b8c10a7bbab9f9d32cb6/pkg/assets/assets/monitoring/system-grafana-dashboard-1.json.tpl) (some graphs will be removed from it by the way).
1. Remove `action` label from `rails_requests_total` metric.
2. Remove all labels from the `rails_request_duration_seconds` histogram (which includes `rails_request_duration_seconds_bucket`, `rails_request_duration_seconds_count` and `rails_request_duration_seconds_sum` metrics).
3. Group status codes to `2xx`, `3xx` etc., as individual values …

THREESCALE-9934: Further reduce prometheus metrics for better performance

---

app/controllers/provider/admin/cms/templates_controller.rb
app/helpers/cms/form_helper.rb
app/views/provider/admin/cms/pages/_form.html.erb
app/views/provider/admin/cms/templates/update.js.erb

This is a PR for https://github.com/3scale/porta/pull/3651
(it actually reverts what https://github.com/3scale/porta/pull/3651 does)

Fix the CMS page update form

---

doc/active_docs/billing_api.json

Add missing states in API docs.
https://issues.redhat.com/browse/THREESCALE-10147

THREESCALE-10147: Add missing Invoice states in 3scale API docs

---

app/javascript/src/QuickStarts/components/CustomCatalog.tsx
app/javascript/src/QuickStarts/templates/basicAPIintegration.yaml
app/javascript/src/QuickStarts/templates/createAPIproduct.yaml
app/javascript/src/QuickStarts/templates/createAccessTiersForAPIconsumers.yaml
app/javascript/src/QuickStarts/templates/createApplication.yaml
app/javascript/src/QuickStarts/templates/createApplicationPlan.yaml
app/javascript/src/QuickStarts/templates/createBackend.yaml
app/javascript/src/QuickStarts/templates/createMappingRule.yaml
app/javascript/src/QuickStarts/templates/createMethod.yaml
app/javascript/src/QuickStarts/templates/createMetric.yaml
app/javascript/src/QuickStarts/templates/createProduct.yaml
app/javascript/src/QuickStarts/templates/learnAboutAccounts.yaml
app/javascript/src/QuickStarts/templates/learnAboutApplicationPlans.yaml
app/javascript/src/QuickStarts/templates/learnAboutApplications.yaml
app/javascript/src/QuickStarts/templates/learnAboutBackends.yaml
app/javascript/src/QuickStarts/templates/learnAboutMappingRules.yaml
app/javascript/src/QuickStarts/templates/learnAboutMethods.yaml
app/javascript/src/QuickStarts/templates/learnAboutMetrics.yaml
app/javascript/src/QuickStarts/templates/learnAboutProducts.yaml
app/javascript/src/QuickStarts/templates/trackUsageForAPIProduct.yaml

This is for https://github.com/3scale/porta/pull/3627
Applying the suggestions in these comments: https://github.com/3scale/porta/pull/3627/files#r1423830312 https://github.com/3scale/porta/pull/3627/files#r1423832208

Refactor quickstarts

---

app/controllers/provider/admin/cms/templates_controller.rb
app/helpers/cms/form_helper.rb
app/views/provider/admin/cms/pages/_form.html.erb
app/views/provider/admin/cms/templates/update.js.erb
features/old/cms/pages.feature

Fix  to update a page after a validation error
https://issues.redhat.com/browse/THREESCALE-9316`
specified in JIRA

THREESCALE-9316: Fix CMS page update after error

---

features/api/alerts.feature
features/api/services/alerts.feature
features/old/api/applications/create_application.feature
features/old/applications/providers/search.feature
features/old/buyers/applications/create_application.feature
features/old/provider/admin/applications/create_application.feature
features/step_definitions/applications/applications_steps.rb

[THREESCALE-10507: Fix application steps](https://issues.redhat.com/browse/THREESCALE-10507)

🥒 Fix typo in application step

---

doc/liquid/drops.md
lib/developer_portal/lib/liquid/drops/message.rb

Follow-up for https://github.com/3scale/porta/pull/3673#discussion_r1460350656

Update the description of Message liquid drop

---

app/lib/three_scale/search.rb

just a (hopefully) clarification of the comment

clarify SPHINX_PAGE_SIZE_INFINITE comment

---

features/support/sphinx.rb

this is just a bugfix reporting sphinx/manticore start-up issues

proper output of Riddle::CommandResult

---

app/lib/three_scale/bot_protection/base.rb
app/lib/three_scale/bot_protection/controller.rb

Remove buggy methods from bot protection logic

Remove methods

---

.github/workflows/stale-prs.yml

Stale PRs action: increase warning times

---

app/controllers/admin/api/service_contracts_controller.rb

Refactoring suggestions for https://github.com/3scale/porta/pull/3672

Refactor service contracts API controller

---

features/api/services/application_plans/index.feature
features/api/services/service_plans/index.feature
features/buyers/account_plans/index.feature
features/support/helpers/capybara_helpers.rb

Don't know how to do this better...

avoid test timing issues

---

.circleci/config.yml
.tool-versions.sample
config/environments/production.rb
config/initializers/non_digest_assets.rb
fedora-manual-setup.md
openshift/system/Dockerfile
openshift/system/contrib/container-entrypoint
openshift/system/contrib/scl_enable
openshift/system/entrypoint.sh
osx-manual-setup.md
package.json
script/oracle/install-instantclient-packages.sh

This is CentOS 8 Stream upgrade to container image. I'm not sure whether reviewing each commit will be easier or just reviewing the whole file. I think that diff comparison will not work well. Better maybe the whole file.
Image is available at `quay.io/3scale/porta:stream8`
Update: the issue is that sphinx connection fails because we use MySQL 8 client libraries and try to connect sphinx compiled with MySQL 5.7 libraries. It seems like we will need to migrate to manticore server to upgrade to RHEL8. Or we can try mariadb libraries that I recollect working with both. But I'm uneasy to have such a mix.
Probably we need to go for manticore at some point anyway and making things more complicated by keep using RHEL7 for system or a mix of libraries doesn't make much sense.

[THREESCALE-1786] assets with node16 poc

---

app/controllers/api/proxy_rules_controller.rb
app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb
app/controllers/proxy_rule_shared_controller.rb
app/presenters/api/proxy_rules_index_presenter.rb
app/views/api/proxy_rules/index.html.slim
app/views/shared/proxy_rules/_body_section.html.slim
app/views/shared/proxy_rules/_header_section.html.slim
config/locales/en.yml
features/backend_apis/mapping_rules.feature
features/services/mapping_rules.feature
features/step_definitions/proxy_steps.rb
features/step_definitions/search_steps.rb
test/factories/proxy.rb
test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb

[THREESCALE-9809: Integration > Mapping rules table](https://issues.redhat.com/browse/THREESCALE-9809)
* apiconfig/services/:id/proxy_rules
* p/admin/backend_apis/:id/mapping_rules
Before:
After:

🦋 Toolbar for proxy rules

---

app/javascript/src/QuickStarts/templates/learnAboutAccounts.yaml
app/javascript/src/QuickStarts/templates/learnAboutApplications.yaml
app/javascript/src/QuickStarts/templates/learnAboutMetrics.yaml
app/javascript/src/QuickStarts/templates/learnAboutProducts.yaml

Reword alt text for images in Quick starts to fix typos and improve the wording

---

config/webpacker.yml

🧑‍💻 Remove annoying `webpack-dev-server` overlay

---

app/controllers/api/applications_controller.rb
app/controllers/buyers/applications_controller.rb
app/controllers/provider/admin/applications_controller.rb
app/javascript/src/Common/components/TableToolbar.tsx
app/javascript/src/Common/components/ToolbarAttributeSearch.tsx
app/javascript/src/Common/components/ToolbarGroupedSelect.tsx
app/javascript/src/Common/components/ToolbarSearch.tsx
app/javascript/src/Common/components/ToolbarSelect.tsx
app/lib/applications_controller_methods.rb
app/presenters/applications_index_presenter.rb
app/views/shared/applications/_listing.html.slim
features/provider/admin/applications/index.feature
features/step_definitions/search_steps.rb
features/support/helpers/capybara_helpers.rb
spec/javascripts/Common/components/ToolbarSelect.spec.tsx

* [THREESCALE-9961: Buyer applications table](https://issues.redhat.com/browse/THREESCALE-9964)
* [THREESCALE-9792: Product applications table](https://issues.redhat.com/browse/THREESCALE-9796)
* [THREESCALE-9966: Audience applications table toolbar](https://issues.redhat.com/browse/THREESCALE-9969)

🦋 Mega improvement for toolbar and applications table

---

app/views/finance/provider/settings/show.html.slim

🐛🦋 Fix cards separation in Charging & Gateway settings

---

app/lib/fields/patternfly_form_builder.rb
app/views/buyers/accounts/edit.html.slim
app/views/provider/admin/accounts/new.html.slim
app/views/provider/admin/backend_apis/forms/_naming.html.slim
app/views/provider/admin/backend_apis/new.html.slim
config/locales/en.yml
features/provider/admin/backend_apis/new.feature
features/step_definitions/backend_api_steps.rb
features/support/data_table_transforms.rb
features/support/paths.rb

[THREESCALE-10450: Backend APIs new page](https://issues.redhat.com/browse/THREESCALE-10450)
After:

🦋 New Backend page with Patternfly

---

app/assets/stylesheets/provider/_tables.scss
app/lib/fields/patternfly_form_builder.rb
app/views/buyers/accounts/_account_details.html.slim
app/views/buyers/accounts/_account_plan.html.erb
app/views/buyers/accounts/_change_plan.html.slim
app/views/buyers/accounts/_monthly_charging.html.erb
app/views/buyers/accounts/show.html.slim
app/views/buyers/applications/_widget.html.erb
app/views/master/providers/plans/_widget.html.slim
features/step_definitions/buyers/accounts/account_overview_steps.rb

[THREESCALE-10691: Update card layout](https://issues.redhat.com/browse/THREESCALE-10691)
Before:
After:
Before:
After:

🦋 Account overview layout (Cards)

---

app/assets/stylesheets/provider/_tables.scss
app/javascript/src/Plans/components/ChangePlanSelect.scss
app/javascript/src/Plans/components/ChangePlanSelect.tsx
app/views/provider/admin/applications/_change_plan.html.slim
app/views/provider/admin/applications/_details.html.slim
app/views/provider/admin/applications/_plan.html.erb
app/views/provider/admin/applications/show.html.slim
app/views/provider/admin/referrer_filters/_widget.html.erb

[THREESCALE-9902: Update card layout](https://issues.redhat.com/browse/THREESCALE-9902)
Before:
After:

🦋 Application overview layout (Cards)

---

lib/developer_portal/app/views/developer_portal/accounts/payment_gateways/show.html.liquid

Replaces #3756 
This is not a fix for THREESCALE 10972 but I've noticed the template is outdated and a bit wrong.

💧Update Payment Gateways template

---

app/assets/stylesheets/provider/_authentication_providers.scss
app/assets/stylesheets/provider/_forms.scss
app/controllers/provider/admin/account/authentication_providers_controller.rb
app/controllers/provider/admin/account/enforce_sso_controller.rb
app/javascript/packs/account_authentication_providers.ts
app/javascript/src/AuthenticationProviders/components/AccountAuthenticationProviders.tsx
app/javascript/src/AuthenticationProviders/components/AuthenticationProvidersTable.tsx
app/javascript/src/AuthenticationProviders/components/EnforceSSOSwitch.tsx
app/javascript/src/Plans/components/PlansTable.tsx
app/javascript/src/Types/index.ts
app/javascript/src/utilities/ajax.ts
app/javascript/src/utilities/patternfly-utils.tsx
app/javascript/src/utilities/test-utils.ts
app/presenters/provider/admin/account/authentication_providers_index_presenter.rb
app/validators/enforce_sso_validator.rb
app/views/provider/admin/account/authentication_providers/index.html.slim
config/locales/en.yml
features/provider/admin/account/sso_enforce.feature
features/step_definitions/provider_steps.rb
features/step_definitions/web_steps.rb
features/support/paths.rb
features/support/selectors.rb
spec/javascripts/AuthenticationProviders/components/AccountAuthenticationProviders.spec.tsx
spec/javascripts/AuthenticationProviders/components/AuthenticationProvidersTable.spec.tsx
spec/javascripts/AuthenticationProviders/components/EnableSSOSwitch.spec.tsx
spec/javascripts/utilities/ajax.spec.ts
test/integration/sso_enforce_flow_test.rb

[THREESCALE-9847: Account > Users > SSO Integrations](https://issues.redhat.com/browse/THREESCALE-9847)

🦋⚛️ Settings SSO Integrations to Patternfly 4

---

test/unit/event_store/event_test.rb

`test_failed_rolledback_with_transactional_callbacks` and `test_rolledback_harmless_exceptions_not_reported` fail with `ActiveRecord::RecordNotFound`

Dependabot/bundler/rails 6.1.7.7

---

config/initializers/oracle.rb
test/unit/oracle_hacks_test.rb

Either this or just skip using `with_lock` entirely.

fix #with_lock on oracle

---

test/unit/proxy_rule_test.rb

Tests were not being executed.

Enable tests

---

app/assets/javascripts/master_application.js

Removing some code that references non-existing routes and HTML elements.
-

Remove some dead JS code

---

app/views/provider/admin/onboarding/wizard/request/show.html.slim

Same as https://github.com/3scale/porta/pull/3813 but cherry-picked for `managed-services`.
https://issues.redhat.com/browse/THREESCALE-11067

[THREESCALE-11067] Onboarding wizard fix for `managed-services`

---

app/controllers/api/applications_controller.rb
app/controllers/buyers/applications_controller.rb
app/controllers/provider/admin/applications_controller.rb
app/helpers/applications_helper.rb
app/lib/applications_controller_methods.rb
app/presenters/applications_index_presenter.rb
app/views/api/applications/index.html.slim
app/views/buyers/applications/index.html.slim
app/views/provider/admin/applications/index.html.slim
app/views/shared/applications/_listing.html.slim
config/locales/en.yml
features/api/services/applications/index.feature
features/buyers/accounts/applications/index.feature
features/provider/admin/applications/bulk_operations.feature
features/provider/admin/applications/index.feature
features/site/settings.feature
features/step_definitions/custom_web_steps.rb
features/step_definitions/web_steps.rb
features/support/helpers/capybara_helpers.rb
features/support/selectors.rb
test/integration/api/applications_controller_test.rb
test/unit/helpers/applications_helper_test.rb
test/unit/presenters/applications_index_presenter_test.rb

* Service: https://issues.redhat.com/browse/THREESCALE-9797
* Audience: https://issues.redhat.com/browse/THREESCALE-9970
* Buyers: https://issues.redhat.com/browse/THREESCALE-9965
Before:
After:
And also empty search state:

🦋 Implement empty state in Applications index

---

features/developer_portal/admin/applications/credentials.feature
features/developer_portal/admin/applications/edit.feature
features/developer_portal/admin/applications/new.feature
features/developer_portal/cms_toolbar.feature
features/provider/admin/applications/show/application_details.feature
features/step_definitions/account_steps.rb
features/step_definitions/applications_steps.rb

This PR fixes the cucumber failures related with the changes made at `features/step_definitions/web_steps.rb` in #3841 .

🥒 Fix "should see the following details" errors

---

test/integration/provider/admin/applications/applications_controller_test.rb
test/integration/user-management-api/buyers_applications_test.rb

Trying to validate https://issues.redhat.com/browse/THREESCALE-10763

Add some test for custom app ids when creating applications

---

lib/three_scale/middleware/multitenant.rb
test/integration/master/api/providers_controller_integration_test.rb
test/integration/multitenant_enforcement_test.rb

there are more means master can authenticate which
tenant leak checker should recognize
fixes THREESCALE-11214

tenant checker should recognize master better

---

app/lib/logic/cms.rb
app/models/cms/template.rb
app/models/features_plan.rb
app/models/metric.rb
app/models/proxy_rule.rb
lib/three_scale/tenant_id_integrity_checker.rb
test/unit/tasks/multitenant/tenants_integrity_test.rb

Follow-up on #3875 
Adding things to ignores and adding `inverse_of`

more associations tidying

---

app/helpers/sites/legal_terms_helper.rb

Legal terms toggling link had a bug due to JQuery updates. There is also some pieces of code which could be removed, but that will be done in a different PR after some investigation.
[THREESCALE-9335](https://issues.redhat.com/browse/THREESCALE-9335)
1. Go to Audience -> Developer portal -> Legal terms -> Signup
2. Click on "Insert toggling code"
3. To save changes, click "update legal terms for Signup"
4. Now go to the developer portal. e.g: http://provider.3scale.localhost:3000/signup
5. At the bottom you should see "By signing up you agree to the following Legal Terms and Conditions (show)"
6. Confirm clicking on `show` expands legal terms and clicking `hide` hides legal terms

THREESCALE-9335: Developer portal: builtin toggling code for legal terms contains a Javascript bug

---

app/lib/three_scale/jobs.rb
test/unit/three_scale/middleware/cors_test.rb

simplify loading of safe YAML

---

app/javascript/packs/invoices_show.scss
app/views/buyers/invoices/show.html.erb
app/views/finance/provider/invoices/show.html.erb
app/views/finance/provider/shared/_invoice_header.html.erb
app/views/provider/admin/account/invoices/show.html.erb

Fixes missing css import in https://github.com/3scale/porta/pull/3848.
Before:
After:

Fix invoices css

---

app/views/provider/admin/account/invitations/index.html.erb
config/locales/en.yml

[THREESCALE-11425: Add empty state](https://issues.redhat.com/browse/THREESCALE-11425)
Before:
After:

🦋 Implement Empty State for Invitations

---

features/provider/dashboard.feature
features/step_definitions/window_steps.rb
features/support/hooks.rb

Hopefully fixes random cucumber failures because an element can't be found/interacted with. This is caused by sidebar covering some elements, because the screen is too narrow.
not reported
All cucumbers must pass, all the time. 

Resize browser width with a hook

---

app/views/shared/proxy_rules/_edit_form.html.slim

Just fixing some styles.
**Before:**
**After:**
-none-
Go to the Mapping Rule edit screen, and make sure it looks good.

Fix styles for mapping rules edit

---

.rubocop.yml

Just some leftovers from Ruby upgrade...

Update Ruby version in rubocop config

---

app/javascript/src/AuthenticationProviders/components/AccountAuthenticationProviders.tsx
app/javascript/src/AuthenticationProviders/components/AuthenticationProvidersEmptyState.tsx
features/provider/admin/account/authentication_providers/new.feature
jest.config.js
spec/javascripts/AuthenticationProviders/components/AccountAuthenticationProviders.spec.tsx
spec/javascripts/AuthenticationProviders/components/AuthenticationProvidersEmptyState.spec.tsx

[THREESCALE-11179: Account Settings > Users > SSO Integrations (Empty view)](https://issues.redhat.com/browse/THREESCALE-11179)
**Before**
**After**

🦋 THREESCALE-11179: Account Settings > Users > SSO Integrations (Empty view)

---

codecov.yml
test/unit/user_test.rb

A small fix in a test

---

app/controllers/provider/admin/messages/outbox_controller.rb
app/views/buyers/accounts/show.html.slim
app/views/provider/admin/messages/outbox/_form.html.slim
app/views/provider/admin/messages/outbox/new.html.slim

* Problem 1: in buyers/account -> new message the modal styles are missing.
* Problem 2: in messages/outbox/new the sidebar has the wrong item highlighted

Fix some problems with new message modal

---

app/controllers/api/alerts_controller.rb
app/models/alert.rb
lib/developer_portal/app/controllers/developer_portal/admin/applications/alerts_controller.rb

This should reduce the chances for a runoff background deletion processes.

fix issue with Alerts background deletion

---

app/javascript/src/Types/globals.d.ts

⚰️ removes old types from provider/utils

---

app/assets/stylesheets/provider/_buttons.scss
app/assets/stylesheets/provider/_colorbox.scss
app/assets/stylesheets/provider/admin/cms/_files.scss
app/assets/stylesheets/provider/admin/cms/_templates.scss
app/helpers/api/integrations_helper.rb
app/helpers/provider/admin/cms/email_templates_helper.rb
app/helpers/sites/legal_terms_helper.rb
app/lib/three_scale/semantic_form_builder.rb
app/views/api/features/_form.html.erb
app/views/api/pricing_rules/_form.html.erb
app/views/api/usage_limits/_form.html.erb
app/views/finance/provider/line_items/new.html.erb
app/views/provider/admin/cms/_content_tabs.html.erb
app/views/provider/admin/cms/builtin_legal_terms/_buttons.html.erb
app/views/provider/admin/cms/email_templates/_buttons.html.erb
app/views/provider/admin/cms/files/edit.html.erb
app/views/provider/admin/cms/files/new.html.erb
app/views/provider/admin/cms/layouts/new.html.erb
app/views/provider/admin/cms/pages/new.html.erb
app/views/provider/admin/cms/partials/new.html.erb
app/views/provider/admin/cms/sections/edit.html.erb
app/views/provider/admin/cms/sections/new.html.erb

Fix some button styles to get them more aligned with PF4 styles and fix some issues.
[THREESCALE-10072](https://issues.redhat.com/browse/THREESCALE-10072) was already fixed somehow, but I also adjusted the styles a bit.
The main fix is [THREESCALE-9455](https://issues.redhat.com/browse/THREESCALE-9455) - where the buttons overlap the image preview in the CMS.
Some before and after screenshots:
----
----
----
----
----
----
https://issues.redhat.com/browse/THREESCALE-9455
https://issues.redhat.com/browse/THREESCALE-10072

THREESCALE-10072 and THREESCALE-9455: Fix CMS (and other) buttons styles

---

app/assets/stylesheets/provider/_service_access.scss

**Before**
**After**
https://issues.redhat.com/browse/THREESCALE-11760
```
/p/admin/account/users/{ID}/edit
```

THREESCALE-11760: Add visualization lines for member permissions

---

Gemfile.lock

This is to work together with https://gitlab.cee.redhat.com/3scale/porta-midstream/-/merge_requests/1179

Upgrade bundler to 2.3.27

---

Gemfile.lock

This is for https://gitlab.cee.redhat.com/3scale/porta-midstream/-/merge_requests/1182

Use bundler 2.2.24 for 2.15

---

features/old/buyers/accounts/approving.feature
features/old/signup/account_activation_emails.feature

because more cucumbers need fixing...

More flaky cucumbers

---

bin/searchd
bin/testunit
fedora-manual-setup.md
osx-manual-setup.md

Setup instructions for latest porta and Fedora 42.

update setup docs

---

app/models/plan.rb
db/migrate/20250522195407_features_plans_index.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/test_helpers/provider.rb
test/workers/delete_object_hierarchy_worker_test.rb

avoid worst slow queries on delete
