app/services/import_countries_service.rb, test/unit/services/import_countries_service_test.rb
Right now `ImportCountriesService#call!` only rescues from `OpenURI::HTTPError` exceptions, which include 404 but not time out errors, for example. Without including time out errors, the step to import the list of countries using the Geonames API will fail to fallback to the static list of countries shipped with the code in some scenarios of disconnected deployment. This PR addresses this issue by including HTTP timeout errors to the fallback conditions of `ImportCountriesService`.
Closes [THREESCALE-4373](https://issues.redhat.com/browse/THREESCALE-4373)
=> Adds HTTP timeout errors to fallback conditions of ImportCountriesService

app/indices/account_index.rb, app/indices/cms_page_index.rb, app/indices/topic_index.rb, config/jobs.rb, config/schedule.rb, lib/tasks/openshift.rake
It does not create a thread for indexing anymore
All indexing is done real time in background with Sidekiq
To initialize an indexation, run `rake ts:clear ts:rebuild`
=> [sphinx] Remove thread in openshift:thinking_sphinx:start

lib/developer_portal/app/views/developer_portal/docs.html.liquid
Because a [while ago](https://github.com/3scale/porta/pull/1728) I did something very stupid.
=> Fix static text in the documentation liquid template

app/lib/logic/contracting.rb, app/models/account/buyer_methods.rb, app/models/contract.rb, app/models/topic.rb
Rails 5.0 has deprecated it https://github.com/rails/rails/commit/adfab2dcf4003ca564d78d4425566dd2d9cd8b4f
It is removed in rails 5.1
Cherry-picked from https://github.com/3scale/porta/pull/1669
To clean up the following warning:
=> Use distinct in relation instead of uniq

app/controllers/buyers/applications_controller.rb, app/views/buyers/applications/_listing.html.slim, test/integration/buyers/applications_controller_test.rb
Restrain the list of plans returned to a user, depending on his permissions. [This line](https://github.com/3scale/porta/blob/031493986866f026054a06c7b575c325cf8d446f/app/controllers/buyers/applications_controller.rb#L61) probably.
[THREESCALE-3268: Admin Portal member user with the access "Developer Accounts -- Applications" is able to create new Applications using the UI for Services they don't have permissions
](https://issues.redhat.com/browse/THREESCALE-3268)
See JIRA ticket.
=> Prevent creating application with forbidden plan in UI

app/controllers/master/service_discovery/auth_controller.rb, test/integration/master/service_discovery/auth_controller_test.rb
Also added the integration test for service_discovery/auth_controller.
Closes [THREESCALE-4851](https://issues.redhat.com/browse/THREESCALE-4851)
=> Allowing all parameters in the Service Discovery request

lib/tasks/openshift.rake
It was launched in the background, the rake task will exit and then stop the daemon
=> Do not detach the Sphinx daemon when starting

portafly/src/tests/components/pages/accounts/AccountsTable.test.tsx, portafly/src/tests/components/shared/data-list/DataListTable.test.tsx, portafly/src/tests/components/shared/data-list/examples/DataListTable.tsx
We were testing the Data List composed component within the Accounts index page and not by itself.
Related to https://github.com/3scale/porta/pull/1977
Complementary to fix https://issues.redhat.com/browse/THREESCALE-5430
=> [PortaFly] DataList component test

portafly/src/components/pages/accounts/AccountsTable.tsx, portafly/src/components/pages/accounts/utils/accountsTableDataFactory.tsx, portafly/src/dal/accounts/getDeveloperAccounts.ts, portafly/src/tests/components/pages/accounts/AccountsTable.test.tsx, portafly/src/tests/components/pages/accounts/utils/__snapshots__/accountsTableDataFactory.test.tsx.snap, portafly/src/types/index.d.ts
Removes features not needed in our first version of the account index.
https://github.com/3scale/porta/pull/1985 covers the missing tests.
Fixes: https://issues.redhat.com/browse/THREESCALE-5430
=> [PortaFly] Removing unused features from Account > Index

app/assets/javascripts/provider/cms/sidebar.js.coffee
**Jira Issue:**
https://issues.redhat.com/browse/THREESCALE-5382
Fix usage of Underscore's collection groupBy function in the sidebar for the CMS Content page of the Admin Portal.
Before:
After:
=> Fix CMS/Content sidebar

lib/tasks/openshift.rake
Remove .pid and .lock files in indices location
The pod could be stopped by openshift, leaving dirty artifacts
On new pod creation, indices cannot be used anymore as they are virtually locked
=> [openshift] Cleanup files When sphinx is not cleanly shutdown

app/lib/api_docs/account_data.rb, app/lib/api_docs/buyer_data.rb, app/lib/api_docs/provider_data.rb, test/unit/api_docs/account_data_test.rb
This is an alternative for how to pass service hosts to the JavaScript layer.
Instead of just one host, it provides with an array of all public URLs (sandbox endpoints), available both at Admin Portal and Developer Portal.
Format: `[{ name: <endpoint>, value: <service_id> }]`
**Admin Portal**
Developer **Portal**
The UI will have to find the service id in the list (`value` property) and fetch the corresponding endpoint (`name`) to replace the OAS host/servers with.
In cases where the ActiveDoc is not associated to any service, maybe one solution could be displaying all the options (if any) for the user to pick one. Alternatively, do nothing and use the original host. TBD.
=> Added service_hosts to json account data (active doc autocompletion)

app/representers/cinstance_representer.rb, spec/acceptance/api/application_spec.rb
We need these 2 fields for Patternfly Applications Index page.
[THREESCALE-5456: Update Applications endpoint to include missing data for Portafly](https://issues.redhat.com/browse/THREESCALE-5456)
Verify the response locally or from preview:
```
$ curl -v  -X GET "<URL>/admin/api/accounts.json?access_token=<TOKEN>"
```
=> Include 'plan_name' and 'org_name' in /admin/api/applications

app/models/go_live_state.rb
Oops 🙈 
I noticed when I briefly made a test reach there.
=> Remove reference to old mailer 'GoLiveNotification' removed in #1428

test/integration/api/integrations_controller_test.rb, test/unit/proxy_config_test.rb
We ignored the column, now it is in its BackendApi, which they all are supposed to have. According to this new reality, the tests should not rely on this column anymore. Especially now that it will be removed for real soon.
Needed for https://github.com/3scale/porta/pull/1979
=> Remove Proxy#api_backend column from tests

portafly/src/utils/http.ts
Makes `URLSearchParams` optional for API calls that don't have any.
=> Updates Portafly http utils

app/indices/account_index.rb, test/unit/account/search_test.rb
[Reopening from right branch, previous PR: [here](https://github.com/3scale/porta/pull/1847)]
Improve the Admin Portal User search feature in order to find users by email address even in case the address contains two-character strings separated by dots (e.g. test@mail.co.uk)
This isn't currently possible due to min_infix_len being set to 3 in thinking_sphinx.yml
[THREESCALE-632](https://issues.redhat.com/browse/THREESCALE-632) 
Go to the Admin Portal and create a user with email test@mail.co.uk
Force a reindex (or wait for it to happen automatically)
Make sure the user can be found via the seach feature by inserting test@mail.co.uk in the search bar
=> Improve the Admin Portal User search - THREESCALE-632

app/models/application_key.rb, test/unit/application_keys_test.rb
It fixes this:
```
{ 
exception: {
class: NoMethodError,
message: "undefined method `push_web_hooks_later' for nil:NilClass",
backtrace: [
"/home/bender/system_preview/releases/20200630090324/app/models/application_key.rb:164:in `push_webhook_key_destroyed'",
"/home/bender/system_preview/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:382:in `block in make_lambda'",
"/home/bender/system_preview/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:232:in `block in conditional'",
"/home/bender/system_preview/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:456:in `block in call'"
]
},
parameters: {
context: 'Job raised exception',
job: {
'class' => …
```
=> Do not push webhook when application key is destroyed by association

config/docker/settings.yml, openshift/system/config/settings.yml
So old user sessions ans stale objects (event store events and deleted objects) are removed automatically once a week on OpenShift.
Explains [THREESCALE-5464](https://issues.redhat.com/browse/THREESCALE-5464)
=> Enables Janitor cleanup worker by default on Openshift

config/initializers/sphinx.rb
Otherwise concurrent threads (e.g. sidekiq, puma) can deadlock while racing to obtain access to the mutex block at 
https://github.com/pat/thinking-sphinx/blob/2ae0c98b8b08242eb623e8eb5e364c4ed0fd3fcb/lib/thinking_sphinx/configuration.rb#L78-L91
This is known bug of ThinkingSphinx, [fixed](https://github.com/pat/thinking-sphinx/commit/814beb0aa3d9dd1227c0f41d630888a738f7c0d6) in v4.3.0+.
See
- https://github.com/pat/thinking-sphinx/issues/1051
- https://github.com/pat/thinking-sphinx/issues/1132
=> [sphinx] Ensures ThinkingSphinx preloads the all the indices upfront

app/javascript/packs/OAS3Autocomplete.js, app/javascript/src/Types/SwaggerTypes.jsx
Autocomplete of OAS 3 parameters fails, depending on the format of spec
`parameters` can be placed inside or outside the `get` object, but we are handling only the second scenario
```
{
"openapi": "3.0.2",
"info": {},
"paths": {
"/example/path": {
"parameters": []
}
}
}
```
```
{
"openapi": "3.0.2",
"info": {},
"paths": {
"/example/path": {
"get": {
"parameters": []
}
}
}
}
```
https://issues.redhat.com/browse/THREESCALE-5516
=> Bugfix: autocomplete params

portafly/portafly_api.yml
Extends our Open API Specification adding Account Settings > Users path
https://issues.redhat.com/browse/THREESCALE-4765 (mockups and analysis)
https://issues.redhat.com/browse/THREESCALE-4944 (OAS
=> Add Account settings Users path to Portafly OAS

app/mailers/account_mailer.rb
Just a refactor that I realized about while working with [THREESCALE-5541](https://issues.redhat.com/browse/THREESCALE-5541)
In fact, it is not exactly the same because it prevents the impersonation admin to pop up 😄
=> Refactor AccountMailer to use Account#admin_user

app/models/account.rb, app/views/notification_mailer/account_created.html.slim, app/views/notification_mailer/account_created.text.erb, app/views/notification_mailer/account_deleted.html.slim, app/views/notification_mailer/cinstance_cancellation.html.slim, app/views/notification_mailer/cinstance_expired_trial.html.slim, app/views/notification_mailer/cinstance_plan_changed.text.erb, app/views/notification_mailer/plan_downgraded.html.slim, app/views/provider_user_mailer/activation.text.erb, lib/developer_portal/lib/liquid/drops/account.rb, test/unit/liquid/drops/account_drop_test.rb
Removed completely from the model because it does not belong there and because it responds with the org_name, and if it is empty (which never happens!), would return the username of the admin_user.
The Account drop with display_name method stays because someone might be already using it, but with a comment.
All the rest of the references to display_name everywhere else become references to the organization name.
1st PR of [THREESCALE-5541](https://issues.redhat.com/browse/THREESCALE-5541)
=> Remove Account#display_name

app/representers/cinstance_representer.rb, spec/acceptance/api/application_spec.rb
We need `service_name` to show it in column _Product_. (see [mockups linked in the JIRA](https://issues.redhat.com/browse/THREESCALE-5421))
**What issue** 
[THREESCALE-5545: Update Applications endpoint (to include missing data for Portafly)](https://issues.redhat.com/browse/THREESCALE-5545)
```
curl -v  -X GET "<URL>/admin/api/accounts/<ACCOUNT_ID>/applications.json?access_token=<TOKEN>"
```
Should include `service_name`.
=> Include 'service_name' in /admin/api/accounts/:id/applications

portafly/src/App.tsx, portafly/src/components/LazyRoute.tsx, portafly/src/tests/components/LazyRoute.test.tsx
Some pages such as Account Overview need being passed props (la the account's own id). The current implementation of `LazyRoute` is too obscured and also its types not well defined.
Here's the aforementioned example implemented https://github.com/3scale/porta/pull/1998/files#diff-e4adad5bca8019703fcc2feecd1730c6R23-R30.
`useMemo` is also not really necessary and finally `React.Suspense` could be moved outside.
The component `LazyRoute` is therefore not really needed, but I preferred doing one step at a time. If the team agrees this PR can do the whole refactorization.
`yarn start` and navigate around, everything should work.
Looking at browser's react tools, only **one** route should be rendered at any time.
=> Refactor LazyRoute to support passing props better

config/schedule.rb, config/thinking_sphinx.yml, openshift/system/config/sidekiq_schedule.yml
Put it at 13:00 UTC for safety, monitoring queue growth in SaaS
=> [sphinx] Fix cron hour for sphinx enqueue

portafly/src/components/pages/accounts/AccountOverviewLink.tsx, portafly/src/components/pages/accounts/ExportAccountsButton.tsx, portafly/src/components/pages/accounts/utils/accountsTableDataFactory.tsx, portafly/src/dal/accounts/getDeveloperAccounts.ts, portafly/src/tests/components/pages/accounts/AccountOverviewLink.test.tsx, portafly/src/tests/components/pages/accounts/AccountsIndexPage.test.tsx, portafly/src/tests/components/pages/accounts/AccountsTable.test.tsx, portafly/src/tests/examples/developerAccounts.ts, portafly/src/tests/factories/developer-account.ts, portafly/src/types/account.d.ts, portafly/src/types/index.d.ts, portafly/src/types/utils.d.ts
Our key values (within PortaFly) should be `camelCased` in order to follow convention.
Fixes https://issues.redhat.com/browse/THREESCALE-5546
needed for a following PR about storing data coming from API calls in context state
=> [PortaFly] camelCasing props

config/application.rb, config/initializers/sphinx.rb
Prevents failing with wrong number of arguments at `Fields::Fields::ActiverecordOverrides#initialize`.
```
ArgumentError: wrong number of arguments (given 2, expected 0..1)...
Failure:
test_find_by_domain!_raises_an_exception_if_domain_is_blank_even_if_there_is_an_account_with_blank_domain(Account::ProviderDomainsTest) [/opt/app-root/src/project/vendor/bundle/ruby/2.5.0/gems/state_machines-activerecord-0.5.2/lib/state_machines/integrations/active_record.rb:461]:
ArgumentError: wrong number of arguments (given 2, expected 0..1)
app/lib/fields/fields.rb:107:in `initialize'
test/unit/account/provider_domains_test.rb:73:in `block in <class:ProviderDomainsTest>'
```
This was actually the right fix to https://app.circleci.com/pipelines/github/3scale/porta/12581/workflows/1082990c-d295-4d66-83f9- …
=> Preloads Sphinx indices Rails after initialization

config/schedule.rb, openshift/system/config/sidekiq_schedule.yml
After discussion this is not needed at all, we trust in the real time indexation
=> Remove sphinx indexation every week

test/unit/csv/buyers_exporter_test.rb
This way, it will ensure that I do not mess up in https://github.com/3scale/porta/pull/2024 as part of [THREESCALE-5541](https://issues.redhat.com/browse/THREESCALE-5541)
=> Test Csv::BuyersExporter#values_for_account without any user

app/models/proxy.rb, test/unit/proxy_test.rb
Closes [THREESCALE-1408](https://issues.redhat.com/browse/THREESCALE-1408)
It should comply with [RFC 2616 Section 14](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23)
Thanks to Gui for letting me know how to find it in the UI 😄 
It is in `http://provider-admin.example.com.lvh.me:3000/apiconfig/services/2/integration/edit` (without APIAP), in `AUTHENTICATION SETTINGS` -> `SECURITY` -> `Host Header`
You can write there for example `my-own.api.example.net:8080` and click on `Update & test Staging Environment`. Reload the page and see that the `Host Header` has been updated correctly.
=> Change validation for Host Header to support <host>:<port>

app/controllers/admin/api/accounts_controller.rb, test/integration/admin/api/accounts_controller_test.rb
Fix 1st error reported by QE in [THREESCALE-5390](https://issues.redhat.com/browse/THREESCALE-5390)
Explained in [this comment in Jira](https://issues.redhat.com/browse/THREESCALE-5390?focusedCommentId=14242400&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14242400)
I do not know how the email can be nil according to our validations but anyway it sounds like a good idea to me performance-wise to not do a search in the DB of empty user emails when the param has not been sent.
=> API Account find without params should not try to find a 'nil' email

portafly/src/App.tsx, portafly/src/utils/http.ts
⚠️ This is blocking #2058 
Adds PUBLIC_URL to the router
Fixes error in `craftRequest` when API_HOST is undefined
=> Fix HTTP utils and add PUBLIC_URL

.circleci/config.yml, portafly/.eslintrc.js, portafly/config/webpack.config.js, portafly/package.json, portafly/src/components/AppLayout.tsx, portafly/src/components/pages/Overview.tsx, portafly/src/components/pages/applications/ApplicationsTable.tsx, portafly/src/components/shared/data-list/SearchWidget.tsx, portafly/src/i18n/locales/en/audience/accounts/listing.yml, portafly/src/tests/components/SwitchWith404.test.tsx, portafly/src/tests/components/shared/data-list/SearchWidget.test.tsx, portafly/src/tests/components/shared/data-list/__snapshots__/SearchWidget.test.tsx.snap, portafly/src/tests/components/util/AlertContext.test.tsx, portafly/src/tests/custom-render.tsx, portafly/src/utils/reducers.ts
We need to have `CI=true` when building in CircleCI
We need to remove some eslint warnings for that (and pass our config, not React's, to webpack)
**Warnings in tests are OK!**
They are ignored by `yarn build` and therefore we should worry about them at development time only.
1. This should work locally:
```
CI=true yarn build
```
2. CircleCI should pass as well
=> Fix eslint warnings and re-enable CI env var for yarn build

portafly/src/i18n/i18n.tsx
Only for development. It's super convenient to keep track of missing strings (and other errors like typos).
=> Set i18n debug mode

portafly/doc/ux_specs/accounts/account_applications_index.md, portafly/doc/ux_specs/accounts/index.md, portafly/doc/ux_specs/product/applications/index.md, portafly/src/components/pages/accounts/utils/accountsTableDataFactory.tsx, portafly/src/components/pages/applications/utils/applicationsTableDataFactory.tsx
* Add Width modifiers to define column distribution rules for Accounts index page
* Add Width modifiers to define column distribution rules for Applications index page
* Add column distribution rules in UX specs files for pages that include a table
=> Update width in tables

portafly/src/tests/utils/http.test.ts, portafly/src/utils/http.ts
`craftRequest` should work regardless of API_HOST being defined. For local for instance we need it but for a production environment such as Openshift we don't.
😓
=> 🐛 Fix HTTP utils

app/models/pricing_rule.rb, config/locales/en.yml, test/unit/pricing_rule_test.rb
changing the error message when setting pricing rules
https://issues.redhat.com/browse/THREESCALE-5565
=> Changing error message when setting pricing rules

portafly/.dockerignore, portafly/Dockerfile, portafly/openshift/deploymentconfig.yml, portafly/openshift/imagestream.yml, portafly/openshift/route.yml, portafly/openshift/service.yml
- Adds a Dockerfile to build Portafly independently from Porta
- Adds examples of Openshift ImageStream, DeploymentConfig, Service and (provider) Route to deploy Portafly
Depends on https://github.com/3scale/porta/tree/portafly/fix_http_url
----
Deployed to Openshift:
=> [portafly] Dockerfile and openshift definitions

config/locales/en.yml
Fixes this:
This fix is not pointing to the latest version.
An alternative approach would be not linking anywhere.
=> [Bugfix] Broken link to Documentation of Openshift#creating-routes

app/models/user.rb, test/unit/user_test.rb
Closes [THREESCALE-5686](https://issues.redhat.com/browse/THREESCALE-5686)
=> Find user with an invalid value returns 'nil' instead of crashing

app/controllers/buyers/accounts_controller.rb, app/lib/logic/signup.rb, app/lib/signup/result.rb, test/integration/buyers/accounts_controller_test.rb
Fixes issues 1 & 2 of [THREESCALE-5678](https://issues.redhat.com/browse/THREESCALE-5678)
=> Better error messages for creating a Buyer Account from the admin portal UI

app/javascript/packs/OAS3Autocomplete.js
In a previous PR (https://github.com/3scale/porta/pull/2022) we added support for `get` methods in paths, but other methods as `post`, `put`, or `delete` are missing.
https://issues.redhat.com/browse/THREESCALE-5516
Go to ActiveDocs and create a new OAS 3 spec, you can use this example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.json
All paths should work fine
Also tests with our Echo Api default example, autocomplete should still work
=> OAS autocomplete: Supporting all methods, not just get

db/migrate/20200629105416_remove_end_user_plans_table.rb, db/migrate/20200629110740_remove_postgres_procedure_end_user_plans_tenant_id.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
I've noticed by running https://github.com/3scale/porta/pull/1979 in Preview that this can be done outside the maintenance window. It is non-blocking and quick 😄
=> Remove EndUserPlans table (and Postgres' procedure)

app/models/proxy.rb, app/services/service_creator.rb, app/services/uri_shortener.rb, config/locales/en.yml, test/integration/api/services_controller_test.rb, test/unit/proxy_test.rb, test/unit/services/service_creator_test.rb, test/unit/services/uri_shortener_test.rb
It will automatically shorten host labels of system-generated proxy endpoints, that exceed the 63-char limit imposed by RFC-1035.
Closes [THREESCALE-5089](https://issues.redhat.com/browse/THREESCALE-5089)
=> Uri shortener for long host label endpoints

portafly/openshift/imagestream.yml
It fixes for Portafly's Openshift ImageStream the source to quay.io/3scale/portafly:latest, now that the repo was created.
=> Fix Portafly source for the Openshift ImageStream

app/models/proxy.rb, test/unit/backend/model_extensions/service_test.rb, test/unit/proxy_test.rb, test/unit/tasks/proxy_test.rb, test/workers/proxy_config_affecting_change_worker_test.rb
The exclamation sign, close to “Integration” in the sidebar menu of the Admin Porta and also in the Dashboard, is showing up for API products just created, right after finishing the provider wizard. This should not happen and neither it was when ProxyConfigAffectingChanges were first introduced. I guess some change later on caused the creation of the proxy’s affecting change history to be postponed to _after_ the creation of the first proxy config itself – likely #1658.
This PR ensure the proxy’s affecting change history exists since creation of the proxy object.
=> Fix proxy config affecting change on create

app/controllers/provider/admin/onboarding/wizard/request_controller.rb, app/forms/onboarding/request_form.rb, app/services/proxy_test_service.rb, test/integration/provider/admin/onboarding/wizard/request_controller_test.rb, test/unit/forms/onboarding/request_form_test.rb, test/unit/services/proxy_test_service_test.rb
Tests requests in the Admin Portal onboarding wizard are currently broken for 2 reasons:
1. It does not take into account the API backend usage routing paths and keeps sending the request to `<sandbox_endpoint>/<api_test_path>`.
2. Even when the test request works, if the response contains characters that are not ideally escaped by `CGI.escape`, or if it's too long, the next screen of the wizard breaks with a 502 or 414 error message (respectively).
This PR addresses these two issues. It ensures a proper APIAP-compatible URL is built for the test request, including the chosen routing path and API test path (1st issue). It also encodes and truncates the test API response before carrying it along to the next step of the wizard, thus preventing from a long or poorly encoded response body …
=> Fixes wizard's test request

app/controllers/api/proxy_configs_controller.rb, app/decorators/proxy_config_decorator.rb, app/views/api/proxy_configs/index.html.slim, test/decorators/proxy_config_decorator_test.rb, test/integration/api/proxy_configs_controller_test.rb
=> Move '.decorate' from view to controller in api/proxy_configs/index

config/initializers/cve-2020-8165.rb, test/cves/cve-2020-8165_test.rb
Monkey patches Rails prior to v5.2.4.3 with the [recommended changes](https://groups.google.com/group/rubyonrails-security/attach/1c0cea804792a/5-2-cache-storage.patch?part=0.1) of [CVE-2020-8165](https://groups.google.com/g/rubyonrails-security/c/bv6fW4S0Y1c).
Closes [THREESCALE-5318](https://issues.redhat.com/browse/THREESCALE-5318)
=> [CVE-2020-8165] Patch: Unintended unmarshalling in ActiveSupport

app/controllers/stats/data/base_controller.rb, app/lib/stats/views/usage.rb, test/functional/stats/data/applications_controller_test.rb, test/functional/stats/data/services_controller_test.rb, test/integration/stats/authentication_test.rb, test/integration/stats/data/applications_test.rb, test/integration/stats/data/base_controller_test.rb, test/integration/stats/data/requests_to_api_test.rb
Adds Rails strong params validation to stats/data usage and usage_response_code actions.
It affects essentially analytics requests for services (API products), API backends and applications, both UI and API.
Makes it consistent with the 3scale api docs where the `since` parameter is a required param.
_Missing:_ support for the use case of the `range` param (undocumented):
https://github.com/3scale/porta/blob/ff0b72315fcd58397aeac04aa254ad6c66376f52/app/lib/stats/views/usage.rb#L148
---
Closes [THREESCALE-5798](https://issues.redhat.com/browse/THREESCALE-5798).
=> Strong params for stats data controllers

app/controllers/buyers/invitations_controller.rb, app/controllers/provider/admin/account/invitations_controller.rb, app/helpers/invitations_helper.rb, app/models/invitation.rb, app/views/buyers/invitations/index.html.erb, app/workers/send_user_invitation_worker.rb, features/step_definitions/providers/invitations_steps.rb, test/unit/invitation_test.rb, test/workers/send_user_invitation_worker_test.rb
Invitation delivery is notified as "successfully sent" when it really isn't.
1. Change the message to "it will be sent"
2. Update the colum `sent_at` only after the email has been sent by the Mailer
[THREESCALE-4360: Using "Invite New User" button, no verification that email is sent](https://issues.redhat.com/browse/THREESCALE-4360)
1. Go to `p/admin/account/invitations` and create a new invitation.
2. The notification should say it will be sent
3. Refresh and check the column `Sent` shows the correct value (perhaps blanks at first, email should be sent not inmediately)
=> Deliver invitations async and fix notification message

app/helpers/cms/url_helper.rb, app/views/admin/api_docs/base/active_docs.html.erb, app/workers/zync_worker.rb
Having these references to `ThreeScale.config.dev_gtld` that we left behind in the code will cause the following problems in dev env:
1. Provider endpoint passed in the Zync update tenant payload has a wrong trailing `.{dev_gtld}` termination, making Zync to fail to fetch data fro Porta
2. The link to non-OAS ActiveDocs preview page will be wrong in the UI
3. Links to draft and published pages of the CMS from the Admin Portal will be broken
The solution here proposed is far from ideal because we still have the Rails server port (3000) hard-coded, but it's a quick and easy fix for the dev_gtld part of the issue, so we don't get blocked in dev.
=> [hotfix] Remove dev_gtld refs left behind

test/unit/tasks/impersonation_admin_user_test.rb
The fix drops the assertion that used to check if ALL impersonation admin users were updated (as expected according to implementation), but this is OK because:
1. It still asserts that users expected to be affected are indeed affected, with chance of missing correspondence with ALL only in case of creation of another 3scaleadmin user by a concurrent test.
2. It still asserts that users NOT expected to be affected remain untouched.
The previous assertion was based on a fixed number of expected user records in the database, which was causing random failures.
---
**Alternative**
We could remove this rake task as it's not used anymore https://github.com/3scale/porta/blob/master/lib/tasks/impersonation_admin_user.rake
In case we do, make sure to ping @3scale/documentation, though I think this …
=> Fix random failure in impersonation_admin_user:update rake task test

app/models/account/buyer_methods.rb, app/models/account/states.rb, app/views/buyers/accounts/show.html.slim, app/workers/process_notification_event_worker.rb, test/integration/buyers/accounts_controller_test.rb
When you first delete tenant and after want you try to suspend it 404 page is displayed and tenant cannot be suspended.
Note: Login as master
https://issues.redhat.com/browse/THREESCALE-5738
1. Login as master
2. Create new tenant
3. Go to /buyers/accounts/{tenant_id}/edit and delete tenant
4. Go to /buyers/accounts/{tenant_id} and try to suspend tenant
**Before:**
**After:**
=> Not displaying suspend button when tenant is deleted

app/indices/proxy_rules_index.rb, test/unit/indices/proxy_rules_indices_test.rb, test/unit/queries/proxy_rule_query_test.rb
**What this PR does**:
> fix for THREESCALE-5817: adds some special characters to the indexing charset in order to allow searching proxy rules like `/v1.0.0/test` with perfect match queries (e.g. search query = `/v1.0.0/test`)
=> THREESCALE-5817

app/javascript/packs/OAS3Autocomplete.js
When doing autocompletion of OAS3 specs, the description and responses of the paths were missing
**BEFORE:**
**AFTER:**
https://issues.redhat.com/browse/THREESCALE-5516
Go to ActiveDocs and create a new OAS 3 spec, you can use this example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.json
=> OAS Autocomplete: Fixing missing description and responses in path

app/controllers/admin/api/api_docs_services_controller.rb, app/models/api_docs/service.rb, test/integration/admin/api/api_docs_services_controller_test.rb, test/unit/api_docs/service_test.rb
- index only includes accessible api docs specs
- show, update and delete will throw `404 Not Found` if api docs spec is not accessible
- create and update will return `422 Unprocessable Entity` if `service_id` param is not of an accessible service
- account-level api docs specs remain accessible
Close [THREESCALE-5884](https://issues.redhat.com/browse/THREESCALE-5884)
=> Apply member permissions to Admin API's ActiveDoc Specs endpoints

app/controllers/admin/api/api_docs_services_controller.rb, app/controllers/admin/api_docs/base_controller.rb, app/controllers/frontend_controller.rb, app/controllers/provider/admin/dashboards_controller.rb, app/models/service.rb, app/models/user.rb, app/views/admin/api_docs/base/_form.html.slim, test/integration/admin/api/api_docs_services_controller_test.rb, test/integration/admin/api_docs/account_api_docs_controller_test.rb, test/integration/admin/api_docs/service_api_docs_controller_test.rb, test/unit/service_test.rb, test/unit/user_test.rb
**What this PR do**
**What this PR does NOT do**
- Permission-level access control other than the ones mentioned above
Closes [THREESCALE-952](https://issues.redhat.com/browse/THREESCALE-952) and a small part of [THREESCALE-5867](https://issues.redhat.com/browse/THREESCALE-5867)
=> Fix member users can manage service resources without permission

portafly/src/i18n/locales/en/account_settings/personal/personal_details.yml, portafly/src/i18n/locales/en/shared.yml
> Lists UI Strings for Account settings > Personal > Personal details
> `fixes #<4835>`
> None
- UI Strings Jira: [THREESCALE-4835](https://issues.redhat.com/browse/THREESCALE-4835)
- Most of the strings contain text similar to the mockup.
- For strings different to the mockup, you will see this tag: [PROPOSED]
=> 4835-Account_Personal_Details: User details form, modal, and change password.

Gemfile.base, Gemfile.lock, Gemfile.prod.lock, app/lib/backend/random_data_generator.rb, app/lib/backend_client.rb, app/workers/report_traffic_worker.rb, test/unit/backend_client_test.rb
So we can use a different port than 80 or 443 in backend
Fixes:
```
Failed to open TCP connection to http://backend-listener-internal:80:80
(getaddrinfo: Name or service not known
```
* Update 3scale_client to 2.11 to set backend port
=> [backend_client] Allow setting port from :host configuration

portafly/src/components/pages/Overview.tsx, portafly/src/components/pages/applications/utils/applicationsTableDataFactory.tsx, portafly/src/dal/applications/getApplications.ts, portafly/src/i18n/locales/en/account_settings/personal/personal_details.yml, portafly/src/i18n/locales/en/account_settings/users/listing-invitations.yml, portafly/src/i18n/locales/en/applications/listing.yml, portafly/src/i18n/locales/en/audience/accounts/account.yml, portafly/src/i18n/locales/en/audience/accounts/listing.yml, portafly/src/i18n/locales/en/overview.yml, portafly/src/i18n/locales/en/product.yml, portafly/src/i18n/locales/en/shared.yml, portafly/src/tests/components/pages/applications/utils/__snapshots__/applicationsTableDataFactory.test.ts.snap, portafly/src/tests/factories/applications.ts
* Fixes a typo from another PR `org_name -> orgName`
* Fixes a typo in a personal_details.yaml `proced -> proceed`
* Fixes indentation in Yaml
* Remove redundant translations variables that cause warnings when building
=> Fixes typo and Yaml

package.json, yarn.lock
We have some critical vulnerabilities in nested dependencies:
- `serialize-javascript`, dependency of `webpack` ([see advisory](https://www.npmjs.com/advisories/1548))
- `dot-prop` , dependency of `@rails/webpacker`  ([see advisory](https://www.npmjs.com/advisories/1213))
As we can't update webpack and webpacker to the 5.x branch (we should upgrade to rails 5.2 first) we need to use selective dependency resolutions.
This is a follow-up of https://github.com/3scale/porta/pull/2091
None
`yarn clean && yarn install`
=> Update serialize-javascript and dot-prop nested dependencies

Gemfile.base, Gemfile.lock, Gemfile.prod.lock, config/docker/unicorn.rb, config/initializers/sidekiq.rb, config/routes.rb, config/unicorn/development.rb, lib/prometheus_exporter_port.rb
Have another endpoint for yabeda-sidekiq /yabeda-metrics
Also use prometheus mmap client to share metrics between processes
Use environment variable `prometheus_multiproc_dir` 
Requires https://github.com/3scale/deploy/pull/679
=> Access yabeda metrics in unicorn

app/controllers/api/applications_controller.rb, app/controllers/buyers/applications_controller.rb, app/controllers/buyers/service_contracts_controller.rb, app/controllers/finance/provider/invoices_controller.rb, app/controllers/provider/admin/messages/inbox_controller.rb, app/controllers/provider/admin/messages/outbox_controller.rb, app/controllers/provider/admin/messages/trash_controller.rb, app/decorators/contract_decorator.rb, app/decorators/invoice_decorator.rb, app/decorators/message_decorator.rb, app/decorators/message_recipient_decorator.rb, app/helpers/buyers/accounts_helper.rb, app/helpers/messages_helper.rb, app/views/buyers/applications/_listing.html.slim, test/decorators/invoice_decorator_test.rb, test/decorators/message_decorator_test.rb, test/decorators/message_recipient_decorator_test.rb, test/unit/helpers/messages_helper_test.rb
Closes [THREESCALE-5813](https://issues.redhat.com/browse/THREESCALE-5813)
It is a bit risky because I do not know if I didn't realize about any Controller using this Helper.
After removing the `.decorate` from the helper, I've changed only the minimum necessary to make it work.
https://github.com/3scale/porta/pull/2106#issuecomment-694251124
Since it is a sensitive issue. We tested in preview to confirm that it keeps working, by checking these scenarios:
1. make sure invoices have no problem to be rendered in the UI
2. the generation of the invoice PDF
=> Remove '.decorate' from Helpers

app/controllers/provider/sessions_controller.rb, test/integration/provider/sessions_controller_test.rb, test/integration/sso_enforce_flow_test.rb
Automatically redirect users to SSO if it is enforced
closes https://issues.redhat.com/browse/THREESCALE-2795
output
1. **When SSO is configured but not enforced**
2. **when only one SSO integration is configured and enforced**
3. **when more than one SSO integration is configured but not enforced**
4.**when more than one SSO integration is configured and enforced**
=> Automatically redirect users to SSO if it is enforced

app/controllers/admin/api/backend_apis/base_controller.rb, app/controllers/admin/api/backend_apis_controller.rb, app/controllers/provider/admin/backend_apis/base_controller.rb, app/controllers/provider/admin/backend_apis_controller.rb, app/models/account/provider_methods.rb, app/models/user.rb, config/abilities/master_admin.rb, config/abilities/provider_admin.rb, config/abilities/provider_member.rb, config/initializers/cancan_hacks.rb, test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb, test/integration/admin/api/backend_apis/metric_methods_controller_test.rb, test/integration/admin/api/backend_apis/metrics_controller_test.rb, test/integration/admin/api/backend_apis_controller_test.rb, test/integration/admin/api/services/backend_usages_controller_test.rb, test/integration/api/backend_usages_controller_test.rb, test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb, test/integration/provider/admin/backend_apis/metrics_controller_test.rb, test/integration/provider/admin/backend_apis_controller_test.rb, test/unit/abilities/master_admin_test.rb, test/unit/abilities/provider_admin_test.rb
Permission-level control over the API backend section endpoints of the Admin Portal and Admin API.
API backends are not scoped by service (API product) and it is not possible to do member access control at the API backend level the way we do for services at the service-level. Therefore, here we are simply enforcing that only member users with the “Integration & Application Plans” permission can access the API backend section.
Creating and deleting API backends remain admin users-exclusive.
| Resource                                | Action                                         | Required permission |
|-----------------------------------------|------------------------------------------------|-----------------|
| ☑︎ backend api                           | new backend api …
=> Require 'plans' permission for member users to manage API backends

app/controllers/api/services_controller.rb
Unused since https://github.com/3scale/porta/pull/2178/files#diff-01277c9f472ebf2c339e13f600d053b4L61
=> Remove unused method Api::ServicesController#integration_method_changed?

app/javascript/packs/OAS3Autocomplete.js, app/javascript/src/Types/SwaggerTypes.jsx
Autocomplete of 3scale data is failing in some OAS specs because of the following reason:
The `parameters` can be placed in several places:
In the path object, like:
```
"paths": {
"/": {
"parameters": [],
"get": {},
"post": {}
...
}
}
```
Inside the http verbs, like:
```
"paths": {
"/": {
"get": {
"parameters": []
},
"post": {}
...
}
}
```
Or inside both the path and the verb, like:
```
"paths": {
"parameters": [],
"/": {
"get": {
"parameters": []
},
"post": {}
...
}
}
```
This PR adds support for the 3 scenarios
https://issues.redhat.com/browse/THREESCALE-6088
Go to API > ActiveDocs
Create a new valid OAS 3 spec (or better use the [default Echo …
=> Bugfix: autocomplete support for common  parameters in path

app/controllers/api/services_controller.rb, app/controllers/provider/admin/backend_apis_controller.rb, app/views/api/services/index.html.slim, app/views/provider/admin/backend_apis/index.html.slim, config/routes.rb, test/integration/api/services_controller_test.rb, test/integration/provider/admin/backend_apis_controller_test.rb
Products/Backends lists are being taken out from the Dashboard into their own pages. This is only the Rails part of it.
[APPDUX-545: Implement Ruby code for Product / Backend Apis](https://issues.redhat.com/browse/APPDUX-545)
=> Add Product and Backends index

app/decorators/application_decorator.rb, app/decorators/backend_api_decorator.rb, app/decorators/service_decorator.rb, app/helpers/menu_helper.rb, app/javascript/packs/api_selector.js, app/javascript/packs/navigation.js, app/javascript/src/Navigation/components/ContextSelector.jsx, app/javascript/src/Navigation/styles/ContextSelector.scss, app/javascript/src/utilities/useClickOutside.js, app/views/shared/_api_selector.html.slim, spec/javascripts/Navigation/ContextSelector.spec.jsx, spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
As part of the improvements in the Dashboard, we're removing the list of services and searchbar inside the ContextSwitcher.
[Address UI scalability issues in API Management Service](https://issues.redhat.com/browse/APPDUX-462)
=> Removes services from the ApiSelector (aka ContextSwitcher)

app/controllers/admin/api/services_controller.rb, db/migrate/20200921135637_add_index_to_services_account_id_and_state.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb, test/factories/simple.rb, test/integration/admin/api/services_controller_test.rb
1st part of [THREESCALE-4528](https://issues.redhat.com/browse/THREESCALE-4528)
Not sure if it is a good idea because there are people already using this API and this is a breaking change, but to some extend it is necessary because no matter how much we optimize, there is always a limit of what we are able to load and respond at once.
1. Create many services, for different accounts, and keeping in mind that a few services must have state 'deleted'.
Still not keeping in mind the **permitted_for**.
`bundle exec rails console` and run:
```ruby
tenant_1st = Account.tenants.first!
def create_tenant(signup_params)
begin
Signup::ProviderAccountManager.new(Account.master).create(signup_params)  
rescue ThreeScale::Core::APIClient::ConnectionError  , ThreeScale::Core::APIClient::JSONError
end …
```
=> Improve performance in API Services List

app/controllers/admin/api/account/proxy_configs_controller.rb, config/routes.rb, test/integration/admin/api/account/proxy_configs_controller_test.rb
Last part of [THREESCALE-4528](https://issues.redhat.com/browse/THREESCALE-4528)
Depends on the other PRs of the issue.
APIcast needs to fetch all proxy configs of a provider and doing so by fetching first all its services (just for its IDs) and then doing an API request to proxy configs for each service is just a too slow approach.
=> API Endpoint Provider ProxyConfig List

app/indices/backend_api_index.rb, app/indices/service_index.rb, app/models/backend_api.rb, app/models/service.rb
It works. It needs to be polished and add a test. I'll do it in the next PR.
1. Clear config, configure and run Sphinx. `rake ts:clear ts:configure && bundle exec rake openshift:thinking_sphinx:start`
2. Run rails server. `RAILS_LOG_TO_STDOUT=1 UNICORN_WORKERS=8 bundle exec rails server -b 0.0.0.0`
3. Run Sidekiq. Consider cleaning pending stuff that you don't care about first (with `redis-cli flushall`). `bundle exec sidekiq -q default -q low -q critical -L log/sidekiq.log`. We are interested in the default queue for this.
4. Enqueue indexations.  `bundle exec rake sphinx:enqueue`
When the indexations are done, feel free to test the search.
=> [Hotfix] Sphinx search Service & BackendAPI

lib/system/database.rb
[Add 'stat' to the connection pool abstract adapter.](https://issues.redhat.com/browse/THREESCALE-5698?focusedCommentId=15309911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15309911)
[Copy-paste from the original method](https://github.com/rails/rails/commit/35b6898f7cb5223e1de4edc1b4539e05dfd83d41#diff-642b90553b888bd2c724c093a1a685a5408a7d8293f3751366c25dc548936eb7R588) (Rails 5.1).
MySQL
Postgres
Oracle
=> ConnectionPool prepend 'stat' method

features/old/services/switch.feature
Known bug for 2.10 ER1
The bug is that we are redirecting to the services' new page always whether the customer has the switch multiple_services or not, and if it does not have it, the response is 'access denied' page.
The right workflow if the mutliple_services is not allowed, is showing the message to upgrade plan as we used to.
=> Skip multiple services upgrade message cuke

Gemfile.lock, Gemfile.prod.lock, lib/developer_portal/developer_portal.gemspec
Part of [THREESCALE-401](https://issues.redhat.com/browse/THREESCALE-401) & [THREESCALE-4053](https://issues.redhat.com/browse/THREESCALE-4053)
Updating Liquid step by step, version by version.
This one is an easy one.
These are the only [differences](https://github.com/Shopify/liquid/compare/v3.0.5...v3.0.6) between the current version and the one of this PR:
=> Bump Liquid to 3.0.6

lib/tasks/sphinx.rake
Part of [THREESCALE-6214](https://issues.redhat.com/browse/THREESCALE-6214)
The purpose of this PR is not having to index all models when we only want to index a specific model.
=> Sphinx indexation rake task accepts param for specific classes to index

app/views/provider/admin/backend_apis/show.html.slim, test/integration/provider/admin/backend_apis_controller_test.rb
Start by editing an API backend like this:
Without the fix:
With the fix:
Closes [THREESCALE-5623](https://issues.redhat.com/browse/THREESCALE-5623)
=> Fix XSS in the API backend Overview page

.codeclimate.yml
Apparently our codeclimate config file is outdated. Changes:
> In the Fall of 2017, we launched our newest analysis model, which introduced our 10 maintainability checks. With the new model, we've launched a new configuration version which requires updated syntax. A few things to note when updating an older configuration file:
> 
> - version: "2" is required at the top of the .codeclimate.yml.
> - engines has been changed to plugins.
> - checks has been introduced. All maintainability checks are enabled by default, but can be disabled or tuned individually under the checks node.
> - exclude_paths has been changed to exclude_patterns.
> - ratings has been deprecated. All files in our supported languages for maintainability will receive maintainability ratings by default.
(Full article can …
=> 👷 bump codeclimate version

app/javascript/src/Navigation/components/ContextSelector.jsx, spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
As requested by QE and also to be consistent with PF components, we're adding the class `pf-m-expanded` to the dropdown.
This doesn't interfere with any existing styles.
=> Add "is-expanded" class in Context Switcher for easier testing

app/helpers/menu_helper.rb, app/javascript/src/Navigation/components/ContextSelector.jsx, app/views/shared/_api_selector.html.slim, app/views/shared/provider/_header.html.slim, features/old/accounts/accounts.feature, features/old/accounts/password_change.feature, features/old/accounts/personal_details.feature, features/old/providers/invitations.feature, features/step_definitions/invitations_steps.rb, features/step_definitions/navigation_steps.rb, spec/javascripts/Navigation/ContextSelector.spec.jsx, spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
[THREESCALE-6241: Move "Settings" inside Context Switcher](https://issues.redhat.com/browse/THREESCALE-6241)
1. Account Settings can be accessed from Context Switcher
2. Item gets highlighted inside ContextSwitcher when in Account Settings
=> Move Settings out of Masthead into Context Switcher

app/views/api/proxy_rules/edit.html.slim, app/views/api/proxy_rules/new.html.slim
Allow editting Proxy pro feature adds a redirect url field to the mapping rule object which a user can edit in the UI.
[THREESCALE-6210: Redirect url field is not rendered when editing a mapping rule](https://issues.redhat.com/browse/THREESCALE-6210)
=> includes field Redirect to Proxy Rule edit form

app/javascript/src/Navigation/styles/VerticalNav.scss
Section not selected:
Section selected:
No title:
=> 💄 Fixes css overflow in VerticalNav

app/lib/api_authentication/by_provider_key.rb, test/unit/api/by_provider_key_test.rb
Closes [THREESCALE-6309](https://issues.redhat.com/browse/THREESCALE-6309)
=> Use request.internal_host to find provider by provider_key

app/decorators/account_decorator.rb, app/views/shared/_service_access.slim
Refactor done for 2 reasons:
1. That _if_ here is a problem. The account **must** have and _admin_user_ at this point 😕
2. Law of Demeter
Josemi mentioned [this circleci issue](https://app.circleci.com/pipelines/github/3scale/porta/14574/workflows/c20b5833-d424-44c5-9541-61f4064adab4/jobs/191319):
```
Failure:
test_member_with_right_permission_and_access_to_all_services(Api::UsageLimitsControllerTest::ProviderMemberTest) [/opt/app-root/src/project/app/views/shared/_service_access.slim:6]:
ActionView::Template::Error: undefined method `email' for nil:NilClass
app/views/shared/_service_access.slim:6:in `_app_views_shared__service_access_slim__466153237176704443_195750400'
app/views/provider/admin/dashboards/show.html.slim:31:in `_app_views_provider_admin_dashboards_show_html_slim___460516966 …
```
=> [Refactor] Shared view ServiceAccess uses current_account.admin_user_email from AccountDecorator

app/decorators/account_decorator.rb, app/models/admin_section.rb, app/models/user/permissions.rb, app/views/provider/admin/dashboards/show.html.slim, app/views/shared/_service_access.slim, features/old/authorization/provider_plans_section.feature, test/unit/user/permissions_test.rb
Any member user has an array of "accessible services IDs" which correspond to the list at the bottom of the following image:
Even if all permission are revoked, such array of services doesn't necessarily have to be empty. That causes those services to be visible in the Dashboard, even if the user cannot interact with them in any way.
This PR adds a new check precisely to hide any "allowed services" when a user doesn't have the necessary permission to interact with them.
[THREESCALE-6278: Remove items from Products/Backends widgets for unauthorized users](https://issues.redhat.com/browse/THREESCALE-6278)
1. Create a member user and go to its edit page.
2. Leave some or all services checked but then uncheck all service-related …
=> Hide services when user has no permission

app/controllers/admin/api/account/proxy_configs_controller.rb, app/models/proxy_config.rb, doc/active_docs/Account Management API.json, test/integration/admin/api/account/proxy_configs_controller_test.rb
Closes [THREESCALE-6310](https://issues.redhat.com/browse/THREESCALE-6310)
⚠️ Blocks [THREESCALE-6237](https://issues.redhat.com/browse/THREESCALE-6237)
Request: `curl -v  -X GET "http://provider-admin.3scale.localhost:3000/admin/api/account/proxy_configs/production.json?access_token=1&host=example.com&version=3"`
=> API Accounts/ProxyConfigs GET by host/version

app/views/shared/_service_access.slim, test/integration/provider/admin/dashboards_controller_test.rb
=> 🐛 Fix wrong slim syntax in "service_access" partial

test/integration/provider/admin/dashboards_controller_test.rb
Test recently introduced in #2249. However, `display_name` and `org_name` aren't always the same thing.
Fixes [this random CircleCI failure](https://app.circleci.com/pipelines/github/3scale/porta/14664/workflows/b554e868-6a3d-4f3a-bde8-44f257a6db98/jobs/192061).
> test_products_and_backends_widgets_no_access - Provider::Admin::DashboardsControllerTest
> --- expected...
> 
> Failure:
> test_products_and_backends_widgets_no_access(Provider::Admin::DashboardsControllerTest) [/opt/app-root/src/project/test/integration/provider/admin/dashboards_controller_test.rb:29]:
> --- expected
> +++ actual
> @@ -1 +1 @@
> -"You don't have access to any API on the Company account. Please contact Company to request access."
> +"You don't have access to any API on the Company account. Please contact dude37 …
=> Fix CircleCI Random Failure for Test Provider::Admin::DashboardsController

app/lib/apicast/curl_command_builder.rb, app/models/proxy_config.rb, test/unit/apicast/curl_command_builder_test.rb, test/unit/helpers/api/integrations_helper_test.rb
Because I need these changes ASAP for another PR that touches the same part of the code 🙈 and the other PR will be easier after this simplification of the code
=> Remove non-APIAP code in CurlCommandBuilder

app/javascript/src/Navigation/components/ContextSelector.jsx, app/views/provider/admin/dashboards/show.html.slim, app/views/shared/_api_selector.html.slim, features/master/menu/dashboard.feature, features/old/menu/dashboard.feature, features/step_definitions/header_steps.rb, features/support/selectors.rb, spec/javascripts/Navigation/ContextSelector.spec.jsx, spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.jsx.snap
* Provider
* Master
[THREESCALE-6222: In master tenant products aren't accessible but there are links/pages to navigate to them](https://issues.redhat.com/browse/THREESCALE-6222)
Log in as master, take a look at Dashboard, open the Context Selector.
**Notes**
Denial of access to `apiconfig/services` and `p/admin/backend_apis` will be dealt with by https://issues.redhat.com/browse/THREESCALE-6223
=> Remove Products/Backends from Master Dashboard and Context Selector

app/helpers/vertical_nav_helper.rb
Vertical menu is not showing some items for member users with permissions for **Application > Application Plans** and **Application > Settings > Usage rules** even when they have the right permissions
Part of https://issues.redhat.com/browse/THREESCALE-6154
1. Create a member user with the following permissions:
___
___
2. Login as member user
3. Vertical menu should look like:
4. And user should be able to navigate to both **Listing** and **Usage Rules**
=> Display Application menu items according to permissions

app/lib/apicast/curl_command_builder.rb, app/models/proxy_config.rb
Just a previous small cleanup for #2230
What this does:
1. Remove unused scope `for_services`
2. Makes the method `max_version` private because it is meant to be used only inside the `update_version` method in the same model.
3. Refactor `Apicast::CurlCommandBuilder::Builder#proxy_from_config` to don't fetch an entire array from the DB only to take the first record if there is any. Plus, now the request is ordered.
=> Clean proxy configs curl command builder and model scope for services

openshift/system/config/core.yml
related to: https://github.com/3scale/platform/pull/322
```
[Core] Using http://backend-listener:3000/internal/ as URL
```
Porta is taking the default value for CORE URL as it's being read from the wrong ENV variable.
=> [Openshift] core.yml - backend setting

app/models/proxy_config.rb, test/unit/proxy_config_test.rb
Istio was never made APIAP-compatible so now promoting a product's integration config may throw an error. This depends on whether the Product had any associated Backend prior changing to Istio.
This change removes the validation `api_backend_exists?` in ProxyConfig when the proxy belongs to an Isito product.
[THREESCALE-6348: Unable to create product with Istio through UI](https://issues.redhat.com/browse/THREESCALE-6348)
> Create a product
> In Integration > Backend remove all backends
> In Integration > Settings set deployment to Istio
> In Integration > Configuration it should be possible to Update Config
=> Can't promote product config with Istio through UI

config/initializers/sphinx.rb
Patches ThinkingSphinx so the `sphinx_internal_class_name` field is avoided for no inheritance indices despite other indices with inheritance defined.
ThinkingSphinx v3 by default will only remove the class name field if there's no index with inheritance at all among the ones defined ([here](https://github.com/pat/thinking-sphinx/blob/2ae0c98b8b08242eb623e8eb5e364c4ed0fd3fcb/lib/thinking_sphinx/configuration/minimum_fields.rb#L7)). In Porta we have at least the `CMS::Page` index with inheritance involved, thus preventing the removal of the unnecessary field in all other indices. As a consequence, searching for terms like 'service' among `Service`s or 'api' among `BackendApi`s causes ALL records to match, because the term is present in the name of the model class.
This PR is a wider …
=> Prevent ThinkingSphinx from searching class names on all no-inheritance indices

test/integration/admin/api/account/proxy_configs_controller_test.rb, test/integration/master/api/proxy/configs_controller_test.rb, test/integration/user-management-api/services/proxy/configs_test.rb
Extracted from #2230 . I need them to ensure that the refactoring won't break anything.
=> Add missing integration tests for ProxyConfig endpoints

app/models/proxy_config.rb
Closes [THREESCALE-6421](https://issues.redhat.com/browse/THREESCALE-6421)
It must be a public method because it is called from the last method in the `CurlCommandBuilder`.
It was a problem of solving conflicts cherry-picking for 2.10 CR1.
It is correct in the `master` branch but not in 2.10 CR1 for now and that's a blocker for QE.
`bundle exec rails t test/unit/apicast/curl_command_builder_test.rb` 😉
=> [Bugfix] 'parsed_content' must be a public method

app/models/contract.rb, app/models/user.rb, test/unit/contract_test.rb
Fixing [this circleci bug in 2.10](https://app.circleci.com/pipelines/github/3scale/porta/14930/workflows/a797b03a-82a2-4bc1-a767-9b1bf35bfde9/jobs/193871):
I see that it was introduced in [this commit](https://github.com/3scale/porta/commit/8bbb177d5ebf8ee684d090b07f13e1fe700df9a2) so I am just cherry-picking it.
`bundle exec rails t test/integration/buyers/service_contracts_controller_test.rb`
=> [Refactor] Contract.permitted_for(user)

Makefile
- `Use 19.3.0-ee` instead of `19.3.0-ee-ci-prebuilt` in the Makefile
- Define the Oracle image url only once
=> Use ORACLE_DB_IMAGE oracle:19.3.0-ee in Makefile

Makefile
=> Use oracle:19.3.0-ee-ci-prebuilt again because it is less slow

app/assets/stylesheets/provider/_services.scss, app/views/api/services/show.html.slim
When browser window is at +/- half size some headers start overlapping
Closes https://issues.redhat.com/browse/THREESCALE-3633
**Before:**
**After:**
=> Align Services Overview headers

app/lib/logic/rolling_updates.rb
This way it will be safe to assume at the code level that `provider_can_use?(:api_as_product)` is always true (except for master).
This will allow us to safely merge to master and deploy small chunks of removing the non-APIAP logic.
=> Make APIAP always enabled in code level; ignore yaml config

app/controllers/api/integrations_controller.rb, config/routes.rb, test/integration/api/integrations_controller_test.rb
The reason for this PR/proposal is that the problem of redirecting to a legit action (`show`) is that then it seems like this is also a reachable legit path, and it isn't 😄 so I propose removing it directly since it is not used anymore (for APIAP) 😉 
What this PR does:
* Remove unused methods and paths: 'update_production' & 'update_onpremises_production'
* 'find_registry_policies' only for update
* Remove 'edit' method
* Clean Array of symbols in routes.rb
=> Remove unused methods & paths 'edit', 'update*production' of Api/IntegrationsController

app/services/service_creator.rb, test/unit/db/seeds_test.rb, test/unit/services/service_creator_test.rb, test/unit/signup/account_manager_test.rb
* Test BackendAPI in Seeds for Tenant & Master (only APIAP)
* Test Backend API attributes for a Service in ServiceCreator (only APIAP)
* ServiceCreator with only APIAP code
* Test only Backend API of APIAP for ProviderAccountManager
=> Remove non-APIAP code in Account Signup / Service creation

app/views/admin/api_docs/base/_form.html.slim, app/views/admin/api_docs/base/edit.html.erb, app/views/admin/api_docs/base/new.html.erb, features/old/providers/active_docs_v2.feature, features/old/providers/active_docs_v3.feature, features/step_definitions/active_docs_steps.rb
2 minor changes to the "new active doc" page.
Current:
New:
=> New active docs tweak

app/controllers/api/integrations_controller.rb, app/controllers/api/policies_controller.rb, app/controllers/api_docs/services_controller.rb, app/helpers/vertical_nav_helper.rb, app/lib/backend_api_logic/proxy_extension.rb, app/models/backend_api.rb, app/services/proxy_test_service.rb, app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim, app/views/api/integrations/apicast/script_driven/_staging.html.slim, app/views/api/plans/_metrics.html.erb, app/views/api/services/new.html.slim, app/views/api/services/show.html.slim, app/views/shared/provider/navigation/service/_integration.html.slim, features/old/menu/api_menu.feature, features/provider/onboarding/wizard.feature, features/step_definitions/provider_steps.rb, features/step_definitions/proxy_steps.rb, features/support/paths.rb, test/integration/api/integrations_controller_test.rb, test/integration/api/services_controller_test.rb, test/integration/api_docs/services_controller_test.rb, test/models/backend_api_test.rb, test/unit/proxy_test.rb, test/unit/services/service_discovery/import_cluster_definitions_service_test.rb
First part of [THREESCALE-3759: Remove (deprecated) non-APIAP code](https://issues.redhat.com/browse/THREESCALE-3759).
Removes all uses of `provider_can_use?(:api_as_product)`.
=> Remove provider_can_use usages

INSTALL.md
It was outdated. For me, it was easy to install it a few days ago, but that's because I am part of the team and for anyone new, it would be much harder.
On top of this update, I would suggest to Andreu from Product a few more things.
1. Do it all without Docker. Install directly.
2. I am using ZSH and my `~/.zshrc` contains this at the end to be able to read the PATH correctly in the terminal (`source ~/.zshrc`):
```bash
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
export NVM_DIR=~/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
```
So my PATH looks like this: `/Users/marta/.rvm/gems/ruby-2.5.7/bin:/Users/marta/.rvm/gems/ruby-2.5.7@global/bin:/ …
=> [DOCs] Update INSTALL.md for Mac 11.0.1 Big Sur - DEC 2020

config/environments/development.rb
To be able to test charging payments locally without having to edit the file with `true` or `false` all the time and then remember to skip it from `git` changes.
Usage: `THREESCALE_PAYMENTS_ENABLED=1`
For example: `THREESCALE_PAYMENTS_ENABLED=1 bundle exec rails console` or `THREESCALE_PAYMENTS_ENABLED=1 UNICORN_WORKERS=8 RAILS_LOG_TO_STDOUT=1 bundle exec rails server`
Just to be clear, 'charging' payments does not necessarily mean moving real money... it can be done with a testing environment payment gateway integration like I am doing 😄
=> ENV THREESCALE_PAYMENTS_ENABLED to be able to 'charge' payments in Development

lib/tasks/payments.rake, test/unit/tasks/payments_test.rb
Given a provider gateway type, save in a file the data of the provider (id, admin_domain and state)
Closes [THREESCALE-6528](https://issues.redhat.com/browse/THREESCALE-6528)
=> Rake Task: Save in a file the data of the providers having configured a specific payment gateway

app/views/payment_gateways/_braintree_customer_form.html.erb, app/views/provider/admin/account/payment_gateways/braintree_blue/edit.html.slim
3D Secure 2.0 requires SDK version 3.52.0 or higher.
Closes [THREESCALE-6527](https://issues.redhat.com/browse/THREESCALE-6527)
=> Updating SDK version in Braintree

Gemfile.base, Gemfile.lock, Gemfile.prod.lock, config/initializers/active_merchant.rb
Fixes [THREESCALE-6534](https://issues.redhat.com/browse/THREESCALE-6534) 🤞🏼 
I've also tested in Preview to ensure that it works for Ruby 2.4 just as we have it in Production. However, testing this in Preview is not as trivial as just following the PDF guide in the Jira Epic for a couple of reasons:
1. [This configuration for preview](https://github.com/3scale/porta/blob/091832b55730a9145c2cf1f6190663145f99f790/config/environments/preview.rb#L32) and [this line of logic in the code](https://github.com/3scale/porta/blob/091832b55730a9145c2cf1f6190663145f99f790/app/models/payment_transaction.rb#L27) together reject payments in preview, which is good for security, but for testing what I have personally done is deploying to preview with a branch changing that line of code for this: `if …
=> Gem activemerchant version '1.107.4' before Ruby 2.4 deprecation (with monkeypatch)

Gemfile.base, Gemfile.lock, Gemfile.prod.lock
It bumps https://github.com/braintree/braintree_ruby to [v2.104.1](https://github.com/braintree/braintree_ruby/tree/2.104.1), which (among other things) extends risk data support (adding `fraud_service_provider` and other fields) and introduces some 3D-Secure-related enhancements.
Closes [THREESCALE-6558](https://issues.redhat.com/browse/THREESCALE-6558) and possibly [THREESCALE-6550](https://issues.redhat.com/browse/THREESCALE-6550).
----
**Tested in preview (without 3D-Secure):**
=> Bumps braintree gem

test/unit/models_test.rb
Fix random CircleCI failure.
Extracted from #2324
=> [Bugfix in ModelTest] NoMethodError: undefined method 'match' (model.name.match) for nil:NilClass

app/views/payment_gateways/_stripe.html.erb
Closes [THREESCALE-6573](https://issues.redhat.com/browse/THREESCALE-6573)
It is not the cleanest solution, but the cleaning process must be inside #2334, and this way, we allow customers to save credit cards in the meantime.
=> [Bugfix][Stripe - Save CC] When a human clicks on 'Save', confirm to Stripe; When Stripe confirms, Submit form to the 3scale Porta server

app/lib/payment_gateways/stripe_crypt.rb, app/models/account/credit_card.rb, features/support/hooks.rb, test/integration/user-management-api/credit_cards_test.rb, test/unit/account/billing_test.rb, test/unit/account/credit_card_test.rb, test/unit/lib/payment_gateways/stripe_crypt_test.rb
Creates the customer in Stripe only once (or when the customer is deleted) and not each time that the page is loaded.
1st commit extracted from #2339
=> [Bugfix] find or create Stripe customer whenever <dev-portal>/admin/account/stripe is loaded

app/controllers/finance/api/payment_callbacks/stripe_callbacks_controller.rb, app/models/invoice.rb, app/models/payment_gateway.rb, app/models/payment_intent.rb, app/models/payment_transaction.rb, app/services/finance/stripe_charge_service.rb, config/routes.rb, db/migrate/20210119101158_create_payment_intents.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb, lib/system/database/definitions/mysql.rb, lib/system/database/definitions/oracle.rb, lib/system/database/definitions/postgres.rb, test/factories/payment_intent.rb, test/functional/finance/provider/settings_controller_test.rb, test/integration/admin/account/payment_gateways_controller_test.rb, test/integration/finance/api/payment_callbacks/stripe_callbacks_controller_test.rb, test/models/payment_intent_test.rb, test/unit/account/billing_test.rb, test/unit/account/gateway_test.rb, test/unit/payment_gateway_setting_test.rb, test/unit/payment_transaction_test.rb, test/unit/services/finance/stripe_charge_service_test.rb, test/unit/tasks/payments_test.rb
In separate PRs:
- Run porta and migrations
- Create a Stripe test merchant account (in case you don't have one already)
- Create a RW access token with the Billing API scope
- Download and run the [Stripe CLI](https://stripe.com/docs/cli) pointing it to `<provider-domain>/api/payment_callbacks/stripe_callbacks?access_token=<access-token>`
- Add credit card to developer accounts
- Create and charge invoices (You may need to hit charge more than once depending on the credit card used.)
- In the Rails console, check for the `params.dig('next_action', 'use_stripe_sdk', 'stripe_js')` of a payment transaction with message "Requires action". You need to paste that link into the browser and authenticate the transaction.
- Check in the [Stripe Dashboard](https://dashboard.stripe.com) for …
=> Stripe async payment intents

app/controllers/finance/api/payment_callbacks/stripe_callbacks_controller.rb, app/lib/three_scale/money.rb, app/models/payment_intent.rb, app/services/finance/stripe_charge_service.rb, app/services/finance/stripe_payment_intent_update_service.rb, db/migrate/20210128155025_add_reference_to_payment_intents.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb, lib/tasks/finance.rake, test/factories/payment_intent.rb, test/integration/finance/api/payment_callbacks/stripe_callbacks_controller_test.rb, test/models/payment_intent_test.rb, test/unit/services/finance/stripe_charge_service_test.rb, test/unit/services/finance/stripe_payment_intent_update_service_test.rb, test/unit/tasks/finance_test.rb, test/unit/three_scale/money_test.rb
Some improvements following #2339.
- Added a rake task to back fill existing records: `bundle exec rake finance:payment_intents:backfill_reference`
**For future PR:**
- Remove column `payment_intents.payment_intent_id`
- Remove rake task `finance:payment_intents:backfill_reference`
----
Related to [THREESCALE-6531](https://issues.redhat.com/browse/THREESCALE-6531).
=> Stripe async payment intents Improvements

app/models/payment_transaction.rb, app/services/finance/charging_service.rb, test/unit/payment_transaction_test.rb, test/unit/services/finance/charging_service_test.rb
- Adds `transaction_source: 'recurring'` to purchase with braintree
- New service `Finance::ChargingService` (to remove charign logic from `PaymentTransaction`
=> Braintree transaction source recurring

app/lib/pdf/finance/invoice_generator.rb, app/views/finance/provider/shared/_line_items.html.erb
When creating an invoice manually, the Line Items section is missing a title
None, but follow-up of https://github.com/3scale/porta/pull/2350
- Go to `/buyers/accounts/[id]/invoices`:
- Create an Invoice
- Add line items
**Before**:
**After**:
=> Adding missing title for line items in Invoices

app/views/shared/provider/_header.html.slim
Removes an unused class `Header-logo--withIcon`
Fixes https://issues.redhat.com/browse/THREESCALE-6694
Verify that the logo in the upper left on the dashboards still appears correctly
=> removes unused class Header-logo--withIcon

app/controllers/buyers/accounts_controller.rb, test/integration/buyers/accounts_controller_test.rb
Adding flash message when the user data is not valid 
closes [THREESCALE-6633](https://issues.redhat.com/browse/THREESCALE-6633)
**Before** 
**After**
=> Adding flash message when the user data is not valid

app/javascript/src/Navigation/components/ActiveMenuTitle.jsx, app/javascript/src/Navigation/components/ContextSelector.jsx, app/javascript/src/Navigation/styles/ContextSelector.scss, app/javascript/src/patternflyStyles/pf4Base.css, app/views/shared/provider/_header.html.slim
This PR replaces custom styling classes with the Patternfly equivalents for the context selector in the header. It also updates the styling to match current Patternfly.
https://issues.redhat.com/browse/THREESCALE-6693
Use the content selector in the masthead to verify it still operates. Inspect the elements to see that the context selector Patternfly classes are now included instead of custom "PopNavigation" classes.
=> Replace context selector classes with Patternfly equivalents

.eslintrc
We should have eslint warn us when we forget to remove our console logs. I would rather have it throw an error but then it would make it impossible to compile assets (since it needs a green lint check).
=> Adds eslint warning for console

.circleci/config.yml
Replacing `@duduribeiro` by `@3scale-ninjabot` as committer for the `make bundle`
```
curl https://github.com/3scale-ninjabot.keys  2>/dev/null | tail -n1 |  ssh-keygen -E md5 -l -f -
2048 MD5:17:be:79:a1:a0:c5:38:84:a7:3c:f2:af:87:d7:f3:cf no comment (RSA)
```
This ssh key fingerprint is registered in CircleCI
=> [mergebot] Use 3scale-ninjabot for make bundle

app/javascript/src/utilities/json-utils.jsx, spec/javascripts/utilities/json-utils.spec.jsx
Sometimes our method tries to parse `undefined` and it's very annoying (and also misleading) to see this error in the console, since `undefined` is actually the expected parsed value:
*Yes it does! 🙂*
The log error should be used when the passed string is actually not correctly formatted, such as when we passed data from rails without calling `to_json`.
=> Allow safeFromJsonString to parse "undefined"

.circleci/config.yml
Fails since Friday 26th February 2021 ( Friday deploy again? :thinking: )
Reported in https://github.com/codecov/codecov-bash/issues/413
=> Temporary fix for Codecov too many uploads

config/unicorn/development.rb
Just revert back this commit ee26e0f3c for the logs
Rails server logs are by default to stdout, so should we do it in development too
This causes binding.pry to malfunction, it stales forever
=> [fix] Unicorn should log to STDOUT by default

app/assets/stylesheets/provider/layouts/_main.scss, app/helpers/account_helper.rb, app/helpers/buttons_helper.rb, app/helpers/finance/invoices_helper.rb, app/views/admin/fields_definitions/index.html.erb, app/views/buyers/accounts/_account_plan.html.erb, app/views/buyers/accounts/_monthly_charging.html.erb, app/views/buyers/accounts/edit.html.slim, app/views/buyers/accounts/show.html.slim, app/views/buyers/applications/new.html.erb, app/views/finance/provider/invoices/_actions.html.erb, app/views/finance/provider/settings/show.html.slim, app/views/finance/provider/shared/_invoice_header.html.erb, app/views/finance/provider/shared/_line_item.html.erb, app/views/finance/provider/shared/_line_items.html.erb, app/views/sites/settings/edit.html.erb, app/views/sites/usage_rules/edit.html.slim, lib/developer_portal/app/views/developer_portal/invoices/show.html.liquid, test/functional/finance/provider/settings_controller_test.rb
It standardize links and buttons using patternfly guidelines.
Example:
`<a class="pf-c-button pf-m-link action edit">`
Instead of 
`<a class="action edit">`
Needed for QE automation
Fixes https://issues.redhat.com/browse/THREESCALE-6717
Sub task of https://issues.redhat.com/browse/THREESCALE-6691
Inspect the HTML markup of the following buttons
**/buyers/accounts/{account_id}**
> ![01](https://user-images.githubusercontent.com/13486237/108383674-481c8480-720a-11eb-9f2d-5f3e4f091259.png)
**/buyers/accounts/{account_id}/edit**
> ![02](https://user-images.githubusercontent.com/13486237/108383860-739f6f00-720a-11eb-89ab-82445b4fec31.png)
**/site/usage_rules/edit**
**/admin/fields_definitions**
> …
=> PF compliant buttons: Audience

app/controllers/api/services_controller.rb, app/controllers/provider/admin/backend_apis_controller.rb, app/views/api/services/index.html.slim, app/views/provider/admin/backend_apis/index.html.slim
It fixes a bug in pagination showing always the count of all items regardless of search.
[THREESCALE-6385: Products/Backends pagination shows all pages even when filtering](https://issues.redhat.com/browse/THREESCALE-6385)
> Go to Products/Backends index pages
> Search using Sphinx and check the count of items is reduced.
Sphinx is probably not going to work properly but having a result of '0' is actually good for verifying this PR.
=> Fix item count in Products and BackendApis pagination

app/helpers/api/integrations_helper.rb, app/helpers/api/services_helper.rb, app/helpers/cinstances_helper.rb, app/javascript/src/NewService/components/FormElements/FormWrapper.jsx, app/javascript/src/Policies/components/HeaderButton.jsx, app/javascript/src/Policies/components/PoliciesWidget.jsx, app/javascript/src/Policies/components/PolicyConfig.jsx, app/javascript/src/Policies/styles/policies.scss, app/views/admin/api_docs/base/_form.html.slim, app/views/admin/api_docs/base/_menu.html.erb, app/views/api/applications/edit.html.slim, app/views/api/applications/show.html.slim, app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim, app/views/api/metrics/_form.html.slim, app/views/api/policies/edit.html.slim, app/views/api/services/edit.html.slim, app/views/api/services/settings_apiap.html.slim, app/views/api/services/show.html.slim, app/views/api/services/usage_rules.html.slim, app/views/buyers/applications/_api_credentials.html.erb, app/views/buyers/applications/_change_plan.html.erb, app/views/buyers/applications/_plan.html.erb, app/views/buyers/applications/_state.html.slim, app/views/shared/proxy_rules/_form.html.slim, spec/javascripts/NewService/NewServiceForm.spec.jsx, spec/javascripts/NewService/ServiceDiscoveryForm.spec.jsx, spec/javascripts/NewService/formElements/FormWrapper.spec.jsx, spec/javascripts/Policies/components/PolicyConfig.spec.jsx, spec/javascripts/Policies/components/__snapshots__/HeaderButton.spec.jsx.snap, test/integration/api/applications_controller_test.rb
It standardize links and buttons using patternfly guidelines.
Example:
`<a class="pf-c-button pf-m-link action edit">`
Instead of 
`<a class="action edit">`
Needed for QE automation
Fixes https://issues.redhat.com/browse/THREESCALE-6691
Sub task of https://issues.redhat.com/browse/THREESCALE-6691
**IMPORTANT:** 
Part of a series of PR's starting with https://github.com/3scale/porta/pull/2363
Merge after https://github.com/3scale/porta/pull/2363
**PAGES AFFECTED:**
/apiconfig/services:
/apiconfig/services/new
/apiconfig/services/{product_id}
/apiconfig/services/{product_id}/edit
/apiconfig/services/{product_id}/applications/{application_id}
/apiconfig/services/{product_id}/applications/{application_id}/edit …
=> PF compliant buttons: Products

app/views/provider/admin/backend_apis/edit.html.slim, app/views/provider/admin/backend_apis/forms/_delete.html.slim, app/views/provider/admin/backend_apis/metrics/_form.html.slim, app/views/provider/admin/backend_apis/metrics/edit.html.erb, app/views/provider/admin/backend_apis/show.html.slim
It standardize links and buttons using patternfly guidelines.
Example:
`<a class="pf-c-button pf-m-link action edit">`
Instead of 
`<a class="action edit">`
Needed for QE automation
Fixes https://issues.redhat.com/browse/THREESCALE-6720
Sub task of https://issues.redhat.com/browse/THREESCALE-6691
**IMPORTANT:** 
PR 3 of a series
Merge after:
https://github.com/3scale/porta/pull/2363
https://github.com/3scale/porta/pull/2376
**PAGES AFFECTED:**
/p/admin/backend_apis
/p/admin/backend_apis/{backend_id}
/p/admin/backend_apis/{backend_id}/edit
/p/admin/backend_apis/{backend_id}/metrics/{metric_id}/children/new
/p/admin/backend_apis/{backend_id}/metrics/{metric_id}/edit
/p/admin/backend_apis/{backend_id}/metrics/new …
=> PF compliant buttons: Backends

.github/workflows/stale-prs.yml
* PRs are marked stale (label stale) after 14 days of inactivity
* stale PRs are closed after 7 days roting
It will run early in the morning at 3:30am UTC
=> [feature] Github action for stale PRs

app/views/provider/admin/account/authentication_providers/form/_form.html.slim, app/views/provider/admin/account/authentication_providers/show.html.slim, app/views/provider/admin/account/users/_form.html.erb, app/views/provider/admin/accounts/_form.html.erb, app/views/provider/admin/accounts/show.html.slim, app/views/provider/admin/user/notification_preferences/_form.html.slim, app/views/provider/admin/user/personal_details/edit.html.slim, app/views/provider/admin/webhooks/edit.html.slim, config/locales/en.yml
It standardize links and buttons using patternfly guidelines.
Example:
`<a class="pf-c-button pf-m-link action edit">`
Instead of 
`<a class="action edit">`
Needed for QE automation
Fixes https://issues.redhat.com/browse/THREESCALE-6721
Sub task of https://issues.redhat.com/browse/THREESCALE-6691
**IMPORTANT:** 
PR 4 of a series
Merge after:
https://github.com/3scale/porta/pull/2363
https://github.com/3scale/porta/pull/2376
https://github.com/3scale/porta/pull/2384
**PAGES AFFECTED:**
/p/admin/account
/p/admin/account/edit
/p/admin/user/personal_details/edit
/p/admin/user/notification_preferences
/p/admin/account/users/{user_id}/edit
/p/admin/account/authentication_providers/new …
=> PF compliant buttons: Account settings

app/helpers/payment_details_helper.rb, app/javascript/packs/braintree3DSecureCustomerForm.js, app/views/payment_gateways/_braintree_customer_form.html.erb
- It fixes an issue where the billing address was not pre-filled when going to the edit form.
- When Braintree fraud detection is enabled, billing address validation is failing because the region is in an unexpected format: it should be a two or three chars code, see [docs](https://braintree.github.io/braintree-web/current/ThreeDSecure.html#~billingAddress).
https://issues.redhat.com/browse/THREESCALE-6495
- To enable Billing and adding Braintree to the Admin Portal, follow the instructions in https://github.com/3scale/porta/pull/2322
- In Dev Portal:
Go to **Settings** > **Credit Card Details**
Click on **Edit Credit Card Details and Billing Address**
=> Bugfix: get billing adress for braintree

app/views/payment_gateways/_braintree_customer_form.html.erb
Improvement to https://github.com/3scale/porta/pull/2394
It handles the case where billing address is empty (if that's possible).
Part of https://issues.redhat.com/browse/THREESCALE-6495
Same as https://github.com/3scale/porta/pull/2394
=> Braintree: Handle empty billing address

.scss-lint.yml, app/assets/stylesheets/provider/_commons.scss, app/assets/stylesheets/provider/_patternfly_tabs_fake.scss, app/assets/stylesheets/provider/_pop_navigation.scss, app/assets/stylesheets/provider/_vertical_nav.scss, app/assets/stylesheets/provider/layouts/_main.scss, app/javascript/src/LoginPage/assets/styles/loginPage.scss, app/javascript/src/PaymentGateways/stripe/styles/stripe.scss
scss-lint `SelectorFormat` rule is not useful anymore, since it's not compatible with Patternfly at all.
Instead of disabling the rule everywhere, we should remove it.
None ;)
=> SCSS lint: remove SelectorFormat rule

app/javascript/packs/braintree3DSecuredisabled.js, app/views/payment_gateways/_braintree_customer_form.html.erb
This is a quickfix.
It recovers the old braintree implementation (not 3DSecure 2) from this [previous commit](https://github.com/3scale/porta/commit/c497dca4b2424fca80f7383e0f33874d49a0aae6#diff-e333f5ac348a321b5b1087b0039ffac2b5ff53e44d9bbf2478debfbf721a5b21), with small changes, when 3DSecure 2 is not enabled.
Or, uses the new 3DSecure 2 enabled implementation when it's enabed in Admin portal.
To be mergen on https://github.com/3scale/porta/pull/2400
https://issues.redhat.com/browse/THREESCALE-6860
=> Braintree: Detect if 3DSecure is enabled, JS side

Gemfile.base, Gemfile.lock, Gemfile.prod.lock, doc/licenses/licenses.xml
The author fixed the nokogiri dependency version in https://github.com/mimemagicrb/mimemagic/commit/f14e3bfbcfdb212fca8975ef43d7d01e4c61d886
=> [gem] Official mimemagic instead of github fork

app/views/finance/provider/settings/show.html.slim
Adds an inline hint to the 3D Secure enabled checkbox in Charging and Gateway page:
TODO:
=> Adding inline hint for 3Dsecure enabled checkbox

INSTALL.md
Updates installation guide for Fedora installation. It changes the Postgres database to MySQL. This is needed to easier the installation because MySQL is the default DB and when using Postgres you need to change the config which is not specified.
=> Use mysql in the installation guide

app/controllers/admin/api_docs/base_controller.rb, app/controllers/master/devportal/auth_controller.rb, app/helpers/account_helper.rb, app/helpers/buyers/accounts_helper.rb, app/helpers/payment_details_helper.rb, app/helpers/vertical_nav_helper.rb, app/messengers/account_messenger.rb, app/messengers/alert_messenger.rb, app/messengers/invitation_messenger.rb, app/messengers/invoice_messenger.rb, app/models/api_docs/service.rb, app/models/sso_token.rb, app/presenters/oauth_flow_presenter.rb, app/views/admin/api_docs/base/active_docs.html.erb, app/views/buyers/accounts/show.html.slim, app/views/notification_mailer/post_created.html.slim, app/views/notification_mailer/post_created.text.erb, app/views/shared/provider/navigation/audience/_portal.html.slim, app/views/sites/dns/show.html.erb
Some things still do not work when using domain substitution #1904
Among those, SSO authentication on developer portal which still redirects to the
domain stored in the database
=> [domain substitution] Use external_* when needed

app/lib/three_scale/oauth2/github_client.rb, test/unit/three_scale/oauth2/github_client_test.rb
Overcome from the authentication via URL query parameters deprecation 
https://issues.redhat.com/browse/THREESCALE-4441
=> Update SaaS developer portal Github login

app/views/api/proxy_rules/index.html.slim, app/views/provider/admin/backend_apis/mapping_rules/index.html.slim, app/views/shared/proxy_rules/_body_section.html.slim, app/views/shared/proxy_rules/_header_section.html.slim, features/backend_apis/mapping_rules.feature, features/services/mapping_rules.feature, features/step_definitions/proxy_steps.rb, features/support/paths.rb
- Move create button to main section
- Prepare structure for PF4 re-implementation
Product:
Backend API:
[THREESCALE-6874 Improve UI for creating a Product Mapping rule > THREESCALE-6954 Implement Create button with PF4](https://issues.redhat.com/browse/THREESCALE-6954)
=> [2.11] Move Create Mapping Rule button to header

config/initializers/paperclip.rb, test/unit/paperclip_test.rb
This is because we provide two storage options ('filesystem' and 's3'), and the Paperclip `url` option is set in the models to what will actually be the `path` of the attachments, instead of the desired S3 URL style. This used to be OK because Paperclip moves the value set for the `url` option to the `path` option, whenever the storage is 's3'. The problem is that, when Paperclip moves the value from `url` to `path`, it also sets the URL style to `:s3_path_url` (see https://github.com/thoughtbot/paperclip/blob/de92a5a44bae7ed20c33356de5cce584dc9125ae/lib/paperclip/storage/s3.rb#L154-L157), and AWS has [deprecated](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) the path style for S3 URLs in favour of the domain style (called "virtual-host style" by …
=> Defaults Paperclip S3 URL style to :s3_domain_url instead of :s3_path_url

app/javascript/packs/braintree3DSecuredisabled.js, app/models/finance/billing_strategy.rb, app/models/payment_gateway.rb, app/models/payment_gateway_setting.rb, app/services/finance/charging_service.rb, app/views/finance/provider/settings/show.html.slim, app/views/payment_gateways/_braintree_customer_form.html.erb, test/integration/admin/account/payment_gateways_controller_test.rb, test/unit/payment_gateway_setting_test.rb, test/unit/payment_gateway_test.rb, test/unit/services/finance/charging_service_test.rb
This is the base for allowing customers to opt-in for 3DS secure
* Added `:boolean` option to `PaymentGateway`
* Added `three_ds_enabled` option to Braintree
As commented by Braintree support;
> **Question: About metered recurring transactions**
> We do metered recurring payment, so we set transaction_source: 'recurring' in later transaction sales, what will be the result:
> If the payment method is subjected to SCA andwe use verify_card: true to create the payment_method
> we use verify_card: false to create the payment_method
> **Braintree Support answer:**
> The result will still ultimately depend on the card-issuing bank's decision. However, if there is a transaction or verification with 3DS information associated, subsequent recurring/unscheduled transactions are much more likely to …
=> [payment-gateway] Add three_ds_enabled settings

app/assets/javascripts/application.js, app/controllers/provider/admin/backend_apis_controller.rb, app/helpers/api/backend_usages_helper.rb, app/javascript/packs/add_backend_usage.js, app/javascript/src/BackendApis/components/AddBackendForm.jsx, app/javascript/src/BackendApis/components/BackendSelect.jsx, app/javascript/src/BackendApis/components/DescriptionInput.jsx, app/javascript/src/BackendApis/components/NameInput.jsx, app/javascript/src/BackendApis/components/NewBackendForm.jsx, app/javascript/src/BackendApis/components/NewBackendModal.jsx, app/javascript/src/BackendApis/components/NewBackendModal.scss, app/javascript/src/BackendApis/components/PrivateEndpointInput.jsx, app/javascript/src/BackendApis/components/SystemNameInput.jsx, app/javascript/src/BackendApis/index.js, app/javascript/src/Types/index.js, app/javascript/src/utilities/patternfly-utils.jsx, spec/javascripts/BackendApis/components/AddBackendForm.spec.jsx, spec/javascripts/BackendApis/components/BackendSelect.spec.jsx, spec/javascripts/BackendApis/components/DescriptionInput.spec.jsx, spec/javascripts/BackendApis/components/NameInput.spec.jsx, spec/javascripts/BackendApis/components/NewBackendForm.spec.jsx, spec/javascripts/BackendApis/components/NewBackendModal.spec.jsx, spec/javascripts/BackendApis/components/PrivateEndpointInput.spec.jsx, spec/javascripts/BackendApis/components/SystemNameInput.spec.jsx, spec/javascripts/__mocks__/global-mocks.js
Replaces the link to the Backend's `new` page with a button that displays a modal containing the form. Once a backend is created it will be selected in the dropdown.
> Subtask of [3scale][2.11][HI-prio] Improve Select in 'Add Backend to Product' form
[THREESCALE-6882: Embed New Backend form into a modal](https://issues.redhat.com/browse/THREESCALE-6882)
=> [2.11] Embed New Backend form into a modal

Gemfile, Gemfile.base, Gemfile.prod, Gemfile.prod.lock, doc/dependency_decisions.yml, features/support/sidekiq.rb
Context: we have it used on one of our production deployment.
We mainly rely on 2 features for it:
- Reliability
- Batches
First, after years used by customers on their own deployments without sidekiq-pro, no issues reported to us so far about reliability
We think it is time to say goodbye on this awesome gem.
Second, we successfully make use of an alternative to Pro batches sidekiq-batch
All in one, the necessity of sidekiq-pro dimmed so the decision is to take it down for good
=> [gem] Remove sidekiq-pro

Gemfile.base, Gemfile.lock, Gemfile.prod.lock
We need to support ruby 2.6 soon while still supporting ruby 2.4
This is the last version of webmock supporting both
=> [gem] Update webmock to 3.8.0 to support ruby 2.6

app/javascript/src/BackendApis/components/AddBackendForm.jsx, app/javascript/src/BackendApis/components/NewBackendForm.jsx, app/javascript/src/LoginPage/loginForms/HiddenInputs.jsx, app/javascript/src/NewService/components/FormElements/FormWrapper.jsx, app/javascript/src/PaymentGateways/stripe/components/StripeCardForm.jsx, app/javascript/src/utilities/CSRFToken.jsx, app/javascript/src/utilities/utils.js, package.json, spec/javascripts/utilities/utils.spec.jsx, yarn.lock
The CSRFToken tests are failing locally and it's rather annoying. Moreover, we're making use of an entire dependency `jsdom` to render a small DOM in an individual test.
The aforementioned error is:
```
$ yarn jest spec/javascripts/utilities/utils.spec.jsx
yarn run v1.22.10
$ jest spec/javascripts/utilities/utils.spec.jsx
FAIL  spec/javascripts/utilities/utils.spec.jsx
● Test suite failed to run
Module did not self-register: '/Users/jgallaso/projects/3scale/porta/node_modules/canvas/build/Release/canvas.node'.
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1151:18)
at Module.load (node:internal/modules/cjs/loader:972:32)
at Function.Module._load (node:internal/modules/cjs/loader:813:14)
at Module.require (node:internal/modules/cjs/loader:996:19)
at require …
```
=> ✅ Fix annoying test failing locally CSRFToken

app/controllers/api/backend_usages_controller.rb, app/javascript/packs/add_backend_usage.js, app/javascript/src/BackendApis/components/AddBackendForm.jsx, app/javascript/src/BackendApis/components/BackendSelect.jsx, app/javascript/src/BackendApis/components/BackendSelect.scss, app/javascript/src/BackendApis/components/PathInput.jsx, app/javascript/src/Common/components/SelectWithModal.jsx, app/views/api/backend_usages/new.html.slim, spec/javascripts/BackendApis/components/AddBackendForm.spec.jsx, test/integration/api/backend_usages_controller_test.rb
Renders the following inline errors whenever the form is sent with invalid data:
- Backend not found: this should never happen but the submit button can be disabled manually and the form submitted (see image).
- Path already taken: this will be returned by the server. In this case, the selected backend will still be selected despite the page refresh.
Demo:
[THREESCALE-6883: Implements inline validations and flash errors upon submition](https://issues.redhat.com/browse/THREESCALE-6883)
> Subtask of [3scale][2.11][HI-prio] Improve Select in 'Add Backend to Product' form
[THREESCALE-6882: Embed New Backend form into a modal](https://issues.redhat.com/browse/THREESCALE-6882)
=> [2.11] Implement inline errors to the Add Backend form

app/models/service.rb, app/workers/create_default_proxy_worker.rb, lib/tasks/services.rake, test/workers/create_default_proxy_worker_test.rb
Proxy is mandatory for a service to function.
The application is failing if a service does not have proxy
This is also useful when using the obfuscated database from production.
We truncate `proxies` table so we need to launch this task everytime we restore the database
=> [task] A task to fix services that do not have proxy

app/lib/backend/storage_rewrite.rb, app/models/metric.rb, test/unit/backend/storage_rewrite_test.rb, test/unit/metric_test.rb
Closes [THREESCALE-6491](https://issues.redhat.com/browse/THREESCALE-6491)
=> Fix resync of API backend-owned metrics with the 3scale backend via storage rewrite task

app/javascript/src/NewApplication/components/NewApplicationForm.jsx
Because https://github.com/3scale/porta/pull/2364 was a long running branch, utilities were reworked https://github.com/3scale/porta/pull/2426
No merging conflicts detected but still issue while compiling assets on the default branch after merge.
```
ERROR in ./app/javascript/src/NewApplication/components/NewApplicationForm.jsx 126:38-47
"export 'CSRFToken' was not found in 'utilities/utils'
@ ./app/javascript/src/NewApplication/index.js
@ ./app/javascript/packs/new_application.js
```
=> 🐛  Fix CSRFToken import

app/views/api/services/show.html.slim
This is part of the cleanup of APIAP. I noticed it causes a null pointer exception in preview due to proxy being `nil`, even when this element is going to be hidden because of the `is-hidden` class.
The element was previously rendered here:
[THREESCALE-7061: Remove permanently hidden elements from service overview](https://issues.redhat.com/browse/THREESCALE-7061)
=> Removes hidden element from Service overview

app/controllers/api/integrations_controller.rb
Clean up old APIAP related methods from `IntegrationsController`.
[THREESCALE-7064: Clean up integration controller unused methods](https://issues.redhat.com/browse/THREESCALE-7064)
=> Clean up APIAP traces in Integration Controller

app/javascript/src/PaymentGateways/braintree/braintree.js, app/javascript/src/PaymentGateways/braintree/types.js
Explanation: we recently updated Flow to look up for this comment in the first line of each file only (#2436), any other file is ignored.
It's similar to what happened with the refactor JS utilities PR, every time something was merged into master failed because the import statements were not updated (for instance #2437). The tests won't fail until the branch is merged but there a also no conflicts.
=> HOTFIX: Flow comment has to be in the first line

app/javascript/src/Common/components/Select.jsx, app/javascript/src/Common/components/SelectWithModal.jsx, spec/javascripts/Common/components/Select.spec.jsx
The typeahead filter in our Select component does not work as it should. In order to fix it we need to define our own `onFilter` callback.
Before:
Now:
=> Fix Typeahead select filter

app/views/api/services/settings_apiap.html.slim
**Update Product** buttons at `apiconfig/services/{service_id}/edit` and  `/apiconfig/services/{service_id}/settings` have different formats.
Using same format (button instead of input)
Follow-up of https://issues.redhat.com/browse/THREESCALE-6719
Requested by QE
=> "Update Product" button, using button instead of input

Gemfile, Gemfile.lock, app/workers/create_default_proxy_worker.rb, app/workers/restore_apicast_master_token_worker.rb, config/initializers/active_job_uniqueness.rb, lib/tasks/access_tokens.rake, lib/tasks/k8s.rake, test/test_helper.rb, test/unit/tasks/access_tokens_task_test.rb, test/workers/restore_apicast_master_access_token_worker_test.rb
In K8s context, pods are deployed and we spin off some management tasks like:
- Create a default proxy for services that do not have one
- Restore the Master APIcast access token to the one set in pod environment
We need to make those tasks reboot proof thus introducing activejob unique jobs
=> [feature] K8s management tasks

.flowconfig, app/decorators/backend_api_decorator.rb, app/decorators/service_decorator.rb, app/javascript/packs/backends_used_list.js, app/javascript/src/Products/components/BackendsUsedListCard.jsx, app/javascript/src/Products/index.js, app/views/api/services/cards/_backends_table.html.slim, app/views/api/services/show.html.slim, app/views/provider/admin/backend_apis/cards/_products_used_list.html.slim, app/views/provider/admin/backend_apis/show.html.slim, features/provider/onboarding/wizard.feature, spec/javascripts/Products/components/BackendsUsedListCard.spec.jsx
Extracts the current list of backends into its own card, with pagination and searching.
The other data is moved to the left column.
* The table is paginated and filtered in client side.
* In order to filter, either click the magnifier button or hit Enter.
OLD:
[THREESCALE-6877: [3scale][2.11][HI-prio] Improve list of Products in Backend overview page](https://issues.redhat.com/browse/THREESCALE-6877)
=> [2.11] New table "Backends used by Product" 

app/lib/backend_api_logic/routing_policy.rb, test/unit/backend_api_logic/routing_policy_test.rb
Signed-off-by: Srijita Mukherjee <srmukher@redhat.com>
Currently, when using APIAP some policies are broken because Routing policy is
always first.
hence placing the Routing policy just above the Apicast policy.
> Closes THREESCALE-6428 
To be documented.
=> Fixed THREESCALE-6428 - Add APIAP Routing policy just before APICast policy

config/initializers/bugsnag.rb
The do_not_send macro is ugly and misuse of it happens a lot
This macro documented in https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.5/html/liquid_reference/liquid-reference#tag-email
should discard an email. The API Provider thinks it is working but in fact it is generating an error because of the liquid syntax error, which prevents the email to be sent.
The proper way to do it would be:
- add a checkbox to each customizable email to opt-out if you do not want to send an email
- validate and parse all emails that have this `do_not_send` macro and set this new setting to false
=> [fix] Ignore error reporting on misused liquid macro `do_not_send`

app/lib/three_scale/open_api/url_resolver.rb, test/unit/three_scale/open_api/url_resolver_test.rb
Attempting to import an OAS3 spec into 3scale with an empty variables declaration in one or more server blocks will fail
fixes: https://issues.redhat.com/browse/THREESCALE-7109
1.  upload an example OAS spec with an unpopulated variables declaration
=> Fix OAS3 mapping error

app/javascript/packs/new_application.js, app/javascript/src/NewApplication/components/NewApplicationForm.jsx, app/javascript/src/NewApplication/components/NewApplicationFormWrapper.jsx, app/javascript/src/NewApplication/index.js
- Adds more types
- Removes Flow suppression comments
- Move react wrapper into NewApplicationForm
- Makes `servicePlansAllowed` optional with default to `false`.
=> Update NewApplicationForm (flow & small refactor)

app/errors/application_configuration_error.rb, app/lib/authentication/by_cookie_token.rb, app/models/user_session.rb, config/docker/settings.yml, config/examples/settings.yml, openshift/system/config/settings.yml, test/unit/user_session_test.rb
Add support to configure user session time to live [THREESCALE-693](https://issues.redhat.com/browse/THREESCALE-693)
fixes THREESCALE-693
1. set `user_sesion_ttl` in `settings.yml` to something small, like 1 minute `PT1M`
2. run porta 
3. open some porta provider console
4. login
5. check that you can navigate between pages
6. wait without activity for more than 1 minute
7. try to navigate to another page
8. you should be asked to login again
I couldn't figure out what other tests I can add. Existing tests already vefiry default TTL of 2 weeks
Still under investigation what needs to be added to OpenShift operator. In any case it should work as before OOB …
=> configurable user session TTL

.github/workflows/nightly-build.yml
Use Github actions to build and push the nightly to quay.io
I need to merge this first then I can use the workflow to refine it.
See https://github.community/t/workflow-files-only-picked-up-from-master/16129/16
=> Nightly build push to quay.io

Gemfile, Gemfile.lock
For Ruby 2.4 support, as some older deployments still uses this EOL Ruby
=> [gem] Use 3scale/activejob-uniqueness

openshift/system/Dockerfile
Otherwise we will be limited by docker rate limits
```
Could not pull base image: API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
=> Latest container build should use quay.io registry

config/jobs.rb
Launch a cron job everyday that creates missing proxy for a Service
Proxy is one of the objects that 3scale Porta requires to run normally.
If it does not exist then a big chunk of the functionalities will not work:
- Anything related to Product UI/API/background jobs
- APIcast configuration
This task was created in https://github.com/3scale/porta/pull/2431
We should use it regularly to fix our db
=> [cron] Recreate service default proxy if missing

.circleci/config.yml, Dockerfile, Gemfile.lock, openshift/system/Dockerfile
Closes CVE-2020-36327 https://issues.redhat.com/browse/THREESCALE-7085
=> [cve] Update bundler to 2.2.18 on 2.10-stable

.flowconfig, app/javascript/src/Logic/BuyerLogic.js, app/javascript/src/Logic/index.js, app/javascript/src/NewApplication/components/NewApplicationForm.jsx, features/old/applications/providers/create_application.feature, spec/javascripts/Logic/BuyerLogic.spec.jsx
The logic around contracted service plans is broken (thank you Flow).
The logic has been extracted to a different file and tested.
* Product with no service plan: can't fill form, need to create a plan first.
* Product with no subscription: need to select a plan in Service Plan dropdown
* Product with subscription: dropdown is disabled and the plan selected, user can't change it
=> Fix New Application Form 🐛 

.circleci/config.yml, Gemfile.lock, openshift/system/Dockerfile
Closes CVE-2020-36327 https://issues.redhat.com/browse/THREESCALE-7085
Is required by https://github.com/3scale/deploy/pull/706
=> [cve] Update bundler to 2.2.18

app/views/api/integrations/apicast/shared/_proxy_endpoints.html.slim, app/views/api/services/forms/_integration_settings.html.slim, app/views/api/services/settings.html.slim, test/integration/api/services_controller_test.rb
**Description**
The issue is only visual, caused by a typo in the Slim template that overrided the value of `deployment_option`:
```diff
- service.deployment_option = 'hosted'
+ service.deployment_option ||= 'hosted'
```
[THREESCALE-7209: 3scale SaaS Product Settings not saving APIcast self-managed option](https://issues.redhat.com/browse/THREESCALE-7209)
See JIRA
=> Fix Deployment radio input in Product settings

app/workers/zync_worker.rb
Otherwise it will break when domain substitution is enabled.
=> Fix provider host passed in the Zync update tenant request

app/decorators/provider_decorator.rb, app/helpers/plans_helper.rb, app/helpers/provider/admin/dashboards_helper.rb, app/helpers/vertical_nav_helper.rb, app/views/shared/provider/navigation/audience/_accounts.html.slim, features/old/applications/providers/create_application.feature, test/decorators/provider_decorator_test.rb, test/unit/helpers/buyers/applications_helper_test.rb
Right now, Service plan select is always visible because  of `servicePlansAllwed` not being calculated correctly.
[THREESCALE-7120: Create application page has Service plan field despite service plan option is turned off](https://issues.redhat.com/browse/THREESCALE-7120)
See JIRA
=> 🐛 Hide Service Plan select when they're switched off

.github/workflows/fast-forward-candidate-branch.yml
So we just have to press a button to do that
* the new candidate points by default to the current refs/heads/master
* the release version is required, it can be 2.11 or 2.12
the workflow will create or update a branch named 3scale-{{ release }}-candidate
=> [gh-actions] To fast forward the candidate branch to default branch HEAD

openshift/system/Dockerfile
This is related to [CVE-2020-25695](https://www.postgresql.org/support/security/CVE-2020-25695/) ([THREESCALE-7225](https://issues.redhat.com/browse/THREESCALE-7225)).
Although the CVE does not directly affect PostgreSQL client libs,
1. matching versions of PostgreSQL client libs and PostgreSQL server is a good practice as some client ("frontend") apps are, according to [documentation](https://www.postgresql.org/docs/9.0/app-psql.html#AEN75717), _"only guaranteed to work smoothly with servers of the same version"_, in spite of PotgreSQL's frontend/backend protocol [kept stable at v3 since PostreSQL v7.4](https://www.postgresql.org/docs/10/protocol.html)) – Note: our [tests](https://github.com/3scale/porta/blob/2e2b870ed4983c5375525049390c14c1448b56dd/.circleci/config.yml#L99) currently …
=> Upgrade pgsql libs to v10

app/controllers/admin/api/policies_controller.rb, app/controllers/admin/api/services/proxy/policies_controller.rb, app/lib/logic/rolling_updates.rb, app/models/proxy.rb, config/docker/rolling_updates.yml, config/examples/rolling_updates.yml, openshift/system/config/rolling_updates.yml, test/integration/user-management-api/policies_test.rb, test/integration/user-management-api/services/proxy/policies_test.rb, test/unit/logic/rolling_updates_test.rb
THREESCALE-7134
removing the `:policies` rolling update based on the comment in `Proxy#policy_chain`
=> THREESCALE-7134 removing :policies rolling update

config/schedule.rb
Since we upgraded to bundler 2.2.18, whenever-created crontab jobs are failing on `bundle exec script/rails`.
This will hotfix the issue until we have a clean ruby env underneath.
=> Hotfix: rails runner command for whenever schedule

app/lib/applications_controller_methods.rb, test/integration/api/applications_controller_test.rb, test/integration/buyers/applications_controller_test.rb, test/integration/provider/admin/applications/applications_controller_test.rb
Current implementation relies on a service subscription to exist OR a service plan id being sent in the request. When neither of those happen, 404 is return.
After this fix, the server will try to get the `default_service_plan` and if no one exist, the first one available.
[THREESCALE-7246: Cannot create application on saas](https://issues.redhat.com/browse/THREESCALE-7246)
TBD
=> 🐛 Prevents New Application from returning 404 when no service plan selected

app/javascript/packs/braintree_customer_form.js, app/views/payment_gateways/_braintree_customer_form.html.erb
In Developer Portal, Braintree form doesn't render when account has no billing address previously stored.
https://issues.redhat.com/browse/THREESCALE-7221
- You need an account without billing address.
- If you don't have one, you can modify it directly in rails console ans set to `nil` these fields:
```
billing_address_name: nil,
billing_address_address1: nil,
billing_address_address2: nil,
billing_address_city: nil,
billing_address_state: nil,
billing_address_country: nil,
billing_address_zip: nil,
billing_address_phone: nil, 
```
- In Dev Portal, login, then go to: 
http://provider.3scale.localhost:3000/admin/account/braintree_blue
- Click on "Add Credit Card Details and Billing Address" …
=> Bugfix: render braintree form without billing address

.circleci/config.yml
Run CI on quay.io/3scale/system-builder:ruby25, as this image now also contains bundler v2.2.18 and there is no need for fetching a different one.
=> CI based on system-builder-ruby25

config/webpacker.yml
Yarn's integrity checks detect unsatisfied or missing NPM dependencies. The problem is some of the error might be inevitable since are thrown by dependencies of a dependency and it's really annoying to get this error "out of nowhere" and block certain commands like `bundle` or the `assets:compile`.
```
error Couldn't find an integrity file                                                                                                                                                           
error Found 1 errors.
========================================
Your Yarn packages are out of date!
Please run `yarn install --check-files` to update.
========================================
To disable this check, please change `check_yarn_integrity`
to `false` …
```
=> Disable Yarn integrity checks in Development

db/migrate/20210708100519_add_index_on_metrics_parent_id.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
In some large databases, `metric.children` can currently take several milliseconds to execute. This can cause pages such as the application plan show page of the Admin Portal to fail with a 502 when either the API product or any of the API backends has a considerable number of top level metrics to render.
Performance can be improved with a database index defined on `metrics.parent_id`.
```ruby
::Benchmark.ms { Metric.find(9).children.count } # environment with hundreds of thousands of metrics
=> 78.72738316655159
Metric.find(9).children.to_sql # from https://github.com/amerine/acts_as_tree
=> "SELECT `metrics`.* FROM `metrics` WHERE `metrics`.`parent_id` = 9 ORDER BY `metrics`.`id` ASC"
```
**Before:**
```sql
mysql> EXPLAIN SELECT `metrics`.* FROM `metrics` WHERE `metrics`.`parent_id` = 9 …
```
=> DB index on metrics.parent_id

app/models/fields_definition.rb, test/functional/admin/fields_definitions_controller_test.rb, test/unit/fields_definition_test.rb
The introduction of the API (https://github.com/3scale/porta/pull/2480) for the field's definition pointed out an old bug with positions.
The fields definition uses the position column for the order of the fields. The `act_as_list` library doesn't know how to handle the list where the position is based on the `target` field, so it tries to update the position for every field, and it breaks the positions.
This PR introduces a fix for it. It overrides the update and corrects the positions of the fields. 
https://issues.redhat.com/browse/THREESCALE-7189
The position is not visible yet, but https://github.com/3scale/porta/pull/2480 introduces the API, which will expose the position.
**Special …
=> [Threescale-7189] Fixes position of the fields definitions

app/controllers/admin/api/nginxes_controller.rb, config/routes.rb, test/functional/admin/api/nginxes_controller_test.rb, test/integration/user-management-api/nginx_test.rb
Removing only the show method, which was generating the Lua-based configuration.
https://issues.redhat.com/browse/THREESCALE-7134
=> [THREESCALE-7134] Remove show method from the nginxes controller

config/application.rb
Closes THREESCALE-5952
Making the plural in MEMCACHE_SERVERS actually effective ...
Basically you can add multiple servers for Dalli following https://github.com/petergoldstein/dalli#configuration
```
ActiveSupport::Cache.lookup_store :dalli_store, ['localhost:332211', 'localhost:112233'], compress: true                                                                            
@data=#<Dalli::Client:0x00000000093b20f0 @options={:compress=>true}, @ring=nil, @servers=["localhost:332211", "localhost:112233"]>,
@options={:compress=>true}>
```
With:
```
MEMCACHE_SERVERS="localhost:11211,localhost:11311" rails c
Rails.cache.dalli
```
=> THREESCALE-5952 Multiple Memcache servers

app/views/api/services/settings.html.slim
Using button instead of input for "Update Product" button.
Already done in https://github.com/3scale/porta/pull/2461, but accidentally deleted on https://github.com/3scale/porta/pull/2444
Follow-up of https://issues.redhat.com/browse/THREESCALE-6719
=> Update Product, use button instead of input

.gitignore, test/test_helper.rb
Allow running tests with Intellyj IDEA after git clean clone.
- custom reporters are not supported by IDEA
- without the /tmp/metrics directory many tests fail, so ensure it exists after clone
1. git clone porta
2. import in IDEA
3. run some unit tests
=> allow running tests with intellij IDEA

config/examples/zync.yml
It is not used in the UI see https://github.com/3scale/porta/commit/9da51ed20f2fb7db4396c71459d3bf6c739bc039
=> Disable messagebus as it was removed from the UI

app/controllers/admin/api/services/proxy/policies_controller.rb, app/models/attributes/policies_config.rb, app/models/proxy.rb, app/representers/proxy_representer.rb, config/locales/en.yml, test/integration/api/integrations_controller_test.rb, test/integration/api/policies_controller_test.rb, test/integration/user-management-api/services/proxy/policies_test.rb, test/unit/backend_api_logic/routing_policy_test.rb, test/unit/proxy_test.rb
This is in relation to #2496 where we hit a reek error with the `#policy_chain`
method. By refactoring `policies_config` attribute to be a custom type
we can avoid this style error and hopefully make things more organized overal.
Now this PR is not complete and is only a rough PoC. Other files need to be changed
also tests to be fixed and added.
I'm submitting it to get feedback whether this direction is desirable and also
to get feedback on validation and other approaches used.
Please check only last commit as this refactoring is on top of unmerged #2496.
=> PoliciesConfig custom attribute type

app/lib/logic/provider_settings.rb, lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb, test/unit/logic/provider_settings_test.rb
The problem is when trying to find the service, if it's multi-service and there is no ID present, it redirects to `choose_service` page:
https://github.com/3scale/porta/blob/eb3a27beef090fe599ef52e0444635d99d17a654/lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb#L157
Once in that page, if there's only 1 available service, it tries to redirect back to the new page with the first service's ID:
https://github.com/3scale/porta/blob/24c9bd2e6242ab1c165b9494e5ee1379ddc75e6f/lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb#L96
BUT
it turns out the path is to `messages`, not the new application page:
```
redirect_to new_provider_admin_application_path(2)
-> …
```
=> 🐛 "Create new application" button in the Developer Portal redirects to messages inbox

.github/workflows/fast-forward-candidate-branch.yml
Allows people under "Settings > Branches > Edit > Restrict who can push to matching branches"
to create a fast-forward to candidate branch
=> Fixing git push fast forward to candidate branch

Makefile
So we do not have to recreate Oracle container everytime
=> [oracle] Fix ORACLE_DIR

app/assets/javascripts/swagger-ui/threescale.coffee.erb, app/assets/javascripts/swagger-ui2/api_docs_proxy.coffee.erb, app/views/admin/api_docs/base/swagger.html.erb, app/views/provider/admin/api_docs/show-v2.html.erb, app/views/provider/admin/api_docs/show.html.erb, lib/developer_portal/app/views/shared/_swagger.html.erb, lib/developer_portal/app/views/shared/_swagger_2_0.html.erb, lib/developer_portal/lib/liquid/filters/rails_helpers.rb, vendor/active-docs/app/assets/javascripts/active-docs/classes/resources_controller.js.erb, vendor/active-docs/app/assets/javascripts/active-docs/form_handler.js.erb
The issue is that this setting is used in coffee files.
Meaning on container image build it enables or disables ApiDocs proxy on asset compilation time
Closing https://issues.redhat.com/browse/THREESCALE-7320
Requires https://github.com/3scale/deploy/pull/714
=> Disabling ApiDocs Proxy should be an active setting

app/models/proxy.rb
This is a workaround for the issue is better explained #2554 and https://github.com/rsim/oracle-enhanced/issues/2200
=> workaround oracle enhanced adapter calling #to_s instead of proper #serialize

.circleci/config.yml
Use circle CI context for quay credentials instead of global env.
One could run oracle tests without creating a branch in main repo when part of the org. Or so I assume.
Also perhaps there is a way to approve such runs from external contributors?
Oracle tests should run properly, at least DB container should be created properly.
I'm not sure how to test this PR. Doesn't work from a forked branch. Trying main repo branch now. Not sure how to make sure that new config was used.
Also I'm not aware how this will affect workflow when we want changes from an external contributor to be tested on oracle. I think at least it will not become harder than before.
=> use context for Quay password instead of global env

Dockerfile, openshift/system/Dockerfile
Warning, we must not upgrade any packages that might use nodejs runtime.
Example https://www.npmjs.com/package/node-sass
=> Please make sure node-saas version is compatible with nodejs 10
This is temporary as we need to migrate all deployments of Porta to nodejs 12+
=> Upgrade to nodejs 12

app/javascript/packs/OAS3Autocomplete.js, app/javascript/src/Types/SwaggerTypes.jsx
When testing an API using swagger-ui, if the response returns just plain text (not json), it will be displayed as array of chars.
https://issues.redhat.com/browse/THREESCALE-6379
- You need an OAS v3, with and endpoint that returns only plain text.
- You can use this example I've created to test it:
- https://gist.github.com/damianpm/93d5876313a75ac7807fb6c4a5dc3da5
- In Admin portal, create a new ActiveDoc
- Be sure the new ActiveDoc is NOT associated to any service ("Service" field must be empty)
- In this way, swagger-ui will make the requests directly to the test API I've created to test. If you select a service, then Apicast will be used as proxy and you'll need to configure Apicast to …
=> ActiveDocs: Do not inject autocomplete fields in plain/text responses

app/javascript/src/Plans/components/DefaultPlanSelect.jsx
For a set of plans:
```
plans = ['Plan A', 'A plan B', 'The plan C']
```
Before:
```
plans.search('A')
// -> ['A plan B']
plans.search('plan')
// -> ['Plan A']
```
After:
```
plans.search('A')
// -> ['Plan A', 'A plan B', 'The plan C']
plans.search('plan')
// -> ['Plan A', 'A plan B', 'The plan C']
```
1. Go to Application Plans index
2. Play with the default plan select
=> Fix DefaultPlanSelect's Typeahead

app/javascript/src/PaymentGateways/braintree/BraintreeCustomerForm.scss, app/javascript/src/PaymentGateways/braintree/BraintreeForm.jsx
When saving Credit Card details for Braintree, some CC that should be rejected are being stored.
The reasons why a CC may be rejected are multiple, some related to the card itself (wrong data entered by user, etc.), some to another issues (timeouts, etc). 
Braintree errors are a bit cryptic and technical (e.g: "THREEDS_LOOKUP_VALIDATION_ERROR"), and not very useful for regular users. For this reason, a generic error is shown when validation fails:
"An error occurred, please review your CC details or try later."
Later, we should improve error messages.
Additionally, fixing some alignment issues in Braintree injected form fields.
Related to 
https://issues.redhat.com/browse/THREESCALE-6860
You …
=> [Bugfix] Braintree: Do not save CC that failed 3DSecure verification

app/controllers/api/plans_base_controller.rb, app/helpers/api/plans_helper.rb, app/views/api/application_plans/index.html.slim, test/integration/api/application_plans_controller_test.rb
The Plans table is showing a total number that doesn't match what is paginated. This happens because the paginated items (the ones rendered in the table) are `plans.not_custom` but the count is calculated from `plans`.
Solution: instead of filtering `not_custom` plans in the view helper, do it in the controller when `plans` is declared.
Before:
After:
[THREESCALE-7426: application plans index has empty pages](https://issues.redhat.com/browse/THREESCALE-7426)
You'll need some plans and custom plans. In master, go to `Master API > Audience > Application Plans` and look at the table's pagination widget. Verify the number of items in the table matches the total count. For instance, "before" image …
=> Plans index page should show no custom plans

.github/workflows/fast-forward-candidate-branch.yml
Ensure that the branch can be checked out correctly
Ensure that we use a predifined PAT (personal access token) for the FF_CANDIDATE_BRANCH_PAT_TOKEN
The change is that the push will always be done through the owner of the PAT
=> Fix branch already exists in FF candidate workflow

Gemfile.lock, openshift/system/Dockerfile
Updates bundle otherwise `loofah` won't be installed.
[THREESCALE-7398: Bundle wont install dependencies because of loofah](https://issues.redhat.com/browse/THREESCALE-7398)
```
bundle install
```
=> Update bundle to 2.2.25

app/views/provider/admin/backend_apis/metrics/_form_new.html.slim
From a **Backend**, when creating new **method/metric** , it saves incorrect system name. The system name is ignored and it takes the friendly name always.
Right behavior should be:
-  If System name is empty, use Friendly name
- If System name is not empty, use it
https://issues.redhat.com/browse/THREESCALE-7483
Go to **Backends > Methods & Metrics**
Create a new method or metric
Try both options:
1.- Leave System name empty
2.- Fill System name
It should work with both options:
=> Bugfix: use right input name for metric system_name

app/javascript/packs/new_mapping_rule.js, app/javascript/src/MappingRules/components/NewMappingRule.jsx, app/javascript/src/MappingRules/components/NewMappingRule.scss, app/javascript/src/MappingRules/components/PatternInput.jsx, app/views/api/proxy_rules/new.html.slim, spec/javascripts/MappingRules/PatternInput.spec.jsx, spec/javascripts/MappingRules/components/PatternInput.spec.jsx
Creating new mapping rule fails when the pattern validation fails.
The pattern is being validated by Rails, but the error is not passed to React.
This PR:
- Pass the error to React
- Shows the error message
- Update the helper text, it was misleading, suggesting the use of unsupported characters ("-")
https://issues.redhat.com/browse/THREESCALE-7510
- Go to **Product > Integration > Mapping rules > Create Mapping rule**
- Create a Mapping rule with an invalid pattern: missing the initial "/" or including an unsupported character like "-" or "*"
- Create a mapping rule with a valid pattern
https://user-images.githubusercontent.com/13486237/132003834-e8ad4e35-cb9c-4dc2-9ee4-b33345ee88ae.mov
=> Bugfix: create mapping rule fails because of pattern validation

app/javascript/src/BackendApis/components/NewBackendForm.jsx, spec/javascripts/BackendApis/components/NewBackendForm.spec.jsx
Changes `minimun_length` for `presence`.
Adds validation for `system_name`.
Updates tests.
[THREESCALE-7520: New Backend form "system name" validation not working](https://issues.redhat.com/browse/THREESCALE-7520)
Product >Integration >Backends > Add Backend > Create new backend
=> Improve New Backend validations

app/views/api/backend_usages/index.html.slim
Moves "Add Backend" button to the page header.
Before:
After:
[THREESCALE-7519: Move "Add Backend" button from table to page header](https://issues.redhat.com/browse/THREESCALE-7519)
Check button at `Product > Integation > Backends`
=> moves "Add Backend" button from backends table into page header

app/javascript/src/BackendApis/components/BackendSelect.scss, app/javascript/src/Common/components/SelectWithModal.scss, app/javascript/src/NewApplication/components/NewApplicationForm.scss
Moves styling affecting the component `SelectWithModal` to its own scss file. Currently these styles are defined individually for `NewBackendForm` and `NewApplicationForm`.
This happens in the new Mapping Rule page
Before:
After:
Bug reported for [THREESCALE-6873: [3scale][2.11][HI-prio] Improve UI for creating a Backend Mapping rule](https://issues.redhat.com/browse/THREESCALE-6873)
** Verification steps:**
Pages where `SelectWithModal` is used:
- Add backend api usage (backend select)
- New application (buyer and product selects)
- New mapping rule (metric and method selects)
=> SelectWithModal should always have a max-width

config/cucumber.yml
So we can split files by timings!
`circleci tests split --split-by=timings` returned an error:
```
Error autodetecting timing type, falling back to weighting by name. Autodetect no matching filename or classname.  If file names are used, double check paths for absolute vs relative.
Example input file: "features/access_tokens/show.feature"
Example file from timings: ""
```
=> Add fileattribute to junit formatter for Cucumber

app/concerns/applications.rb, app/presenters/api/applications_new_presenter.rb, app/presenters/buyers/applications_new_presenter.rb, app/presenters/provider/admin/applications_new_presenter.rb
Currently `New Application` page has no pagination implemented: it loads all products and buyers from the server. However, as part of https://github.com/3scale/porta/pull/2459 some commits have been mixed up with master (rebases...) and the items are being limited to 20.
The items will be limited to 20 once the new Async select with modal is merged (see mentioned PR).
Bug reported in 
- [THREESCALE-6878: [3scale][2.11][HI-prio] Improve Select in 'Create new Application' form](https://issues.redhat.com/browse/THREESCALE-6878)
- [THREESCALE-6879: [3scale][2.11][HI-prio] Add 'Create new Application' flow to Product > Applications index](https://issues.redhat.com/browse/THREESCALE-6879)
=> 🐛 Buyers and Products are limited to 20 items in New Application page

app/controllers/api/plans_base_controller.rb, app/helpers/api/plans_helper.rb
Force all plans to be listed alphabetically by default.
Bug reported in:
- [THREESCALE-6875: [3scale][2.11][LO-prio] Improve list of Application plans in Application plans index page](https://issues.redhat.com/browse/THREESCALE-6875)
- [THREESCALE-6871: [3scale][2.11][LO-prio] Improve UI for changing Application plan for existing Application](https://issues.redhat.com/browse/THREESCALE-6871)
=> Order all plans alphabetically by default

app/views/provider/admin/applications/edit_redirect_url.html.erb
The Edit button is supposed to load a template that wasn't updated during the Applications Controllers refactoring.
[THREESCALE-7501: Unable to edit Redirect URL in Admin Portal](https://issues.redhat.com/browse/THREESCALE-7501)
See JIRA
=> 🐛 Fix Edit Redirect URL form in Application's show page

.gitignore, Gemfile, Gemfile.lock, config/application.rb, config/environments/production.rb, config/examples/cors.yml, config/initializers/assets.rb, doc/licenses/licenses.xml, lib/three_scale/middleware/cors.rb, test/unit/three_scale/middleware/cors_test.rb
font_assets is obsolete and unsupported. rack-cors open possibilities for a richer CORS support when needed.
THREESCALE-7515
For font_assets behavior see https://github.com/3scale/porta/pull/2581#issuecomment-911502552
This is GET request with rack-cors:
```
🐚 curl -v -H "Origin: localhost" -H "Access-Control-Request-Method: GET" http://provider-admin.3scale.localhost:3000/packs/media/overpass-webfont/overpass-light-c97e1959.woff2
*   Trying ::1:3000...
* connect to ::1 port 3000 failed: Connection refused
*   Trying 127.0.0.1:3000...
* Connected to provider-admin.3scale.localhost (127.0.0.1) port 3000 (#0)
> GET /packs/media/overpass-webfont/overpass-light-c97e1959.woff2 HTTP/1.1
> Host: …
```
=> Replace font_assets with rack-cors

app/javascript/src/NewApplication/components/ProductSelect.jsx
`ProductsSelect` mentions _Accounts_ instead of _Products_.
After fix:
The account needs to have >20 products.
In New Application page, inspect Product input and the modal.
=> 🐛  Fix wrong strings in ProductSelect

features/step_definitions/credit_card_steps.rb, features/support/parameter_types.rb
Cucumber is not able to suggest new step definitions (a very useful feature IMO) because there is a parameter type with a "catch-all" regexp. As a result, Cucumber will always suggest to use it:
=> Fix ParameterType "date"

app/decorators/service_decorator.rb, features/api/overview.feature, features/step_definitions/provider_steps.rb, features/step_definitions/service_steps.rb, features/support/paths.rb
backends have to be sorted by name.
Bug reported in: [THREESCALE-6866: [3scale][2.11][LO-prio] Improve list of Backends in Product overview page](https://issues.redhat.com/browse/THREESCALE-6866)
Go to some product overview page and check the list.
=> 🐛 Sort "Backends used by product" list alphabetically

app/javascript/src/Stats/lib/menu.jsx
Stats "until" date (datepicker) is showing and allowing to select future dates (there are no stats for future dates)
**Before:**
**After:**
https://issues.redhat.com/browse/THREESCALE-6650
=> Stats - Datepicker: Disabling future dates in 'until' field

config/initializers/autoload_aws.rb
When running cucumbers:
```
Aws.eager_autoload is no longer needed, usage of autoload has been replaced with require statements
```
[THREESCALE-7539: Resolve Cucumber deprecation warnings](https://issues.redhat.com/browse/THREESCALE-7539)
=> 🗑️  AWS auto_load no longer needed

app/javascript/packs/validateSignup.js
Developer Portal's signup form can conditionally render **password** and **password confirmation** fields.
When not displayed, form validation fails, being unable to validate them.
This PR improves form validation, validating  **password** and **password confirmation**  only when present
https://issues.redhat.com/browse/THREESCALE-7633
**Note:** This issue was reported as happening when using SSO Integrations (and no _password_ and _password confirmation_ fileds). But, in fact, it can happen without SSO integrations.
**To test with SSO integrations enabled:**
In Admin Portal
Go to **Audience > Developer Portal > SSO Integrations**
Enable one of the SSO Integrations available (e.g. Git Hub): …
=> Signup form: validate just required fields

Gemfile, Gemfile.lock, config/initializers/audited_hacks.rb, db/migrate/20210914124206_revert_polymorphic_indexes_order.rb, db/migrate/20210917163154_add_version_to_auditable_index.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
This should preserve Rails lazy initialization order.
Also fixes deprecation warnings with Rails 6.1 and adds support for 7
supersedes #2616
=> update audited to 5.0.2

.circleci/asset_paths, .circleci/config.yml
When no changes to cached assets are needed, on my laptop `rake
assets:precompile assets:clean` takes around 12 seconds while without it
takes almost 2 minutes.
=> add CircleCI caching for compiled assets

app/controllers/application_controller.rb, app/controllers/finance/provider/billing_strategies_controller.rb, app/controllers/provider/admin/applications_controller.rb, app/controllers/provider/admin/cms/builtin_legal_terms_controller.rb, app/controllers/provider/admin/cms/versions_controller.rb, app/controllers/provider/passwords_controller.rb, app/controllers/sites/usage_rules_controller.rb, app/lib/forum_support/user_topics.rb, lib/developer_portal/app/controllers/developer_portal/admin/applications/user_keys_controller.rb
This PR removes the depreciated warning for redirect_to :back
https://issues.redhat.com/browse/THREESCALE-7759
=> Change `redirect_to :back` with new method `redirect_back`

app/controllers/application_controller.rb
Fixes deprecation:
```
DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/html`. (called from render_error at /opt/app-root/src/project/app/controllers/application_controller.rb:199)
```
=> Fix deprecation of render text in the application controller

test/workers/delete_plain_object_worker_test.rb, test/workers/index_proxy_rule_worker_test.rb
…ils 5.1
In our rails upgrade branch, those tests are failing. Since the assert_nothing_raised is noop we can remove it.
=> Removes assert_nothing_raised with parameter

test/integration/user-management-api/signup_test.rb, test/unit/cms/section_test.rb
Fixes deprecation:
```
DEPRECATION WARNING: Passing an argument to force an association to reload is now deprecated and will be removed in Rails 5.1. Please call `reload` on the result collection proxy instead.
```
=> Fixes deprecation of association reload

test/workers/persist_event_worker_test.rb
Fixes deprecation of ActiveRecord exceptions.
https://github.com/rails/rails/blob/v5.0.7.2/activerecord/lib/active_record/errors.rb#L102
=> Fixes deprecation in constructor of ActiveRecord exceptions

app/javascript/src/NewApplication/components/ApplicationPlanSelect.jsx, spec/javascripts/NewApplication/components/ApplicationPlanSelect.spec.jsx, spec/javascripts/NewApplication/components/NewApplicationForm.spec.jsx
App plans select is now disabled when there are no plans available
Fixes # THREESCALE-7576.
 https://issues.redhat.com/browse/THREESCALE-7576?_sscc=t
=> THREESCALE-7576 disables plan select when no plans

test/unit/tasks/sidekiq_test.rb
Queues order are important because they determine the priority
The former test sort them which is not what we want
If we want to ensure that all job queues are taken care by sidekiq then we should try another approach
=> Fix sidekiq queues test

app/controllers/admin/api/base_controller.rb, app/controllers/application_controller.rb, app/controllers/master/api/base_controller.rb, test/integration/application_controller_test.rb
Adds CSRF token to the HTTP calls that are made through the 3scale API Docs.
https://issues.redhat.com/browse/THREESCALE-7475
=> [THREESCALE-7475] Api docs calls won't destroy user session because of CSRF

app/javascript/src/NewApplication/components/ApplicationPlanSelect.jsx, app/javascript/src/NewApplication/types.js, app/presenters/service_presenter.rb, features/old/api/applications/create_application.feature, features/old/buyers/applications/create_application.feature, features/old/provider/admin/applications/create_application.feature, features/step_definitions/applications/applications_steps.rb, features/step_definitions/web_steps.rb, spec/javascripts/NewApplication/components/ApplicationPlanSelect.spec.jsx, spec/javascripts/NewApplication/components/NewApplicationForm.spec.jsx, spec/javascripts/NewApplication/components/ProductSelect.spec.jsx
Removes `buyerCanSelectPlan` parameter, which in fact means _developer can select plan_ and it shouldn't affect the New Application page.
[THREESCALE-7834: admin can't create application when developer is not allowed to pick a plan](https://issues.redhat.com/browse/THREESCALE-7834)
See JIRA
=> Fix Application plans select

config/docker/thinking_sphinx.yml, config/thinking_sphinx.yml
Upgrading to Rails 5.1 benefits from Sphinx update to 5.3.0. In that version
Sphinx does not set default configuration file path value and starting
Sphinx locally in dev mode fails.
Emulating same behavior in the configuration file.
=> [THREESCALE-5010] sphinx 5.3 does not set default value

app/models/user.rb, lib/tasks/sidekiq.rake, test/integration/developer_portal/passwords_controller_test.rb, test/unit/tasks/sidekiq_test.rb, test/unit/user_test.rb
We do not want to keep the web server busy sending email
Requires: https://github.com/3scale/deploy/pull/721
Tested and working
Part of THREESCALE-7574
=> [email-async] Generate email async for lost password token

app/controllers/api/service_plans_controller.rb
In Rails 5, ActionController::Parameters no longer inherit from Hash. It also requires to use permit and required keys to be more secure.
=> Service plans controller permit parameters

app/controllers/buyers/users_controller.rb, test/functional/buyers/account_plans_controller_test.rb, test/functional/buyers/applications_controller_test.rb, test/functional/buyers/impersonations_controller_test.rb, test/functional/buyers/users_controller_test.rb
This PR fix deprecated positional arguments in functional buyers test.
Fixed rubocops
=> THREESCALE-7852 fixed deprecated positional arguments in functional buyers test

test/functional/api/web_hooks_failures_controller_test.rb
This PR fix deprecated positional arguments in functional api test.
Fixed rubocops
=> THREESCALE-7852 Fixed functional api test

test/functional/accounts/notifications_controller_test.rb
This PR fix deprecated positional arguments in functional accounts test.
Fixed rubocops
=> THREESCALE-7852 Fixed functional accounts test

app/controllers/admin/api/account/authentication_providers_controller.rb, app/controllers/admin/api/authentication_providers_controller.rb, app/controllers/admin/api/services_controller.rb, app/controllers/provider/admin/account/authentication_providers_controller.rb, app/controllers/provider/admin/authentication_providers_controller.rb
In Rails 5, ActionController::Parameters no longer inherit from Hash.
=> Fixes usage of action controller parameters in integration/admin tests

config/examples/zync.yml
Disables zync in the cucumber tests.
When you have the zync configure locally (`ZYNC_ENDPOINT` env exists) the cucumber tests will fail.
=> Cucumber tests won't use zync even if it's configured

config/application.rb, config/docker/cors.yml, config/examples/cors.yml, lib/three_scale/middleware/cors.rb, test/unit/three_scale/middleware/cors_test.rb
`rack-cors` gem handles all pre-flight requests but signup controller has its
own way of handling these. So we make rack-cors skip handling of requests
with the signup controller path.
Otherwise 3scale.net signup form gets broken.
To test you need cors enabled in `config/cors.yml`. The this is with the fix:
```
$ curl -v 'http://master-account.3scale.localhost:3000/p/signup?signup_origin=website-signup' -X OPTIONS -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.7,bg;q=0.3' --compressed -H 'Access-Control-Request-Method: GET' -H 'Access-Control-Request-Headers: 3scale-origin,x-requested-with' -H 'Referer: https://www.3scale.net/' -H 'Origin: https://www.3scale.net' -H 'DNT: 1' -H 'Connection: …
```
=> signup controller handles CORS by itself

app/presenters/service_presenter.rb, test/unit/presenters/service_presenter_test.rb
Because it's required
Bug reported for [THREESCALE-6879: [3scale][2.11][HI-prio] Add 'Create new Application' flow to Product > Applications index](https://issues.redhat.com/browse/THREESCALE-6879)
**Note**: plans in the images have been created in reverse order so that it doesn't coincide with created_at order.
=> Sort plans alphabetically in Create Application form

test/integration/user-management-api/services/proxy/configs_test.rb
Fixes proxy/configs_test to be compatible with rails 5.1
=> Fixes integration proxy configs tests to be compatible with rails 5.1

test/functional/developer_portal/buyer/stats_controller_test.rb
* test/functional/developer_portal/buyer/stats_controller_test
=> Remove `context` and `should` from stats_controller_test

test/functional/developer_portal/admin/account/personal_details_controller_test.rb, test/integration/utilization_test.rb, test/unit/abilities/cms_test.rb, test/unit/abilities/multiple_applications_test.rb, test/unit/alert_test.rb, test/unit/backend/model_extensions/provider_test.rb, test/unit/exception_reporting_test.rb, test/unit/line_item_test.rb, test/unit/liquid/drops/service_plan_drop_test.rb, test/unit/mailers/invitation_mailer_test.rb, test/unit/payment_gateway_test.rb, test/unit/web_hook_test.rb
* test/integration/utilization_test
* test/unit/abilities/cms_test
* test/unit/abilities/multiple_applications_test
* test/unit/alert_test
* test/unit/backend/model_extensions/provider_test
* test/unit/exception_reporting_test
* test/unit/line_item_test
* test/unit/liquid/drops/service_plan_drop_test
* test/unit/mailers/invitation_mailer_test
* test/unit/payment_gateway_test
* test/unit/web_hook_test
=> Remove `context` and `should` from a bunch smaller test files

.gitignore, app/models/finance/billing_strategy.rb, config/application.rb, config/docker/settings.yml, config/environments/test.rb, config/examples/settings.yml, config/initializers/active_merchant.rb, openshift/system/config/settings.yml, test/unit/finance/billing_strategy_test.rb
Adds support for `config/payments.yml` to set configs such as `active_merchant_mode`, `active_merchant_logging` and `billing_canaries`. This is especially useful for running integration tests with `Rails.env == 'production'`.
No default or sample `payments.yml` file will be provided; the settings continue to default to values in `config/settings.yaml` and safe defaults enforced by code, according to each application environment.
The environment variables `THREESCALE_PAYMENTS_ENABLED` and `ACTIVE_MERCHANT_LOGGING` continue to be supported as before.
In test environment specifically, as before, the following settings are enforced regardless of any values in the YAML files:
- `enabled: true`
- `active_merchant_mode: :test`
- `active_merchant_logging: false`
<br/>
**Default (i.e., based on …
=> Payments settings

test/functional/buyers/account_plans_controller_test.rb
* account_plans_controller_test
=> Remove `context` and `should` from account_plans_controller_test

test/functional/forums/public/topics_controller_test.rb
* test/functional/forums/public/topics_controller_test
=> Remove `context` and `should` from topics_controller_test

test/functional/developer_portal/signup_controller_test.rb
=> Remove `context` and `should` from signup_controller_test

test/integration/notifications_test.rb
* test/integration/notifications_test.rb
=> Remove `context` and `should` from notifications_test

test/integration/provider/invoices_controller_test.rb
* test/integration/provider/invoices_controller_test.rb
=> Remove `context` and `should` from invoices_controller_test

test/integration/mandatory_keys_test.rb
* test/integration/mandatory_keys_test.rb
=> Remove `context` and `should` from mandatory_keys_test

test/integration/developer_portal/admin/applications_controller_test.rb
* test/integration/developer_portal/admin/applications_controller_test.rb
=> Remove `context` and `should` from applications_controller_test

test/integration/finance/charging_invoice_states_test.rb, test/integration/user-management-api/accounts_test.rb, test/unit/application_plan_test.rb, test/unit/contract_test.rb, test/unit/service_contract_test.rb, test/unit/service_test.rb
* test/integration/finance/charging_invoice_states_test.rb
* test/integration/user-management-api/accounts_test.rb
* test/unit/application_plan_test.rb
* test/unit/contract_test.rb
* test/unit/service_contract_test.rb
* test/unit/service_test.rb
=> Remove `context` and `should` from another bunch of tests

test/integration/user-management-api/application_plan_features_test.rb, test/integration/user-management-api/application_plan_limits_test.rb, test/integration/user-management-api/application_plan_metric_limits_test.rb, test/integration/user-management-api/application_plan_metric_pricing_rules_test.rb, test/integration/user-management-api/application_plan_pricing_rules_test.rb
* test/integration/user-management-api/application_plan_features_test.rb
* test/integration/user-management-api/application_plan_limits_test.rb
* test/integration/user-management-api/application_plan_metric_limits_test.rb
* test/integration/user-management-api/application_plan_metric_pricing_rules_test.rb
* test/integration/user-management-api/application_plan_pricing_rules_test.rb
=> Remove `context` and `should`  from application_plan_*_test

test/integration/finance/api/invoices_test.rb
* test/integration/finance/api/invoices_test.rb
=> Remove `context` and `should` from invoices_test

test/integration/stats/applications_test.rb, test/integration/stats/services_test.rb
* test/integration/stats/applications_test.rb
* test/integration/stats/services_test.rb
=> Remove `context` and `should` from integration/stats

test/factories/other.rb, test/unit/abilities/forums_test.rb, test/unit/array_test.rb, test/unit/cinstance/trial_test.rb, test/unit/month_test.rb, test/unit/referrer_filters_test.rb
* test/unit/array_test.rb
* test/unit/abilities/forums_test.rb
* test/unit/month_test.rb
* test/unit/referrer_filters_test.rb
* test/unit/cinstance/trial_test.rb
=> Remove `context` and `should` from a bunch of tests

test/unit/account/buyer_test.rb, test/unit/account/fields_test.rb, test/unit/account/gateway_test.rb, test/unit/account/provider_test.rb
* test/unit/account/buyer_test.rb
* test/unit/account/fields_test.rb
* test/unit/account/gateway_test.rb
* test/unit/account/provider_test.rb
=> Remove `context` and `should` from unit/account_test

test/unit/message_test.rb
=> Remove `context` and `should` from message_test

app/models/billing_summary.rb, test/unit/billing_summary_test.rb
Issue:
Sometimes it does not unstore the results, because the batch callback was not called
The root cause is not yet found, this still ensures that Redis memory usage won't grow indefinitely
=> Billing summary should expire

app/controllers/master/service_discovery/auth_controller.rb
Fixes usage of params in the auth controller
=> [params] Fixes master/service_discovery/auth_controller.rb

package.json, yarn.lock
PR https://github.com/3scale/porta/pull/2675 upgraded jquery-ui to 1.13, but it's breaking the datepicker.
To deploy a quickfix we should r**evert the change and block version to 1.12**
Later, in order to upgrade jquery-ui, we should:
- Make sure to use jQuery 1.8+ (we have 3.5 installed, but we are not using it in Admin portal)
- Check jQuery UI 1.13 [release notes](https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/) and [upgrade guide](https://jqueryui.com/upgrade-guide/1.13/) 
- Update code where needed
- Since we have a lot of conflicts with jquery versions, this may take a lot of time, then better to create a new task and not block this one (issue is happening on SAAS and needs a quick fix)
- See …
=> Bugfix: datepicker doesn't close

test/factories/plan.rb, test/unit/account_plan_test.rb, test/unit/application_plan_test.rb, test/unit/plan_test.rb, test/unit/service_plan_test.rb
* test/factories/plan.rb
* test/unit/account_plan_test.rb
* test/unit/application_plan_test.rb
* test/unit/plan_test.rb
* test/unit/service_plan_test.rb
=> Remove `context` and `should` and from plan_test

test/test_helpers/assertions.rb, test/test_helpers/pending.rb, test/unit/cinstance/billing_test.rb, test/unit/cms/email_template_test.rb, test/unit/finance/charging_test.rb, test/unit/helpers/messages_helper_test.rb, test/unit/liquid/drops/user_drop_test.rb, test/unit/mailers/user_mailer_test.rb, test/unit/observers/cinstance_observer_test.rb, test/unit/observers/message_observer_test.rb, test/unit/signup/plans_with_defaults_test.rb, test/unit/three_scale/search_test.rb
=> Remove `context` from the last batch of tests

test/unit/fields_definition_test.rb
* test/unit/fields_definition_test.rb
=> Remove `context` and `should` from fields_definition_test

test/unit/liquid/drops/application_drop_test.rb, test/unit/liquid/drops/application_plan_drop_test.rb, test/unit/messengers/service_contract_messenger_test.rb, test/unit/pdf/finance/invoice_generator_test.rb, test/unit/three_scale/spam_protection_test.rb, test/unit/user/roles_test.rb, test/unit/web_hook/event_spec_test.rb
* test/unit/liquid/drops/application_drop_test.rb
* test/unit/liquid/drops/application_plan_drop_test.rb
* test/unit/messengers/service_contract_messenger_test.rb
* test/unit/pdf/finance/invoice_generator_test.rb
* test/unit/three_scale/spam_protection_test.rb
* test/unit/user/roles_test.rb
* test/unit/web_hook/event_spec_test.rb
=> Remove `context` and `should` and from yet another bunch of tests

test/factories/cinstance.rb, test/test_helpers/cinstance.rb, test/unit/cinstance_test.rb
=> Remove `context` and `should` from cinstance_test

test/unit/payment_transaction_test.rb
* test/unit/payment_transaction_test.rb
=> Remove `context` and `should` and from payment_transaction_test

test/unit/user_test.rb
=> Remove `context` and `should` and from user_test

app/services/support_entitlements_service.rb, config/initializers/active_job_hooks.rb, lib/active_job/arguments.rb, lib/active_job/serializers.rb, lib/active_job/serializers/date_serializer.rb, lib/active_job/serializers/date_time_serializer.rb, lib/active_job/serializers/duration_serializer.rb, lib/active_job/serializers/module_serializer.rb, lib/active_job/serializers/object_serializer.rb, lib/active_job/serializers/symbol_serializer.rb, lib/active_job/serializers/time_object_serializer.rb, lib/active_job/serializers/time_serializer.rb, lib/active_job/serializers/time_with_zone_serializer.rb, test/unit/services/support_entitlements_service_test.rb
It enqueues Entitlement support email in ActionMailer::DeliveryJob
Instead of sending it along the web request
It will suppress some 5xx errors when the SMTP server is not available at the time of the web request
Part of THREESCALE-7574
- Imported ActiveJob::Arguments and ActiveJob::Serializers from Rails 6.1.4.1
in order to have Time serialization
I thought this is a good addition. ActiveJob arguments and serializers should be compatible with Rails 5.x
=> [email-async] Support entitlements

test/integration/provider/invoices_controller_test.rb
Some tests are outdated in the upgrade branch `rails` and are throwing "unknown key format". This is the same change as #2835 but for `master`.
=> [master] Fix unknown key format error

app/controllers/provider/admin/redhat/auth_controller.rb
Fixes usage of params in the provider admin redhat auth  controller
=> [params] Fixes provider admin redhat auth controller

test/integration/provider/invoices_controller_test.rb
Some tests are outdated in the upgrade branch `rails` and are throwing "unknown key format". It happened due to a bad re-formatting probably.
=> [rails] Fix unknown key format error

test/unit/finance/no_variable_cost_test.rb
In the past `bill for variable` test failed on 1st of the month. Now using `Timecop` to cover some other edge cases as well.
=> cover bill variable tests with timecop

test/functional/developer_portal/login_controller_test.rb
rarely
`FDeveloperPortal::LoginControllerTest#test_cas_is_not_displayed_on_login_page`
may fail, I suspect because of the random content of `authenticity_token`.
Example failure:
https://app.circleci.com/pipelines/github/3scale/porta/19117/workflows/7f60c74d-94d0-48cc-98df-0de12187f9ea/jobs/228400/parallel-runs/1
=> transient CAS login test failure

config/routes.rb
allow operations to check deployment data without need to save a cookie
```shell
curl http://localhost:9394/deploy/status | jq '.revision'
```
Should display the revision of the running code
=> allow /deploy endpoint on prometheus port

app/lib/forum_support/categories.rb
Fixes tests using  `app/lib/forum_support/categories.rb`: 
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-6
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-9
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-10
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-11
https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-12 …
=> Update usage of #include in categories.rb

Gemfile, Gemfile.lock
Upgrades bullet gem to a newer version. The old version is incompatible with rails 5.1.7. It results in errors like: `Wrong number of arguments (given 1, expected 2)`. 
The issue in the bullet Github: https://github.com/flyerhzm/bullet/issues/389
=> Upgrades bullet gem to 6.1.5

app/helpers/cms/form_helper.rb, features/step_definitions/new_cms/partials_steps.rb
`#parameterize` no longer accepts arguments (See [test failure](https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9341e/jobs/229561/tests#failed-test-1)) instead `separator: 'foo'` is passed.
Moreover, it downcases by default unless `preserve_case: true` is passed. Therefore any call to `downcase` is redundant.
=> Update usage of #parameterize for rails 5

app/controllers/admin/api/fields_definitions_controller.rb, doc/active_docs/Account Management API.json, spec/acceptance/api/fields_definition_spec.rb
Fixes choices parameter in the fields definition admin api controller.
https://issues.redhat.com/browse/THREESCALE-7615
=> [Threescale-7615] Fixes choices parameter in the fields definition controller

app/controllers/provider/admin/messages/outbox_controller.rb
Fixes failure:
```
Scenario: Sending a message
Then the "To" field should be fixed to "bob"
Message:
unable to convert unpermitted parameters to hash (ActionController::UnfilteredParameters)
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/strong_parameters.rb:265:in `to_h'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/inheritance.rb:218:in `subclass_from_attributes'
...
/opt/app-root/src/project/app/controllers/provider/admin/messages/outbox_controller.rb:45:in `build_message'
...
features/old/messages/provider_side.feature:27:in `the "To" field should be fixed to "bob"'
```
Link to build: https://app.circleci.com/pipelines/github/3scale/porta/19248/workflows/2546831f-88c2-4728-a620-bf9cd2b9 …
=> [params] Fixes Outbox controller

Gemfile, Gemfile.lock, test/unit/finance/bill_variable_for_plan_changed_test.rb
Needed for the rails upgrade. Fixes scenario:
```
Scenario: Turning charging on/off
And I press "Save"
Message:
undefined method `with_indifferent_access' for #<ActionController::Parameters:0x0000000011e2ec10> (NoMethodError)
```
=> 💎 Update `protected_attributes_continued` to 1.8.2

app/controllers/provider/admin/sudo_controller.rb
Fixes the sudo controllers usage when using rails 5.1 version. 
We need to convert the params to hash before calling `symbolize_keys`
=> [Params] Fixing sudo controllers when using symbolize keys

app/controllers/buyers/service_contracts_controller.rb
Fixes scenario:
```
Scenario: Subscribe to service with selected service plan
AfterStep hook at features/support/hooks.rb:59
Message:
unable to convert unpermitted parameters to hash (ActionController::UnfilteredParameters)
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/actionpack-5.1.7/lib/action_controller/metal/strong_parameters.rb:265:in `to_h'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/inheritance.rb:218:in `subclass_from_attributes'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/activerecord-5.1.7/lib/active_record/inheritance.rb:56:in `new'
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/protected_attributes_continued-1.3.0/lib/active_record/mass_assignment_security/reflection.rb:8:in `build_association' …
```
=> [params] Service contracts controller

app/controllers/finance/provider/settings_controller.rb, features/old/finance/settings/provider.feature
**Description**
~Unlike Hash, Params doesn't have `with_indiferent_access` so it has to be parsed when passed to `update_attribute`. However, since params are not permitted, `to_h` will fail.~
We need to upgrade `protected_attributes_continued` https://github.com/3scale/porta/pull/2870
**Steps to reproduce**
Go to Audience > Billing > Charging & Gateway and change charging settings
**Before**
**After**
=> [params] Settings controller

features/step_definitions/event_steps.rb, test/functional/master/api/services_controller_test.rb
Fixes can't cast class errors.
=> Fixes can't cast class errors when using rails 5.1 version

test/unit/cinstance_test.rb
This PR is need to fix the failing unit postgres tests.
**TypeError**: can't cast Class
**Fix**: Converted passed attribute to string as data type was string
=> Fixed other failing unit postgres tests

config/initializers/oracle.rb
Fix remaining Rails 5.1 issues. For easier review disable white space changes. This should be no change for current version because old visitor is used anyway.
=> [THREESCALE-5010] prepare for oracle adapter and rails upgrade

app/javascript/src/Policies/index.jsx, app/javascript/src/Types/libs/libdefs.js, app/javascript/src/utilities/fetchData.js, package.json, yarn.lock
`whatwg-fetch` is a polyfill for `fetch` that we no longer need. We have been using `fetch` for a while so it should be safe to remove.
`fetchData` is used in `ActiveDocs v3 autocomplete`, `policies`, `service discovery` and `inline stats`. Everything should be working as usual.
=> Remove whatwg-fetch polyfill

app/indices/account_index.rb, app/models/account/states.rb, app/workers/sphinx_account_indexation_worker.rb, app/workers/sphinx_indexation_worker.rb, config/initializers/sphinx.rb, test/monkey_patches/active_job_test_helper.rb, test/test_helpers/sphinx.rb, test/unit/account/search_test.rb, test/unit/presenters/buyers/accounts_index_presenter_test.rb, test/unit/tasks/services_test.rb, test/workers/delete_object_hierarchy_worker_test.rb, test/workers/sphinx_account_indexation_worker_test.rb, test/workers/sphinx_indexation_worker_test.rb
we may also need to add a callback when state of account changes to `scheduled_for_deletion`. But this probably will quickly reduce index size.
=> Sphinx index only non-deleted accounts

app/workers/backend_storage_rewrite_worker.rb
Fixes this errors that appears in the thinking sphinx logs.
```log
2021-12-14T12:38:36.221Z 132730 TID-1ovjl6 WARN: {"context":"Job raised exception","job":{"class":"BackendStorageRewriteWorker","args":[1],"retry":true,"queue":"low","jid":"34e41e7542db77ef034f3b32","created_at":1639485407.7940912,"bid":"yJVM1slCL5sCAA","enqueued_at":1639485516.1842265,"error_message":"You are passing an instance of ActiveRecord::Base to `find`. Please pass the id of the object by calling `.id`.","error_class":"ArgumentError","failed_at":1639485407.819227,"retry_count":2,"retried_at":1639485465.4869988},"jobstr":"{\"class\":\"BackendStorageRewriteWorker\",\"args\":[1],\"retry\":true,\"queue\":\"low\",\"jid\":\"34e41e7542db77ef034f3b32\",\"created_at\":1639485407.79409 …
```
=> Fixes errors with sphinx BackendStorageRewriteWorker

app/controllers/forums/admin/categories_controller.rb, app/controllers/forums/admin/forums_controller.rb, app/controllers/forums/admin/hiden_forum_controller.rb, app/controllers/forums/admin/posts_controller.rb, app/controllers/forums/admin/subscriptions_controller.rb, app/controllers/forums/admin/topics_controller.rb, app/controllers/forums/admin/user_topics_controller.rb, app/lib/forum_support/public.rb, config/docker/rolling_updates.yml, config/examples/rolling_updates.yml, features/old/forums/anonymous_posting.feature, features/old/forums/buyer_side/visibility.feature, features/old/forums/privacy.feature, features/old/forums/subscriptions.feature, features/step_definitions/navigation_steps.rb, features/step_definitions/security/topic_steps.rb, test/helpers/vertical_nav_helper_test.rb
PR in deploy repo: https://github.com/3scale/deploy/pull/727
Updates public forum support helper to check rolling update, not only the provider setting for Forum. This way by switching the rolling update `forum` off all Forum functionality will be hidden.
New providers won't have Forum templates in their CMS either.
ForumsController will now raise an error when the RU is off, showing a 404 page:
[THREESCALE-8032: Hide forum functionality from all users (dev portal)](https://issues.redhat.com/browse/THREESCALE-8032)
Set rolling update `forum: false` and reset the DB, then start the server. Forum should not be visible anywhere:
- Audience > Forum
- Audience > Dev portal > Settings > Forum …
=> Hide Forum in SaaS

app/lib/permalink_fu.rb, app/models/cms/builtin.rb, app/models/payment_gateway_setting.rb, app/models/proxy.rb, config/initializers/new_framework_defaults.rb
Rails changed the behavior of `attribute_changed?` in after and before callbacks. Older versions will throw deprecation warnings indicating which methods to use instead.
```
DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.
```
This PR reviews usages of `attribute_changed?` and replace it with `saved_change_to_attribute?` when necessary.
More info:
* https://rubyinrails.com/2019/04/08/rails-changed-behavior-of-attribute-changed-in-callbacks/
* …
=> Fix deprecated usage of `attribute_changed?` in callbacks

yarn.lock
Fixes:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```
Output:
```
Latest version:     1.0.30001311
Installed version:  1.0.30001245
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
warning " > eslint-plugin-flowtype@5.8.0" has incorrect peer dependency "eslint@^7.1.0".
warning " > eslint-plugin-promise@5.1.0" has incorrect peer dependency "eslint@^7.0.0".
warning "flow-typed > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
Cleaning package.json dependencies from caniuse-lite
$ yarn remove -W caniuse-lite
warning " > …
```
=> Update `canuse-lite` node package

app/events/oidc/proxy_changed_event.rb, test/events/oidc/proxy_changed_event_test.rb
According to the warning, it should be `saved_change_to_backend_version` instead of `saved_changes`.
```
DEPRECATION WARNING: The behavior of `attribute_change` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute` instead. (called from valid? at (pry):7)
```
=> Small change

app/controllers/admin/api/web_hooks_failures_controller.rb
**DEPRECATION WARNING**: `:nothing` option is deprecated and will be removed in Rails 5.1. Use `head` method to respond with empty response body.
Main Task: https://issues.redhat.com/browse/THREESCALE-8009
Subtask: https://issues.redhat.com/browse/THREESCALE-8186
=> Remove `:nothing` deprecated option

app/views/buyers/service_contracts/bulk/send_emails/new.html.erb, features/old/services/subscriptions/bulk_operations/send_emails.feature
When sending emails from the bulk operations emails for subscriptions can be sent if body and subject is empty
Fixed subtask 
Main task : https://issues.redhat.com/browse/THREESCALE-8009
SubTask: https://issues.redhat.com/browse/THREESCALE-8145
=> Prevent email from being sent in bulk to Subscriptions without subject/body

app/controllers/provider/admin/account/payment_gateways/braintree_blue_controller.rb, test/integration/provider/admin/account/payment_gateways/braintree_blue_controller_test.rb
```
NoMethodErrordeveloper_portal/admin/account/braintree_blue#hosted_success
undefined method `deep_merge' for #<ActionController::Parameters:0x00000010ea575...>
```
It seems that `BrainTreeBlueCrypt#confirm` was relying on a hash as a paremeter, but after upgrading rails `params.require` returns `ActiveController::Parameters` instead.
https://github.com/3scale/porta/blob/7f33217f7b54a01d792574136fe1b1693a895bf2/app/lib/payment_gateways/brain_tree_blue_crypt.rb#L19-L20
https://app.bugsnag.com/3scale-networks-sl/system/errors/622f6145c44845000939c6e7?event_id=622f61450092d7af73190000&i=sk&m=nw
=> 🐛 Parse customer params to hash in BrainTreeController

lib/developer_portal/app/controllers/developer_portal/admin/account/braintree_blue_controller.rb, test/functional/developer_portal/admin/account/braintree_blue_controller_test.rb
Follows up on https://github.com/3scale/porta/pull/2938
```
NoMethodErrordeveloper_portal/admin/account/braintree_blue#hosted_success
undefined method `deep_merge' for #<ActionController::Parameters:0x00000010ea575...>
```
It seems that `BrainTreeBlueCrypt#confirm` was relying on a hash as a paremeter, but after upgrading rails `params.require` returns `ActiveController::Parameters` instead.
https://github.com/3scale/porta/blob/7f33217f7b54a01d792574136fe1b1693a895bf2/app/lib/payment_gateways/brain_tree_blue_crypt.rb#L19-L20
https://app.bugsnag.com/3scale-networks-sl/system/errors/622f6145c44845000939c6e7?event_id=622f61450092d7af73190000&i=sk&m=nw
=> 🐛 [dev-portal] parse brain_tree_controller customer params to hash

lib/developer_portal/lib/liquid/filters/rails_helpers.rb, test/integration/liquid/legacy_tags_test.rb
There used to be a script `buyer/1/analytics.js` included in some Dev portal templates, I think these two only:
- https://github.com/3scale/system/blob/bbfaa59f2b70d065d432c5771796787732071850/lib/developer_portal/app/views/developer_portal/stats/index.html.liquid#L1-L3
- At some point in `applications/show`
Sometime before the open-sourcing step, the package `highcharts` was removed [with this](https://github.com/3scale/system/pull/9368/files?show-deleted-files=true&show-viewed-files=true&file-filters%5B%5D=#diff-62adc7322d21216fc0dca38d01c1b388f6390f681ff2a0ece2abadf28216cb68) and other scripts. This one however was left inside `THREESCALE_JAVASCRIPTS`, meaning the script would still be available as an importable asset.
Therefore, there is a customer with an old versions of either of …
=> 🐛 Remove `buyer/1/analytics` from list of Dev Portal available scripts

app/lib/events/importers/first_daily_traffic_importer.rb, app/lib/events/importers/first_traffic_importer.rb, test/unit/events/importers/first_daily_traffic_importer_test.rb, test/unit/events/importers/first_traffic_importer_test.rb
https://app.bugsnag.com/3scale-networks-sl/system/errors/61ba778a71d2ed0008544c1d?event_id=622fc0e90092e226db140000&i=sk&m=fq
No idea how to reproduce this but hopefully the new tests are enough.
=> Prevent traffic importers `#notify_segment` from rising nullpointer error

app/mailers/post_office.rb, test/unit/mailers/post_office_test.rb
We observed error from ActionMailer background job
>  NoMethodError · undefined method `buyer?' for nil:NilClass
It seems to appear when account got deleted before delivery happens.
This is just logging the error. But PR is in WIP status because
I try to make sure that we don't try to deliver such messages when
for example an account is deleted. So far I don't see such occasion though.
=> fix NoMethodError: undefined method for nil:NilClass

features/api/backend_usages.feature, features/support/capybara.rb
Cucumbers are not written well and that is a fact. I don't think nobody has ever understood them very well and one of the workarounds added to force them pass was adding a max waiting time of 10 seconds whereas the default is 2. That means, every time capybara checks something it isn't in the UI it will wait 10 seconds. Thats x5 spent time for elements that are not supposed to be there!
Whenever cucumber fails finding or not finding a selector, it should be addressed locally
- Rethink the Scenario and steps involved (it's supposed to test behavior NOT functionality)
- Add a specific max wait time for that specific instruction (by using `wait: T` option)
- Re write the step to assert the scenario correctly: look for invisible, wait for X to happen, navigate to a route instead of clicking a …
=> 🥒 Reduce Cucumber build time

app/controllers/provider/admin/account/users_controller.rb, app/models/user/permissions.rb, test/integration/provider/admin/account/users_controller_test.rb
`attributes` used to be a hash, now it's ActionController::Parameters.. and sometimes it's still a hash 🤷🏻‍♂️ .
Error found https://app.bugsnag.com/3scale-networks-sl/system/errors/623154afea8d6b0008c052c5?event_id=623154af0092ebfb070a0000&i=sk&m=nw
=> Attributes are now Parameters in user_controller's #update_attributes

app/controllers/admin/api/services/proxy/configs_controller.rb, app/lib/apicast/curl_command_builder.rb, app/models/proxy_config.rb, test/integration/master/api/proxy/configs_controller_test.rb, test/unit/account_test.rb, test/unit/proxy_config_test.rb
@akostadinov came up with a new query that is also very quick and it can be still a scope, therefore we can keep the `.current_versions` format.
The query to be fixed is `ProxyConfig#current_versions`. It is a very complex one because it's supposed to check the ProxyConfig with max version for each Proxy and each environment, and be compatible with other scopes such as `by_environment` and `by_host`.
After some investigation and testing, this is **not possible**. The query is just too complex for ActiveRecord to figure out, therefore I've refactored it into a class method that will run a handcrafted query, hopefully maintaining the same behaviour.
Here are the places where `current_versions` is called and a comparison with the old and new queries, using 7000 Proxy configs.
This endpoint …
=> Improve performance of SQL proxy_configs query

app/javascript/src/Common/components/Select.jsx, spec/javascripts/Common/components/Select.spec.jsx
`title` was used for `ariaLabel`, but the former can be a React component which is not valid as aria-label. Therefore, we need a new prop to pass a valid aria-label.
=> Update Common/Select component

app/lib/authentication/by_cookie_token.rb, test/unit/lib/authentication/by_cookie_token_test.rb
It seems like this method it being called many times even tho the updated values are already `nil`.
=> Reduce times `by_cookie_token` query is executed

features/old/accounts/bulk_operations/send_email.feature
When sending emails from the bulk operations emails can be sent if body and subject is empty
Main task : https://issues.redhat.com/browse/THREESCALE-8009
SubTask: https://issues.redhat.com/browse/THREESCALE-8141
=> THREESCALE-8141 Prevent emails from being sent without subject and/or body for accounts

features/old/applications/providers/bulk_operations/send_emails.feature
When sending emails from the bulk operations emails can be sent if body and subject is empty
Main task : https://issues.redhat.com/browse/THREESCALE-8009
SubTask: https://issues.redhat.com/browse/THREESCALE-8140
=> THREESCALE-8140 Prevent emails from being sent without subject and/or body for applications

app/models/metric.rb
WARNING: Can't mass-assign protected attributes 
Added all the attributes which are mass assigned and removed duplicate from protected 
https://issues.redhat.com/browse/THREESCALE-8347
=> THREESCALE-8347 fixed warnings Can't mass-assign protected attributes

test/integration/admin/api/account/proxy_configs_controller_test.rb
This used to fail with the old `current_versions`. Now it doesn't and it doesn't make sense to ask for pagination, but since it's possible and it used to fail, here's a test for it.
=> Add test for getting latest version + pagination

app/lib/backend/model_extensions/metric.rb, test/unit/backend/model_extensions/metric_test.rb
The test is doing nothing because essentially we don't protect against a race so callback executes twice. We do not need it to execute twice so there is no point to test that. If it executed only once, that would be better but then this is not the case.
=> metrics delete race simplification

app/models/access_token.rb, app/models/cinstance.rb, app/models/web_hook/event.rb
In these case both methods are equivalent and in Rails 5.2+ they will be equivalent in all conditions. But updating to `#saved_changes` to prevent deprecation warnings as well because this is method with more clear intentions and behavior. At least I don't have to think how to write `previous` properly anymore.
Namely in Rails 5.1, `#saved_changes` and `#previous_changes` differ in behavior only in `after_save` callback where `#previous_changes` returns nothing. In 5.2 `#previous_changes` will behave exactly as `#saved_changes`.
=> use #saved_changes in place of #previous_changes

app/models/email_configuration.rb, test/models/email_configuration_test.rb
CA trust is dependent on runtime environment so we need to set it
from default in all cases.
If we implement in the future a feature to specify trust in another way,
it could be merged only in absense of user configuration for that. For now
having it always merged is the safest option.
=> EmailConfigurations CA trust

Gemfile, Gemfile.lock
sour usage was removed in #2893
sidekiq stopped using sinatra in [v4.2](https://github.com/mperham/sidekiq/blob/main/Changes.md#420=)
I have verified that sidekiq web still works.
=> remove unused sour and sinatra gems

Gemfile, Gemfile.lock, app/lib/three_scale/json_representer.rb
DEJAVU https://github.com/3scale/porta/pull/2391
Since we're using ruby 2.4 in the production server we can't upgrade Nokogiri just yet.
Reverts 3scale/porta#2988
=> Revert "Bump nokogiri from 1.10.10 to 1.13.6"

app/views/provider/admin/messages/outbox/new.html.erb, features/old/applications/providers/bulk_operations/send_emails.feature, features/provider/admin/messages/outbox.feature, features/support/paths.rb
**hat this PR does / why we need it:**
When sending emails from the bulk operations emails can be sent if body and subject is empty
In admin portal - /p/admin/messages/outbox/new - page under Audience > Messages > Inbox/Sent messages
https://issues.redhat.com/browse/THREESCALE-8009
https://issues.redhat.com/browse/THREESCALE-8392
=> THREESCALE-8009 prevent outbox emails from being sent empty

app/presenters/provider/admin/backend_apis_index_presenter.rb, test/unit/presenters/api/services_index_presenter_test.rb, test/unit/presenters/provider/admin/backend_apis_index_presenter_test.rb
[THREESCALE-8402 Deleted product or backend is still visible in list
](https://issues.redhat.com/browse/THREESCALE-8402?jql=project%20%3D%20THREESCALE%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(currentUser())%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)
1. Go to Backends.
2. Delete a previously created backend. 
3. Confirm that it doesn't appear on Backends list.
4. Go to Products.
5. Delete a previously created product.
6. Confirm that it doesn't appear on Products list
=> Deleted product or backend is still visible in list

app/models/account.rb, test/test_helpers/sphinx.rb, test/unit/indices/indexing_test.rb
MySQL 5.7 used incorrect index when accounts were
queried for sphinx indexation in batches.
This made `rake sphinx:enqueue[Account]` very slow.
Altering the `not_master` scope a little seems to
help optimizer make the right choice so that
getting each batch takes less than 200ms instead
of 3 to 8 seconds.
fixes THREESCALE-8586
=> MySQL account query optimization

app/views/api/services/forms/_integration_settings.html.slim, test/integration/api/services_controller_test.rb
[THREESCALE-8570 Unable to change product authentication method](https://issues.redhat.com/browse/THREESCALE-8570)
1. Navigate to Product setting page (/apiconfig/services/{product_id}/settings).
2. Change authentication method.
3. Click Update Product button at the bottom of the page.
4. You get 'Product information updated' message but authentication method won't change.
=> Unable to change product authentication method

app/views/api/services/settings.html.slim
[THREESCALE-8557 Incorrect behaviour after Product update with invalid public base URL](https://issues.redhat.com/browse/THREESCALE-8557)
1. Go to Product Settings page (/apiconfig/services/{service_id}/settings)
2. Write invalid URL to Staging or Production public base URL text field
3. Click Update Product button at the bottom of the page
=> Incorrect behaviour after Product update with invalid public base URL

features/step_definitions/flash_steps.rb, features/step_definitions/plans_steps.rb
[THREESCALE-8549](https://issues.redhat.com/browse/THREESCALE-8549)	Fix random failure "failed Delete an account plan" in oracle
=> Fix "Delete Account" scenario failing in Oracle

app/concerns/searchable.rb, app/controllers/proxy_rule_shared_controller.rb, app/lib/three_scale/search.rb, app/models/account/search.rb, app/queries/proxy_rule_query.rb, features/services/mapping_rules.feature, features/step_definitions/proxy_steps.rb, test/unit/queries/proxy_rule_query_test.rb
Fixes missing pagination links on mapping rules search results.
Fixes [THREESCALE-7327: Mapping rule search pagination not displayed on search results page](https://issues.redhat.com/browse/THREESCALE-7327)
From the above JIRA:
- Create a new product
- Add more than 25 mapping rules similar to /cust/(RANDOM_PATHs)
- You will notice that the pagination is enabled by default when you load the admin-portal mapping rules page.
- Search the term /cust
- Only 20 results will be displayed and pagination is not shown to view the rest of the results.
The root cause of the issue is that the size of the search results returned by Sphinx was always maximum 20, which …
=> THREESCALE-7327: Fix missing pagination links on mapping rules search results

openshift/system/Dockerfile
Sphinx 3.x is non-FLOSS so we can't use it.
It also lacks builds for non-x86 archs.
We can update in the future to Manticore.
Especially when we update to RHEL8 base image,
2.2.11 fails to work with MySQL 8.
=> revert back to Sphinx 2.2.11

app/presenters/buyers/accounts_index_presenter.rb
There's a N+1 problem in Buyers::AccountsIndexPresenter
[THREESCALE-8530](https://issues.redhat.com/browse/THREESCALE-8530)
1. Go to `/buyers/accounts`
2. Verify that bullet is not warning about the n+1 anymore
3. Also, in the rails console, a new query is executed to retrieve all users in one single query
`  ↳ app/views/buyers/accounts/_search_results.html.slim:43
User Load (0.5ms)  SELECT users.* FROM users WHERE users.role = 'admin' AND (username <> '3scaleadmin') AND users.account_id IN (5, 4, 3)`
=> THREESCALE-8530: Fix a N+1 problem in Buyers::AccountsIndexPresenter

.tool-versions.sample, INSTALL.md
Updates our installation guide:
* For latest macOS and Silicon chip
* Some fixes to Fedora
* asdf is the recommended version manager now for ruby, Node.js and Python.
[ASDF](https://asdf-vm.com/guide/getting-started.html#global)
Any proper dev environment requires a version manager tool, ruby and node in the case of porta. Throughout the years the team has tried a bunch of them: nvm, rvm, rbenv... and recently the majority seems to favor `asdf` which main advantage is it allows managing both packages.
Moreover, there's been times when a conflict between versions between local and prod has caused us problems.
My proposal is to promote `asdf` as the preferred version manager for our project. This way we're all in the same page and we can mitigate potential configuration issues. It will also …
=> Update setup steps (`asdf` as default now)

app/lib/signup/domains_builder.rb, app/models/account.rb, app/views/provider/admin/accounts/new.html.slim, config/locales/en.yml, test/unit/account/provider_domains_test.rb, test/unit/account_test.rb, test/unit/signup/result_test.rb
This issue is for tenant (account in master portal) and not for account in admin portal. Because tenant URL is created from tenant name hence those special characters are forbidden.
https://issues.redhat.com/browse/THREESCALE-7540
mentioned in Jira
Note for reviewer:
Validation was already there but error message is not shown so I have added.
=> THREESCALE-7540 fix master admin tenant name issue

Gemfile, Gemfile.lock, app/lib/pdf/finance/invoice_generator.rb, app/lib/pdf/finance/invoice_report_data.rb, config/docker/paperclip.yml, config/examples/amazon_s3.yml, config/examples/paperclip.yml, openshift/system/.env, test/unit/paperclip_test.rb, test/unit/pdf/finance/invoice_generator_test.rb, test/unit/pdf/finance/invoice_report_data_test.rb
Fixes the issue where the logo image is not added to the invoice PDF.
Fixes https://issues.redhat.com/browse/THREESCALE-6933
1. Add a Logo in Audience > Developer portal > Logo
2. Create an invoice for an account
3. Generate a PDF invoice
4. Check that the logo appears on the invoice PDF
`PAPERCLIP_STORAGE` was renamed to `FILE_UPLOAD_STORAGE` for consistency.
The root cause of the issue is that the invoice generator was using the `.url` method of paperclip attachment, which for file system storage type returns a **relative** path on the server (which is fine for front-end usage), instead of the actual path in the file system.
Also, it's important to note …
=> THREESCALE-6933: Fix paperclip filesystem

Gemfile, Gemfile.lock
Reverts 3scale/porta#3069
Ruby 2.4 is not supported anymore.
=> Revert "Bump commonmarker from 0.21.0 to 0.23.6"

test/unit/services/aws/credentials_service_test.rb
A quick fixup for https://github.com/3scale/porta/pull/3066
`assert` will pass if the 1st argument is truthy, in this case the 2nd one can be anything :upside_down_face:
=> Fix assertions for AWS creds service test

app/views/provider/admin/account/payment_gateways/braintree_blue/edit.html.slim
Crappy solution. We leave the "good one" for when we have time.
> **What this PR does / why we need it**:
> 
> The JS at Braintree edit form is faulty, probably due to inconsistent jQuery version or unexpected upgrade.
> 
> The Braintree js SDK is also being downloaded via CDN, even though it's already included as a NPM package. For that reason the JS has been moved into a pack (to be handled by webpack and have access to NPM modules).
> 
> Moreover, this form is already implemented by React and used in the Dev portal but this this bug is a blocker we're not gonna spend time refactoring the whole page.
> 
> **Which issue(s) this PR fixes** 
> 
> [THREESCALE-8808: SaaS customers not able to add/edit Payment details](https://issues.redhat.com/browse/THREESCALE-8808)
> 
> **Special notes for …
=> Fix Braintree form

Gemfile, Gemfile.lock, config/webpacker.yml, package.json, yarn.lock
=> Update webpacker to 5.4.3

app/views/provider/admin/cms/groups/edit.html.erb
Developer Portal > Groups > edit is returning an internal server error, due to this line: 
[/app/views/provider/admin/cms/groups/edit.html.erb#L5](https://github.com/3scale/porta/blob/e415c82a8eb57a65724c84ae71741f101f294d2c/app/views/provider/admin/cms/groups/edit.html.erb#L5)
As far as I know, Formtastic 2.3.1 doesn't allow any actions other than `:submit`, `:reset` and `:cancel`.
[lib/formtastic/helpers/action_helper.rb#L90-L96](https://github.com/formtastic/formtastic/blob/2.3.1/lib/formtastic/helpers/action_helper.rb#L90-L96)
To show the commit button, the method `commit_button` must be called explicitly, and it must be wrapped under `f.actions` in order to get the proper styling. The same way that it's done in the `new` form: …
=> THREESCALE-8875: Fix developer portal groups edit page

openshift/system/Dockerfile, openshift/system/entrypoint.sh
jemalloc has a performance and size advantage when running
Ruby on Rails. So use it when available in the container.
container image `quay.io/3scale/porta:jemalloc-20221021`
=> use jemalloc or memkind when present

doc/dependency_decisions.yml, package.json, yarn.lock
From time to time, `canvas.node` throws an error that mess Circleci or yarn install or whatever. Example:
```
FAIL  spec/javascripts/utilities/json-utils.spec.ts
● Test suite failed to run
/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/app-root/src/project/node_modules/canvas/build/Release/canvas.node)
at Object.<anonymous> (node_modules/canvas/lib/bindings.js:3:18)
FAIL  spec/javascripts/Settings/components/AuthenticationSettingsFieldset.spec.tsx 
```
TL;DR: Well it turns out we don't even use this dependency 🤷🏻‍♂️ .
Some history though:
When Policies were added (#687), instead of using the existing testing library for React `enzyme`, a new package `jsdom` was added to be used literally twice, one to test `Editor` and …
=> ➖ Remove `canvas`

app/workers/sphinx_indexation_worker.rb, test/workers/sphinx_indexation_worker_test.rb
we needed this part when we changed enqueuing from passing an object
to passing a class and id. It was only needed until old jobs were
drained.
So we have this code in 2.12 as well 2.13, it should be fine
to get rid of it in 2.14
=> clean compatibility code in SphinxIndexationWorker

openshift/system/entrypoint.sh
let us fail quickly in case any commands fail
instead of trying to figure out why something fails to work as expected
=> fail if setup commands fail

app/controllers/provider/admin/messages/inbox_controller.rb, test/functional/provider/admin/messages/inbox_controller_test.rb
prevent Messages being sent without a subject or body in reply to message form under Messages > Inbox > Message
https://issues.redhat.com/browse/THREESCALE-8443
Emails can be sent without a subject or body in reply to message form under Messages > Inbox > Message
e.g. path /p/admin/messages/inbox/{message_id}
try sending message without subject.
=> THREESCALE-8443 prevent Mesages being sent without a subject or body in reply to message form under Messages > Inbox > Message

config/initializers/filter_parameter_logging.rb
Some sensitive parameters are being dumped to the logs without any masking. This PR adds those parameters to the filtering list.
[THREESCALE-5442](https://issues.redhat.com/browse/THREESCALE-5442)
1. Send a request including one of the sensitive parameters:
`curl http://provider-admin.3scale.localhost:3000//admin/api/accounts.xml?access_token=supersecrettoken`
3. Check how it¡s been traced in the logs
This filters parameters being sent to the app, but the issue also mentions how some environmental variables with sensitive values are being disclosed in the the pods logs. Those logs are generated by the container engine and are out of our scope. The only way …
=> THREESCALE-5442: Redact sensitive parameters in logs

app/controllers/finance/api/payment_callbacks/stripe_callbacks_controller.rb, test/integration/finance/api/payment_callbacks/stripe_callbacks_controller_test.rb
When a client is using Stripe to accept payments from other applications besides 3scale, all payment events are sent through all webhooks, so we receive them even when we don't care. So far, we were returning a 404 in that situation as the payment intent was not in our DB, but that's causing problems to clients since Stripe disables a webhook if it returns 404 too many times. This PR makes it return a 204 to acknowledge the reception in order to prevent Stripe to disable the webhook.
[THREESCALE-6851](https://issues.redhat.com/browse/THREESCALE-6851)
The easiest way to generate a stripe payment out of 3scale is to use the [stripe  cli](https://stripe.com/docs/stripe-cli) tool.
1. Log into the …
=> THREESCALE-6851: Stripe webhook: Acknowledge reception even for payments we don't care about

app/javascript/packs/inline_chart.tsx
Fixes a bug that was introduced during Flow > Typescript migration.
Fixes https://issues.redhat.com/browse/THREESCALE-8913
1. Load any application page
2. Make sure the "Usage in last 30 Days" chart gets loaded (even with empty data), and not shows up with a spinning icon.
=> THREESCALE-8913: Fix inline charts - missing unitPluralized value

jest.config.js, tsconfig.json
There are inconsistencies between TS and Jest config files. `tsconfig` targets module `ES6` which is meant for web (whereas CommonJS is how node works`.
However, the preset we're using for jest actually transforms `ts` and `tsx` files to CommonJS, hence the following error:
```
ReferenceError: Cannot access 'enzyme_1' before initialization
4 | import $ from 'jquery'
5 | (global as any).jQuery = $
> 6 |
| ^
7 | Enzyme.configure({ adapter: new Adapter() })
8 |
at Object.<anonymous> (spec/javascripts/setupTests.ts:6:1)
at async TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
at async runJest (node_modules/@jest/core/build/runJest.js:404:19)
at async _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
at async runCLI …
```
=> 🔧 Use proper jest preset and TS moduleResolution

app/javascript/packs/braintree_customer_form.ts, app/views/payment_gateways/_braintree_customer_form.html.erb
The first time `billingAddress` is empty. Before migrating to TS it was defined as `{}` by default but this got lost in translation. Now the default is an object with all expected attributes set as empty string so that the Form fields does not complain with `undefined` values. `null` values are also stripped from the original object by calling `.compact` before `to_json`.
[THREESCALE-8922: Unable to add/edit credit card details in developer portal](https://issues.redhat.com/browse/THREESCALE-8922)
**Verification steps:**
1. Set Braintree as credit card gateway in the admin portal
2. Sign in with a new user (can't have billing address data) in Developer portal
3. Go to Settings > Credit card details > Add Credit Card …
=> 🐛 Fix default values in Braintree customer form

app/javascript/packs/braintree_customer_form.ts, app/javascript/src/PaymentGateways/braintree/BraintreeBillingAddressFields.tsx, app/javascript/src/PaymentGateways/braintree/types.ts, app/views/payment_gateways/_braintree_customer_form.html.erb
Reverts and fixes: #3116 
The whole Braintree logic needs and will be refactored shortly. But right now there's a blocker bug in production and the safest way is to revert this pack to its original, pre-ts form.
Reference: https://github.com/3scale/porta/blob/3scale-2.12.1-GA/app/javascript/packs/braintree_customer_form.js
[THREESCALE-8922: Unable to add/edit credit card details in developer portal](https://issues.redhat.com/browse/THREESCALE-8922)
=> 💩 Revert braintree fix pre TS

app/lib/cms/s3.rb, test/unit/cms/s3_test.rb
QE noticed that, when `ENV['AWS_HOSTNAME']` is not provided, Paperclip is not able to generate the correct path to S3 files.
This happens because we're now returning an empty string (`""`) instead of `nil` in `CMS::S3.hostname` when the ENV variable is not provided. When a hostname is not provided (`nil`) Paperclip tries to get it from the provided credentials and, when not found, defaults to `s3.amazonaws.com` ([reference](https://github.com/thoughtbot/paperclip/blob/c769382c9b7078f3d1620b50ec2a70e91ba62ec4/lib/paperclip/storage/s3.rb#L197-L202)). Since we're sending an empty string, paperclip just returns it as the hostname.
This change was introduced not long ago in https://github.com/3scale/porta/pull/3095.
1. When …
=> Fix CMS::S3.hostname

lib/developer_portal/lib/liquid/xss_protection.rb
In our development environments, the developer portal is losing its styling after making some changes in the ruby code.
No jira for this
1. Open the developer portal
2. Make some changes in the code
3. Open the developer portal again
4. The portal should keep it's styling
The problem is caused because some `style` and `script` tags are being escaped. The piece of code that escapes these tags is [/lib/developer_portal/lib/liquid/xss_protection.rb#L20](https://github.com/3scale/porta/blob/9dc90cba804404c6de9bb727112c0c4bb89017b8/lib/developer_portal/lib/liquid/xss_protection.rb#L20). `context.registers[:escape_html]` seems to be always `true`, but …
=> Fix developer portal html escaping

config/examples/settings.yml, config/initializers/bugsnag.rb
This is a way to set a different `releaseStage` metadata on Bugsnag (e.g. `staging`), while still using `RAILS_ENV=production`)
**NOTE:** In order to use a different environment `Rails.configuration.three_scale.error_reporting_stages` (in `settings.yml`) must be changed to include the new environment.
This env var as added as default one in Bugsnag Ruby in 6.16, see [the PR](https://github.com/bugsnag/bugsnag-ruby/pull/613) and the [release notes](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.16.0).
=> Add BUGSNAG_RELEASE_STAGE and use it in Bugsnag initializer

app/workers/process_notification_event_worker.rb, test/workers/process_notification_event_worker_test.rb
This PR removes non-active users from the list of possible email receivers.
Fixes [THREESCALE-8903](https://issues.redhat.com/browse/THREESCALE-8903).
1. Configure SMTP Settings on 3scale in case it is not configured yet
2. Create a New Temporary Email account (i.e using mailhog)
3. As an already existing Admin (Provider) user - User A - log into the admin portal and invite the new user (Provider) - User B - with the email created in the step above
4. User A should create some new Developer Accounts and Applications
5. User B will receive email notifications triggered by the above events
6. User A should suspend User B by using the Account Management API User Suspend (provider account)
7. …
=> THREESCALE-8903 - Prevent notifications to be sent to non active users

Gemfile, Gemfile.lock
Updates the fork used for the `httpclient` ruby gem
same exact code on both forks - the 3scale one having the benefit that it doesn't depend on an external (nowadays) contributor.
=> Fix httpclient fork

openshift/system/contrib/scl_enable
This is required because cachito requires `git > 2.7.0` and the git version available in the current RHEL7 parent image is < 2.0
In case the env var is not set, this shouldn't affect anything
=> Allow enabling latest git version

Gemfile, Gemfile.lock
* Updates the fork used for the `httpclient` ruby gem
same exact code on both forks - the 3scale one having the benefit that it doesn't depend on an external (nowadays) contributor.
* Fixes version of httpclient
the `require_relative` change is necessary for bundler to be able to correctly resolve the dependencies provided by Cachito
(cherry picked from commit f916a10ef03068a119f84f394730e098e24ba6f7)
I would like to promote this fix to the 2.13 release stream, so that continuous product builds are functional again. (they'll be broken until this is ported over).
We need this to be a part of 2.13.1 release (current expected release date 16 Jan), for source compliance reasons.
=> Backport httpclient fix in 2.13 stream

config/application.rb
In THREESCALE-8905 it became known that these settings n 2.12 did not
take effect. While in 2.13 they did again, it is worth reverting back
to the community standards.
In 2.12 we had these settings in an initializer that was actually not loaded
early enough as evidenced by THREESCALE-8905
Given that we had no issues reported in SaaS and only one 2.12 user that used reverse proxy improperly, I think it is
safe to drop that option and use the Rails recommended default.
=>   remove obsolete CSRF options

app/controllers/admin/api/cms/files_controller.rb, doc/active_docs/CMS API.json
The OpenAPI v1 spec for the CMS API contains some wrong parameters for the DELETE File endpoint
This is part of: [THREESCALE-8991](https://issues.redhat.com/browse/THREESCALE-8991)
=> CMS API: Remove wrong params for DELETE file

lib/tasks/licenses.rake
rake fails in production environment (read container images) with the changes from #3093
```
LoadError: cannot load such file -- license_finder
```
Because `license_finder` is a development dependency and these are
not installed in images, the `require` statement should only be
evaluated if one tries to call the dependent tasks.
Otherwise any rake call raises an error to load `license_finder`.
This is consistent with how it worked when we used cli.
=> fix rake in production environment

config/abilities/provider_any.rb, test/unit/abilities/provider_any_test.rb
This PR updates how we grant the permission to `:show AlertRelatedEvent`s. Right now, any provider on an account has this permission, even though they might not have permissions for a service the alert refers to. With this PR, we're adding a check on service level to prevent the issue reported on the linked ticket. 
fixes [THREESCALE-6318](https://issues.redhat.com/browse/THREESCALE-6318)
Verification steps copied from the linked ticket:
1) As Admin user, create a Product i.e. Test API, an application and application plan. Set a limit of 2 requests per minute.
2) Create a member i.e “Tom” user with the following rights:
```
Accounts – Applications
Analytics
Integration & Application Plans …
```
=> Prevent alerts to be sent to users who don't have access to the related service

openshift/system/Dockerfile, openshift/system/contrib/scl_enable
Applying https://github.com/3scale/porta/pull/3130 to 2.13 stable.
Doing this instead of cherry-picking as it's less error-prone. Otherwise, we'd need to cherry-pick also https://github.com/3scale/porta/commit/363fa0621ee2516d66f76f5a69f196d61f4bc34a but it adds other changes that we are not interested in.
Although `openshift/system/Dockerfile` is not used for downstream builds, but in order to avoid confusion we are not applying any changes to it (like jemalloc library) even for upstream.
=> Add required Git SCL

openshift/system/Dockerfile
A follow-up for https://github.com/3scale/porta/pull/3130 that does the following:
- sets the `GIT_SCL` environment variable value
- installs GIT_SCL package
So that upstream builds also work.
=> Add GIT_SCL environment variable to Dockerfile

openshift/system/Dockerfile
The upstream container builds started failing in Quay recently, because PostgreSQL 10 was removed from the [RPM](https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm) that is specified in the [Dockerfile](https://github.com/3scale/porta/blob/b767f57ff5fecc6467677daee5b240a5fadc3ea8/openshift/system/Dockerfile#L24).
PostgreSQL 10 is not supported anymore, and the version that is currently supported with 3scale is PostgreSQL 13 (see [Supported Configurations](https://access.redhat.com/articles/2798521)).
=> Upgrade PostgreSQL to version 13 in Dockerfile

app/lib/logic/rolling_updates.rb, app/models/access_token.rb, config/docker/rolling_updates.yml, config/examples/rolling_updates.yml, openshift/system/config/rolling_updates.yml, test/models/access_token_test.rb, test/unit/logic/rolling_updates_test.rb
This removes the rolling update for the CMS API and makes it public for everyone. This is one of the tasks required to release the tech preview.
[THREESCALE-8990](https://issues.redhat.com/browse/THREESCALE-8990)
In the provider portal:
1. Account Settings -> Personal -> Tokens
2. Create or edit a token
3. The check button for the `Developer portal` scope must appear.
4. When `Developer portal` or `Account` tokens are enabled, the CMS API must accept the requests. It must deny the requests otherwise.
=> THREESCALE-8990: CMS access token scope: make  public

config/docker/thinking_sphinx.yml
Updating the `thinking_sphinx.yml` configuration, by:
- organize the different settings according to what they configure (thinking sphinx, searchd, etc.)
- remove the environments `development`, `test`, `preview` that are not needed in the container image.
- add `batch_size` configuration. It is required for reindexing in SaaS, as with the default value `1000` reindexing with `rake ts:rt:index` fails with the following error:
```
ThinkingSphinx::QueryLengthError: The supplied SphinxQL statement is 10266420 characters long. The maximum allowed length is 8388603.
```
Probably that's because of indexing CMS contents that can be quite long.
No JIRA, that's part of SaaS migration activity.
- …
=> Update Thinking Sphinx configuration file: add batch_size

app/javascript/src/Stats/lib/application_details.jsx, app/lib/stats/views/usage.rb, spec/javascripts/Stats/lib/application_details.spec.ts, spec/javascripts/Stats/lib/applications_table.spec.ts, test/integration/stats/clients_test.rb, test/unit/stats/views/usage_test.rb
This PR fixes a broken link to Applications listed on the "Top Applications" table. This table may be found in `/services/:service_id/stats/usage/top_applications` or by navigating to `Products > Analytics > Top Applications`.
The old broken link "/apiconfig/services/:service_id/applications/:application_id" was replaced by "/p/admin/applications/:application_id".
[THREESCALE-8100](https://issues.redhat.com/browse/THREESCALE-8100)
Navigate to the Top Application view;
Check that the URL to Applications works correctly;
About testing:
1. The "Top Applications" table only appears if there are at least 2 Applications to be shown;
2. Setting the chart to …
=> Fix link on Top Applications table

app/javascript/src/Common/components/SelectWithModal.tsx
Tiny improvement. Since `onMount` does not really manage anything "UI relevant", the component does not need to render when it changes its value.
By using a ref instead of a state variable the component won't be rendered twice.
Check number of renders in the following images. These are the output of a `console.count` added in the component's body, so every time it is rendered it adds 1.
Before:
After:
=> Prevent initial re-render in React component

.circleci/config.yml
Remove unused ssh key from CircleCI config
=> CircleCI: Remove 3scale-ninjabot key

app/controllers/provider/admin/cms/templates_controller.rb, app/models/cms/base_page.rb, app/models/cms/page.rb
In the templates controller for the UI, `assign_attributes` was being called with `without_protection: true` to bypass the strong parameters protection. I removed that option and unified the mass_assignment whitelist in `CMS::Page`.
This is part of [THREESCALE-8991](https://issues.redhat.com/browse/THREESCALE-8991)
Nothing should change in the user experience.
=> CMS: Enforce params security for templates

app/views/provider/admin/account/payment_gateways/braintree_blue/edit.html.slim, features/old/providers/wizard_upgrade_plan.feature
* It updates the styles used for hosted fields with actual formtastic styles, so that all fields in the form look the same.
* It also disables the credit card fields if Braintree fails (the fields won't be editable anyway).
* And finally disables the submit button until all required fields are filled.
Before:
After:
Before:
After:
=> 💄 Improve Braintree edit page's UX 🧠 🌴

app/javascript/src/Types/globals.d.ts, app/javascript/src/utilities/flash.ts, spec/javascripts/utilities/flash.spec.ts
Right now we have `flash` defined as part as `window.$` but also we export a module from `utilities/`. This PR removes the global type and allow to use flash only from that module. From now on, calling `$.flash` will throw a TS error.
=> Encapsulate `flash` available in React

app/controllers/api/application_plans_controller.rb, app/controllers/api/plans_base_controller.rb, app/controllers/api/service_plans_controller.rb, app/presenters/api/application_plans_presenter.rb, app/presenters/api/service_plans_presenter.rb, app/presenters/buyers/account_plans_presenter.rb, app/presenters/plans_base_presenter.rb, test/unit/presenters/plan_presenters_test.rb
From time to time `test/unit/presenters/plan_presenters_test.rb:26` fails with the following error:
```
--- expected
+++ actual
@@ -1 +1 @@
-[#<ApplicationPlan id: 55, issuer_id: 20, name: "plan100", rights: nil, full_legal: nil, cost_per_month: 0.0, trial_period_days: nil, created_at: "2023-01-30 11:19:48", updated_at: "2023-01-30 11:19:48", position: 4, state: "hidden", cancellation_period: 0, cost_aggregation_rule: "sum", setup_fee: 0.0, master: false, original_id: 0, type: "ApplicationPlan", issuer_type: "Service", description: nil, approval_required: false, tenant_id: 15, system_name: "plan191", partner_id: nil, contracts_count: 0>, #<ApplicationPlan id: 56, issuer_id: 20, name: "plan101", rights: nil, full_legal: nil, cost_per_month: 0.0, …
```
=> Fix random failure... hopefully

config/examples/core.yml, config/examples/sandbox_proxy.yml
I think we mostly run a real backend when developing. So disable `fake_server`.
and because probably `*.localhost` already resolves to localhost in our
setups, much better to have endpoints use that instead of a domain
that doesn't resolve to what we need.
=> better backend defaults

features/step_definitions/applications/applications_steps.rb, features/step_definitions/buyer_steps.rb, features/step_definitions/buyers_management/account_steps.rb, features/step_definitions/developer_portal/admin/account/payment_details_steps.rb
By removing an unused step definition, I noticed 2 scenarios failed but I could not figure out why. It turns out these particular scenarios rely on 2 buyers created for 2 providers, but the way our steps find those buyers is by `Account.find_by_org_name` so for any X buyers with the same name, only one of them will be found, regardless of the provider they belong too.
This is precisely what happens in commit 30b0c970ad813f9a81e77a7a9f74456d91a478fd, the 2nd buyer is supposed to be approved but it isn't. Instead, the first `buyer_one` is approved twice, making the sign in fail.
The second commit makes sure all buyers are fetched from the provider they belong to.
=> 🧪 🥒 Make some cucumbers more robust

features/developer_portal/admin/account/invoices.feature, features/step_definitions/buyer_steps.rb, features/step_definitions/developer_portal/admin/account/invoices_steps.rb, features/step_definitions/time_steps.rb
The mails should not really be tested in this feature but it's better than not test them at all.
2 problems with this scenario:
* Provider mode is `postpaid` and the first month won't be charged, therefore it needs to wait 2 months not 1.
* The emails are not sent right at the start of the month, instead, the billing notice is sent on the 3rd or so day, then every 3 days there will be a charging attempt with its corresponding "charge failed" notification.
Solution:
* Fix the time at beginning of the month
* Fix billing mode as postpaid (even though it is the default) to make it clear 2 months must pass
=> 🥒 Fix failing cuke in CI

app/views/api/application_plans/index.html.slim
[THREESCALE-8778[UI Strings] Description in Application plan introduction on the application plan list is incorrect](https://issues.redhat.com/browse/THREESCALE-8778)
1. Go to Applications > Applications Plans
2. Confirm the microcopy matches the strings. 
Snapshot: 
=> THREESCALE-8778[UI Strings] Description in Application plan introduction on the application plan list is incorrect

.circleci/config.yml
`lint` does not depends on assets compilation, only on `yarn install`.
On the other hand, assets compilation is already run by mysql_build. This is a relatively heavy process and we can save time by running it only once.
**mysql_build**
**javascript_build**
=> 👷 Separate lint from webpack compilation

app/controllers/provider/admin/cms/templates_controller.rb, app/models/cms/layout.rb, test/integration/provider/admin/cms/layouts_test.rb
Mass assignment sanitizer was set to `:strict`, only for CMS Layouts in all the project, which is strange. This produces an exception when somebody try to mass-assign parameters that are not explicitly white listed by `attr_accessible` ([app/models/cms/layout.rb](https://github.com/3scale/porta/blob/b3b774b16bb3be0c3f87cb456227df3aa1c5db2b/app/models/cms/layout.rb#L3))
This was introduced in this [commit](https://github.com/3scale/system/commit/4be79c1382fee617308a3f37987bacb1ae81c0e9), and I'm not sure what is it for. AIUI, that commit ensures the content of the layout draft is not lost when somebody tries to send a parameter which is not in the white list. Buy why would the controller receive such parameter? and anyway, why not just ignore and …
=> CMS Layout: remove strict mass assignment protection

app/lib/system/deploy.rb, test/unit/lib/system/deploy_test.rb
Removes the environment variables and the Rails version from the information exposed by the `/deploy` on master account.
-none-
Go to `{MASTER_URL}/deploy` and make sure that the environment variables and the Rails version are not seen. Example response should be:
```
{"revision":"alpha","release":"alpha","deployed_at":"2023-02-09T12:03:44+01:00"}
```
=> Do not expose environment variables at /deploy endpoint

app/lib/system/deploy.rb, test/unit/lib/system/deploy_test.rb
Ignore what's set in the `.deploy_info` for SaaS, as in the container image the version will be set to `alpha`
-none-
Start porta with `onpremises: false` in `settings.yml`.
Verify that the version that is shown in the admin portal footer is 2.x
=> Report 2.x version for SaaS, despite what's set in .deploy_info

openshift/system/Dockerfile, openshift/system/Makefile, openshift/system/docker-compose.yml, openshift/system/entrypoint.sh
Removes a bunch of `declare -x` statements in the logs when the pods starts.
e.g.
```
declare -x THREESCALE_SANDBOX_PROXY_OPENSSL_VERIFY_MODE="VERIFY_NONE"
declare -x THREESCALE_SUPERDOMAIN="3scale.xxxxxx"
declare -x TZ=":/etc/localtime"
declare -x USER_EMAIL=""
declare -x USER_LOGIN="admin"
```
See the notes below.
https://issues.redhat.com/browse/THREESCALE-8902
Not sure if it fixes the issue completely, but certainly fixes the issue in [this comment](https://issues.redhat.com/browse/THREESCALE-8902?focusedCommentId=21606681&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21606681)
Build the container image and start the container with the default entrypoint. …
=> THREESCALE-8902: Remove BUNDLER_ENV

SETUP_ORACLE.md
As pointed out in [here](https://github.com/3scale/porta/pull/3195#issuecomment-1429499513), Porta currently supports Oracle 19c but we have links related with Oracle 21c in the Docs.
This PR updates those links.
none
=> Fix Oracle version on Docs

config/docker/thinking_sphinx.yml, lib/tasks/openshift.rake, openshift/system/Dockerfile
To allow decoupling of Sphinx and porta container requirements, stop bundling Sphinx with Porta.
But also generate Sphinx configuration file to be easily available when building the searchd standalone image.
part of THREESCALE-8729
=> free the Sphinx 1/2

app/lib/pdf/finance/invoice_report_data.rb, test/unit/pdf/finance/invoice_report_data_test.rb
Fix an issue with missing logo on invoices in **SaaS**.
Fixes https://issues.redhat.com/browse/THREESCALE-9162
1. Add a Logo in Audience > Developer portal > Logo
2. Create an invoice for an account
3. Generate a PDF invoice
4. Check that the logo appears on the invoice PDF
This is a regression caused by https://github.com/3scale/porta/pull/3067 that fixed invoice logo when using file system for paperclip.
This only happens in SaaS, because it's an issue specific to Ruby 2.4.
The `URI.open` call fails with the following error:
```
Failed to retrieve logo: private method `open' called for URI:Module
```
The reason is that in Ruby 2.4 this method is not …
=> THREESCALE-9162: Fix missing logo on invoices in SaaS

config/docker/unicorn.rb, config/unicorn/development.rb
k8s/Openshift sends SIGTERM to containers when terminating them.
This installs same handler for SIGTERM as it is set for SIGQUIT to
make unicorn terminate gracefully instead of killing workers with
active connections.
=> graceful unicorn termination in container

app/services/finance/stripe_charge_service.rb, test/unit/services/finance/charging_service_test.rb, test/unit/services/finance/stripe_charge_service_test.rb
Adds a description of the Payment Intent - this is not visible in the 3scale UI / API, but will be seen in Stripe dashboard.
It is required for Stripe account operating in India to accept international payments according to https://stripe.com/docs/india-accept-international-payments#valid-charges
Fixes [THREESCALE-9323: Add description to Payment Intent for transactions via Stripe payment gateway](https://issues.redhat.com/browse/THREESCALE-9323)
With Stripe configured in the admin portal:
- Create an invoice on an account
- Issue and charge the invoice
- Verify that the payment has succeeded
- Verify in Stripe dashboard that the payment intent has a description
=> THREESCALE-9323: Add stripe payment description

config/webpack/development.js
I will do this small change to React and the browser will refresh automatically...
But after this PR:
=> 🧑‍💻 Ignore `typescript` errors from tests during development

.tool-versions.sample, fedora-manual-setup.md, osx-manual-setup.md
* macOS requires `mysql` and `postgresql` as dependencies.
* macOS requires a flag in order to run mysql in docker
* rewording
=> 📝 Update manual installation

app/models/cms/builtin.rb, app/models/cms/layout.rb, app/models/cms/page.rb, app/models/cms/partial.rb, app/representers/cms/file_representer.rb, app/representers/cms/layout_representer.rb, app/representers/cms/page_representer.rb, app/representers/cms/partial_representer.rb, app/representers/cms/portlet_representer.rb, app/representers/cms/section_representer.rb, spec/acceptance/api/cms_file_spec.rb, spec/acceptance/api/cms_layout_spec.rb, spec/acceptance/api/cms_page_spec.rb, spec/acceptance/api/cms_partial_spec.rb, spec/acceptance/api/cms_section_spec.rb, spec/api_helper.rb, spec/support/api/context.rb, test/integration/cms/api/sections_test.rb
This PR updates the JSON format responses for the CMS API so that they follow the same structure and return the same data as the XML responses, updated recently in https://github.com/3scale/porta/pull/3193.
Fixes [THREESCALE-8993](https://issues.redhat.com/browse/THREESCALE-8993).
Call the following endpoints to check they match the responses in [this document](https://docs.google.com/document/d/14Lpu5T-ktDVUNl9SINtd7WRdew1x0f5qDzFngThZyV8/edit):
```
GET /admin/api/cms/sections/:section_id/files.json
GET /admin/api/cms/sections.json
GET /admin/api/cms/sections/:id.json
GET /admin/api/cms/files.json
GET /admin/api/cms/files/:id.json
GET /admin/api/cms/templates.json
GET …
```
=> CMS API: Implement API Contract for JSON responses

app/lib/pdf/data.rb, app/lib/pdf/finance/invoice_generator.rb, test/test_helpers/env.rb, test/unit/pdf/data_test.rb, test/unit/pdf/finance/invoice_generator_test.rb, test/unit/pdf/report_test.rb
We had some unnecessary escaping in report PDFs.
Also Invoices with long addresses caused `Address` and `Country` words to wrap (see screenshot vs attached PDF).
[fixed invoice.pdf](https://github.com/3scale/porta/files/10935133/fixed.invoice.pdf)
=> fixes to PDF rendering

app/javascript/packs/active_docs.ts, app/javascript/packs/service_active_docs.ts, app/javascript/src/ActiveDocs/OAS3Autocomplete.ts, app/javascript/src/ActiveDocs/swagger-ui-3-provider-patch.scss, spec/javascripts/.eslintrc, spec/javascripts/ActiveDocs/OAS3Autocomplete.spec.ts
Fix the issue where the response body of the API calls made from Active Docs (OpenAPI spec v3).
For JSON responses it was adding `"servers"` object, and for XML responses it was also "transforming" it to JSON, which was actually wrapping the response in quotes `"<element>...</element>"`
https://issues.redhat.com/browse/THREESCALE-8612
- Go to `/admin/api_docs/services` in the admin portal
- Create a new spec from [echo-api-3.0.json](https://raw.githubusercontent.com/3scale/porta/3017562449d3275840cae6afe338a01c1dcca899/public/echo-api-3.0.json) - do **not** link it to any service (product).
- Make a test call with _Try it out_ feature
- Verify that there is in "servers" added in the JSON …
=> THREESCALE-8612: Do not manipulate the response of the API calls made from Active Docs

app/helpers/payment_details_helper.rb, app/javascript/packs/stripe_form.ts, app/javascript/src/PaymentGateways/stripe/StripeElementsForm.tsx, app/javascript/src/PaymentGateways/stripe/types.ts, spec/javascripts/PaymentGateways/stripe/StripeElementsForm.spec.tsx, spec/javascripts/PaymentGateways/stripe/StripeElementsProvider.spec.tsx, spec/javascripts/PaymentGateways/stripe/StripeFormWrapper.spec.tsx, spec/javascripts/__mocks__/@stripe/react-stripe-js.js, spec/javascripts/__mocks__/@stripe/stripe-js.js, test/helpers/payment_details_helper_test.rb
This is a proposal for https://issues.redhat.com/browse/THREESCALE-8626, see also https://github.com/3scale/porta/pull/3236
It uses the existing Billing address' name of the account to register the credit card.
In the Braintree form we already ask for first and last name. In the Stripe for we only ask for "Contact / Company", whatever that means. The fun part is that internally we store it as `billing_address_name`😓. 
So for this proposal to work, we need to replace the existing field with a first and last name ones and then use it when registering the card.
Ideally, we could merge this 2 weird forms (credit card and Billing address) into 1, same as Braintree.
TODO:
=> 🦓 Use billing address name when registering a CC

app/lib/pdf/styles/base.rb
now it should only find fonts once for the Ruby process lifetime as
well find the font on a mac
=> more robust font finding

doc/licenses/licenses.xml, package.json, yarn.lock
To put it delicately, `node-sass` is a PITA (and not the bread kind).
It was added some time ago because of a weird error coming from `webpacker` (see https://github.com/3scale/porta/pull/262/commits/0c156bcd6a44b9cac751648ec6c62e3eaf7e6652)
The message is something like this:
```
[....]
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jgallaso/projects/3scale/porta/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command …
```
=> ➖ Remove `node-sass`

app/controllers/admin/api/cms/base_controller.rb, app/controllers/admin/api/cms/files_controller.rb, app/controllers/admin/api/cms/sections_controller.rb, app/controllers/admin/api/cms/templates_controller.rb, app/models/cms/builtin.rb, app/models/cms/file.rb, app/models/cms/layout.rb, app/models/cms/page.rb, app/models/cms/partial.rb, app/models/cms/section.rb, config/routes.rb, doc/active_docs/Developer Portal API (Tech Preview).json, spec/acceptance/api/cms_file_spec.rb, spec/acceptance/api/cms_layout_spec.rb, spec/acceptance/api/cms_page_spec.rb, spec/acceptance/api/cms_partial_spec.rb, spec/acceptance/api/cms_section_spec.rb, spec/acceptance/api/cms_template_spec.rb, test/functional/admin/api/cms/templates_controller_test.rb, test/integration/cms/api/files_test.rb, test/integration/cms/api/sections_test.rb, test/integration/cms/api/templates_test.rb, test/integration/cms/base_controller_test.rb
This PR removes support for `XML` format requests from all CMS endpoints. It also makes `JSON` the standard request format for the CMS API. 
[THREESCALE-9433](https://issues.redhat.com/browse/THREESCALE-9433)
The following endpoints should only respond to `JSON` requests. Any other format should return a `406` status.
| Verb | Endpoint | Controller#Action |
| ------- | ------- | ------- |
|GET|/admin/api/cms/sections/:section_id/files|admin/api/cms/files#index|
|GET|/admin/api/cms/sections|admin/api/cms/sections#index|
|POST|/admin/api/cms/sections|admin/api/cms/sections#create|
|GET|/admin/api/cms/sections/new|admin/api/cms/sections#new| …
=> CMS API:  Drop support for XML requests

test/integration/audited_hacks_async_test.rb
Oracle driver does some extra queries for whatever evil reason it has and test failed. This should fix that.
=> fix oracle test

app/presenters/plans_base_presenter.rb, features/step_definitions/plans_steps.rb, test/unit/presenters/plan_presenters_test.rb, test/unit/services/finance/stripe_charge_service_test.rb
What the title says
-
Run postgres build in CircleCI
Fixes two issues:
1. Default `friendly_id` on the invoice is set differently in PostgreSQL and MySQL. This is fixed by https://github.com/3scale/porta/pull/3273/commits/eeddb7db47a55235346663030329c9f0193a8388
For some reason, when using MySQL, [calling the stored procedure](https://github.com/3scale/porta/blob/bd064fd/app/services/invoice_friendly_id_service.rb#L51) that sets the correct friendly ID doesn't have any effect, while when using PostgreSQL it does.
2. Another issue was with the application plans ordering.
The issue was that a specific order was expected from the list of application plans, …
=> Fix postgres tests

package.json, yarn.lock
Fixes:
```
$ yarn check
...
error "@stripe/react-stripe-js#@stripe/stripe-js@^1.44.1" doesn't satisfy found match of "@stripe/stripe-js@1.37.0"
...
```
=> ⬆️ Bump `stripe-js`

app/models/cms/page.rb, app/models/cms/section.rb, test/integration/cms/api/sections_test.rb, test/unit/cms/page_test.rb, test/unit/cms/section_test.rb
This is a simpler approach to https://github.com/3scale/porta/pull/3163.
In that PR I added validations to all CMS models so `system_name`:
1. Is always present.
2. Meets the format `%r{\A\w[\w\-/_]+\z}`.
The problem is that there are some sections and pages in the DB that doesn't meet the format, so adding validations would require a backfill migration to fix those two tables.
In this PR, I applied the minimal changes possible to ensure those two conditions above are meet **for all new records**, but it doesn't add the validations, so the existing records not meeting the conditions are allowed in order to avoid breaking anything.
Part of [THREESCALE-8991](https://issues.redhat.com/browse/THREESCALE-8991) …
=> CMS: Unify system names

test/events/service_contracts/service_contract_cancellation_event_test.rb, test/unit/liquid/drops/account_drop_test.rb
When sending emails from the bulk operations emails can be sent if body and subject is empty
**DEPRECATED**: Use assert_nil if expecting nil
https://issues.redhat.com/browse/THREESCALE-8184
=> THREESCALE-8184  Use assert_nil if expecting nil

app/javascript/src/Policies/styles/policies.scss, package.json, yarn.lock
Recently the following warning shows up when running webpack:
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($line-height-computed, 2) or calc($line-height-computed / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
```
To remove it, upgrade `bootstrap-sass`.
On the other hand, we're importing **the whole** library to style only a couple components in Integration / Policies. Ideally we should remove bootstrap-sass altogether and use PF4 components. In the meantime, the imported scss has been removed to the minimum.
```
master    8.7M      public/packs/js/policies-df14e7c216a288d657bb.js
fix       8.6M      public/packs/js/policies-8007597a59460b826fb8.js
```
**NOTE**
After …
=> Fix `bootstrap-sass` warning

.tool-versions.sample, Dockerfile, fedora-manual-setup.md, openshift/system/Dockerfile, osx-manual-setup.md, package.json
This belongs a series of upgrades towards [shakapacker](https://github.com/shakacode/shakapacker) (AKA webpacker 6)
It also add `engines` to the package.json, this will render an error when node doesn't meet the specified version.
[THREESCALE-7331: Upgrade to NodeJS 14 for ubi8](https://issues.redhat.com/browse/THREESCALE-7331)
TODO:
**Verification**:
Update your `.tool-versions` with the new version and/or install the new version, then run `yarn`.
=> ⬆️ Node.js 14

app/lib/three_scale/socket.rb, db/seeds.rb
When doing db:reset usually backend is down. If local configuration
doesn't use `fake_server`, then operation will fail at `db:seed`.
And since recently our example config does disable `fake_server`.
This change makes sure we mock it regardless of configuration when
we detect that backend is not available. So if anybody has a use case
where backend is indeed available it will work as expected. But not fail
for others.
=> db:seed succeed if backend is unavailable

app/javascript/src/ActiveDocs/OAS3Autocomplete.ts, spec/javascripts/ActiveDocs/OAS3Autocomplete.spec.ts
The endpoint urls in the Developer portal docs were not being processed, due to a regression caused by https://github.com/3scale/porta/pull/3246. This fixes it.
[THREESCALE-9498](https://issues.redhat.com/browse/THREESCALE-9498)
Just open http://provider.3scale.localhost:3000/docs and check the "Servers" dropdown is set to apicast.
**Notes for the reviewer**
The problem is at:
https://github.com/3scale/porta/blob/81f9b67687d137206436f5c6dba1a149528ffd19/app/javascript/src/ActiveDocs/OAS3Autocomplete.ts#L135-L137
Here, `specUrl` comes as a relative path but `response.url` is absolute, so it's a false negative and `autocompleteOAS3` doesn't get called when it should. The value ultimately comes …
=> Fix api docs endpoints in the developer portal

.circleci/config.yml
Fixes the following deprecation warning:
```
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local deployment 'true'`, and stop using this flag
```
=> 👷 Fixes bundle --deployment deprecation in in ci

app/javascript/packs/navigation.scss, app/javascript/packs/provider.ts, app/javascript/src/Navigation/renderContextSelector.ts, app/javascript/src/Navigation/renderVerticalNav.ts, app/javascript/src/Navigation/setupHeaderTools.ts, app/javascript/src/QuickStarts/renderQuickStarts.ts, app/views/layouts/provider.html.slim, app/views/shared/_api_selector.html.slim, app/views/shared/provider/_header.html.slim, app/views/shared/provider/_quickstarts_container.html.slim, app/views/shared/provider/navigation/_vertical_nav.html.slim
The idea is to reduce the amount of entry points. The layout "provider" renders the header, sidebar and quickstarts container so their individual packs can be combined into one. Results:
Before:
```
Asset                                     Size          Chunks
js/api_selector-e9b9632898d3b33b014c.js   592 KiB       3   [emitted] [immutable]  [big]  api_selector
js/provider-d03ab4a73e9061267dd4.js       828 KiB       32  [emitted] [immutable]  [big]  provider
js/quickstarts-f5e48672621375ee7345.js    4.83 MiB      34  [emitted] [immutable]  [big]  quickstarts
js/navigation-6abd334a13fe068b1a26.js     53.8 KiB      21  [emitted] [immutable]         navigation
js/vertical_nav-1c05e2b641ba4d1c1f28.js   953 KiB       43  [emitted] [immutable]  [big]  vertical_nav
~ 7.26 MiB
```
After:
``` …
```
=> ♻️ Combine all packs loaded in layout provider

.circleci/config.yml, lib/tasks/assets.rake
It's important to set the correct env vars when compiling assets for tests, so here's a task to be run before running tests.
=> Task for compiling assets for tests

app/javascript/src/ActiveDocs/OAS3Autocomplete.ts, app/javascript/src/ActiveDocs/ThreeScaleApiDocs.ts, app/javascript/src/Types/SwaggerTypes.ts, app/javascript/src/Types/swagger.d.ts, package.json, spec/javascripts/ActiveDocs/OAS3Autocomplete.spec.ts, spec/javascripts/ActiveDocs/ThreeScaleApiDocs.spec.ts, spec/javascripts/__mocks__/swagger-client/es/execute/index.js, spec/javascripts/__mocks__/swagger-ui.js
This fixes the serialization issue with the `report` endpoint of the Service Management API, initially reported in this comment: https://github.com/3scale/porta/pull/3103#issuecomment-1413955116 (item 2).
Actually, it serializes differently in different cases:
- just using the single transaction element with the value from example:
```
'service_token=token&service_id=123&transactions[user_key]=example&transactions[usage][hits]=1'
```
- the default element plus another element:
```
'service_token=token&service_id=123&transactions[user_key]=example&transactions[usage][hits]=1&transactions=%7B%0A%20%20%22user_key%22%3A%20%22example%22%2C%0A%20%20%22usage%22%3A%20%7B%0A%20%20%20%20%22hits%22%3A%201%0A%20%20%7D%0A%7D'
```
- with manual changes in both elements:
``` …
```
=> Serialize Service Mgmt API's report endpoint body correctly

Gemfile, lib/tasks/licenses.rake, openshift/system/Dockerfile
license_finder fails due to https://github.com/rubygems/rubygems/issues/6626
So easiest solution is to disable it. As it doesn't appear useful anyway. If issue is fixed upstream, then we may re-enable or may not.
The Gemfile change is to enable using bundler and the rake task in production builds where things work due to the different way of distributing gems.
=> Fix licenses report

.github/workflows/container-image-buildah.yml, .github/workflows/container-image-buildx.yml, .github/workflows/container-image.yml, README.md
A workflow to replace Quay as builder of our images, still push to Quay. Keeping the `buildx` workflow for debugging purposes in case of troubles with buildah.
This works, tested with
https://github.com/3scale/porta/actions/runs/4745576359/jobs/8428089503
because it needed the licenses report fix
=> more options to build images + buildah

app/lib/three_scale/swagger/specification.rb, test/unit/three_scale/swagger/specification_test.rb
Do not add `schemes` field fo OpenAPI v3 spec.
[THREESCALE-9010](https://issues.redhat.com/browse/THREESCALE-9010): When downloading the Active Doc 3scale adds "schemes":["http"]" at the end
- Go to the preview page for an OpenAPI specification (e.g. http://provider-admin.3scale.localhost:3000/apiconfig/services/2/api_docs/1/preview)
- Click on the URL of the spec (e.g. http://provider-admin.3scale.localhost:3000/admin/api_docs/services/1.json)
- Verify that there is no `schemes` field.
The feature was initially implemented by https://github.com/3scale/system/pull/5548
But OpenAPI v3 was added later, and this is not relevant for v3, as `schemes` field is …
=> THREESCALE-9010: Do not add 'schemes' to OpenAPI v3 spec

Gemfile, Gemfile.lock, app/lib/pdf/data.rb, app/lib/pdf/report.rb, config/initializers/prawn.rb, fedora-manual-setup.md, openshift/system/Dockerfile, osx-manual-setup.md, test/fixtures/report_mocks.yml, test/unit/pdf/data_test.rb, test/unit/pdf/report_test.rb
this one is based on #3148 so should be merged after it
uploading example old and new implementation examples:
[report-simple1.example.com-300.pdf](https://github.com/3scale/porta/files/10449969/report-simple1.example.com-300.pdf) - new empty daily
[report-simple1.example.com-294.pdf](https://github.com/3scale/porta/files/10449830/report-simple1.example.com-294.pdf) - old empty daily
[report-simple1.example.com-276.pdf](https://github.com/3scale/porta/files/10449837/report-simple1.example.com-276.pdf) - new big weekly
[report-simple1.example.com-12.pdf](https://github.com/3scale/porta/files/10449838/report-simple1.example.com-12.pdf) - old big weekly
=> [THREESCALE-8769] replace gruff with svg-graph2

app/controllers/master/api/providers_controller.rb, config/routes.rb, test/factories/plan.rb, test/integration/master/api/providers_controller_integration_test.rb
In SaaS there is a special logic for upgrading tenant accounts (includes not only the application plan change, but also applying switches for the different features).
This is currently only available through the multitenant UI.
This PR adds an endpoint `PUT /master/api/providers/{id}/plan_upgrade.xml` (with `plan_id` body param specifying the ID of the new plan) that allows upgrading the tenant through API.
This will be useful in SaaS staging environment, where a new provider can be created and upgraded to the corresponding plan, in order to enable all features (by default only a limited subset of features is enabled).
=> Add an endpoint for upgrading a tenant in SaaS

app/models/cms/template.rb
Fix `by_type` filter for CMS::Template that was broken in PostgreSQL.
-none-
Make sure the test passes.
This was caught by tests in CircleCI:
```
Error:
CMS::Api::TemplatesTest#test_index_filters_by_type:
TypeError: can't cast Class
app/lib/three_scale/api/responder.rb:80:in `serializable'
app/lib/three_scale/api/responder.rb:6:in `api_behavior'
app/controllers/admin/api/cms/templates_controller.rb:38:in `index'
app/lib/api_authentication/by_access_token.rb:162:in `enforce'
app/lib/api_authentication/by_access_token.rb:112:in `enforce_access_token_permission'
app/controllers/admin/api/base_controller.rb:42:in `block in notification_center' …
```
=> Stringify the name of the class for the by_type query for CMS::Template

app/javascript/src/ActiveDocs/components/ApiJsonSpecInput.tsx, app/javascript/src/ActiveDocs/components/NameInput.tsx, app/javascript/src/BackendApis/components/BackendSelect.tsx, app/javascript/src/Common/components/CompactListCard.tsx, app/javascript/src/Common/components/MicroPagination.tsx, app/javascript/src/Common/components/NoMatchFound.tsx, app/javascript/src/Common/components/TableModal.tsx, app/javascript/src/Common/components/ToolbarSearch.tsx, app/javascript/src/Dashboard/components/BackendsWidget.tsx, app/javascript/src/LoginPage/loginForms/AuthenticationProviders.tsx, app/javascript/src/LoginPage/loginForms/FlashMessages.tsx, app/javascript/src/Metrics/components/MetricsTable.tsx, app/javascript/src/Policies/components/HeaderButton.tsx, spec/javascripts/Metrics/components/MetricsTable.spec.tsx
Import icons individually vs. import the whole module.
Before:
After:
=> ⚡ Remove react-icons chunk

app/javascript/packs/codemirror.scss
This PR deals with:
`Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`
As recommended by sass, now our webpack-handled-css files will be using `calc()` method for divisions, keeping webpack happy and green 🍏. 
Check that when running webpacker there aren't any warnings.
=> 💄➗ Use calc() for math operations in scss files

config/thinking_sphinx.yml, openshift/system/config/thinking_sphinx.yml
Need more investigation how it works and how exactly to apply it with our custom background jobs indexing (if we keep that to begin with) but the basic idea is described in pat/thinking-sphinx#1192
So basically this is all to make the PR work. The only thing needed is to wipe all indices of sunning sphinx though. Which should happen automatically at present. Except on SaaS.
=> sphinx clean indices

app/indices/backend_api_index.rb, app/indices/service_index.rb, test/unit/backend_api/search_test.rb, test/unit/service/search_test.rb
Adds `system_name` to index for Product and Backend API.
Fixes [THREESCALE-8562: Products and backend can't be found by searching for system name](https://issues.redhat.com/browse/THREESCALE-8562)
- Create a Product with system name which is different from the name.
- Search by the system name.
- Verify that the product appears in search results.
Applying this change requires rebuilding the index, so it should only be merged when we're ready to do that.
=> THREESCALE-8562: Search products and backend APIs by system name

app/javascript/packs/load_stripe.ts, features/asset_host/asset_host.feature, lib/developer_portal/app/views/developer_portal/main_layout.html.liquid, lib/developer_portal/lib/liquid/filters/rails_helpers.rb
This snippet from dev portal's main layout:
```liquid
{% if provider.payment_gateway_type == :stripe %}
{{ 'load_stripe.js' | javascript_include_tag }}
{% endif %}
```
doesn't do what you think. It always loads stripe, no matter the provider's settings.
Luckily for us we moved the Stripe form into React so now we can import the module directly there and don't need a pack anymore.
This removal has no impact on older dev portals and only shows the following failed request:
[THREESCALE-9590: Don't include Stripe js in Dev portal](https://issues.redhat.com/browse/THREESCALE-9590)
=> 🦓💣 Remove `load_stripe.js`

app/controllers/admin/api/cms/templates_controller.rb, doc/active_docs/cms_api.json, test/integration/cms/api/templates_test.rb
In order to enable a way to export all templates in one request, QE asked for a new parameter `:full` to add the `:draft` and `:published` fields to every template in the response.
[THREESCALE-9576](https://issues.redhat.com/browse/THREESCALE-9576)
`curl --request GET --url 'http://provider-admin.3scale.localhost:3000//admin/api/cms/templates?access_token=secret&full=true'`
=> THREESCALE-9576: Add parameter "full" to endpoint GET templates.json

app/workers/report_traffic_worker.rb, test/workers/report_traffic_worker_test.rb
Use non-deprecated interface for reporting traffic (porta's API traffic) to backend - in order to stop spamming logging infra.
https://issues.redhat.com/browse/THREESCALE-9170
Example call:
```
ReportTrafficWorker.new.perform(2, 'hits', {}, { code: 200 })
```
Make sure deprecation warning is not shown.
Not actually related to the PR itself, but I hit this issue when trying to reproduce the behavior with the previous code.
In a local setup the requests to the backend (when using the provider key) were failing with the following error 
```
=> #<ThreeScale::Response:0x000000000caf8d48 @error_code="provider_key_invalid_or_service_missing", …
```
=> Remove deprecation warning for ReportTrafficWorker

spec/javascripts/Stats/buyer/stats_application.spec.ts
`spec/javascripts/Stats/buyer/stats_application.spec.ts` throws the following error:
```
(node:59475) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'concat' of undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59475) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59475) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, …
```
=> ✅ Fix unhandled promise in test

.github/workflows/fast-forward-branch.yml
Modify the Github Action we are using to launch a new `managed-services` build.
Now it prints a git log including all the FF'd commits. So it's easy to now which issues are part of the new build.
Launch the **Fast forward manually**  pipeline.
=> Workflow: Report changes that are part of the managed services buld

app/javascript/src/ActiveDocs/components/ApiJsonSpecInput.tsx, app/javascript/src/ActiveDocs/components/DescriptionInput.tsx, app/javascript/src/ActiveDocs/components/NameInput.tsx, app/javascript/src/ActiveDocs/components/SystemNameInput.tsx, app/javascript/src/BackendApis/components/PrivateEndpointInput.tsx, app/javascript/src/ChangePassword/components/ChangePassword.tsx, app/javascript/src/Common/components/TableModal.tsx, app/javascript/src/Common/components/UserDefinedField.tsx, app/javascript/src/EmailConfigurations/components/EmailConfigurationForm.tsx, app/javascript/src/NewApplication/components/NewApplicationForm.tsx, app/javascript/src/Users/components/FeaturesFieldset.tsx, app/javascript/src/Users/components/PermissionsForm.tsx, app/javascript/src/Users/components/ServicesFieldset.tsx, yarn.lock
The latest builds fail with the following error (one per each JS pack):
```
ERROR in ./app/javascript/packs/active_docs.ts
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: /opt/system/app/javascript/packs/active_docs.ts: Invalid Version: 70001900000
at new SemVer (/opt/system/node_modules/semver/semver.js:314:11)
at compare (/opt/system/node_modules/semver/semver.js:647:10)
at Function.lt (/opt/system/node_modules/semver/semver.js:688:10)
at PluginPass.pre (/opt/system/node_modules/@babel/plugin-transform-named-capturing-groups-regex/node_modules/@babel/helper-create-regexp-features-plugin/lib/index.js:55:44)
at transformFile (/opt/system/node_modules/@babel/core/lib/transformation/index.js:73:27)
at transformFile.next …
```
=> Bump the version of @babel/helper-create-regexp-features-plugin

package.json, yarn.lock
After upgrading patternfly, this is no longer used by webpack.
=> ➖ Remove `null-loader`

app/javascript/src/Common/components/Pagination.tsx, spec/javascripts/BackendApis/components/IndexPage.spec.tsx, spec/javascripts/Common/components/Pagination.spec.tsx, spec/javascripts/Metrics/components/MetricsTable.spec.tsx, spec/javascripts/Products/components/IndexPage.spec.tsx
[THREESCALE-9644: Fix PF pagination](https://issues.redhat.com/browse/THREESCALE-9644)
There seems to be a bug in PF's Pagination component. `page` default value is 0 and the math doesn't work, but it does when it's 1 so that's the workaround.
Mind the lack of query param `page` in the URL.
Before:
After:
=> 🦋🐛 Fix PF4 Pagination

app/assets/stylesheets/provider/_commons.scss, app/assets/stylesheets/provider/_typography.scss
Makes the `h1` title on the legacy (non-react) pages look like Patternfly headers.
=> Align header font for leagacy page headers

app/assets/stylesheets/error.scss, app/assets/stylesheets/provider/_colors.scss, app/assets/stylesheets/provider/_footer.scss, app/assets/stylesheets/provider/_print.scss, app/views/layouts/error.html.erb, app/views/provider/_footer.html.slim, app/views/provider/_footer_powered_by_part.html.slim
[THREESCALE-9640: Remove hardcoded styles in footer](https://issues.redhat.com/browse/THREESCALE-9640)
Apply Patternfly structure and classes to footer. It looks closer now now closer to the main section, have in mind that's Patternfly's default.
The error layout does not support Patternfly, therefore its footer is to remain unchanged.
=> 🦋 Implement provider footer with PF4

doc/active_docs/service_management_api.json
Just fixing a bug in the spec. There was a reference to `"$ref": "#/components/schemas/Log"` in one place, but no Log schema.
There were two occurrences initially, one was replaced with the inline schema definition (hence the schema removed), but there was one more occurrence left.
This PR fixes it.
=> Fix broken Log reference in SaaS version of Service Management API spec

app/javascript/src/ActiveDocs/swagger-ui-3-provider-patch.scss, doc/active_docs/service_management_api.json, doc/active_docs/service_management_api_on_premises.json
The JIRA `THREESCALE—9667` reports a "bug" in the Service Management API which is not actually a bug, but rather a not documented limitation for the "timestamp" value.
This PR adds the description in the API specification.
Also, while looking into this, I realized that there is an undocumented feature that allows specifying the timestamp in unix epoch, so added this to the spec description too.
=> Document the limitations of the timestamp field, and add another format

package.json, yarn.lock
[THREESCALE-9688: Remove @patternfly/patternfly dependency](https://issues.redhat.com/browse/THREESCALE-9688)
This is a dependency of quickstarts and it should not be listed as a direct dependency in our package.json. In fact quickstarts requires v4 but we list v2:
```
yarn why @patternfly/patternfly
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@patternfly/patternfly"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@patternfly/patternfly@2.40.6"
info Has been hoisted to "@patternfly/patternfly"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "16.34MB"
info Disk size with unique dependencies: "16.34MB"
info Disk size with transitive dependencies: …
```
=> ⬆️ Upgrade `@patternfly/patternfly` from v2 to v4 (quickstarts dependency)

app/controllers/buyers/service_contracts_controller.rb, app/helpers/buyers/accounts_helper.rb, app/models/service_contract.rb, app/models/service_plan.rb, app/views/buyers/service_contracts/index.html.slim, test/integration/buyers/service_contracts_controller_test.rb, test/unit/service_contract_test.rb, test/unit/service_plan_test.rb
The queries are not very efficient on the page, so it takes a long time to load the Service Subscriptions page - Audience > Accounts > Subscriptions, or `/buyers/service_contracts`.
Service Subscriptions page takes too long to load: [THREESCALE-918](https://issues.redhat.com/browse/THREESCALE-918)
Go to `/buyers/service_contracts` in the admin portal, and make sure that the loading times are reasonable (I used the staging database locally).
I used the SaaS Staging DB locally, because it is difficult to reproduce on an empty (local) DB, unless you fill the DB with a significant amount of data.
I used my test account, which has roughly 60 service …
=> THREESCALE-918: Optimize service contracts page loading

.circleci/asset_paths, .circleci/config.yml
The alpha nightly tests are failing because of two cucumbers:
https://app.circleci.com/pipelines/github/3scale/porta/24483/workflows/5b85ed13-787e-4c08-a25c-923f678b0026/jobs/275299/tests
They started failing overnight, without any change in the code, testing the same commit, etc. I wasn't able to find the cause, so I thought it could be fixed by clearing the cache.
Cache clearing in CircleCI requires changes in the config file and a PR, I think the process is too slow so I implemented this:
https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-dependency-cache
I created the `CACHE_VERSION` env. variable in CircleCI. Every time we want to clear the cache we only have to update the value for that variable.
The tests seem to be …
=> CircleCI: Allow manually clearing cache

app/lib/month.rb, app/models/invoice.rb, test/unit/invoice_test.rb, test/unit/month_test.rb
Follow-up for https://github.com/3scale/porta/pull/3073
QE detected some values that were not rejected by the validation:
1. Values such as `2023-05xxx` or `2023abc-05` were accepted and applied successfully, setting the period to May 2023.
This is because `Time.zone.local` allows this:
```
[201] pry(main)> Time.zone.local('2023', '05xxx')
=> Mon, 01 May 2023 00:00:00 UTC +00:00
[202] pry(main)> Time.zone.local('2023abc', '05')
=> Mon, 01 May 2023 00:00:00 UTC +00:00
```
I guess this is because how strings are transformed into integers under the hood.
```
[208] pry(main)> ['2023abc', '05xxx'].map(&:to_i)
=> [2023, 5]
```
The PR adds a regex match for `/^(\d{4})-(\d{2})(?:-\d{2})?$/` to avoid this.
The last non-capturing group is for the optional day, e.g. `2023-04-01`. This is to avoid …
=> Fixing some invalid values for invoice period

app/helpers/menu_helper.rb, app/javascript/src/Navigation/components/ContextSelector.scss, app/javascript/src/Navigation/components/InlineIcon.scss, app/javascript/src/Navigation/components/InlineIcon.tsx, spec/javascripts/Navigation/__snapshots__/ContextSelector.spec.tsx.snap, spec/javascripts/Navigation/components/__snapshots__/Masthead.spec.tsx.snap
[THREESCALE-9674: Cannot select context Products from other pages](https://issues.redhat.com/browse/THREESCALE-9674)
The "disability" policy in Context selector is too restrictive at the moment. Any page under the Product context would disable the "Products" option from the Context selector. Only the following options should be disabled:
* Dashboard when in dashboard
* Products when in products index
* Backend APIs when in backends index
But, **⚠️ no items will be disabled to maintain the same behaviour.**
=> Fix Context selector items

app/lib/system/error_reporting.rb, config/environments/development.rb, config/initializers/deprecation.rb
The title is self-explanatory.
I added a new tab to store which rails version will stop supporting the deprecated feature. This is how it looks at Bugsnag:
The idea was to have something to filter for, so when we want to upgrade to e.g. rails 6.1, we can filter errors by `deprecation_horizon = 6.1` and get the list quickly. But it seems our plan doesn't allow that kind of custom filters (Sad face).
=> Report deprecation warnings to Bugsnag

db/migrate/20230612105944_add_index_to_member_permissions_user_id.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
Querying member permissions for a user is a very commonly used operation, and not having an index results in the DB having to perform full table scan, causing a huge DB load.
[> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`
](https://issues.redhat.com/browse/THREESCALE-9694)
=> THREESCALE-9694: Add index to member_permissions on user_id

app/javascript/packs/inline_chart.tsx, app/javascript/src/Common/components/InlineChart.tsx, app/views/stats/_inlinechart.html.erb, spec/javascripts/Common/components/InlineChart.spec.tsx
This component is used in Product overview as well as Application overview, therefore is should be considered a Common component.
Moreover, we need to clean up module `Stats` and `InlineChart` is now completely independent of it.
=> `InlineChart` as a Common component

app/helpers/account_helper.rb, app/helpers/api/services_helper.rb, app/helpers/buttons_helper.rb, app/helpers/cinstances_helper.rb, app/helpers/finance/invoices_helper.rb, app/views/admin/api_docs/base/_menu.html.erb, app/views/admin/fields_definitions/index.html.erb, app/views/api/services/_delete.html.slim, app/views/api/services/show.html.slim, app/views/buyers/accounts/_account_plan.html.erb, app/views/buyers/accounts/_monthly_charging.html.erb, app/views/buyers/accounts/show.html.slim, app/views/buyers/applications/_api_credentials.html.erb, app/views/buyers/invoices/index.html.erb, app/views/finance/provider/invoices/index.html.erb, app/views/finance/provider/shared/_invoice_header.html.erb, app/views/finance/provider/shared/_line_items.html.erb, app/views/provider/admin/account/authentication_providers/form/_form.html.slim, app/views/provider/admin/accounts/show.html.slim, app/views/provider/admin/applications/_plan.html.erb, app/views/provider/admin/applications/_state.html.slim, app/views/provider/admin/applications/show.html.slim, app/views/provider/admin/backend_apis/forms/_delete.html.slim, app/views/provider/admin/backend_apis/metrics/edit.html.erb
In the past, we tried to apply Patternfly by adding classes like `pf-c-button` and `pf-m-link` to all buttons and links. This only helper because Patternfly stylesheet was being loaded before our legacy stylesheet, therefore the latter had priority.
Now that Patternfly is loaded last (so that it overrides legacy styles) some of these components are broken.
[THREESCALE-9734: Broken UI/layout on multiple pages - missing CSS](https://issues.redhat.com/browse/THREESCALE-9734)
This PR removes Patternfly classes from legacy components. It doesn't make sense to add them to components that should not look different, only to those that are updated.
Example Application Overview:
* Buttons and links **with** Patternfly classes:
* Buttons and links **without** them:
=> 💄 Fix [yet even more] css, this time missing legacy styles

db/migrate/20230614232715_audited_changes_medium_text.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
this is needed to enable auditing of larger fields like
`policies_config`, see #3342
```sql
MySQL [3scale_system_development]> show create table audits;
+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> bigger field for audited_changes

app/representers/member_permissions_representer.rb, spec/acceptance/api/member_permissions_spec.rb
https://github.com/3scale/porta/pull/3420 introduced an index for `member_permissions` column. That broke the API integration tests, only for Postgres, and only for CircleCI - it was not reproducible locally. Probably related to the version, running the same container image as CircleCI (`cimg/postgres:10.20`) made it possible to reproduce locally.
So, it seems that introducing an index changed the order in which the records were returned by the DB.
It's all very confusing, because in theory there is a mechanism that prevents that, in the custom responder there is an ordering done on the `id` field: https://github.com/3scale/porta/blob/379b3dc/app/lib/three_scale/api/responder.rb#L87-L89
However, it turns out that in this case this is not taken into …
=> Fix member permissions test for Postgres

db/migrate/20230621090207_change_index_for_mail_dispatch_rules_account_id_first.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
The deletion process, and some other places in the code query `mail_dispatch_rules` table by `account_id`. There is no index for it, so the DB performs full table scan for this, causing a huge DB load.
https://issues.redhat.com/browse/THREESCALE-9695
`algorithm: :concurrently` is for Postgres, the migration was otherwise blocked by `strong_migrations`
=> THREESCALE-9695: Add index for mail dispatch rules

app/helpers/vertical_nav_helper.rb, app/javascript/src/Navigation/components/NavSection.tsx, app/javascript/src/Navigation/components/VerticalNav.tsx, app/javascript/src/Navigation/types.ts, features/step_definitions/menu_steps.rb, spec/javascripts/Navigation/VerticalNav.spec.tsx, test/helpers/vertical_nav_helper_test.rb
[THREESCALE-9646: Fix vertical nav](https://issues.redhat.com/browse/THREESCALE-9646)
Patternfly 4 do not support Expandable + Grouped navigation and  items inside a section look very similar if not identical:
Instead, there is a "third level" expandable navigation.
Third level items will be collapsed by default:
When the section is active, they will be expanded and highlighted
=> 🦋 Add third level navigation

app/assets/stylesheets/provider/_colors.scss
PatternFly color palette is different from the one that was used in PF3.
Compare:
PF3: https://pf3.patternfly.org/v3/styles/color-palette/
PF4: https://www.patternfly.org/v4/guidelines/colors/#color-palette
This PR updates the colors, without changing the names of the variables.
This removes some weird artifacts, like the one observed here (different colors on the background) and introduced in [this PR](https://github.com/3scale/porta/pull/3367):
=> Update color palette after PF4 upgrade

app/assets/stylesheets/provider/_forms.scss
[THREESCALE-9750: Kebab menu items should have full width](https://issues.redhat.com/browse/THREESCALE-9750)
Before (master):
After:
=> 💄 Fix table action width

app/helpers/vertical_nav_helper.rb, app/javascript/src/Navigation/components/NavSection.tsx
Inside the vertical nav, no 2 items should share the same key. Turns out the separators are.
Error in browser console:
```
Warning: Encountered two children with the same key, `separator`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
in ul (created by Context.Consumer)
in section (created by Context.Consumer)
in li (created by Context.Consumer)
in NavExpandable (created by NavSection)
in NavSection (created by VerticalNav)
in ul (created by Context.Consumer)
in NavList (created by VerticalNav)
in nav (created by Nav)
in Nav (created by VerticalNav)
in div (created by VerticalNav)
in VerticalNav
```
=> 🐛 Fix sidebar console error

.circleci/config.yml
This is according to 
https://circleci.com/docs/rerun-failed-tests-only/
The running of unit tests is self-crafted so requires to be well tested.
=> ability to re-run only failed tests

app/controllers/admin/api/services/proxy/policies_controller.rb, app/models/proxy.rb, config/locales/en.yml, db/migrate/20230704094429_extend_policy_chain_my_sql.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb, test/integration/admin/api/services/proxy/policies_controller_test.rb, test/unit/proxy_test.rb
We need to increase the size of the `policies_config` column in the `proxies` table in MySQL. This column is now limited to 64kb and some customers are complaining because they use larger policy chains that don't fit in the column.
This affects only MySQL databases, Postgres and Oracle don't set a size limit to this colmn.
This PR includes a migration that raises a Strong Migrations error, because changing a column type on the fly is considered dangerous by the gem authors:
https://github.com/ankane/strong_migrations#changing-the-type-of-a-column
However, the safe approach they suggest would require many PRs and a column name change, which seems even more dangerous to me.
@akostadinov tried modifying the column size in a copy of the staging DB and …
=> THREESCALE-8377: Support for larger policy chains

Gemfile, Gemfile.lock, app/controllers/provider/admin/destroys_controller.rb, app/lib/csv/applications_exporter.rb, app/models/forum.rb, app/models/invoice.rb, app/presenters/dashboard/notifications_presenter.rb, config.ru, lib/developer_portal/lib/liquid/drops/pagination.rb, lib/developer_portal/lib/liquid/tags/debug.rb, lib/developer_portal/lib/liquid/template/handler.rb, test/unit/liquid/drops/authentication_strategy_test.rb, test/unit/liquid/drops/country_field_test.rb
Part of the Rails 6 upgrade (https://github.com/3scale/porta/pull/3339)
Move to 5.2 all changes that fix deprecation warnings in 6 but are also valid for 5.2
[THREESCALE-7405](https://issues.redhat.com/browse/THREESCALE-7405)
Everything should work. The tests should pass.
=> Remove deprecation warnings for Rails 6

config/application.rb, test/unit/indices/indexing_test.rb, test/unit/models_test.rb
Part of the Rails 6 upgrade (https://github.com/3scale/porta/pull/3339)
Only load those rails components we actually use, and remove any reference to others.
[THREESCALE-7405](https://issues.redhat.com/browse/THREESCALE-7405)
Everything should work. Tests should pass.
=> Don't load unused rails components

app/assets/javascripts/provider/cms/sidebar.js.coffee, app/assets/stylesheets/provider/admin/cms/_sidebar.scss, app/helpers/application_helper.rb, app/javascript/src/Common/components/SystemNamePopover.tsx, app/views/api/features/_feature.html.erb, app/views/api/metrics/_metric.html.erb, app/views/buyers/users/show.html.erb, app/views/layouts/_cms.html.erb, app/views/plans/_widget.html.erb, app/views/provider/admin/account/change_plans/widget/_features.html.erb, app/views/provider/admin/account/change_plans/widget/_limits.html.erb, app/views/provider/admin/accounts/show.html.slim
These and other icons have disappeared... who knows when! This PR replace such icons with "updated" ones, according to cms-toolbar-menu-right. Note that they now look flat whereas before they were outlined.
Before:
After:
=> Fix some missing icons

features/old/accounts/personal_details.feature, features/step_definitions/provider_steps.rb
This PR fix failure of wip feature of file 
porta/features/old/accounts/personal_details.feature
Jira issue
https://issues.redhat.com/browse/THREESCALE-9798
For verification
=> THREESCALE-9798 fix wip for Edit personal details with invalid data

lib/developer_portal/lib/liquid/drops/user.rb
Customers will update User > Show template at their Developer Portals from the following weeks until 2nd of October, when we will merge #3201. This PR introduces the method `using_password?`, which allows the template to render correctly.
This PR is related to [THREESCALE-6648 Require the current password on the password update form](https://issues.redhat.com/browse/THREESCALE-6648) and to #3201.
1. Go to Audience > Developer Portal > Content
2. At User > Show change the template for [this one](https://github.com/3scale/porta/blob/37c08f0882d0d07d00dae51a007f1db266a14029/lib/developer_portal/app/views/developer_portal/user/show.html.liquid).
3. Sign in at the Developer Portal using password. …
=> Add using_password? method to User at Drops module

Gemfile, Gemfile.lock
prior upgrading to Rails 6, better to upgrade cancancan alone and be easier if we have to fix something
upgrade guides are https://github.com/CanCanCommunity/cancancan/blob/develop/docs/migrating.md#from-2x-to-3x
- For "Defining abilities without a subject is not allowed anymore" - grep returned no such definitions, also I assume rails app initialization would fail if we had such
- For "Eager loading is not automatic", we enabled bullet N+1, etc. reporting so I hope we catch any such issues #3475 
- For "aliases are now merged" - I couldn't grep any instance where we call `merge` on Abilities
- For "Use of distinct" - this is more tricky, tried to go through the definitions to see how queries are defined and couldn't spot anything. Hope we test these anyway. Namely I inspected all blcok …
=> upgrade cancancan to a version supporting Rails 6

features/step_definitions/timehelpers_steps.rb, features/support/hooks.rb, features/support/time_machine_helpers.rb
We have some cucumbers failing on master for some time now ([CircleCI](https://app.circleci.com/pipelines/github/3scale/porta/25187/workflows/1aad78ed-fabf-4b05-9b8d-c24e7fe28b92/jobs/283477/tests)). This is the error:
`Message:Expected /^EUR\p{Separator}-7.00/ to match "EUR -6.7100". (Minitest::Assertion)`
These tests assert the invoice amount is generated correctly when the plan is changed in the middle of the month. But the time at which the plan is changed was wrong and the computed amount in the invoice didn't match because of that.
I observed locally that it was caused by [this step](https://github.com/3scale/porta/blob/4796fc3dcbfc40d549f7447bb0d33f7024ebe8ae/features/finance/variable_cost.feature#L93) being executed at any moment before the …
=> Fix time zone problem affecting cucumbers

app/javascript/src/ActiveDocs/OAS3Autocomplete.ts, app/lib/api_docs/provider_data.rb, doc/active_docs/account_management_api.json, test/integration/provider/admin/api_docs/account_data_controller_test.rb, test/unit/api_docs/provider_data_test.rb
Fixing auto-complete, replacing the buyers' users' IDs with providers' users' IDs (admin users only).
https://issues.redhat.com/browse/THREESCALE-9990
Open the Active Docs and check that IDs that appear belong to the current provider account.
=> THREESCALE-9990: Fix autocomplete for provider user IDs

app/helpers/whitelabel/admin/accounts/users_helper.rb
This string needs to be marked as html safe.
Before:
After:
=> Fix role radio button label

app/lib/plan_rule_loader.rb, test/unit/plan_rule_loader_test.rb
The tests pass: https://app.circleci.com/pipelines/github/3scale/porta?branch=THREESCALE-7405-rails-6-test
Not saying this is strictly required, but just wanted to clarify this :)
I think that even when the config shows up as having string keys, they are actually converted to `HasWithIndifferentAccess` by Rails' `config_for`, so symbol keys also work. So maybe we can clean up some more `symbolize_keys`, but not in the Rails PR.
=> Do not additionally deep-symbolize-keys

app/models/finance/billing_strategy.rb, app/models/finance/postpaid_billing_strategy.rb, app/models/finance/prepaid_billing_strategy.rb, app/models/invoice.rb, app/workers/billing_worker.rb
Just adding a consistent `[billing] provider #{buyer.provider_account_id} buyer #{buyer.id}:` prefix to log statements on all billing staging so we can query by that and reconstruct what happened during the process.
Also, putting the provider in front, so we can also filter out all billings for a single provider.
=> Improve logging for billing process - add a consistent prefix

Gemfile, Gemfile.lock, app/indices/account_index.rb, app/models/account.rb, app/workers/sphinx_account_indexation_worker.rb, app/workers/sphinx_indexation_worker.rb, config/initializers/sphinx.rb, features/support/initial_data.rb, features/support/sphinx.rb, test/integration/master/api/finance/billing_jobs_controller_test.rb, test/integration/provider/admin/backend_apis_controller_test.rb, test/integration/service_not_deleted_test.rb, test/test_helper.rb, test/test_helpers/sidekiq.rb, test/test_helpers/simple_mini_test.rb, test/test_helpers/sphinx.rb, test/unit/account/search_test.rb, test/unit/indices/indexing_test.rb, test/unit/tasks/services_test.rb, test/workers/delete_account_hierarchy_worker_test.rb, test/workers/delete_object_hierarchy_worker_test.rb, test/workers/signup_worker_test.rb, test/workers/sphinx_account_indexation_worker_test.rb, test/workers/sphinx_indexation_worker_test.rb
This is upgrading thinking-sphinx and updating `SphinxIndexationWorker` and `SphinxAccountIndexationWorker`.
In the past we used some internal APIs to call the proper thinking-sphinx callbacks for indexing and deinxing stuff. But  in 5.5.0 the `ThinkingSphinx::Processor` was introduced.
Unfortunately not getting access to the index, we also don't get the index `scope`, that's why `SphinxAccountIndexationWorker` hardcodes the searching scope. And the index `scope` is extracted into a model `scope` for easier access (see `account.rb`).
<del>### the error reporting</del>
<del>Improved error reporting of index worker errors. Switched `ErrorReporting` to use `add_metadata` because `add_tab` is deprecated.</del>
<del>https://www.rubydoc.info/gems/bugsnag/6.24.2/Bugsnag/Report#add_metadata-instan …
=> use ThinkingSphinx public API

features/old/accounts/notifications.feature
This PR fix failure of wip feature of file
features/old/accounts/notifications.feature
Jira issue
https://issues.redhat.com/browse/THREESCALE-9924
This feature is for enabling email notification of few process 
As soon as the checkbox is checked or unchecked details to send email is updated in database and so is checked in the test
=> THREESCALE-9924 completed the notification test

app/controllers/api/services_controller.rb, config/locales/en.yml, features/old/services/multiservice.feature, test/integration/api/services_controller_test.rb
Updated Flash errors while creating  new product
updated screenshots is added in JIRA comments
**Steps to reproduce**
Go to Products
Create new product
try creating product with name already used or not in the expected format which is mentioned in the form
Bakend page is a rails page and New prodcut is typescript.
https://issues.redhat.com/browse/THREESCALE-8131
=> THREESCALE-8131 fix misleading error

app/controllers/api/service_plans_controller.rb, app/presenters/api/service_plans_presenter.rb, features/api/services/service_plans.feature, features/old/api/plans/creation.feature, features/step_definitions/api/services/service_plans_steps.rb, features/support/parameter_types.rb, test/unit/presenters/plan_presenters_test.rb
Fix the issue where the index of service plans on a product include the service plans from other products.
Introduced by this change: https://github.com/3scale/porta/pull/3185/commits/99c6cb029f773831d287e4fdf1c9672c2f16d7b9#diff-2066514485e54295d6b177e8f030e3d8e547f73abbe2ae019981bac031e2232bR5
https://issues.redhat.com/browse/THREESCALE-9570
1. Create multiple products
2. Enable service plans in Audience > Usage Rules
3. Go to a product > Subscriptions > Service Plans
4. Make sure that only the service plans for the selected service are listed
=> THREESCALE-9570: Fix service plans scope on index page

features/support/sphinx.rb
Hopefully prevent issues like:
```
failed No pages match the search
Scenario: No pages match the search
Given I log in as "bob"
Message:Record IDs found by Sphinx but not by ActiveRecord : 10, 11, 12
https://freelancing-gods.com/thinking-sphinx/v5/common_issues.html#record-ids (ThinkingSphinx::Search::StaleIdsException)
/opt/app-root/src/project/vendor/bundle/ruby/2.6.0/gems/thinking-sphinx-5.5.1/lib/thinking_sphinx/middlewares/stale_id_checker.rb:38:in `raise_exception'
...
```
=> prevent stale search data

Gemfile, Gemfile.lock, test/test_helpers/transactional_fixtures.rb
I saw this annoying log all the time when running cucumbers locally:
```
Code:
* features/support/env.rb
Removing :environment prerequisite from db:create
rails aborted!
ActiveRecord::NoEnvironmentInSchemaError: 
Environment data not found in the schema. To resolve this issue, run: 
rails db:environment:set RAILS_ENV=test
bin/rails:4:in `<main>'
Tasks: TOP => db:test:load => db:test:purge => db:check_protected_environments
(See full trace by running task with --trace)
```
And found this: https://stackoverflow.com/questions/58923245/environment-data-not-found-in-the-schema-with-database-cleaner-when-calling-c
It says that this issue is happening in the version of `database_cleaner` that we were using.
I decided to risk it and upgrade to the latest …
=> Upgrade database cleaner

app/views/api/integrations/apicast/shared/_policies.html.slim, app/views/api/policies/edit.html.slim
[THREESCALE-10051: Render Policies errors using an Empty State](https://issues.redhat.com/browse/THREESCALE-10051)
Before:
After:
=> 🦋 Use EmptyState for Policies errors

app/lib/system_name.rb, app/models/access_token.rb, app/models/alert.rb, app/models/authentication_provider.rb, app/models/backend_api_config.rb, app/models/cinstance.rb, app/models/cms/builtin/legal_term.rb, app/models/cms/email_template.rb, app/models/cms/file.rb, app/models/cms/group.rb, app/models/cms/redirect.rb, app/models/cms/section.rb, app/models/cms/template.rb, app/models/country.rb, app/models/feature.rb, app/models/fields_definition.rb, app/models/invitation.rb, app/models/member_permission.rb, app/models/metric.rb, app/models/payment_intent.rb, app/models/policy.rb, app/models/referrer_filter.rb, app/models/sso_authorization.rb, app/models/system_operation.rb, app/models/topic_category.rb, app/models/usage_limit.rb, app/models/user.rb, app/models/user_topic.rb, app/models/web_hook.rb, config/initializers/tags.rb
Since upgrading to Rails 6 (in Staging so far), we've been seeing deprecation warning with the following text:
```
DEPRECATION WARNING: Uniqueness validator will no longer enforce case sensitive comparison in Rails 6.1. To continue case sensitive comparison on the :attribute_name attribute in ModelClass model, pass `case_sensitive: true` option explicitly to the uniqueness validator.
```
This is only observed on SaaS database, because its tables use case-insensitive collation. In on-premises (or locally) the warning is not shown, because there is no mismatch between the table collation and the validator behavior.
-none-
Make sure you don't see the deprecation warnings in the logs or in …
=> Fix deprecations for uniqueness validator (case-sensitivity)

app/assets/stylesheets/provider/_forms.scss, app/javascript/src/Policies/styles/policies.scss, app/views/api/policies/edit.html.slim
[THREESCALE-10042: Apply Patternfly to Policies](https://issues.redhat.com/browse/THREESCALE-10042)
Before:
* Remove legend and border:
* Remove width limit for index and new
* Use width limit and left align according to Patternfly design guidelines:
* Update submit button
=> 🦋 Improve Policies styling a bit

app/controllers/api/plans_base_controller.rb, features/api/application_plans.feature, features/step_definitions/api/application_plans_steps.rb
When creating an application plan with empty values instead of redirecting to the original form with error messages, an exception was thrown (resulting in Internal Error in production).
https://issues.redhat.com/browse/THREESCALE-10067
1. Create an application plan with empty values
2. Make sure the page gets redirected to the "new plan" form again and an error "can't be blank" is shown.
It was broken by this change: https://github.com/3scale/porta/commit/81580b903449a9df4f0e07c6fd9091acef38a4c2#diff-4fe6f4c55cef3c19ca6dd95d29923df263506790f761f312e8bf618bf463e5f7R73
The `#create` action renders [new](https://github.com/3scale/porta/blob/fix-app-plan-create …
=> THREESCALE-10067: Fix exception when creating app with empty data

app/controllers/stats/data/base_controller.rb
This fixes a deprecation warning:
`DEPRECATION WARNING: render file: should be given the absolute path to a file`
[THREESCALE-10056](https://issues.redhat.com/browse/THREESCALE-10056)
Send a `GET` request to:
```
http://provider-admin.3scale.localhost:3000/stats/applications/5/usage.xml?access_token=secret&metric_name=hits&since=2023-08-01&period=month&granularity=month&timezone=UTC
```
Before and after this PR, the deprecation warning should disappear.
=> THREESCALE-10056: Fix Deprecation when rendering file

app/models/account/provider_methods.rb, app/models/finance/billing_strategy.rb, app/services/finance/billing_error.rb, app/services/finance/billing_service.rb, app/services/finance/lock_billing_error.rb, app/services/finance/spurious_billing_error.rb, app/workers/billing_worker.rb, test/unit/account_test.rb, test/unit/finance/billing_strategy_test.rb, test/unit/provider_test.rb, test/unit/services/finance/billing_service_test.rb, test/workers/billing_worker_test.rb
The main fix is adding a scope to the `buyer_accounts` association that prevents returning self as a buyer. The changes in `BillingWorker::enqueue_for_buyer`, `BillingService` and `BillingStrategy` are extra safety layers.
<del>The main fix is in `BillingWorker::enqueue_for_buyer`. The changes in
`BillingService` and `BillingStrategy` are extra safety layers.</del>
And of course some tests.
=> fix double billing of providers

openshift/system/Dockerfile
The community image had liberation fonts missing thus billing acocunts failed when PDF was generated.
```
RuntimeError 
BillingWorker@billing
cannot find location of LiberationSans-Regular.ttf
```
=> liberation fonts for PDF generation

app/models/api_docs/service.rb
In ActiveRecord <7 some SQL queries generated under particular circumstances include more WHERE clauses they should. We hit this here:
https://github.com/3scale/porta/blob/f9ccd7442d8beb2e20634de64c1caaec252e05ff/app/models/api_docs/service.rb#L131-L133
From this code, one would expect this to be the resulting SQL:
```
SELECT `api_docs_services` .*
FROM `api_docs_services`
WHERE `api_docs_services`.`base_path` = 'http://echo-api.3scale.net/'
LIMIT 1
```
However, the code above is executed as part of the call to `first_or_create!` from here:
https://github.com/3scale/porta/blob/f9ccd7442d8beb2e20634de64c1caaec252e05ff/app/lib/logic/provider_signup.rb#L102-L104
And because of that, the parent scope `default_service.api_docs_services.where(name: …
=> THREESCALE-10059: Fix scope leak in ApiDocs::Service

app/controllers/application_controller.rb, app/lib/action_controller/request_forgery_protection/exception_and_reset_strategy.rb, app/lib/authenticated_system.rb, lib/developer_portal/app/controllers/developer_portal/login_controller.rb, test/integration/application_controller_test.rb, test/integration/sessions_test.rb
Check the description and comments at [THREESCALE-9752](https://issues.redhat.com/browse/THREESCALE-9752)
[THREESCALE-9752](https://issues.redhat.com/browse/THREESCALE-9752)
See the issue description to reproduce the bug.
=> THREESCALE-9752: Set :exception as the default forgery protection strategy

features/old/menu/dashboard.feature, features/step_definitions/custom_web_steps.rb, features/support/selectors.rb
🔥🔥🔥 
Back in the day, there was a widget in the Dashboard showing details about the first API (product). With APIaP it was replaced by the current widgets Products and Backends.
These 2 widgets are tested in `features/provider/dashboard/widgets.feature`.
=> 🔥🥒 Delete old scenario and selector

app/assets/stylesheets/provider/_forms.scss, app/javascript/src/Policies/components/PolicyChain.tsx, app/javascript/src/Policies/components/PolicyTile.tsx, app/javascript/src/Policies/styles/policies.scss, package.json, spec/javascripts/Policies/components/PolicyChain.spec.tsx, yarn.lock
[THREESCALE-10055: Remove dependency to react-sortable-hoc](https://issues.redhat.com/browse/THREESCALE-10055)
This PR removes a library used for the "drag and drop" functionality: `react-sortable-hoc`. This functionality is already included in Patternfly's `DragDrop` so it's become redundant.
It deleted middle-man components: `SortableList`, `SortableItem` and `DragHandle`.
It also implements Patternfly in the list by means of the component `DataList`.
Before:
After:
=> 🦋 Replace `react-sortable-hoc` with Patternfly's `DragDrop`

app/models/application_key.rb, app/models/cms/page.rb
follow-up on #3507
What really bothers me is that I can't see deprecation error locally. Although `config.active_support.deprecation` is configured.
**update:** I figured out. In prod database we use `utf8_general_ci` while locally we have `utf8_bin`. But the deprecation message from `/home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-6.0.6.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb` only applies when column collation is case insensitive. That's why locally it didn't trigger. If locally the `ci` collation is being used, the deprecation message is shown up.
=> rails 6 deprecation of case-sensitive uniqueness

app/views/provider/admin/cms/changes/index.html.erb
Just fixing a warning I noticed in the test logs:
```
/app/views/provider/admin/cms/changes/index.html.erb:12: warning: key :"data-method" is duplicated and overwritten on line 15
```
And as on it, I've refactored it a bit, and fixed another small issue (invalid `td` attribute on the `td` element)
=> Small refactor

Gemfile, Gemfile.lock, app/lib/events/importer.rb, app/models/web_hook/event.rb, app/services/service_discovery/import_cluster_definitions_service.rb, app/subscribers/zync_subscriber.rb, app/workers/cms/upgrade_content_worker.rb, app/workers/pdf_report_worker.rb, app/workers/persist_event_worker.rb, app/workers/report_traffic_worker.rb, config/initializers/audited_hacks.rb, config/initializers/sidekiq.rb, features/support/sidekiq.rb, test/test_helpers/sidekiq.rb, test/workers/backend_storage_rewrite_worker_test.rb, test/workers/billing_worker_test.rb, test/workers/create_service_token_worker_test.rb, test/workers/message_worker_test.rb, test/workers/persist_event_worker_test.rb, test/workers/zync_worker_test.rb
We need to add TLS and ACL support for Redis. The fastest and safest way to do it is to upgrade the `redis-rb` gem to v5. Unfortunately, this version is not supported by Sidekiq 5 which we are using now, so we need to upgrade Sidekiq to version 6.4.X.
[THREESCALE-10027](https://issues.redhat.com/browse/THREESCALE-10027)
All jobs should work successfully.
-----------
A couple of useful links about this upgrade:
- https://github.com/sidekiq/sidekiq/blob/main/docs/6.0-Upgrade.md
- https://github.com/sidekiq/sidekiq/wiki/Best-Practices
------------
When running `porta reset`, I saw a couple of deprecation warnings like this:
```
2023-08-01T10:45:09.766Z …
```
=> Upgrade to Sidekiq 6

app/controllers/api/metrics_controller.rb, app/models/metric.rb, app/models/proxy.rb, app/models/proxy_config.rb, app/views/api/metrics/edit.html.erb, app/views/provider/admin/backend_apis/metrics/edit.html.erb, config/locales/en.yml, features/api/metrics/delete.feature, features/step_definitions/api/metrics_steps.rb, features/step_definitions/apicast_steps.rb, test/factories/proxy.rb, test/unit/proxy_config_test.rb
Prevents deletion of metrics that are used in the current gateway configuration (staging or production).
https://issues.redhat.com/browse/THREESCALE-7112
1. Create a metric or method
2. Create a mapping rule using this metric
3. Promote the configuration to staging
4. Try deleting the metric and verify that it's not deleted, and an error message (flash) is shown
5. Remove the mapping rule using the metric
6. Promote the configuration
7. Try deleting the metric again and verify that it is successfully deleted
This should work for both staging and production environments.
This should work for both product-level and backend-level metrics.
What I am not sure …
=> THREESCALE-7112: Prevent deletion of metrics used in latest config

lib/tasks/sidekiq.rake, test/unit/tasks/sidekiq_test.rb
After upgrading to Sidekiq 6, the rake task to launch Sidekiq started to fail. The problem was found by the RHOAM team.
This PR fixes the problem by removing the `--index` parameter, which was used in very old Sidekiq releases but it's irrelevant since long ago. Check the commit where they removed it:
https://github.com/sidekiq/sidekiq/commit/5987a8c352a220a94e1850c79186d82c35050d85#diff-6cb1e9c2f07f71eba03ed54d2157cd999b8b3212009c92338d630f7e215ceed7L322-L327
Just run `bundle exec rails sidekiq` and check Sidekiq starts without issues.
=> Sidekiq task: remove `index` param

Gemfile, Gemfile.lock
kt-paperclip is a successor to paperclip which was discontinued.
This upgrade is necessary to prevent Ruby 2.7 and Rails 6.1 deprecation warnings as well add compatibility with Ruby 3.0
Should be a drop-in replacement. Locally I see no anomalies. Haven't tried with S3 but will do so in stg.
=> update paperclip to suppported version

app/views/provider/admin/applications/_utilization.html.erb
[THREESCALE-10133](https://issues.redhat.com/browse/THREESCALE-10133): Display percentage at Current utilization
This PR fixes an error at Current utilization, where it was duplicating the value metrics instead of displaying value and percentage. 
**Before**
**After**
from @mayorova:
Just for reference, the bug was introduced here: https://github.com/3scale/porta/commit/ee6afab4bc84146c6327f16e09a88bf2eb906cab#diff-c03110c10f92df9dcba83b75e405de05ac811ef040b854a1692ad71c6479cdecR45
=> Display percentage at Current utilization

app/helpers/application_helper.rb, app/helpers/menu_helper.rb, app/lib/system/deploy.rb, app/lib/three_scale.rb, config/locales/en.yml, test/helpers/menu_helper_test.rb, test/unit/helpers/application_helper_test.rb, test/unit/lib/system/deploy_test.rb
The documentation URLs in RHOAM are broken and point to 404 page.
https://issues.redhat.com/browse/THREESCALE-1699, specifically the issue reported in [this comment](https://issues.redhat.com/browse/THREESCALE-1699?focusedId=22849777&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22849777)
1. Run porta in RHOAM mode:
a. Set `onpremises: true` in `config/settings.yml`
b. Add `.deploy_info` file with `{"revision": "2.x-mas", "release": "RHOAM"}`
2. Go to `/p/admin/cms` path in the provider admin portal, and check that the [Creating the Developer Portal](https://access.redhat.com/documentation/en-us/red_hat_3scale/2-saas/html/creating_the_developer_portal/index) …
=> Refactor docs path and fix broken docs links for RHOAM

app/models/deleted_object.rb
Fix a Deprecation warning catched by [Bugsnag](https://app.bugsnag.com/3scale-networks-sl/system/errors/64d96e8ed4b5da00086171cb?filters[event.since]=30d&filters[error.status]=open&filters[search][]=Class&filters[search][]=level&filters[search][]=methods).
[THREESCALE-10138](https://issues.redhat.com/browse/THREESCALE-10138)
Just open a Rails console and type:
```
DeletedObject.stale
```
You should see the warning in master but not in this branch. The resulting query should be exactly the same.
=> Fix deprecation warning: Class level methods will no longer inherit scoping

Gemfile, Gemfile.lock, app/controllers/concerns/error_handling.rb, app/lib/system/error_reporting.rb, config/initializers/bugsnag.rb
The motivation for this upgrade was removing this warning in the development server logs:
```
[Bugsnag] -- Breadcrumb Read cache meta_data super_operation:Symbol has been dropped for having an invalid data type
```
This is [fixed](https://github.com/bugsnag/bugsnag-ruby/pull/563) in [v6.12](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.12.0)
Another useful fix is [Ruby 2.7 deprecation warnings](https://github.com/bugsnag/bugsnag-ruby/pull/582), which is released in [v6.13.1](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.13.0).
But as we're upgrading, I decided to upgrade to the latest available version. And it included some deprecations, e.g. in release [v6.23.0](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.23.0) …
=> Upgrade BugSnag gem

app/assets/stylesheets/provider/_forms.scss
I thought this selector made the Policy edit modal look good but it doesn't...? Instead it removes the input's right margin... no idea why either 😆 
**Note for reviewers**: please take an thorough look at possible CSS glitches.. this was added for a reason and something else could be broken.
Before:
After:
=> Fix checkbox input margin

app/views/provider/_footer.html.slim
Adds a link to the admin portal footer.
[THREESCALE-10145](https://issues.redhat.com/browse/THREESCALE-10145)
Open any page of the admin portal and see the link in the footer.
`ThreeScale.saas?` checks for `onpremises: false` in `settings.yml`, while `ThreeScale.tenant_mode.multitenant?` checks for the tenant mode (which is only multitenant in SaaS). In the current configuration (where on-premises pods use different tenant modes) they are equivalent, and I find `ThreeScale.saas?` less confusing.
=> THREESCALE-10145: Add Terms and Conditions link to the admin portal footer

app/controllers/finance/provider/invoices_controller.rb, app/models/invoice.rb, app/views/finance/provider/invoices/index.html.erb, features/old/finance/invoices/deleted_account.feature, features/provider/finance/invoices.feature, features/step_definitions/finance/invoicing_steps.rb, features/step_definitions/finance/navigation_steps.rb, features/step_definitions/provider_steps.rb, features/step_definitions/timehelpers_steps.rb, features/support/paths.rb, test/integration/provider/invoices_controller_test.rb
Reason mentioned in JIRA
https://issues.redhat.com/browse/THREESCALE-9592
We can remove this method as we are not using it any more 
**Pending** : test are pending if query looks good I can check for test
**Notes**
This is how it will look now, will show only current year if no invoices are present
this is how it was looking before
I don't have data on my local, so if any one have please past the screenshot how it will looks with data for reference but IMO query will work fine
=> THREESCALE-9592 show provide invoice years

app/lib/system/deploy.rb, test/unit/helpers/application_helper_test.rb, test/unit/lib/system/deploy_test.rb
Fixing random failures like here: https://app.circleci.com/pipelines/github/3scale/porta/25892/workflows/ee6dce4c-7b32-462d-ae92-c09b0f4bd21b/jobs/291266/parallel-runs/1?filterBy=FAILED
-none-
just run the CI tests and pray
I believe the issue was caused by the fact that when some tests were run in parallel, the deploy info was in some tests set to `nil` or invalid info.
So, I removed/changed `teardown` to ensure that outside of the `InvalidInfoTest` the `System::Deploy.info` is always a valid `System::Deploy::Info` class.
=> Fix (hopefully) deploy info random failures

.circleci/config.yml
When for example we rerun only failed tests,
then multiple runners may not have any tests to run.
<del>initial version is just to simulate skipping a run</del>
=> skip run when test list empty

app/controllers/application_controller.rb, app/lib/action_controller/request_forgery_protection/exception_and_reset_strategy.rb, app/lib/authenticated_system.rb, lib/developer_portal/app/controllers/developer_portal/login_controller.rb, test/integration/application_controller_test.rb, test/integration/request_forgery_protection/exception_and_reset_strategy_test.rb, test/integration/sessions_test.rb
We had to revert (https://github.com/3scale/porta/pull/3536) the CSRF fix (https://github.com/3scale/porta/pull/3528) because it broke the `basic` auth method.
This PR fixes the regression and also adds some tests:
- For the `basic` auth method
- For our new request forgery protection strategy
[THREESCALE-9752](https://issues.redhat.com/browse/THREESCALE-9752)
This both requests should work now
```
curl -X POST \
'http://master-account.3scale.localhost:3000/master/api/providers.xml?email=admin%40example.com&org_name=examplepp&password=password&username=adminp&access_token=0ed4092e4ce8edd23afb2b68d8216482237da6a990e988616cf2613e8e9e2631' \
-H 'accept: application/xml' \
-H 'cache-control: …
```
=> THREESCALE-9752: Fix Basic auth method

Gemfile, Gemfile.lock, app/lib/three_scale/metrics/yabeda.rb, config/initializers/yabeda.rb, config/routes.rb
- report less stuff
The next step (once we are happy with this set of metrics) would be to expose system-app metrics (not sidekiq) at `/metrics` (as opposed to the current `/yabeda-metrics`).
https://issues.redhat.com/browse/THREESCALE-9934
```
curl http://localhost:9394/yabeda-metrics
```
Verify that it reports what is expected.
The changes are just to try something, it's not necessarily what we want, we may remove some metrics completely, or change them.
=> THREESCALE-9934: Report less metrics to prometheus from Rails app

features/provider/admin/messages/outbox.feature, features/support/paths.rb
Fixes CI failing every day on Postgres and Oracle
The `#find` block was using assignment  `=` instead of comparison `==`
Fixes [THREESCALE-10219](https://issues.redhat.com/browse/THREESCALE-10219)
Say hello to the team from my part ;)
=> [Cucumber] Fix THREESCALE-10219 - feature failing because of a typo

app/controllers/admin/api_docs/account_api_docs_controller.rb, app/controllers/admin/api_docs/service_api_docs_controller.rb, app/controllers/api/integrations_controller.rb, app/controllers/api/services_controller.rb, app/controllers/application_controller.rb, app/controllers/finance/provider/settings_controller.rb, app/controllers/provider/admin/account/authentication_providers_controller.rb, app/controllers/provider/admin/accounts_controller.rb, app/controllers/provider/admin/api_docs/account_data_controller.rb, app/controllers/provider/admin/api_docs_controller.rb, app/controllers/provider/admin/applications_controller.rb, app/controllers/provider/admin/authentication_providers_controller.rb, app/controllers/provider/admin/user/access_tokens_controller.rb, app/controllers/provider/admin/webhooks_controller.rb, app/controllers/sites/dns_controller.rb, doc/liquid/tags.md, lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb, lib/developer_portal/app/controllers/developer_portal/cms/new_content_controller.rb, lib/developer_portal/app/views/developer_portal/accounts/payment_gateways/edit.html.liquid, lib/developer_portal/app/views/developer_portal/accounts/payment_gateways/show.html.liquid, lib/developer_portal/app/views/developer_portal/applications/index.html.liquid, lib/developer_portal/app/views/developer_portal/applications/show.html.liquid, lib/developer_portal/app/views/developer_portal/docs.html.liquid, lib/developer_portal/app/views/developer_portal/index.html.liquid, lib/developer_portal/config/initializers/liquid.rb, lib/developer_portal/lib/liquid/tags/disable_client_cache.rb, test/integration/application_controller_test.rb, test/unit/liquid/tags/disable_client_cache_test.rb
[THREESCALE-10076: Content caching not set for personal tokens page. Allows page retrieval when logged out.
](https://issues.redhat.com/browse/THREESCALE-10076)
When logging out and clicking back button on the browser page is rendered from the browser cache.
Though the PR says it's in the personal tokens page, it happens anywhere so it could be verified there and also wherever in the application. Just log out and confirm that when clicking back you won't be redirected to the previous page.
**Update**
As @jlledom proposed, finally we'll be applying this to the following screens: 
Admin portal:
Developer portal:
=> 🔒️ Set cache headers to no-cache

app/javascript/packs/provider.scss, app/javascript/src/QuickStarts/components/QuickStartContainer.scss, app/javascript/src/QuickStarts/components/QuickStartContainer.tsx, app/javascript/src/Types/custom.d.ts, package.json, yarn.lock
Upgrading Patternfly Quick starts to the PF4 ones (https://www.patternfly.org/v4/extensions/quick-starts).
In order to avoid the Quick starts bug with `showFilter`, the search has been deleted until we upgrade to PF5.
[THREESCALE-9638: Upgrade Patternfly Quickstarts](https://issues.redhat.com/browse/THREESCALE-9638)
**Before**
**After**
=> 🦋 Upgrade Patternfly Quickstarts

config/initializers/yabeda.rb, lib/three_scale/metrics/yabeda.rb
Fix the annoying
```
Prometheus::Client::Registry::AlreadyRegisteredError`
rails_requests_total has already been registered
```
-none-
-none-
=> Run prometheus metrics installation just once

.rubocop.yml
What the title says. We're on Ruby 2.7 now.
=> Upgrade Ruby version in .rubocop.yml

Gemfile, Gemfile.lock, test/test_helpers/sidekiq.rb, test/workers/backend_delete_service_token_worker_test.rb
Removing `sidekiq-lock` dependency, as it is not used.
It was initially added here:
https://github.com/3scale/system/commit/bd63ac2ecaccb4d51e1854c24e109ae4f4770506
But locking was replaced by `sidekiq-throttled` here:
https://github.com/3scale/porta/commit/9ff8f6abf8a4c1f3b0aa402a6e04a1f997edbac4
No other workers use this.
-none-
=> Remove unused sidekiq-lock gem

app/assets/stylesheets/provider/_forms.scss, app/helpers/account_helper.rb, app/helpers/api/services_helper.rb, app/helpers/cinstances_helper.rb, app/javascript/src/NewService/components/FormElements/FormWrapper.tsx, app/lib/cms/semantic_form_builder.rb, app/lib/three_scale/semantic_form_builder.rb, app/views/admin/fields_definitions/edit.html.erb, app/views/api/policies/edit.html.slim, app/views/buyers/accounts/edit.html.slim, app/views/buyers/users/edit.html.erb, app/views/finance/provider/settings/show.html.slim, app/views/provider/admin/account/data_exports/new.html.erb, app/views/provider/admin/applications/edit.html.slim, app/views/provider/admin/backend_apis/forms/_delete.html.slim, app/views/provider/admin/keys/edit.html.erb, app/views/provider/admin/messages/outbox/new.html.slim, app/views/sites/settings/edit.html.slim, app/views/sites/usage_rules/edit.html.slim, features/step_definitions/providers/csv_steps.rb
[THREESCALE-10250: Remove ugly separators in formtastic forms](https://issues.redhat.com/browse/THREESCALE-10250)
* Apply PF4 to all actions fieldset.
* Remove top border from inputs fieldsets.
* Apply PF4 Form section styles to fieldset legends.
Some examples:
* After:
=> 🦋 Remove ugly borders in forms

app/controllers/api/backend_usages_controller.rb, app/javascript/packs/toolbar.ts, app/javascript/src/Common/components/Toolbar.tsx, app/views/api/backend_usages/index.html.slim, config/locales/en.yml, features/api/backend_usages.feature, features/step_definitions/backend_usages_steps.rb, features/step_definitions/service_steps.rb
[THREESCALE-9814: Integration > Backend usages table](https://issues.redhat.com/browse/THREESCALE-9814)
Old:
Option A: button to the right
Option B: button to the left
=> 🦋 Backend APIs pagination, toolbar and empty state

lib/tasks/boot.rake
Due to a regression after upgrading to Sidekiq 7, the `boot:redis` rake task was broken.
The new redis gem doesn't accept any unknown parameter, but we include some parameters in our `.yml` which belong to the pool, not Redis. I modified the task to connect to Redis the same way [Porta](https://github.com/3scale/porta/blob/master/app/lib/system/redis_pool.rb#L9-L14) and [Sidekiq](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/redis_connection.rb#L10-L26) do it: through a pool.
Run and verify it works correctly
```
bundle exec rake boot:redis
```
=> Fix regression: boot:redis task

app/controllers/master/events/imports_controller.rb, test/integration/master/events/imports_controller_test.rb
Events coming from backend are failing due to CSRF forgery protection. This is a regression caused by https://github.com/3scale/porta/pull/3543
[THREESCALE-10272](https://issues.redhat.com/browse/THREESCALE-10272)
1- Send a query to the endpoint:
```
curl --request POST  --url 'http://master-account.3scale.localhost:3000/master/events/import'
```
2- Check that an `EventsFetchWorker` job is enqueued
=> THREESCALE-10272: Skip CSRF protection for events webhook

app/views/provider/admin/messages/outbox/index.html.slim, app/views/provider/admin/messages/trash/index.html.slim, features/provider/admin/messages/outbox.feature
1. Outbox page erroneously showed the "To" column as "From" (the "From" is always the same - the current provider)
2. Added "To" column to the trashed messages table. For the deleted sent messages only "From" was shown (with the provider name as value), but not who the message was sent to, while the same message can be sent to multiple developers, so if they are all deleted, it's very confusing, as they look like duplicates.
No JIRA for this.
=> Fix the columns in messages tables

app/workers/zync_worker.rb, test/workers/zync_worker_test.rb
Fix a regression that we introduced here: https://github.com/3scale/porta/pull/3608/commits/60ce61cde319490356feaa10ecc7e60f1a014113
It results in some ZyncWorker jobs failing with 
```
ZyncWorker::InvalidResponseError: Expected successful response. Got 400
```
Because the payload get serialized to JSON twice.
-none-
-none-
=> Fix serialization of ZyncWorker arguments

app/lib/backend/storage_rewrite.rb, app/lib/three_scale/filter_arguments.rb, app/workers/backend_storage_rewrite_worker.rb, lib/tasks/backend.rake, test/unit/backend/storage_rewrite_test.rb, test/unit/sidekiq_logging_middleware_test.rb, test/workers/backend_storage_rewrite_worker_test.rb
Currently, the backend storate rewriting schedules one Sidekiq job per each provider. For some providers, that have thousands of applications, the jobs take forever.... they get stuck in Sidekiq for excessive times (sometimes more than 30 mins), this way blocking all other processing.
This PR adds some improvements:
1. It skips deleted (scheduled for deletion) and suspended providers, so we don't sync anything for these accounts
2. Instead of executing a single job per provider, it splits all the work into mutliple jobs, grouping the objects in batches (currently max batch size is set to 500).
This should allow the jobs to get executed faster, and also give opportunity to other jobs in the same queue to get processed.
**Which issue(s) this PR …
=> THREESCALE-10043: Optimize BackendStorageRewriteWorker

app/controllers/frontend_controller.rb, app/views/provider/admin/accounts/suspended.html.slim, features/provider/accounts/suspending_tenants.feature, features/step_definitions/provider_steps.rb, features/support/hooks.rb, features/support/initial_data.rb
Change the wording on the suspended page, and ensure it is informative and non-confusing for both SaaS and On-premises.
SaaS (point to https://access.redhat.com/support):
On-premises (using `SUPPORT_EMAIL` value):
https://issues.redhat.com/browse/THREESCALE-8974
Go to any page on the portal of the suspended tenant.
=> THREESCALE-8974: Reword "your account is suspended" page

test/unit/authentication/strategy/provider_oauth2_test.rb
This test started randomly failing when we switched to `:random` test order in https://github.com/3scale/porta/pull/3618
Basically, the test is wrong, and the reason why they used to pass, is that when they were always executed in order, it was like this:
1. `test_create_a_non_active_user_through_sso`
2. `test_create_an_active_user_through_sso`
So, the email was actually sent in test 1, and this was the email asserted in test 2, while test 2 did not actually create any new emails. It is expected, because if the user already has `email_verified: true` coming from SSO, we don't need to verify their email by sending them a message with activation link.
-none-
Make sure the tests do not randomly …
=> Fix SSO user creation test

app/controllers/provider/admin/accounts_controller.rb
[THREESCALE-10446: New Account page menu is not activated (master)](https://issues.redhat.com/browse/THREESCALE-10446)
Before:
After:
=> Activate menu in New Provider page

test/integration/admin/api/member_permissions_controller_test.rb
Fixing the member permissions test. Because hard-coding `22` as a "surely nonexistent ID" was a bad idea :sweat_smile: 
-none-
-none-
=> Fix hardcoded value in the member permissions test

app/workers/set_tenant_id_worker.rb, lib/tasks/fixes.rake, lib/tasks/multitenant/tenants.rake, test/workers/set_tenant_id_worker_test.rb, test/workers/sphinx_account_indexation_worker_test.rb, test/workers/sphinx_indexation_worker_test.rb
Follow-up on #2904
Supersedes #2949
First require user to enter relations that need fixing so that
they can be fixed individually.
Additionally perform updating in batches to reduce overall number of
jobs.
Also set the used queue to "low". Can't really test whether its faster in staging before we merge.
```
bundle exec rake 'multitenant:tenants:fix_missing_in_background[backend_apis,alerts]'
BackendApi.where(tenant_id: nil).count # 46850
Alert.where(tenant_id: nil).count # 1695504
```
Which issue(s) this PR fixes:
https://issues.redhat.com/browse/THREESCALE-7676
=> THREESCALE-7676: limit number of jobs for tenant fixes

app/javascript/src/Common/components/TableToolbar.tsx
[THREESCALE-10506: TableToolbar: Rename isShared param to shared](https://issues.redhat.com/browse/THREESCALE-10506)
=> ⚛️ Fix prop `isShared`

app/views/emails/account_approved.text.liquid
This is a bug introduced by https://github.com/3scale/porta/pull/3001/files#diff-1c5334d368e3ebaf8349ca1d8407e2e694c6d9b54ff062dd728305c900ea4e1e
We renamed all **internal** invocations of `.domain` because this method had been deprecated. However, in this case it's a Liquid drop, it should never have been changed, but we missed this.
https://issues.redhat.com/browse/THREESCALE-10212
Ensure that when the account is approved, the email is sent correctly.
=> THREESCALE-10212: Fix account approved email template

app/controllers/sites/spam_protections_controller.rb, app/helpers/vertical_nav_helper.rb, app/lib/three_scale/semantic_form_builder.rb, app/views/sites/spam_protections/edit.html.erb, doc/liquid/tags.html, doc/liquid/tags.md, features/developer_portal/login.feature, features/old/accounts/service_contracts.feature, features/old/authorization/provider_settings.feature, features/old/menu/audience_menu.feature, features/step_definitions/buyer_steps.rb, features/support/paths.rb, lib/developer_portal/app/controllers/developer_portal/login_controller.rb, lib/developer_portal/lib/liquid/forms/login.rb, lib/developer_portal/lib/liquid/tags/form.rb
This adds bot protection to the login screen in the developer poral.
It also renames "Spam protection" to "Bot protection" in the UI.
[THREESCALE-10579](https://issues.redhat.com/browse/THREESCALE-10579)
1. Enable or disable reCAPTCHA on the bot protection settings screen (`/site/spam_protection/edit`)
2. Check the reCAPTCHA badge appears or disappears accordingly on the login screen
3. With reCAPTCHA enabled, and `RECAPTCHA_MIN_BOT_SCORE=0.5`, the login screen behaves as usual. But with `RECAPTCHA_MIN_BOT_SCORE=0.99`, the bot protection prevents the user to log in, even when sending the correct credentials.
=> THREESCALE-10579 : Bot protectin on the login screen

app/javascript/src/Stats/lib/csv_link.js, spec/javascripts/Stats/lib/csv_link.spec.js
Encode the data that is used for the CSV export of charts.
https://issues.redhat.com/browse/THREESCALE-10259
1. Create an app with a special character, e.g. #, and create some traffic on it
2. Go to Analytics > Top Applications of the product, and click Download CSV
3. Verify that the CSV is generated correctly (no data is truncated)
=> THREESCALE-10259: URL-encode data in the Download CSV link

.github/workflows/fast-forward-branch.yml
Fixes two issues with the fast-forward action:
1. The refs (not branches) couldn't be fast-forwarded, as one of the steps was failing with the following error:
```
Run issues=$(git log origin/managed-services..origin/13022c9ac07a87847d3d3dec00085e3f24dcfbd0 | grep -ioh "THREESCALE-[0-9]\+" | sort -u | sed -e 's/^/https:\/\/issues.redhat.com\/browse\//')
fatal: ambiguous argument 'origin/managed-services..origin/13022c9ac07a87847d3d3dec00085e3f24dcfbd0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'origin/managed-services..origin/13022c9ac07a87847d3d3dec00085e3f24dcfbd0': unknown revision or path not in the working …
```
=> Fix fast-forward GitHub action

lib/three_scale/metrics/yabeda.rb
Restoring `controller` label on `rails_request_duration_seconds_*` metrics that was previously deleted in https://github.com/3scale/porta/pull/3648
After speaking with @slopezz we thought it might be useful, and we will need to see how bad will the memory consumption of Prometheus be affected.
Example:
```
rails_request_duration_seconds_bucket{controller="api/services",le="+Inf"} 1
rails_request_duration_seconds_bucket{controller="api/services",le="0.01"} 0
rails_request_duration_seconds_bucket{controller="api/services",le="0.025"} 0
rails_request_duration_seconds_bucket{controller="api/services",le="0.05"} 0
rails_request_duration_seconds_sum{controller="api/services"} 0.415
rails_request_duration_seconds_sum{controller="api_docs/services"} …
```
=> Restore controller label on rails_request_duration_seconds_* metrics

app/views/provider/admin/dashboards/_developers_navigation.html.slim, features/old/menu/dashboard.feature
Fixes the messages counter on the dashboard.
https://issues.redhat.com/browse/THREESCALE-1752
- Send some messages from the developer portal
- Make sure that the correct count is shown in admin portal dashboard. It should correspond to the number of messages in provider's Inbox. The number in parenthesis should indicate the number of unread messages (if any).
=> THREESCALE-1752: Fix messages counter on the dashboard

app/views/sites/dns/show.html.erb, features/api/backend_usages/index.feature, features/old/buyers/users.feature, features/old/providers/fields_definitions.feature, features/old/switches/branding.feature, features/provider/admin/applications/keys.feature, features/provider/admin/messages/inbox.feature, features/step_definitions/user_management/common_steps.rb, features/step_definitions/web_steps.rb
This is needed in an effort to understand some intermittent failures but also is a good idea in general to be more strict about which link is being clicked.
Commits are self-contained so can be reviewed individually.
=> stricter link following in cucumbers

features/old/messages/buyer_side.feature, features/step_definitions/messages_steps.rb, lib/developer_portal/app/controllers/developer_portal/admin/messages/outbox_controller.rb, lib/developer_portal/lib/liquid/drops/message.rb, test/integration/developer_portal/admin/messages/outbox_controller_integration_test.rb
@akostadinov noticed that the following test was failing randomly:
```
No message from bob to foo.3scale.localhost with subject "Re: Wassup?" and body "Yep, all good." was sent.
features/old/messages/buyer_side.feature:48:in `a message should be sent from buyer "bob" to provider "foo.3scale.localhost" with subject "Re: Wassup?" and body "Yep, all good."'
Failing Scenarios:
cucumber -p ci features/old/messages/buyer_side.feature:39 # Scenario: Repling to a message
```
https://app.circleci.com/pipelines/github/3scale/porta/27058/workflows/80e72514-a5cc-40c1-a0ca-8cff2c3c5572/jobs/303600/parallel-runs/5?filterBy=FAILED
This was caused by https://github.com/3scale/porta/pull/3588, specifically [this …
=> Fix Message Liquid drop that broke replies

app/helpers/vertical_nav_helper.rb, app/views/api/services/show.html.slim, app/views/provider/admin/backend_apis/show.html.slim, features/old/menu/api_menu.feature, features/old/services/multiservice.feature, features/provider/admin/backend_apis/show.feature, test/helpers/vertical_nav_helper_test.rb
Currently the [Product_name] in the side menu is not clickable, user needs to click the dropdown menu on the header, select products>x product to jump to the [Product_overview page
All comments of the JIRA clears the need of this issue
https://issues.redhat.com/browse/THREESCALE-8748
its already done on Backend so updated Product
=> Threescale 8748 update product overview header

app/views/sites/spam_protections/edit.html.erb
When no reCAPTCHA keys are provided, the Bot protection edit form should be disabled.
[THREESCALE-10579](https://issues.redhat.com/browse/THREESCALE-10579)
Don't configure any reCAPTCHA key and visit `/site/spam_protection/edit`:
**Before:**
**After:**
=> THREESCALE-8404: Disable edit form When no reCAPTCHA keys are provided

app/views/buyers/accounts/index.html.slim, app/views/provider/admin/applications/index.html.slim
No description in [Product_applications_listing] page & [Product_accounts_listing]
Improvement: Add a description for audience/applications and audience/accounts.
Location
https://red-hat-wat-admin.3scale.net/p/admin/applications
https://red-hat-wat-admin.3scale.net/buyers/accounts
Microcopy
https://docs.google.com/document/d/1igPAmV9g78R3tlm8O3fifgAFNq7hYuitz0_1JpRuj0k/edit#
https://issues.redhat.com/browse/THREESCALE-8747
=> Threescale 8747 add description for Acount and  Application

config/initializers/sphinx.rb, test/workers/sphinx_account_indexation_worker_test.rb
The purpose of this is to support manticore which doesn't have compatible
behavior for the `found` query metadata.
The pagination in sphinx should work ideally with `found`:
https://sphinxsearch.com/blog/2014/03/28/basics-of-paginating-results/
Since that is not available (see https://github.com/pat/thinking-sphinx/pull/1213 and https://github.com/manticoresoftware/manticoresearch/issues/912) we
monkey patch the method as well limit max results we return to 1000.
That should be plenty for our use cases. And should thus work with both - sphinx and manticore.
=> [THREESCALE-10375] manticore support

features/support/hooks.rb
I've hit a problem that the `chrome` driver didn't have this enabled in local runs. So on failure there is an error from this code that hides the actual test error. I think it is not necessary to collect performance metrics in the local browser so rather I made this collection optional.
FIY for `headless_chrome` perf logs are enabled here:
https://github.com/3scale/porta/blob/bd54e7485e144e4b0a933f75b51e2463573cb746/features/support/capybara.rb#L108-L110
=> fixup browser logs

app/controllers/provider/sessions_controller.rb, app/views/provider/sessions/logged_out.html.erb, test/integration/provider/sessions_controller_test.rb
Previously we decided that users shouldn't be able to logout when there's SSO is enforced and there's only one SSO provider published.
See the Jira issue: https://issues.redhat.com/browse/THREESCALE-2795
And the PR: https://github.com/3scale/porta/pull/2155
Note the second scenario in the PR: `when only one SSO integration is configured and enforced`
However, **THREESCALE-2983** complains about this behavior. This PR ensures the user can't skip the login screen even when there's only one published provider and one active session on that provider.
[THREESCALE-10797](https://issues.redhat.com/browse/THREESCALE-10797)
1. Configure the admin portal to enable an RH SSO integration
**Account …
=> THREESCALE-10797: Enable SSO logout when SSO is enforced

Gemfile, Gemfile.lock
Upgrades `psych` gem - it's normally provided together with Ruby, but as we are using an older version (2.7), we are just upgrading this gem.
The issue is described in the [issue #442](https://github.com/ruby/psych/issues/442), and fixed in the [PR #438](https://github.com/ruby/psych/pull/438).
The first release where it got fixed is [v](https://github.com/ruby/psych/releases/tag/v3.2.0). I am not sure if it makes sense going to the most recent version. I'd say - not worth it, maybe on the next Ruby upgrade we can consider getting rid of adding explicit version for `psych`.
And the reason why this causes an issue in the first place is that we create audit logs for `Cinstance` (among other models), and `audited_changes` column is YAML-serialized. …
=> Upgrade psych to fix issues with serializing values with trailing underscore

app/inputs/patternfly_checkbox_input.rb
There are no disabled checkboxes yet, but the style will be missing when it's used.
Before:
After:
=> 🦋 Add missing style for disabled PF checkbox

app/models/application_key.rb, app/models/cinstance.rb, config/locales/en.yml, config/routes.rb, doc/active_docs/account_management_api.json, test/unit/application_keys_test.rb, test/unit/cinstance_test.rb
Add support to `/` and `\` (the latter was previously in the list of allowed characters, but in fact was not working, see [this JIRA comment](https://issues.redhat.com/browse/THREESCALE-9033?focusedId=24165695&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24165695))
This would only work however with apisonator that has this feature: https://github.com/3scale/apisonator/pull/366
https://issues.redhat.com/browse/THREESCALE-9033
**NOTE:** In theory, according to [RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749/#appendix-A) we are supposed to support the whole `x20-7E` range, but we excluded spaces previously. But now …
=> Add support for slash for application IDs and keys

config/routes.rb, test/integration/user-management-api/buyers_application_keys_test.rb
Fixes deleting application key when it has dots, via API.
https://issues.redhat.com/browse/THREESCALE-7570
Honestly, I am not sure whether that's the right way, but it seems to be working as expected :upside_down_face:
=> THREESCALE-7570: Allow dots in application key for API

app/controllers/api/proxy_rules_controller.rb, app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb, app/controllers/proxy_rule_shared_controller.rb, app/javascript/src/BackendApis/components/IndexPage.tsx, app/javascript/src/Products/components/IndexPage.tsx, app/lib/applications_controller_methods.rb, app/presenters/api/proxy_rules_index_presenter.rb, app/presenters/applications_index_presenter.rb, app/presenters/provider/admin/backend_apis/mapping_rules_index_presenter.rb, app/presenters/proxy_rules_index_base_presenter.rb, app/views/api/applications/index.html.slim, app/views/api/proxy_rules/index.html.slim, app/views/buyers/applications/index.html.slim, app/views/provider/admin/applications/index.html.slim, app/views/provider/admin/backend_apis/mapping_rules/index.html.slim, app/views/shared/provider/_page_header.html.slim, app/views/shared/proxy_rules/_body_section.html.slim, app/views/shared/proxy_rules/_header_section.html.slim, features/api/services/applications/new.feature, features/buyers/accounts/applications/new.feature, features/provider/admin/applications/new.feature, features/provider/admin/backend_apis/new.feature
[THREESCALE-9661: Move buttons in title to the main section](https://issues.redhat.com/browse/THREESCALE-9661)
There are still some legacy tables that are blocking this task. When they are updated, the buttons will be removed.
Before:
After:
=> 🦋 Remove buttons from page headers

app/views/buyers/accounts/show.html.slim, app/views/master/providers/plans/_widget.html.slim, features/step_definitions/buyers/accounts/account_overview_steps.rb
Functionality is broken due to missing class `colorbox` and wrong input's `id` and `name`.
=> 🐛 Fix change plan widget in account overview

db/migrate/20240302090207_remove_redundant_provider_index.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb
Since we have compound indices that begins with provider_id,
it is redundant to also have a separate provider_id index
=> optimize RDBMS provider indexing

app/javascript/packs/bulk_operations.ts, app/javascript/src/BackendApis/components/NewBackendModal.tsx, app/javascript/src/Common/components/BulkActionsDropdown.tsx, app/javascript/src/Policies/webpack-public-path.ts, app/javascript/src/Types/colorbox.d.ts, app/javascript/src/Types/globals.d.ts, app/javascript/src/Types/jquery/v1/index.d.ts, app/javascript/src/utilities/flash.ts, app/javascript/src/utilities/test-utils.ts, spec/javascripts/ActiveDocs/useCodeMirror.spec.tsx, tsconfig.json, yarn.lock
`window.$` has jquery v1 with plugins injected from gems, such as rails-ujs, cookie, flash...
`import $ from 'jquery'` is jquery v3 without plugins, just plain jquery.
CAVEAT: this messes up with vs code types and will show errors, however compilation will work as expected. An issue has been opened to try to fix it: https://github.com/microsoft/TypeScript/issues/57555. It's an IDE problem, not a typescript one.
CAVEAT 2: it seems it's `@types/jquery`'s fault. I opened an issue: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/68853.
**Verification:**
- tests pass: `yarn jest`
- lint passes: `yarn lint`
- webpack assets compiles: `rails assets:precompile assets:precompile:tests`
=> 🏷️ Types for `window.$`

app/models/cms/email_template.rb, lib/developer_portal/lib/liquid/template/resolver.rb
On production, when an email template is updated, the changes don't take effect until the Sidekq pod is restarted.
This happens because liquid templates are stored in a cache on the server, and that cache never gets invalidated, so after the template is cached the first time, the renderer will always fetch the same cached version of the template, and ignore any more recent version of it.
It's important to mention that this cache is not the same cache store configured through `cache_store.yml`, so Memcached is not involved. This is an internal in-memory cache implemented by Rails for optimization and the user is not supposed to deal with it.
The bug only affects liquid templates because they are fetched using a custom template resolver written by us, which doesn't integrate correctly with …
=> THREESCALE-8383: Clear liquid cache for email templates

features/support/sphinx.rb
Trying to fix errors like
```
Before hook at features/support/sphinx.rb:8
Message:thinking sphinx should be running: [Sat Apr 13 00:16:30.021 2024] [626] using config file '/opt/ci/project/config/test.sphinx.conf' (5387 chars)...
[Sat Apr 13 00:16:30.022 2024] [626] WARNING: secondary_indexes set but failed to initialize secondary library: (null)
Manticore 6.2.12 dc5144d35@230822
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
...
```
https://app.circleci.com/pipelines/github/3scale/porta/27939/workflows/c19ccf0a-e1e2-408a-98f4-0e978a01a7f8/jobs/312776/tests
=> wait more for manticore if needed

app/helpers/vertical_nav_helper.rb, config/abilities/provider_member.rb, test/helpers/vertical_nav_helper_test.rb, test/integration/provider/admin/backend_apis/stats/usage_controller_test.rb, test/integration/stats/data/backend_apis_controller_test.rb
Fixes "Access Denied" to a member admin user that tries to access the Backend API's analytics screen.
Also fixed a similar access issue when trying to access the backend API usage via Analytics API.
There is no fine-grained permission system for API backends, but the UI says "all API backends", so when this permission is enabled, I guess it should allow the user to view all backends.
I also allowed viewing the Backend API index, because without it the user can't navigate to a specific backend (in a very likely case that it doesn't appear on the Dashboard).
https://issues.redhat.com/browse/THREESCALE-7491
- Create a member user in the admin portal and grant "Access & query analytics of:" …
=> THREESCALE-7491: Fix permissions errors for member user with Analytics permissions

app/javascript/packs/codemirror.ts, app/views/provider/admin/cms/_save_buttons.html.erb, app/views/provider/admin/cms/email_templates/_buttons.html.erb
This features was supposed to be handled by Mousetrap. Who knows when it stopped working. This is completely optional.
=> Fix codemirror save shortcut

app/controllers/admin/api/service_contracts_controller.rb, app/controllers/admin/api/service_subscriptions_controller.rb, app/models/service_contract.rb, app/representers/service_subscription_representer.rb, app/representers/service_subscriptions_representer.rb, config/locales/en.yml, config/routes.rb, doc/active_docs/account_management_api.json, test/integration/user-management-api/service_subscriptions_controller_test.rb, test/unit/observers/message_observer_test.rb, test/unit/observers/plan_observer_test.rb, test/unit/service_contract_test.rb
This PR comes out of https://github.com/3scale/porta/pull/3750 and replaces https://github.com/3scale/porta/pull/3672 (as it has already diverged from it too much).
It adds the missing service subscription (service contracts) API endpoints, and fixes some bad representation in the existing endpoints - by adding new endpoints under `/admin/api/accounts/{account_id}/service_subscriptions` and deprecating the old `/admin/api/accounts/{account_id}/service_contracts`.
The new endpoints are only available in JSON format, XML is not supported.
https://issues.redhat.com/browse/THREESCALE-2689
=> THREESCALE-2689: Service Subscription API: create, show, change plan, approve

app/lib/three_scale/api/responder.rb, app/models/plan.rb, app/models/service.rb, lib/developer_portal/app/controllers/developer_portal/admin/account/account_plans_controller.rb, lib/developer_portal/app/views/developer_portal/javascripts/3scale.js, lib/developer_portal/app/views/developer_portal/javascripts/3scale_v2.js, lib/developer_portal/lib/liquid/drops/provider.rb, lib/developer_portal/lib/liquid/drops/service.rb, test/unit/service_test.rb, test/unit/three_scale/api/responder_test.rb
This removes the default scope of Plan, which orders by the value of the `position` column. This column is populated using [acts_as_list](https://github.com/brendon/acts_as_list) gem.
It seems that long long time ago there probably was some way to reorder the application plans manually, but now I can't see any feature related to that in the UI or API. Moreover, in the UI plans are normally ordered by name, with a posibility of ordering by state or contracts count.
It actually causes problems with Oracle, that doesn't support `ORDER BY` in subqueries.
This PR also adds a default order for objects in API responses (by `id`) - it guarantees a predictable order in all databases, which is especially important for endpoints that have pagination.
**Which …
=> Do not use plan position for ordering

app/assets/javascripts/application.js
TODO
Reproducing steps:
1. In dev portal CMS, add the following to "Main Layout"'s head:
```liquid
<head>
...
{% essential_assets %}
</head>
```
2. Open dev portal and you shouldn't see an error like this:
```
ActionView::Template::Error (The asset "application.js" is not present in the asset pipeline.
):
9:
10: <%= javascript_include_tag 'highlight/highlight.pack.js' %>
11: <%= javascript_include_tag 'flash', 'remote', 'switch', 'extra_fields' %>
12: <%= javascript_include_tag 'application' %>
13:
14: <%= yield :javascripts %>
lib/developer_portal/app/views/shared/_essential_assets.html.erb:12
```
=> 🐛 Restore `application.js` for old dev portals

config/locales/en.yml, doc/active_docs/cms_api.json, test/integration/api_docs/services_controller_test.rb
Just remove the `(Tech Preview)` notice about CMS API
https://issues.redhat.com/browse/THREESCALE-10588
=> Remove "Tech Preview" notice

.circleci/config.yml
We say we [support](https://access.redhat.com/articles/2798521) PostgreSQL 13, so we'd rather test it. On the other hand, the built-in Postgres is version 10 still. See JIRA #8545
There is also JIRA #8920 to support the latest version.
And even though built-in Postgres is 10, I think we need to test 13 anyway, because we recommend using an external DB in production environment (and that should be version 13).
-none-
-none-
=> Upgrade PostgreSQL on CircleCI from 10 to 13

app/lib/three_scale/redis_config.rb, test/unit/three_scale/redis_config_test.rb
Our Redis client for porta is able to select the given logical database from the url.
e.g. `redis://localhost:6379/6` will connect to `localhost:6379` and select the DB `6`.
When using sentinels, a URL like `redis://redis-master/6` should be used to extract the group name `redis-master` and the DB `6`. This works fine for porta, but not for Sidekiq after we upgraded to version 7. Now Sidekiq expects these two parameters to be provided explicitly through the `:name` and `:db` options.
This PR extracts the `:db` parameter from the URL in case it's not provided. If empty, `:db` will be null, not `0`.
https://issues.redhat.com/browse/THREESCALE-11062
1. Set a config like this:
``` …
```
=> THREESCALE-11062: Redis config: extract DB from URL

app/lib/three_scale/redis_config.rb, config/examples/backend_redis.yml, config/examples/redis.yml, openshift/system/config/backend_redis.yml, openshift/system/config/redis.yml, test/unit/three_scale/redis_config_test.rb
When using Redis sentinels, we need to provide a group name. This was automatic before, but after upgrading to Sidekiq 7 we need to provide it manually. For that reason we added `REDIS_SENTINEL_NAME` and `BACKEND_REDIS_SENTINEL_NAME`. However, in order to maintain backwards compatibility and avoid changes in the operator, it's better to extract the group name from the URL.
This PR also removes the env vars, since they are not needed anymore.
https://issues.redhat.com/browse/THREESCALE-11070
1. Set this config:
```
REDIS_URL=redis://redis-master/1
REDIS_SENTINEL_HOSTS=redis://localhost:26379,redis://localhost:26380,redis://localhost:26381
``` 
2. Launch Sidekiq
3. It should start and work …
=> THREESCALE-11070: Extract the Redis sentinels group name from the URL

app/assets/javascripts/srcdoc-polyfill.min.js, lib/developer_portal/app/views/shared/cms/_toolbar.html.slim
This is a pollyfill for the HTML5 attribute `srcdoc`, which is supported by all major browsers since a long time ago. It was probably used at first for IE compatibility.
See https://github.com/jugglinmike/srcdoc-polyfill/
=> 🔥🧹 Remove unnecessary srcdoc polyfill

features/support/sphinx.rb
I think previously it was possible for some `After` hooks
to trigger indexing jobs for `not @search` scenarios as well after
`@search` scenarios but after searchd was already stopped.
Thus lets disable indexing jobs at the very begining and only enable it
within scenarios that actually need that.
=> disable search by default in cucumbers and enable with @search annotation

app/lib/system/redis_pool.rb, app/lib/three_scale/redis_config.rb, config/application.rb, config/examples/backend_redis.yml, config/examples/redis.yml, config/initializers/sidekiq.rb, openshift/system/config/backend_redis.yml, openshift/system/config/redis.yml, test/unit/system/redis_pool_test.rb, test/unit/three_scale/redis_config_test.rb
QE detected some strange behavior when many tenants are created in a short period of time. @akostadinov thinks this could be due to the new `:size` parameter we are sending to Sidekiq.
I verified that `:size` in fact interferes with Sidekiq internals ([code](https://github.com/sidekiq/sidekiq/blob/e798c23643cd7d3f3b229016a87fec2bfeb7905a/lib/sidekiq/redis_connection.rb#L22-L29)) and after Sidekiq 7, they recommend to let Sidekiq decide the pools size ([docs](https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-API-Migration.md#connection-pools))
We don't know if that's going to fix QE problem or not, but I think this PR is needed anyway, considering the reasons above.
The reason why I renamed `:pool_size` to `:size` initially it's because the Redis …
=> Rename `:size` back to `:pool_size`

app/indices/cms_page_index.rb, app/presenters/search_presenters.rb, app/workers/sphinx_account_indexation_worker.rb, app/workers/sphinx_indexation_worker.rb, config/initializers/sphinx.rb, test/factories/cms.rb, test/unit/indices/indexing_test.rb, test/unit/tasks/searchd_tasks_test.rb
We filter out unpublished pages in `SearchPresenter` anyway. So better not index them to begin with.
Also don't index anything out of sphinx/manticore index scope globally.
=> sphinx index only published cms pages

app/views/provider/admin/onboarding/wizard/request/show.html.slim
In production, the last step of the onboarding wizard was responding with the `Internal Error` page and the following logs:
```
[728d8711-352c-4fc0-8773-c753a178b2c6] [provider-admin.3scale.localhost] [127.0.0.1]   Rendering provider/admin/onboarding/wizard/request/show.html.slim within layouts/wizard
[728d8711-352c-4fc0-8773-c753a178b2c6] [provider-admin.3scale.localhost] [127.0.0.1]   Rendered provider/admin/onboarding/wizard/request/show.html.slim within layouts/wizard (Duration: 9.8ms | Allocations: 4095)
[728d8711-352c-4fc0-8773-c753a178b2c6] [provider-admin.3scale.localhost] [127.0.0.1] Completed 500 Internal Server Error in 100ms (ActiveRecord: 14.0ms | Allocations: 40423)
[728d8711-352c-4fc0-8773-c753a178b2c6] …
```
=> THREESCALE-11067: Fix onboarding wizard error

app/helpers/menu_helper.rb, features/menu/context_selector.feature, features/step_definitions/navigation_steps.rb, features/step_definitions/user_steps.rb, features/support/helpers/session_helpers.rb, test/helpers/menu_helper_test.rb, test/integration/stats/applications_test.rb
A member can't see either Audience, Products or Backends but the context selector shows these options. This PR removes the aforementioned items as long as the current user hasn't got permission to access them.
For a standard member, this is how it looks after this PR:
=> 🐛 Context selector shows forbidden pages to members

app/controllers/provider/admin/dashboards_controller.rb, app/controllers/provider/sessions_controller.rb, features/provider/dashboard.feature, features/step_definitions/password_steps.rb, features/support/helpers/session_helpers.rb
Fix a bug introduced at #3726 ([THREESCALE-11006](https://issues.redhat.com/browse/THREESCALE-11006)). The `dashboards_controller` wasn't handling properly the `first_login` flash, making Quick starts notification trigger every time the user went to the Dashboard. This PR fixes that problem and improves its cucumber.
1. Create a new provider.
2. Confirm that on login you receive the Quick starts notification.
3. Confirm that after logout and login again you don't receive the Quick starts notification.
4. Confirm that when reloading the dashboard you don't receive the Quick starts notification.
=> Fix Quick starts notification problem

openshift/system/Dockerfile
Recently the upstream image builds started failing with the following error:
```
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
This apparently happened because Centos8 repos were deprecated, and now are located in http://vault.centos.org.
Relevant info: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
> After May 31, 2024, CentOS Stream 8 will be archived and no further updates will be provided.
> The packages will be archived on vault.centos.org after May 31, 2024.
-none-
Builds must pass. Locally can be checked with:
```
podman build -f openshift/system/Dockerfile --tag …
```
=> Fix yum repo by disabling mirror and using vault as baseurl

app/models/settings.rb, test/integration/admin/api/settings_controller_test.rb, test/unit/settings_test.rb
Adds some validations for the settings attributes that were having issues:
- `change_service_plan_permission` could be set to any value, added a validation
- when setting empty values, for some columns the following error was being thrown:
```
ActiveRecord::NotNullViolation: Mysql2::Error: Column 'public_search' cannot be null
```
I've also noticed that setting boolean attributes to any string (e.g. `public_search=whatever`) was flipping the setting to `true`. This is how Rails casting works, it converts any value that is not `"false"`, `"false"` or empty to `true`. So, I guess this is the common behavior across all endpoints. I don't like it, because it is quite confusing, but it is also a bit tricky to fix.
We can't really add a validation because …
=> Settings API validations

app/models/settings.rb, test/integration/admin/api/settings_controller_test.rb, test/unit/settings_test.rb
Fix the issue reported https://issues.redhat.com/browse/THREESCALE-8319?focusedId=24892835&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24892835
https://issues.redhat.com/browse/THREESCALE-8319
1) set `account_approval_required` to `true` via API
2) set only `account_plans_ui_visible` or other attribute to whatever and NOT add `account_approval_required` to the query
3) verify that `account_approval_required` is still `true`
This behavior (defaulting to `false` on empty values - `attrs.delete(:account_approval_required).presence || false`) was implemented long time ago in the model, and in …
=> THREESCALE-8319: Ignore empty values for account_approval_required instead setting to false

config/initializers/filter_parameter_logging.rb
Just add `authenticity_token` and `access_code` to the list of filtered parameters in logs.
The issue mentions `access_token` as well, but that one was fixed in 2.14: https://github.com/3scale/porta/pull/3099/files
https://issues.redhat.com/browse/THREESCALE-10798
1. Add an access code to the developer portal
2. Open the developer portal and fill in the access code
3. Check the logs, they should look like
```
Parameters:
{"authenticity_token"=>"[FILTERED]", "access_code"=>"[FILTERED]", "commit"=>"Enter"} 
```
=> THREESCALE-10798: Filter out `authenticity_token` and `access_code`

app/views/sites/usage_rules/_settings_check.html.slim, config/locales/en.yml, features/master/settings.feature
In the master portal, when following Audience > Accounts > Settings > Usage rules it fails due to a missing translation at the edit template. 
As suggested by @mayorova, adding a empty default option fixes the problem. 
[THREESCALE-11114](https://issues.redhat.com/browse/THREESCALE-11114)
In the master portal, go to Audience > Accounts > Settings > Usage rules and confirm the page is shown.
=> THREESCALE-11114: Usage rules missing translation

.circleci/config.yml
Postgres 13 will be EOL soon, we need to officially support Postgres14.
After a research, I would say we already support it completely, so this PR only updates the CircleCI pipeline. More info below.
https://issues.redhat.com/browse/THREESCALE-8920
This is the list of checks and tests I made:
- Check `pg` gem support
- We use `1.3.5`. In the [Changelog](https://github.com/ged/ruby-pg/blob/master/History.md) I didn't find in which release they added support for Posgres 14, but there are multiple references to it in older releases, so I assume our version supports it.
- Reset database with `bundle exec rails db:reset`
- Working fine locally
- Create triggers with `bundle exec rails …
=> THREESCALE-8920: Support postgres 14

app/controllers/provider/admin/account/payment_gateways/braintree_blue_controller.rb, app/lib/payment_gateways/stripe_crypt.rb, app/models/account/credit_card.rb, features/step_definitions/developer_portal/admin/account/payment_details_steps.rb, lib/developer_portal/app/controllers/developer_portal/admin/account/payment_details_base_controller.rb, lib/developer_portal/app/controllers/developer_portal/admin/account/stripe_controller.rb, lib/developer_portal/config/routes.rb, lib/developer_portal/lib/liquid/forms/account.rb, test/integration/developer_portal/admin/account/stripe_controller_test.rb, test/unit/account/credit_card_test.rb, test/unit/lib/payment_gateways/stripe_crypt_test.rb, test/unit/liquid/forms_test.rb
Changing customer billing address, in the developer portal, is updated to Stripe only when credit card details are changed. Just editing and saving billing address details creates problems, when customer details are not consistent between 3scale and Stripe. This can be forcefully fixed, when the customer updates their credit card information as well. 
Expected behavior:
Editing just billing address details should update customer details on Stripe.
https://issues.redhat.com/browse/THREESCALE-9532
Mentioned in jira with snapshots
=> Fixed Updating customer billing address now correctly reflected to stripe

lib/developer_portal/lib/liquid/drops/base.rb
When working with the developer portal in the `development` mode I noticed that going to Settings (`/admin/account`) throws the following error:
This happens at least when the provider has a payment gateway defined and Billing is visible in the dev portal. 
This didn't happen before, and it also not reproducible in production (yay!).
Below I list my findings in order of appearance:
- There was a change in accessing the polymorphic routes implemented in Rails 6.1 (that we recently merged): https://github.com/rails/rails/commit/bb61baa6ef2ffb0d01f6f5a37a4add5934341bc6
- there is a difference in the results of `.public_methods` and `.private_methods` of `Liquid::Drops::Urls` (which is the "recipient" in the code referenced in the Rails commit listed …
=> Do not "privatize" URL helper in Liquid::Drops::Base

db/migrate/20240719174715_onboardings_tenant_id_fix.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb, lib/system/database/definitions/mysql.rb, lib/system/database/definitions/oracle.rb, lib/system/database/definitions/postgres.rb, test/integration/buyers/users_controller_integration_test.rb
onboardings are currently created for buyer accounts as well and
existing trigger created with `tennant_id = account_id` is incorrect.
This PR fixes this. Also existing onboardings are reset to `nil` tenant.
This should avoid failures when checking the tenant_id and they don't contain
critical information so no need to obtain the correct `tenant_id`.
It can be done later if necessary.
=> THREESCALE-7183 onboardings tenant_id fix

config/examples/database.yml
Add support to connect to TLS protected MySQL and Postgres.
Our current versions of `pg` and `mysql2` gems already support TLS connections, so the only thing we need is a few environment variables for the user to provide the certs and keys.
These variables will be set by the operator, as specified in this jira issue: https://issues.redhat.com/browse/THREESCALE-11156
https://issues.redhat.com/browse/THREESCALE-4185
Here is the `podman-compose.yml` I used to launch TLS protected Postgres and MySQL locally:
```yml
version: '3.8'
services:
mysql:
image: mysql:8.0
container_name: mysql-compose-ssl
ports:
- "23306:3306"
environment:
- MYSQL_ALLOW_EMPTY_PASSWORD=true
healthcheck:
test: "mysql …
```
=> THREESCALE-4185: Support TLS protection for external DBs

app/lib/three_scale/redis_config.rb, test/unit/three_scale/redis_config_test.rb
Last changes to support TLS for Redis caused a regression that broke one scenario: reading the sentinels credentials from the URL.
Now providing a sentinel URL like this should be accepted:
```
rediss://user:password@localhost:56380 
```
https://issues.redhat.com/browse/THREESCALE-11205
1. Don't set `REDIS_SENTINEL_USERNAME` nor `REDIS_SENTINEL_PASSWORD`.
2. Include credentials in `REDIS_SENTINEL_HOSTS`:
```
REDIS_SENTINEL_HOSTS=rediss://username:password@localhost:56380,rediss://localhost:56381,rediss://localhost:56382`
```
3. It all should work fine
=> THREESCALE-11205: Read sentinels credentials from the URI

config/application.rb
Prevent the following error when `rolling_updates.yml` is not present in `config`:
```
NoMethodError: undefined method `deep_merge' for nil:NilClass
config.three_scale.rolling_updates.features = try_config_for(:rolling_updates).deep_merge(try_config_for(:"extra-rolling_updates") || {})
^^^^^^^^^^^
/home/dmayorov/Projects/3scale/porta/config/application.rb:218:in `<class:Application>'
```
---
=> Do not fail when rolling_updates.yml is missing

app/lib/cms/s3.rb, app/lib/pdf/finance/invoice_report_data.rb, app/models/profile.rb, app/views/provider/admin/account/logos/_logo.html.slim, lib/developer_portal/app/views/shared/_logo.html.slim, lib/developer_portal/lib/liquid/drops/provider.rb, test/unit/pdf/finance/invoice_report_data_test.rb, test/unit/profile_test.rb
Currently, profile logo uses a public URL, e.g.
https://bucket-name.s3.amazonaws.com/provider/id/profiles/logos/medium/logo-file-name.png
This requires public access to be enabled on the bucket, which is a bad security practice.
This PR changes the URL used for the logo to [presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html) (through `#expiring_url` from `kt-paperclip`).
https://issues.redhat.com/browse/THREESCALE-8932
Create and configure an S3 bucket with no public access and verify that the following works:
- upload a logo at `/p/admin/account/logo/edit` and view it afterwards
- regenerate some invoice PDF and verify the logo is visible on the …
=> Fix logo s3 public access

app/lib/three_scale/oauth2/keycloak_client.rb, app/lib/three_scale/oauth2/redhat_customer_portal_client.rb, test/unit/three_scale/oauth2/keycloak_client_test.rb, test/unit/three_scale/oauth2/redhat_customer_portal_client_test.rb
Since version 23 Keycloak (RHBK) adds a `iss` query parameter to the authentication response, see https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-23-0-0
The result of this is that 3scale client included this `iss` value to the `redirect_uri` when fetching the access token, which in its turn caused an error:
```
{"error":"invalid_grant","error_description":"Incorrect redirect_uri"}
```
This PR only removes the `iss` from the redirect URI when forming the access token request. Ideally, we would need to also verify the value of the `iss` parameter to make sure it is exactly the same as the Realm URL specified in the SSO configuration. See [2.4.  Validating the Issuer Identifier](https://www.rfc-editor.org/rfc/rfc9207.html#name-val …
=> Strip 'iss' query param from the redirect URL for Keycloak auth flow

Gemfile, Gemfile.lock
After upgrading to Sidekiq 7, we had to fork `sidekiq-batch` because upstream was outdated and only supported up to Sidekiq 6. They recently released a new version with full support for Sidekiq 7, so we can get rid of the fork.
This completes [THREESCALE-10207](https://issues.redhat.com/browse/THREESCALE-10207)
Everything should work as usual, specially the workers using the batches feature, like the billing worker.
=> THREESCALE-10207: Upgrade `sidekiq-batch` to 0.8.0

app/views/provider/admin/accounts/new.html.slim
When we upgraded this template to PatternFly the password field became an input without type. Adding the type covers that.
=> 🦋 Hide password field at New Provider account

app/controllers/admin/api/signups_controller.rb, app/lib/active_model/errors_to_xml.rb, app/lib/three_scale/errors_to_xml.rb, config/initializers/active_model.rb
This PR fixes two deprecation messages reported to Bugsnag:
[Report](https://app.bugsnag.com/3scale-networks-sl/system/errors/667178505397250008adc486?filters[event.since]=30d&filters[app.release_stage]=production)
When calling an API endpoint using XML format, if there are any errors those are returned in XML. To do that, rails ends up calling `ActiveModel::Errors#to_xml`.
For some reason they have deprecated that method because allegedly is not much used. I'm very surprised they think nobody supports XML in their APIs... Anyway. They'll remove the method in Rails 7, so we have to provide our own. I monkey patched `ActiveModel::Errors` to include the original `#to_xml` method but without the warning.
Check: https://github.com/rails/rails/pull/32313
**Commit**: …
=> Fix deprecations on `ActiveModel::Errors`

app/models/account/search.rb, app/models/user.rb, test/unit/account/search_test.rb
When searching accounts using searchd, results are filtered by current `tenant_id`, but not in the master portal. When searching as master, all accounts are considered, also buyer accounts.
Read the Jira description for further info.
This PR introduces one change:
**Before:**
- Master: Search over all accounts
- Provider: Search over all accounts having `tenant_id` = current provider ID
**After:**
- Master and Provider: Search over all accounts having `provider_account_id` = current provider ID
**New query:**
```sql
SELECT * FROM `account_core` WHERE MATCH('*api*')
AND `provider_account_id` = 1
AND `sphinx_deleted` = 0 LIMIT 0, 1000000 OPTION cutoff=0, field_weights=(name=2)
``` …
=> THREESCALE-10856: Searchd: Filter Accounts by provider id

app/controllers/admin/api/accounts_controller.rb, app/controllers/admin/api/backend_apis_controller.rb, app/controllers/admin/api/services_controller.rb, app/controllers/master/api/providers_controller.rb, app/models/account.rb, app/models/annotation.rb, app/models/application_record.rb, app/models/backend_api.rb, app/models/concerns/annotating.rb, app/models/concerns/annotating/managed_by.rb, app/models/concerns/annotating/model.rb, app/models/service.rb, app/representers/account_representer.rb, app/representers/backend_api_representer.rb, app/representers/service_representer.rb, db/migrate/20240726111800_create_annotation_references.rb, db/oracle_schema.rb, db/postgres_schema.rb, db/schema.rb, lib/system/database/definitions/mysql.rb, lib/system/database/definitions/oracle.rb, lib/system/database/definitions/postgres.rb, test/factories/annotation.rb, test/integration/annotating_test.rb, test/unit/annotation_test.rb, test/unit/concerns/annotating/managed_by_test.rb, test/unit/concerns/annotating/model_test.rb, test/unit/concerns/annotating_test.rb
Adds annotations to models. This allows adding a new parameter `annotations` to some API endpoints. I tested:
- **POST** `/admin/api/backend_apis`
- **PUT** `/admin/api/backend_apis/{id}`
- **POST** `/admin/api/services`
- **PUT** `/admin/api/services/{id}`
- **POST** `/admin/api/signup`
- **PUT** `/admin/api/accounts/{id}`
- **POST** `/master/api/providers`
- **PUT** `/master/api/providers/{id}`
This comes from https://github.com/3scale/porta/pull/3581. I took the DB migration and the Ruby backend for annotations, but I removed the service, I don't think we need it and it demands significant changes in the controllers, which would make it more cumbersome to add new annotations to new controllers. …
=> THREESCALE-1786: Managed by operator

app/models/account/buyer_methods.rb, app/models/cms/group.rb, app/models/cms/group_section.rb, app/models/contract.rb, app/models/features_plan.rb, app/models/oidc_configuration.rb, app/models/plan.rb, lib/tasks/multitenant/tenants.rake, lib/three_scale/tenant_id_integrity_checker.rb, test/unit/plan_test.rb, test/unit/tasks/multitenant/tenants_integrity_test.rb, test/workers/set_tenant_id_worker_test.rb
The main feature is a rake task to validate integrity of database `tenant_id` fields. With some fixes.
The output in logs after running is something like:
```
Inconsistent tenant_ids for:
Plan[285] features_plans FeaturesPlan[285, 140]
Service[117] features Feature[140]
```
Note that `[285, 140]` is a complex primary key, not two objects. There is only 1-1 objects on each line. Too lazy to deduplicate and it is ugly with complex primary keys on top of it.
=> tenant_id integrity validation task

app/controllers/admin/fields_definitions_controller.rb
Accounts/Settings/Fields Definitions/New: When the form is sent but it's invalid, the sent data stays in the in-memory object. When `fieldname` is in memory, the value it's excluded from the dropdown. This just reloads the object to ensure all in-memory data is discarded. 
https://issues.redhat.com/browse/THREESCALE-11276
Follow the steps in the ticket description
=> THREESCALE-11276: New field definition: Fix dropdown content

Makefile, SETUP_ORACLE.md, config/examples/database.yml, lib/system/database.rb
wrt postgres change in configuration file
To run with Postgres locally is a little harder because when
DATABASE_URL is set, it remains the same for all environments.
To differentiate from the development database one can set
TEST_ENV_NUMBER but that makes database name like
`3scale_system_development_test` instead of simpler `3scale_system_test`
as on MySQL/MariaDB and more importantly this is somehow ugly to see.
With this change one can just set DATABASE_URL for development and URL
for the `test` environment will be adjusted automatically.
This is also similar to how oracle works where `test` is appended to
`systempdb` automatically.
oracle instructions are self-explanatory
=> some database inscructions and convenience

app/helpers/patternfly_components_helper.rb, app/views/api/services/edit.html.slim, app/views/api/services/show.html.slim, app/views/buyers/accounts/edit.html.slim, app/views/buyers/accounts/show.html.slim, app/views/provider/admin/backend_apis/edit.html.slim, app/views/provider/admin/backend_apis/show.html.slim, app/views/shared/_annotations.html.slim, app/views/shared/provider/_page_header.html.slim, config/locales/en.yml
This replaces https://github.com/3scale/porta/pull/3865. That got closed after merging https://github.com/3scale/porta/pull/3857
The operator can manage porta resources through API. When a resource is managed by operator, we must inform the user about that.
https://github.com/3scale/porta/pull/3857 implements the backend support (annotations). This PR implements the frontend, for now, just a banner in the relevant screens:
- `http://provider-admin.3scale.localhost:3000/buyers/accounts/4`
- `http://provider-admin.3scale.localhost:3000/buyers/accounts/4/edit`
- `http://provider-admin.3scale.localhost:3000/apiconfig/services/2`
- `http://provider-admin.3scale.localhost:3000/apiconfig/services/2/edit`
- …
=> THREESCALE-1789: Add "Managed by operator" banner (UI)

app/helpers/patternfly_components_helper.rb, app/views/shared/_annotations.html.slim
The changes introduced in are not compatible with Ruby 3.1, the error is:
```
Message:wrong number of arguments (given 1, expected 2) (ActionView::Template::Error)
/opt/ci/project/app/helpers/patternfly_components_helper.rb:32:in `pf_inline_alert'
/opt/ci/project/app/views/finance/provider/settings/show.html.slim:7:in `block in _app_views_finance_provider_settings_show_html_slim__2337285527868729147_165440'
```
To fix it I decided to refactor it a bit more - see comments inline.
=> Refactor pf_inline_alert

app/controllers/provider/admin/user/personal_details_controller.rb, app/controllers/provider/sessions_controller.rb, app/models/user.rb, app/models/user_session.rb, lib/developer_portal/app/controllers/developer_portal/admin/account/personal_details_controller.rb, lib/developer_portal/app/controllers/developer_portal/login_controller.rb, test/factories/user_session.rb, test/functional/developer_portal/admin/account/personal_details_controller_test.rb, test/functional/developer_portal/login_controller_test.rb, test/functional/provider/admin/user/personal_details_controller_test.rb, test/integration/provider/sessions_controller_test.rb, test/unit/user_session_test.rb
This PR adds audits for `UserSession`. In particular fot `:create` and `:revoke` operations
The Jira issue also mentions auditing when a `User` is locked. I'm not sure what **"locked"** means but I assume it means **"suspended"**. If that's the case, then that was already done.
Besides, the issue also asks to add some audit logs for some operations:
- Login
- success (this was already done)
- failed
- User account
- password change success
- password change failed
In both admin and developer portals.
The PR also adds some tests for the new functionality.
https://issues.redhat.com/browse/THREESCALE-10843
Just perform the operations above and check the audits appear.
=> THREESCALE-10843: Audit user sessions

features/support/capybara.rb
* Assets from webpack-dev-server (after `bye_bye_webpacker`) can't be found due to host_resolver
* Running cucumbers with tag `@chrome` fail due to chromedriver showing a "choose search engine" dialog. Disabled with `--disable-search-engine-choice-screen`.
* Formatting
=> Update `headless_chrome` options

app/views/api/applications/index.html.slim, app/views/provider/admin/applications/index.html.slim, config/locales/en.yml
Adds a brief description to the header of Product > Applications > Listing, applying consistency as we already have that description at Audience > Applications > Listing.
[THREESCALE-11090](https://issues.redhat.com/browse/THREESCALE-11090)
1. Go to Product > Applications > Listing
2. Confirm there is a description under the header
**Before**
**After**
=> THREESCALE-11090: Add description to Applications > Listing on Product side

Gemfile, Gemfile.lock, app/lib/backend/storage.rb, app/lib/three_scale/jobs.rb, test/unit/lib/three_scale/jobs_test.rb, test/unit/three_scale/middleware/cors_test.rb
`psych` gem is the a default gem shipped with Ruby.
In https://github.com/3scale/porta/pull/3714 there was an attempt to fix some issues with YAML serialization by upgrading the version, however for some reason it never worked in the production images (still needs to be figured out why).
With Rails upgrade from 2.7 to 3.1 Psych version was upgraded to 4.0.4.
Apparently, this caused an issue due to an uncompatibility between the versions: https://stackoverflow.com/a/71192990
This was caughed by QE tests, the logs in the system pods were:
```
Completed 500 Internal Server Error in 37ms (ActiveRecord: 14.3ms | Allocations: 12401)
Psych::BadAlias (Unknown alias: default):
app/lib/backend/storage.rb:9:in `parse_config'
app/lib/backend/storage.rb:14:in `initialize'
app/lib/stats/base.rb:22:in …
```
=> Remove psych hardcoded version and use alias explicitly

config/application.rb
The `X-Served-By` header was added a long time ago (see https://github.com/3scale/system/pull/4966) for debugging purposes, apparently.
I guess this was never announced as a "feature", so I doubt anybody actually relies on it.
This PR effectively removes the header (actually enabling it only when `DEBUG_X_SERVED_BY=1` is set), so it will not be present anywhere, but we may enable it if we want (e.g. in SaaS).
This header is mostly related to caching servers, so I don't think it's critical that it will go away for most users.
https://issues.redhat.com/browse/THREESCALE-11201
Send any request and make sure that `X-Served-By` is not present.
=> Disable X-Served-By header by default

app/javascript/packs/dashboard.scss, features/provider/dashboard.feature, features/step_definitions/window_steps.rb
This PR assures that Quick start button at the dashboard disappears when screen size is smaller than 1200px.  
1. Go to Dashboard
2. Make the screen smaller than 1200px
3. Confirm Quick start button isn't displayed
**Before**
**After**
=> 💄 Fix quick start dashboard button

app/javascript/src/Navigation/components/VerticalNav.scss
[THREESCALE-11235: Product or Backend name is not visible if name is too long](https://issues.redhat.com/browse/THREESCALE-11235)
Before:
After:
=> 💄 Product name in vert nav

app/models/account/credit_card.rb, app/models/account/gateway.rb, test/unit/account/credit_card_test.rb
If payment gateway configuration is invalid on a provider account, their buyers cannot be deleted because the `unstore_credit_card!` method is called as `before_destroy` callback.
Specifically, if the payment gateway type is `:stripe`, but the gateway settings stored in the database miss the `login` field, the payment gateway instance cannot be initialized, and the whole operation fails.
This PR catches the error, raises a more specific `Account::Gateway::InvalidSettingsError` error and "swallows" it the `unstore_credit_card!`, thus allowing for the destroy to complete successfully.
https://issues.redhat.com/browse/THREESCALE-11383
Steps to reproduce or to confirm that that issue is not …
=> THREESCALE-11383: Ignore errors on payment gateway initialization when destroying buyer

.circleci/config.yml, Gemfile, Gemfile.lock, features/support/capybara.rb, features/support/hooks.rb
For Ruby 3.1 upgrade we built a `system-builder` image with a fixed version of chromedriver, because the latest (127 on that moment) was timing out.
https://github.com/3scale/porta/pull/3896 introduced a configuration change which probably is what was missing for the latest Chrome to work as expected, so hopefully we can now remove this restriction.
=> Do not hardcode chromedriver versions for test

config/examples/amazon_s3.yml
This PR fixes a confusing behavior when `FILE_UPLOAD_STORAGE` is set to `filesystem` explicitly.
It's not "broken" in the product, because it's assumed that when this env var is empty, `filesystem` is used, and when it's `s3`, then S3 is used for storage.
But when `FILE_UPLOAD_STORAGE=filesystem` is set explicitly, the application isn't loaded, with the error:
```
/home/dmayorov/.asdf/installs/ruby/3.1.5/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:326:in `block in visit_Psych_Nodes_Alias': Unknown alias: filesystem (Psych::BadAlias)
```
because the `amazon_s3.yml` doesn't have a `:filesystem` alias.
There are some references that hint that `filesystem` is a potential valid value for `FILE_UPLOAD_STORAGE`:
- …
=> Fix amazon_s3.yml config for FILE_UPLOAD_STORAGE=filesystem

Gemfile, Gemfile.lock, app/concerns/new_application_form.rb, app/controllers/admin/api/accounts_controller.rb, app/controllers/admin/api/application_plans_controller.rb, app/controllers/admin/api/applications_controller.rb, app/lib/apicast/provider_source.rb, app/lib/applications_controller_methods.rb, app/lib/backend_api_logic/routing_policy.rb, app/lib/signup/plans_with_defaults.rb, app/models/account.rb, app/models/backend_api_config.rb, app/models/cinstance.rb, app/models/service.rb, app/presenters/applications_index_presenter.rb, config/abilities/provider_member.rb, config/environments/test.rb, config/initializers/active-record-query-trace.rb, lib/developer_portal/app/controllers/developer_portal/admin/plans_widget_controller.rb, test/integration/user-management-api/applications_test.rb, test/unit/abilities/provider_member_test.rb, test/unit/finance/billing_strategy_test.rb
Check JIRA for issue description https://issues.redhat.com/browse/THREESCALE-11139
Note to reviewer. As an additional optimizations, I also fixed N+1 queries in this call. I removed the bullet ignores to see which one were triggered by the tests and removed 4 of the ignores. This had the side effect of also causing unrelated tests to fail, so I fixed some other N+1 queries as well.
So wherever you see `includes` changes, you can largely ignore them because these were changed to make tests pass and there should be no functional change there.
=> THREESCALE-11139 simplify application queries

config/application.rb
The upgrade from Rails 6.0 to 6.1 introduced a new `Link` header that is added to the response, with the full list of all assets:
https://guides.rubyonrails.org/6_1_release_notes.html#action-view-notable-changes
The `javascript_include_tag` and `stylesheet_link_tag` asset helpers generate a link header that gives hints to modern browsers about preloading assets. This can be disabled by setting `config.action_view.preload_links_header` to `false`.
On some pages this header becomes huge, making the total headers size > 4KB, and this may cause an issue with some proxies.
While this header might be used by browsers for optimizing the assets pre-loading, I think we can happily live without it.
Rails 7.1 and higher includes a fix that stops adding links …
=> Do not add Link header for preloading assets

Gemfile, Gemfile.lock
Since Ruby 3.0 `webrick` is not a default gem: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
>The following libraries are no longer bundled gems or standard libraries. Install the corresponding gems to use these features.
>- sdbm
>- webrick
>- net-telnet
>- xmlrpc
It is a dependency for Yabeda prometheus exporter: https://github.com/yabeda-rb/yabeda-prometheus?tab=readme-ov-file#usage
> WEBrick will be launched in separate thread and will serve metrics on `/metrics` path.
not reported
Check that Sidekiq starts successfully, and this error is not observed:
```
#<Thread:0x00007f533d636ef0 /opt/system/vendor/bundle/ruby/3.1.0/gems/yabeda-prometheus-mmap-0.1.1/lib/yabeda/promet …
```
=> Add webrick explicitly for Yabeda metrics

app/inputs/patternfly_input_input.rb, app/lib/fields/patternfly_form_builder.rb, app/views/provider/admin/user/personal_details/edit.html.slim, config/locales/en.yml
[THREESCALE-10399: Account Settings > Personal > Personal Details](https://issues.redhat.com/browse/THREESCALE-10399)
Without password (SSO sign up)
Without password (SSO sign up)
=> 🦋 Update Personal details page

app/views/provider/admin/accounts/new.html.slim, features/buyers/accounts/edit.feature, features/buyers/accounts/new.feature, features/old/accounts/accounts.feature, features/old/accounts/password_change.feature, features/old/accounts/personal_details.feature, features/provider/admin/accounts/new.feature
Fixing some forms and tests that were apparently broken.
**Before:**
**After:**
As for the tests, I think this change has modified the behavior:
https://github.com/3scale/porta/pull/3919/files#diff-6784bb890636509ec8f3fec49d3b6d3af3b7d777beb990cd4b46e8721e1a99baR15-R17
Now for the fields that are marked required  it is not possible to submit empty values, because the browser prevents it (due to `required` property on the HTML).
So, I removed some tests that are not relevant, and updated other that can still be applied.
=> Fix new provider form and UI tests

.circleci/config.yml
The Codecov bash uploader is deprecated, and (related or not) it was not working consistently lately. 
Te documentation and the migration path are documented here: https://docs.codecov.com/docs/deprecated-uploader-migration-guide
For this PR I've chosen the CircleCI Orb: https://circleci.com/developer/orbs/orb/codecov/codecov
-none-
Run the full CircleCI pipeline and ensure that the results are uploaded.
The latest version of the codecov CircleCI orb is 4.2.0. However, it fails with the following error:
```
[PYI-364:ERROR] Failed to load Python shared library '/tmp/_MEI0P0UrX/libpython3.11.so.1.0': dlopen: /lib64/libm.so.6: version `GLIBC_2.29' not found …
```
=> Update codecov uploader

app/controllers/buyers/impersonations_controller.rb, app/controllers/partners/sessions_controller.rb, app/models/sso_token.rb, features/old/buyers/impersonate.feature
The master portal allows impersonating users. To do this, it generates a token which expires in 10 minutes. This PR reduce the expiration time to 1 minute.
Read the Jira description and comments to get more details about this change.
[THREESCALE-11440](https://issues.redhat.com/browse/THREESCALE-11440)
The impersonation feature should work as usual.
=> THREESCALE-11440: Reduce impersonation token expiration time to 1 minute

config/initializers/sidekiq.rb
**NOTE:** merge https://github.com/3scale/porta/pull/3928 first, run the script in production, and then merge this PR.
Changes the default TTL of Sidekiq Batch keys from 30 days to 6 hours.
This is a temporary measure, because we need a proper way to fix the issue with this keys accumulation (either by fixing our code, or by getting rid of the gem).
In theory, once the batch is finished, the keys should get cleaned up, but they never are, for some reason. And very weird things happen with these batch keys in general :dizzy_face: 
https://issues.redhat.com/browse/THREESCALE-8124
Need to remove the constant and set it again, because just changing the value …
=> Change the Sidekiq Batch default TTL to 6h

app/controllers/finance/api/invoices_controller.rb, config/application.rb, config/initializers/paperclip.rb, lib/three_scale/middleware/presigned_downloads.rb, test/integration/finance/api/invoices_test.rb, test/integration/finance/invoice_download_test.rb
The middleware is installed before the `ActionDispatch::Static` middleware which actually serves the `public` folder.
It tries to use the same PATH_INFO pre-processing as `ActionDispatch::Static` so that we match against the same path it will be using later to serve files, thus avoiding path traversal issues. So we find the actual middleware instance.
If path is under the invoices directory, we require a valid signature. For that we use `Rails.application.message_verifier` to get a secure verifier for us.
To make the pre-signed URLs more user friendly, we put a human readable timestamp as `3scale-Expires` parameter. And since all signed information is just the timestamp and the path, we only pass the signature in the `3scale-Signature` query parameter, not the whole signed message. This …
=> [THREESCALE-11399] presigned invoice PDF downloads

app/javascript/src/ActiveDocs/ThreeScaleApiDocs.ts, app/javascript/src/Types/swagger.d.ts
Sets the "Send empty value" checkbox on the 3scale API docs to disabled state by default.
This was part of the wishlist on https://issues.redhat.com/browse/THREESCALE-9599
Open some request on 3scale API docs, and see that "Send empty value" is unchecked by default.
Just taken this from https://github.com/swagger-api/swagger-ui/issues/6505#issuecomment-1206651563 not sure whether it's right, but seems to be doing the trick.
=> Disable 'Send empty value' checkbox by default

app/controllers/admin/api/access_tokens_controller.rb, app/controllers/admin/api/personal/access_tokens_controller.rb, app/lib/api_authentication/by_access_token.rb, app/models/access_token.rb, app/representers/access_token_representer.rb, config/routes.rb, doc/active_docs/account_management_api.json, test/integration/api/access_tokens_test.rb, test/integration/api/personal/access_tokens_test.rb, test/integration/by_access_token_integration_test.rb, test/models/access_token_test.rb, test/unit/api_authentication/by_authentication_token_test.rb
This adds the backend to add an expiration date to access tokens.
The PR doesn't include the UI, I plan to do that in another PR.
https://issues.redhat.com/browse/THREESCALE-10245
Since there's no UI, you need to update the DB column manually to verify the behavior:
Query examples (MySQL):
```sql
update access_tokens set expires_at = NOW() where id = 3 
update access_tokens set expires_at = DATE_ADD(NOW(), INTERVAL 10 SECOND) where id = 3
update access_tokens set expires_at = DATE_ADD(NOW(), INTERVAL 2 HOUR) where id = 3
update access_tokens set expires_at = NULL  where id = 3 
```
=> THREESCALE-10245: Expirable access tokens

app/controllers/provider/admin/cms/visit_portal_controller.rb, app/helpers/cms/url_helper.rb, app/helpers/vertical_nav_helper.rb, app/lib/cms/signature.rb, config/routes.rb, features/developer_portal/cms_toolbar.feature, features/step_definitions/developer_portal/cms_toolbar_steps.rb, lib/developer_portal/app/controllers/developer_portal/access_codes_controller.rb, lib/developer_portal/app/views/shared/cms/_toolbar.html.slim, lib/developer_portal/lib/cms/toolbar.rb, test/integration/cms/toolbar_test.rb
This might replace https://github.com/3scale/porta/pull/3932
To avoid sending the CMS token in the URL, this PR signs it and sends the signature instead. Then it signs the token again when the request is received, if the signature matches, then it enables the CMS edit mode. This way the actual CMS token never leaves the server.
See the Jira description and comments for more info.
[THREESCALE-11439](https://issues.redhat.com/browse/THREESCALE-11439)
1. Go to Audiende -> Developer Portal -> Visit Portal
2. The developer portal should load correctly and the CMS toolbar should be visible
3. Copy the URL that includes the token
4. Open a private window and paste the URL
5. The dev. portal should …
=> THREESCALE-11439: Sign the CMS token

config/locales/en.yml, doc/active_docs/account_management_api.json
Making sure that the backslash `\` appears in the list of the valid characters for the application key:
That character is supported according to https://github.com/3scale/porta/blob/26743e8b360e4c8c7fcae370a721c3ed5e1f9b00/app/models/application_key.rb#L15-L17
=> Fix missing slash in app key allowed characters hint

app/assets/stylesheets/provider/_tables.scss, app/views/provider/admin/applications/show.html.slim, app/views/provider/admin/keys/_widget.html.erb
Not sure this is the right place to put this... but seems to be working as expected.
**Before:**
**After:**
It is especially noticeable when there is an error.
Also:
**Before:**
**After:**
=> Fix styles for application keys form

app/views/provider/admin/messages/inbox/show.html.erb
This is a tiny fix that removes the double title.
**Before:**
**After:**
none
=> Fix a duplicated header for inbox message

app/models/plan.rb, app/views/api/plans/_features.html.erb, doc/active_docs/account_management_api.json, test/integration/user-management-api/service_features_test.rb, test/test_helpers/xml_assertions.rb
The plan features API is a bit messy. For instance, AFAIK there's no endpoints to create or remove features for a plan, they must be created and deleted from the UI. The API only allows enabling or disabling features previously created from the UI. These are the endpoints:
1. GET /admin/api/account_plans/:account_plan_id/features(.:format)
- Returns the enabled features 
3. POST /admin/api/account_plans/:account_plan_id/features(.:format)
- Enables a feature
- It must receive `feature_id` as query param or form data
- Returns 200 on success
- Returns 409 when the feature was already enabled
- Returns 404 when the plan doesn't exist or the plan exists but the feature doesn't exists for that plan
5. DELETE …
=> THREESCALE-11498: API plans features

package.json, yarn.lock
[THREESCALE-11549: CVE-2024-21536 3scale-amp-system-container: Denial of Service [3amp-2.14]](https://issues.redhat.com/browse/THREESCALE-11549)
By specifying "resolutions" we force yarn to install that fixed version for 3rd party dependencies, even though in this case webpack has a loose dependency: `^2.0.3`.
=> 🧶 Fix `http-proxy-middleware` to `2.0.7`

test/unit/abilities/provider_any_test.rb
Fixing a bug introduced in https://github.com/3scale/porta/pull/3929
The test was randomly failing with:
```
User can show #<Cinstances::CinstancePlanChangedEvent:0x00007fcf9c94d3d8> but should not
/opt/ci/workdir/test/test_helper.rb:68:in `assert_cannot'
/opt/ci/workdir/test/unit/abilities/provider_any_test.rb:50:in `block (2 levels) in <class:ProviderAnyTest>'
```
Because... why would a Cinstance ID be provided to a Services IDs list? :upside_down_face: 
Obviously, the Cinstance ID may coincide with the service ID, causing a wrong behavior.
=> Fix incorrect member permission service

.circleci/config.yml, openshift/system/Dockerfile
The corresponding builder image is: https://github.com/3scale/system-builder/pull/42
=> THREESCALE-11575: Upgrade to CentOS stream9

spec/acceptance/api/proxy_spec.rb, test/unit/finance/billing_strategy_test.rb
This fixes the RSpec for API update, which has intermittent failures.
I believe this has been broken since https://github.com/3scale/porta/pull/3953/files
The issue is that any API spec test [compares](https://github.com/3scale/porta/blob/c982bdcb0f21444b75c7304680b011c31d355bd5/spec/api_helper.rb#L51) the API response (`response_body`) to the serialized version of the resource (`serialized`). And in this case the resource is Proxy, and the problem is that the `updated_at` in the serialized resource and in the response body do not coincide.
The reason is because the flow is:
1. the resource (proxy) is updated via API and a response is returned. This response has a timestamp, say `15:00:00`.
2. after the response is returned, the …
=> Fix RSpecs for Proxy API

.circleci/config.yml, features/support/capybara.rb
Oracle tests are slower, so sometimes the default 10 seconds is not enough to find for the desired HTML elements in Cucumber tests.
This PR increases the default wait timeout only for Oracle.
-
-
=> Increase Capybara timeout for Oracle tests

package.json, yarn.lock
[THREESCALE-11098: CVE-2024-29041 3scale-amp-system-container: express: cause malformed URLs to be evaluated [3amp-2.14]](https://issues.redhat.com/browse/THREESCALE-11098)
=> [CVE] Fix `express` version to 4.21.2

package.json, yarn.lock
[THREESCALE-11331: CVE-2024-45590 3scale-amp-system-container: Denial of Service Vulnerability in body-parser [3amp-2.14]](https://issues.redhat.com/browse/THREESCALE-11331)
Right now `body-parser@1.18.2` is used by "swgger-tools" and `body-parser@1.20.2` by "webpack-dev-server#express".
"swagger-tools" is dead and will never be updated so we need to set a resolution in our package.json to use only `body-parser@1.20.3`. According to its [changelog](https://github.com/expressjs/body-parser/blob/master/HISTORY.md) it should be safe to use it, despite the following warning:
```bash
$ yarn
yarn install v1.22.22
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "body-parser@1.20.3" is incompatible with requested version "body-parser@1.18.2"
```
=> [CVE] Fix `body-parser` version to 1.20.3

app/lib/signup/result_with_access_token.rb
Adds `Policy Registry API` scope to the initial token when creating a new tenant
[THREESCALE-9006](https://issues.redhat.com/browse/THREESCALE-9006)
1. Create a new tenant:
```
curl --request POST \
--url 'http://master-account.3scale.localhost:3000//master/api/providers?access_token=[MASTER_TOKEN]' \
--header 'Content-Type: application/json' \
--data '{
"org_name": "API provider",
"username": "api-user",
"password": "p",
"email": "test-api-user@redhat.com",
"redirect_url": "http://master-account.3scale.localhost:3000/buyers/accounts"
}'
```
2. The new provider should have an access token called `Administration` with the `Policy Registry API` scope enabled:
```
$ bundle exec rails c
Loading …
```
=> THREESCALE-9006: Add `policy_registry` scope to the initial token

features/buyers/accounts/applications/new.feature, features/support/capybara_extensions.rb
https://issues.redhat.com/browse/THREESCALE-11585
Reason: Capybara tries to click the second select but the first one is still open somehow (see image below). Rerunning the test will make it pass in Circleci. It doesn't fail locally.
=> Try to fix flaky tests involving multi-dropdown forms

app/controllers/provider/admin/account/users_controller.rb, app/helpers/patternfly_components_helper.rb, app/helpers/users_helper.rb, app/presenters/provider/admin/account/users_index_presenter.rb, app/views/provider/admin/account/users/index.html.slim, config/locales/en.yml, features/old/accounts/users.feature, features/provider/admin/account/invitations.feature, features/provider/admin/account/users/index.feature, features/step_definitions/custom_web_steps.rb, features/step_definitions/provider_steps.rb, features/step_definitions/security/generic_steps.rb, features/step_definitions/session_steps.rb, features/step_definitions/user_steps.rb, test/integration/provider/admin/account/users_controller_test.rb
[THREESCALE-9873: Account Settings > Users > Listing](https://issues.redhat.com/browse/THREESCALE-9873):
* [THREESCALE-9875: Add a toolbar to the table](https://issues.redhat.com/browse/THREESCALE-9875)
Before:
After:
=> 🦋 Update Account > Users table

app/controllers/provider/admin/user/access_tokens_controller.rb, app/javascript/packs/expiration_date_picker.ts, app/javascript/src/AccessTokens/components/ExpirationDatePicker.scss, app/javascript/src/AccessTokens/components/ExpirationDatePicker.tsx, app/models/access_token.rb, app/presenters/provider/admin/user/access_tokens_new_presenter.rb, app/views/provider/admin/user/access_tokens/_form.html.slim, app/views/provider/admin/user/access_tokens/edit.html.slim, app/views/provider/admin/user/access_tokens/index.html.slim, app/views/provider/admin/user/access_tokens/new.html.slim, config/locales/en.yml, features/provider/admin/user/access_tokens.feature, spec/javascripts/AccessTokens/components/ExpirationDatePicker.spec.tsx
After we merged https://github.com/3scale/porta/pull/3939 now we want to update the Access Tokens screens to add a new field for the expiration date. For this, I created a new React component based on what Github does:
- A select input with the next options:
- Expires in 7 days
- In 30 days
- In 60 days
- In 90 days
- Custom date
- A calendar appears to select the desired date
- No expiration
- An warn is shown to advise the user to set an expiration date for security reasons
[THREESCALE-10245](https://issues.redhat.com/browse/THREESCALE-10245)
Just set the an expiration date when creating a token and verify the data is correctly stored in DB and is properly shown in `#index` and `#edit` …
=> THREESCALE-10245: access tokens expiration UI

app/lib/three_scale/oauth2/client.rb, app/models/authentication_provider.rb, app/models/authentication_provider/auth0.rb, app/models/authentication_provider/keycloak.rb, app/models/proxy_rule.rb, app/models/web_hook.rb, app/views/provider/admin/account/authentication_providers/_keycloak.html.slim, app/views/provider/admin/account/authentication_providers/form/_auth0.html.slim, app/views/provider/admin/account/authentication_providers/form/_form.html.slim, app/views/provider/admin/account/authentication_providers/form/_keycloak.html.slim, app/views/provider/admin/account/authentication_providers/new.html.slim, app/views/provider/admin/authentication_providers/_auth0.html.slim, app/views/provider/admin/authentication_providers/_keycloak.html.slim, config/locales/en.yml, features/provider/admin/account/authentication_providers/edit.feature, features/provider/admin/account/authentication_providers/new.feature, features/provider/admin/authentication_providers/edit.feature, test/factories/authentication_provider.rb, test/integration/admin/api/account/authentication_providers_controller_test.rb, test/integration/admin/api/authentication_providers_controller_test.rb, test/integration/provider/admin/account/authentication_providers_controller_test.rb, test/unit/authentication_provider_test.rb, test/unit/presenters/oauth_flow_presenter_test.rb
When creating an SSO integration for the admin portal (`/p/admin/account/authentication_providers/new`), if the realm/site URL has leading/trailing spaces, the creation, and later viewing this integration throws an Internal Error (status code 500).
In dev mode the error is:
```
bad URI(is not URI?): "https://rh-sso.example.com/auth/realms/demo " 
def build_client
@client = ThreeScale::OAuth2::Client.build(authentication_provider).tap do |new_client|
new_client.client.connection.ssl.verify = authentication_provider.ssl_verify_mode
end
rescue ::ThreeScale::OAuth2::KeycloakClient::MissingRealmError
@client = NullClient.new
```
Find more details below.
https://issues.redhat.com/browse/THREESCALE-11609
**Verification …
=> THREESCALE-11609: Fix whitespaces in keycloak realm

app/services/finance/charging_service.rb, app/workers/service_discovery/create_service_worker.rb, test/test_helper.rb, test/workers/backend_delete_application_worker_test.rb, test/workers/service_discovery/create_service_worker_test.rb, test/workers/web_hook_worker_test.rb
In the latest alpha Service discovery feature doesn't work - the service is discovered through annotations, but not imported.
The sidekiq logs show the following error:
```
2025-01-23T05:40:56.608Z pid=7 tid=63sh3 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[2,"tools","go-httpbin",2],"class":"ServiceDiscovery::CreateServiceWorker","jid":"00dd5087d7c2cc369aade997","created_at":1737610803.388993,"enqueued_at":1737610856.6016831,"error_message":"wrong number of arguments (given 2, expected 1; required keywords: cluster_namespace, cluster_service_name)","error_class":"ArgumentError","failed_at":1737610803.3969626,"retry_count":1,"retried_at":1737610826.7337837}}
2025-01-23T05:40:56.608Z pid=7 tid=63sh3 WARN: …
```
=> THREESCALE-11624: Fix keyword argument in Service Discovery import

config/webpack/rules.js
When Sass was upgraded by Snyk in https://github.com/3scale/porta/pull/3977 a bunch of deprecation warnings appeared when running `bundle exec rake webpack:dev`
This PR silences them until (if) we address them.
=> Silence deprecation warnings in Sass

app/views/api/metrics/_form.html.slim, app/views/provider/admin/backend_apis/metrics/_form_edit.html.slim, app/views/provider/admin/backend_apis/metrics/edit.html.erb, app/views/provider/admin/backend_apis/metrics/edit.html.slim, features/provider/admin/backend_apis/metrics/delete.feature, test/integration/provider/admin/backend_apis/metrics_controller_test.rb
It started as a desire to fix the Delete button style, but ended up applying PF4 styles by reusing an existing form.
Before:
After:
- none -
=> Fix styles on the Backend API metric Edit form

app/controllers/api/applications_controller.rb, app/views/shared/applications/_listing.html.slim, features/api/services/applications/index.feature, features/step_definitions/table_steps.rb
Fixes the missing **Plan** column on the application listing.
Before:
After:
not registered
View a list of applications under a service that has multiple plans, and make sure that there is a **Plans** column.
See comments inline
=> Fix a missing Plans column on the applications list

app/presenters/provider/admin/account/users_index_presenter.rb, features/support/capybara.rb
Cucumber tests sometimes fail with the following error:
https://app.circleci.com/pipelines/github/3scale/porta/30739/workflows/b0f7ecdd-5c07-433d-a059-c93b7ae75538/jobs/344495/tests
```
Message:Tables were not identical:
|     Name          |     Email                |     Role   |     Permission groups | (+)                  |
|     Albert Wesker |     wesker@umbrella.corp |     admin  |     Unlimited access  | (+) Personal details |
| (-) honk          | (-) honk@umbrella.corp   | (-) member | (-) -                 | (+)                  |
|     Ada Wong      |     awong@umbrella.corp  |     member |     -                 | (+) Delete\nEdit     |
| (+) honk          | (+) honk@umbrella.corp   | (+) member | (+) -                 | (+) Delete\nEdit …
```
=> Fix cucumber tests for provider accounts users list

app/assets/javascripts/provider.js, app/assets/javascripts/provider/utils.js.coffee
This function was called by the CMS intro tabs, here:
https://github.com/3scale/porta/pull/3773/files#diff-89e68fd82864e95731204d1b91e2c3d400d39eb941e25795e5a488b5c867d627L23
It was removed because it was totally unnecessary, but the declaration of `setLocationHash` was left behind.
=> ⚰️ Remove `provider/utils.js`

.circleci/config.yml
This is in the hope of debugging the recurring issue with cucumber steps failing with no failed tests reported or visible.
We can also run this as a background step but this is cleaner and less data. So lets see if it works.
=> number of OOM killed processes after tests

app/models/fields_definition.rb, features/developer_portal/admin/applications/extra_fields.feature, features/old/accounts/buyers/account_fields.feature, features/step_definitions/provider_steps.rb, features/support/parameter_types.rb, lib/developer_portal/app/controllers/developer_portal/accounts/invitee_signups_controller.rb, lib/developer_portal/app/controllers/developer_portal/admin/account/personal_details_controller.rb, lib/developer_portal/app/controllers/developer_portal/admin/account/users_controller.rb, lib/developer_portal/app/controllers/developer_portal/admin/accounts_controller.rb, lib/developer_portal/app/controllers/developer_portal/admin/applications_controller.rb, lib/developer_portal/app/controllers/developer_portal/base_controller.rb, lib/developer_portal/app/controllers/developer_portal/signup_controller.rb, test/integration/developer_portal/base_controller_test.rb, test/unit/developer_portal/base_controller_test.rb
A provider can create extra fields for `Account`, `User` and `Cinstance`. In the developer portal, these fields are hidden by default, but we can't control what clients do with templates, also a form can be easily tampered using browser dev tools. If the user manages to send read-only fields in a form, porta stores them in the DB.
This is a draft because I'm not 100% convinced this is the proper way to solve the problem. I was looking for a way to have a unified solution in one place but I could only think of approaches requiring ActiveRecord methods overwriting or middledware, so I manually edited all controllers to manually remove all read-only fields from parameters. I don't like it but it's the option I dislike the least. Also please read …
=> THREESCALE-9751: Ignore read only fields

app/lib/pdf/styles/base.rb
Generating invoce PDF fails on Fedora 41 becuase the default path for the Liberation Sans font have been moved
Before: `/usr/share/fonts/liberation-sans`
https://packages.fedoraproject.org/pkgs/liberation-fonts/liberation-sans-fonts/fedora-40.html
After: `/usr/share/fonts/liberation-sans-fonts`
https://packages.fedoraproject.org/pkgs/liberation-fonts/liberation-sans-fonts/fedora-41.html
This adds the new path to the list so it can find the font in the new location
=> Add new path for Liberation sans font

.eslintrc, jest.config.js, spec/acceptance/api/service_spec.rb, spec/javascripts/AccessTokens/components/ExpirationDatePicker.spec.tsx, spec/javascripts/customJestMatchers.ts
Fixing some intermittently failing tests.
See comments inline.
none
I was also investigating the following issue:
I believe the reason this happens is that when the component is loaded the `today` timestamp is fixed, and when the options are selected from the dropdown, the originally fixed time is applied. The test, however, calculates the expected timestamp based on the **current** time, so there might be a discrepancy.
This does not happen too often though, probably only when the component is loaded at the end of the second.
Some of the solutions that we can apply if it starts bothering us:
1. Keep the current implementation, and in the test, instead of …
=> Fixing flaky tests

Gemfile, Gemfile.lock
We need to update `braintree` or it will stop working at June 30, 2025.
This PR updates `braintree` and adds `libxml-ruby` which allegedly makes Braintree faster. It also updates `activemerchant`, since we were using an old version which wasn't compatible with the newer `braintree` versions
[THREESCALE-11641](https://issues.redhat.com/browse/THREESCALE-11641)
I tried this locally, for Braintree and also for Stripe, since I updated `activemerchant`:
1. Try to add an invalid CC
2. Add a valid CC
3. Make a failed payment
4. Make a successful payment
It all worked fine for me.
**Useful links**:
- https://developer.paypal.com/braintree/docs/guides/credit-cards/testing-go-live/ruby#valid-card-number …
=> THREESCALE-11641: Update braintree

app/controllers/admin/api/services/proxy/policies_controller.rb, app/controllers/api/services_controller.rb, app/decorators/service_decorator.rb, app/helpers/vertical_nav_helper.rb, app/javascript/src/Users/utils/index.tsx, app/models/admin_section.rb, app/presenters/service_actions_presenter.rb, config/abilities/provider_admin.rb, config/abilities/provider_any.rb, config/abilities/provider_member.rb, features/menu/context_selector.feature, features/provider/dashboard/widgets.feature, spec/javascripts/Users/components/PermissionsForm.spec.tsx, spec/javascripts/Users/utils/utils.spec.ts, test/decorators/service_decorator_test.rb, test/integration/admin/api/services/proxy/policies_controller_test.rb, test/integration/user-management-api/services/proxy/policies_test.rb, test/unit/abilities/provider_admin_test.rb, test/unit/abilities/provider_any_test.rb, test/unit/abilities/provider_member_test.rb, test/unit/presenters/service_actions_presenter_test.rb, test/unit/user/permissions_test.rb
After fixing member permissions per service in https://github.com/3scale/porta/pull/3929, policy registry operations are not working as expected. This PR fixes it.
This PR changes the permission model, and now the `policy_registry` is considered a "service-level" permission, so it can be applied to a subset of serviced, or all services.
This also affects the UI.
1. Member user permissions:
2. Dashboard for the user that only has `policy_registry` permission for a single service:
3. Product details for a user with `policy_registry` permission:
This PR also fixes an issue reported in https://issues.redhat.com/browse/THREESCALE-6482: when the member user only has Analytics permission, they can see "Explore all Products" link on the dashboard, and also …
=> THREESCALE-11644: Fix policy registry permission (and THREESCALE-6482)

script/yarn/package-lock.json
We use this file for a single purpose - to instruct the productization build system to prefetch the `yarn` dependency (of the version that is specified), so we can install it with `npm` in a hermetic (with no internet access) build.
There were some issues with the previous version of the file when using with the new dependencies prefetching system (it was still trying to access internet, because of the link), but updating this `package-lock.json` file resolves it.
There were no manual changes, just removing `package-lock.json` and running `npm install` again generated this new version of the file.
=> Update yarn package-lock

app/javascript/src/ActiveDocs/components/SwaggerUpdateHelpAction.tsx, app/lib/system/deploy.rb, config/locales/en.yml, test/unit/helpers/application_helper_test.rb, test/unit/lib/system/deploy_test.rb
I noticed some broken link to the 3scale product documentation, and tried to fix it.
https://issues.redhat.com/browse/THREESCALE-9306
Check that all links point to existing pages in the 3scale product documentation.
=> THREESCALE-9306: Update broken documentation links in the admin portal

app/events/accounts/account_created_event.rb, app/events/application_related_event.rb, app/events/messages/message_received_event.rb, app/lib/event_store/repository.rb, config/abilities/provider_any.rb, test/unit/abilities/provider_any_test.rb, test/unit/abilities/provider_member_test.rb
Clients complain their inboxes are being spammed with non-relevant emails about notifications they don't care about because their users don't have permissions to manage the services the notifications are about.
We already implement a system to filter such notifications, this is how it works:
1. An event happens
2. It's listened by `PublishNotificationEventSubscriber`:
https://github.com/3scale/porta/blob/a8979588f3cde863765813cce1ca40974cb863a2/app/lib/event_store/repository.rb#L117-L167
https://github.com/3scale/porta/blob/a8979588f3cde863765813cce1ca40974cb863a2/app/lib/event_store/repository.rb#L186-L188
3. A `NotificationEvent` is created:
https://github.com/3scale/porta/blob/25fa9bc53bdd3eeb8f2a9c8e882f771c85c3c3cb/app/subscribers/publish_notifi …
=> THREESCALE-10758: Filter email notifications by service

Gemfile.lock
We're locking to bundler `2.2.25`, and it's deprecated.
We could upgrade to the latest bundler as well, but the version that is currently installed from RPM in the build image (`ubi9`) is `2.3.27`, and it's easier to use that version, because `hermeto` (depnedencies fetcher in productization) doesn't fetch bundler specified in `Gemfile.lock` in the prefetch stage, so we'd need to pull it manually to some Nexus repo (which I get might get discontinued at some point).
-none-
=> Upgrade bundler to 2.3.27

app/controllers/provider/sessions_controller.rb
Basically the problem is the impersonation controller redirects directly to the sessions controller bypassing the login screen, so the recaptcha params are not set, which causes the challenge to fail.
Same thing happens with open ID. From the login screen we link to an external provider, which ends up querying our sessions controller directly, so again no recaptcha params set.
In a previous PR (https://github.com/3scale/porta/pull/4050) I tried creating a new route only for impersonation, but then I realized OpenID connections were also failing. So I discarded that approach and now I'm simply enforcing recaptcha when the request is POST and bypassing it otherwise.
I don't really like the solution but I think is the less disrupting approach I can …
=> THREESCALE-11735: Impersonation and OpenID confilcts with recaptcha

.circleci/config.yml
> We have reverted a change that prevented dnsmasq from binding port 53 on 127.0.0.x address. This should fix the main cause of the issue you reported.
> 
> This change had been put in place to add a DNS resolver to 127.0.0.11, as it had previously been hardcoded to this address and some jobs relied on a dns server being available there.
> 
> I\u2019ve reviewed your build to check for any further potential issues on V2 and noticed that your script also relies on this hardcoded address to replace the resolver with dnsmasq. In order to support v2, please could you update your job\u2019s sed command below
> 
> `sudo sed -c -i".bak" 's/[127.0.0.11](http://127.0.0.11/)$/[127.0.0.1/](http://127.0.0.1/)' /etc/resolv.conf `
>
> with
> 
> `sudo sed -c -i".bak" 's/^nameserver.*/nameserver …
=> fix circleci DNS setup for v2 executors

app/javascript/src/Policies/components/PolicyConfig.tsx, package.json, yarn.lock
In order to update `nanoid` (https://github.com/3scale/porta/pull/3968) I had to update `react-jsonschema-form@1.8.1` to `@rjsf/core@5.24.1`. This package is used from the Policies screen. We have the policies defined in JSON schema format and this package transforms then into HTML forms. The package includes a validator, which last version is V8, but I had to use the deprecated V6 version because our `policies.json` was being considered inavalid by V8, check [this comment](https://github.com/3scale/porta/pull/3968/files#r1920249458) where I explain the issue.
After suggesting some changes to our `policies.json`, a new version has been released which solves the problem, so we are now free to update to the V8 validator.
**Which issue(s) this PR …
=> THREESCALE-11725: Update JSON schema validator to V8

app/workers/delete_all_stale_objects_worker.rb, test/test_helpers/n_plus_one_control.rb, test/workers/delete_all_stale_objects_worker_test.rb
Testing showed that deleting without batching these objects is acceptable and I suspect more efficient than batching. Because batching will basically call the same select query many times and my gut feeling is that at some point that would become much more stressful to the database.
originally introduced with #3958
=> THREESCALE-11764 avoid unnecessary batching when deleting messages

app/lib/backend/storage_rewrite.rb, test/unit/backend/storage_rewrite_test.rb
If the Backend redis is wiped, the data can be repopulated from System via the rake task backend:storage:rewrite, however, this does not push the information about the enabled alert levels (levels of usage at which the notifications are going to be sent).
https://issues.redhat.com/browse/THREESCALE-11808
- Wipe backend redis
- Set some usage rules for alert levels
- run `bundle exec rake backend:storage:rewrite`
Before the fix, there would be no `alerts/service_id:123/allowed_set` entries (where `123` is a sample service ID)
After the fix, there will be a `alerts/service_id:123/allowed_set` entry for every service.
=> THREESCALE-11808: Update alert levels in backend:storage:rewrite

app/lib/three_scale/models.rb, config/environments/test.rb, features/step_definitions/usage_limit_steps.rb, features/support/test_helpers.rb, lib/three_scale/tenant_id_integrity_checker.rb, test/test_helpers/retries.rb, test/unit/cms/portlet_test.rb, test/unit/fields_definition_test.rb, test/unit/indices/indexing_test.rb, test/unit/models_test.rb, test/unit/three_scale/search_test.rb
UPDATE: decided to keep `config.cache_classes` but filter out test models when obtaining them. 29b0e82f46d93dc0fc1cfaffa653eeddbaca1116 can be reviewed separately, it is not related to filtering test models but it made me some troubles so I thought to have them more stable.
Presently tests that iterate over all ActiveRecord descendants intermittently fail when some test ActiveRecord models were created before running them.
This is most prominently the DeleteObjectHierarchyWorkerTest.
Here we enable clearing of descendant objects and clear the test classes in a way compatible with latest Rails 8.0
An alternative approach would be to filter them out within `ThreeScale::Models#all_models_with_a_table` in `app/lib/three_scale/models.rb`.
I'm not sure which approach would be preferable. Let me …
=> make more reliable the tests going over all AR descendants

app/workers/delete_object_hierarchy_worker.rb, test/workers/delete_object_hierarchy_worker_test.rb
Increase single loop duration to 25 seconds.
Cache records to avoid the need to reload them from database for each associated object.
You can review by commit.
=> THREESCALE-11766 background deletion optimize by caching records

lib/developer_portal/app/views/developer_portal/docs.html.liquid, public/oauth2-redirect.html
Adds `/oauth2-redirect.hml` globally to all portals, implementing option 3 of this list of suggestions: https://issues.redhat.com/browse/THREESCALE-11160?focusedId=26750532&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26750532
The content of the file is taken from https://raw.githubusercontent.com/swagger-api/swagger-ui/refs/tags/v5.12.3/dist/oauth2-redirect.html
Adding `oauth2RedirectUrl: oauth2RedirectUrl` is required so that the solution works from any page. Without it, the solution would work if the page where the spec is rendered is "simple", like `/docs`, but in case it's something more complex like `/api/docs/echo`, the redirect URL would be `/api/docs/oauth2-redirect.hml` which will obviously fail.
I didn't …
=> THREESCALE-11160: Add oauth2-redirect.hml globally

app/helpers/vertical_nav_helper.rb, test/helpers/vertical_nav_helper_test.rb
This is to solve [THREESCALE-9037|https://issues.redhat.com/browse/THREESCALE-9037]. In fact, after https://github.com/3scale/porta/pull/3938 was merged, the user with no "portal" permission would not be able to go check the portal in "preview" mode, because clicking on "Visit Portal" would bring them to "Access Denied" page, because the `VisitPortalController` checks for this permission.
So, as such a user cannot use the link, I believe it's best to just hide it.
I think ideally, we should still allow the user to see the link and use it, but only allow them to see the published version. But I guess that feature would be more involved, and we can add it in case someone requests. …
=> THREESCALE-9037: Do not show 'Visit Portal' if it won't work due to lack of permissions

app/views/provider/admin/user/notification_preferences/show.html.slim, features/notification_preferences/update.feature, features/step_definitions/notification_preferences_steps.rb, features/support/paths.rb
This PR fixes a but that prevented disabling all notification preferences via UI by adding a hidden input. It's not a problem adding an empty string there, because empty values are going to be [rejected](https://github.com/3scale/porta/blob/master/app/models/notification_preferences.rb#L10).
https://issues.redhat.com/browse/THREESCALE-11844
Go to the **Notification Preferences** page, disable all notifications, press the submit button.
Make sure that the preferences are updated successfully.
=> THREESCALE-11844: Allow disabling all notifications via UI

app/views/provider/admin/account/users/index.html.slim
[THREESCALE-11810: Table element lost it's id="users"](https://issues.redhat.com/browse/THREESCALE-11810)
=> adds id for tests to users table

app/models/message.rb, app/views/buyers/accounts/_account_details.html.slim, test/unit/message_test.rb
We are currently sending email notifications to buyers even when they are suspended. This PR fixes that.
It also removes a UI button to directly send a message to a suspended buyer, since it won't receive the message after this PR.
https://issues.redhat.com/browse/THREESCALE-11845
1. Suspend a buyer:
```ruby
buyer = Account.find(id)
buyer.marked_for_suspension = true
buyer.suspend
```
2. Perform any action that leads to an email notification. For instance, change an application plan, or just send a message to the buyer/all buyers.
3. Before, email was sent to the buyer; now, email is not sent.
=> THREESCALE-11845: Skip notifications to inactive buyers

app/controllers/provider/admin/cms/visit_portal_controller.rb, app/lib/authenticated_system.rb, app/lib/cms/settings.rb, app/lib/cms/signature.rb, app/models/settings.rb, config/initializers/filter_parameter_logging.rb, features/developer_portal/cms_toolbar.feature, features/step_definitions/developer_portal/cms_toolbar_steps.rb, lib/developer_portal/lib/cms/toolbar.rb, test/integration/cms/toolbar_test.rb, test/unit/models_test.rb
In a previous PR we started using the cms token signature instead of the cms token itself in order to enable or disable the CMS Edit mode: https://github.com/3scale/porta/pull/3938
Once we are using the signature, there's no need to keep using the cms token at all. This PR uses the account id instead of the cms token to sign the request.
https://issues.redhat.com/browse/THREESCALE-11466
Everything should work as before:
1. Go to Audiende -> Developer Portal -> Visit Portal
2. The developer portal should load correctly and the CMS toolbar should be visible
3. Copy the URL that includes the token
4. Open a private window and paste the URL
5. The dev. portal should load correctly and the toolbar …
=> THREESCALE-11466: Remove cms token

Gemfile, Gemfile.lock, app/lib/three_scale/semantic_form_builder.rb, app/views/admin/fields_definitions/index.html.erb, app/views/buyers/invoices/index.html.erb, app/views/finance/provider/invoices/index.html.slim, app/views/finance/provider/log_entries/index.html.erb, app/views/finance/provider/shared/_line_item.html.erb, app/views/finance/provider/shared/_payment_transaction.html.erb, app/views/provider/admin/account/invoices/index.html.slim, app/views/provider/admin/cms/groups/index.html.erb, app/views/provider/admin/cms/sections/index.html.erb, config/locales/en.yml, features/step_definitions/finance/invoicing_steps.rb
The features implemented by these gems were removed from Rails at some point and extracted into separate gems. But I think it's better to get rid of them, because they are causing some dependencies issues when upgrading Rails to 7.1, and might cause more in future.
1. `record_tag_helper` transforms
```
<%= content_tag_for(:tr, @article) do %>
```
into 
```
<tr id="article_1234" class="article">
```
so, adds a class, and the ID of the element.
See more at https://github.com/rails/record_tag_helper
I think it's unnecessary, and can be simply removed. I replaced some occurrences with a plain `tr` tag, and for others, that required adding something extra, like an ID, I used `content_tag`, which is very similar to `content_tag_for`, just that it does not …
=> Remove obsolete gems

app/models/backend_api.rb, test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb, test/unit/apicast/proxy_rules_source_test.rb
There was no defined order on backend APIs, so the order was defined by the database, and it is error-prone and unpredictable.
https://issues.redhat.com/browse/THREESCALE-11879
The mapping rules should be ordered by position at least in:
- the configuration JSON, found at `/apiconfig/services/{SERVICE_ID}/proxy_configs?environment=staging`
- on the backend API mapping rule page: `/p/admin/backend_apis/{BACKEND_API_ID}/mapping_rules`
- in the API responses, e.g. `/admin/api/backend_apis/{BACKEND_API_ID}/mapping_rules.json`
=> THREESCALE-11879: Order backend API mapping rules

app/models/notification_preferences.rb, app/models/user.rb, features/buyers/accounts/managing.feature, features/developer_portal/admin/applications/plan_change.feature, features/developer_portal/signup.feature, features/notifications/signup.feature, features/old/finance/reporting/buyer.feature, features/old/sort_out_these/providers/usage_reports.feature, features/step_definitions/notification_preferences_steps.rb, test/factories/notification.rb, test/integration/notifications_test.rb, test/integration/provider/admin/applications/applications_controller_test.rb, test/test_helpers/provider.rb, test/unit/logic/plan_changes_test.rb, test/unit/observers/cinstance_observer_test.rb, test/unit/observers/post_observer_test.rb, test/unit/pdf/report_test.rb, test/unit/user_test.rb, test/workers/delete_object_hierarchy_worker_test.rb, test/workers/process_notification_event_worker_test.rb
It's good to add some default notification preferences to the DB when a new user is created. This won't change the behavior since porta builds some in-memory notifications when there's no record in the DB. The difference is that having a record in the DB allows us to obfuscate it in staging, so we have a way to disable notifications for all provider users in that environment.
In this PR, I also modified the default notification preferences. Before, the only preferences disabled were:
```
post_created
weekly_report
daily_report
```
Now, everything is disabled. Except:
```
limit_alert_reached_provider
limit_violation_reached_provider
account_plan_change_requested
application_plan_change_requested
service_plan_change_requested
invoices_to_review …
```
=> THREESCALE-10168: Add default notification preferences to new users

app/controllers/admin/api/personal/notification_preferences_controller.rb, app/models/notification_preferences.rb, app/representers/notification_preferences_representer.rb, config/locales/en.yml, config/routes.rb, doc/active_docs/account_management_api.json, test/integration/admin/api/personal/notification_preferences_controller_test.rb, test/models/notification_preferences_test.rb
Update personal notification preferences via API.
It's still to be decided whether we need to support updating preferences of **another** user (e.g. an admin to be able to change preferences of a member).
https://issues.redhat.com/browse/THREESCALE-1643
TBD
=> THREESCALE-1643: Update notification preferences via API

app/workers/suspend_inactive_accounts_worker.rb, test/workers/suspend_inactive_accounts_worker_test.rb
The next change caused a regression that broke `SuspendInactiveAccountsWorker`:
https://github.com/3scale/porta/commit/34857265eac8620ec1122be2b87a42c61ab49055#diff-b3ff5e3df6b875e9ecfde657ae21de84f4f43c942d3232761ed550cf0eecbce0
PR: https://github.com/3scale/porta/pull/3063
When creating a new account, the domain is generated from the name. In the process, the `parameterize` method is called:
https://github.com/3scale/porta/blob/34857265eac8620ec1122be2b87a42c61ab49055/app/lib/signup/domains_builder.rb#L18
This caused errors. When `org_name` was entirely composed of special characters, the resulting domain was empty, which prevented creating the account. In order to improve that, https://github.com/3scale/porta/pull/3063 adds a new validation to …
=> `SuspendInactiveAccountsWorker`: Make it iterable

test/workers/suspend_inactive_accounts_worker_test.rb
A follow-up for https://github.com/3scale/porta/pull/4119 :sweat_smile:
=> Fix a unit test for SuspendInactiveAccountsWorker for invalid accounts

app/javascript/src/BackendApis/components/BackendSelect.tsx, app/javascript/src/Common/components/SelectWithModal.tsx, features/api/backend_usages/new.feature, features/provider/admin/applications/new.feature, features/step_definitions/dashboard_steps.rb
Fixes the search for backend select modal in "Add backend usage" form.
https://issues.redhat.com/browse/THREESCALE-10684
1. Create > 20 backend APIs.
2. Go to `/apiconfig/services/2/backend_usages/new` (or use another service ID)
3. Expand the Backend select
4. Try searching, the results should be filtered.
5. Click on "View all backends"
6. In the modal, try:
- searching by keyword (e.g. "product")
- moving through the pages
- clicking on "x" clear button in the input
- closing the modal (or clicking Cancel) and opening again - unfiltered results should be shown
- selecting a value
=> THREESCALE-10684: Fix backend modal search

Gemfile.lock
io-console 0.8.0 fails to compile on Fedora 42.
Since it is only a dev dependency, I think better to move it back to the
default gem version coming with Ruby 3.1
We can update it to the default version of next ruby we upgrade to.
=> compatibility fix for Ruby 3.1 vs Fedora42 gcc

config/examples/settings.yml, config/initializers/captchas.rb
This is the situation with ReCAPTCHA right now:
- All classic keys are going to be migrated to ReCAPTCHA enterprise at Google Cloud by the end of 2025. That means all keys for our clients on premises, also SaaS keys.
- There are no code changes required. I verified this: I migrated our test key `Test recaptcha 3` to my Google Cloud account and everything works for us. So both SaaS and onpremises will continue to work after the end of 2025.
- At some point in the future, Google will probably stop supporting classic key pairs in their API, but there is no deadline for this AFAIK. If this happens, we should support enterprise keys to not disrupt our users.
- While investigating this, I found adding such support for enterprise keys is almost trivial, so …
=> THREESCALE-11640: Add support for ReCAPTCHA enterprise

.github/workflows/container-image-buildx.yml
I'm not sure whether `workflow_dispatch` workflows require input types now but this one fails presently without this.
=> workflow_call requires inputs types now

config/examples/sandbox_proxy.yml
Porta uses this override value to get address of the test proxy. Which is useful for local dev runs where one wants to access the API from UI.
For example go through the provider initial setup wizard and go through it. Without proper value, accessing the API will fail at the end of the wizard.
https://github.com/3scale/porta/blob/4ee6a660307a740ad4df6c1368ded6aabeff5405/app/services/proxy_test_service.rb#L92-L103
=> Fix default and document the purpose of the setting

app/lib/backend/model_extensions/usage_limit.rb, config/application.rb
In the upgrade to [Rails 7.1](https://github.com/3scale/porta/pull/4089), there was something that I missed. Probably because it's not in the generic release notes for [7.1](https://guides.rubyonrails.org/7_1_release_notes.html).
The change is that now order of the `after_commit` callbacks is as it is defined in the code, while prior to 7.1 the order was reversed. See https://guides.rubyonrails.org/active_record_callbacks.html#transactional-callback-ordering
This specifically affected the callbacks on usage limits creation, where two callbacks are defined (and note also the comment that proves the privious statement):
https://github.com/3scale/porta/blob/db92cc6ebe910229de333015975b204ced868273/app/lib/backend/model_extensions/usage_limit.rb#L11-L13 …
=> THREESCALE-11945: Fix the issue with after_commit transaction callbacks
