config/examples/database.yml

Database for dev environment should have its own name:
`3scale_system_production` -> `3scale_system_development`

Fixes Dev database name in database.yml

---

app/views/api/metrics/index.html.slim

Rewords the description of Metrics to make it more explicit that custom metrics are not included in _Hits_.
https://issues.jboss.org/browse/THREESCALE-1206

Rewords metrics description

---

app/views/notification_mailer/cinstance_expired_trial.html.slim
app/views/notification_mailer/cinstance_expired_trial.text.erb
test/mailers/notification_mailer_test.rb

`admin_buyers_application_url` should be from an `application` and not from an `account`.

[Bugfix] admin_buyers_application_url with an @application as param

---

README.md

Fixes broken badges in README.md 
after moving the 3scale/porta repo under the "Open Source" section in code climate, the project IDs changed, so the badges URLs have also changed.
copy pasted from https://codeclimate.com/github/3scale/porta/badges#test-coverage-markdown
(new repo, under Open Source)

Fix code climate badges

---

CONTRIBUTING.md

fixes https://github.com/3scale/porta/issues/54
It is meant to help contributors to know about our GPG signed commits requirement and follow the guides they may need to make it possible.

[Documentation] Point to Github links to sign with GPG

---

app/views/provider/admin/dashboards/widgets/_service_integration_errors.html.slim

Related to [THREESCALE-1331](https://issues.jboss.org/browse/THREESCALE-1331) and https://github.com/3scale/porta/pull/49
Now it points to a clean URL:
So `services/2/errors` instead of `/services/2/errors?service_id=2`

Clean Dashboard link to have service_id only once

---

app/javascript/src/Navigation/api_selector.jsx

I found what I believe is a bug. When creating a new service title is `API: `
But I think it should be:
Simplest solution is to check if `name` is empty but I think `api` should be `null` when in `apiconfig/services/new`.

Fixes SearchBoxTitle

---

lib/api_docs/provider_data.rb

As I am working on https://github.com/3scale/porta/pull/62, I've found this `N+1 Query`:
```
/p/admin/api_docs/account_data.json
N+1 Query detected
ApplicationPlan => [:service]
Add to your finder: :includes => [:service]
N+1 Query method call stack
/Users/marta/Devel/porta/lib/api_docs/provider_data.rb:33:in `block in <class:ProviderData>'
/Users/marta/Devel/porta/lib/api_docs/provider_data.rb:36:in `block in application_plan_ids'
/Users/marta/Devel/porta/lib/api_docs/provider_data.rb:35:in `application_plan_ids'
/Users/marta/Devel/porta/lib/api_docs/account_data.rb:13:in `block in account_data'
/Users/marta/Devel/porta/lib/api_docs/account_data.rb:13:in `map'
/Users/marta/Devel/porta/lib/api_docs/account_data.rb:13:in `account_data' …
```

Fix N+1 Query on ProviderData#application_plan_ids for service of application_plans

---

app/views/buyers/applications/edit_redirect_url.html.erb

@mayorova  discovered this bug.
1. Go to the `show` page of an `application`
2. Click `Edit`, enter the url in a popup and click `Save`
3. It showed `404 Not Found page` because it tried to make a `POST` request to `provider-url/apiconfig/services/:service_id/applications/:application_id`
I broke this in https://github.com/3scale/porta/commit/29f64d5c2888005ecb0285ea1eedb4d529e6dec4#diff-51ecc5cd2637a2e14f8651147ed56f9bR3 😊 sorry 😞

[Hotfix] Fix redirect_url update link

---

app/models/api_docs/service.rb
lib/tasks/swagger.rake
test/unit/api_docs/service_test.rb
test/unit/tasks/swagger_test.rb

This is beneficial for https://github.com/3scale/porta/pull/62
and specially discussed in https://github.com/3scale/porta/pull/62#discussion_r222043034
Account is mandatory for all ActiveDocs already, so enforcing this in the model as well makes checking other things easier 😄 
In another PR because it is a slightly risky change and I want to see if it breaks anything on its own first 😂

ActiveDocs' account is required now

---

lib/tasks/integration.rake
script/jenkins.sh

This PR offers a reworking (not just refactoring, as some behaviour _has_ changed) of `integration.rake` into rake tasks. 
The behaviour change is intentional: 
Instead of relying on a single environment variable (MULTIJOB_KIND) that allows us to select just one kind of test suite to run, we can define the actual test suites in here as independent rake tasks.
This way, they can be orchestrated together in the same way as before (i.e. into a "MULTIJOB_KIND" type of run, with same behaviour), BUT, in doing so, we increase the flexibility to invoke independently each of the different rake tasks on the command line, getting rid of some of the complexity in the process.
Related to #22 
**Special notes for your reviewer:** …

More flexible tests execution

---

app/assets/stylesheets/provider/admin/_dashboard.scss
app/views/layouts/api/_service.html.slim
app/views/provider/admin/dashboards/_service.html.slim
app/views/provider/admin/dashboards/_service_navigation.html.slim
app/views/provider/admin/dashboards/show.html.slim
app/views/shared/provider/_submenu.html.slim

In a service driven navigation context "applications" and "active docs" sit inside the "API" menu. Also, the dashboard is the new API's page. We need more granular checks for showing/hiding service related content on the dashboard. (at this moment we only show service on dashboard if user can manage analytics.) We also need to make decisons which permission unlocks active docs and definition (metrics) as they are not locked at all at this moment.
things we won't do:
- fix api's top navigation level for members with app only access. This section will be gone in 2 weeks.
to do:
Member with applications access for some services will see those services and links to applications of those services on the dashboard.
that person will have a bit of a broken …

Permissions in a service-driven navigation context

---

app/controllers/buyers/account_plans_controller.rb
app/views/shared/provider/_submenu.html.slim
features/old/api/plans/account_plans.feature
features/old/menu/provider.feature

Fixes [THREESCALE-1356](https://issues.jboss.org/browse/THREESCALE-1356)
Go to `provider-url/buyers/account_plans` and you will see the new navigation:

[2.4 Feature][Navigation] Move account plans to settings

---

app/controllers/admin/api/api_docs_services_controller.rb
app/controllers/admin/api_docs/services_controller.rb
app/models/api_docs/service.rb
app/models/service.rb
app/representers/api_docs/service_representer.rb
app/views/admin/api_docs/services/_form.html.slim
config/locales/en.yml
db/migrate/20180928114956_add_service_to_api_docs.rb
db/oracle_schema.rb
db/schema.rb
doc/active_docs/Account Management API.json
lib/developer_portal/lib/liquid/drops/provider.rb
test/integration/admin/api/api_docs_services_controller_test.rb
test/integration/admin/api_docs/services_controller_test.rb
test/unit/api_docs/service_test.rb
test/unit/liquid/drops/provider_drop_test.rb

Part of [THREESCALE-1340](https://issues.jboss.org/browse/THREESCALE-1340)
Depends on https://github.com/3scale/infrastructure/issues/546
- ApiDocs allows for service selection in edit so customers with free floating api docs can attach them to a service.
- If imported as part of "discovering a service" from the cluster, we should be able to also update that api doc when the service is updated ("rediscovered").
- Create/New form filled:
- Once created (it is another ActiveDocs creation 😄 but I post this one for the flash message):
- Update/Edit form filled:
- Once edited:
- Swagger:
- Curl request: `curl -v  -X POST "http://provider-admin.example.com.lvh.me:3000/admin/api/active_docs.json" -d 'access_token=your-access-token&name=created+through+api&system_name=api-system-name&service_id=2& …

[Service - ApiDocs relationship] Create relationship and adapt endpoints for Create and Update (UI & API)

---

app/controllers/admin/api/api_docs_services_controller.rb
app/controllers/admin/api_docs/services_controller.rb
app/models/api_docs/service.rb
app/models/service.rb
app/representers/api_docs/service_representer.rb
app/views/admin/api_docs/services/_form.html.slim
config/locales/en.yml
db/migrate/20180928114956_add_service_to_api_docs.rb
db/oracle_schema.rb
db/schema.rb
doc/active_docs/Account Management API.json
doc/liquid/drops.html
doc/liquid/drops.md
lib/developer_portal/lib/liquid/drops/api_spec.rb
lib/developer_portal/lib/liquid/drops/provider.rb
lib/developer_portal/lib/liquid/drops/service.rb
test/integration/admin/api/api_docs_services_controller_test.rb
test/integration/admin/api_docs/services_controller_test.rb
test/unit/api_docs/service_test.rb
test/unit/liquid/drops/api_spec_drop_test.rb
test/unit/liquid/drops/provider_drop_test.rb
test/unit/liquid/drops/service_drop_test.rb

Depends on https://github.com/3scale/porta/pull/62 in which ActiveDocs and Service have a relationship.
fixes https://github.com/3scale/porta/issues/61 and belongs to [THREESCALE-1340](https://issues.jboss.org/browse/THREESCALE-1340)
1. Service drop -> api_specs
`http://provider-admin.example.com.lvh.me:3000/p/admin/liquid_docs#service-drop`
2. ApiSpecs drop -> service
`http://provider-admin.example.com.lvh.me:3000/p/admin/liquid_docs#apispec-drop`
3. Improve the already existing ProviderDrop#api_specs documentation
`http://provider-admin.example.com.lvh.me:3000/p/admin/liquid_docs#provider-drop`
Removing the access to deleted api_specs from provider for the service is already done in https://github.com/3scale/porta/pull/62

[Service - ApiDocs relationship] Adapt Liquid Drops to it

---

INSTALL.md

In order to set up the dev env, a Redis db is required. There's currently no indication of that.
#55
Since I'm using the Docker container I'm not sure the instructions for running a local Redis are complete.

Adds Redis step to Install.md

---

test/unit/api_docs/service_test.rb

Improve Test efficiency in `ApiDocs::ServiceTest` and test `accessible` by its IDs and not by name.
This comes from the reviews of less urgent stuff in https://github.com/3scale/porta/pull/62
The other review, the one of changing `provider_account` for `simple_provider` is not possible for integration tests.

Improve Test efficiency in ApiDocs::ServiceTest & test `accessible` by its IDs and not by name

---

.github/pull_request_template.md

This is a suggestion for including the section **Verification Steps** in the PR template. It makes it easier and quicker for any reviewer to verify the issue has been addressed properly or that the changes work as expected.

adds verification steps to pr template

---

app/lib/three_scale/spam_protection/protector.rb
app/views/sites/spam_protections/edit.html.erb
config/initializers/captchas.rb
config/locales/en.yml
lib/forum_support/posts.rb
test/integration/sites/spam_protection_test.rb
test/unit/three_scale/spam_protection_test.rb

Not configured, but enabled reCaptcha breaks Developer portal login page.
Fixes https://issues.jboss.org/browse/THREESCALE-1108

reCAPTCHA doesn't work in on-premises

---

lib/tasks/boot.rake

Otherwise it will not run other following tasks
Bug introduced in https://github.com/3scale/porta/pull/83/commits/884ed69c4f3dc24db4590a0beff06bb6f1fc6854

[fix] rake boot:database should only exit when db is not ready

---

db/migrate/20181008065816_add_kubernetes_service_link_to_service.rb
db/oracle_schema.rb
db/schema.rb

So we can differenciate which are the services that are fetched from K8s and the others.
Store in this column the self_link so we can identify the service easily.

[db] Migration to prepare service resync for Kubernetes service discovery

---

app/services/service_creation_service.rb
app/workers/service_discovery/import_cluster_service_definitions_worker.rb
test/unit/services/service_creation_service_test.rb

It makes the creation of APIs by service discovery to fill the lookup column `services.kubernetes_service_link` with the cluster service `selfLink` attribute.
The PR also introduces better tests for `ServiceCreationService`.
Related to https://github.com/3scale/porta/issues/34

[Service Discovery] Fill lookup column services.kubernetes_service_link

---

app/models/api_docs/service.rb
app/models/service_discovery/model_extensions.rb
test/unit/service_discovery/model_extensions_test.rb

It makes the import of a swagger/OAS spec into an ActiveDoc on service discovery to also fill ApiDocs::Service.service_id, ensuring the relationship between the new API and the new API spec created.
Related to https://github.com/3scale/porta/issues/34

[Service Discovery] Fill api_docs_services.service_id

---

app/controllers/frontend_controller.rb
app/helpers/menu_helper.rb
app/views/shared/_api_selector.html.slim
app/views/shared/provider/_user_widget.html.slim

I've found this `N+1 Query` when loading `/apiconfig/alerts`:
```
/apiconfig/alerts
N+1 Query detected
Service => [:account]
Add to your finder: :includes => [:account]
N+1 Query method call stack
/Users/marta/Devel/porta/app/models/service.rb:397:in `support_email'
/Users/marta/Devel/porta/app/helpers/json_helper.rb:5:in `json'
/Users/marta/Devel/porta/app/views/shared/_api_selector.html.slim:7:in `_app_views_shared__api_selector_html_slim___3374156238745550695_70267119012920'
/Users/marta/Devel/porta/app/views/shared/provider/_user_widget.html.slim:10:in `_app_views_shared_provider__user_widget_html_slim__4437274933794199262_70267111450280'
/Users/marta/Devel/porta/app/views/layouts/provider.html.slim:20:in `_app_views_layouts_provider_html_slim__958426546298312323_70267087833860' …
```

[Refactor] FrontendController#all_services for api_selector_services helper

---

config/schedule.rb
openshift/system/config/sidekiq_schedule.yml

So weekly means every 1,8,15,22 of the month for whenever
Though every Sunday or Monday, Xday of the week is more correct
This is to harmonize the different behaviour using either the OS cron or using sidekiq
Fixes: https://issues.jboss.org/browse/THREESCALE-1307

[cron] Sidekiq Cron weekly should equal to whenever weekly

---

app/assets/stylesheets/provider/admin/_dashboard.scss
app/views/provider/admin/dashboards/_service.html.slim
app/views/provider/admin/dashboards/_services_filter.html.slim
app/views/provider/admin/dashboards/_services_navigation.html.slim
app/views/provider/admin/dashboards/show.html.slim

Some improvements for users that only manage 1 api.
-  don't show API's filter box
-  don't show applications at all api's level
- always show new api link as it re-enforces the idea of API's section. (points to upgrade if not allowed)
current:
improved:

Dashboard improvements for 1 service accounts

---

Dockerfile
config/webpacker.ci.yml
script/jenkins.sh

> Fixes possible stale assets when running the test battery

[webpack] Precompile assets on test env

---

app/assets/stylesheets/provider/_tables.scss
app/views/api/metrics/_metric.html.erb

Fixing overlapping of metric and methods names in tables
[https://issues.jboss.org/browse/THREESCALE-1389](https://issues.jboss.org/browse/THREESCALE-1389)
You need to create an Application Plan previously, with some long metrics and methods names.
Then, go to APIS > Application Plans, then select an Application Plan
**Before:**
**After**
**BEFORE:**
**After**

Fixing overlapping of metric names

---

app/assets/stylesheets/provider/_theme.scss
app/assets/stylesheets/provider/_vert_nav_toggle.scss
app/views/shared/provider/_user_widget.html.slim
app/views/shared/provider/navigation/_vertical_nav.html.slim

Adds a button in the MastHead for toggling the vertical navigation. Collapse state is stored in localStorage so that it persist after refreshing.
https://issues.jboss.org/browse/THREESCALE-1390
1. Button is rendered in MastHead only when vertical nav is available (e.g. not in Dashboard)
2. Clicking on the button alternatively collapses/expands the vertical navigation
3. Refreshing the browser does not change vert nav state: it keeps being collapsed/expanded
Please ignore the the _Master Account_ ribbon look.
TODOs:
- [ ] Check styles

Implements Persistent Vertical Navigation Toggle

---

app/assets/stylesheets/provider/_tables.scss
app/helpers/usage_limits_helper.rb

Long metric names break the layout on the Applications page
It adds word-break to long metrics and methods names
https://issues.jboss.org/browse/THREESCALE-1382
APIs > Applications > YourApplicationName
**Before:**
**After:**

THREESCALE-1382 Long metric names - Applications page

---

app/javascript/src/Navigation/components/ContextSelector.jsx
app/javascript/src/Navigation/components/ContextSelector.spec.jsx

Adds a missing _Dashboard_ option in the context selector.
Follows up on: #137 
Fixes: https://issues.jboss.org/browse/THREESCALE-1395

Include Dashboard option in ContextSelector

---

app/controllers/admin/api_docs/account_api_docs_controller.rb
app/views/shared/provider/navigation/_vertical_nav_item.html.slim

The problem was the Controller activates `main_menu` and the `active` class only activates if the `submenu` (not main menu) is that one, or if the url is the one it has (which is the case for the `index` 😉 ).

[Bugfix] Fix ActiveDocs active menu for edit/preview under account scope

---

app/models/service.rb
app/representers/service_representer.rb
test/integration/admin/api/services_controller_test.rb

Attributes provided in services#show endpoint should mirror attributes from services#post
fixes https://github.com/3scale/porta/issues/133
fixes https://github.com/3scale/3scale-api-ruby/issues/38

[services#show] attributes should mirror post attributes

---

features/old/authentication/skypeid.feature
features/old/services/switch.feature

Fix `old/services/switch`, which is passing.
And a wrong link in `old/authentication/skype` although that feature is a `wip` since who knows when... 😂

Fix Cucumbers: old/services/switch and old/authentication/skype

---

app/views/provider/admin/dashboards/_service_navigation.html.slim
features/old/authorization/provider_stats.feature

Fixes features/old/authorization/provider_stats.feature
**to do:**

Provider stats feature

---

test/integration/provider/invoices_controller_test.rb
test/test_helpers/menu.rb

Fix testing menus for Finance::Provider::InvoicesControllerTest

---

features/step_definitions/navigation_steps.rb

Fix all tests that use the step to navigate to partner. Now we click on a text that looks like "1 Account" or "20 Accounts".
Example of this in: `spring cucumber features/old/buyers/invitations/for_admins.feature:30`

Fix Cucumber step: I navigate to the page of the partner name-of-partner

---

features/old/applications/providers/search.feature

Now finding Apps is much easier from the Dashboard 😄 So this feature goes through the new path

Fix Cucumber navigation to find Apps in old/applications/providers/search

---

app/events/services/service_scheduled_for_deletion_event.rb
app/lib/event_store/repository.rb
app/models/service.rb
app/subscribers/service_deletion_subscriber.rb
test/events/services/service_scheduled_for_deletion_event_test.rb
test/subscribers/service_deletion_subscriber_test.rb
test/unit/service_test.rb

related https://github.com/3scale/porta/issues/20

[service] service is not being deleted measures

---

features/old/api/alerts.feature

Fix cucumber feature in `features/old/api/alerts.feature`.
It just goes to the API by the new way 😄

Fix cucumber feature old/api/alerts

---

features/old/buyers/impersonate.feature
features/step_definitions/navigation_steps.rb

Fix cucumber feature in `old/buyers/impersonate.feature`.
It just goes to Accounts by the new way 😄

Fix cucumber feature old/buyers/impersonate

---

app/views/shared/provider/navigation/_vertical_nav.html.slim
public/packs/manifest.json

Imitates original Patternfly behavior of [vertical navigation](https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html) by adding a delay to the submenus, when mouse hovers.
Also changed `mouseover -> mouseenter` and `mouseout -> mouseleave` for a better performance: events would be triggered when hovering the mouse over the same element.
- Any submenu should be shown after a brief delay when overing.
- If moving the mouse away before submenu appears, it won't.
- If moving the mouse away after submenu appeared, it will hide after a brief delay.

Adds a delay to showing/hiding submenus

---

openshift/system/Dockerfile.on_prem

It makes https://github.com/3scale/porta/blob/master/openshift/system/Dockerfile.on_prem to install a more recent version of bundler (1.16.6) than the one avaiable in the base image (1.10.6).
This started failing after https://github.com/3scale/porta/pull/44 as merged, particularly https://github.com/3scale/porta/commit/6bb972b031f95c63b90e0276262a83f56c121c6e#diff-33c867a743c81c1ce1e040ecbb221d39:
```
[!] There was an error parsing `Gemfile.base`: `mri_23` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :rbx, :jruby, :jruby_18, :jruby_19, :mswin, :mswin_18, :mswin_19, :mswin_20, :mswin_21, :mswin64, :mswin64_19, :mswin64_20, :mswin64_21, …
```

Fix bundler version for On-premises

---

app/lib/three_scale.rb
app/views/shared/provider/navigation/account/_nav.html.slim
features/old/menu/account_menu.feature
features/step_definitions/finance/providers/billing_settings_step.rb

It tests whether Account submenu Billing options ('3scale Invoices' and such) appear according to the deployment – on-premises or not on-premises.

Test for Account submenu Billing options

---

app/controllers/buyers/service_contracts_controller.rb

- ServiceContract#index under Accounts scope
- ServiceContract#index under Services scope
- ServiceContract#index under ServicePlans scope
About the other actions of the controller being affected by this code, `edit` and `new` are under Account so it is correct:

[Bugfix] ServicesContracts navigation under Accounts/Services for index

---

test/integration/admin/api_docs/account_api_docs_controller_test.rb

Fix the tests since the Account scope has the title as well now

Fix Tests for AccountApiDocsController: now with ActiveDocs title

---

lib/tasks/boot.rake

So we can properly check it without the need of the database to be up
Checking Redis connectivity was depending on :environment
The :environment task needs MySQL to be up
We also need it for dependencies checking in https://github.com/3scale/openshift-templates/pull/360
Relates to https://github.com/3scale/openshift-templates/pull/360
- Shutdown MySQL
- Verify that `rake boot:redis` does not crash if Redis is up

[boot] Make redis check independent of environment

---

app/controllers/api/metrics_controller.rb

The key was checking at `app/views/shared/provider/navigation/_vertical_nav_item.html.slim` for the values of `@active_menus[:sidebar]` and `title`, then look at `lib/menu_system.rb` in `active_menu?` and do the conversions in the same way. The error was it was comparing `'methods_and_metrics'` with just `methos_metrics` after the conversion of both.

Activate sidebar 'Methods & Metrics'

---

app/controllers/forums/admin/forums_controller.rb
app/controllers/forums/admin/topics_controller.rb

Fix Navigation Sidebar Forums->Threads active and not 'My Threads' and vice versa

---

app/controllers/buyers/accounts_controller.rb
app/indices/account_index.rb
app/models/account.rb
app/models/account/states.rb
test/unit/account/states_test.rb
test/unit/account_test.rb

Master account appears in the buyer accounts search. Master account should not be searchable in the first place. Let's not create an account index in sphinx for master account and do not show `master: true` account on buyers/tenants page. 
Master account should not be suspendable.

Do not index master account + master account cannot be suspended

---

app/views/provider/admin/dashboards/_services_filter.html.slim

By request of @hallelujah in [this coment](https://github.com/3scale/porta/pull/78#pullrequestreview-162126816), here it is a proposal to make api filter logic more readable (both solutions are identical logic-wise).
I've tried them both with 500 services and performance-wise the _double for_ is quicker. However the times are small enough to be negligible.
I personally think the _double for_ is more readable but I'd like to know your opinions.

Reduce loops in Api Filter

---

app/models/invitation.rb
test/unit/invitation_test.rb

Fixes [THREESCALE-647](https://issues.jboss.org/browse/THREESCALE-647)
It allows inviting admin users with the same email of any of its buyers, but it keeps verifying it doesn't exist among the users of the same account.

[Bugfix] Invitation does not require uniqueness emails including its buyers

---

doc/liquid/drops.md
lib/developer_portal/lib/liquid/drops/application.rb
test/unit/liquid/drops/application_drop_test.rb

We expect the same objects as the variable `alerts` in /admin/applications/:application_id/alerts
Drops are a way to protect database objects. The current implementation is returning an ActiveRecord::Relation which should not be exposed in the view

[drops] Liquid::Drops::Application#alerts is a Drops::Alert collection

---

app/models/account.rb
app/models/account/states.rb
test/unit/account_test.rb

It comes from the thread in https://github.com/3scale/porta/pull/17#discussion_r229269290
> Master is a "provider" by definition, but it won't ever be a "tenant".

[Refactor] Rename #provider_but_not_master? -> #tenant?

---

app/controllers/provider/sessions_controller.rb
config/routes.rb
test/integration/provider/sessions_controller_test.rb

There is a new route, `GET` on `/auth/:system_name/bounce` that redirects to the `authorize_url` of that `AuthenticationProvider`
Closes https://issues.jboss.org/browse/THREESCALE-1292

AuthorizationProvider bounce redirects to the authorize_url

---

app/lib/signup/master_domains_builder.rb
test/unit/account/domains_test.rb
test/unit/signup/master_domains_builder_test.rb

It ensures that master's subdomain and self_subdomain matches what the account holds in the database, no longer enforcing the hardcoded `-admin` suffix.
That comes together with https://github.com/3scale/openshift-templates/pull/387

Master sudomains generated without '-admin'

---

app/models/cinstance.rb

Plenty of not deleted alerts in the database.

[alerts] alert without cinstance

---

app/models/account/billing.rb
app/models/invoice.rb
config/locales/en.yml
test/integration/finance/api/invoices_controller_test.rb
test/unit/finance/charging_test.rb
test/unit/invoice_test.rb

This makes not only zero-valued invoices to be prevented from being charged, but also the negative ones.
Instead of applying the condition at `Account#charge!`, the validation was moved to `Invoice#charge!`. This is possible because an account is always charged through an invoice.
[THREESCALE-1378](https://issues.jboss.org/browse/THREESCALE-1378)
1. I understand that not changing the status of the invoice will make it to be continuously attempted to charge. We should also fix that. Nevertheless, that behavior is not introduced by this PR itself, but rather present already since the bare possibility of non-positive invoices.
2. Another step to take is preventing negative line items …

[billing] Prevent non-positive invoices from being charged

---

app/assets/stylesheets/provider/_forms.scss
app/views/api/services/forms/_naming.html.slim
app/views/api/services/forms/_service_discovery.html.slim
app/views/api/services/new.html.slim
features/old/services/multiservice.feature
features/old/services/switch.feature

Better naming for labels of the New API form, including the Service Discovery option, OAuth link, etc
https://docs.google.com/presentation/d/1ZEU5KmY5slLTteZm5r9o3a10nqVfQdozF8GfNL5oP5A/edit#slide=id.g40d2a2fcbf_2_40
Having Service Discovery feature enabled (better with SSO),
- Login to the Admin Portal
- From the Dashboard, click "New API"
- Switch between the two options "Define manually" and "Import from OpenShift"

UI enhancements for New API form

---

app/views/shared/provider/navigation/_secondary_nav.html.slim

Prevent section content from scrolling up when expanding/collapsing menus from the vertical navigation.
https://issues.jboss.org/browse/THREESCALE-1477
1. Navigate to a screen where there is enough content to scroll down a bit (e.g. Fields Definition)
2. Scroll down. Then collapse/expand any of the menus of vertical navigation (Accounts, Applications, Billing...)
3. Screen should not scroll up to the top when clicking those items
This is more a workaround than a fix, but a rather safe one. It would navigate to a `!` section but that's hardly ever going to be a title for anything.

Prevent Vertical Navigation items from scrolling up to the top when being clicked

---

app/helpers/account_helper.rb
app/models/account/states.rb
app/workers/find_and_delete_scheduled_accounts_worker.rb
test/unit/account/states_test.rb
test/unit/helpers/account_helper_test.rb
test/unit/helpers/api/account_plans_helper_test.rb
test/workers/find_and_delete_accounts_scheduled_worker_test.rb

Improvements in TIME_TO_DELETE_ACCOUNT

---

app/models/service_discovery/cluster_client.rb
test/unit/service_discovery/cluster_client_test.rb

It makes the cluster client wrapper to raise generic error massages thrown by the actual clients while trying to fetch cluster resources. Now only 404's are raised.
This will improve debuging of failures occurred while fetching cluster objects and prevent `ServiceDiscovery::ClusterResource#metadata delegated to resource.metadata, but resource is nil`.

[Service Discovery] Generic error on cluster resource fetch

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock
config/schedule.rb

There were multiple environment declaration that are not needed
It removes double declaration of environment variables
* Run `whenever`
* verify that the environments are declared only once in the ouptut
* verify that all the commands are prepended with `bundle exec`
My local output
```
whenever                                                                                                                                
PATH=/home/bender/bin:/home/bender/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
MAILTO=""
0 0 * * 1 /bin/bash -l -c 'cd /Users/hery/Devel/3scale/porta && BUNDLE_GEMFILE=Gemfile /Users/hery/.rbenv/versions/2.3.7/bin/ruby …
```

[cron] Commands are now properly generated

---

app/views/provider/admin/dashboards/_developers_navigation.html.slim
app/views/provider/admin/dashboards/_service_navigation.html.slim
features/old/menu/dashboard.feature

…as they are secondary and space is limited. 
Docs are not affected by this change as we don't guide people through home page links.

Remove links to plans from dashboard

---

app/assets/stylesheets/provider/admin/_dashboard.scss

> Align items to the left, as they were originally 

Quick Fix: Aligning items to the left

---

app/views/provider/admin/dashboards/show.html.slim

Fixes [THREESCALE-1473](https://issues.jboss.org/browse/THREESCALE-1473)
Show the right number of tenants in the dashboard
1. Go to the master admin portal
2. See the `1 account` in the first row for the audience
3. Click on the `1 account` and see just one

Master dashboard shows the right number of tenants

---

app/views/shared/provider/navigation/audience/_messages.html.slim
app/views/shared/provider/navigation/audience/_nav.html.slim
app/views/shared/provider/navigation/audience/_portal.html.slim
app/views/shared/provider/navigation/service/_analytics.html.slim
app/views/shared/provider/navigation/service/_applications.html.slim
app/views/shared/provider/navigation/service/_end_users.html.slim
app/views/shared/provider/navigation/service/_nav.html.slim
config/abilities/switches.rb
features/old/menu/api_menu.feature

closes:
https://issues.jboss.org/browse/THREESCALE-1461
https://issues.jboss.org/browse/THREESCALE-1476

various permission fixes for master on prem

---

app/views/provider/_logo.html.slim

It aims to remove all traces of custom logo in admin portal.
[[THREESCALE-1462] Remove logo customisation from admin portal](https://issues.jboss.org/browse/THREESCALE-1462)
?

Removes traces of custom logo

---

app/assets/stylesheets/provider/_header.scss

When creating new Application '/buyers/accounts/3/applications/new'. If Application plan field (#cinstance_plan_id) is expanded and at the same time user expand #api_selector this two elements overlap in unexpected way.
https://issues.jboss.org/browse/THREESCALE-1472
**Note that I added extra whitespace below "API" just to have more height and be able to see the overlapping**

THREESCALE-1472-Api-Selector-Overlapped

---

.gitignore
.rubocop.yml
Gemfile.base
Gemfile.lock
Gemfile.prod.lock
config/application.rb
config/docker/prometheus.yml
config/examples/prometheus.yml
config/initializers/bugfix-rails-18666.rb
config/initializers/bugfix_rails_18666.rb
config/routes.rb
lib/routing_constraints.rb
test/integration/prometheus_test.rb

Closes https://github.com/3scale/infrastructure/issues/574
The metrics are exposed as:
http://${MASTER_DOMAIN}/system/metrics
Metrics are only available if authentication basic is configured by setting in the `config/prometheus.yml` file the `username` and `password`

[gem] Expose sidekiq metrics to prometheus

---

app/assets/stylesheets/provider/_tables.scss
app/views/buyers/applications/_utilization.html.erb

Adding word-break to metric names in Current Utilization
https://issues.jboss.org/browse/THREESCALE-1382
**Before:**
-----
-----
**After:**
-----
-----

THREESCALE-1382 Adding word-break to metric names in Current Utilization

---

app/controllers/api/applications_controller.rb
app/models/cinstance.rb
test/integration/api/applications_controller_test.rb
test/unit/cinstance_test.rb

Fixes [THREESCALE-1474](https://issues.jboss.org/browse/THREESCALE-1474)
Master account has a cinstance for which he is both its provider and its buyer, and right now it is shown in the provided cinstances list, but when we click in its buyer (in this case itself), it says 404 because it tries to find it as a buyer and not itself.
In 2.2 we used to show both this cinstance in the provided cinstances list, and the master as its buyer when clicked on it.
I wonder: should we show both just like in 2.2 or should I hide both so the list of provided cinstances does not show this one?
[DECIDED] This PR it is doing the latter: Master bought_cinstance is not returned among its provided_cinstances.

Master bought cinstance should not appear as a provided cinstance

---

app/controllers/admin/api/authentication_providers_controller.rb
test/integration/admin/api/authentication_providers_controller_test.rb

Fixes [THREESCALE-1207](https://issues.jboss.org/browse/THREESCALE-1207)
`:site` was documented but not accepted in the strong params.

API Endpoint for Authentication Provider Developer Portal Update also updates site

---

app/assets/stylesheets/provider/_colors.scss
app/assets/stylesheets/provider/admin/cms/_cms_intro.scss

The highlights in the CMS tool for the designing the developer portal should be more visible. Right now it's changing text color to link color, maybe text color to alert color would be enough. The idea is that peripheral vision should be able to detect the change
https://issues.jboss.org/browse/THREESCALE-1470

THREESCALE-1470 Highlights more visible

---

features/old/services/multiservice.feature

Fix Jenkins cucumber JS not found for creating in `features/old/services/multiservice.feature:26 in `And I press "Add API"` with the error:
```
{:line_number=>0, :message=>"TypeError: 'undefined' is not an object", :source=>"undefined"} (Capybara::Webkit::JavaScriptError)
```

Cucumber Feature Multiservice: Remove JS when it is not used

---

app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
app/lib/logic/rolling_updates.rb
app/models/proxy.rb
app/models/service.rb
app/services/proxy_test_service.rb
app/views/api/integrations/edit.html.slim
app/views/api/integrations/service_mesh/_form.html.slim
app/views/api/integrations/show.html.slim
app/views/api/services/forms/_integration_settings.html.slim
config/examples/rolling_updates.yml
config/locales/en.yml
openshift/system/config/rolling_updates.yml
test/unit/proxy_test.rb
test/unit/service_test.rb

* Introduce new rolling update.
* Implement `Proxy#deployable?` to skip deployments and testing.
* Add Service Mesh integration option only when the rolling update is
enabled.
Fixes [THREESCALE-1426](https://issues.jboss.org/browse/THREESCALE-1426)
Closes https://github.com/3scale/porta/issues/302

Service Mesh on the Integraton page [THREESCALE-1426]

---

app/assets/stylesheets/provider/layouts/_login.scss
app/views/provider/sessions/new.html.slim

text beneath authorize link should not highlight on hover or show pointer cursor.

style text beneath authorize link

---

app/views/api/services/forms/_service_discovery.html.slim

Service discovery form is submitted even if no option selected.
Adding required attribute to select in order to prevent form submission
https://issues.jboss.org/browse/THREESCALE-1523

THREESCALE-1523 Adding required attribute to selects

---

app/lib/service_discovery/oauth_configuration.rb
test/unit/service_discovery/oauth_configuration_test.rb

Forbid access to service discovery if it is not enabled in the configuration
This should not be there

[hotfix] Service discovery should not be accessible if not enabled in the config

---

app/controllers/buyers/applications_controller.rb
test/integration/buyers/applications_controller_test.rb

Fixes [THREESCALE-1474](https://issues.jboss.org/browse/THREESCALE-1474)
Master account has a cinstance for which he is both its provider and its buyer, and right now it is shown in the provided cinstances list, but when we click in its buyer (in this case itself), it says 404 because it tries to find it as a buyer and not itself.
In the Dashboard, it also needs to show the number of applications properly, without the buyers, but @thomasmaas will do that in another PR.

Master bought cinstance should not appear as a provided cinstance [Part 2]

---

features/provider/integration/edit.feature
features/step_definitions/plans/application_plans_steps.rb
features/step_definitions/service_steps.rb

Add a cucumber test for [THREESCALE-1496](https://issues.jboss.org/browse/THREESCALE-1496)
Fixed in https://github.com/3scale/porta/pull/316

Cucumber feature for link from integration/edit to analytics usage

---

app/workers/delete_plain_object_worker.rb

By the beginning of September we had a `StaleObjectError` in `DeletePlainObjectWorker`. Back then I did https://github.com/3scale/system/pull/9431, and we weren't Open Source back then but all it contains inside is this:
https://github.com/3scale/porta/blob/164eba4828debfa97bbd13a0031486d941db223e/app/workers/delete_plain_object_worker.rb#L11-L14
And I explained there that I suspect that at this point the object has already been deleted and then we don't need to do anything else about it, but I added that to have more information if it happens again.
Now it happened again, and the log of it is:
```json
{
"parameters": {
"caller_worker_hierarchy": [
"Hierarchy-Service-2555417761880",
"Hierarchy-Proxy-108121",
"Plain-Proxy-108121"
],
"error_messages": []
}
}
```
I checked in production if …

DeletePlainObjectWorker ignores errors when the object has been destroyed

---

lib/developer_portal/app/views/developer_portal/access_codes/show.html.erb

The navigation in the UI has changed, but the hint on this page didn't reflect it.
This PR sets the correct location of the access token settings (and clarifies the terms).

Fix navigation hint for dev portal access code

---

test/functional/admin/api/services/mapping_rules_controller_test.rb
test/functional/provider/admin/messages/trash_controller_test.rb
test/integration/payment_gateways/braintree_blue_test.rb
test/integration/sessions_test.rb
test/unit/account_test.rb
test/unit/api_authentication/http_authentication_test.rb
test/unit/cms/template_test.rb
test/unit/deploy/basic_info_test.rb
test/unit/developer_portal/controller_methods/plan_changes_methods_test.rb
test/unit/forms/onboarding/api_form_test.rb
test/unit/forms/onboarding/request_form_test.rb
test/unit/helpers/application_helper_test.rb
test/unit/liquid/drops/invoice_drop_test.rb
test/unit/liquid/drops/pagination_test.rb
test/unit/liquid/filters/form_helpers_test.rb
test/unit/presenters/dashboard/top_traffic_presenter_test.rb
test/unit/service_discovery/well_known_fetcher_test.rb
test/unit/services/messages/destroy_all_service_test.rb
test/unit/three_scale/oauth2/keycloak_client_test.rb
test/unit/three_scale/oauth2/redhat_customer_portal_client_test.rb
test/unit/user_session_test.rb

Removes deprecation warning:
> DEPRECATED: Use assert_nil if expecting nil from .... This will fail in Minitest 6.

Removes deprecation warnings for "equal_to nil"

---

app/helpers/admin/cinstances/invoices_helper.rb
app/helpers/admin/cinstances/messages_helper.rb
app/helpers/admin/contracts_helper.rb
app/helpers/admin/finance/dashboards_helper.rb
app/helpers/admin/finance/line_items_helper.rb
app/helpers/admin/sessions_helper.rb
app/helpers/analytics/dashboards_helper.rb
app/helpers/analytics/traffic_helper.rb
app/helpers/analytics/users_helper.rb
app/helpers/api/account_plans_helper.rb
app/helpers/api/application_plans_helper.rb
app/helpers/api/service_plans_helper.rb
app/helpers/api/supports_helper.rb
app/helpers/cross_domain_sessions_helper.rb
app/helpers/dashboards_helper.rb
app/helpers/fields_definitions_helper.rb
app/helpers/finance/provider/settings_helper.rb
app/helpers/provider_sessions_helper.rb
test/unit/helpers/api/application_plans_helper_test.rb
test/unit/helpers/api/service_plans_helper_test.rb
test/unit/helpers/api/supports_helper_test.rb
test/unit/helpers/buyers/service_contracts_helper_test.rb
test/unit/helpers/finance/provider/settings_helper_test.rb
test/unit/helpers/reports_helper_test.rb

Removes empty `helpers` and empty tests of helpers.
It can get a bit confusing otherwise 😄

Remove empty helpers' classes/modules and tests

---

.github/wip.yml

Before this used to be the default behaviour, but now by default it only checks for `WIP` in the title, so in order to check for `Do not merge` as well, which is not the same concept, we need this config file as  you can find at the moment in https://github.com/wip/app#configuration

Configure the Github app to prevent us for merging PRs to check for certain words in the title

---

app/models/service_discovery/cluster_service.rb
test/unit/service_discovery/cluster_service_test.rb

It's currently not possible to set the annotation `discovery.3scale.net/path` to empty string or "/".
[THREESCALE-1587](https://issues.jboss.org/browse/THREESCALE-1587)
- Set the `discovery.3scale.net/path` annotation of a service to "/" or empty string
- Import the service from OpenShift into 3scale
- system-sidekiq container should raise an error:
```
WARN: TypeError: no implicit conversion of nil into String
WARN: /opt/system/app/models/service_discovery/cluster_service.rb:36:in `join'
```

[Service Discovery] Fix API endpoint without path

---

app/services/notification_delivery_service.rb
test/unit/services/notification_delivery_service_test.rb

Solution to the 1st problem of https://github.com/3scale/porta/issues/10
Allow event with `false` value in their attribute. They will not be considered invalid anymore.
This is done by changing the check from `blank?` to `nil?`, since that's the check we actually want.
Just for referencing, this started when we weren't open source yet, in https://github.com/3scale/system/pull/9439 😄

NotificationDeliveryService nil value invalid event. Blank valid

---

app/assets/stylesheets/provider/admin/_dashboard.scss
app/helpers/provider/admin/dashboards_helper.rb
app/views/provider/admin/dashboards/_developers_navigation.html.slim
app/views/provider/admin/dashboards/_service_navigation.html.slim
app/views/provider/admin/dashboards/widgets/_service_integration_errors.html.slim
test/unit/helpers/provider/admin/dashboards_helper_test.rb

Refactors `dashboard_collection_link` into 2 methods:
- `dashboard_navigation_link (text, path, options?)`
- `dashboard_collection_link (text, collection, path, options?)`
Options being `{ icon_name, notice }` and `{ icon_name, notice, plural }` respectively.
Adds possibility of including `u-notice` class in the link by means of `notice: boolean`.
Adds _secondary_ versions of each method above.
Comment from @hallelujah -> https://github.com/3scale/porta/pull/78#pullrequestreview-16212538

Refactor dashboard_collection_link method

---

app/helpers/account_helper.rb
app/models/account.rb
app/models/account/states.rb
db/migrate/20181105203727_add_accounts_state_changed_at.rb
db/migrate/20181105212016_duplicate_deleted_at_state_changed_at.rb
db/oracle_schema.rb
db/schema.rb
spec/acceptance/api/account_spec.rb
test/integration/master/api/providers_controller_test.rb
test/unit/account/states_test.rb

Part 1 of https://github.com/3scale/porta/issues/290
In SaaS the migrations of the indexes in https://github.com/3scale/infrastructure/issues/576#issuecomment-436035644

[Part 1] Change Accounts column name deleted_at -> state_changed_at

---

.circleci/config.yml

circleci contexts allow environment variables to only be used in jobs where they are needed.
Adding the `PERCY_TOKEN` environment variable to the project settings in circleci causes some errors in other jobs (e.g. https://circleci.com/gh/3scale/porta/12361?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link ).
More info on circleci contexts: https://circleci.com/docs/2.0/contexts/#section=projects

Fix percy runs by scoping env vars

---

.circleci/config.yml

we need this, so we only trigger notifications to slack on builds taking place on master branch.
the current circleci - slack integration does not offer this possibility, so leads to extreme high volume of messages on slack and a rather low signal-to-noise ratio.
More info on circleci - slack integration: https://circleci.com/blog/slack-integration/

added jobs for sending manual notifications to slack

---

app/models/finance/billing_strategy.rb
features/support/paths.rb
test/unit/finance/billing_strategy_test.rb

Fixes [THREESCALE-1594](https://issues.jboss.org/browse/THREESCALE-1594)
Support `CHF` and `SAR` currencies.
It is following exactly the same of this code:
https://github.com/3scale/porta/blob/1689b23e5d239bb9435029eb75e1dd6afe89315d/features/old/finance/settings/provider.feature#L22-L32
But explained and with screenshots:
1. Go to `provider-url/finance/settings` (if you are in development and have the seeds in the DB, go to `http://provider-admin.example.com.lvh.me:3000/finance/settings`).
2. See the 2 new currencies in the list
3. Select one of them and save it. You should see this flash message:
4. Create an invoice for this provider and one of its buyers. I did it by console with: `Account.find(2).billing_strategy.create_invoice!(:buyer_account => Account.find(3), :finalized_at => …

Add CHF and SAR to the list of currencies

---

app/views/stats/_sparklines.html.erb

We aim to fix this:
Bug introduced in https://github.com/3scale/porta/commit/b2db347c6f968442019cd91ceae0a879c0e74998#diff-4ceb896c14cace67f20a237b1e57be01L3

Fix UI API/Overview fetch stats usage

---

app/models/account.rb
app/models/account/states.rb
lib/migration/finance.rb
spec/acceptance/api/account_spec.rb
test/integration/master/api/providers_controller_test.rb
test/unit/account/states_test.rb
test/workers/find_and_delete_accounts_scheduled_worker_test.rb

Step 2 of https://github.com/3scale/porta/issues/290
Depends on https://github.com/3scale/porta/pull/294
Change the code to make it work using `state_changed_at` instead of `deleted_at`, although we keep duplicating all the data.

[Part 2] Change Accounts column name deleted_at -> state_changed_at

---

LICENSE
NOTICE

As @unleashed said in https://github.com/3scale/porta/pull/372#issuecomment-443411060
> APPLYING THE LICENSE TO NEW SOFTWARE
> To apply the ALv2 to a new software distribution, include one copy of the license text by copying the file:
> 
> http://www.apache.org/licenses/LICENSE-2.0.txt
> 
> into a file called LICENSE in the top directory of your distribution. If the distribution is a jar or tar file, try to add the LICENSE file first in order to place it at the top of the archive. This covers the collective licensing for the distribution.
> 
> In addition, a correct NOTICE file MUST be included in the same directory as the LICENSE file.
> 
> Each original source document (code and documentation, but excluding the LICENSE and NOTICE files) SHOULD include a short license header at the top. …

[opensource] Apply Apache 2.0 with LICENSE and NOTICE

---

README.md

As the title says.
Since we call the component `Porta` everywhere now 😄

[opensource] Change component name in README: System -> Porta

---

app/models/account.rb
app/models/account/states.rb
app/models/cinstance.rb
app/workers/stale_account_worker.rb
app/workers/suspend_inactive_accounts_worker.rb
config/jobs.rb
test/unit/account/states_test.rb
test/unit/cinstance_test.rb
test/workers/stale_account_worker_test.rb
test/workers/suspend_inactive_accounts_worker_test.rb

fixes https://github.com/3scale/porta/issues/13
Under this criteria (established by product):
- No traffic in the last year -> Suspend
- Suspended form more than 90 days -> Schedule for deletion

Find inactive accounts and schedule them for deletion

---

app/models/service.rb
app/workers/delete_plain_object_worker.rb
lib/tasks/services.rake
test/unit/tasks/services_test.rb
test/workers/delete_plain_object_worker_test.rb

Fixes [THREESCALE-1194 - Services marked as "deleted", but not actually getting deleted](https://issues.jboss.org/browse/THREESCALE-1194)
This is the log of one of times that happened: https://gist.github.com/guicassolato/5e8a4c39b95909ca4b91775ea2b19136
We also have this issue in bugsnag from production (SaaS), one example would be:
The simplest way to reproduce it, without involving Sidekiq workers, is, as Hery discovered:
```
service = Service.find id
service.proxy
------
proxy = Proxy.find id
proxy.destroy
-----
service.destroy!
```
The test of this PR reproduces it with the workers.

[Bugfix] Delete Services through Sidekiq workers

---

lib/system/error_reporting.rb

It adds more info to the log of an error through Rails logger. Few days ago I received this logs from an error: https://gist.github.com/guicassolato/5e8a4c39b95909ca4b91775ea2b19136
It was not in production so I didn't have the information that we have in bugsnag and I really missed it. So this PR makes some useful information to be shown here as well.
There are many ways, but for example:
1. Open Rails Console in test environment to have FactoryGirl available. With `RAILS_ENV=test bundle exec rails console`.
2. Create a service with only basic stuff through `service = FactoryGirl.create(:simple_service)`. It also creates a new provider with very simple data and this is its only service.
3. Do this: …

Improve Rails log error message adding more info

---

lib/system/error_reporting.rb

Reporting error when the `Exception` it receives does not respond to `message` or `backtrace`.
It fixes these bugs: https://circleci.com/gh/3scale/porta/14609 and https://circleci.com/gh/3scale/porta/14612#tests/containers/2

[Bugfix] Report error tries "message" and "backtrace"

---

app/events/applications/application_deleted_event.rb
app/lib/event_store/event.rb
db/migrate/20181130072917_remove_foreign_key_events_accounts.rb
db/oracle_schema.rb
db/schema.rb
test/events/applications/application_deleted_event_test.rb

Fixes https://github.com/3scale/porta/issues/37
Pick the `provider_account_id`, but if it doesn't exist anymore, pick the `tenant_id` 😄 
Fixes https://github.com/3scale/porta/issues/42
When the provider doesn't exist in DB anymore (has been deleted), the event should be saved anyway.
We deleted a provider and all its relationships, but we still want the events of the relationships to be saved (in this case application) to do the correspondent actions once it is deleted (whatever the subscriber tells it to do).

[Bugfix] Applications::ApplicationDeletedEvent is invalid because its provider is already deleted

---

app/controllers/admin/api/accounts_controller.rb
app/models/account/master_methods.rb
app/models/account/provider_methods.rb
test/integration/admin/api/accounts_controller_test.rb

To be able to find an account by provider key or service token.
https://issues.jboss.org/browse/THREESCALE-1562

[accounts#find] find account by provider key or service token

---

lib/api_authentication/by_access_token.rb

Using an read-only access token to update resources is forbidden.
To solve https://issues.jboss.org/browse/THREESCALE-1041, we implemented more logging to understand the cause.
Now it is solved we do not need the logging anymore

Do not send to error logger when API is accessed with RO token

---

lib/tasks/user.rake
test/unit/tasks/user_test.rb

This task was added in https://github.com/3scale/porta/pull/8
There were 2 problems with it:
1. We want it to be done for all type of accounts, which means developers too, not only providers.
2. It took too long and it ended up with the process being killed and nothing done 😞 
This PR fixes those problems.
Run it with `bundle exec rake user:update_all_first_admin_id`

Update first_admin_id of any type of accounts and do better

---

lib/tasks/user.rake

It failed and we don't know why.
We suspect that we should do `update_column` to skip validations and callbacks.
It also takes very long, which is acceptable but not ideal, but we don't want to complicate the code so I just added a `where(first_admin_id: nil)`.

Update where(first_admin_id: nil) and skip validations and callbacks

---

app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
app/helpers/api/integrations_helper.rb
app/models/proxy.rb
app/services/proxy_test_service.rb
config/locales/en.yml
features/provider/integration/edit.feature
features/step_definitions/proxy_steps.rb
test/unit/helpers/api/integrations_helper_test.rb
test/unit/services/proxy_test_service_test.rb

Support Basic (and possibly other) Authorization on APIcast.
I do not intend to finish this PR, but wanted to open it to show it is quite easy to do.
Closes [THREESCALE-430](https://issues.jboss.org/browse/THREESCALE-430)

Basic authentication support for the proxy [THREESCALE-430]

---

app/controllers/admin/api/member_permissions_controller.rb
doc/active_docs/Account Management API.json
vendor/active-docs/app/assets/javascripts/active-docs/templates.coffee

The ActiveDocs documentation for the User Permission Update endpoint introduced in https://github.com/3scale/porta/pull/121 is wrong.
Fixes https://issues.jboss.org/browse/THREESCALE-1703
_Before:_
_After:_
Adds additional parameters `defaultName` and `defaultValue` to ActiveDocs template for "custom" field type to help user understand how it works. Further description of how the API works can be found here: https://access.redhat.com/solutions/3125541
Also pasting it below.
The following endpoints are available for managing member user permissions (`{id}` is the member user ID):
- _User Permissions Read_ `GET /admin/api/users/{id}/permissions.xml`
- _User …

Fix the ActiveDocs documentation for User Permissions Update endpoint

---

.circleci/config.yml

This PR migrates the circleci config from v2.0 to [version 2.1](https://circleci.com/docs/2.0/reusing-config/) 
this is useful so we can start using the latest circleci features, like orbs. 
it will also keep the circleci config a little more DRY.
tests should remain green. not changing anything in the app here. aiming this to be a simple refactoring

Move to CircleCI 2.1 config 

---

lib/developer_portal/app/controllers/developer_portal/buyer/stats_controller.rb
test/functional/developer_portal/buyer/stats_controller_test.rb

It uses the `@applications` instead 😄 
The only places in views where this is used is:

Remove repeated @cinstance variable

---

app/controllers/admin/api/access_tokens_controller.rb
app/models/access_token.rb
doc/active_docs/Account Management API.json
spec/acceptance/api/access_token_spec.rb
test/factories/access_token.rb
test/integration/api/access_tokens_test.rb
test/integration/cms/base_controller_test.rb
test/integration/master/api/finance/accounts/billing_jobs_controller_test.rb
test/integration/master/api/finance/billing_jobs_controller_test.rb
test/integration/stats/data/requests_to_api_test.rb
test/integration/user-management-api/credit_cards_test.rb
test/models/access_token_test.rb

Fixes [THREESCALE-1112](https://issues.jboss.org/browse/THREESCALE-1112)
Some of what is requested was already done before we became open source in https://github.com/3scale/system/pull/8441
```bash
curl -v  POST "http://provider-admin.example.com.lvh.me:3000/admin/api/users/2/access_tokens.json" -d 'name=exampleee&permission=rw&scopes%5B%5D=cms&access_token=47f2128f72ad4b6e494b08f7cecc41a7e22c4a47f6215a7544f773392adf2af7'
```
```bash
curl -v  POST "http://provider-admin.example.com.lvh.me:3000/admin/api/users/2/access_tokens.json" -d 'name=example2&permission=ro&scopes%5B%5D=finance&scopes%5B%5D=stats&access_token=47f2128f72ad4b6e494b08f7cecc41a7e22c4a47f6215a7544f773392adf2af7'
```
The documentation doesn't have `cms` because it is not public and officially unsupported.

[API] Create access token

---

gemfiles/prod/Gemfile
gemfiles/prod/Gemfile.lock

Updating to new version removing the deprecated 3.x version

[gem] Update newrelic_rpm gem to 5.6

---

db/seeds.rb

It ensures the `USER_EMAIL` env var is present (as opposed to provided as an empty string or not provided at all) before setting a default value based on `USER_LOGIN` and provider domain.
The fix follows Option 2 presented by @miguelsorianod at https://github.com/3scale/3scale-operator/pull/12#issuecomment-450836585.
Part of [THREESCALE-1763](https://issues.jboss.org/browse/THREESCALE-1763)

Empty seed USER_EMAIL param/env var

---

app/models/account/states.rb
test/integration/master/api/providers_controller_test.rb
test/unit/account/states_test.rb

Step 3 of https://github.com/3scale/porta/issues/290.
It removes the updates of `deleted_at` from the code. And https://github.com/3scale/porta/pull/295 actually removes the `deleted_at` attribute itself.
It is ok to have it done now because the previous step was a migration and not a task 😄 
https://github.com/3scale/porta/blob/e3b8d3a4f614d8923538c7649dd526087fa91b18/db/migrate/20181105212016_duplicate_deleted_at_state_changed_at.rb#L1-L15

Stop updating deleted_at from Account

---

app/models/proxy_config.rb
db/migrate/20181205131457_extend_proxy_content_size.rb
db/schema.rb
test/unit/proxy_config_test.rb

Fixes https://issues.jboss.org/browse/THREESCALE-1549
When there are too many objects in the proxy, the configuration cannot be saved
TODO in another PR
Databases constraints:
- MySQL database has `MEDIUMTEXT` type (16M chars)
- Oracle database, we set all text as CLOB so virtually no limit
- PostgreSQL database, only has TEXT (virtually unlimited)
Application constraints:
The JSON that the application builds cannot superior than 2 megabytes. If there are too many objects and the generated content is superior than 2 megabytes then the `ProxyConfig` will not be saved.

[db] Allow up to 2MB for proxy_configs content

---

Gemfile.base
Gemfile.lock
config/application.rb
gemfiles/prod/Gemfile.lock

Removing quiet_assets gem as it is already native in Rails 4.2

Quieting natively in 4.2

---

.babelrc
config/webpack/development.js
config/webpack/environment.js
config/webpack/production.js
config/webpack/test.js

Webpacker manages webpack itself, creating config files at compilation time. However this generated configs are being overridden in porta in a hardcoded way that leads to errors and uncontrolled results.
This PR gives this control back to Webpacker and Rails and apply all custom configs appropriately. This way config files look a bit more convoluted but also free us from managing webpack.js files.
Read more about how to manage webpack config with webpacker [here](https://github.com/rails/webpacker/blob/master/docs/webpack.md#webpack).
Thanks to this change we are able to better handle specific setups (dev, test, prod..) as well as reduce duplicated code in a safer and more maintainable way by means of JS.

Removes Babel duplication in Webpack configs

---

app/workers/destroy_all_deleted_objects_worker.rb
config/jobs.rb
lib/tasks/services.rake
test/unit/tasks/services_test.rb
test/unit/three_scale/jobs_test.rb
test/workers/destroy_all_deleted_objects_worker_test.rb

Fixes [THREESCALE-1194](https://issues.jboss.org/browse/THREESCALE-1194)
A cron automatically executed daily that destroys all services marked as 'deleted'.

Cron automatically executed daily that destroys all services marked as 'deleted'

---

config/initializers/oracle.rb
db/migrate/20190104134224_fix_oracle_constraints_references_to_index_names.rb
db/oracle_schema.rb
db/schema.rb

There is a bug in:
https://github.com/rsim/oracle-enhanced/blob/cd14e88a9f1101af7a4087c538249026e2595a7c/lib/active_record/connection_adapters/oracle_enhanced/schema_statements.rb#L288-L296
Oracle references to the first index it finds, which is not necessarily the right one.
We noticed about this issue in https://github.com/3scale/porta/pull/295/ , when removing indexes was not allowed because we had for example the uniqueness constraint of Account `self_domain` being associated to the index of self_domain with deleted_at, which had no uniqueness.
1. Update current unique constraints
2. Patch `add_index` to use the proper index
These are the malformed versions discovered in the other PR.
```ruby
[
{ constraint_name: 'INDEX_ACCOUNTS_ON_DOMAIN',      column_name: 'DOMAIN',      table_name: …
```

[Oracle] Fix unique constraints to reference to the right index

---

app/models/invoice.rb
test/unit/invoice_test.rb

What the title says, it ensures invoices with non-positive cost are cancelled when charged.
Closes [THREESCALE-1420](https://issues.jboss.org/browse/THREESCALE-1420)
- Subscribe to a paid plan (new application)
- Before billing is run, change to a free plan (this will generate a non-positive invoice)
- Charge the invoice
- The invoice should not be charged and its state should change to 'cancelled'

[billing] Cancel non-positive invoices on charge

---

.gitignore
package-lock.json
package.json

Due to a well-known [error in the npm registry](https://npm.community/t/npm-install-downgrading-resolved-packages-from-https-to-http-registry-in-package-lock-json/1818/16), `package-lock.json` is constantly being updated, changing tarball urls from https to http.
This workaround simply replaces all http back to https after lock file is generated. The reason why using `replace` is environment compatibility and ease of use.
Although hacky, this has been pointed out as a secure workaround by npm [(source)](https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285/3).
**Verification**
Run `npm i`, there should be no changes.

Applies a workaround to fix package-lock.json generation

---

features/finance/instant_bill_plan_change.feature

The value of $90.10 asserted in the test to be the expected amount billed for variable cost is actually correct. The pricing rule says "from 100 to infinity" $0.1 should be applied per hit, meaning that up to the 99th hit, it should be free. Therefore, in the case of 1000 hits, it's actually 901 of them that should be charged $0.1 each, in a total of $90.10.
This PR removes a `FIXME` comment in the code that suggested the correct amount to bill should be $90.00 (1000 - 100 = 900 hits * $0.1).

Removes incorrect comment about calculation of variable cost

---

app/javascript/src/Navigation/components/ContextSelector.jsx
app/javascript/src/Policies/actions/UISettings.jsx
app/javascript/src/Stats/lib/metrics_list.jsx
app/javascript/src/Stats/lib/metrics_source.jsx
app/javascript/src/Stats/lib/source_collector.jsx

Fixes Eslint errors that breaks webpack compilation.
Succesfully run `bundle exec webpack:dev`.

Fix Eslint errors

---

app/views/buyers/accounts/_search_results.html.slim
app/views/provider/admin/accounts/new.html.slim
config/abilities/master_admin.rb
config/abilities/master_member.rb
test/unit/abilities/master_admin_test.rb
test/unit/abilities/master_member_test.rb

Update the page to create accounts in the Master Admin Portal to: Create new account
https://issues.jboss.org/browse/THREESCALE-1782
@thomasmaas , please review locally with Master account
Before:
After:

Updating create account text

---

app/helpers/buyers/applications_helper.rb
test/unit/helpers/buyers/applications_helper_test.rb

Fix order of test as explained in https://github.com/3scale/porta/pull/376/files#r248806142
Also the query is from the DB (more efficient) for this:
https://github.com/3scale/porta/blob/098c1fd6ab186c6876c323c56b349a2351f33e2f/app/models/account/buyer_methods.rb#L50-L62

Improve ApplicationsHelper#services_contracted

---

app/models/access_token.rb
lib/api_authentication/by_access_token.rb
test/unit/api_authentication/by_authentication_token_test.rb

https://github.com/3scale/porta/pull/492#discussion_r249470181
It just changes the name of the method to a more accurate one since it returns an instance of `AccessToken` or `nil`

[Rename] AccessToken#by_value -> AccessToken#find_from_value

---

app/helpers/buyers/applications_helper.rb

I've tested the change and it works:
Refactor inject to each_with_object because it doesn't require returning the hash after each execution of the block.

[Refactor] ApplicationsHelper#relation_plans_service is more efficient and simpler

---

app/controllers/admin/api/personal/access_tokens_controller.rb
app/controllers/admin/api/personal/base_controller.rb
app/models/access_token.rb
app/representers/access_tokens_representer.rb
config/routes.rb
doc/active_docs/Account Management API.json
spec/acceptance/api/access_token_spec.rb
test/integration/api/personal/access_tokens_test.rb
test/models/access_token_test.rb

Fixes [THREESCALE-1766 - Improve the API endpoints of access token](https://issues.jboss.org/browse/THREESCALE-1766)
The system/ruby team had a meeting about this and I will explain here what we decided. We also informed product about this.
We have only 1 API endpoint for access tokens but we have much more in the UI. The API endpoint that we have right now was created years ago before we were open source in https://github.com/3scale/system/pull/8441 but it was not documented and officially not supported and we documented it and made it public recently in https://github.com/3scale/porta/pull/430
This endpoint right now is under the URL `provider-url/admin/api/users/:user_id/access_tokens`. An officially documented that customers can authenticate through access token and we will allow to …

[API] Access Token endpoints

---

app/controllers/admin/api/access_tokens_controller.rb
app/controllers/admin/api/personal/access_tokens_controller.rb
doc/active_docs/Account Management API.json

Change the `values values` in the description for just `values` as @guicassolato noticed in https://github.com/3scale/porta/pull/492#discussion_r249798484

Fix ActiveDocs description for Access Token Create

---

app/workers/delete_object_hierarchy_worker.rb
config/application.rb
test/integration/service_not_deleted_test.rb
test/workers/delete_object_hierarchy_worker_test.rb
test/workers/delete_plain_object_worker_test.rb

Some services are not being deleted because of "ghost" workers. Besides `..delete_object..` workers there are others, backend related. Those workers could be still in the queue when `batch_success_callback` is being called. Therefore, `service` (main object) wouldn't get destroyed at all. To fix that we implement `on_complete` batch callback that destroy the main object + we manually call `on_success` once batch is blank, if batch still contain some jobs, we'll retry the job after 5 minutes.

[Bugfix] Service is not being deleted 

---

db/migrate/20190110095221_remove_accounts_deleted_at.rb
db/oracle_schema.rb
db/schema.rb

Step 3 of https://github.com/3scale/porta/issues/290
Depends on https://github.com/3scale/porta/pull/476, which stops the updates of `deleted_at` in DB.
Removes all the `deleted_at` attribute from Account from the DB.
Infrastructure issue to do it in SaaS before merging this PR in https://github.com/3scale/infrastructure/issues/604

Removes all the deleted_at attribute from Account from the DB.

---

app/controllers/admin/api/services_controller.rb
doc/active_docs/Account Management API.json
test/integration/admin/api/services_controller_test.rb

We were asked if it is possible to set the description of a service through the API, which it is, so this PR just adds the param in the ActiveDocs and adds some tests for that param 😄

[API] Service create/update with documentation and test for the 'description' param

---

app/models/account.rb

Tell ActiveRecord to remove a column from the cache first
Deploy the code
Then actually remove it from the Database
https://blog.codeship.com/rails-migrations-zeo-downtime/
Need by #546

[safe-migration] Programmatically reject the columns we are going to delete

---

app/workers/delete_object_hierarchy_worker.rb

Remove this reporting to Bugsnag because it is done for every time we call to `DeleteObjectHierarchyWorker` and for each of its associations. It is too overwhelming.

Remove reporting to Bugsnag for each perform of DeleteObjectHierarchyWorker with associations

---

app/models/account.rb
app/models/account/gateway.rb
test/unit/account_test.rb

- Added a test
- Doing it in a single place so table columns are not retrieved again.

[fix] Use only one place to reject columns

---

app/events/zync_event.rb
test/events/zync_event_test.rb
test/workers/zync_worker_test.rb

Fixes https://github.com/3scale/porta/issues/538
The application does not need the proxy to delete in Zync, so when it is a deleted application, it's only dependency is the Service, which exists.

[Bugfix] Deleted Cinstance does not have the Proxy dependency for Zync anymore

---

app/workers/purge_old_events_worker.rb

The batch control over a potentially very large unindexed table is causing the job to last a long time to finish and we don't really need a batch to control that job.

Removes batch wrapping from PurgeOldEventsWorker

---

openshift/system/contrib/scl_enable

the `NODEJS_SCL` environment variable is available on the software collections base image we are using and [was recently updated to nodejs 10](https://github.com/sclorg/s2i-base-container/blob/master/base/Dockerfile#L10) from [nodejs8 that it used to be](https://github.com/sclorg/s2i-base-container/blob/f517f392bdeb32903fb44dd9ccf3ce14a0ff4281/base/Dockerfile#L10). 
Fixes https://github.com/3scale/porta/issues/563
1. failing: run a docker build, using the brew pulp internal repository as the source of your `rhscl/ruby-23-rhel7:2.3` image. 
2. substitute hard-coded version with env var
3. passing: rerun docker build
the [base image we are …

Fixed hard-coded nodejs version

---

app/models/account.rb
app/models/account/states.rb
app/models/application_plan.rb
app/models/contract.rb
app/models/service.rb
app/workers/stale_account_worker.rb
app/workers/suspend_inactive_accounts_worker.rb
test/unit/account/states_test.rb
test/unit/account_test.rb
test/unit/application_plan_test.rb
test/unit/contract_test.rb
test/unit/service_test.rb
test/workers/stale_account_worker_test.rb
test/workers/suspend_inactive_accounts_worker_test.rb

Fixes [THREESCALE-1836 - Exceptions for automatic suspension and deletion of inactive providers](https://issues.jboss.org/browse/THREESCALE-1836)
Since https://github.com/3scale/porta/pull/17 we automatically suspend and destroy inactive tenants.
Now there are some situations where we do not want to automatically suspend (neither delete) inactive accounts.

Exceptions for automatic suspension and deletion of inactive providers

---

app/models/service.rb

Fixes https://github.com/3scale/porta/issues/578
It does the removal like for all the other relationships with `dependent: :destroy`. The `DeleteObjectHierarchyWorker` fetches all the relationships with this option and will do it in parallel 😄

Destroy Service has_many features in parallel

---

app/javascript/src/Policies/index.jsx

Fixes a bug presented in the proxy integration page when using IE11
* Using whatwg-fetch polifyll with our redux RSSA calls
* Since
https://github.com/agraboso/redux-api-middleware/releases/tag/v2.0.0 it
stop using isomorphic-fetch
* Breaks otherwise with browsers nos supporting or having an old
implementation of fetch standard
fixes https://issues.jboss.org/browse/THREESCALE-1711
1. Set up 3scale 2.4
2. Integrate an API in a tenant account
3. Go to API > Configuration > POLICIES

[Policies] Fix policiy chain in IE11

---

app/lib/account_deletion_config.rb
config/initializers/features.rb
test/unit/account_deletion_config_test.rb
test/workers/stale_account_worker_test.rb
test/workers/suspend_inactive_accounts_worker_test.rb

This test fails sometimes in CircleCI:
https://github.com/3scale/porta/blob/bccc4581cc76b46c625c4db778e96c54cfd57e45/test/workers/suspend_inactive_accounts_worker_test.rb#L42
The reason is it happens when the tests of this class are executed first:
https://github.com/3scale/porta/blob/bccc4581cc76b46c625c4db778e96c54cfd57e45/test/unit/account_deletion_config_test.rb#L5
Now AccountDeletionConfig is a class configured by an initialiser 😄

Fix CircleCI Tests: AccountDeletionConfig used to be tested leaving stubbed a wrong config

---

app/controllers/buyers/service_contracts/bulk/change_plans_controller.rb
test/integration/buyers/service_contracts/bulk/change_plans_controller_test.rb

Fixes https://github.com/3scale/porta/issues/581
`application` there should be `contract` so it is the same as the block param. Like in https://github.com/3scale/system/commit/9a0f7ad01e763ab41f2124d09d68fc1aa10155a6#diff-e7f50001751092bfdfdd9c38ffd9e82fR16

[Bugsnag] NameError ChangePlansController#create undefined 'application'

---

app/indices/account_index.rb
test/unit/account/search_test.rb

Fixes [THREESCALE-996 - Search engine doesn't show a result when searching by user key](https://issues.jboss.org/browse/THREESCALE-996)
Sphinx is not indexing the `user_key` properly. We are using a `GROUP_CONCAT` with a limit of 1024 characters for all the user keys of the account, which is not enough, so that's why some of them can be found and some can not. This is not the first time it happens, so the solution in the code is this one:
https://github.com/3scale/porta/blob/bccc4581cc76b46c625c4db778e96c54cfd57e45/app/models/account/search.rb#L19-L27
https://github.com/3scale/porta/blob/bccc4581cc76b46c625c4db778e96c54cfd57e45/app/models/account/search.rb#L37-L41
https://github.com/3scale/porta/blob/bccc4581cc76b46c625c4db778e96c54cfd57e45/test/unit/account/search_test.rb#L100-L112
That …

[Bugfix] Search engine doesn't always show a result when searching by user key

---

app/helpers/mailers_helper.rb
app/views/provider_user_mailer/activation.text.erb
app/views/provider_user_mailer/activation_reminder.text.erb
app/views/provider_user_mailer/lost_domain.text.erb
app/views/provider_user_mailer/provider_lost_password.text.erb
test/unit/mailers/provider_user_mailer_test.rb

Improving perception of customer so they know emails come from Red Hat 3scale.
Takes care of https://issues.jboss.org/browse/THREESCALE-1883
Emails can be triggered from the product, only SaaS is affected:
- activation: create a new account
- activation reminder: 3 days without activating the account
- password reminder: click on forgot password
- domain reminder: click on forgot domain (not sure if this exists anymore?)
Emails should say 'Red Hat 3scale' instead of only '3scale' and all references to '3scale' by itself should have been removed.

Threescale 1883

---

app/models/finance/postpaid_billing_strategy.rb
features/finance/automatic_billing_postpaid.feature
features/finance/automatic_billing_prepaid.feature
features/step_definitions/plans/plans_steps.rb

This PR prevents negative invoices from being generated on plan change on postpaid. This issue was fixed in the past for prepaid, but on postpaid billing mode, whenever a plan change happens from a more expensive plan to a less expensive one before billing runs for the contract for the first time, a negative amount invoice is generated. This is because the contract was never billed for the more expensive plan but a refund is issued anyway.
[THREESCALE-995](https://issues.jboss.org/browse/THREESCALE-995)
1. Define an application Plan A with monthly cost $200
2. Define a second application Plan B with monthly cost $50
3. Signup for Plan A
4. Change plan from A to B
5. If it's the first day of …

[billing] Fix negative invoices on plan downgrade on postpaid

---

config/locales/en.yml
features/provider/integration/edit.feature

Changing "As HTTP Basic Authorization" to "As HTTP Basic Authorization"
https://issues.jboss.org/browse/THREESCALE-1922
Go to Service integration > Edit APIcast configuration > Authentication settings > Credential locations
One label  should be set to  "As HTTP Basic Authentication"

Fixes THREESCALE-1922: Typo for HTTP Basic Authentication

---

app/controllers/admin/api/service_contracts_controller.rb

ServiceContracts belongs to `Account Management API`, but it is not specifically specified so right now it is correct but when I added a new API for https://github.com/3scale/porta/pull/593 and I generate the docs, this automatically goes there because it is not specifically defined, and that would be wrong.
I make a PR specifically for this because it is a bit unrelated to the other PR, just a side effect of it, and as it is already big and complicated enough, it is better to have this separately.

[Docs] Specify that ServiceContracts belongs to Account Management API

---

app/javascript/src/Dashboard/components/ApiFilter.jsx
app/javascript/src/Navigation/components/ContextSelector.jsx
app/javascript/src/Types/ReactWrapper.jsx
app/javascript/src/Types/index.js
app/javascript/src/utilities/createReactWrapper.jsx

We render React components in rails by using a `ReactWrapper` function. It simply is a function that gets the props and a element id and calls `React#render`.
However Codeclimate has been complaining since the wrapper has grown in complexity (undefined-check for `document#getElementById`).
By encapsulating this logic, Codeclimate won't complain again.
1. Codeclimate does not complain when adding new Components in rails.
2. Components render as expected (like ContextSelector and ApiSearch)

Fixes Codeclimate by encapsulating ReactWrapper

---

app/lib/finance/fixed_fee.rb
app/lib/finance/setup_fee.rb
app/models/contract.rb
app/models/finance/billing_strategy.rb
app/models/finance/postpaid_billing_strategy.rb
app/models/line_item.rb
features/finance/automatic_billing_postpaid.feature

Refactors `Finance::PostpaidBillingStrategy#bill_plan_change` to use `Contract#bill_for` instead of duplicating logic.
It also introduces another test for plan changes in the middle of the day, specially targeting Postgres timestamp and ordering issues.
Related to https://github.com/3scale/porta/pull/588

[billing] Refactor postpaid plan change

---

config/docker/database.yml
config/examples/database.yml
openshift/system/config/database.yml

This PR fixes the setting of the postgres database timezone.
Some tests involving date comparison may pass on local (development) environment where TZ is other than UTC but still fail in CI. Example: https://github.com/3scale/porta/blob/2bb337a7a71bd1c116b0439dbcbe4eef2c5dde42/features/finance/automatic_billing_postpaid.feature#L78-L99
**Special notes for the reviewer**
This was originally considered as a fix for tests later known to be failing not because of timezone but rather due to Postgres timestamp/ordering issues. See https://github.com/3scale/porta/pull/617.

Postgres timezone setting

---

test/unit/account/search_test.rb

This PR fixes 2 issues of the same test:
1. It makes the user_key to have 256 characters (the default one has 32 characters), which is the maximum allowed for that attribute. This way we ensure we are indexing `256 * 5 = 1280`, which is more than the default `1024`.
2. The test is sometimes failing in CircleCI, as it if it wasn't indexed. The problem is not the execution code itself but an issue in the test that this PR fixes (the `ThinkingSphinx::Test.config`)

[Bugfix][Test] search user_key without keyword with many records is always indexed and found

---

app/helpers/api/integrations_helper.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
config/locales/en.yml

When choosing service mesh deployment option, the labels should use "Istio" and not "APIcast"
This is a small quick fix.
Before:
After:

Configurable deployment option labels for APIcast and Service Mesh

---

app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee

Adds class `hidden` to cred forms whenever _HTTP Basic Authentication_ option is selected.
[THREESCALE-1840: Header undefined when choosing HTTP Authentication in service integration](https://issues.jboss.org/browse/THREESCALE-1840)
1. Integration -> Configuration -> Edit APIcast settings
2. (With User Key auth mode) Change _Credentials location_, verify user-key hides when _HTTP Basic Auth_ is selected
3. (With App ID and App Key pair) Change _Credentials location_, verify app-id, app-key hides when _HTTP Basic Auth_ is selected

[THREESCALE-1840] Hide credentials forms when HTTP Basic Authentication es selected

---

gemfiles/prod/Gemfile.lock

I did `make bundle` after adding a Gem in https://github.com/3scale/porta/pull/593 and it also updated Nokogiri for this Gemfile. But it does not belong to that PR as said in [here](https://github.com/3scale/porta/pull/593#discussion_r257736973).

Update newrelic_rpm in Prod Gemfile

---

app/lib/finance/variable_cost.rb
app/models/contract.rb
app/models/finance/prepaid_billing_strategy.rb
app/observers/billing_observer.rb
features/finance/variable_cost.feature
features/step_definitions/account_steps.rb
features/step_definitions/plans/application_plans_steps.rb
features/step_definitions/timecop_steps.rb

This PR fixes an edge case of applications that signup on the last day of the month and generate variable cost on the first day of contract. Automated billing process fail to account the hits of this last day of the month.
This is initially because `variable_cost_paid_until` is `nil` when billing runs for the first time and gets replaced by `trial_period_expires_at || created_at` (the signup timestamp). A safe guard conditional of `Finance::VariableCost::bill_for_variable` that prevents paid contracts from being billed in duplicity performs a date comparison between `variable_cost_paid_until` and the end of billing period. Since the signup day in this case coincides with the end of the period, the variable cost is not accounted. In the month after …

[billing] Fix variable cost of new contracts on the last day of month

---

openshift/system/config/settings.yml

When making a request from internal pods to system-app in OpenShift we use system-master, system-provider or system-developer services.
Those requests are using plain HTTP. Other requests should use HTTPS.
Any other requests coming from system-* host will be redirected to SSL
Fixes https://issues.jboss.org/browse/THREESCALE-940

THREESCALE-940 Forbid bypassing SSL when host starts with system-

---

.circleci/config.yml
.eslintrc
package.json
spec/javascripts/Stats/metrics_source.spec.js
spec/javascripts/Stats/source.spec.js
spec/javascripts/Stats/source_collector.spec.js
spec/javascripts/__mocks__/c3.js

It divides current `lint` job into 3: `lint`,  `karma` and `jest` to make it more clean and maintainable.
Also adds a new `lint` script to package.json so that *eslint* checks both source and specs.
CircleCI should run these 3 jobs successfully.

Extract Karma and Jest tests from Lint job in CircleCI

---

config/docker/thinking_sphinx.yml

Make sphinx outputs log in /dev/stdout when using docker
Otherwise it will grow the log file indefinitely
Fixes https://issues.jboss.org/browse/THREESCALE-1728

[sphinx] Logs output to STDOUT when using docker

---

lib/developer_portal/app/controllers/developer_portal/swagger/spec_controller.rb
test/integration/developer_portal/swagger/spec_controller_test.rb

If passing a non-existent swagger spec identifier it raises a 503 for the spec.json in developer portal

[developer-portal] Swagger spec should return a 404 if not found

---

app/models/web_hook/event.rb
test/unit/web_hook/event_test.rb
test/workers/web_hook_worker_test.rb

This is random test failure, if created_at and updated_at are in the same millisecond then the guess_event won't work.
When saved in database, Rails does not keep the micro seconds.

[fix] Random test failures on comparing dates without microseconds

---

app/controllers/api/integrations_controller.rb
app/models/cms/email_template.rb
app/models/oidc_configuration.rb
app/models/proxy.rb
app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
config/locales/en.yml
db/migrate/20190225170501_create_oidc_configurations.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
lib/system/database/definitions/mysql.rb
lib/system/database/definitions/oracle.rb
lib/system/database/definitions/postgres.rb
lib/tasks/multitenant/triggers.rake
test/integration/api/integration_test.rb
test/models/oidc_configuration_test.rb
test/unit/proxy_test.rb

When OIDC is selected as authentication method, 4 checkboxes appear at APicast's Authentication Settings with the following options:
* Authorization Code flow [selected by default]
* Implicit Flow Enabled
* Service Accounts Enabled (Client Credentials flow)
* Direct Access Grants Enabled (Resource Owner Password Credentials flow)
[THREESCALE-1947: Configure OAuth flows in the UI](https://issues.jboss.org/browse/THREESCALE-1947)
[THREESCALE-1949](https://issues.jboss.org/browse/THREESCALE-1949)
1. Make sure OpenID Connect is enabled in **rolling_updates.yml** (`apicast_oidc: true`)
2. Go to Integration > APIcast configuration > Select _OpenID Connect_
3. Go to Integration > Integration …

[THREESCALE-1947/THREESCALE-1949] adds checkboxes for oidc auth options

---

app/models/cinstance.rb
app/models/oidc_configuration.rb
app/models/service.rb
app/representers/cinstance_representer.rb
app/representers/oidc_configuration_representer.rb
test/integration/user-management-api/applications_test.rb
test/test_helpers/xml_assertions.rb
test/unit/service_test.rb

Closes [THREESCALE-1948](https://issues.jboss.org/browse/THREESCALE-1948)
Zync needs to know which flows are enabled. Zync queries the  "/admin/api/applications/find.json" endpoint to configure the RH SSO correctly by application.
Implementation would be to send another field in the response (JSON/XML) corresponding to `oidc_configuration` as described in https://www.keycloak.org/docs-api/4.8/rest-api/index.html
Example:
```
"oidc_configuration": {
"service_accounts_enabled": true,
"standard_flow_enabled": false,
"implicit_flow_enabled": true,
"direct_access_grants_enabled": true				
}
```

[api] Applications should return oidc_configuration if service is using OIDC

---

app/controllers/admin/api/application_plans_controller.rb
doc/active_docs/Account Management API.json
test/integration/admin/api/application_plans_controller_test.rb

Allow updating extra Application Plan values from system API.
https://issues.jboss.org/browse/THREESCALE-1868

[THREESCALE-1868] more default parameters for api#applications_plan

---

test/unit/account/search_test.rb

There is a random failure happening on CircleCi. Hard to reproduce locally.
Adding more verbosity so I can see what is happening next time it fails to fix it
```
Failure:
Minitest::Result#test_search_user_key_without_keyword_with_many_records_is_always_indexed_and_found [/opt/app-root/src/project/test/unit/account/search_test.rb:129]
Minitest::Assertion: Expected: [3]
Actual: []
```

[random-test-failure] Use verbose: true for diagnostic

---

Gemfile.base
Gemfile.lock
app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
app/controllers/api/integrations_controller.rb
app/models/proxy_rule.rb
app/views/api/integrations/apicast/shared/_mapping_rule.html.erb
app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
features/old/proxy.feature
features/step_definitions/proxy_steps.rb
gemfiles/prod/Gemfile.lock
test/integration/api/integration_test.rb
test/unit/apicast/proxy_source_test.rb
test/workers/delete_plain_object_worker_test.rb

Depends on #658
Feature: Sort mapping rules + last called
fixes https://issues.jboss.org/browse/THREESCALE-1787
1. Visit APIcast configuration page
2. Play with the order of the mapping rules
3. Profit!
* Done the easiest way
* This is meant to be removed in the near future favoring an entire page craft in React using APIcast json schema config.
TODO:

[Mapping Rules] Sorting mapping rules

---

app/controllers/admin/api/registry/policies_controller.rb
config/routes.rb
doc/active_docs/Policy Registry API.json
test/integration/admin/api/api_docs_services_controller_test.rb
test/integration/admin/api/registry/policies_controller_test.rb

It defines an endpoint to show a provider's custom policy registry.
Closes [THREESCALE-1986](https://issues.jboss.org/browse/THREESCALE-1986)

[API] Endpoint to show custom policy

---

app/controllers/admin/api/policies_controller.rb
app/models/account/provider_methods.rb
app/models/policy.rb
app/services/policies/policies_list_service.rb
app/views/api/integrations/apicast/shared/_policies.html.slim
test/integration/user-management-api/policies_test.rb
test/unit/services/policies/policies_list_service_test.rb

Closes [THREESCALE-1987](https://issues.jboss.org/browse/THREESCALE-1987)
When provider can use custom policies, those policies are merged to the builtin ones

[policy] THREESCALE-1987 Merge builtin policies with custom ones

---

app/models/plan.rb

This test was failing `bundle exec m test/integration/api/application_plans_controller_test.rb:43`

[Test failure] Fixes acts_as_list using the first issuer regardless of the type

---

features/old/proxy.feature
features/step_definitions/proxy_steps.rb

Fix bug for Oracle DB for the feature done in https://github.com/3scale/porta/pull/530.
An example of this bug is in https://circleci.com/gh/3scale/porta/35439#tests/containers/11
It makes sense because we can not promise the ID that the metric will have, and it does not give useful info to the user for being a cucumber feature anyway 😄

[Bugfix][Cuke] Check metric of sorted mapping rules by Name instead of ID

---

app/events/notification_event.rb
app/events/services/service_deleted_event.rb
app/lib/event_store/repository.rb
app/mailers/notification_mailer.rb
app/subscribers/service_deleted_subscriber.rb
app/workers/backend_delete_end_users_worker.rb
test/events/services/service_deleted_event_test.rb
test/functional/master/api/services_controller_test.rb
test/mailers/notification_mailer_test.rb
test/subscribers/service_deleted_subscriber_test.rb
test/test_helpers/backend.rb
test/unit/services/notification_delivery_service_test.rb
test/workers/backend_delete_end_users_worker_test.rb
test/workers/process_notification_event_worker_test.rb

Part of [THREESCALE-1164 - Delete objects in Backend when the Provider is completely deleted for real](https://issues.jboss.org/browse/THREESCALE-1164)
Delete all end users of a Service when the Service is completely removed from System 😄

Destroy EndUsers of a Service when the Service is destroyed

---

test/integration/admin/api/api_docs_services_controller_test.rb

Sometimes, depending on the tests run before Service.find(200) exists ...
So the test will not fail

Fix random failure due to fixed id in the test

---

app/controllers/admin/api/services_controller.rb
test/integration/admin/api/services_controller_test.rb

Service cannot be deleted with provider key.
https://issues.jboss.org/browse/THREESCALE-1917

[THREESCALE-1917] service should be deleted with api key

---

app/controllers/admin/api/registry/policies_controller.rb
app/representers/policies_representer.rb
config/routes.rb
doc/active_docs/Policy Registry API.json
test/integration/admin/api/registry/policies_controller_test.rb

It defines a new endpoint in the API to list the provider's custom policies.
Closes [THREESCALE-2007](https://issues.jboss.org/browse/THREESCALE-2007)

[API] Endpoint to list custom policies

---

.circleci/config.yml
Gemfile.base
config/docker/database.yml
config/docker/thinking_sphinx.yml
config/examples/database.yml
config/thinking_sphinx.yml
lib/tasks/ci/db.rake
openshift/system/config/database.yml

This PR removes any reference to the environment variable `DB` in porta, making it depend always and only on `DATABASE_URL` instead.
Safe defaults remain in place for mysql database (all environments).
Deployments that depend on `config/examples/database.yml`, in test environment, will automatically have the value of the `TEST_ENV_NUMBER` env var appended to the value of `DATABASE_URL` (thus modifying the  name of the database)
Without this, while using openshift templates, either
1) `DB` (environment variable) needs to come from a deployment parameter just like, independently, other database connection details (username, password); _OR_
2) multiple versions of the templates would have to be maintained (one per …

Remove DB env var

---

app/controllers/admin/api/registry/policies_controller.rb
config/routes.rb
doc/active_docs/Policy Registry API.json
test/integration/admin/api/registry/policies_controller_test.rb

It defines a new endpoint in the API to delete a provider's custom policy.
Closes [THREESCALE-2008](https://issues.jboss.org/browse/THREESCALE-2008)
Update and delete actions for policies can be considered unsafe because a policy may be in use. We should either freeze and forbid modification in policies currently in use and/or implement a `force` attribute to these state-modifier endpoints.

[API] Endpoint to delete custom policies

---

app/controllers/admin/api/registry/policies_controller.rb
config/routes.rb
doc/active_docs/Policy Registry API.json
test/integration/admin/api/registry/policies_controller_test.rb

It defines a new endpoint in the API to update a provider's custom policy registry.
Closes [THREESCALE-1986](https://issues.jboss.org/browse/THREESCALE-1986)
Update and delete actions for policies can be considered unsafe because a policy may be in use. We should either freeze and forbid modification in policies currently in use and/or implement a `force` attribute to these state-modifier endpoints.

[API] Endpoint to update custom policy

---

app/controllers/admin/api/application_plan_limits_controller.rb
doc/active_docs/Account Management API.json
test/integration/admin/api/application_plan_limits_controller_test.rb

Page renders slow so a pagination has to be added.
https://issues.jboss.org/browse/THREESCALE-1980

[THREESCALE-1980] pagination for application plan limits

---

app/workers/publish_enabled_changed_event_for_provider_applications_worker.rb

So if someone creates, approves and destroys very quickly, there is nothing we can do 😄 
Fixes [THREESCALE-2034](https://issues.jboss.org/browse/THREESCALE-2034)

Ignore DeserializationError in PublishEnabledChangedEventForProviderApplicationsWorke when account is already deleted

---

app/models/proxy.rb
test/unit/services/apicast_v2_deployment_service_test.rb

So that APIcast can use the correct ordering to stop matching the rule
Closes [THREESCALE-1344](https://issues.jboss.org/browse/THREESCALE-1344)

[proxy config] Return proxy rules ordered by position

---

app/models/settings.rb
test/integration/provider/admin/accounts_controller_test.rb
test/unit/abilities/end_users_test.rb
test/unit/logic/provider_signup_test.rb
test/unit/settings_test.rb
test/unit/signup/account_manager_test.rb

It globally  denies end_users feature for on-premises
Closes [THREESCALE-1927](https://issues.jboss.org/browse/THREESCALE-1927)

[end_users] Removal of End-users feature in on-prem

---

package-lock.json
package.json
spec/javascripts/Policies/components/PolicyConfig.spec.jsx

After upgrading to `1.3` our specs are failing due to this change: https://github.com/mozilla-services/react-jsonschema-form/commit/59038c0ce0f9f215e78e0f730d9e6138b5dcbf20#diff-07a63ede6fe55fca89398d42da737369R154
The problem is solved by simply updating our mock.

Bumps react-jsonschema-form version to 1.3

---

.circleci/config.yml
package.json

Flow typings are not required for porta to work, they only make sense for development and in order to `npm lint` to pass.
This PR is moving the `flow-typed install` step directly to `lint` job and using a cache.

Removes flow-typed install from standard install

---

.circleci/config.yml
Rakefile
openshift/system/Dockerfile
openshift/system/Dockerfile.on_prem

`npm install` is run twice during each workflow, in `dependencies_npm` and `assets_precompile` jobs.
It takes a lot of time to complete even if modules are present. However, NPM modules can be safely shared between jobs and workflows until package-lock.json changes.
This way we can reduce the times it is run to the minimum, by using CircleCI cache properly.
Also `npm dedupe` is run twice, one during `dependencies_lint` and then again in `lint`. Simplified structure will be already stored in the cache therefore license_check should not complain about duplicated dependencies.

Remove duplication of npm install and npm dedupe in CircleCI

---

app/workers/create_service_token_worker.rb
test/workers/create_service_token_worker_test.rb

Fixes [THREESCALE-2048](https://issues.jboss.org/browse/THREESCALE-2048)
What happened is a customer created and deleted a service very quickly (several times), and when a service is created, we also create an event with the service just created and with the user who did it:
https://github.com/3scale/porta/blob/245555bbef2f265cec806a8a6f40152a1ce57e66/app/events/services/service_created_event.rb#L7-L8
Later we asynchronously perform `CreateServiceTokenWorker`:
https://github.com/3scale/porta/blob/245555bbef2f265cec806a8a6f40152a1ce57e66/app/events/services/service_created_event.rb#L22-L24
So if by the time that `CreateServiceTokenWorker` is performed, the service does not exist anymore, it raises `ActiveJob::DeserializationError` with the proper error message, and it makes sense because …

[Bugfix] CreateServiceTokenWorker rescue ActiveRecord::RecordNotFound & ActiveJob::DeserializationError

---

gemfiles/prod/Gemfile.lock

It bumps yard version to 0.9.18 in production. Deploys using `gemfiles/prod/Gemfile` will fail until this gets merged.
Missing in https://github.com/3scale/porta/pull/641

Bumps yard version in prod

---

app/assets/stylesheets/provider/_tables.scss

Metrics with very long names break the design of tables
https://issues.jboss.org/browse/THREESCALE-1382
1) Define metric(s) with very long `name`, `system name` and `units` name 
2) Define `pricing rules` and `limits`for the metric(s)
3) Go to API > Applications > Listing > Your App name
**Before:**
---
**After:**

THREESCALE-1382: Adjusting word break in very large words

---

app/lib/logic/plan_changes.rb
app/mailers/mail_preview.rb
app/observers/message_observer.rb
app/services/notifications/new_notification_system_migration.rb
test/integration/admin/api/buyers_applications_controller_test.rb
test/unit/observers/cinstance_observer_test.rb
test/unit/observers/message_observer_test.rb
test/unit/services/notifications/new_notification_system_migration_test.rb

This PR makes application plan changes performed by the provider through the API to send a notification message to the buyer as well, as it does when performed in the Admin Portal.
Closes [THREESCALE-923](https://issues.jboss.org/browse/THREESCALE-923).

Email to developer on plan change performed via API

---

app/models/policy.rb
app/models/proxy.rb
config/locales/en.yml
test/integration/admin/api/registry/policies_controller_test.rb
test/unit/policy_test.rb
test/unit/proxy_test.rb

It freezes a policy in use by any proxy of the provider so the policy cannot have its attributes name, version or schema modified, neither deleted.
Closes [THREESCALE-2097](https://issues.jboss.org/browse/THREESCALE-2097)
**Special notes for the reviewer**
Why not to use `attr_readonly :name, :version, :schema` on `Policy`?
1. It is not conditional
2. It does not raise errors – just prevents modifications silently

Prevents policies in use from being modified

---

test/unit/account/search_test.rb

Temporarily skipped so it is not blocking everyone's PR until we fix it for [THREESCALE-2130](https://issues.jboss.org/browse/THREESCALE-2130)

Skip test that randomly fails in CircleCI for: search user_key without keyword with many records is always indexed and found

---

.circleci/config.yml

Since https://github.com/3scale/system-builder/pull/5 has been merged, we can move back to `latest` tag, which is automatically built by Quay.io trigger, from https://github.com/3scale/system-builder/ `master` branch.
Fixes https://github.com/3scale/porta/issues/715
If pipeline is green, we are good. 

move away from manually built builder image

---

.gitignore
config/application.rb
config/docker/message_bus.yml
config/examples/message_bus.yml
config/initializers/message_bus.rb
openshift/system/config/message_bus.yml

It makes message bus settings configurable. This is specially important for redis configuration not to enforce logical db '8', which is causing problems to setup 3scale with Redis Cluster/Enterprise.
**What issue(s) this PR fixes**
Closes [THREESCALE-2161](https://issues.jboss.org/browse/THREESCALE-2161)
1. ~We're still using `REDIS_URL` env var here. Perhaps define a separate one?~
2. We could maybe fallback to System's default redis config in case Message Bus is enabled and missing some specific redis config for it (?).
----
_Important!_ We need to ensure the proper configurations are in place before deploying this.

Configurable message bus settings

---

config/jobs.rb

After what happened today in SaaS, we need some days of margin to find a real solution to this problem.

Do not automatically destroy tenants that are scheduled for deletion

---

package.json

Relates to https://github.com/3scale/porta/pull/454
The issue is solved https://npm.community/t/some-packages-have-dist-tarball-as-http-and-not-https/285
Requirement is using npm 6+
Then
```
rm -rf ./node_modules
npm cache clean --force
npm install
```

[npm] Remove postshrinkwrap

---

app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
app/views/api/integrations/apicast/shared/_mapping_rule.html.erb
app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
config/locales/en.yml

Adds a ⚠️ icon inside Mapping Rules' _pattern_ input that shows up when its value equals `/`, meaning it is a "Catch All" Mapping Rule.
The warning won't show up when the input is empty since that's a wrong value and wouldn't be saved.
It is rendered first time by ruby then refreshed on `keyup` event by Javascript.
> NOTE: It's not clear in the gif but the icon is grayed only when the input is disabled.
[THREESCALE-1861 Distinguished styling & info for catch-all mapping rules](https://issues.jboss.org/browse/THREESCALE-1861)
1. Go to API > Integration > Configuration > Edit > Mapping Rules
1. All patterns matching `/` should have a warning icon with a tooltip
1. Edit and try different values …

Adds warning styling & info for catch-all mapping rules

---

doc/liquid/drops.md
lib/developer_portal/lib/liquid/drops/provider.rb

For information, after modifying the file, we regenerate the documentation with `rake doc:liquid:generate`

Fix typo in doc of provider.logo_url drop

---

config/docker/message_bus.yml
config/docker/redis.yml
config/examples/message_bus.yml
config/examples/redis.yml
config/initializers/message_bus.rb
config/initializers/redis.rb
config/initializers/sidekiq.rb
lib/system/redis_pool.rb
openshift/system/config/message_bus.yml
openshift/system/config/redis.yml
test/unit/redis_with_namespace_test.rb

It makes possible to enforce namespaces for all sidekiq and message_bus redis keys, so system can work with a single redis db without risk of key collision. This is not particularly relevant for the scenario where sidekiq and message_bus red/write to different redis instances/dbs, however it is a safe measure for the scenario where those components work on the same redis instance and same redis db, such when using Redis Entrerprise/Cluster.
Closes [THREESCALE-2173](https://issues.jboss.org/browse/THREESCALE-2173)
message_bus is not compatible with redis-namespace OOTB, so we either monkey patch it or create our own fork of the gem.

Namespaces for sidekiq and messsage_bus redis keys

---

app/views/api/services/forms/_integration_settings.html.slim

fixes https://issues.jboss.org/browse/THREESCALE-1876?focusedCommentId=13714771&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13714771
in onprem `Rails.application.config.three_scale.apicast_oauth` is set to `true`, in saas it's set to `false`. I believe we might actually remove the whole `apicast_oauth` var but that's for another pull request.

js check for oidc without conditional

---

app/workers/find_and_delete_scheduled_accounts_worker.rb
config/jobs.rb
test/workers/find_and_delete_accounts_scheduled_worker_test.rb

Otherwise tenants won't be destroyed at all for on-prem.
We need to fix the problem of destroying many at once for SaaS before enabling it for SaaS.

Enable for on-prem the deletion of accounts scheduled for deletion

---

package-lock.json
package.json

* It was introduced by https://github.com/3scale/porta/pull/454
* The postshrinkwrap was removed here: https://github.com/3scale/porta/pull/730
Removes an unused lib.
None. This is a maintenance PR.

[npm] Replace is not needed anymore

---

package.json

Current version of node-sass solves it doing it in build.js and install.js packages
called from package.json scripts
Cleaning our scripts.
None. Maintenance task.

[npm] No need of postinstall

---

app/controllers/admin/api/services_controller.rb
app/models/service.rb
app/representers/service_representer.rb
app/views/account_messenger/expired_credit_card_notification_for_buyer.text.liquid
app/views/cinstance_messenger/expired_trial_period_notification.text.liquid
config/locales/en.yml
doc/active_docs/Account Management API.json
lib/developer_portal/lib/liquid/drops/service.rb
test/integration/api/services_controller_test.rb
test/integration/user-management-api/services_test.rb

Removes unused fields from the API request and response (they are not visible in the UI and not used anywhere).
Closes https://issues.jboss.org/browse/THREESCALE-1615
TBD

Remove unused tech_support_email and admin_support_email

---

app/javascript/src/utilities/json-utils.jsx

* It's meant to use in a safe way
* If not you will be reinventing the wheel, what'd be the difference?!
Fixes https://github.com/3scale/porta/pull/746

[utils] safeFromJson should warn and return undefined

---

app/models/cinstance.rb
config/examples/features.yml
test/unit/cinstance_test.rb

Part of [THREESCALE-2132 - [Refactor & Bugfix] Improvements in automatic suspension and deletion of tenants](https://issues.jboss.org/browse/THREESCALE-2132)
It blocks https://github.com/3scale/porta/pull/745 because if we merge that one first, it means that we will destroy accounts that shouldn't be destroyed.
The config edited in the _deploy_ repo: https://github.com/3scale/deploy/pull/554 (tested in preview)

List of plans in AccountDeletionConfig feature accept SQL Wildcard Characters

---

app/models/cinstance.rb
test/unit/cinstance_test.rb

Fixes [THREESCALE-2072 - Application update events trigger zync when first*traffic_at fields are updated](https://issues.jboss.org/browse/THREESCALE-2072)

Application update events don't trigger zync when first*traffic_at fields are updated

---

db/migrate/20181105212016_duplicate_deleted_at_state_changed_at.rb
openshift/system/Dockerfile
openshift/system/Dockerfile.on_prem

We have a bug to migrate from 2.4 to 2.5 saying that `deleted_at` doesn't exist at the moment to run that migration.
To see the root cause of the problem, I followed the steps explained in _Verification Steps_ below. I replicated the error, I saw that `deleted_at` was in the schema, so I replicated all the steps again but running the migration without having `deleted_at` removed programatically in `Account.columns` this time, and it worked, so I knew it was that Ruby wasn't detecting but it was in the DB, so the solution is a query that runs in the DB and no Ruby side for that migration, because we need to keep the attribute removed programatically at this point (for SaaS).
By programatically deleted I mean this:
https://github.com/3scale/porta/blob/73fe1815a4419128e1708cbf5deca6c8776b90be …

Update state_changed_at from deleted_at with a SQL query because deleted_at is removed from Rails programatically

---

lib/system/database.rb
test/unit/system_database_test.rb

This memoize the configuration specification. Thus preventing reading from file every request
Fixes [THREESCALE-2281](https://issues.jboss.org/browse/THREESCALE-2281)
1. boot the application with a valid database.yml
2. make a valid query to an API, for example  admin/api/service_features#index
3. verify the query is successful
4. Remove the config/database.yml file
5. make a valid query to an API, for example  admin/api/service_features#index
6. verify it fails with a 500 error:  "Could not load database configuration. No such file - [config/database.yml"]
Expected: step 6 should not fail with an error but succeed

THREESCALE-2281 Do not read the database configuration every request

---

lib/tasks/user.rake
test/unit/tasks/user_test.rb

Fixes [THREESCALE-2055](https://issues.jboss.org/browse/THREESCALE-2055) once executed in production.

[Bugfix] Rake task to obfuscate corrupt private data and fix the tenant_id

---

app/lib/three_scale/message_bus_config.rb
config/docker/message_bus.yml
config/examples/message_bus.yml
config/initializers/message_bus.rb
openshift/system/config/message_bus.yml
test/unit/three_scale/message_bus_config_test.rb

This PR makes message bus configuration to use `REDIS_URL` env var in case `MESSAGE_BUS_REDIS_URL` is not present. Nothing changes if `MESSAGE_BUS_REDIS_URL` is defined.
It keeps the behavior of using different redis dbs for `MessageBus` and `System.redis` in case namespaces are not configured for either of those redis connections.
Closes [THREESCALE-2382](https://issues.jboss.org/browse/THREESCALE-2382) as an alternative to a templates solution approach.
Normal behavior setting `MESSAGE_BUS_REDIS_URL`
1. Boot porta setting `MESSAGE_BUS_REDIS_URL=redis://localhost/8`
2. Confirm that message bus redis entries are being sent to redis db 8
3. Confirm that Sidekiq redis entries are being sent to …

Use REDIS_URL for message bus when MESSAGE_BUS_REDIS_URL is missing

---

app/models/access_token.rb
app/models/cms/builtin.rb
app/models/country.rb
app/models/end_user_plan.rb
app/models/feature.rb
app/models/go_live_state.rb
app/models/invitation.rb
app/models/invoice.rb
app/models/invoice_counter.rb
app/models/message.rb
app/models/metric.rb
app/models/partner.rb
app/models/payment_detail.rb
app/models/payment_transaction.rb
app/models/policy.rb
app/models/profile.rb
app/models/proxy.rb
app/models/proxy_log.rb
app/models/proxy_rule.rb
app/models/service.rb
app/models/settings.rb
app/models/sso_authorization.rb
app/models/system_operation.rb
app/models/topic_category.rb
app/models/user.rb
app/models/user_session.rb
test/unit/metric_test.rb
test/unit/models_test.rb
test/unit/proxy_rule_test.rb
test/unit/proxy_test.rb

Fixes [THREESCALE-2367](https://issues.jboss.org/browse/THREESCALE-2367)
It validates for all models that the length of the strings is not higher than what the field can take, so it doesn't reach the DB and it doesn't raise an error for requests through the API but responds with a nice error message instead.

Validate maximum length of strings in models (before reaching DB)

---

app/services/policies/policies_list_service.rb
config/examples/sandbox_proxy.yml
config/locales/en.yml
features/old/api/settings.feature
features/step_definitions/apicast_steps.rb
test/unit/services/policies/policies_list_service_test.rb

When APICAST_REGISTRY_URL is not provided, custom policies won't show up instead of crashing porta.
[THREESCALE-2327: Prevent Integration Settings from crashing when APIcast not available](https://issues.jboss.org/browse/THREESCALE-2327)
1. Navigate to any `tenantURL/apiconfig/services/:service_id/integration/edit`
2. There should be no 500 error but custom policies are empty

Prevents Runtime error in integration/edit when APIcast not available

---

app/workers/zync_worker.rb
config/resque-pool.yml
lib/tasks/sidekiq.rake

Relates to: https://github.com/3scale/deploy/pull/567
We need Zync Workers to be confined, not running on the _low_ queue
Otherwise if we want to "throttle" calls to Zync we are throttling all jobs in the _low_ queue

[zync] Move Zync worker to its own queue

---

app/workers/delete_object_hierarchy_worker.rb
app/workers/find_and_delete_scheduled_accounts_worker.rb
lib/tasks/sidekiq.rake
test/performance/workers/delete_object_hierarchy_test.rb
test/workers/delete_object_hierarchy_worker_test.rb
test/workers/find_and_delete_accounts_scheduled_worker_test.rb

Delete object worker does many database queries. It loads all associations one by one. 
All associations are being loaded in one eager loaded query.
Fixes [THREESCALE-2204 - Fix efficiency to destroy tenants/services and enable the worker again](https://issues.jboss.org/browse/THREESCALE-2204)

Delete object worker optimization

---

Gemfile.base
Gemfile.lock
config/initializers/strong_migrations.rb
gemfiles/prod/Gemfile.lock

Closes [THREESCALE-1859 - Ability to detect dangerous migrations](https://issues.jboss.org/browse/THREESCALE-1859)
Install and use the Gem `strong_migrations` to detect dangerous migrations for new migrations from now on.
I think that it works well in the 3 DBs without doing anything else 🤔 
I am doing some tests locally with this new temporary migration in `db/migrate/20190507145848_temporarily_remove_account_service_preffix.rb` :
```ruby
class TemporarilyRemoveAccountServicePreffix < ActiveRecord::Migration
def change
puts "\n------------------------\nUsing #{System::Database.adapter}\n------------------------\n"
remove_column :accounts, :service_preffix
end
end
```
The `Account` model has this change now to remove the column from the Rails cache programatically:
And simulating that it …

Detect dangerous migrations

---

test/unit/logic/provider_upgrade_test.rb

Closes [THREESCALE-2144 - Fix random test failure in test_raises_if_trying_to_upgrade_to_enterprise](https://issues.jboss.org/browse/THREESCALE-2144)
The goal of this test, from very old commits, when everything was inside `ProviderUpgrade`, was to check that it was not possible to upgrade through `enterprise` by `upgrade_to_provider_plan!`.
https://github.com/3scale/system/blob/d18418385555e96094cb3346db3724aedcef7993/test/unit/logic/provider_upgrade_test.rb#L62-L65
https://github.com/3scale/system/blob/0696c85a78f8e63369d8808e1a05a8f32b4d9181/app/lib/logic/provider_upgrade.rb#L176-L190
Later we extracted a lot of this code into `PlanRule`, `PlanRuleCollection`, and made it configurable by `plan_rules.yml`. The `enterprise` was not hardcoded anymore and we added the metadata option …

Fix random test failure in test_raises_if_trying_to_upgrade_to_enterprise

---

Dockerfile
openshift/system/Dockerfile
openshift/system/Dockerfile.on_prem

Closes [THREESCALE-2504 - Add SAFETY_ASSURED=1 for on-prem and QE nightly builds](https://issues.jboss.org/browse/THREESCALE-2504)

[Bugfix] Assure safety for strong_migrations in Openshift

---

INSTALL.md

Some steps are missing in the installation guide for MacOS.
[THREESCALE-2489](https://issues.jboss.org/browse/THREESCALE-2489)

Adds missing steps for installation on MacOS X

---

Gemfile
Gemfile.lock
gemfiles/prod/Gemfile
gemfiles/prod/Gemfile.lock

So that we can run tests for ruby 2.3, 2.4 and 2.5 at the same time

[Gemfile] Remove ruby requirements

---

Gemfile.base
Gemfile.lock
gemfiles/prod/Gemfile.lock
test/test_helpers/backend.rb

It updates the version of the faraday gem in use to v0.12.2.
This is expected to include support to no_proxy env var in the HTTP requests performed using the gem, such as connections to backend, segment and some requests performed by Sidekiq.
Closes [THREESCALE-1739](https://issues.jboss.org/browse/THREESCALE-1739)

Bump faraday version to 0.12.2

---

test/unit/array_test.rb

The change of Fixnum to Integer might break some XML integration. We need to warn product

Array#to_xml test fix

---

app/events/applications/application_plan_change_requested_event.rb
config/abilities/provider_any.rb
test/unit/abilities/provider_any_test.rb

Bug reproduced following the steps of the description in the Jira issue ([THREESCALE-629 - Dashboard stream and email notifications should be filtered according to the member permissions](https://issues.jboss.org/browse/THREESCALE-629))
In development I also use this code to reproduce it in the rails console quickly (you need sidekiq running 😄 ):
```ruby
def reproduce_bug
tenant = Account.find(2)
('A'..'B').to_a.each do |letter|
begin
tenant.services.create!(name: "Service #{letter}")
rescue ThreeScale::Core::APIClient::ConnectionError
end
end
(1..2).to_a.each do |n|
Service.find_by(name: 'Service B').application_plans.create!(name: "plan_#{n}")
user = tenant.users.create!(role: :member, username: "member#{n}", email: "member#{n}@example.com", password: '123456')
user.activate
end …
```

Dashboard stream and email notifications are filtered according to the member permissions

---

.circleci/config.yml
app/lib/three_scale/spam_protection/checks/timestamp.rb
openshift/system/Dockerfile
openshift/system/Dockerfile.on_prem
openshift/system/contrib/scl_enable

Running nightly:
- mysql + ruby 2.4
- postgres + ruby 2.4
- oracle + ruby 2.4
Normal PR are still running on ruby 2.3
Replaces https://github.com/3scale/porta/pull/790
Closes THREESCALE-2062
All nightly builds will run first, if green I will just activate the triggers at midnight.
I will squash some commits too
The commit named "Fix ArgumentError: key must be 32 bytes..." could be extracted to another PR

Ruby 2.4 nightly builds

---

.circleci/config.yml
Gemfile
Gemfile.base
Gemfile.lock
app/lib/three_scale/spam_protection/checks/timestamp.rb
gemfiles/prod/Gemfile
gemfiles/prod/Gemfile.lock
openshift/system/Dockerfile
openshift/system/Dockerfile.on_prem
openshift/system/contrib/scl_enable
test/unit/active_merchant/stripe_fix_test.rb
test/unit/array_test.rb
test/unit/backend_client/connection_test.rb

Now the 2.5 stable branch is using ruby 2.4
It will be the case on the master branch soon, for some technical reasons, it is not possible for now.
Closes https://issues.jboss.org/browse/THREESCALE-2064

[ruby] Upgrade to ruby 2.4 on 2.5-stable branch

---

app/controllers/master/providers/plans_controller.rb
app/views/buyers/accounts/show.html.slim
config/abilities/master_member.rb
test/integration/master/providers/plans_controller_test.rb
test/unit/abilities/master_member_test.rb

Closes [THREESCALE-1733 - Multitenant member user with appropriate rights doesn't have access to application plans](https://issues.jboss.org/browse/THREESCALE-1733).
Locally, if you have the default DB from the seeds, follow this steps 😄 
1. Put in `config/plan_rules.yml`:
```yaml
plan_rules: &default
base:
rank: 1
limits:
max_users: 1
max_services: 1
switches: []
metadata: {}
2015_plus_copy_14540190951550343:
rank: 3
limits:
max_users: 1
max_services: 1
switches: []
metadata:
trial: true
plus:
rank: 8
limits:
max_users: 1
max_services: 1
switches:
- finance
- multiple_applications
- branding
- require_cc_on_signup
metadata: {}
master_plan:
rank: 50
limits:
max_users:
max_services:
switches:
- finance
- multiple_applications
- branding
- require_cc_on_signup
- account_plans
- …
```

Master Member gets permissions for provider_plans

---

.circleci/config.yml

So it is automatized
The build is triggered in quay for the tag `ruby24` on the branch `ruby24`

Use the image built by circleci on system-builder/ruby24 branch merge

---

test/integration/master/providers/plans_controller_test.rb

Trying to fix a bug for CircleCI in Postgres.
When I run `spring m test/integration/master/providers/plans_controller_test.rb:41`, I see:
Example of this: https://circleci.com/workflow-run/64eaa26c-fb5f-4dbe-b482-2276e82b443b
This is blocking any PR that needs to run the tests for all DBs.

[Bugfix] [Postgres] for SELECT DISTINCT, ORDER BY expressions must appear in select list.

---

test/workers/delete_object_hierarchy_worker_test.rb

Bugfix in test for CircleCI/locally in Oracle.
When I run `spring m test/workers/delete_object_hierarchy_worker_test.rb:208` (now `204`), I see:
Example of this: https://circleci.com/gh/3scale/porta/54953#tests/containers/3
This is blocking any PR that needs to run the tests for all DBs.
Depends on https://github.com/3scale/porta/pull/823

[Bugfix][Oracle] Remove experimental test

---

db/migrate/20190527104222_fix_oracle_deleted_objects_precision.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Closes [THREESCALE-2298 - Fix Oracle Schema for DeletedObjects](https://issues.jboss.org/browse/THREESCALE-2298)
Blocks some issues.
It depends on https://github.com/3scale/porta/pull/823 and https://github.com/3scale/porta/pull/824

Fix Oracle Schema for DeletedObjects

---

app/models/service.rb

It doesn't exist anymore since https://github.com/3scale/system/pull/8582 and it was also remove from SaaS/Production.

Remove reference to old field Services#buyer_can_see_log_requests

---

lib/tasks/multitenant/triggers.rake

Closes [THREESCALE-2571 - Fix users without tenant_id set](https://issues.jboss.org/browse/THREESCALE-2571)
The code that we currently have to reset the `tenant_id` updates all records of the DB ([here](https://github.com/3scale/porta/blob/f591474f5e7b00b99ac41b026936616c237ca309/lib/tasks/multitenant/triggers.rake#L41-L115)), not only the ones that are NULL. Besides, it does not rely on indexes. This is not ideal. Just in case, I tried executing it in preview with ops supervision, and it did not went well indeed. I am not really considering refactoring though:
1. That would be a lot of work in comparison to what we need to close the issue
2. It's technically out of scope.
3. There is already a refactoring in progress in [this old PR](https://github.com/3scale/porta/pull/598) which should …

Fix empty or corrupted tenant_id

---

lib/tasks/multitenant/tenants.rake
lib/tasks/multitenant/triggers.rake
test/unit/tasks/multitenant/tenants_test.rb

Refactor and Bugfix from https://github.com/3scale/porta/pull/813, closes [THREESCALE-2571](https://issues.jboss.org/browse/THREESCALE-2571)
1. Fix bug: For those tables associated to user, it was doing `record.account` instead of `record.user`
2. Move to `tenants` to be able to add tests (in `triggers` it doesn't work)
3. Add tests
4. A bit of DRY
5. Divide alerts between empty and not empty
```
RAILS_ENV=production FILE=corrupted_accounts bundle exec rake 'multitenant:tenants:fix_corrupted_tenant_id_accounts[1, 1]'
RAILS_ENV=production bundle exec rake 'multitenant:tenants:fix_corrupted_tenant_id_for_table_associated_to_account[User, 01/24/2019 08:00 UTC, 01/24/2019 16:30 UTC, 1, 1]'
RAILS_ENV=production bundle exec rake 'multitenant:tenants:fix_corrupted_tenant_id_for_table_associated_t …
```

[Refactor & Bugfix] Task update corrupted or empty tenant_id

---

app/controllers/api/integrations_controller.rb
app/services/policies/policies_list_service.rb
app/views/api/integrations/apicast/shared/_policies.html.slim
features/old/proxy.feature
features/provider/integration/edit.feature
features/provider/integration/staging_environment.feature
test/functional/api/integrations_controller_test.rb
test/integration/api/integration_test.rb
test/test_helpers/proxy.rb

Renders an error message when it fails to fetch the APIcast policy registry
It currently looks like this:
fixes https://issues.jboss.org/browse/THREESCALE-2312
Easy way to test this is in dev mode, start a rails server with `APICAST_REGISTRY_URL` env with nothing or a random URL. Then visit the Service integration page, under policies you should see an error message.
TO DO:

Error message when fails to fetch policies

---

features/step_definitions/navigation_steps.rb

This step was wrong 😄 This is our real UI:
From `Messages` it is impossible to access directly to `Threads`. The real path is from the Dashboard to `Messages`, then to `Forum` and finally to `Threads`.
It was working anyway because it is in the same HTML:
But as soon as we want to add the `@javascript` tag to any cucumber with this step, it would work. But after this PR, it works both with or without the tag 😄 
I discovered this problem thanks to https://github.com/3scale/porta/pull/761

[Cuke] Fix 'element not interactable' for 'I navigate to the forum admin page'

---

features/old/accounts/users.feature
features/step_definitions/user_management/common_steps.rb
test/integration/provider/admin/account/users_controller_test.rb

This step is problematic because it does not exist for `Chrome::Driver` (which is the driver used when we have the tag `@javascript`) and it does not belong to cucumber to make this tests anyway, because it is not UI-related. It must be in `test/integration` 😄

Remove cucumber step to make http requests (non-UI step)

---

features/old/menu/account_menu.feature

This PR is similar to https://github.com/3scale/porta/pull/834
The way to navigate to "Invoices" is not "Account" -> "Invoices" from the Dashboard. Because "Invoices" is under "Billing":
The reason why it was working anyway is because it is under the same HTML:
But as soon as we add the tag `@javascript`, it won't work because it isn't the real navigation.
With this PR it works both with and without the `@javascript` tag.

[Cuke] Fix navigation to 'Invoices'

---

app/events/zync_event.rb
app/workers/zync_worker.rb
test/events/zync_event_test.rb
test/workers/zync_worker_test.rb

Reverts 3scale/porta#809. `ThreeScale::SidekiqRetrySupport::Worker#last_attempt?` doesn't really work the way it has been used here.

Revert "Try Zync dependency chain in a Sidekiq batch on UnprocessableEntityError"

---

features/old/applications/buyers/referrer_filters/buyer_side_multiple_applications.feature
features/old/applications/providers/referrer_filters.feature
features/old/buyers/accounts/searching.feature
features/old/buyers/accounts/security.feature
features/old/buyers/invitations/security.feature
features/old/cms/advanced/groups_and_sections.feature
features/old/cms/advanced/multi-tenant/authorizations/groups_and_sections.feature
features/old/cms/pages.feature
features/old/forums/categories.feature
features/old/forums/searching.feature
features/old/home_page.feature
features/old/signup/with_invitation.feature
features/step_definitions/custom_web_steps.rb
features/step_definitions/forum/category_steps.rb
test/functional/forums/admin/categories_controller_test.rb
test/integration/developer_portal/forums/admin/categories_controller_test.rb

Checking status codes from cucumber does not work from `Chrome::Driver`, which is the browser used when we have the tag `@javascript`. This way it works anyway.
And either way it is wrong to test status codes from HTTP requests from Cucumber. Cucumber should do only UI related actions and assert from the UI.

Do not check status codes from cucumber features

---

features/step_definitions/custom_web_steps.rb
features/step_definitions/user_management/common_steps.rb

Fix all cukes for `features/old/buyers/users.feature`. It works for the current master branch as well.
In `PF3-Login-Page` branch, it relies on the `@javascript` tag to work anyway 😄

[Cukes] Fix: features/old/buyers/users.feature

---

features/old/public_site_access.feature
features/step_definitions/url_steps.rb
test/functional/developer_portal/access_codes_controller_test.rb

Fix features from `features/old/public_site_access.feature` by removing moving to a new wingow due to the `target: "_blank"`
Remove empty test
Remove redundant cucumber scenario

[Cukes] Fix feature public site access

---

features/old/accounts/invitations.feature
features/old/api/metrics/deletion.feature
features/old/buyers/invitations/for_admins.feature
features/old/cms/groups.feature
features/old/services/subscriptions/bulk_operations/change_states.feature
features/step_definitions/confirm_dialog_steps.rb
features/step_definitions/invitations_steps.rb

Fixes the following scenarios:
And for `features/old/cms/groups.feature:26`:

[Cukes] Fix steps that require accepting alerts

---

app/models/service.rb
app/representers/service_representer.rb
spec/acceptance/api/service_spec.rb

This PR adds the following attributes to the response for Service Read API endpoint:
- intentions_required (boolean)
- buyers_manage_apps (boolean)
- buyers_manage_keys (boolean)
- referrer_filters_required (boolean)
- custom_keys_enabled (boolean)
- buyer_key_regenerate_enabled (boolean)
- mandatory_app_key (boolean)
- buyer_can_select_plan (boolean)
- buyer_plan_change_permission (enum: request, direct, credit_card, request_credit_card, none)
- notification_settings (complex attribute – child attributes: web_provider, email_provider, web_buyer, email_buyer – array of integers)
```
$ curl 'http://provider-admin.example.com/admin/api/services/2.json?access_token=<my-secret-access-token>'
{"service":{"id":2,"name":"API","state":"incomplete","system_na …
```

Service setting attributes added to api response

---

app/lib/features/logging_config.rb
config/examples/features.yml
config/initializers/audited_hacks.rb
config/initializers/features.rb
test/factories/audit.rb
test/unit/audited_hacks_test.rb
test/unit/features/logging_config_test.rb

- It defines a global feature `logging` where types of logging can be configured at the deployment level
- It defines a logging configuration `audit_to_stdout` that when enabled prints a simplified representation of a recently created audit record to the standard output
Example:
Close [THREESCALE-2593](https://issues.jboss.org/browse/THREESCALE-2593)
1. Activate `audits_to_stdout` in `config/features.yml:logging` (enabled by default on OpenShift once https://github.com/3scale/porta/pull/851 gets merged)
2. Create any audited record such as an account, application contract, etc
3. Make sure Sidekiq is running and audit jobs have been processed
4. Check the audits of the object created in (2) …

Audit logs to stdout

---

app/controllers/admin/api/services/proxies_controller.rb
app/controllers/api/integrations_controller.rb
app/models/proxy.rb
app/representers/proxy_representer.rb
app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
config/locales/en.yml
db/migrate/20190530065503_add_proxies_oidc_issuer_type.rb
db/schema.rb
test/unit/proxy_test.rb

Adds a select box for user chose if they are using Keycloak or Generic HTTP adapter for the OIDC sync integration.

[proxy] introduce OIDC integration types [THREESCALE-2665]

---

app/views/payment_gateways/_stripe_elements.html.erb

stripe elements form is taking more width than it should. This pr fixes that.

Give stripe elements form less width so submit button sits at right edge

---

app/javascript/src/LoginPage/LoginPageWrapper.jsx
app/javascript/src/LoginPage/assets/styles/loginPage.scss
app/javascript/src/LoginPage/loginForms/AuthenticationProviders.jsx
spec/javascripts/LoginPage/AuthenticationProviders.spec.jsx

Moving Login Providers to bottom, for https://github.com/3scale/porta/pull/761

Moving Login Providers to bottom

---

features/step_definitions/table_steps.rb

Fixing only a deprecation warning 😄

[Cukes] Fix deprecation warning: Ast::Table -> MultilineArgument::DataTable

---

INSTALL.md

Sometimes the mysql2 gem installation fails with an error telling that
the library was not found for linking. This commit adds the instruction
to configure it for bundler.
It also modifies the `Run Porta` instruction to use `env` to set the
`UNICORN_WORKERS` environment variable allowing it to works fine in
fish shell along with bash and zsh.

Add mysql2 ld flags instructions in INSTALL.md

---

features/provider/applications/stats.feature
features/support/selectors.rb

It tries to follow a link of Analytics but there are 2. This PR clarifies which one but also fixes the selector of the subsubmenu.

[Cukes] Follow 'Analytics' within the subsubmenu

---

Makefile

Update the Makefile to use `DATABASE_URL` instead of `DB`.
Needed since https://github.com/3scale/porta/pull/584

Update Makefile to use DATABASE_URL instead of DB

---

app/models/account.rb
app/models/contract.rb
app/models/payment_detail.rb
app/models/settings.rb
app/models/user.rb
config/initializers/audited_hacks.rb
test/factories/audit.rb
test/unit/audited_hacks_test.rb

This PR adds to the audits to STDOUT trail the actual changes to the audited model.
It also introduces an option `sensitive_attributes: Array` to `Audited#audited` method, where whatever attribute name listed in this option will have its value obfuscated in the audit trail.
Closes [THREESCALE-2788](https://issues.jboss.org/browse/THREESCALE-2788)

Audited changes included into audits to STDOUT

---

app/events/domains/provider_domains_changed_event.rb
app/events/domains/proxy_domains_changed_event.rb
app/events/zync_event.rb
app/lib/event_store/repository.rb
app/lib/missing_model.rb
app/models/account.rb
app/models/account/domains.rb
app/models/proxy.rb
app/models/service.rb
app/representers/proxy_representer.rb
app/subscribers/publish_zync_event_subscriber.rb
app/workers/zync_worker.rb
db/seeds.rb
spec/acceptance/api/proxy_spec.rb
test/unit/provider_test.rb
test/unit/proxy_test.rb

Publish events to Zync when Provider or a Proxy changes domain (that includes when a provider/proxy is created and deleted).
Depends on https://github.com/3scale/zync/pull/199

[zync] publish events about provider domain changes [THREESCALE-2686]

---

.circleci/config.yml

This is needed for 2.6 ER1.
Jest tests were failing with
```
console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Uncaught [Error: ENOMEM: not enough memory, read]
```
This will prevent that memory over comsumption

Running jest test with maxWorkers option

---

app/javascript/packs/LoginPage.js
app/javascript/src/LoginPage/LoginPageWrapper.jsx
app/javascript/src/LoginPage/assets/styles/ie11-pf4BaseStyles.css
app/javascript/src/LoginPage/assets/styles/loginPage.scss

Adds styles for PF4 Login page in IE 11, copying some rules from PF4 Base Styles and overriding some others
**Screenshots:**

Adding IE11 styles

---

app/assets/stylesheets/provider/_header.scss

By adding a padding the button has a wider clickable area.
Padding value of `line-height-times(1 / 2)` for a button's width of `line-height-times(3 / 2)`. Also aligns icons to the center.

Add some padding to Header icons

---

app/assets/stylesheets/provider/_pop_navigation.scss

Moves `ContextSelector`'s dropdown menu down and also aligns icons vertically.
**Provider**
**Master**
**Help menu**

Fix ContextSelector position / alignment

---

app/models/payment_gateway.rb
features/step_definitions/credit_card_steps.rb
test/functional/developer_portal/admin/account/adyen12_controller_test.rb
test/functional/finance/provider/settings_controller_test.rb
test/helpers/payment_details_helper_test.rb

Deprecate Adyen payment gateway and remove the option for choosing it in Billing Settings page. It will continue active for accounts already using it but they won't be able to switch back if they change it.
Update Account Management API to remove Adyen references.
Closes [THREESCALE-2769](https://issues.jboss.org/browse/THREESCALE-2769)
1. Access the Admin Portal with a Provider that has `Adyen` configured as the payment gateway. 
2. It should keep `Adyen` as the provider's gateway but alert it with a deprecated message:
3. Change the gateway to another one and hit `Save Changes`. 
4. It should change the provider's gateway and don't list `Adyen` in the list.

Deprecate Adyen payment gateway

---

.gitignore
Makefile

After making some change in the database we need to regenerate the
schema for Postgres. This changes the `make schema` command to
accept a env var `POSTGRES_DATABASE_URL` and uses it to migrate
the database and updates the schema after the migration
Start your postgres database and create the data.
to simulate a non-executed migration in postgres you can run:
`DATABASE_URL="YOUR_PG_URL" bundle exec rake db:rollback db:schema:dump`
the db/postgres_schema.rb should have been changed with some columns being removed.
Now you can run `POSTGRES_DATABASE_URL="YOUR_PG_URL" make schema` (it will run the migration and redump the schema) and your
db/postgres_schema.rb should have no difference (it will be the same as git since we …

Include Postgres schema dumping into make schema

---

app/workers/zync_worker.rb

It sets ZyncWorker number of retry attempts to Sidekiq default (25) and
makes the job to go to the dead set in case it still exhausts the number of
attempts.
Closes [THREESCALE-2843](https://issues.jboss.org/browse/THREESCALE-2843)

Set ZyncWorker number of retries to Sidekiq default

---

doc/liquid/tags.md
features/old/emails.feature
lib/developer_portal/lib/liquid/tags/email.rb

It fixes the liquid documentation about how to use the `email` tag in
combination of conditional blocks.
Close [THREESCALE-2226](https://issues.jboss.org/browse/THREESCALE-2226)

Fix documentation of liquid email tag

---

lib/tasks/zync.rake
test/unit/tasks/zync_test.rb

It implements a set of rake tasks to issue domain changed events of
providers and proxies. This will make Zync to resync Openshift routes
eventually managed.
Related to [THREESCALE-2841](https://issues.jboss.org/browse/THREESCALE-2841)
Provider domains:
```
bundle exec rake zync:resync:provider_domains
```
Proxy domains:
```
bundle exec rake zync:resync:proxy_domains
```
Both provider and proxy domains:
```
bundle exec rake zync:resync:domains
```

Rake task to issue domain changed events to all providers

---

features/support/capybara.rb

Trying to fix the annoying `Net::ReadTimeout (Net::ReadTimeout)` that happens randomly in our cukes

[cukes] Selenium client timeout waits longer

---

app/assets/stylesheets/provider/_flash.scss

**Note**
Due to scrollbar not being overlayed, the flash message is not aligned with the header icons anymore.

Fix flash message spacing

---

features/old/accounts/service_contracts.feature
features/step_definitions/services/service_contract_steps.rb
features/step_definitions/stats/provider_charts.rb
features/support/alerts.rb

Originally this PR was opened to investigate and test for the `Net::ReadTimeout` randomly appearing in CircleCI for the provider login, but since that has been fixed in https://github.com/3scale/porta/pull/930, this PR now only contains 2 minor improvements that I encountered when I was dealing with that error:
1. One of the scenarios of the feature _service contracts_ doesn't need JS 😄 
2. Fix deprecation warning: Ast::Table -> MultilineArgument::DataTable

[Cukes] 2 minor improvements from 2.6: A scenario doesn't need JS + fix warning

---

app/lib/three_scale/analytics/user_tracking.rb
test/unit/three_scale/analytics/user_tracking_test.rb

3scale on-prem tries to send requests to segment.io and fails when it
is not reachable. This commit creates a section to toggle segment at
features.yml and it avoids sending requests to segment.io if it is
disabled.
Closes [THREESCALE-2572](https://issues.jboss.org/browse/THREESCALE-2572)

Does not send request to segment if disabled

---

.flowconfig

After merging https://github.com/3scale/porta/pull/904 flow is checking `.dir` directory and failing. 
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ .git/refs/heads/3scale-2.6.0-ER1-Update-package-lock.json:1:1
Unexpected identifier
1│ af757b0bce4ebc38fd8486f8ef7f848fdd8d5536
2│
This PR adds `.git` folder to ignored list

Fix flow errors in .git dir

---

app/lib/three_scale/sidekiq_retry_support.rb
app/workers/web_hook_worker.rb
test/unit/three_scale/sidekiq_retry_support_test.rb

Fixes a reference to `Sidekiq::Middleware::Server::RetryJobs::DEFAULT_MAX_RETRY_ATTEMPTS` in `ThreeScale::SidekiqRetrySupport::Worker::retry_limit`.
`Sidekiq::JobRetry::DEFAULT_MAX_RETRY_ATTEMPTS` was introduced in Sidekiq 5: https://github.com/mperham/sidekiq/pull/3235

Fix uninitialized constant Sidekiq::JobRetry

---

.babelrc
.eslintrc

It adds some missing configuration to our build process, to prevent warnings like:
> WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version...
Or:
> Warning: React version not specified in eslint-plugin-react settings

Cleaning some npm/babel/eslint warnings

---

app/assets/stylesheets/provider/stats/_base.scss

Slightly improves Stats screen since introduction of PF4 by adding blank space. This size is exactly `320px` as it's the height of the chart rendered by the stats package.
**Before**
**Now**

Slightly improve loading Stats screen

---

config/examples/database.yml
script/oracle/002_setup.sh

We only need 3 PDB now: systempdb{,test,production}
Also removes password expiry for those pdbs by default
Closes THREESCALE-2814
[See Managing profiles in Oracle Database](https://docs.oracle.com/cd/B19306_01/network.102/b14266/admusers.htm#i1012785)

[oracle] Setup with the minimum PDBS

---

app/assets/stylesheets/provider/_header.scss
app/assets/stylesheets/provider/_pop_navigation.scss

Set manually top/right/left values to PopNavigation so that it works properly in Safari.
This is Safari:
[THREESCALE-2902: Adjust vertical position of pop ups at the top right in Safari](https://issues.jboss.org/browse/THREESCALE-2902)
context-selector and help/session popups should look good in Chrome, Firefox, IE11 and Safari.

Fix Popup positioning in Safari

---

.circleci/config.yml

Relates to #924
In #924 we use systempdb systempdbtest and systempdbproduction in [config/database.yml](https://github.com/3scale/porta/commit/1d371059a5491422608a5aebe9ce3d1d2610d614#diff-23ee76661959fed8a0ed82075a4b5468)
But in circleci we only create [systempdb](https://github.com/3scale/porta/blob/3d6c398a64eec8842bbedd2c00d14c02d9a8091e/.circleci/config.yml#L113) though it should be systempdbtest as `RAILS_ENV=test`

[oracle] Fix PDB name for testing

---

app/models/account/gateway.rb
lib/developer_portal/app/controllers/developer_portal/admin/account/adyen12_controller.rb
test/unit/account/gateway_test.rb
test/unit/invoice_test.rb

Removes a method that was only used from tests and now it is not used from anywhere else:
I encountered this while working on another task 😄

[Refactor] Remove unused Account::Gateway#payment_gateway_unconfigured?

---

app/lib/three_scale/analytics.rb
app/lib/three_scale/on_premises.rb

It fixes an annoying warning message "already initialized constant
ACCEPTED_TENANT_MODES" on load of the rails environment

Already initialized constant ACCEPTED_TENANT_MODES

---

lib/developer_portal/lib/liquid/drops/provider.rb

This method is duplicated.
I've removed this one:
https://github.com/3scale/porta/blob/09ea71b4ca22de7b27fef10d15e648462d189e37/lib/developer_portal/lib/liquid/drops/provider.rb#L114-L118
And I've kept this one:
https://github.com/3scale/porta/blob/09ea71b4ca22de7b27fef10d15e648462d189e37/lib/developer_portal/lib/liquid/drops/provider.rb#L193-L201

Remove duplicated method Liquid::Drop::Provider#logo_url

---

app/events/zync_event.rb
app/workers/zync_worker.rb
test/events/zync_event_test.rb
test/workers/zync_worker_test.rb

TLDR – Reverts 3scale/porta#846 + a couple fixes, including one after https://github.com/3scale/porta/pull/927 was merged
This PR modifies the way the hook on the `UnprocessableEntityError` exceptions in the Zync worker behaves.
Right now in master, whenever a zync job fails with a `UnprocessableEntityError`, we hook into the error to publish zync events for the possible dependent objects that are assumed to be missing in Zync and therefore make it to return a 422. Right after publishing those dependency zync events, it raises the error in the current job and all zync jobs concur to be processed in parallel by Sidekiq – the one that failed and the ones just created as "dependencies".
This PR makes the current job to wait for the dependency jobs to be …

Zync UnprocessableEntityError hook in a Sidekiq batch

---

app/models/application_key.rb
app/models/cinstance.rb
test/unit/application_keys_test.rb
test/unit/backend/model_extensions/cinstance_test.rb
test/unit/cinstance_test.rb

Closes [THREESCALE-1451](https://issues.jboss.org/browse/THREESCALE-1451)

Allow inclusion of special chars in App ID/KEY as defined in RFC 6749

---

app/lib/three_scale/oauth2/keycloak_client.rb
test/unit/three_scale/oauth2/keycloak_client_test.rb

Closes THREESCALE-2909
In order to use OpenID Connect as specified in https://openid.net/specs/openid-connect-basic-1_0.html#Scopes
The scope `openid` is REQUIRED otherwise
REQUIRED. Informs the Authorization Server that the Client is making an OpenID Connect request. If the openid scope value is not present, the behavior is entirely unspecified.

[bugfix] Keycloak client must have openid scope

---

app/lib/service_discovery/authentication_provider_support.rb

Error discovered by @guicassolato in https://github.com/3scale/porta/pull/982#discussion_r301696933 and explained in https://github.com/3scale/porta/pull/982#discussion_r301845050
Before this PR:
After this PR:

Fix Reflection Account-ProvidedAccessTokens through Users

---

app/subscribers/publish_zync_event_subscriber.rb
test/subscribers/publish_zync_event_subscriber_test.rb

Makes `ProviderDomainsChangedEvent` and `ProxyDomainsChangedEvent` not to be issued on Saas

DomainsChangedEvent not issued on Saas

---

app/javascript/packs/LoginPage.js
app/javascript/packs/SignUpPage.js
app/javascript/src/LoginPage/assets/styles/loginPage.scss
app/views/provider/invitee_signups/show.html.erb
app/views/provider/sessions/new.html.slim

In Firefox the BG image of PF4 Loginpage component is not rendering (in the signup form, with invitation email).
https://issues.jboss.org/browse/THREESCALE-2991
- Go to **Account Settings > Users > Invitations**
- Send an invitation
- Logout
- In the terminal, look for the link sent
- Go to the link in Firefox

Fixing PF4 BG image in firefox

---

app/assets/stylesheets/provider/_patternfly_ie11.scss

After introducing PF4 React in vert nav, the header is showing some weird styles due to Patternfly variables.
In order to fix this, it is required to use `!important` in our `_patternfly_ie11.scss`.
Before:
After:
[THREESCALE-3013: Header changes color when on small screen setup](https://issues.jboss.org/browse/THREESCALE-3013)
* Go to a screen where there's a Vertical Navigation (e.g. Audience)
* Shrink browser and look at the Header's nav component. Background and margins should stay unchanged.

Fixes Header on small screen setup

---

CONTRIBUTING.md

Updates CONTRIBUTING.md with references to jira instead of github
[THREESCALE-2718](https://issues.jboss.org/browse/THREESCALE-2718)

Update CONTRIBUTING.md - closes THREESCALE-2718

---

package-lock.json
package.json

**Description**
I've detected a huge, huge amount of changes in the package-lock in master, this time versions.
There's also `npm@6.10.1` now.
**Steps to reproduce**
* run `npm run clean` (new task)
* run `npm i`
* see changes in package-lock.json

Yet another update of the package-lock

---

app/presenters/backend_api_presenter.rb
app/presenters/services/backend_api_presenter.rb
app/views/provider/admin/backend_apis/show.html.slim

Removes Backend API default product slug, not need since it was decided that a product may include one (and only one) Backend API without any slug at all.

[apiap] Remove Backend API default slug

---

app/controllers/api/metrics_controller.rb
app/controllers/provider/admin/backend_apis/metrics_controller.rb
app/helpers/vertical_nav_helper.rb
app/views/provider/admin/backend_apis/mapping_rules/index.html.slim
app/views/provider/admin/backend_apis/metrics/_form.html.slim
app/views/provider/admin/backend_apis/metrics/_link_to_mapping_rules.slim
app/views/provider/admin/backend_apis/metrics/index.html.slim
app/views/provider/admin/backend_apis/show.html.slim
config/routes.rb

Creates a separate controller for Backend API metrics and methods.
For the moment it still renders the index page based on the old template (`/api/metrics/index`).
Contains commits of https://github.com/3scale/porta/pull/995

[apiap] Backend API metrics controller and index page

---

app/events/domains/proxy_domains_changed_event.rb
app/lib/missing_model.rb
test/events/domains/proxy_domains_changed_event_test.rb

Fixes a bugsnag error 😄 The problem we have is when we destroy a service and destroy its proxy, this happens:
https://github.com/3scale/porta/blob/041ccb6cf322d9f278dbaf52a47388738d289180/app/models/proxy.rb#L91
https://github.com/3scale/porta/blob/041ccb6cf322d9f278dbaf52a47388738d289180/app/models/proxy.rb#L261
https://github.com/3scale/porta/blob/041ccb6cf322d9f278dbaf52a47388738d289180/app/events/domains/proxy_domains_changed_event.rb#L6
So the event is saved correctly but when it tries to use it, it tries to deserialise and it fails here because the proxy doesn't exist anymore:
https://github.com/3scale/porta/blob/041ccb6cf322d9f278dbaf52a47388738d289180/app/lib/event_store/event.rb#L13
So I have done the same as we are doing for …

ProxyDomainsChangedEvent saves the ProxyID instead of the globalID

---

app/workers/delete_object_hierarchy_worker.rb
test/workers/delete_object_hierarchy_worker_test.rb

I've seen that we have this error while I was working on https://github.com/3scale/porta/pull/981
I separate it because it is unrelated and also more urgent.

[Bugfix] DeleteObjectHierarchyWorker raise URI::GID::MissingModelIdError

---

app/helpers/plans_helper.rb
app/views/buyers/accounts/show.html.slim
app/views/shared/provider/navigation/audience/_accounts.html.slim
features/old/menu/audience_menu.feature
features/step_definitions/menu_steps.rb
test/unit/helpers/plans_helper_test.rb

Closes [THREESCALE-3005](https://issues.jboss.org/browse/THREESCALE-3005)
Check `http://provider-admin.example.com.lvh.me:3000/buyers/accounts/3` locally

Hide AccountPlan from Account#show view unless it has permission, like in the nav

---

app/models/service.rb
test/unit/service_test.rb

Fixes THREESCALE-3001
Relates to https://github.com/3scale/Red_Hat_3scale_Documentation/pull/470
~Trying to fix the issues on a migration if possible (for existing services created on version 2.5)~

Allow choosing between 3scale managed or self managed for on-premises

---

Makefile

PostgreSQL default port is 5432 and it can be confusing to developers having anything other than that. Whoever uses a different configuration locally can always set `POSTGRES_DATABASE_URL` accordingly before running `make schema`.

Change PostgreSQL default port in the Makefile

---

app/events/base_event_store_event.rb
app/events/domains/provider_domains_changed_event.rb
app/events/domains/proxy_domains_changed_event.rb
app/models/proxy.rb
app/workers/process_domain_events_worker.rb
db/migrate/20190722114341_add_proxy_domains.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
lib/generators/subscriber/subscriber_generator.rb
test/events/domains/provider_domains_changed_event_test.rb
test/events/domains/proxy_domains_changed_event_test.rb
test/workers/process_domain_events_worker_test.rb

Create domain changed events for all proxies/providers matching the same domain. 
So for example when it is no longer used it can be recreated by zync for another provider/proxy.

Zync domain events cascade

---

app/javascript/src/Stats/lib/csv_link.jsx
app/javascript/src/Stats/lib/methods_table.jsx
app/javascript/src/Stats/lib/series.jsx

This is important since it was breaking the Analytics/Usage and Response Codes with
```
Uncaught (in promise) TypeError: t.tz is not a function
```
In preview/production environments after the Babel/Webpack update and dropped of `npm ci` in deploy process.
**

[stats] Fix moment-range and timezone

---

features/step_definitions/buyer_steps.rb

Fixes this random CircleCI bug: https://circleci.com/gh/3scale/porta/78331#tests/containers/31

Fix Cuke Given Step to Signup Buyer: Do not approve when already approved

---

app/events/base_event_store_event.rb
test/events/applications/application_deleted_event_test.rb
test/events/base_event_store_event_test.rb
test/events/domains/provider_domains_changed_event_test.rb
test/events/domains/proxy_domains_changed_event_test.rb
test/events/oidc/proxy_changed_event_test.rb
test/events/oidc/service_changed_event_test.rb
test/events/services/service_deleted_event_test.rb
test/events/services/service_token_deleted_event_test.rb
test/events/users/user_deleted_event_test.rb
test/workers/backend_delete_end_users_worker_test.rb
test/workers/backend_delete_service_token_worker_test.rb
test/workers/backend_delete_service_worker_test.rb
test/workers/backend_delete_stats_worker_test.rb
test/workers/create_service_token_worker_test.rb
test/workers/process_notification_event_worker_test.rb
test/workers/segment_delete_user_worker_test.rb
test/workers/zync_worker_test.rb

Otherwise it is counterintuitive and problematic, and this way it simplifies the code and it is also easier for any newcomer.
Outside the tests, it is used in the following places, all of them will keep working after this because the only expect a truthy value if it worked and a falsy value and if it didn't:
https://github.com/3scale/porta/blob/af47f5f0f34b856571eb0c3a4227ba5f17ed7849/app/models/contract/states.rb#L63-L65
https://github.com/3scale/porta/blob/af47f5f0f34b856571eb0c3a4227ba5f17ed7849/app/models/service_token.rb#L15-L17
https://github.com/3scale/porta/blob/af47f5f0f34b856571eb0c3a4227ba5f17ed7849/app/models/proxy.rb#L259-L263
https://github.com/3scale/porta/blob/af47f5f0f34b856571eb0c3a4227ba5f17ed7849/app/models/cinstance.rb#L269-L271 …

create_and_publish returns the event

---

app/lib/three_scale/sidekiq_logging_middleware.rb
app/models/account.rb
app/models/contract.rb
app/models/payment_detail.rb
app/models/settings.rb
app/models/user.rb
config/application.rb
config/initializers/audited_hacks.rb
lib/three_scale/filter_arguments.rb
test/unit/audited_hacks_test.rb
test/unit/sidekiq_logging_middleware_test.rb

The SidekiqLoggingMiddleware was missing to filter the sensitive
parameters when AuditedWorker was enqueued.
This commit moved all specific sensitive attributes to a global scope
and filtered these attributes in regular and Sidekiq logging.
[THREESCALE-2985](https://issues.jboss.org/browse/THREESCALE-2985)
- Create an account
- Sidekiq arguments should be filtered like the Audited one
I decided to move all specific sensitive attributes (like `user_key`) into Rails `filter_parameters` configuration. This way it will be filtered even on the Rails logging itself. Also, it will filter future models that possibly include this attributes. If this is not a desire …

Filter sensitive information in Sidekiq logging

---

app/controllers/buyers/service_contracts_controller.rb
app/views/buyers/service_contracts/new.html.erb
test/integration/buyers/service_contracts_controller_test.rb

Currently when you try to subscribe in some service, the plan listing is 
blank and when you try to submit it, it explodes an exception and it 
renders a weird 404 page.
This commit validates if the service plan exists
[THREESCALE-2944](https://issues.jboss.org/browse/THREESCALE-2944)
- Create user and application
- Create at least 2 services 
- Go to Accounts->Listing and choose created account
- Go to Service Subscriptions tab and try to add one available service subscription
- It should not have a blank option in the listing

Do not allow blank plan in service subscription

---

app/javascript/src/Types/libs/libdefs.js
package.json

1. The eslint script is *wrong* at the moment: `eslintrc` is not supposed to be there. As a config file it is used by default and including it in the script means we want to _linter_ it.
2. Ignore usage of `any` in window, it's unavoidable so no reason to have this warning always showing up.

Fix warning in eslint

---

test/factories/other.rb

This comment has been there since `28 Nov 2013` in a [wip commit](https://github.com/3scale/system/commit/cf1f0d1c5cc959ad1cc389ae4fab580e4ba81fee#diff-5ff39f52de683ee8bae9f36d8bde5a69R36), and I find it just confusing instead of helpful 😕 
The proxy is created anyway with this factory and the tests are relying on that.

Remove comment about proxy association in Service Factory

---

app/assets/stylesheets/provider/_tables.scss
app/assets/stylesheets/provider/admin/apiconfig/services/_proxies.scss
app/controllers/api/proxy_rules_controller.rb
app/lib/logic/rolling_updates.rb
app/models/proxy_rule.rb
app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
app/views/api/proxy_rules/_form.html.slim
app/views/api/proxy_rules/edit.html.slim
app/views/api/proxy_rules/index.html.slim
app/views/api/proxy_rules/new.html.slim
app/views/shared/provider/navigation/service/_integration.html.slim
config/examples/rolling_updates.yml
config/routes.rb
features/old/menu/api_menu.feature
features/step_definitions/menu_steps.rb
test/integration/api/proxy_rules_controller_test.rb

Our current page that manages the mapping rules don't have
pagination, causing a timeout if you have a lot of rules.
This commit creates a new independent page to manage Mapping rules
with a paginated list of itens.
[THREESCALE-3002](https://issues.jboss.org/browse/THREESCALE-3002)

Create an independent page to manage Mapping Rules

---

Dockerfile
Gemfile.base
Gemfile.lock
gemfiles/prod/Gemfile.lock

Changing the Dockerfile to not run webpacker:compile (because
assets:precompile already do it) we could remove the gem
activerecord-nulldb-adapter from the application. It was only used
to avoid webpacker:compile fail with a database connection error.
You can verify it  by trying to run the app with docker-compose locally:
```
make dev-setup
make dev-start
```

Remove activerecord-nulldb-adapter gem

---

app/models/backend_api.rb
app/models/proxy_rule.rb
db/migrate/20190801143026_add_owner_to_proxy_rules.rb
db/migrate/20190801143259_backfill_proxy_rules_owners.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/unit/proxy_rule_test.rb

This is step 1 of migrating mapping rules from the proxies to the backend APIs. Next step will be removing `proxy_id` and using only the new polymorphic owner.
Closes [THREESCALE-3157](https://issues.jboss.org/browse/THREESCALE-3157)
It contains commits of https://github.com/3scale/porta/pull/1059

[apiap] Polymorphic owner for ProxyRule

---

app/lib/backend/model_extensions/metric.rb
app/models/backend_api.rb
app/models/metric.rb
db/migrate/20190805135730_add_owner_to_metrics.rb
db/migrate/20190805135829_backfill_metric_owners.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/unit/backend/model_extensions/metric_test.rb
test/unit/metric_test.rb

This is step 1 of migrating metrics from the services to the backend APIs. Next step will be removing `service_id` and using only the new polymorphic owner.
Closes [THREESCALE-3158](https://issues.jboss.org/browse/THREESCALE-3158)
It contains commits of https://github.com/3scale/porta/pull/1059

[apiap] Polymorphic owner for Metric

---

features/step_definitions/applications/configuration_steps.rb

I accidentally found this while working on another issue and I saw that [it was deprecated 8 years ago](https://github.com/3scale/system/commit/e8dced76d30b3094aff6803a9102f979690e724a).

Remove Deprecated & Unused Cuke Step for partners to select plan

---

app/events/zync_event.rb
test/events/zync_event_test.rb

Closes THREESCALE-1526
Make sure that the metadata are kept in the successive events on ZyncEvent.create
Steps to reproduce:
1. Setup Porta and launch web server + Sidekiq with ZYNC_ENDPOINT=http://localhost:5000 ZYNC_AUTHENTICATON_TOKEN=foo
2. Setup Zync and launch web server with ZYNC_AUTHENTICATON_TOKEN=foo
3. Drop and recreate zync database: rails db:drop && ./bin/setup
4. Create an application (call it App1)
5. See in the Sidekiq Web UI that Proxy cannot be created and is stuck with UnprocessableEntityError
Expected result:
All the components needed in Zync (Tenant, Service, Proxy, Application) are created

[zync] Fixes issue when the Zync DB is reset, and Proxy can't be recreated

---

db/migrate/20190731092006_add_acts_as_product_to_service.rb
db/migrate/20190731092338_backfill_add_acts_as_product_to_service.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Extracted from https://github.com/3scale/porta/pull/1008 to make the PR smaller and it is actually part of https://github.com/3scale/porta/pull/1041
The way to do this PR has been making a new branch from master, reset the DBs (mysql, postgres and oracle) and setup, then rollback all of them with STEP=7 (just in case 😄 ), add these 2 migrations, and migrate the 3 DBs 😎

[Migrate] Service with field to act as product

---

app/controllers/api/proxy_rules_controller.rb
app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb
app/controllers/proxy_rule_shared_controller.rb
app/helpers/proxy_rules_helper.rb
app/views/api/proxy_rules/edit.html.slim
app/views/api/proxy_rules/index.html.slim
app/views/api/proxy_rules/new.html.slim
app/views/provider/admin/backend_apis/mapping_rules/edit.html.slim
app/views/provider/admin/backend_apis/mapping_rules/index.html.slim
app/views/provider/admin/backend_apis/mapping_rules/new.html.slim
app/views/shared/proxy_rules/_form.html.slim
app/views/shared/proxy_rules/_table.html.slim
config/routes.rb
test/helpers/proxy_rules_helper_test.rb

Now we have 2 pages to manage mapping rules, 1 for backend apis
and another for the service itself, and some code are being
duplicated between both. This commit tries to reuse some logics
and views for both pages.

Share logic between the 2 pages to manage Mapping Rules

---

.flowconfig
app/assets/stylesheets/provider/_forms.scss
app/controllers/provider/admin/service_discovery/cluster_projects_controller.rb
app/controllers/provider/admin/service_discovery/cluster_services_controller.rb
app/javascript/src/NewService/components/FormElements/ErrorMessage.jsx
app/javascript/src/NewService/components/FormElements/Select.jsx
app/javascript/src/NewService/components/FormElements/ServiceDiscoveryListItems.jsx
app/javascript/src/NewService/components/FormElements/index.jsx
app/javascript/src/NewService/components/NewServiceForm.jsx
app/javascript/src/NewService/components/ServiceDiscoveryForm.jsx
app/javascript/src/NewService/components/ServiceSourceForm.jsx
app/javascript/src/NewService/index.jsx
app/javascript/src/NewService/types/index.js
app/javascript/src/Types/libs/libdefs.js
app/javascript/src/utilities/utils.js
app/views/api/services/new.html.slim
spec/javascripts/NewService/NewServiceForm.spec.jsx
spec/javascripts/NewService/ServiceDiscoveryForm.spec.jsx
spec/javascripts/NewService/ServiceManualForm.spec.jsx
spec/javascripts/NewService/ServiceSourceForm.spec.jsx
spec/javascripts/NewService/formElements/FormWrapper.spec.jsx
spec/javascripts/NewService/formElements/Select.spec.jsx
spec/javascripts/NewService/formElements/ServiceDiscoveryListItems.spec.jsx
spec/javascripts/NewService/formElements/ServiceManualListItems.spec.jsx
spec/javascripts/Policies/components/PolicyList.spec.jsx

* Improves the way "error scenarios" are managed in the form, such as when projects is an empty string or when there's any error code.
* Improves *Flow* typings
* Improves the UI flow by adding a loading spinner and disabling inputs when there's an ongoing request
* Simplifies some pieces of logic
**Possible TODOs**
[THREESCALE-2646: Service Discovery: Improve error messages and visual feedback when ajax request fails](https://issues.jboss.org/browse/THREESCALE-2646)
Having Service Discovery enabled and logged in in Openshift go to `/apiconfig/services/new` and select *Import from Openshift*. Mess around the form and look for any errors.
**Visuals**
Expected:
When empty:
When error:

Improve Service Discovery Errors (AKA improve New API form)

---

app/lib/service_discovery/authentication_provider_support.rb
app/models/authentication_provider.rb
app/models/authentication_provider/custom.rb
app/models/authentication_providers/auth0.rb
app/models/authentication_providers/custom.rb
app/models/authentication_providers/github.rb
app/models/authentication_providers/keycloak.rb
app/models/authentication_providers/redhat_customer_portal.rb
app/models/authentication_providers/service_discovery_provider.rb
features/support/transforms.rb
lib/redhat_customer_portal_support.rb
test/factories/authentication_provider.rb
test/integration/admin/api/account/authentication_providers_controller_test.rb
test/integration/admin/api/authentication_providers_controller_test.rb
test/unit/account/provider_test.rb
test/unit/authentication_provider_test.rb
test/unit/liquid/drops/authentication_provider_drop_test.rb
test/unit/models_test.rb
test/unit/presenters/provider_oauth_flow_presenter_test.rb
test/unit/redhat_customer_portal_test.rb

This commit renames the module AuthenticationProvider to 
AuthenticationProviders to avoid clashing it with the already existent 
class with the same name. With this, we can safely drop the 
`require_dependency` for each authentication provider.

Rename AuthenticationProvider module to AuthenticationProviders

---

app/helpers/menu_helper.rb

This commit fix the problem that we currently have that displays
the backend apis in the menu even if the rolling update is turned
off

Don't display Backend APIs in menu if feature is off

---

app/assets/stylesheets/provider/admin/_dashboard.scss
app/javascript/packs/services_search_bar.js
app/views/provider/admin/dashboards/_services_filter.html.slim

🐛
`ApiFilter` is not working when APIAP is disabled, this was introduced in #1058 .
Fixes:
- Create a pack for services searchbar (to be consistent with #1058) that is loaded when APIAP rolling update is off
- Adjust style `.hidden` to affect both service sections and product/backend sections

Fixes API search in non-APIAP dashboards

---

app/assets/stylesheets/provider/_services.scss

When many items, padding gets weird. The problem is the styles targeting first, nth and last li-children.
**Before:**
**After:**

Fixes used backends list at Service overview

---

app/assets/stylesheets/provider/_commons.scss
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim

Renders a list of endpoints of all `@service.backend_api_config` instead of a single "Private Base URL".
Without API as Product (still like this for all services that do not act as product):
With API as Product:
"Private Base URL" will inflect automatically depending on the number of `backend_api_config` of the service.
[THREESCALE-3282: APIAP: list all backend API endpoints in the proxy config show page](https://issues.jboss.org/browse/THREESCALE-3282)
**Notes for reviewers**:
Go to `/apiconfig/services/<id>/integration`
Either have an APIcast running or create a `service_token` and a `proxy_configs`:
```ruby
s = Service.find(<id>)
s.service_tokens.create!(value: 'token')
s.proxy.proxy_configs.create(content: { …
```

List all backend API endpoints inside the APIcast config

---

app/assets/stylesheets/provider/_commons.scss
app/assets/stylesheets/provider/_metrics.scss
app/javascript/packs/plans-metrics.js
app/views/api/metrics/_backend_api.erb
app/views/api/plans/_metrics.html.erb

Sets table-layout to fixed so that both tables (metrics and backend_api_metrics) look aligned.
[THREESCALE-3092: APIAP: Application plan > edit > Methods & Metrics - Fix header style](https://issues.jboss.org/browse/THREESCALE-3092)
**Before**:
**After**:

[Do Not Merge] Fixes Metrics table header in Application Plan page

---

app/models/backend_api_config.rb

Remove a few no longer used associations from BackendApiConfig
* metrics (through service)
* proxy_rules (through proxy > service)
* aliases and related methods

Remove associations from BackendApiConfig

---

app/assets/stylesheets/provider/_metrics.scss
app/javascript/packs/plans-metrics.js
app/views/api/metrics/_backend_api.erb
app/views/api/plans/_metrics.html.erb

Adds a caret to the title and hides/shows the table.
[THREESCALE-3093: APIAP: Application plan > edit > Methods & Metrics - Collapsible table](https://issues.jboss.org/browse/THREESCALE-3093)
**Tested in**:
- Go to `apiconfig/application_plans/22/edit` and click on the names of each Backend API under _Metrics, Methods, Limits & Pricing Rules_
- Metrics from each particular API should collapse/expande
- The caret should rotate
- When no JS, there shouldn't any caret
- When no metrics, there shouldn't any caret either

Application Plan "Methods & Metrics" collapsible table

---

app/controllers/provider/admin/backend_apis_controller.rb
app/views/provider/admin/backend_apis/new.html.slim
test/integration/provider/admin/backend_apis_controller_test.rb

Adds the view for creating a new Backend API.
[THREESCALE-3322: APIAP: New page for backend APIs](https://issues.jboss.org/browse/THREESCALE-3322)
1. Go to backend_apis/new
2. Try to create a new one

New page for Backend APIs

---

app/controllers/provider/admin/backend_apis_controller.rb

Removes the empty vertical navigation showing up in `/backend_apis`.
Also fixes Context Selector `backend: undefined`.
**Before**:
**After**:

Fixes index view '/backend_apis'

---

app/assets/stylesheets/provider/_metrics.scss

Some styles introduced in #1121 affects other tables. This PR makes those more accurate.
**Before** (Methods & Metrics):
**After** (Methods & Metrics):
It also aligns `enable` column between tables at Application Plan's page:
**Before** (app plan page):
**After** (app plan page):

Fixes styles for "Metrics" tables

---

app/controllers/api/services_controller.rb
app/javascript/src/NewService/components/FormElements/BackendApiSelect.jsx
app/javascript/src/NewService/components/FormElements/index.jsx
app/javascript/src/NewService/components/NewServiceForm.jsx
app/javascript/src/NewService/components/ServiceManualForm.jsx
app/models/backend_api_config.rb
app/views/api/services/new.html.slim
spec/javascripts/NewService/NewServiceForm.spec.jsx
spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
test/integration/api/services_controller_test.rb

This commit adds a new option in the screen to create a service
to inform if it will act as product. If this options is checked, it will
present a select to choose which backend api it will be attached
or if it will create a new one.
This is when you create a Service without checking act as product:
This is when you create a Service checking act as product and let it create a new Backend API:
This is when you create a Service checking act as product and select an already existent Backend API:
[THREESCALE-3294](https://issues.jboss.org/browse/THREESCALE-3294)
1. Go to the screen to create a new Service
2. Create a new service without checking `act as product` checkbox.
3. It should create a …

Add an option to mark that the Service acts as product

---

app/assets/stylesheets/provider/_commons.scss
app/views/provider/admin/backend_apis/forms/_delete.html.slim

* List the list of products used by backend
* If there's any, disable the delete link
[THREESCALE-3344: Provide Feedback when there are Products used by a Backend](https://issues.jboss.org/browse/THREESCALE-3344)
Go to a Backend API edit page and try to delete it.

List products used by backend and disable delete link

---

test/integration/application_controller_test.rb

I have the perception that the tests in https://github.com/3scale/porta/pull/1123/files#diff-5d113ecd6dff22e5dfd32ef384f7dd74R13 are lacking this request.

Fix ApplicationControllerTest: modern browser test do requests before asserting

---

test/integration/admin/api/member_permissions_controller_test.rb
test/integration/master/api/finance/accounts/billing_jobs_controller_test.rb
test/integration/master/api/finance/billing_jobs_controller_test.rb
test/integration/payment_gateways/braintree_blue_test.rb
test/integration/provider/admin/keys_controller_test.rb
test/integration/sites/settings_controller_test.rb
test/integration/stats/clients_test.rb
test/test_helpers/authentication.rb

I encountered this while reviewing https://github.com/3scale/porta/pull/1008
We have several methods doing the same thing... besides, it was setting the `host` twice for all logins of providers.

[Refactor][Test] Remove redundant test login methods

---

app/controllers/provider/invitee_signups_controller.rb
config/locales/en.yml
test/integration/provider/invitee_signups_controller_test.rb

It was a small pending _TODO_ since https://github.com/3scale/porta/commit/d38138949dd374823d51117a11f43ef02e4cf65a#diff-31f104d42ede0161621ab77154eaf31bR59

[Refactor] InviteeSignups redirect if logged in flash message using i18n

---

app/controllers/admin/api/services_controller.rb
test/integration/admin/api/services_controller_test.rb

Closes [THREESCALE-3210](https://issues.jboss.org/browse/THREESCALE-3210)
Depends on https://github.com/3scale/porta/pull/1078 and https://github.com/3scale/porta/pull/1068

[APIAP][API Endpoints] Set the flag of a service to 'act as product'

---

app/javascript/src/Dashboard/tabs-widget.jsx

Tab highlight is not working in IE11 since `NodeList.forEach` is not supported.

Fixes tab highlighting in IE11

---

app/controllers/provider/admin/backend_apis_controller.rb
test/integration/provider/admin/backend_apis_controller_test.rb

Implements `destroy` method of Backend APIs. It checks whether the backend is used by any product: if so, it can't be destroyed; otherwise it is destroyed and user is redirected to the Dashboard.
[THREESCALE-3342: Implement basic deletion for Backend API](https://issues.jboss.org/browse/THREESCALE-3342)
1. Go to a Backend API and click on 'edit'
2. At the bottom there's the delete button, confirm the alert and
* if backend is used by any product: it redirects to edit page and shows an error message
* if backend is **not** used by any product: it redirects to dashboard and backend is deleted
**TODO**:

Implements basic deletion of Backend APIs

---

app/assets/stylesheets/provider/admin/_dashboard.scss
app/javascript/src/Dashboard/components/ApiFilter.jsx

* Removes white space from backends table when filtering in Safari
* Fixes name column width so that table doesn't change size when filtering
[THREESCALE-3358: filtering backends should remove white space](https://issues.jboss.org/browse/THREESCALE-3358)
1. Go to dashboard > Backends tab
2. Filter Backends. Make sure there are some with big names.
Verified in:

Remove white spaces when filtering backends in Safari

---

app/views/api/services/show.html.slim

Fixes text alignment issue in Product overview page
https://issues.jboss.org/browse/THREESCALE-3354
Go to **Your Product > Overview**
**Before:**
> ![before](https://user-images.githubusercontent.com/13486237/64016728-04baeb80-cb28-11e9-9df9-157908936047.png)
**After:**
> ![after](https://user-images.githubusercontent.com/13486237/64016733-097f9f80-cb28-11e9-8071-055be93e24d7.png)

Fixing broken alignment text in Product overview page

---

package-lock.json
package.json

Webpack loader `css-loader` must be updated
https://issues.jboss.org/browse/THREESCALE-3303

Updating css-loader to ^2.1.1

---

app/controllers/provider/admin/backend_apis_controller.rb
test/integration/provider/admin/backend_apis_controller_test.rb

Done for the Controller 👍 
For the UI it is already correct:
https://github.com/3scale/porta/blob/dd5c49fd0bc9903d3f6f88b1f0e0d98b4d2962ac/app/views/provider/admin/backend_apis/edit.html.slim#L4
https://github.com/3scale/porta/blob/dd5c49fd0bc9903d3f6f88b1f0e0d98b4d2962ac/app/views/provider/admin/backend_apis/forms/_naming.html.slim#L3
Just like we do for the rest of models, for example for service:
https://github.com/3scale/porta/blob/dd5c49fd0bc9903d3f6f88b1f0e0d98b4d2962ac/app/views/api/services/forms/_naming.html.slim#L3

UI BackendAPI Controller allows system_name for create but not for update

---

app/lib/backend_api_logic/routing_policy.rb
app/lib/string_utils/strip_slash.rb
app/models/backend_api_config.rb
app/models/proxy.rb
test/models/backend_api_config_test.rb
test/unit/proxy_test.rb

So the request is properly mapped to the correct upstream
Closes https://issues.jboss.org/browse/THREESCALE-3311

Inject Routing policy for Backend API upstreams (THREESCALE-3311)

---

features/old/accounts/bulk_operations.feature
features/old/accounts/bulk_operations/change_plans.feature
features/old/accounts/notifications.feature
features/old/accounts/service_contracts.feature
features/old/api/end_user_plans.feature
features/old/api/metrics/visibility.feature
features/old/api/usage_limits.feature
features/old/applications/buyers/application_management.feature
features/old/applications/providers/bulk_operations.feature
features/old/applications/providers/keys.feature
features/old/cms/changes.feature
features/old/emails.feature
features/old/liquid/active_docs.feature
features/old/services/subscriptions/bulk_operations.feature
features/step_definitions/api/end_user_plan_steps.rb
features/step_definitions/applications/keys_steps.rb
features/step_definitions/confirm_dialog_steps.rb
features/step_definitions/metric_steps.rb
features/step_definitions/new_cms/changes_steps.rb
features/step_definitions/notification_steps.rb
features/step_definitions/usage_limit_steps.rb
features/support/hooks.rb

As spoken in https://github.com/3scale/porta/pull/986/files#r304486361, the goal is to remove this `@ajax` tag and make wait only in those steps when it is necessary, so it will be faster.

[Refactor] Remove '@ajax' tag from cukes to be faster

---

app/decorators/proxy_rule_decorator.rb
app/models/proxy.rb
app/services/apicast_v2_deployment_service.rb
lib/apicast/proxy_rules_source.rb
lib/apicast/proxy_source.rb
test/unit/apicast/proxy_rules_source_test.rb

It allows overriding from Product level the Proxy Rules defined in Backend API
https://issues.jboss.org/browse/THREESCALE-3325

[Apicast::ProxySource] inject backend API proxy rules

---

app/javascript/src/Policies/components/SchemaEditor.jsx

We have an issue with `flow`. Locally it doesn't find any errors, but in `circle ci` we are getting this:
```
Launching Flow server for /opt/app-root/src/project
Spawned flow server (pid=442)
Logs will go to /tmp/flow/zSoptzSapp-rootzSsrczSproject.log
Monitor logs will go to /tmp/flow/zSoptzSapp-rootzSsrczSproject.monitor_log
Error ---------------------------------------------------- app/javascript/src/Policies/components/SchemaEditor.jsx:30:10
Cannot return `!ajv.validate(...) ? ajv.errors : []` because:
- undefined [1] is incompatible with array type [2].
- `Error` [3] is incompatible with `$npm$ajv$ErrorObject` [4] in array element.
- property `dataPath` is missing in `Error` [3] but exists in `$npm$ajv$ErrorObject` [4] in array element.
- …
```

Fixing ajv ErrorObject  error in circle ci

---

Gemfile.lock
gemfiles/prod/Gemfile.lock

bcrypt-ruby 3.1.11 is broken on Fedora 28 as these both issues
shows: https://github.com/codahale/bcrypt-ruby/issues/165
https://github.com/codahale/bcrypt-ruby/issues/170

Upgrade bcrypt-ruby to 3.1.13

---

app/javascript/src/LoginPage/utils/formValidation.js

Setting login password minimum length to 1, to avoid conflicts with our seeds that currently accepts 1 char.

Setting login password minimum length to 1

---

features/old/applications/providers/create_application.feature
features/step_definitions/service_steps.rb

The test passes when it should not. In order to show "create new service plan" there has to be no service plans.
https://issues.jboss.org/browse/THREESCALE-3390

Fix Create Application wrong test

---

package-lock.json
package.json

Updating `css-loader` to 2.x
Note: a previous [PR](https://github.com/3scale/porta/pull/1151) was reverted because master was failing. Trying again now that master issues are fixed
https://issues.jboss.org/browse/THREESCALE-3303

Updating css-loader to 2.x

---

app/lib/backend/model_extensions/service.rb
app/models/account.rb
app/models/backend/transaction.rb
app/models/cinstance.rb
app/models/service.rb

At first we thought that we needed this for the backend_id of a
Service, but if we are not using the service_prefix as it seems
from the SaaS DB, then the backend_id of the service by default
is just its id.
[THREESCALE-2025](https://issues.jboss.org/browse/THREESCALE-2025)

Stop using service_prefix column from Account

---

app/lib/backend_api_logic/routing_policy.rb
app/models/backend_api_config.rb

Test it locally with oracle DB for the test: `test/unit/proxy_test.rb:103`
For Oracle the empty string is saved as `NULL`.

[Bugfix][Oracle] path order in routing_policy working for null/empty values

---

app/helpers/buyers/applications_helper.rb
app/javascript/src/Applications/create_application.js
app/views/buyers/applications/new.html.erb

In Create Application form, when there isn't any Service Plan associated with a Service, a link is shown "create a new service plan". Currently that link is broken, now this PR sets the `href` of such element with the appropriate URL to the service _Service Plans_ page.
1. Go to New Application
2. Make sure you have a service with no service plans, select a plan from that service
3. Click on "create a new service plan" below the _Service Plan" dropdown and verify it goes to the proper page

Fixes "create new service plan" link in New Application form

---

app/javascript/src/Policies/types/index.jsx
package.json
spec/javascripts/LoginPage/SignupPageWrapper.spec.jsx
spec/javascripts/Navigation/ContextSelector.spec.jsx
spec/javascripts/Policies/components/PolicyChain.spec.jsx
spec/javascripts/Policies/middleware/PolicyChain.spec.jsx

`eslint` watches both **js** and **jsx** files when running webpack-dev. However it only includes **js** when running in CI.
This PR fixes the script `lint` for that purpose.

Include JSX files under Eslint coverage

---

features/old/switches/branding.feature
features/step_definitions/switches_steps.rb

The test is using this screen in the test:
But it should display an "Upgrade" button.
The test only passes because the assertion is too broad:
```
assert has_content?("Upgrade")
```
And it finds the word _Upgrade_ in the page `<title>` so that it falsely passes.
https://issues.jboss.org/browse/THREESCALE-3390
```
cuke features/old/switches/branding.feature:12
```
should pass.

Fixes wrong feature for Branding

---

app/models/backend_api.rb
test/integration/provider/admin/backend_apis/metrics_controller_test.rb
test/models/backend_api_test.rb
test/unit/backend_api_logic/service_extension_test.rb
test/unit/metric_test.rb

Closes [THREESCALE-3355](https://issues.jboss.org/browse/THREESCALE-3355)

Create default 'hits' metric to backend API

---

app/javascript/src/LoginPage/loginForms/RequestPasswordForm.jsx

Adding validation to request password form when pristine
In https://github.com/3scale/porta/pull/1005 form validation was added.
But I missed the pristine state of email input in request password form
**Pristine:**
**Dirty:**

Adding validation to request password form when pristine

---

features/old/accounts/buyers/personal_details.feature
features/old/proxy.feature
features/step_definitions/applications/keys_steps.rb
features/step_definitions/buyer_steps.rb
features/step_definitions/buyers_management/user_steps.rb
features/step_definitions/capcha_steps.rb
features/step_definitions/cms/email_template_steps.rb
features/step_definitions/credit_card_steps.rb
features/step_definitions/custom_web_steps.rb
features/step_definitions/fields_steps.rb
features/step_definitions/liquid_steps.rb
features/step_definitions/navigation_steps.rb
features/step_definitions/personal_details_steps.rb
features/step_definitions/proxy_steps.rb
features/step_definitions/spam_protection_steps.rb
features/step_definitions/stats/application_steps.rb
features/step_definitions/stats_steps.rb
features/support/capybara.rb
features/support/current_user.rb
features/support/helpers/messages_helpers.rb

Some elements are found in even when the are _not visible_, resulting in false positives.

Ignore hidden elements in Capybara to avoid false positives

---

app/controllers/api/proxy_rules_controller.rb
app/helpers/vertical_nav_helper.rb
app/models/account.rb
app/views/api/integrations/apicast/shared/_mapping_rules.html.slim
app/views/shared/provider/navigation/service/_integration.html.slim
features/old/menu/api_menu.feature
test/integration/api/proxy_rules_controller_test.rb
test/unit/service_test.rb

We need to make independent_mapping_rules always enabled for
services acting as product.
[THREESCALE-3341](https://issues.jboss.org/browse/THREESCALE-3341)
Depends on https://github.com/3scale/porta/pull/1156

Make independent mapping rules always enabled when APIAP is on

---

app/lib/backend/model_extensions/metric.rb
app/lib/backend_api_logic/metric_extension.rb
app/models/metric.rb
app/workers/backend_metric_worker.rb
test/unit/backend/model_extensions/metric_test.rb
test/unit/backend_api_logic/metric_extension_test.rb
test/unit/metric_test.rb
test/workers/backend_metric_worker_test.rb

Closes [THREESCALE-3399](https://issues.jboss.org/browse/THREESCALE-3399)

Sync backend API 'hits' metrics with apisonator as children of service 'hits'

---

app/lib/backend/model_extensions/backend_api_config.rb
app/lib/backend/model_extensions/metric.rb
app/lib/backend/storage_rewrite.rb
app/models/backend_api_config.rb
app/workers/backend_metric_worker.rb
test/unit/backend/model_extensions/backend_api_config_test.rb
test/unit/backend/model_extensions/metric_test.rb
test/workers/backend_metric_worker_test.rb

Whenever a new `BackendApiConfig` is created, we need to synchronize all existing metrics that belong to the `backend_api` as if they were owned by the `service` (product), but because of ActiveRecord caching of model associations, we are not really achieving that.
Also, there's no need to synchronize again for all services; only for the one service (product) of the config.

Fix sync of backend api metrics on create BackendApiConfig

---

features/step_definitions/dashboard_steps.rb

Some title in system are upper case and Capybara is case-sensitive by default. Adding a regex with the flag `/i` fixes this issue.
Error:
```
failed Folded services have no overview data
Scenario: Folded services have no overview data
And service "Fancy API" is folded
Message:
Unable to find visible css "section" with text "Fancy API" within #<Capybara::Node::Element tag="section" path="/html/body/div[1]/div/main/div/div[1]/section[2]"> (Capybara::ElementNotFound)
```
EDIT
And also it's required to specify `visible: false` so that the element is found and asserted.
Using `visible: :hidden` could make the test throw an error, which would be also valid but not so elegant.

Fixes test by making assertion case insensitive

---

CONTRIBUTING.md

This is how it looks before this PR:
This is how it looks like after this PR:

[Doc] Add missing ')' in Contributing for the right format

---

package-lock.json
package.json

NPM silently installed `react-jsonschema-form@1.8.0` which has a change in their `Form` component that breaks our implementation.
Since we rely on `1.3.0`, let's install that _exact_ version.
fixes https://issues.jboss.org/browse/THREESCALE-3475

Fix missing configs in Custom Policies

---

app/decorators/proxy_rule_decorator.rb
test/unit/apicast/proxy_rules_source_test.rb

Backend api mapping rules injected in the proxy config have two problems:
1. It does not prepend the backend API config path to the pattern of the proxy rule
2. It does not inject the full `system_name` of the metric but only the part without the `.#{backend_api.id}` suffix
First problem is due to draper's `delegate_all` method used in https://github.com/3scale/porta/blob/ccc776ca84d1acb04694f8762c405eed5bdf4137/app/decorators/application_decorator.rb#L4. This method makes the decorator class to dynamically define delegations of the decorated object's instance methods to the object itself, thus making `ProxyRuleDecorator#pattern` to execute only once and then always be delegated to the object.
See https://github.com/drapergem/draper/issues/818
The second …

Fix Backend API mapping rules injected into the proxy config

---

app/models/backend_api.rb
lib/tasks/backend_api.rake
test/models/backend_api_test.rb
test/unit/tasks/backend_api_test.rb

Although the deletion process of Services is async, even after
several hours or even days a given Service cannot be created again
using the same system_name from a previously deleted one. This
happens because the backend api is still created. Some customers
reported this bug.
This commit includes a Rake task to allow us to run this in cli
to destroy orphans backend apis

Include Rake task to destroy orphans backend apis

---

app/models/account.rb
app/models/account/provider_domains.rb
test/unit/account/provider_domains_test.rb

Remove the usage of require_dependency in Account models
- This one removes the needing of require_dependency
'account/domains'. To this, we needed to rename the
Account::Domains concern to be Account::ProviderDomains in order
to not have naming clashes with the other Domains module.
- Remove the backend_client require_dependency from Account class.

Remove require dependency from account

---

app/controllers/admin/api/services/proxies_controller.rb
doc/active_docs/Account Management API.json
doc/active_docs/preview/Account Management API.json

This PR adds the `authorization` option to the API documentation for the proxy update where it is missing.
It is extending the #90 PR.

Extends the documentation of the credentials_location option -- adds the Basic Auth option

---

db/migrate/20190716110000_add_owner_to_metrics.rb

After https://github.com/3scale/porta/pull/1171, https://github.com/3scale/porta/commit/bbd7051d92cfc4f286f0c0ae28c04aa1d9bd65a2 became a requirement for https://github.com/3scale/porta/blob/8cecd33c61eed6e724ffcc2108effb89fd913ac0/db/migrate/20190716110520_create_the_backend_apis_of_services.rb.
Closes [THREESCALE-3485](https://issues.jboss.org/browse/THREESCALE-3485)
```
git co c2204dcdf8cf3e5a9484e635df3bba7544e8b529~1 # right before the migration that breaks without this PR
bundle exec rake db:reset
git co fix/create-backend-apis-migration
bundle exec db:migrate
```
You should see no error
```
Migrating to CreateTheBackendApisOfServices (20190716110520)
== 20190716110520 …
```

Move creation of metric.owner_(id|type) before migration of existing backend APIs

---

app/helpers/application_helper.rb
lib/system/deploy.rb
test/unit/deploy/basic_info_test.rb

`major_and_minor_version_path` does not work for "upstream" release name
https://issues.jboss.org/browse/THREESCALE-2250

[major_and_minor_version_path] unknown version 

---

test/unit/csv/applications_exporter_test.rb

The order in postgres changes depending on the execution, so if we fetch the `2nd` and the `2nd` changes for each execution, then sometimes it is going to raise an error because it does not fetch the one we want. So this PR just orders by ID before fetching, so it will always fetch the same one 😄 
Fixes [this random bug](https://circleci.com/gh/3scale/porta/101044?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).
Run several times locally `DATABASE_URL="postgresql://postgres:@localhost:5433/systempdb" bundle exec m test/unit/csv/applications_exporter_test.rb:54`

Fix Random Bug in Test: Order Services by ID before fetching the 2nd [Test Export to CSV]

---

test/integration/admin/api/backend_apis_controller_test.rb

Fixes the tests:
- The name contains the proper name
- Removed a repeated method
It was originally fixed as part of https://github.com/3scale/porta/pull/1178 but that PR is not in master yet because it pointed to another PR waiting for the blockers.
It needs to be fixed now because it is failing tests in oracle (integration) for this.
The tests in oracle for cucumber are fixed in another PR 😉

Fix Test for BackendApisController

---

app/controllers/api/services_controller.rb
app/helpers/api/services_helper.rb
app/helpers/vertical_nav_helper.rb
app/views/api/services/settings.html.slim
features/old/menu/api_menu.feature
features/old/services/multiservice.feature

The current Integration > Settings needs to be migrated to Applications > Usage Rules when rolling update `api_as_product` is enabled
fixes https://issues.jboss.org/browse/THREESCALE-3471
* With Rolling update on:
* With Rolling update off:
Mind the rolling update feature needs to be either `false` or an array with the provider_id (s)

Integration Settings as Application Usage Rules

---

app/assets/stylesheets/provider/_patternfly_tabs_fake.scss
app/assets/stylesheets/provider/_theme.scss
app/assets/stylesheets/provider/admin/_dashboard.scss
app/javascript/src/Dashboard/tabs-widget.jsx
app/views/provider/admin/dashboards/_apiap_navigation.html.slim
app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
features/old/authorization/provider_plans_section.feature
features/old/menu/dashboard.feature
features/step_definitions/custom_web_steps.rb
features/support/selectors.rb

~⚠️**PF4 Styles**⚠️ There's still an issue with the hover style. For some reason I can't get the [::after style](https://github.com/3scale/porta/pull/1190/files#diff-b04944eeb7c91095409e39e62cf6cf8cR54) work, despite the fact that it works for `.pf-m-current`.~
[THREESCALE-3357: Improve product and backend tabs on dashboard](https://issues.jboss.org/browse/THREESCALE-3357)
* Feels and looks like [PF4 tabs](https://pf4.patternfly.org/components/Tabs/examples/)
* After refreshing the page, same tab is selected (it doesn't show Products by default)

Improve Tabs in Dashboard

---

openshift/system/config/rolling_updates.yml

So it is the default behaviour for on premises builds

Enable APIAP on On-premises

---

app/helpers/vertical_nav_helper.rb

**API > Applications > Settings** should have subheader in vertical nav, just like  **Audience > Accounts > Settings**
[THREESCALE-3511](https://issues.jboss.org/browse/THREESCALE-3511)
**With APIAP on:**
**With APIAP off:**

Adding Settings subheader to Application menu when APIAP is on

---

app/controllers/api/services_controller.rb
app/helpers/api/services_helper.rb
app/helpers/vertical_nav_helper.rb
app/views/api/services/forms/_usage_rules.html.slim
app/views/api/services/usage_rules.html.slim
config/routes.rb

This aims to enhance the previous https://github.com/3scale/porta/pull/1202, making it a bit easier to tackle https://issues.jboss.org/browse/THREESCALE-3451
Improves  https://issues.jboss.org/browse/THREESCALE-3471
This is an enhancement of the previous https://github.com/3scale/porta/pull/1202
* The views are duplicated, but it's needed in order to get independence for method
settings
* In the future, we just adjust the cukes to Usage Rules instead of old
Settings, and we can safely remove the old settings
* Clean, no conditionals

[Usage Rules] Separated view and route

---

app/models/backend_api_config.rb

Oracle consider VARCHAR `''` as NULL
So lets just typecast it in the model

[oracle] Fix for empty String in Oracle

---

features/step_definitions/master_steps.rb

Fixes the random failure [in CircleCI](https://circleci.com/gh/3scale/porta/105017#tests/containers/18) with title `failed The 404 page` and in `features/percy/provider.feature:5:in Given the master account allows signups`

Fix Cuke Master Step ensuring that master exists or creates it

---

features/step_definitions/provider_steps.rb

Fixes [this random cuke error in CircleCI](https://circleci.com/gh/3scale/porta/104931#tests/containers/18).
It doesn't happen always, but sometimes it fails in the step _a provider signs up and activates his account_ because it tries to fetch from the internet _the integration errors_ but CircleCI shouldn't try to access the internet so it is stubbed here using this:
https://github.com/3scale/porta/blob/434182f7f4889f04fe4efbdd26e052be22034f5b/test/test_helpers/backend.rb#L87-L91
https://github.com/3scale/porta/blob/434182f7f4889f04fe4efbdd26e052be22034f5b/features/step_definitions/provider_steps.rb#L142-L146
Just like we are currently doing for other steps before logging in:
https://github.com/3scale/porta/blob/434182f7f4889f04fe4efbdd26e052be22034f5b/features/step_definitions/provider_s …

Fix Cuke Step: stub integration errors after signup and before login

---

app/views/api/proxy_rules/index.html.slim
app/views/api/proxy_rules/new.html.slim
app/views/shared/proxy_rules/_form.html.slim
app/views/shared/proxy_rules/_table.html.slim
test/integration/api/proxy_rules_controller_test.rb
test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb

We currently have a bug in
app/views/shared/proxy_rules/_form.html.slim page. To render the
redirect_url field, it relies on the owner to check if it is
using proxy pro. But this caller to owner is invalid. Owner for
ProxyRule can be a Proxy or BackendApi, not the Service (which we
expect to call the using_proxy_pro method).

Fix redirect_url field in the proxy and backend_api/mapping rules

---

app/controllers/admin/api/services/proxies_controller.rb
app/controllers/api/integrations_controller.rb
app/lib/gateway_settings/proxy_extension.rb
app/models/gateway_configuration.rb
app/models/proxy.rb
app/representers/proxy_representer.rb
app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
app/views/api/integrations/apicast/shared/_oidc.html.slim
config/locales/en.yml
db/migrate/20190920123906_create_gateway_configurations.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
doc/active_docs/Account Management API.json
lib/apicast/provider_source.rb
lib/system/database/definitions/mysql.rb
lib/system/database/definitions/oracle.rb
lib/system/database/definitions/postgres.rb
spec/acceptance/api/proxy_spec.rb
test/models/gateway_configuration_test.rb
test/unit/apicast/provider_source_test.rb

Closes THREESCALE-2542
Ability to configure through API and UI the JWT Claim With ClientID
By default in the UI they are pre-filled to `plain` and `azp` if OIDC is chosen as authentication methid, so customers are not confused.
In the API they are not set as the default in APIcast no values means `plain` and `azp` anyway
This  PR introduces a new storage for the Proxy model: GatewayConfiguration
Instead of using columns, configurations are stored into a JSON field through `ActiveRecord::Base::store` method
It will be more flexible in the future, no need of migration (proxies table is quite core in the project)
Also we could migrate probably the old columns to that one but no need for now.

THREESCALE-2542 Ability to configure JWT Claim with ClientID

---

app/controllers/api/backend_api_configs_controller.rb
app/lib/backend_api_logic/service_extension.rb
app/models/backend_api_config.rb
app/views/api/backend_api_configs/new.html.slim
app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
config/abilities/provider_admin.rb
config/routes.rb
test/factories/account.rb
test/factories/simple.rb
test/integration/api/backend_api_configs_controller_test.rb
test/models/backend_api_config_test.rb
test/unit/abilities/provider_admin_test.rb

Closes [THREESCALE-3321](https://issues.jboss.org/browse/THREESCALE-3321)

Add Backend API config to product

---

app/models/backend_api.rb

We have a performance issue in our orphans method for BackendApi.
This commit changes it to use not in instead of a left join. This
reduced our query running from 80 seconds to 30 miliseconds in a
table with 37 thousands records.

Change BackendApi#orphans to use not in instead of Left Join

---

config/application.rb
openshift/system/entrypoint.sh

This PR makes the default rolling updates in `openshift/system/config/rolling_updates.yml`
to be merged with `config/extra-rolling_updates.yml`
Blocks: https://github.com/3scale/porta/pull/744

[Rolling Updates] On-premises, defaults are merged to extra configs

---

openshift/system/config/rolling_updates.yml

So we can remove the rolling_updates.yml mount from the templates
And just document how to customize any rolling updates
Relates to https://github.com/3scale/3scale-operator/pull/117#issuecomment-478922952
Relates to https://issues.jboss.org/browse/THREESCALE-2604
Requires https://github.com/3scale/porta/pull/744
This is the same as https://github.com/3scale/3scale-amp-openshift-templates/blob/2.6.0.GA/amp/amp.yml#L1581-L1603 with `api_as_product: true`

[onprem] Synchronize templates and code rolling updates

---

app/assets/stylesheets/provider/_tables.scss
app/controllers/api/backend_api_configs_controller.rb
app/helpers/vertical_nav_helper.rb
app/models/backend_api_config.rb
app/views/api/backend_api_configs/_form.html.slim
app/views/api/backend_api_configs/edit.html.slim
app/views/api/backend_api_configs/index.html.slim
app/views/api/backend_api_configs/new.html.slim
app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
config/routes.rb
features/old/menu/api_menu.feature
test/integration/api/backend_api_configs_controller_test.rb

Closes [THREESCALE-3472](https://issues.jboss.org/browse/THREESCALE-3472)

CRUD for backend api configs detached from proxy config page

---

INSTALL.md

BecauseHomebrew bottles are compiled with default environments
and with dynamic library of mysql pointing to  @@HOMEBREW_PREFIX@@/opt/mysql/lib/libmysqlclient.21.dylib
It needs to be build from source to take into account that we use mysql@5.7

[INSTALL.md] Install sphinx from source

---

app/models/backend_api.rb
app/models/backend_api_config.rb
app/models/deleted_object.rb
app/models/service.rb
app/views/api/backend_api_configs/_form.html.slim
db/migrate/20190925133159_enforce_uniqueness_association_service_backend_api.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/integration/provider/admin/backend_apis_controller_test.rb
test/models/backend_api_config_test.rb
test/models/backend_api_test.rb

We need this for now for the API. Because we are hiding the 'backend api config' from the customer, so we are not returning its ID, so without this PR, the only way to identify a backend api config in `/admin/api/services/:service_id/backend_apis/` to update it or destroy it is by the field path, which is clearly a bad idea because it would be part of the path of the request and because it can be empty.
Which this PR, it is just the ID of the backend_api :smile:

Ensure uniqueness of service_id + backend_api_id

---

Gemfile.base
Gemfile.lock
app/controllers/api/proxy_rules_controller.rb
app/controllers/provider/admin/backend_apis/mapping_rules_controller.rb
app/controllers/proxy_rule_shared_controller.rb
app/indices/proxy_rules_index.rb
app/models/proxy_rule.rb
app/queries/proxy_rule_query.rb
app/views/shared/proxy_rules/_table.html.slim
app/workers/application_job.rb
app/workers/index_proxy_rule_worker.rb
config/routes.rb
features/support/env.rb
gemfiles/prod/Gemfile.lock
test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
test/integration/service_not_deleted_test.rb
test/monkey_patches/active_job_test_helper.rb
test/test_helper.rb
test/unit/proxy_rule_test.rb
test/unit/queries/proxy_rule_query_test.rb

This commit implements a search by pattern for mapping rules. It
includes a search field in the mapping rules page for both Backend
APIs and Services. It also adds an index for ProxyRule class using
Sphinx.

Implement search by pattern for Mapping Rules

---

app/controllers/api/integrations_controller.rb
app/presenters/api/integrations_show_presenter.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
test/unit/presenters/api/integrations_show_presenter_test.rb

1. We will be able to hide the button once https://github.com/3scale/porta/pull/1244 gets merged. (Ideally also https://github.com/3scale/porta/pull/1235.)
2. We also need to solve a previous step when it's the first staging config to be generated. Right now we are pointing the user to the integration edit page where the "Save & test" is broken, apart from other fields that should not appear for APIAP-accounts.
3. We can easily improve the flash message shown after the config is promoted in https://github.com/3scale/porta/blob/95cf0c394bb8ee73131184080361e2be03d8f8a3/app/controllers/api/integrations_controller.rb#L33

Promote to Staging button

---

app/lib/backend_api_logic/service_extension.rb
db/migrate/20190716110520_create_the_backend_apis_of_services.rb
db/migrate/20190801143259_backfill_proxy_rules_owners.rb
db/migrate/20190805135829_backfill_metric_owners.rb
lib/tasks/proxy.rake
lib/tasks/services.rake
test/unit/backend_api_logic/service_extension_test.rb
test/unit/tasks/proxy_test.rb
test/unit/tasks/services_test.rb

Rails migrations should not really contain changing-state DML code (INSERT, UPDATE, DELETE), as they are not sufficiently tested and tend not to follow changes in the code.
Closes [THREESCALE-3556](https://issues.jboss.org/browse/THREESCALE-3556)
Try upgrade 3scale from 2.6 to a newer version. You should see no migration exceptions.
**Missing**

Extract apiap data migrations to rake tasks

---

app/lib/logic/rolling_updates.rb
test/unit/logic/rolling_updates_test.rb

Impersonation admin has the same role than any admin
Closes https://issues.jboss.org/browse/THREESCALE-3442
**TL;DR It has become confusing when doing support and mess up with some live tests**
- We use impersonation administrator to investigate some support cases
So the behaviour should be the same as any normal administrator of the tenant
- `provider_can_use?` has different meaning if it is used in the view as a helper,
if it is used in the controller as method, or in the model as method
- Also the behaviour changes with skipped? and enabled? in the tests
- chaining different RU can be complex ....
- Does really anyone wants to test RU with impersonation admin? If we want to test a feature we just create an account and enable RU on this account
- It is also an old code (4 years) without …

[Rolling updates] Make impersonation admin behave like normal admin

---

app/events/proxy_configs/affecting_object_changed_event.rb
app/lib/event_store/repository.rb
app/lib/proxy_config_affecting_changes.rb
app/models/backend_api.rb
app/models/proxy.rb
app/models/proxy_config_affecting_change.rb
app/models/proxy_rule.rb
app/subscribers/proxy_config_event_subscriber.rb
app/workers/proxy_config_affecting_change_worker.rb
db/migrate/20190925152107_create_proxy_config_affecting_changes.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/events/proxy_configs/affecting_object_changed_event_test.rb
test/subscribers/proxy_config_event_subscriber_test.rb
test/unit/proxy_rule_test.rb
test/unit/proxy_test.rb
test/workers/proxy_config_affecting_change_worker_test.rb

It defines a new event to be issued whenever an object that is part of a proxy config changes (or gets created, or destroyed). This event will asynchronously touch a tracking record in a separate table, also introduced, that holds a 1-1 relationship with proxy.
This will make possible for the UI to highlight for the user a potential outdated proxy config, thus being relevant to https://github.com/3scale/porta/pull/1235.
Closes [THREESCALE-3555](https://issues.jboss.org/browse/THREESCALE-3555)
**TODOs**
- `ProxyRule` (`Metric` deletion will kick `ProxyRule` deletion, so already covered)
- ~`Policy`~
- `Proxy` (Maybe only a few attributes – `policies_config`)
- `GatewayConfiguration`
**Special notes for your …

Proxy config affecting change events

---

app/assets/stylesheets/provider/_patternfly_ie11.scss
app/helpers/application_helper.rb
app/helpers/provider/admin/dashboards_helper.rb
app/javascript/packs/vertical_nav.js
app/javascript/src/Navigation/components/PF4NavProxy.jsx
app/javascript/src/Navigation/components/VerticalNav.jsx
app/models/service.rb
app/views/provider/admin/dashboards/_service_navigation.html.slim
app/views/shared/provider/navigation/_vertical_nav.html.slim
app/views/shared/provider/navigation/_vertical_nav_item.html.slim
test/unit/helpers/provider/admin/dashboards_helper_test.rb

_hiding other icons to make this one stand out, other icons should be removed anyway as icons are no longer supported in vertical nav so doesn't make sense._

Show exclamation mark for each product with out of date config

---

app/controllers/admin/api/backend_apis/metrics_controller.rb
test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
test/integration/admin/api/backend_apis/metrics_controller_test.rb

Fixes [this inconsistency reported by QE](https://issues.jboss.org/browse/THREESCALE-3209?focusedCommentId=13790191&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13790191).

MetricsController in API must behave the same way for BackendApi as for Service

---

app/controllers/provider/admin/backend_apis_controller.rb
app/models/backend_api.rb
app/models/backend_api_config.rb
app/representers/backend_api_representer.rb
app/views/provider/admin/backend_apis/forms/_delete.html.slim
app/workers/delete_object_hierarchy_worker.rb
app/workers/delete_service_hierarchy_worker.rb
config/locales/en.yml
spec/acceptance/api/backend_api_spec.rb
test/integration/admin/api/backend_apis_controller_test.rb
test/integration/admin/api/services/backend_api_configs_controller_test.rb
test/integration/provider/admin/backend_apis_controller_test.rb
test/models/backend_api_config_test.rb
test/models/backend_api_test.rb
test/workers/delete_service_hierarcy_worker_test.rb

Closes [THREESCALE-3571](https://issues.jboss.org/browse/THREESCALE-3571)

Cannot destroy a BackendApi used by Services

---

app/lib/proxy_config_affecting_changes.rb
app/models/backend_api_config.rb
app/models/proxy.rb
test/models/backend_api_config_test.rb
test/unit/proxy_rule_test.rb
test/unit/proxy_test.rb

Currently `BackendApiConfig` object are not signalling a proxy config affecting change. They should. So we show the exclamation mark to the user whenever a backend is added to a product, edited ot removed.

BackendApiConfig as an affecting object of Proxy config

---

app/helpers/api/services_helper.rb
app/helpers/cinstances_helper.rb
app/views/api/services/_delete.html.slim
app/views/provider/admin/backend_apis/forms/_delete.html.slim

Closes [THREESCALE-2547](https://issues.jboss.org/browse/THREESCALE-2547)
Not sure if it is a good idea but I am escaping JSON instead of HTML to obtain this. For this:
https://github.com/rails/rails/blob/a273da7619ac6a2b2f98532a5610238c68ad219b/activesupport/lib/active_support/core_ext/string/output_safety.rb#L10-L11

[LOW PRIORITY][Fix] Escaped HTML entities in edit API page

---

app/services/policies/policies_list_service.rb
config/locales/en.yml

Before this PR:
After this PR:

Improve error message when the apicast registry url is not present + 'Start by'

---

app/assets/stylesheets/provider/_commons.scss

[THREESCALE-3585: When product has no mapping rules, show page looks weird](https://issues.jboss.org/browse/THREESCALE-3585)
**Before:**
**After:**

Sets correct min-height to element dd

---

app/controllers/api/services_controller.rb

Currently, if we edit some service's proxy field at
/apiconfig/services/:id/settings, the value is not being saved.
This commit fixes this problem, making the controller to accept
the right attributes sent from the UI.

Fix proxy fields not being updated

---

app/views/api/services/forms/_authentication_settings.html.slim
app/views/api/services/forms/_oidc.html.slim

Fixes a bug when Service Mesh integration was saved and auth options were displayed.
Fixes https://issues.jboss.org/browse/THREESCALE-3591
APIAP and Istio should be enabled in rolling updates.
Visit Integration -> Settings
When picking Istio integration and auth key, hit `update service` then authentication settings should not be available. 
Testing will be done when replaced by react component.

[settings] Disabling auth options when service mesh and not oidc

---

app/controllers/api/services_controller.rb
app/helpers/alerts_helper.rb
app/views/api/services/forms/_settings.html.slim
app/views/api/services/forms/_usage_rules.html.slim
app/views/api/services/settings_apiap.html.slim

Fixes [THREESCALE-3588](https://issues.jboss.org/browse/THREESCALE-3588)
Currently if we try to save a service settings with wrong value,
it renders the service edit page instead of the service settings
page. This commit fixes this

Fix wrong page rendering in Service Settings page

---

app/javascript/src/Policies/components/PoliciesWidget.jsx
app/views/api/policies/edit.html.slim

Fixes broken logic regarding update buttons in Policies:
* Move button into a fieldset
* Changes query from `input#id` to simply the id.

Fixes update buttons in new Policies page

---

app/controllers/api/services_controller.rb
app/lib/api_integration/settings_result.rb
app/views/api/integrations/apicast/shared/_proxy_endpoints.html.slim
app/views/api/services/forms/_integration_settings_apiap.html.slim
test/functional/api/services_controller_test.rb
test/integration/api/services_controller_test.rb
test/unit/lib/api_integration/settings_result_test.rb

Closes [THREESCALE-3576](https://issues.jboss.org/browse/THREESCALE-3576)
1. In `config/rolling_updates.yml` you will need `api_as_product: true`
2. In `config/settings.yml` you will need `apicast_custom_url: http://example.com.lvh.me` for this:
https://github.com/3scale/porta/blob/17d259fa26abe0bbbfc710c869cc3bf7c3a26470/app/helpers/api/integrations_helper.rb#L71-L75
3. Run the server with `UNICORN_WORKERS=8 bundle exec rails server -b 0.0.0.0`
4. Through the browser, go to `http://provider-admin.example.com.lvh.me:3000/apiconfig/services/:service_id/settings`
5. Change that data and update :dancer:

[APIAP] Update Proxy public/staging urls from Integration -> Settings

---

app/controllers/admin/api/objects_controller.rb
config/routes.rb
doc/active_docs/Account Management API.json
test/integration/admin/api/objects_controller_test.rb

API endpoint: object deletion status for objects that are deleted asynchronously
https://issues.jboss.org/browse/THREESCALE-3265

[api#ednpoint] objects status endpoint

---

app/lib/backend_api_logic/routing_policy.rb
test/unit/backend_api_logic/routing_policy_test.rb
test/unit/proxy_test.rb

It changes the routing policies injected into the proxy config for the backends of a product so they use the `replace_path` rule with `remove_first` instead of with `replace`.
Porta is currently generating proxy configs for products containing backends with paths with the following attribute in the corresponding injected routing policy:
```
"replace_path": "{{original_request.path | replace: '/the-path', '/'}}"
```
This is causing apicast to route the incoming traffic, for example, from `<public-domain>/the-path/actual-backend-path`, to `<private-domain>//actual-backend-path`. The correct backend endpoint would be `<private-domain>/actual-backend-path`.
We should use instead in the routing policy injected for the …

Fix apicast replace_path to use remove

---

app/controllers/api/integrations_controller.rb
app/controllers/frontend_controller.rb
app/helpers/api/integrations_helper.rb
app/lib/proxy_config_affecting_changes.rb
app/presenters/api/integrations_show_presenter.rb
app/views/api/backend_api_configs/new.html.slim
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
app/views/api/integrations/apicast/shared/_deployment_options.html.slim
app/views/api/integrations/show.html.slim
app/views/provider/admin/backend_apis/edit.html.slim
app/views/provider/admin/backend_apis/new.html.slim
app/views/provider/admin/dashboards/_service_navigation.html.slim
features/old/api/settings.feature
features/old/menu/dashboard.feature
test/unit/proxy_test.rb

It implements the new workflow for generating/promoting proxy configs on APIAP, mostly changing the UI.
_Non-APIAP_
_APIAP_
Closes
- [THREESCALE-3581](https://issues.jboss.org/browse/THREESCALE-3581)
- [THREESCALE-3575](https://issues.jboss.org/browse/THREESCALE-3575)
- [THREESCALE-3539](https://issues.jboss.org/browse/THREESCALE-3539)
**TODOs**

Proxy config workflow

---

app/views/api/services/show.html.slim
app/views/buyers/applications/index.html.slim

It checks if the current user as no accessible services, if so it renders the message instead of the list.
Currently the message is always shown 🐛.
[THREESCALE-3595: Message shown incorrectly in applications listing page](https://issues.jboss.org/browse/THREESCALE-3595)
**Visual verification**:

Show "service access" message only when there are no accessible services

---

test/unit/db/seeds_test.rb
test/unit/signup/account_manager_test.rb

Improves tests of https://github.com/3scale/porta/pull/1292 according to the reviews.

Improve the tests of creating a backend api for each new tenant

---

lib/system/deploy.rb
test/fixtures/deploy_info
test/unit/deploy/basic_info_test.rb

Closes [THREESCALE-3621](https://issues.jboss.org/browse/THREESCALE-3621)
The problem is that we are memoizing at Module level, so when it runs tests, it keeps the memoized attributes of the previous tests, and this test only passes when it is executed the 1st one. It is ok to memoize for the real code because the `.deploy_info` won't change in execution time, but for the tests it is a problem.
A way to reproduce it locally would be, for example:
```ruby
test 'custom release' do
System::Deploy.load_info!
System::Deploy.info.major_version # So it loads all the memoized variables
System::Deploy.info.stubs(:release).returns('4.5.1-CR1')
assert_equal '4', System::Deploy.info.major_version
assert_equal '5', System::Deploy.info.minor_version
end
```
And an alternative way to make it work would …

Fix Random CircleCI failure: in 'test_custom_release' - Expected '4', got '2'

---

app/javascript/src/LoginPage/LoginPageWrapper.jsx
app/javascript/src/LoginPage/loginForms/Login3scaleForm.jsx
app/views/provider/sessions/new.html.slim
spec/javascripts/LoginPage/Login3scaleForm.spec.jsx
spec/javascripts/LoginPage/LoginPageWrapper.spec.jsx

When username is present in URL params it must be used to pre-fill username input

Passing username from params to login form

---

app/controllers/admin/api/services/backend_api_configs_controller.rb
app/representers/backend_api_config_representer.rb
config/routes.rb
doc/active_docs/Account Management API.json
test/integration/admin/api/services/backend_api_configs_controller_test.rb

As decided with QE, we add a show endpoint and return the service id and backend api id of all Backend API Usage endpoints and in Backend API read for its usage.
- Request: `curl -v  -X GET "http://provider-admin.example.com.lvh.me:3000/admin/api/services/2/backend_apis/2.json?access_token=c32fc99008021a29babf962bb04bb30807f8f3310add73ac6f51377477f2486d"`
- Response:
```json
{
"path": "",
"service_id": 2,
"id": 2,
"links": [
{
"rel": "service",
"href": "http://provider-admin.example.com/admin/api/services/2"
},
{
"rel": "backend_api",
"href": "http://provider-admin.example.com/admin/api/backend_apis/2"
}
]
}
```

[API] Backend Usage 'show/read' + Representer returns service id & backend api id

---

app/javascript/src/Navigation/components/ActiveMenuTitle.jsx
app/javascript/src/Navigation/components/ContextSelector.jsx
app/views/provider/admin/dashboards/_section_products_and_backends.html.slim
app/views/provider/admin/dashboards/_service.html.slim
spec/javascripts/Navigation/ContextSelector.spec.jsx

Update icons in the Dashboard and Context Selector:
- Products: cube
- Backends: cubes
- Services (non-APIAP): puzzle-piece

Update APIAP icons in the Dashboard

---

app/workers/index_proxy_rule_worker.rb
test/workers/index_proxy_rule_worker_test.rb

[THREESCALE-3639](https://issues.jboss.org/browse/THREESCALE-3639)
IndexProxyRuleWorker raises ActiveRecord::RecordNotFound: Couldn't find
ProxyRule with id X when ProxyRule id "X" no longer exists.
This commit changes the worker to rescue this error and logs instead
of making it raising the error.

Avoid IndexProxyRuleWorker to raise Record not found

---

app/controllers/api/integrations_controller.rb
test/functional/api/integrations_controller_test.rb
test/integration/api/integrations_controller_test.rb

[THREESCALE-3625](https://issues.jboss.org/browse/THREESCALE-3625)
APIAP-users should not have access to `/apiconfig/services/:service_id/integration/edit` and before this PR they do by typing the URL on the browser. This PR blocks access to the `edit` action of this controller for APIAP users.

Do not allow access to edit or update IntegrationsController for apiap

---

app/assets/stylesheets/provider/_tables.scss

This just isn't acceptable. (saw during demo of Andreu to UXD team)

stop breaking words at random places in table content

---

app/lib/cms/settings.rb
app/models/account.rb
app/models/account/provider_methods.rb
app/models/account/states.rb
app/models/service.rb
app/representers/account_representer.rb
lib/developer_portal/app/views/shared/_footer.html.erb
test/unit/pdf/dispatch_test.rb
test/unit/service_test.rb
test/workers/delete_account_hierarchy_worker_test.rb
test/workers/delete_object_hierarchy_worker_test.rb

Without this fix, this is what the DeleteObjectHierarchyWorker (and its children) receive in the test I wrote:
With this fix:

Fix infinite lazy initialization when the object will be destroyed

---

app/helpers/vertical_nav_helper.rb
app/javascript/src/Navigation/components/PF4NavProxy.jsx
app/javascript/src/Navigation/components/VerticalNav.jsx
app/views/shared/provider/navigation/_vertical_nav_item.html.slim

When config is outdated, Integration menu shows an exclamation mark.
If collapsed, the icon must shown at top level, if expanded the icon must shown in submenu.
When JS is off, the icon is placed in the submenu (no collapse/expand is available)
**Closes:** https://issues.jboss.org/browse/THREESCALE-3660
JS on:
JS off:

Improve out-of-date config ux

---

app/assets/javascripts/provider/cms/sidebar.js.coffee
app/assets/stylesheets/provider/admin/cms/_sidebar.scss
app/views/layouts/_cms.html.erb

Catches when json is `null` and shows an error message.
Also minor lint fixes.
https://app.bugsnag.com/3scale-networks-sl/system/errors/5d9ba1d604b3fe0019229e5d?event_id=5d9ba1d60050a3b0d87f0000&i=sk&m=nw
1. Override AJAX call so it returns `null`
2. There should be no error in the console
3. An error message should be shown in the sidebar

Fixes TypeError: json is null in CMS

---

app/events/oidc/proxy_changed_event.rb
test/events/oidc/proxy_changed_event_test.rb

Fixes NoMethodError: undefined method `backend_version' for nil:NilClass when proxy validity is checked while service has been deleted already.
Closes [THREESCALE-2917](https://issues.jboss.org/browse/THREESCALE-2917)

Fixes undefined method backend_version on OIDC::ProxyChangedEvent

---

db/migrate/20191007101321_add_index_on_proxy_configs_envs.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Defines a database index on `proxy_configs(proxy_id, environment, version)`, so the SQL query corresponding to the following scope can perform better: https://github.com/3scale/porta/blob/ab53f034d27d61db26710706256a4dd30b3bd6fd/app/models/proxy_config.rb#L40-L47 
Closes [THREESCALE-3054](https://issues.jboss.org/browse/THREESCALE-3054)

Index on proxy_configs(proxy_id, environment, version)

---

app/lib/backend_api_logic/routing_policy.rb
app/lib/backend_api_logic/service_extension.rb
app/models/backend_api_config.rb
app/models/config_path.rb
app/services/service_creator.rb
app/validators/path_validator.rb
lib/tasks/data_migration/fix_backend_config_path.rb
lib/tasks/services.rake
test/factories/backend_api.rb
test/fixtures/backend_api_configs.yml
test/integration/admin/api/services/backend_api_configs_controller_test.rb
test/integration/api/backend_api_configs_controller_test.rb
test/integration/provider/admin/backend_apis_controller_test.rb
test/models/backend_api_config_test.rb
test/unit/backend_api_logic/routing_policy_test.rb
test/unit/config_path_test.rb
test/unit/proxy_rule_test.rb
test/unit/tasks/data_migration/fix_backend_config_path_test.rb
test/unit/tasks/services_test.rb

MySQL and Postgres saves `''` as empty string, but Oracle saves it as null.
Now for the first service of each tenant, we link it to a new backend api, with empty string path in the backend api config. The problem is that we are checking the uniqueness of service_id and path for backend_api_config but for Oracle, it searches by empty string although it is saved as null, so it does not find it by Rails and it tries to save it but raises an error.
We also have this problem if we try to use `where(path: '')` or a `find_by`, that it tries to search by `''` but it is saved as null so it does not find it although it is there. 
This commit changes this behave to make the application to save `'/'` instead of the empty string. 
**Which issue(s) this PR …

Avoid Empty paths for BackendApiConfig

---

app/javascript/src/Policies/components/App.jsx
app/javascript/src/Policies/index.jsx
app/javascript/src/Policies/store/configureStore.jsx
app/javascript/src/Policies/store/index.jsx
app/javascript/src/Types/libs/libdefs.js
package-lock.json
package.json

`react-hot-loader` is supposed to be used during development to "hot-load" react, that is to refresh the UI without reloading the page.
Since webpacker is configured to refresh the page after every change, it doesn't make sense and it is useless to have this module anymore.
* Policies widget should work as usual
**Note**:
This is part 1 of the refactorization of Policies:
[THREESCALE-2221: Policies: Normalise the use of policies schema and its types](https://issues.jboss.org/browse/THREESCALE-2221)
A follow-up PR will be created once this one is merged.

Remove react-hot-loader module from Policies

---

app/assets/stylesheets/provider/_patternfly_tabs_fake.scss

Aligning "APIs" title of tabs section, to match with "AUDIENCE" spacing (moving it down)

Aligning APIs tabs title in Dashboard

---

app/javascript/src/Form/FormFieldset.jsx
app/javascript/src/Form/FormLegend.jsx
jest.config.js
package-lock.json
package.json
spec/javascripts/Form/FormFieldset.spec.jsx
spec/javascripts/Form/FormLegend.spec.jsx
spec/javascripts/Form/__snapshots__/FormFieldset.spec.jsx.snap
spec/javascripts/Form/__snapshots__/FormLegend.spec.jsx.snap

the patternfly-react lib hasn't implemented still the components for fieldset and legend, so these ones are the ones we will be using until they release their own.
Needed for https://github.com/3scale/porta/pull/1315
These components will be removed when patternfly team release the official ones.

PatternFly React: Our own FormFieldset and FormLegend components

---

app/helpers/api/integrations_helper.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim

This PR fixes a tiny regression bug in the UI after https://github.com/3scale/porta/pull/1308 was merged.
**Before**
**After**

Fix show of backend usage routing paths in the integration page

---

app/views/api/metrics/_link_to_mapping_rules.slim
app/views/api/metrics/index.html.slim
app/views/api/services/show.html.slim
app/views/provider/admin/dashboards/widgets/_service_top_traffic.html.slim
features/provider/onboarding/wizard.feature

In API overview page, links to Integration page `/apiconfig/services/<id>/integration/edit` should not shown when APIAP is on.
https://issues.jboss.org/browse/THREESCALE-3705
**APIAP ON:**
**APIAP OFF:**

Fix broken integration page links when apiap is on

---

app/assets/stylesheets/provider/_forms.scss
app/javascript/src/NewService/components/NewServiceForm.jsx

After merging https://github.com/3scale/porta/pull/1182, error message for service discovery is missaligned
**Before:**
**After (no error):**
**After (error):**

Fix alignment in service discovery error message

---

app/lib/backend_api_logic/routing_policy.rb
test/unit/backend_api_logic/routing_policy_test.rb
test/unit/proxy_test.rb

`owner_id` is the id of the backend api of the backend api config behind the policy rule.
This will allow the gateway to be match only proxy rules that belong to the same backend as the request will end up been proxied to.
Proxy rules already include enough information for the match. Whenever a proxy rule belongs to a Backend API (as opposed to belonging to the Product), the gateway will find:
```json
"proxy_rules": [
{ ...
"owner_id" : "<id-of-the-backend>",
"owner_type" : "BackendApi"
}
]
```
With this PR, the routing policy injected for the backend apis will also include:
```json
"rules": [
{ ...
"owner_id" : "<id-of-the-backend>"
}
]
```
----
Related to [THREESCALE-3623](https://issues.jboss.org/browse/THREESCALE-3623)
Related to https://github.com/3scale/APIcast/pull/1125

Inject `owner_id` into the routing policy rules

---

app/controllers/admin/api/backend_apis_controller.rb
doc/active_docs/Account Management API.json

When I was testing https://github.com/3scale/porta/pull/1337, I needed to create some Backend APIs first, so I realized that we were not enforcing the `private_endpoint` in `create` for the docs although it is mandatory, and what is worse, we are enforcing to update params that should not be mandatory to be updated.
I do not know if this happens with other ActiveDocs of APIAP.

Fix ActiveDocs of Backend API Create/Update Endpoints

---

app/lib/logic/provider_signup.rb
test/unit/account_test.rb

Closes [THREESCALE-3687](https://issues.jboss.org/browse/THREESCALE-3687)
:warning: blocks https://github.com/3scale/porta/pull/1304

Create a new tenant through 'master-domain/p/signup' does not create a backend api

---

config/abilities/master_admin.rb
test/unit/abilities/master_admin_test.rb
test/unit/abilities/provider_admin_test.rb

Adds permissions for master tenant to see Backend APIs.
[THREESCALE-3725: In master tenant, master backend service overview page shows access denied](https://issues.jboss.org/browse/THREESCALE-3725)
1. Open the master tenant
2. Go to "Master Service Backend API" (from the context selector)
Some permissions might be still missing.

Give Master Admin permission to see Backend API

---

lib/developer_portal/app/views/developer_portal/_users_menu.html.liquid

Fixes [THREESCALE-1142](https://issues.jboss.org/browse/THREESCALE-1142)
404 Not Found error is returned for member users when they try to navigate to some of the presented menu items. These menu items shouldn't be rendered if the user is not an admin user and therefore restricted access is enforced whilst hiding those menus.

adds liquid check for admin role

---

app/views/api/metrics/edit.html.erb
app/views/provider/admin/backend_apis/metrics/edit.html.erb

When deleting a method, a popup window notify that you are deleting a metric but you are currently deleting a method.
https://issues.jboss.org/browse/THREESCALE-3738
**Product (Method):**
**Product (Metric):**
**Backend (Method):**
**Backend (Metric):**

Fix wrong popup message when deleting method or metric

---

app/helpers/vertical_nav_helper.rb

Usage rules link should be hidden for onprem master.
https://issues.jboss.org/browse/THREESCALE-3727

[UsageRules] hide link for onprem master

---

app/controllers/admin/api/services_controller.rb
doc/active_docs/Account Management API.json

- Fixes in "Service Update" from `self-managed` to `self_managed`
- Adds `service_mesh_istio` to both "Service Create" and "Service Update"
Closes [THREESCALE-3704](https://issues.jboss.org/browse/THREESCALE-3704)

[api-docs] fix description of service deployment_option parameter

---

app/lib/proxy_config_affecting_changes.rb
app/models/backend_api.rb
test/models/backend_api_test.rb

This is an alternative to https://github.com/3scale/porta/pull/1352. Instead of always enabling the "Promote to staging" button, it makes `BackendApi` to issue a `ProxyConfigs::AffectingObjectChangedEvent` whenever `private_endpoint` is updated. The former is a broader "fix" that prevents from any other (yet unkown) flaws of the proxy affecting changes mechanism. This is a more specific approach addressing the issue reported in https://issues.jboss.org/browse/THREESCALE-3760.

Issue proxy affecting change on backend api private endpoint update

---

app/helpers/api/integrations_helper.rb
app/javascript/src/Settings/authentication-widget.jsx
app/models/proxy.rb
app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
app/views/api/integrations/apicast/shared/_proxy_endpoints.html.slim

With `ENABLE_APICAST_CUSTOM_URL=1`
With `ENABLE_APICAST_CUSTOM_URL=0`
Default Hosted APIcast url behaviour:
Fixes a bug with proxy staging and production URLs and integration method selected.
Fixes https://issues.jboss.org/browse/THREESCALE-3753
** Notes **
Missing cuke for feature. https://issues.jboss.org/browse/THREESCALE-3762

Settings: Fix staging and production URL grayed out

---

app/models/account/payment_details.rb
app/workers/delete_account_hierarchy_worker.rb
app/workers/delete_object_hierarchy_worker.rb
app/workers/delete_payment_setting_hierarchy_worker.rb
app/workers/delete_service_hierarchy_worker.rb
test/integration/service_not_deleted_test.rb
test/workers/delete_account_hierarchy_worker_test.rb
test/workers/delete_object_hierarchy_worker_test.rb
test/workers/delete_payment_setting_hierarchy_worker_test.rb
test/workers/delete_service_hierarcy_worker_test.rb

Closes [THREESCALE-3637](https://issues.jboss.org/browse/THREESCALE-3637)
I tested also in preview to be more realistic and the way to test it there is:
1. Get a some tenants scheduled for deletion. Some of them big ones. For example by doing: `tenants = Account.tenants.scheduled_for_deletion.first(10)`
2. Do the deletion in Background: `tenants.each { |tenant| DeleteAccountHierarchyWorker.perform_later(tenant) }`
3. Keep track of what's going on in the UI by the URL `/sidekiq/queues` , and check which ones are destroyed by doing in the terminal: `tenants.map { |tenant| Account.exists?(tenant.id) }`. That until all of them are completely destroyed.
4. Download the Sidekiq logs and search there for the order of how everything has been destroyed. For example, this is the format of the data …

When deleting in parallel, try once to unstore credit card before destroying the buyer

---

app/controllers/provider/admin/onboarding/wizard/request_controller.rb
app/forms/onboarding/request_form.rb

Follows up on #1304 , the last commit did not get pushed.. so here it is.
It adds the "backend api path" to the test request.

Add fix to Wizard

---

app/assets/stylesheets/provider/_forms.scss

Some nested forms in configuration page are showing box-shadow.
**Before:**
**After:**
**NO APIAP**
**Integration page:**
**Configuration page:**

Removing box-shadow in nested forms in integration page

---

app/assets/stylesheets/provider/_patternfly_tabs_fake.scss

APIs title in dashboard is a bit vertically misaligned.
**Before:**
After:

Align vertically APIs title in Dashboard

---

app/lib/proxy_config_affecting_changes.rb

Closes [THREESCALE-3737](https://issues.jboss.org/browse/THREESCALE-3737)

Prevent ProxyConfigs::AffectingObjectChangedEvent when proxy is nil

---

package-lock.json
package.json

Updating jest to `^24.9.0` to fix a vulnerability issue with a dependency (handlebars)
`npm run jest`
All JS tests must run and pass as ususal

Update jest to 24.9.0 to fix a security issue of handlebars dependency

---

app/helpers/api/integrations_helper.rb
test/unit/helpers/api/integrations_helper_test.rb

[THREESCALE-3783](https://issues.jboss.org/browse/THREESCALE-3783)
We have a problem in integrations page when the user access it with a
proxy that has a blank endpoint. It is raising an error when trying to
construct the URI for it.
This commit changes it to avoid constructing the command for blank
endpoints.

Ignore empty endpoint when generating curl command

---

app/controllers/admin/api/application_plan_metric_limits_controller.rb
app/controllers/admin/api/application_plan_metric_pricing_rules_controller.rb
test/functional/admin/api/application_plan_metric_pricing_rules_controller_test.rb
test/integration/user-management-api/application_plan_metric_limits_test.rb

[THREESCALE-3746](https://issues.jboss.org/browse/THREESCALE-3746)
Currently when the user tries to create/update/delete limits or pricing
rules for a Backend API metric in a plan it fails with 404.
This commit fixes it by making the controller consider the backend api
metrics using the `all_metrics` method from the plan.

Fix Pricing Rules and Limits endpoints to accept metrics from BackendApi

---

app/views/api/policies/edit.html.slim

In Policies page (`apiconfig/services/<id>/policies/edit`), when fetch to policies endpoint fails for any reason, an error message is shown: "Failed to fetch APIcast policies from ...", but the submit button is enabled and the form can be submitted. This PR disables submit button when fetch APIcast policies fails.
Try with APIAP on. When APIAP off, the button is not displayed at all in the integration page.
https://issues.jboss.org/browse/THREESCALE-3793
**Before:**
**After:**

Disabling submit button when policies endpoint is wrong

---

app/views/layouts/provider.html.slim
app/views/layouts/provider/suspended.html.slim
app/views/layouts/wizard.html.slim

All pages in the app are doing a request to `https://support.3scale.net/api_docs/track.json?callback=$.noop`:
It looks like an outdated/unused tracking script.
The commit is old (it comes from System in 2015)
There are some tickets asking to remove it:
https://issues.jboss.org/browse/THREESCALE-661
https://issues.jboss.org/browse/THREESCALE-870
The branch is deployed in preview, please check that everything works normally
https://multitenant-admin.preview01.3scale.net/p/admin/dashboard

Removing https://support.3scale.net/api_docs/track.json request

---

app/javascript/src/Policies/components/PoliciesForm.jsx
app/javascript/src/Policies/components/PoliciesWidget.jsx
app/javascript/src/Policies/components/PolicyConfig.jsx
app/javascript/src/Policies/reducers/PolicyConfig.jsx
spec/javascripts/Policies/components/PolicyConfig.spec.jsx

When having 2 policies of the same type, clicking between one and the other wasn't updating the UI.
This happens because React is not detecting a change in `PolicyConfig` props and therefore the view isn't updated. The fix is to render/destroy the detailed view when it's supposed to be displayed/hidden by css.
[THREESCALE-1924: When adding a 2nd URL rewriting policy the UI doesn't work as expected](https://issues.jboss.org/browse/THREESCALE-1924)
1. Go to Integration > Policies
2. Add 2 policies of the same kind, i.e. _Upstream_
3. Open the first one, edit its config, click on _Update Policy_
4. Open the second one, its config should be empty.
Alternative:
Having 2 policies of the same kind …

Fix Policies when having twice of the same type

---

app/views/provider/_analytics.html.erb

Currently analytics scripts are loaded even when analytics are not enabled, simply `load()` method is not called but the script is loaded.
Scripts must be loaded only when analytics are enabled.

Include analytics script only when analytics are enabled

---

app/assets/javascripts/application.js
app/assets/stylesheets/provider/_colorbox.scss

Some modal windows are too wide:
Setting some max width and height they looks better:
https://issues.jboss.org/browse/THREESCALE-3807
1. Login to SaaS master account
2. Go to Audience->Account->Listing and select an account
3. Under account details, select a plan and click on "Change plan" 
This branch is deployed in [preview](https://multitenant-admin.preview01.3scale.net/buyers/accounts/2445582823158)

Adjust width and height of colorbox modals

---

app/assets/stylesheets/provider/_settings_box.scss
app/helpers/api/integrations_helper.rb
app/lib/backend_api_logic/routing_policy.rb
app/models/backend_api_config.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim

It reorganizes how APIcast Configuration info is displayed for APIAP accounts, making it more clear that Backends are composing parts of Products, they also bring their own mapping rules to the configuration.
It also now shows the backends in the same order as they will be injected into the routing policy rules.
Related to [THREESCALE-3781](https://issues.jboss.org/browse/THREESCALE-3781) (although it doesn't really show the full list of mapping rules, but it already communicates better to the user)

Reorganization of APIcast configuration view for APIAP

---

app/views/api/integrations/apicast/shared/_deployment_options.html.slim
features/old/api/settings.feature
features/old/proxy.feature
features/step_definitions/apicast_steps.rb

closes https://issues.jboss.org/browse/THREESCALE-3266
Next steps would be to have custom policies fully operational in SaaS (@hallelujah), agree on decommissioning date (@3scale/product) and communicate it.

More agressive APIcast upgrade message plus removal of downgrading in ui

---

app/javascript/src/Policies/middleware/PolicyChain.jsx
spec/javascripts/Policies/middleware/PolicyChain.spec.jsx

When there is any bogus policy in the policy chain the components dispatched an error, instead of updating the store, so the chain is kept empty.
However, dispatching an error does nothing because this is not implemented so the errors fall silently.
The proper behavior is that both things happen:
* if there are wrong policies it should dispatch an error and exclude them from the chain
* then it should update the chain with all the resting valid policies
[THREESCALE-3229: Empty Policy Chain list after removal of custom policy from apicast](https://issues.jboss.org/browse/THREESCALE-3229)
1. Using APIcast 2.7 add a HTTP Proxy policy
2. Change to APIcast 2.6 and go to policies/edit
3. The policy …

Fix empty Policy Chain list in policies/edit

---

app/assets/stylesheets/provider/_settings_box.scss

Nested cards in APIAP integration page are showing box-shadow, but it must be there only for not-nested cards, also the vertical line should not overflow outside container.
**Before:**
**After:**

Removing box shadows from nested cards in APIAP intengration page

---

app/lib/logic/rolling_updates.rb

Revert Master Account to 2.7 functionality by putting it behind the rolling update `api_as_product`.
[THREESCALE-3786: Don't display backends in master account](https://issues.jboss.org/browse/THREESCALE-3786)
Master account should work like a non-APIAP account.

Don't display backends in master account

---

package-lock.json

* https://snyk.io/vuln/SNYK-JS-HTTPSPROXYAGENT-469131
Npm reported a vulnerability in one of our dependencies: `https-proxy-agent` 
No issue associated.
Run `npm install` after checkout and instead of warnings, the notice `found 0 vulnerabilities` should be shown

[npm] Fix https-proxy-agent vulnerability (MitM)

---

app/services/apicast_v2_deployment_service.rb
test/unit/services/apicast_v2_deployment_service_test.rb

When a product is using multiple backend, system still injects the old api_backend attribute into the proxy configuration. With this PR, `api_backend` is set to `nil` for new proxy configs when there are more than 1 backend.
[THREESCALE-3775: Nullify old api_backend attribute when APIAP routing policy is used](https://issues.jboss.org/browse/THREESCALE-3775)

Nullify api_backend when APIAP routing policy is used

---

app/decorators/proxy_rule_decorator.rb
test/decorators/proxy_rule_decorator_test.rb

This will make proxy rules whose pattern is the "catch-all" pattern `/` not to end with the slash if the pattern has been prepended by a backend api path.
**Example 1**
Backend path: `/mybackend`
Proxy rule pattern: `/`
Actual proxy rule pattern in the config: `/mybackend` (it used to be `/mybackend/` before this PR)
**Example 2**
Backend path: `/mybackend`
Proxy rule pattern: `/hello`
Actual proxy rule pattern in the config: `/mybackend/hello` (same as before)
**Example 3**
Backend path: `/`
Proxy rule pattern: `/`
Actual proxy rule pattern in the config: `/` (same as before)
**Example 4**
Backend path: `/`
Proxy rule pattern: `/hello`
Actual proxy rule pattern in the config: `/hello` (same as before)
----
Closes [THREESCALE-3833](https://issues.jboss.org/browse/THREESCALE-3833)

Prevent trailing slash in patterns of proxy rules of backend api configs with a path

---

app/assets/javascripts/help.js.erb
app/assets/stylesheets/provider/_forms.scss
app/assets/stylesheets/provider/_inline_helper.scss

Some popup bubbles are broken, sometimes showing a space between the icon (?) and the text box, and sometimes are displayed at the right (outside the browser window).
**Before:**
**After:**
**Brach deployed to preview**: https://multitenant-admin.preview01.3scale.net/p/admin/dashboard
**Note:** Bubbles needs a whole refactor, this is just a quick-fix
New task created for 2.8 release https://issues.jboss.org/browse/THREESCALE-3854

Fix broken bubbles

---

app/controllers/provider/admin/onboarding/wizard/base_controller.rb

The check was using `site_account` in case there was no provider available, which was a wrong assumption.
> Wizard should feature instructions for Product and Backend

APIAP check returns false in the Wizard

---

app/decorators/proxy_rule_decorator.rb
test/decorators/proxy_rule_decorator_test.rb

This PR reverts https://github.com/3scale/porta/pull/1394 and introduces new tests to the proxy rule decorator.
It goes in the opposite direction of https://github.com/3scale/porta/pull/1400, which should be closed in case we decide to move on with this one.
Related to [THREESCALE-3833](https://issues.jboss.org/browse/THREESCALE-3833).
Closes [THREESCALE-3872](https://issues.jboss.org/browse/THREESCALE-3872).
The Jira reported as a bug a scenario where two requests with and without a trailing slash, targeting a mapping rule of a backend whose pattern was `/` (AKA the "catch-all" mapping rule pattern), were treated differently. According to the description of the bug, one would expect those things to be trated equally. But this is not correct. Requests with and without the trailing slash …

Revert Prevent trailing slash in patterns of proxy rules of backend api configs with a path

---

app/assets/stylesheets/provider/admin/_dashboard.scss
features/provider/dashboard/tabs.feature
features/step_definitions/dashboard_steps.rb
features/step_definitions/service_steps.rb

Css rule `display: none;` was being overridden by `display: table`.
* Moved `hidden` definition to a higher priority place so that it overrides `display: table`
* Sets min-height so that the card doesn't collapse
[THREESCALE-3871: Products search bar in Dashboard not working](https://issues.jboss.org/browse/THREESCALE-3871)
1. Open the dashboard, Products tab
2. Use the search bar: products should hide and show accordingly with the search query
Todo:

Fix Products' search bar in Dashboard

---

app/javascript/src/Policies/components/PolicyChainHiddenInput.jsx
spec/javascripts/Policies/components/PolicyChainHiddenInput.spec.jsx

Simplify logic and improve performance of `PolicyChainHiddenInput`. It is currently a bit convoluted (and heavy).
Performance comparison: http://jsben.ch/4fWbF.
* Policies widget should work as usual
**Note**:
This is part 5 of the refactorization of Policies:
[THREESCALE-2221: Policies: Normalise the use of policies schema and its types](https://issues.jboss.org/browse/THREESCALE-2221)
Previous step #1399.

Simplify and improve performance of HiddenInput

---

app/javascript/src/Policies/components/PoliciesForm.jsx
app/javascript/src/Policies/components/PoliciesWidget.jsx
app/javascript/src/Policies/components/PolicyChain.jsx
app/javascript/src/Policies/components/PolicyRegistry.jsx
app/javascript/src/Policies/styles/policies.scss
features/step_definitions/proxy_steps.rb
spec/javascripts/Policies/components/PolicyConfig.spec.jsx

In React, the recommended way to hide components is to not render them at all, this is achieved by means of conditional rendering.
* Remove repeated class definitions of `is-hidden` class in policies.scss
* Remove parameters `visible`
* Use local parameters to conditional render components 
* Policies widget should work as usual
**Note**:
This is part 6 of the refactorization of Policies:
[THREESCALE-2221: Policies: Normalise the use of policies schema and its types](https://issues.jboss.org/browse/THREESCALE-2221)
Previous step #1403.

Remove 'is-hidden' class used in Policies in favor of conditional rendering

---

.circleci/config.yml

Until 1 before I opened this PR, right before merging https://github.com/3scale/porta/pull/1290, we had the following builds related to DBs running every night:
1. mysql-container (for Ruby 2.3)
2. postgres-container (for Ruby 2.3)
3. oracle-db-container (for Ruby 2.3)
4. mysql-ruby24 (for Ruby 2.4)
5. postgres-ruby24 (for Ruby 2.4)
6. oracle-ruby24 (for Ruby 2.4)
But now the 3 first ones already run with 2.4, so we should not run the 3 last ones anymore because they are exactly the same :smile:

[CircleCI] Do not run nightly 2.4 tests twice

---

test/unit/tasks/backend_api_test.rb
test/unit/tasks/backend_test.rb
test/unit/tasks/cms/cms_test.rb
test/unit/tasks/data_migration/fix_backend_config_path_test.rb
test/unit/tasks/deleted_objects_test.rb
test/unit/tasks/forum/migrate_forum_test.rb
test/unit/tasks/impersonation_admin_user_test.rb
test/unit/tasks/multitenant/tenants_test.rb
test/unit/tasks/proxy_test.rb
test/unit/tasks/services_test.rb
test/unit/tasks/sidekiq_test.rb
test/unit/tasks/swagger_test.rb
test/unit/tasks/zync_test.rb

This commit adds all tests from Tasks unit tests inside a module instead
of using inline modules.

Do not use inline module in Tasks unit test

---

app/models/user.rb

User#kill_user_session uses delete_all instead of destroy_all for the memory

---

app/workers/user_session_sweeper_worker.rb

Requested by Hery in this comment: https://github.com/3scale/porta/pull/1415#issuecomment-554879081
Sorry, I saw it after merging 🙈

UserSessionSweeperWorker uses delete instead of destroy for the UserSession

---

app/javascript/src/Policies/components/HeaderButton.jsx
app/javascript/src/Policies/components/PoliciesForm.jsx
app/javascript/src/Policies/components/PolicyChain.jsx
app/javascript/src/Policies/components/PolicyRegistry.jsx
app/javascript/src/Policies/styles/policies.scss
spec/javascripts/Policies/components/HeaderButton.spec.jsx
spec/javascripts/Policies/components/PolicyConfig.spec.jsx
spec/javascripts/Policies/components/PolicyRegistry.spec.jsx
spec/javascripts/Policies/components/__snapshots__/HeaderButton.spec.jsx.snap

Policy lists are the chain and the registry. Form also shares the same header.
* Extracts a `HeaderButton` component
* Simplifie styles, removing some classes and combining repeated things.
* At Policy Chain button should be 'add':
* At Edit Policy or Select a Policy shuold be "cancel":
**Note**:
This is part 7 of the refactorization of Policies:
[THREESCALE-2221: Policies: Normalise the use of policies schema and its types](https://issues.jboss.org/browse/THREESCALE-2221)
Previous step #1408.

Simplify policy lists header and its styles

---

app/javascript/packs/settingsPageStyles.js
app/javascript/src/patternflyStyles/settingsPage.css
app/views/layouts/provider.html.slim

The new integration settings component https://github.com/3scale/porta/pull/1315 is missing PF4 styles.
Since https://github.com/3scale/porta/pull/1019 we should import explicitly all PF4 styles required. This was a recommendation from PF4 team: https://github.com/patternfly/patternfly-react-seed/wiki/Disable-Patternfly-React-Auto-Style-Injection.
https://issues.jboss.org/browse/THREESCALE-3563
run `bundle exec rake webpack:compile && bundle exec rake assets:precompile`
Apply this patch to make it work:
```
diff --git a/app/javascript/packs/settings.js b/app/javascript/packs/settings.js
index e9bb1a69..0bfeb4b6 100644
--- a/app/javascript/packs/settings.js …
```

Include PF4 styles for settings page

---

app/javascript/src/Policies/util.jsx
spec/javascripts/Policies/util.spec.jsx

When polices change their place within the chain, the update button is enabled.
[THREESCALE-3941: Policies cannot be updated after reordering them](https://issues.jboss.org/browse/THREESCALE-3941)
1. In Product-> Integration-> Policies-> add multiple policies and update
2. Reload policies page and try to reorder policies
3. Try to click on "Update Policy Chain"

Enable Policies update button after rearranging chain

---

test/unit/tasks/segment/segment_test.rb

Fixes https://app.circleci.com/jobs/github/3scale/porta/129583
It creates the user with ID 1 at that moment, so it exists and it detects that it is not deleted, which is correct. So the CSV must contain different user ids that the ones in DB for the test.
1. 'disable transactional fixtures' to don't have other user ids in the DB from other tests
2. change the ids of the csv for higher so the user we create in the test is the 1 always

Fix Random CircleCI Failure in Test for Segment Rake Task

---

app/controllers/api/services_controller.rb
config/locales/en.yml
test/integration/api/services_controller_test.rb

This is my proposal for https://github.com/3scale/porta/pull/1398/files#r347518158
This way the result is exactly the same, but we don't have to manually add/edit/remove every validation from the model also in the locale, because many are already done by ActiveRecord and the less repetition, the less changes to mess up from us while maintaining the code 😄

Automatically fetch model error message when fails to create service

---

app/javascript/src/Policies/actions/PolicyChain.jsx
app/javascript/src/Policies/actions/PolicyConfig.jsx
app/javascript/src/Policies/actions/index.jsx
app/javascript/src/Policies/components/PoliciesWidget.jsx
app/javascript/src/Policies/components/PolicyTile.jsx
app/javascript/src/Policies/index.jsx
app/javascript/src/Policies/middleware/PolicyChain.jsx
app/javascript/src/Policies/reducers/OriginalPolicyChain.jsx
app/javascript/src/Policies/reducers/PolicyChain.jsx
app/javascript/src/Policies/reducers/PolicyConfig.jsx
app/javascript/src/Policies/reducers/PolicyRegistry.jsx
app/javascript/src/Policies/reducers/initialState.jsx
app/javascript/src/Policies/types/Actions.jsx
app/javascript/src/Policies/types/Policies.jsx
app/javascript/src/Policies/types/State.jsx
app/javascript/src/Policies/util.jsx
spec/javascripts/Policies/components/PolicyChainHiddenInput.spec.jsx
spec/javascripts/Policies/middleware/PolicyChain.spec.jsx
spec/javascripts/Policies/reducers/PolicyChain.spec.jsx
spec/javascripts/Policies/reducers/PolicyConfig.spec.jsx
spec/javascripts/Policies/reducers/PolicyRegistry.spec.jsx
spec/javascripts/Policies/reducers/UISettings.spec.jsx

Big refactor of types, removing duplications and using names as much clear as possible:
* Policies return by rails is an object of `RawRegistryPolicy`. It is parsed and added into the registry component as an array of `IPolicy`
* policies_config is passed as props as an array of `PolicyConfig`. Then they are parsed and added to the chain, copied from the registry -> `ChainPolicy`
* Some variable/prop names also changed for more consistency and clarity
* Policies widget should work as usual
**Note**:
This is part 8 of the refactorization of Policies:
[THREESCALE-2221: Policies: Normalise the use of policies schema and its …

Redefine Policies types

---

db/migrate/20190716110000_add_owner_to_metrics.rb
db/migrate/20190805135829_backfill_metric_owners.rb
db/migrate/20190805135839_add_index_to_metrics_owner_and_system_name.rb

The index uses columns recently added combined with existing system_name. This makes Oracle to activate the uniqueness constraint and fail if the owner_id and owner_type haven't yet been backfilled.
Closes [THREESCALE-3944](https://issues.jboss.org/browse/THREESCALE-3944)
Alternative to https://github.com/3scale/porta/pull/1444.

[oracle] Fix creation of unique index on metrics(owner_type, owner_id, system_name)

---

lib/system/database/oracle/trigger.rb

Generating an error with
SELECT * FROM user_errors where type = 'TRIGGER' and NAME = 'BACKEND_APIS_TENANT_ID'
PLS-00103: Encountered the symbol "IF" when expecting one of the following:
* & = - + ; < / > at in is mod remainder not rem
<an exponent (**)> <> or != or ~= >= <= <> and or like like2
like4 likec between || multiset member submultiset

[oracle] Missing a semi-colon in trigger declaration

---

db/migrate/20190716110000_add_owner_to_metrics.rb
db/migrate/20190805135829_backfill_metric_owners.rb
db/migrate/20190805135839_add_index_to_metrics_owner_and_system_name.rb

Adds these 2 PRs from 2.7 CR2 to master:
- [oracle] Missing a semi-colon in trigger declaration (https://github.com/3scale/porta/pull/1447)
- [oracle] Fix creation of unique index on metrics(owner_type, owner_id, system_name) (https://github.com/3scale/porta/pull/1445)

2.7 CR2 Oracle Fixes to master: Migration index unique + Trigger with semicolon.

---

test/unit/abilities/provider_member_test.rb

Fixes https://app.circleci.com/jobs/github/3scale/porta/131396
```
Error:
Abilities::ProviderMemberTest#test_events_according_the_service:
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '1' for key 'PRIMARY': INSERT INTO `services` (`state`, `mandatory_app_key`, `name`, `account_id`, `id`, `system_name`, `created_at`, `updated_at`) VALUES ('incomplete', 0, 'service88', 68, 1, 'service88', '2019-11-22 00:05:47', '2019-11-22 00:05:47')
test/unit/abilities/provider_member_test.rb:32:in `test_events_according_the_service'
Error:
Abilities::ProviderMemberTest#test_services:
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry '1' for key 'PRIMARY': INSERT INTO `services` (`state`, `mandatory_app_key`, `name`, `account_id`, `id`, `system_name`, `created_at`, …
```

Fix 'Abilities::ProviderMemberTest' - ActiveRecord::RecordNotUnique: Duplicate entry '{id_value}'

---

test/unit/models_test.rb

Fixes this random bug:
In [this case](https://app.circleci.com/jobs/github/3scale/porta/131905), it is because it was trying to test this class:
https://github.com/3scale/porta/blob/00f267bb5cf8dbdbe05e36a2071e8345c31e5516/test/unit/provider_constraints_test.rb#L5-L11
But the purpose of this test is not for classes inside the tests, which is only problematic, so I am skipping them all here :smile:

Skip ModelsTest for all ActiveRecord classes declared inside the Tests

---

app/assets/stylesheets/provider/layouts/_main.scss

Exclamation mark icon for outdated configuration is missing spacing
**Before:**
**After:**

Adding space to exclamation icon in navbar

---

package-lock.json
package.json
spec/javascripts/Settings/components/Common/__snapshots__/SelectGroup.spec.jsx.snap
spec/javascripts/Settings/components/Common/__snapshots__/TextInputGroup.spec.jsx.snap

PF4 dependencies where updated in https://github.com/3scale/porta/pull/1436
Now, we can update core PF4 packages
Note: Updating snapshots to match latest changes introduced in https://github.com/patternfly/patternfly-react/pull/3220 and https://github.com/patternfly/patternfly-react/pull/3333
Branch [deployed in preview](https://multitenant-admin.preview01.3scale.net/p/admin/dashboard)

Updating PF4 core dependencies

---

app/lib/proxy_config_affecting_changes.rb
test/models/backend_api_config_test.rb

Closes [THREESCALE-3989](https://issues.jboss.org/browse/THREESCALE-3989)

Fix BackendApiConfig issuing ProxyConfigs::AffectingObjectChangedEvent on proxy update

---

app/javascript/src/Policies/components/PolicyChain.jsx
app/javascript/src/Policies/styles/policies.scss

When dragging a policy from the policy chain, it disappears.
This PR adds a css class to the item being dragged (via `helperClass` prop) which sets a high enough `z-index` and a background.
Before:
After:
No JIRA
1. Go to a Product > Integration > Policies (apiap) or Service > Integration settings (non apiap)
2. Sort policy chain: the policy being moved should be visible

Fix invisible policy when re-ordering Policy Chain

---

app/decorators/proxy_rule_decorator.rb
app/lib/backend/model_extensions/metric.rb
app/lib/backend_api_logic/metric_extension.rb
app/lib/backend_client/application/utilization.rb
app/representers/method_representer.rb
app/representers/metric_representer.rb
app/workers/backend_metric_worker.rb
test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
test/integration/admin/api/backend_apis/metrics_controller_test.rb
test/unit/backend/model_extensions/metric_test.rb
test/unit/backend_api_logic/metric_extension_test.rb
test/unit/backend_client/application/utilization_test.rb
test/workers/backend_metric_worker_test.rb

This PR fixes a bug in the `BackendClient::Application::Utilization` module that, despite receiving usage data from apisonator properly separated by each metric's true/extended system_name, was ignoring the extension and grouping the records by `system_name` without the suffix. This was causing a 500 error while at `/apiconfig/services/<service_id>/applications/<application_id>`.
Closes [THREESCALE-4013](https://issues.jboss.org/browse/THREESCALE-4013)

BackendClient::Application::Utilization with the metric's extended system_name

---

app/lib/backend_api_logic/routing_policy.rb
test/unit/backend_api_logic/routing_policy_test.rb

This is one of the options we have to fix [THREESCALE-4016](https://issues.jboss.org/browse/THREESCALE-4016) It corresponds to the first solution proposed in the dev notes.

Merge all routing policies into one

---

app/lib/stats/views/csv/top_applications.rb
app/lib/stats/views/csv/usage.rb
app/workers/data_exports_worker.rb
lib/tasks/provider_stats.rb
lib/tasks/segment/segment.rake

Get rid of the following obnoxious warnings:
```
jgallaso (feature/THREESCALE-1135_captcha_password_reset *) ~/Projects/3scale/porta $ rake routes
/usr/local/Cellar/ruby@2.4/2.4.6_1/lib/ruby/2.4.0/csv.rb:211: warning: already initialized constant CSV::VERSION
/usr/local/Cellar/ruby@2.4/2.4.6_1/lib/ruby/2.4.0/csv.rb:211: warning: previous definition of VERSION was here
/usr/local/Cellar/ruby@2.4/2.4.6_1/lib/ruby/2.4.0/csv.rb:929: warning: already initialized constant CSV::FieldInfo
/usr/local/Cellar/ruby@2.4/2.4.6_1/lib/ruby/2.4.0/csv.rb:929: warning: previous definition of FieldInfo was here
/usr/local/Cellar/ruby@2.4/2.4.6_1/lib/ruby/2.4.0/csv.rb:932: warning: already initialized constant CSV::DateMatcher
/usr/local/Cellar/ruby@2.4/2.4.6_1/lib/ruby/2.4.0/csv.rb:932: warning: previous …
```

[Refactor] Use require for CSV instead of require_dependency

---

Gemfile.base
Gemfile.lock
features/support/hooks.rb
lib/color.rb

Extracted from #1396
In order to remove the lib folder from autoload, this commit removes the
lib/color file, since it was not being used in any place. Only one test
was using some of its constant.

Remove lib/color.rb

---

app/models/service.rb
app/views/api/services/settings_apiap.html.slim
app/views/layouts/api/_service.html.slim
app/views/shared/service/_deprecated_plugin_warning.html.slim
test/unit/helpers/services_helper_test.rb
test/unit/service_test.rb

[THREESCALE-2395](https://issues.jboss.org/browse/THREESCALE-2395)
Our plugin deployment option is deprecated. To avoid needing some data migration in database, this commit sets the deployment option as hosted if the current option is set to plugins and also displays a message to the user to update their configuration.

Display a deprecated message when Service uses plugin deployment

---

app/lib/active_merchant_hacks.rb

Extracted from #1396
In order to remove the lib folder from autoload, this commit moves the
lib/active_merchant_hacks into app/lib

[lib] Move lib/active_merchant_hacks to app/lib

---

app/controllers/api/services_controller.rb
test/integration/api/services_controller_test.rb

Closes [THREESCALE-4162](https://issues.redhat.com/browse/THREESCALE-4162)
The problem was that the format of the strong params wasn't matching how the values are sent.

[Bugfix] Changing the 'OIDC Authorization Flow' does not work when using 'API as a Product'

---

app/lib/fields/fields.rb
app/models/backend_api.rb
lib/tasks/backend_api.rake
test/models/backend_api_test.rb

This comment is not true anymore. Now it is tested in the place where one would expect:
1. `test/unit/fields/fields_test.rb`
2. `test/unit/account/fields_test.rb`
3. `test/unit/extra_fields_test.rb`
Each testing individually what it should.
It is unrelated to the rest of the PR but it is just removing an outdated pretty irrelevant comment and  removing it was committed originally just to check if circleci was working properly back then :smile: 
__________________________________________________________
Makes `lib/tasks/backend_api.rake` more efficient by fetching the account in the same query and selecting only the necessary fields.
Closes [THREESCALE-3966](https://issues.jboss.org/browse/THREESCALE-3966)
Closes [THREESCALE-3554
](https://issues.jboss.org/browse/THREESCALE-3554)
Fixes …

Fix & Refactor BackendAPI scopes: orphans & not_used_by

---

gemfiles/prod/Gemfile.lock

This commit bumps the rack and colorize gem versions in the Gemfile.lock
from the production version.

Bump versions in Gemfile.lock production

---

Makefile
SETUP_ORACLE.md

This is needed in order to work in Ubuntu (and some other Linux distributions).
It works for Mac because although it does not have 'AppArmor', it just ignores the option and works anyway.
In Fedora, @srijitamukherjee has tested it and we have the same problem. So I have created [THREESCALE-4171](https://issues.redhat.com/browse/THREESCALE-4171) for that.

[Oracle][Docker] Setup Docker Instructions + Use AppArmor default docker profile to run Oracle

---

test/test_helper.rb

A bad copy paste ended up with code coverage messed up

Fix Code Coverage test unit path

---

test/integration/api/services_controller_test.rb

Fixes Oracle tests because it was being saved as `''` which in Oracle is 'nil' so [it failed](https://app.circleci.com/jobs/github/3scale/porta/138852) in `assert_equal '', nil`. Besides, it is better to test and actual value to ensure that it works :smile:

[Fix Oracle Tests] Test oidc_issuer_endpoint with an actual value

---

app/workers/backend_metric_worker.rb
config/application.rb
config/environment.rb
config/environments/development.rb
config/environments/test.rb
lib/system/database.rb
lib/system/database/definitions/mysql.rb
lib/system/database/definitions/oracle.rb
lib/system/database/definitions/postgres.rb
lib/system/database/mysql/procedure.rb
lib/system/database/mysql/trigger.rb
lib/system/database/oracle/procedure.rb
lib/system/database/oracle/trigger.rb
lib/system/database/postgres/procedure.rb
lib/system/database/postgres/trigger.rb
test/integration/developer_portal/forums/admin/categories_controller_test.rb
test/unit/apicast/abstract_generator_test.rb

This commit removes the lib directory from the autoload path. It also
forces the inclusion of the database files that are still present in the
folder.

Remove lib from autoload

---

app/models/proxy.rb
app/services/service_creator.rb
app/validators/uri_validator.rb
config/locales/en.yml
test/integration/api/services_controller_test.rb
test/unit/models_test.rb
test/unit/proxy_test.rb
test/unit/validators/uri_validator_test.rb

According to RFC 1035, domain host names must be 255 characters-long or less, and its labels must be 63 characters-long or less. Currently we do not validate domain names against this constraint which is causing OpenShift to reject non-compliant routes created by Zync.
One not-so-obvious case where this issue can cause us trouble is when creating a new product. The `system_name` of the product, chosen by the user, will end up being used to generate the proxy endpoints (depending on the sandbox proxy config). A sufficiently long `system_name` may produce a domain name containing a lable that is longer than 63 characters. The route will then fail to be created or updated by Zync, requiring a manual intervention by the user to fix it. The creation of the product succeeds in this case though; …

Validation of labels of domain names according to RFC 1035

---

lib/developer_portal/lib/liquid/filters/rails_helpers.rb

Uses argument `disable_with` for the button to be disabled after submission.
Also adds proper styling, similar to other "Regenerate" buttons.
[THREESCALE-942: Application show view is overlaid by the Error Layout when a 404 Not Found is returned](https://issues.redhat.com/browse/THREESCALE-942)
- Sign in to the dev portal
- Go to an application, it must make use of a client secret
- Click multiple times on "Regenerate"
- (More detailed steps to reproduce in the [JIRA](https://issues.redhat.com/browse/THREESCALE-942))

Disable generate client secret button in Dev portal

---

app/workers/backend_metric_worker.rb
test/workers/backend_metric_worker_test.rb

`BackendMetricWorker` was [recently refactored](https://github.com/3scale/porta/pull/1498) as an `ApplicationJob`, removing the 5-minute wait between job retries. See https://github.com/3scale/porta/pull/1498/files#r362426938.
This PR reinstantes the wait between job retries.

Sparse BackendMetricWorker retries by 5 minutes from each other

---

app/javascript/packs/LoginPage.js
app/javascript/packs/PF4Styles/base.js
app/javascript/packs/SignUpPage.js
config/webpacker.yml

Webpacker assets compilation in dev mode is very slow, it fails silently in loop but doesn't log any useful info:
```
[Webpacker] Compiling…
[Webpacker] Compilation failed:
[Webpacker] Compiling…
[Webpacker] Compilation failed:
```
This PR adds  `webpack_compile_output: true` to webpacker config file, and fix current found errors

Log webpacker compile errors

---

app/models/account.rb
app/models/application_record.rb
app/models/backend_api.rb
app/models/cinstance.rb
app/models/concerns/background_deletion.rb
app/models/feature.rb
app/models/metric.rb
app/models/plan.rb
app/models/proxy.rb
app/models/service.rb
app/models/service_plan.rb
app/models/user.rb
app/workers/delete_account_hierarchy_worker.rb
app/workers/delete_object_hierarchy_worker.rb
app/workers/delete_payment_setting_hierarchy_worker.rb
app/workers/delete_service_hierarchy_worker.rb
test/unit/concerns/background_deletion_test.rb
test/workers/delete_object_hierarchy_worker_test.rb
test/workers/delete_service_hierarcy_worker_test.rb

Association that should be deleted on the background should be defined manually, instead of taking them by the `depenend` option from the association.
https://issues.jboss.org/browse/THREESCALE-3702

[BackgroundDeletion] module

---

.circleci/config.yml
Dockerfile
INSTALL.md
app/lib/pdf/data.rb
openshift/system/Dockerfile
openshift/system/Dockerfile.on_prem
openshift/system/contrib/scl_enable

Upgrade ruby to version 2.5.
The current version that we use (2.4) EOL is March 31, 2020.
[https://issues.redhat.com/browse/THREESCALE-3900](https://issues.redhat.com/browse/THREESCALE-3900)

Upgrade to ruby2 5

---

app/models/backend_api.rb
config/locales/en.yml
test/models/backend_api_test.rb

This commit allows the BackendApi to accept websocket protocol (ws://
and wss://) in the private_endpoint attribute.
[THREESCALE-916](https://issues.redhat.com/browse/THREESCALE-916)

Support websocket protocol in BackendApi

---

.circleci/config.yml

As we have another way to build the image directly in quay.io/3scale/porta
We do not need this job anymore, neither on CI validating it every push
When the PR is merged the build is triggered in quay.io, if it fails, we get a notification

[ci] Remove docker-build job from CI

---

app/lib/pdf/report.rb
app/mailers/notification_mailer.rb
app/mailers/post_office.rb
test/mailers/notification_mailer_test.rb
test/unit/mailers/post_office_test.rb
test/unit/pdf/report_test.rb

Makes PDF reports to be named using the account ID and service ID, instead of account domain and service name.
Closes [THREESCALE-4147](https://issues.redhat.com/browse/THREESCALE-4147)
----

Fix pdf report file name

---

app/events/domains/proxy_domains_changed_event.rb
app/models/proxy.rb
test/events/domains/proxy_domains_changed_event_test.rb

A missing service while a proxy is being deleted in the background is causing a proxy domains changed event to fail to issue. We don't care about the event itself. The idea is preventing the error to be raised at this point.
Closes [THREESCALE-4248](https://issues.redhat.com/browse/THREESCALE-4248)

Fix proxy domains event on background deletion of proxy

---

app/lib/cms/s3.rb
config/application.rb
config/docker/amazon_s3.yml
config/examples/amazon_s3.yml
openshift/system/config/amazon_s3.yml

Related to [THREESCALE-4052](https://issues.redhat.com/browse/THREESCALE-4052)
----
This PR ensures Paperclip will consider the new configuration options introduced by https://github.com/3scale/porta/pull/1522 while uploading attachments to S3, passing them along to the `Aws::S3::Resource` instance.
- Sets `s3_options` with the `endpoint` value (matching `s3_protocol` and `s3_host_name`) if configured by the user
- Sets `force_path_style: true` by default
----
AWS S3
Minio.io

Fix AWS S3 options

---

.codeclimate.yml

Codeclimate should ignore developer portal assets, but some directories were missing from exclusion in codeclimate.yml
(e.g. https://github.com/3scale/porta/pull/1468 was failing because of https://codeclimate.com/github/3scale/porta/pull/1468)

Ignoring Developer portal assets in codeclimate

---

app/controllers/admin/api/services_controller.rb
test/integration/admin/api/services_controller_test.rb

[THREESCALE-1650: Admin Portal member user with the access "Developer Accounts -- Applications" can create new APIs](https://issues.redhat.com/browse/THREESCALE-1650)
- Log in as a member permission an generate a token under `/p/admin/user/access_tokens`
- Try to create a service via command line, example:
```bash
curl -v  -X POST "http://provider-admin.example.com.lvh.me:3000/admin/api/services.xml" -d 
'access_token=<token>&name=my- 
api&deployment_option=self_managed&backend_version=1&system_name=my-api'
```
**TODO**:

Prevent member users from creating Services

---

app/lib/three_scale/open_api/url_resolver.rb
app/lib/three_scale/swagger/schemas/swagger-3.0.schema.json
app/lib/three_scale/swagger/specification.rb
app/lib/three_scale/swagger/validator.rb
test/fixtures/swagger/pet-store-3.0.json
test/unit/three_scale/open_api/url_resolver_test.rb
test/unit/three_scale/swagger/specification_test.rb

Adds validation to `ApiDocs::Service.specification` based on OpenAPI 3.0.X schema.
Closes [THREESCALE-770](https://issues.redhat.com/browse/THREESCALE-770)
**TODOs**

Validation of ActiveDocs based on OAS 3.0.X

---

app/models/account.rb
app/models/service.rb
test/workers/delete_account_hierarchy_worker_test.rb
test/workers/delete_service_hierarcy_worker_test.rb

Easy fix for [this bugsnag error](https://app.bugsnag.com/3scale-networks-sl/system/errors/5e29562a4b57c80019134019?event_id=5e29ba7a0055efac186c0000&i=sk&m=fq).
Closes [THREESCALE-4318 - NameError in DeleteServiceHierarchyWorker@deletion](https://issues.redhat.com/browse/THREESCALE-4318)

[Bugfix] NameError in DeleteServiceHierarchyWorker@deletion. uninitialized constant ApiDocsService

---

app/events/proxy_configs/affecting_object_changed_event.rb
app/models/backend_api.rb
app/models/proxy.rb
app/models/proxy_rule.rb
test/unit/proxy_rule_test.rb

Deletion of multiple proxy rule objects in parallel, which may happen when an Account or a Backend is being deleted in the background, can deadlock on the update of the "position" of the proxy rules. This PR disables `acts_as_list` position update when a proxy rule is destroyed if (and only if) the proxy rule's owner or the account top of it has been deleted (scheduled for deletion).
Closes [THREESCALE-3845](https://issues.jboss.org/browse/THREESCALE-3845)

Disable update of proxy rule position when account is gone

---

test/test_helpers/backend.rb

This reverts commit 440cc4c332b12f49a0ef7c3aebd1272749341781.

Revert "ThreeScale::Core::AlertLimit.load_all mocked"

---

app/lib/fields/fields.rb

Using #extract! otherwise it is impossible to use it with models with extra fields

ActionController::Parameters#slice! does not behave like before

---

app/lib/api_authentication/by_access_token.rb
app/models/access_token.rb
app/models/user.rb
db/migrate/20200121142649_add_timestamps_to_access_token.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/integration/finance/api/invoices_controller_test.rb
test/models/access_token_test.rb
test/unit/api_authentication/by_authentication_token_test.rb

Closes [THREESCALE-421](https://issues.redhat.com/browse/THREESCALE-421)

Audit access tokens + Requests through access tokens contain the user_id in their audits

---

config/initializers/protected_attributes_hacks.rb

Protected attributes gem is a bad citizen. They monkey patch `ActiveRecord::QueryMethods` instead of adding their own module. It doesn't play well with BabySqueel, for example.
This PR reverts the patch and make it right.

[Rails 5] Fix protected_attributes_continued's evil monkey patch

---

test/unit/api_docs/service_test.rb

Disables NotificationCenter for ApiDocs::Service during its unit tests

[Rails 5] Fix ApiDocs::Service test with NotificationCenter enabled

---

app/controllers/api/applications_controller.rb
app/controllers/buyers/applications_controller.rb
app/controllers/buyers/service_contracts_controller.rb
app/models/contract.rb
app/models/service.rb
features/step_definitions/messages_steps.rb
test/models/backend_api_config_test.rb
test/unit/contract_test.rb
test/unit/three_scale/search_test.rb

Baby Squeel does not work with records in Rails 5, it needs the id
instead of the record.

[Rails5] Fix Baby Squeel usage

---

app/lib/event_store/event.rb

Because it inherits from another class than ApplicationRecord
Closes: THREESCALE-4339

EventStore::Event does not include BackgroundDeletion

---

app/controllers/provider/admin/cms/email_templates_controller.rb
app/lib/authentication/strategy/base.rb
app/lib/three_scale/api/responder.rb
app/models/web_hook/event.rb
app/presenters/dashboard_widget_presenter.rb
lib/developer_portal/app/controllers/developer_portal/access_codes_controller.rb
lib/developer_portal/lib/liquid/drops/pagination.rb
test/functional/provider/admin/dashboard/service/hits_controller_test.rb
test/integration/provider/admin/dashboard/service/hits_controller_test.rb

Causing this error:
Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure. (ActionView::Template::Error)

[Rails 5] Use of unsafe parameters in URL generation

---

test/events/service_contracts/service_contract_created_event_test.rb

[Rails 5] Do not assert_equal nil values for ServiceContracts::ServiceContractCreatedEventTest

---

app/assets/stylesheets/provider/_vertical_nav.scss
app/helpers/vertical_nav_helper.rb
app/javascript/src/Navigation/components/VerticalNav.jsx

We switched to PF4 dark mode in https://github.com/3scale/porta/pull/1525
Now the exclamation mark icon for outdated configuration is missing
https://issues.redhat.com/browse/THREESCALE-4353

Showing exclamation mark when outdated config

---

app/representers/cms/portlet_representer.rb

Extracted from the Rails 5 PR :smile:

[Rails 5] CMS::Portlet does not have attribute #description

---

app/controllers/provider/admin/dashboard/service/hits_controller.rb
app/controllers/provider/admin/dashboard/service/top_traffic_controller.rb

Stats::Service is autoloaded and Rails dependency loader is trying to acquire lock in two different thread but failed

[Rails 5] Race condition non requiring Stats::Service

---

test/unit/invoice_test.rb

Cherry picked from https://github.com/3scale/porta/pull/4/commits/09ac1f11e14ea0b07869aa50c1d7ec848211f2bb

[Rails 5] Use assert_in_delta because of DateTime in DB rounding usec to 0

---

test/unit/mailers/provider_invitation_mailer_test.rb

Extracted from https://github.com/3scale/porta/pull/4/commits/2834e501511638f18de23cdefdd9cdc3cfa6a1f3

[Rails 5] ProviderInvitationMailerTest Use assert_difference with block

---

app/presenters/dashboard_widget_presenter.rb

Extracted from https://github.com/3scale/porta/pull/4/commits/65ebd218ee23d5f887d54dec9cff0d65d6ca30cb

[Rails 5] ActionController::Parameters will not have #to_a

---

app/assets/stylesheets/provider/_forms.scss
app/helpers/api/integrations_helper.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
app/views/api/integrations/show.html.slim
test/functional/api/integrations_controller_test.rb

Closes https://issues.redhat.com/browse/THREESCALE-4242
- make more clear that this about staging apicast configs and not staging their API
- show version above promote button so button text doesn't get too long
before:
after:

Make more clear that configuration page is about the APIcast configuration

---

app/assets/javascripts/provider/admin/apiconfig/services/integration.js.coffee
app/assets/stylesheets/provider/_forms.scss
app/views/provider/admin/backend_apis/forms/_naming.html.slim
config/locales/en.yml

Hint message for Private Base URL is not shown when protocol is 'http'.
https://issues.redhat.com/browse/THREESCALE-3269
- Go to **API  > Integration > Configuration** (http://provider-admin.example.com.lvh.me:3000/apiconfig/services/2/integration/edit)
- Fill input using 'http://echo-api.3scale.net:443', then 'https://echo-api.3scale.net:443'

Show hint message when protocol is not https

---

.flowconfig
app/helpers/admin/api_docs_helper.rb
app/javascript/packs/service_active_docs.js
app/javascript/src/ActiveDocs/components/ActiveDocsSpec.jsx
app/javascript/src/Types/libs/libdefs.js
app/views/admin/api_docs/base/swagger.html.erb
config/locales/en.yml
doc/dependency_decisions.yml
package-lock.json
package.json
spec/javascripts/ActiveDocs/ActiveDocsSpec.jsx
spec/javascripts/ActiveDocs/__snapshots__/Spec.spec.jsx.snap

> ⚠️ Merge only after #1596
Introduces `swagger-ui-react` in ActiveDocs in order to support OAS3 / Swagger 3:
[THREESCALE-2725: Start using SwaggerUI 3.18.3 or higher for OAS3 specs](https://issues.redhat.com/browse/THREESCALE-2725)
1. Go to any Product's active docs section: apiconfig/services/2/api_docs/<id>/preview#/
2. Create a new spec (v3) i.e. [Swagger petstore](http://petstore.swagger.io:8080/api/v3/openapi.json)
3. It should display the new UI
4. Opening a spec (v2) should still display the old UI:
Dev portal support and proper styling will be handled in a following PR (#1595).

Support OAS3 in Admin Portal (ActiveDocs)

---

config/initializers/rails_sqli.rb
test/unit/rails_sqli_test.rb

We forbid all nested subquery like: Model.where({models: {column: true}}) in the code on purpose.
To prepare for Rails 5.x we need to take into account ActionController::Parameters as well
The fix is a bit reworked on for it to be more robust

[CVE] Rails SQLi also check for ActionController::Parameters

---

app/javascript/packs/active_docs.js
app/javascript/src/ActiveDocs/swagger-ui-3-patch.scss

> Moved from #1544
Adds a CSS "patch" that overrides Swagger-ui styles and makes it look more like dev portal.

Support OAS3: add proper styling to Dev Portal

---

app/models/authentication_provider.rb

Fixes AuthenticationProvider.available(:provider) #=> nil

AuthenticationProvider::AVAILABLE is an HashWithIndifferentAccess

---

lib/developer_portal/app/controllers/developer_portal/admin/account/passwords_controller.rb
lib/developer_portal/app/views/developer_portal/password/new.html.liquid
lib/developer_portal/lib/liquid/forms/base.rb
lib/developer_portal/lib/liquid/forms/password_reset.rb
lib/developer_portal/lib/liquid/forms/signup.rb
lib/developer_portal/lib/liquid/forms/spam_protected.rb
test/integration/developer_portal/password_reset_test.rb
test/unit/liquid/forms_test.rb
test/unit/liquid/tags/form_test.rb

* Adds recaptcha to the reset password form in Dev portal (provided **Spam Protection** is enabled)
* refactor and extract `spam_protection` logic from `sign_up` and `password_reset` into a new form class `SpamProtected`.
[THREESCALE-1135: Add Captcha element in the password reset form](https://issues.jboss.org/browse/THREESCALE-1135)
1. Go to admin/account/password/new in the Developer Portal
2. There should be a captcha
3. Form can't be submitted without completing the captcha

Add Captcha to password reset form in Dev Portal

---

app/controllers/sites/base_controller.rb
app/controllers/sites/documentations_controller.rb

The name of the commit is not related to what it currently does. Explanation in https://github.com/3scale/porta/pull/1601#discussion_r373514905

[Rails 5] Remove skip_before_action :activate_menu_site_or_settings

---

config/environments/test.rb

Extracted from https://github.com/3scale/porta/pull/4/commits/2c3deee3cfb5a83768151e451bcfb34c92ce7578

[Rails 5] Remove config.allow_concurrency = false. It causes the session to be reset

---

.circleci/config.yml

Our Slack isn't receiving any notifications from CI. When you run the
curl command manually, it returns `no_system` error. We added a new
environment variable with the right endpoint.

Fix Slack Webhook URL

---

app/assets/stylesheets/provider/_vertical_nav.scss
app/helpers/vertical_nav_helper.rb
app/javascript/src/Navigation/components/VerticalNav.jsx

Outdated icon in vertical nav bar should be displayed in **Integration** when menu collapsed, then move to **Configuration** when menu expanded
https://issues.redhat.com/browse/THREESCALE-4392

Moving icon to submenu when expanded

---

app/lib/stats/views/csv/top_applications.rb
app/lib/stats/views/csv/usage.rb
app/workers/data_exports_worker.rb

This one removes the require_dependency for app/lib/csv

Remove require_dependency for app/lib/csv

---

test/mailers/notification_mailer_test.rb
test/unit/pdf/finance/invoice_report_data_test.rb

I've extracted here a small part of this commit https://github.com/3scale/porta/pull/4/commits/d3f4aa7e58a5a30c26b6cfc83f029d42209c603d
Part will be extracted to another PR with more changes, and there is part that cannot be extracted.

[Rails 5] Fix Tests: Pdf::Finance::InvoiceReportDataTest & NotificationMailerTest

---

config/environments/test.rb

Extracted: 6c8fd304
A copy of Provider::Admin::Dashboard::Service has been removed from the
module tree but is still active

[Rails5] Eager load test environment

---

app/services/service_creator.rb

Extracted: cb55fdb2
Reason
* Rails 4.2.11
Hash#slice!(*keys)
Replaces the hash with only the given keys. Returns a hash containing the removed key/value pairs.
{ a: 1, b: 2, c: 3, d: 4 }.slice!(:a, :b) #=> {:c=>3, :d=>4}
* Rails 5.x
ActionController::Parameters#slice!(*keys)
Returns current ActionController::Parameters instance which contains only the given keys.
params = ActionController::Parameters.new(a: 1, b: 2, c: 3)
params.slice(:a, :b) # => <ActionController::Parameters {"a"=>1, "b"=>2} permitted: false>
params.slice(:d)     # => <ActionController::Parameters {} permitted: false>

[Rails5] Fix change in ActionController::Parameters#slice!

---

app/lib/proxy_config_affecting_changes.rb
app/models/service.rb
test/unit/service_test.rb

This PR ensures that proxy config affecting changes events are issued when the `Service`'s `backend_version` attribute changes. In theory, this should not be needed, because changing `backend_version` also causes the `Proxy`'s `authentication_method` to change, and this one is tracked already as a so called "proxy config affecting change". The problem is that sometimes we change both the service and the proxy together, the service "autosaves" the proxy, but yet the callback fails to catch `authentication_method` among the `previous_changes` and the event is never issued.
With this PR, we will issue redundant events, which is not great resources-wise, but acceptable for now. Important to recall that the event for proxy config affecting changes is idempotent.
In the future, we should …

Fix proxy affecting changes event not issued on Settings update

---

app/services/messages/destroy_all_service.rb
app/workers/delete_plain_object_worker.rb
app/workers/destroy_all_deleted_objects_worker.rb
app/workers/proxy_config_affecting_change_worker.rb
app/workers/publish_enabled_changed_event_for_provider_applications_worker.rb
app/workers/purge_stale_objects_worker.rb
config/jobs.rb
lib/tasks/services.rake
test/unit/services/messages/destroy_all_service_test.rb
test/unit/tasks/services_test.rb
test/workers/destroy_all_deleted_objects_worker_test.rb

- Inherit from ApplicationJob instead of ActionJob::Base
- [RuboCop] DestroyAllDeletedObjectsWorker with frozen_string_literal
- DestroyAllDeletedObjectsWorker inherits from ApplicationJob instead of including
- [Refactor] Simplify Messages::DestroyAllServiceTest
A small part of this is extracted from https://github.com/3scale/porta/pull/4/commits/d3f4aa7e58a5a30c26b6cfc83f029d42209c603d, but the vast majority of this PR is just refactoring :smile:

[Refactor] Make some workers inherit from ApplicationJob

---

lib/three_scale/lazy_initialization.rb

We want to switch to ruby 2.5 at least but for now we need to be compatible with 2.4
See https://bugs.ruby-lang.org/issues/14133
Closes [THREESCALE-4409](https://issues.redhat.com/browse/THREESCALE-4409
)

private define_method in ruby 2.4

---

app/controllers/provider/admin/webhooks_controller.rb
lib/developer_portal/app/controllers/developer_portal/cms/new_content_controller.rb

Remove deprecation of render text: 'Something'
Uses render plain: 'Something' instead

Get rid of deprecation warning about :text format in render

---

config/application.rb

⚠️ This is a hotfix
Adding as reference https://issues.redhat.com/browse/THREESCALE-4418
* If this file is needed before anything, it should not live app/lib
* Sidekiq config/initializers/sidekiq.rb require some files that live in app/lib
All files that are required before eager_load should live in lib and required manually
Otherwise production dependency require failures might happen: wrong order of dependencies loaded
because it will rely on ActiveSupport::Dependencies loading mechanism ...
Just try to launch sidekiq in `test` environment
```shell
RAILS_ENV=test bundle exec sidekiq
```

[hotfix] Require threescale.rb before any app initializers

---

test/unit/extra_fields_test.rb

The main goal is to remove the shoulda syntax to be able to run any test in isolation :smile: but the PR also improves the test in other ways :smile:

[Rails 5] Refactor Test ExtraFieldsTest

---

Gemfile.base
Gemfile.lock
gemfiles/prod/Gemfile.lock

We are using a forked version of HtmlPipeline and looks like it isn't
needed, since the fork was only to be able to run with ruby 2.1.
Using this old forked gem is causing us to have a CVE-2018-3740 because
it uses the sanitize library (in an old version). This new version of
HtmlPipeline doesn't even use sanitize.
[THREESCALE-3437](https://issues.redhat.com/browse/THREESCALE-3437)

Replace the forked version of HtmlPipeline gem with the released one

---

app/controllers/provider/signups_controller.rb
test/integration/provider/signups_controller_test.rb

Closes [THREESCALE-4423](https://issues.redhat.com/browse/THREESCALE-4423)
- Make Provider::SignupsControllerTest runnable by adding the '.each'
- Fields must be built AFTER building user and account. ActionView::Template::Error: undefined method `defined_extra_fields' for nil:NilClass
- Test with invalid email
- Do not test the value of the password
- Ensure variables @Provider and @user even when spam does not pass
- Ensure the correct value of subdomain and singup_mode
- Test signup_type

[Bugfix] Fix Provider::SignupsController#create & tests.

---

app/assets/javascripts/flash.js
app/assets/stylesheets/provider/_flash.scss
app/views/shared/provider/_flash.html.erb

Flash message at top of the page not visible when the page is large
https://issues.redhat.com/browse/THREESCALE-4028
- Go to **API > Applications > Application Plans**(http://provider-admin.example.com.lvh.me:3000/apiconfig/services/2/application_plans)
-Create an application plan and observe the flash message

Flash message at top of the page not visible

---

app/lib/logic/provider_upgrade.rb
test/integration/admin/cms/switches_controller_test.rb

For some reason `provider` has to be reloaded in order for this test case to pass.
It's blocking #1667

✅ Fix SwitchesController test

---

Gemfile.base
Gemfile.lock
app/controllers/application_controller.rb
app/models/ability.rb
config/initializers/cancan_hacks.rb
gemfiles/prod/Gemfile.lock
lib/developer_portal/app/controllers/developer_portal/admin/accounts_controller.rb

Fixes Rails 5 deprecation warning messages to use before_action instead of before_filter.
Allows to close https://github.com/3scale/porta/pull/452 (together with https://github.com/3scale/porta/pull/1670) and https://github.com/3scale/porta/pull/1668
Contains a commit extracted from https://github.com/3scale/porta/pull/1669.

Bump cancancan from 1.7.1 to 2.3.0

---

app/controllers/provider/signups_controller.rb
test/integration/provider/signups_controller_test.rb

Closes [THREESCALE-4476](https://issues.redhat.com/browse/THREESCALE-4476)
1. Go to master-domain.example.com/p/signup
2. Fill different values for **organization name**, **subdomain**, and **admin domain**.
3. Create and confirm that the new account has been created with those values.

[Bugfix] Custom Admin Portal address from 3scale signup form not being created

---

app/controllers/provider/passwords_controller.rb
test/functional/provider/passwords_controller_test.rb
test/integration/provider/passwords_test.rb

We currently have a bug in production that does not allow the user to
reset its password in the master provider. It returns a `Wrong domain
for pat /p/password` error.

Allow reset password in master provider

---

app/helpers/account_helper.rb
app/models/sso_token.rb
app/workers/zync_worker.rb
lib/developer_portal/app/views/developer_portal/dashboards/components/_latest_forum_posts.html.erb
lib/developer_portal/lib/liquid/drops/application.rb
lib/developer_portal/lib/liquid/drops/base.rb
lib/developer_portal/lib/liquid/drops/topic.rb
lib/developer_portal/lib/liquid/forms/base.rb

Fixes THREESCALE-3397
Big thanks to @guicassolato  who made a deep search on this memory leak
He found out that the routes helpers were increasing every requests
Also read rails/rails#32304 (comment)

[memory-leak] Do not regenerate routes every requests

---

app/models/account.rb
app/models/user.rb
test/unit/concerns/background_deletion_test.rb

This is necessary to be able to do [THREESCALE-4483](https://issues.redhat.com/browse/THREESCALE-4483)
I encountered when testing that Jira issue in preview and seeing:
> DeleteAccountHierarchyWorker Account->associations NameError: uninitialized constant 'class_name'

[Bugfix] Ensure that all associations of the BackgroundDeletion config can be constantized

---

config/environments/test.rb

Do not eager_load if Spring is defined in Kernel.
Meaning it is run inside of a Spring server fork

[test] Allow the use of Spring

---

config/initializers/redis_hacks.rb

While trying to detect redis sentinels, DNS failures are raised not with the expected `Redis::BaseConnectionError` class, but as simple `RuntimeError`, making https://github.com/redis/redis-rb to fail on `Redis::Client::Connector::Sentinel#sentinel_detect` without rescue.
This PR makes the hack introduced in https://github.com/3scale/porta/pull/858 to address this issue as well.
Closes System part of [THREESCALE-4495](https://issues.redhat.com/browse/THREESCALE-4495).

Fix connection error on detection of Redis sentinel

---

app/models/plan.rb
test/workers/delete_plain_object_worker_test.rb

This is necessary to do [THREESCALE-4483](https://issues.redhat.com/browse/THREESCALE-4483)
It fixes the deadlock described in [this comment](https://issues.redhat.com/browse/THREESCALE-4483?focusedCommentId=13971719&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13971719).
We need to update the position of the plans within an issuer when we remove a plan, however, when we are gonna remove the issuer anyway (which means when the plan is destroyed_by_association), we do not need to do that update.

Fix Deadlock destroying plans by association without updating the position within the service

---

spec/javascripts/Dashboard/ApiFilter.spec.jsx

As part of #1058 the `ApiFilter` was refactored and some specs became outdated.
This PR makes sure ApiFilter has a proper coverage.

Fixes spec for ApiFilter component

---

features/old/liquid/active_docs_v3.feature
features/old/providers/active_docs_v3.feature
features/provider/active_docs.feature
features/services/active_docs.feature
features/step_definitions/active_docs_steps.rb
features/step_definitions/api_docs_step.rb

Tests were left half done due to time constraints. This PR is to make sure all necessary tests are present and the ones that are not yet supported (due to lack of plugins) are properly marked as `@wip`.

OAS3: Cleaning up tests

---

lib/tasks/db.rake
openshift/system/config/database.yml

Deploying to OCP with PostgreSQL fails with `PG::InsufficientPrivilege: ERROR: permission denied to create database` due to `db:setup` always trying to create the database, even when the database is already there. This PR handles this error.
Closes [THREESCALE-4522](https://issues.redhat.com/browse/THREESCALE-4522)

Fix deploy to OCP with PostgreSQL

---

app/controllers/application_controller.rb
app/lib/proxy_config_affecting_changes.rb
app/models/backend_api.rb
app/models/backend_api_config.rb
app/models/proxy.rb
app/models/proxy_rule.rb
app/models/service.rb
test/integration/application_controller_test.rb
test/models/backend_api_config_test.rb
test/models/backend_api_test.rb
test/test_helpers/proxy_config_affecting_changes.rb
test/unit/proxy_config_affecting_changes_test.rb
test/unit/proxy_rule_test.rb
test/unit/proxy_test.rb
test/unit/service_test.rb

**TODOs**
1. Create Product
2. Add product-level mapping rule
3. Edit product-level mapping rule
4. Delete product-level mapping rule
5. Add Policy config
6. Edit Policy config
7. Delete Policy config
8. Edit Product setting attribute (e.g. authentication method)
9. Edit Proxy config attribute (e.g. error message)
10. Stale settings update
11. Add Backend
12. Edit Backend path
13. Edit Backend endpoint
14. Add backend-level mapping rule 
15. Edit backend-level mapping rule
16. Delete product-level mapping rules
17. Remove Backend
18. Delete Product

Refactoring ProxyConfigAffectingChanges

---

app/assets/stylesheets/provider/_commons.scss
app/controllers/admin/api/backend_apis_controller.rb
app/views/api/backend_usages/edit.html.slim
app/views/api/backend_usages/index.html.slim
app/views/provider/admin/backend_apis/forms/_naming.html.slim
config/locales/en.yml

Fixes nothing, just tries to:
- make backends in a product and the path they have a bit easier to understand
- be consistent with naming of Private Base URL
(triggered by docs review)

APIAP small ux improvements

---

Gemfile.base
Gemfile.lock
gemfiles/prod/Gemfile.lock

Closes [THREESCALE-4527](https://issues.redhat.com/browse/THREESCALE-4527)

Downgrades rack from 2.2.2 back to 2.0.9

---

app/controllers/provider/passwords_controller.rb
app/javascript/src/LoginPage/LoginPageWrapper.jsx
app/views/provider/sessions/new.html.slim
config/routes.rb
features/old/accounts/password_reset.feature
features/step_definitions/url_steps.rb
spec/javascripts/LoginPage/LoginPageWrapper.spec.jsx
test/integration/provider/passwords_test.rb

[THREESCALE-303](https://issues.redhat.com/browse/THREESCALE-303)
We currently enabled reseting password for master account but we
shouldn't have done this. This commit disables the reset password link
for master account.

Disable Reset Password for Master account

---

lib/tasks/password_reset.rake

Relates to https://issues.redhat.com/browse/THREESCALE-303
Usage, in a shell console where the application is running
```shell
bundle exec rails 'password:reset:master'
```
You will be prompted for the email or username
Then you will be prompted for the password and confirm it
```shell
bundle exec rails 'password:reset:master[john]'
```
Then you will be prompted for the password and confirm it
```shell
bundle exec rails 'password:reset:master[john,123456]'
```
It will set the password of User `john` to `123456`

[rake] Task to reset password of a User of Master tenant

---

config/initializers/redis_hacks.rb
test/unit/redis_hacks_test.rb

Introduces a test for the `RedisHacks` module, ensuring that the `RuntimeError` exceptions with message "Name or service not known" are handled when trying attempting to connect to Redis sentinels.
The test assumes too much about the implementation of `Redis::Client`, but I found no other way since it's testing a hack on that class. Maybe we could mock the connection with the sentinel instead.

Test for the RedisHacks

---

db/migrate/20200224095152_default_nil_fields_end_user_removal.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Following @Martouta 's [suggestion](https://github.com/3scale/porta/pull/1648#issuecomment-587091982) let's try to default all columns (that will be removed) to `null` before ignoring them. 
[THREESCALE-2490: Remove “End-user plans” feature (SaaS) - Phase 2](https://issues.redhat.com/browse/THREESCALE-2490)
**Notes:**
Merge before #1677.
The migration consists of:
```ruby
class RemoveEndUserPlans < ActiveRecord::Migration
def change
safety_assured { remove_column :settings, :end_users_switch }
safety_assured { remove_column :settings, :end_user_plans_ui_visible }
safety_assured { remove_column :cinstances, :end_user_required }
safety_assured { remove_column :plans, :end_user_required }
safety_assured { remove_column :services, …
```

Remove EndUser and EndUserPlans [default fields to null]

---

app/models/proxy.rb

Tries to fix ~[THREESCALE-4470](https://issues.redhat.com/browse/THREESCALE-4470)~ [THREESCALE-4565](https://issues.redhat.com/browse/THREESCALE-4565).
I don't really know why some times the `ProxyConfigAffectingChange` object is tried to be saved without a `proxy_id` if it's created using the (has_one) association of the `Proxy` object. I think it has to do with the hacks of https://github.com/westonganger/protected_attributes_continued, which BTW would be great if we could remove for good.
What this PR does is making `Proxy#create_proxy_config_affecting_change` to comply with the method signature of gem's override for `ActiveRecord::Associations::SingularAssociation#create`, and ensures `proxy_id` is always passed among the attributes.
A test would probably be stupid at this point, like …

Ensures `proxy_id` on create proxy config affecting change

---

app/models/contract.rb
app/models/plan.rb
app/models/service.rb
app/models/settings.rb
db/migrate/20200224095152_default_nil_fields_end_user_removal.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

This PR programmatically removes (ignores) the columns that will be removed in [the migration](https://github.com/3scale/porta/pull/1667).
[THREESCALE-2490: Remove “End-user plans” feature (SaaS) - Phase 2](https://issues.redhat.com/browse/THREESCALE-2490)
**Notes:**
The migration consists of:
```ruby
class RemoveEndUserPlans < ActiveRecord::Migration
def change
safety_assured { remove_column :settings, :end_users_switch }
safety_assured { remove_column :settings, :end_user_plans_ui_visible }
safety_assured { remove_column :cinstances, :end_user_required }
safety_assured { remove_column :plans, :end_user_required }
safety_assured { remove_column :services, :end_user_registration_required }
safety_assured { remove_column :services, :default_end_user_plan_id …
```

Remove EndUser and EndUserPlans [ignore columns]

---

app/models/account/payment_details.rb
app/models/account/states.rb
test/unit/account/payment_details_test.rb

Bugfix for `ActiveRecord::InvalidForeignKey` when destroying an account.
The error info from the logs is the following:
```ruby
{
class: ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper,
wrapped: DeletePlainObjectWorker,
queue: 'default',
args: [{
job_class: DeletePlainObjectWorker,
job_id: '85eff265-d651-4c89-a018-4c72208623d7',
provider_job_id: nil,
queue_name: 'default',
priority: nil,
arguments: [{ _aj_globalid: 'gid://system/Account/ObfuscatedID' }, ['Hierarchy-Account-ObfuscatedID'], 'destroy'],
locale: 'en'
}],
retry: true,
jid: '835a14c11d288e7aa9f458f4',
created_at: 1_582_278_967.298682,
enqueued_at: 1_582_279_062.923246,
error_message: "Mysql2::Error: Cannot add or update a child row: a foreign key constraint fails
(`preview01`.`payment_details`, CONSTRAINT …
```

[Bugfix] InvalidForeignKey deleting an account while persisting its payment detail

---

app/lib/pdf/dispatch.rb

Batch will keep in memory all jobs until it finishes executing the block
Then serializes them ...
Meaning that if the number of Service is high it will make memory bloat
I do not think we need batch jobs for that
If we do we should make groups of batches
For history it was introduced here: https://github.com/3scale/system/pull/7146/files#diff-11a34b15fb80c7e8722c003106db3066

[memory-bloat] Do not use batch on pdf worker

---

lib/developer_portal/app/views/developer_portal/docs.html.liquid

We should not be creating new accounts with liquid template of the Documentation page expecting a OAS 3-based ActiveDoc.
Closeso [THREESCALE-4578](https://issues.redhat.com/browse/THREESCALE-4578)

[hotfix] Roll back liquid template for the documentation page

---

app/assets/stylesheets/provider/_tables.scss

In a[ previous PR](https://github.com/3scale/porta/commit/2aa16f13084ddf75ac3c89d8e53664d800ee92b2#diff-a0b0a5af615f99925dc446629346f40bR29) word-break was added to handle long metric names, but now it's affecting also other places.
**BEFORE:**
**AFTER:**

Fix word-break for long words

---

app/models/service.rb
app/workers/delete_service_hierarchy_worker.rb
test/workers/delete_service_hierarcy_worker_test.rb

Closes [THREESCALE-4534](https://issues.redhat.com/browse/THREESCALE-4534)
1. In the test, the following line was true no matter if it was `.never` at the end or `.once` (really, try it locally with the master branch before this PR and you will see xD) :joy: :woman_shrugging: :crystal_ball: 
https://github.com/3scale/porta/blob/731e2821a2c70311adf5ca14fd5c1f4366ceed27/test/workers/delete_service_hierarcy_worker_test.rb#L54
So as I saw that we could avoid relying on the dangerous "never called" and we could just run it and see if it is deleted for real or not, that is what I did :smile: 
2. In the same test, lacking `::Logic::RollingUpdates.stubs(enabled?: true)` and `::Logic::RollingUpdates.stubs(skipped?: false)` made the 2 following lines completely useless and both tests turned out to …

[Bugfix] [APIAP] Deletion of product also delete backend used by another product

---

lib/tasks/proxy.rake
test/unit/tasks/proxy_test.rb

```
rake task proxy:reset_config_change_history
rake task proxy:reset_config_change_history[<account_id>] 
```
Closes [THREESCALE-4588](https://issues.redhat.com/browse/THREESCALE-4588)

Rake task to reset proxy config change history

---

app/lib/backend_api_logic/routing_policy.rb
test/unit/backend_api_logic/routing_policy_test.rb
test/unit/proxy_test.rb

We currently use `original_request.path` in the config for the APIAP routing policy. This causes the URL Rewriting policy to be a no-op when used in combination with APIAP. This PR replaces `original_request.path` with `uri`, which should have no side-effect for APIAP and re-enable the URL Rewriting policy in combination.
Customers may need to regenerate their proxy configs (i.e. promote) for this change to take effect, but this is OK, because that would be needed anyway in order to append an eventual URL Rewriting policy config.
Closes [THREESCALE-4301](https://issues.redhat.com/browse/THREESCALE-4301)

Use uri instead of original_request.path in the apiap routing policy

---

app/workers/delete_plain_object_worker.rb

Closes [THREESCALE-4445](https://issues.redhat.com/browse/THREESCALE-4445)
Mysql raises timeouts when it tries to delete many records at once.
Error:
```
{:exception=>{:class=>ActiveRecord::StatementInvalid, :message=>"Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: DELETE FROM `application_keys` WHERE `application_keys`.`id` = 20391", :backtrace=>[...]}, :parameters=>{:context=>"Job raised exception", :job=>{"class"=>"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper", "wrapped"=>"DeletePlainObjectWorker", "queue"=>"default", "args"=>[{"job_class"=>"DeletePlainObjectWorker", "job_id"=>"aa6dfb9a-c59e-4141-b80c-302bfdd73eb5", "queue_name"=>"default", "arguments"=>[{"_aj_globalid"=>"gid://system/Account/ObfuscatedID"}, ["Hierarchy-Account-ObfuscatedID", …
```

[Bugfix] DB timeout deleting many records at once

---

app/helpers/api/integrations_helper.rb
app/lib/apicast/curl_command_builder.rb
app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
test/test_helpers/curl_command_test_helpers.rb
test/unit/apicast/curl_command_builder_test.rb
test/unit/helpers/api/integrations_helper_test.rb

Closes [THREESCALE-3797](https://issues.redhat.com/browse/THREESCALE-3797) + Refactoring of the `CurlCommandBuilder` class used by the `IntegrationsHelper`.
It also fixes a bug with the test curl command showed for accounts with api as product enabled, when apicast's target environment is `production`. I don't think we really show the example curl command in such case, in a way that the bug was probably never activated. Still, just in case we ever decide to use that option, the `environment` argument was supposed to be passed along and it is not in https://github.com/3scale/porta/blob/3ef93f4c68835705e134cd81c9cb9f7f2c888cbd/app/helpers/api/integrations_helper.rb#L129 It was hard-coded always `:staging`.

Fix test curl command bad URI

---

app/lib/api_authentication/by_access_token.rb
test/integration/by_access_token_test.rb

In System API requests it is possible to bypass access token security by
using HTTPBasicAuth. This is a security issue.
A member access token that does not have access to a given scope should
also be denied when used in HTTPBasicAuth requests targeting API
endpoints secured under that same scope.
Example:
```
$ curl
"https://<host>/admin/api/registry/policies.json?access_token=<my-secret-access-token>"
{"error":"Your access token does not have the correct permissions"}
$ curl -u :<my-secret-access-token>
"https://<host>.3scale.net/admin/api/registry/policies.json"
{"policies":[]}
```
The problem was a problem in the token checking. We were only checking
the if the token was being sent in params. This commit also considers
the HttpBasicAuth token to …

Fix HttpBasicAuth security scope check in api calls

---

db/migrate/20200224095152_default_nil_fields_end_user_removal.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb

Following @Martouta 's [suggestion](https://github.com/3scale/porta/pull/1648#issuecomment-587091982) let's try to default all columns (that will be removed) to `null` before ignoring them. 
⚠️ This is blocking #1725 
[THREESCALE-2490: Remove “End-user plans” feature (SaaS) - Phase 2](https://issues.redhat.com/browse/THREESCALE-2490)

Default EndUser related fields to null in the DB

---

lib/system/database/definitions/mysql.rb
lib/system/database/definitions/oracle.rb
lib/system/database/definitions/postgres.rb

Removes the triggers for End User Plans in the 3 DBs. Merge before https://github.com/3scale/porta/pull/1648
[THREESCALE-2490: Remove “End-user plans” feature (SaaS) - Phase 2](https://issues.redhat.com/browse/THREESCALE-2490)

Remove EndUser and EndUserPlans [triggers]

---

app/events/proxy_configs/affecting_object_changed_event.rb
test/events/proxy_configs/affecting_object_changed_event_test.rb

Closes [THREESCALE-4322](https://issues.redhat.com/browse/THREESCALE-4322)
It will help a lot for [THREESCALE-4483](https://issues.redhat.com/browse/THREESCALE-4483)

Do not issue ProxyConfigs::AffectingObjectChangedEvent when account is scheduled_for_deletion

---

.circleci/config.yml

Now every push will need manual approval
Incovenient but will maybe lower the bill
Press the button if you want your PR to go through the builds

[circleci] Do not trigger CircleCI build automatically

---

app/lib/api_authentication/by_access_token.rb
test/integration/admin/api/services_controller_test.rb
test/integration/by_access_token_test.rb
test/integration/by_provider_key_test.rb

We currently have a bug when apicast tries to fetch the proxy configs
for a service using ProviderKey via BasicAuth. It returns a forbidden
status.
This happened because we changed in #1736 to consider the access_token
when sent in HttpBasicAuth but we only considered if the token was
present.
This commit changes this behave to also consider if the AccessToken is
present, otherwise, it will tries to make the authentication using the
provider key.
[THREESCALE-4625](https://issues.redhat.com/browse/THREESCALE-4625)

Fix HTTP BasicAuth when using ProviderKey

---

app/controllers/admin/api/services/proxies_controller.rb
doc/active_docs/Account Management API.json

Adds a warning to the description of the attribute `api_backend` of the Proxy Update endpoint of the Admin API. This attribute should not be used in combination with APIAP as it may result in Backend Usages being removed from the Product. Instead, when APIAP is enabled (Saas and 2.7+), the new Backend Update endpoint should be used instead.
The reason why the attribute was not removed from the API is for compatibility reasons. We still need to support it in Saas for non-APIAP accounts.
Closes [THREESCALE-4117](https://issues.redhat.com/browse/THREESCALE-4117)

Warning message for the api_backend attr in the API

---

app/indices/topic_index.rb

Closes [THREESCALE-4652](https://issues.redhat.com/browse/THREESCALE-4652)
Topic has been deprecated for 3 years and it is SaaS-only.
We do not even run tests of Topic for Oracle:
https://github.com/3scale/porta/blob/670411d5bdcba562da6d413446c521bf7e9c598b/test/unit/topic_test.rb#L4-L6
So this PR does not index the topic.

[Sphinx] Do not index Topic for Oracle

---

app/assets/stylesheets/provider/_commons.scss
app/assets/stylesheets/provider/_tables.scss

Very long names of metrics, patterns and url's are not wrapping
https://issues.redhat.com/browse/THREESCALE-4659
Fill your Products/Backends with absurd large names in metrics, mapping rules or url's
_______
**Before:**
_______
**After:**

Adding word-break to long names in metrics, patterns and urls

---

config/initializers/oracle.rb

INTERVAL DAY TO SECOND cannot be cast to integer thus the delta indices fail
[Oracle][ODBC][Ora]ORA-30081: invalid data type for datetime/interval arithmetic
Closes THREESCALE-4652
Helped from https://stackoverflow.com/questions/10092032/extracting-the-total-number-of-seconds-from-an-interval-data-type
```sql
SELECT DUMP("ACCOUNTS"."UPDATED_AT" - SYSDATE) FROM "ACCOUNTS"
WHERE ROWNUM = 1
```
```
Typ=190 Len=24: 0,0,0,0,0,0,0,0,244,255,255,255,220,255,255,255,56,12,106,247,10,0,0,0
```
```
rake openshift:thinking_sphinx:start                                                                                                                               [2.5]
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original …
```

[oracle] Fix sphinx delta not using correct datatypes

---

portafly/src/App.tsx
portafly/src/pages/index.tsx

* Removes a relative path that wasn't changed in #1757 
~~* Specify props for the `LazyRoute` component, removing "prop spreading" pattern.~~
* Fixes `portafly/src/pages/index.tsx` by importing from default (instead of named) exports.
* yarn start works
* yarn tests is green

Small Fixes

---

app/models/backend_api.rb
app/services/service_creator.rb
app/validators/uri_validator.rb
config/locales/en.yml
test/unit/proxy_test.rb
test/unit/services/service_creator_test.rb
test/unit/validators/uri_validator_test.rb

Closes [THREESCALE-4658](https://issues.redhat.com/browse/THREESCALE-4658)
Fix requested from [ [#1515](https://github.com/3scale/porta/pull/1515) | [THREESCALE-2932](https://issues.redhat.com/browse/THREESCALE-2932) ]
- Add tests for scenarios that were not tested and fix/improve existing tests.
- Respond with 'too_long' message when the label or the host is too long.
- Refactor UriValidator.
TODO in another PR: https://github.com/3scale/porta/pull/1761#discussion_r390632248

[Bugfix & Refactor] Improve validation of URIs.

---

app/events/services/service_deleted_event.rb
test/events/services/service_deleted_event_test.rb

Closes [THREESCALE-4620](https://issues.redhat.com/browse/THREESCALE-4620)
We are using this event from the following places only (except for the tests 😄 ):
https://github.com/3scale/porta/blob/d30107bb05143712c5ef9545a822f3db93555b52/app/mailers/notification_mailer.rb#L370-L380
https://github.com/3scale/porta/blob/d30107bb05143712c5ef9545a822f3db93555b52/app/models/service.rb#L587-L589
https://github.com/3scale/porta/blob/d30107bb05143712c5ef9545a822f3db93555b52/app/lib/event_store/repository.rb#L150
https://github.com/3scale/porta/blob/d30107bb05143712c5ef9545a822f3db93555b52/app/lib/event_store/repository.rb#L165
https://github.com/3scale/porta/blob/d30107bb05143712c5ef9545a822f3db93555b52/app/subscribers/service_deleted_subscriber.rb#L6
This means that it is used only for mailing and …

[Bugfix] ServiceDeletedEvent never saves the entire provider object

---

lib/routing_constraints.rb
test/integration/provider/passwords_test.rb
test/unit/domain_constraints_test.rb

Extracted from: https://github.com/3scale/porta/pull/1765/
Currently ProviderDomainConstraint has a bug that it also allows Master
to access it. We should only allow provider on this constraint because
we have another one called MasterOrProviderDomainConstraint to be used
when both can access a route.
This commit changes this behave forbidding MasterDomain to access routes
only for providers.

Avoid Master account to access routes with ProviderDomain constraint

---

app/lib/authentication/strategy/base.rb
app/lib/authentication/strategy/oauth2.rb
app/lib/authentication/strategy/oauth2_base.rb
app/lib/authentication/strategy/provider_oauth2.rb

- This one removes the needing of require_dependency for
app/lib/authentication

Remove the usage of require_dependency for app/lib/authentication

---

app/models/contract.rb
app/models/plan.rb
test/unit/contract_test.rb

Attempt to fix [THREESCALE-3876](https://issues.redhat.com/browse/THREESCALE-3876)
I am not sure if it fixes it or not because I could not reproduce it and I do not have access to those Bugsnag logs anymore. And I couldn't reproduce it.
But either way, this will help to avoid duplication... when a plan is about to be destroyed, let's do not try to destroyed it again.

Do not run callback to destroy customized plan if it is about to be destroyed anyway

---

app/models/plan.rb
test/unit/plan_test.rb

This PR adds a validation for parameters which cannot be negative. 
[THREESCALE-1758: Negative value can be set for trial period](https://issues.redhat.com/browse/THREESCALE-1758)
While creating a new application, User(previously) could give negative inputs in the fields like: trial period, setup fee and cost per month. Now these fields ask for a positive value.
- Go to the 'Context Selector'
- Click on the 'API'
- On the left hand side, under the functionality panel, click on 'Applications' and choose 'Application Plans'
- Click on 'Create Application Plan' and these parameters are available on the new page that shows up.

Add validation to trial period, setup fee and cost per month

---

app/models/proxy.rb
app/workers/proxy_config_affecting_change_worker.rb

The 1st commit reverts https://github.com/3scale/porta/pull/1721 because unfortunately, it does not work 😞 
The 2nd commit adds some logs to help us understand [THREESCALE-4778 - Mysql2::Error: Field 'proxy_id' doesn't have a default value: INSERT INTO `proxy_config_affecting_changes` VALUES ()](https://issues.redhat.com/browse/THREESCALE-4778)

LOG ProxyConfigAffectingChangeWorker to understand the proxy_id as NULL

---

app/models/config_path.rb
test/unit/backend_api_logic/routing_policy_test.rb
test/unit/config_path_test.rb
test/unit/proxy_test.rb

The regex used to match the path of the backend in the APIAP routing policy configuration should only allow paths that _start with_ the chosen value for the path. Currently it matches all paths that _contains_ the value.
This PR fixes it by wrapping the current regex pattern within a `^()` group.
Closes [THREESCALE-4736](https://issues.redhat.com/browse/THREESCALE-4736)

Fix APIAP routing policy rule

---

test/test_helpers/spam_protection_stubs.rb

Because they seem to do nothing at all 😂

Remove empty methods related to a test helper to unstub spam_protection

---

portafly/src/components/Root.tsx
portafly/src/i18n/i18n.tsx
portafly/src/i18n/index.ts
portafly/src/i18n/locales/en/index.ts
portafly/src/i18n/locales/index.ts
portafly/src/i18n/supported-languages.ts
portafly/src/i18n/useTranslation.ts
portafly/src/pages/Applications.tsx
portafly/src/pages/Overview.tsx
portafly/src/tests/__mocks__/reacti18nextMock.js

Proposal for some improvements in the base PR:
* Creates types for the translations: it's very important to be able to check what "pages" we are requesting.
* Encapsulates translations (JSON) inside their modules (folders). This way no matter if we use one or multiple jsons for each language, the code stays consistent.
* Creates types for the locales (languages really): i18next handles simple strings.
One thing to keep in mind: I think we're starting to mix up _locales_ with _languages_. A locale takes localization into account whereas language does not. That is basically why I defined a `ISupportedLanguages` instead of `ILocales`, because we're using `en` instead of `en-US`.

Add types and encapsulates translations

---

portafly/portafly_api.yml

In order to not only shaping but documenting the API endpoints we need to hydrate PortaFly, we need to use as base an OAS. This will also serve as a testing tool and development used as mocked data.
This PR also solves the first specification needed for Account > List
This spec is created with Apicurio and it's meant to be edited with it. More info in https://www.apicur.io/
Introduces an Open API Specification and address the specification needs described in https://issues.redhat.com/browse/THREESCALE-4731
https://issues.redhat.com/browse/THREESCALE-4711
https://issues.redhat.com/browse/THREESCALE-4731
BASED ON https://marvelapp.com/55343de/screen/67190787
**How it looks** …

Adding a simple first version of an ongoing shaping OAS3 spec

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock
config/initializers/active_record.rb
lib/deadlock_retry.rb
test/minitest_helper.rb
test/test_helpers/proxy_config_affecting_changes.rb
test/test_helpers/simple_mini_test.rb
test/test_helpers/thread_helper.rb
test/unit/api_authentication/by_authentication_token_test.rb
test/unit/api_authentication/http_authentication_test.rb
test/unit/api_authentication/suspended_account_test.rb
test/unit/events/event_test.rb
test/unit/events/importer_test.rb
test/unit/notification_center_test.rb
test/unit/proxy_config_affecting_changes_test.rb
test/unit/search_presenters_test.rb
test/unit/three_scale/analytics/account_classifier_test.rb
test/unit/three_scale/analytics/user_classifier_test.rb
test/workers/event_import_worker_test.rb
test/workers/last_traffic_worker_test.rb
test/workers/user_session_sweeper_worker_test.rb

Just use a simple file in lib as it is not maintained anymore
Remove deprecation warning
Also fixes some random failures (commits out of scope of this PR but I am lazy to put them in another PR while those failures happen in this one)
https://app.circleci.com/pipelines/github/3scale/porta/10565/workflows/5a2e408d-4a40-4fd8-bda2-0eeaf294f6e0/jobs/165960/tests
| test_add_cost - Finance::BillingStrategyTest |
| --------------------------------------------|
````
NoMethodError: undefined method `create_invoice!' for nil:NilClass...
Failure:
test_add_cost(Finance::BillingStrategyTest) [/opt/app-root/src/project/app/models/finance/buyer_invoice_finder.rb:26]:
NoMethodError: undefined method `create_invoice!' for nil:NilClass
app/models/finance/buyer_invoice_finder.rb:26:in `create_invoice' …
```

[gem] Remove deadlock_retry gem and fix random failures

---

test/factories/account.rb

@guicassolato discovered in https://github.com/3scale/porta/pull/1793#discussion_r402315785 that the tests were creating 2 backend_apis with 2 backend_api_configs for the default service using the factory provider_account.
This was happening because Rails 5 runs callbacks for the tests and this didn't happen for Rails 4, so in Rails 4, we created the BackendApi and BackendApiConfig of the factory ourselves instead of relying on the callbacks of the regular workflow, and now, it will just follow the regular workflow only instead.
https://github.com/3scale/porta/blob/c67d5d8227a1f64c0ff2c0d91f5ea39a00cb9fb9/app/models/service.rb#L45
https://github.com/3scale/porta/blob/c67d5d8227a1f64c0ff2c0d91f5ea39a00cb9fb9/app/models/service.rb#L560-L562 …

[Tests] The Factory provider_account now has only 1 BackendApi and 1 BackendApiConfig

---

db/migrate/20190527104222_fix_oracle_deleted_objects_precision.rb

**DONE AND WORKING... NOW IT MUST BE DECIDED IF WE ARE GOING TO MERGE THIS PR BEING A PATCH FOR 2.6 OR JUST CLOSE IT** 😄 
Closes [THREESCALE-4793](https://issues.redhat.com/browse/THREESCALE-4793)
1. Go to the code of 2.6. `git checkout 3scale-2.6.0-CR1`. _Ideally, we should do the test from 2.5, but that is more time consuming because it implies [installing an older version of Ruby and may give errors trying to install it all now](https://stackoverflow.com/questions/59350892/installing-ruby-2-1-2-cannot-load-such-file-openssl-loaderror)._
2. Set the config files of that moment in time. `yes | cp config/examples/* config/` and `git checkout . && git clean -f -d`
3. Install the gems of that code. `DATABASE_URL="oracle-enhanced://rails:railspass@127.0.0.1:1521/systempdb" …

[Bugfix] [Oracle] Patch Upgrade from 2.5 to 2.6. FixOracleDeletedObjectsPrecision with data

---

portafly/package.json
portafly/src/tests/factories/developer-account.ts
portafly/src/tests/factories/index.ts
portafly/src/tests/pages/DeveloperAccountList.test.tsx
portafly/src/types/index.d.ts
portafly/yarn.lock

Aiming to have more solid and realistic examples when testing, an object factory specific for testing is added. [Fishery](https://github.com/thoughtbot/fishery)  is used to tackle this, from Thoughtbot, same company that produced Factory Bot currently used in Porta.
fixes https://issues.redhat.com/browse/THREESCALE-4646
Run within portafly directory: `yarn test src/tests/pages/DeveloperAccountList.test.tsx`
And it should be green. Also, feel free to `console.log` and analyze the object created.

Introducing factories for better testing

---

app/controllers/api/metrics_controller.rb
test/integration/api/metrics_controller_test.rb

https://github.com/3scale/porta/commit/91cac4d1101b43cfae3b85239af82f8e6e9126ae broke finding the metric for methods `toggle_(enabled|visible|limits_only_text)`. This PR fixes it.
BTW, those methods should not even be part of that controller!
Closes [THREESCALE-4936](https://issues.redhat.com/browse/THREESCALE-4936)

Fix toggle metric enabled/disabled

---

app/lib/apicast/curl_command_builder.rb
test/unit/apicast/curl_command_builder_test.rb

Closes [THREESCALE-4786](https://issues.redhat.com/browse/THREESCALE-4786)
It tries to update the proxy with an invalid URI, it detects it as invalid in the model when it rescues the error and adds an error message. Then, it tries to render the edit page with the error message, but it also tries again to use the URI as such without rescues the error that it rescued before so it gets raised. 
With this PR, the page renders anyway.
https://github.com/3scale/porta/blob/3970c8a478ebcb6e033cd4255d09df5136fe3c90/app/controllers/api/integrations_controller.rb#L30
https://github.com/3scale/porta/blob/3970c8a478ebcb6e033cd4255d09df5136fe3c90/app/models/proxy.rb#L698-L704
https://github.com/3scale/porta/blob/3970c8a478ebcb6e033cd4255d09df5136fe3c90/app/controllers/api/integrations_controller.rb#L46- …

Apicast::CurlCommandBuilder renders the page with an invalid uri as well

---

app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
test/integration/api/integrations_controller_test.rb

Hiding test curl command when the integration in OpenID Connect
https://issues.redhat.com/browse/THREESCALE-4384
Verification steps
Go to **Integration > Configuration** change **Integration settings** to OpenID Connect

Hiding test curl command when the integration in OpenID Connect

---

app/models/application_key.rb
app/models/concerns/save_destroy_for_application_association.rb
app/models/deleted_object.rb
app/models/referrer_filter.rb
db/migrate/20200420104331_add_metadata_text_column_to_deleted_objects.rb
db/oracle_schema.rb
db/postgres_schema.rb
db/schema.rb
test/unit/application_keys_test.rb
test/unit/deleted_object_test.rb
test/unit/referrer_filters_test.rb

Extracted from #1815 as part of [THREESCALE-4806](https://issues.redhat.com/browse/THREESCALE-4806
)
There are corrections and comments from https://github.com/3scale/porta/pull/1815#discussion_r412776325 😄 
It has the same naming as #1827 
We also clean DeletedObject orphans 1 week after their parents have been deleted, so even if at 1st we will save things that we won't need, it will be only for 1 week.

Save AppKey/RefFilter as DeletedObject for destroyed_by_association

---

app/events/applications/application_deleted_event.rb
app/lib/event_store/repository.rb
app/models/deleted_object.rb
app/subscribers/application_deleted_subscriber.rb
app/workers/backend_delete_application_worker.rb
test/events/applications/application_deleted_event_test.rb
test/subscribers/application_deleted_subscriber_test.rb
test/unit/deleted_object_test.rb
test/workers/backend_delete_application_worker_test.rb

Extracted from #1815 as part of [THREESCALE-4806](https://issues.redhat.com/browse/THREESCALE-4806
)
Depends on #1829 (already merged 💃 )

When a Cinstance is destroyed => We delete in Apisonator the Cinstance and its associations saved in DeletedObject

---

app/lib/three_scale/spam_protection/integration/controller.rb
app/lib/three_scale/spam_protection/protector.rb
test/integration/developer_portal/passwords_controller_test.rb

The controller request should mark in a session that the request was considered as spam for the next GET request. 
https://issues.redhat.com/browse/THREESCALE-4531

[ThreeScale::SpamProtection::Integration::Controller] mark_possible_spam

---

test/factories/account.rb
test/functional/api/integrations_controller_test.rb
test/integration/provider/admin/backend_apis/mapping_rules_controller_test.rb
test/integration/provider/admin/backend_apis/metrics_controller_test.rb
test/integration/provider/admin/backend_apis/stats/usage_controller_test.rb

Related to https://github.com/3scale/porta/pull/1805
As explained in that issue, we do not need this anymore.
I have removed the trait only from provider_account and not from the simple_service factory because that explanation only applies to the default service and not all services.
Not generating or saving these extra objects anymore may also make the tests a little bit faster.

Remove Trait in Account to create BackendApi associated to its default Service

---

app/controllers/api/integrations_controller.rb
app/controllers/api/services_controller.rb
test/integration/api/integrations_controller_test.rb
test/integration/api/services_controller_test.rb

2.8 patch for [THREESCALE-5103](https://issues.redhat.com/browse/THREESCALE-5103)
Follow these steps to test it locally.
1. Add this to `config/rolling_updates.yml` (I think that only the 2nd one is necessary for this, but just in case):
```
apicast_v2: true
apicast_oidc: true
```
2. Make webpack work properly for development `bundle exec rake webpack:dev`
3. Run the rails server `UNICORN_WORKERS=8 bundle exec rails server -b 0.0.0.0`
4. You need to ensure that your service has a service token. If you are not sure of that, open sidekiq with the default queue `bundle exec sidekiq -q default -L log/sidekiq.log` and run `bundle exec rake fixes:create_missing_service_tokens`. Then you won't need sidekiq anymore for this so feel free to close it after this 😄 
5. Go to …

[2.8] Do not recreate OIDCConf object from UI IntegrationsController

---

lib/tasks/backend_api.rake
test/unit/tasks/backend_api_test.rb

Closes [THREESCALE-5137](https://issues.redhat.com/browse/THREESCALE-5137)
Problem explained in https://issues.redhat.com/browse/THREESCALE-5137?focusedCommentId=14066849&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14066849
The reason is that this backend api does not have metrics. Since [THREESCALE-3355](https://issues.redhat.com/browse/THREESCALE-3355), we create this metric for all new backend apis. But [this was made the 9th of September](https://github.com/3scale/porta/commit/6be289ac6ce93b1a83aa99fd6d4bc1f3793b9167), but this backend api was created before that... so we should create it for all the older backend apis.

[Bugfix][Task] Create default metrics for the backend apis that do not have it

---

app/controllers/api/integrations_controller.rb
app/controllers/api/services_controller.rb
test/integration/api/integrations_controller_test.rb
test/integration/api/services_controller_test.rb

2.9 part of [THREESCALE-5103](https://issues.redhat.com/browse/THREESCALE-5103)
Cherry-picked from the 2.8 patch https://github.com/3scale/porta/pull/1838

[2.9] Do not recreate OIDCConf object from UI IntegrationsController

---

lib/tasks/backend_api.rake

Fix Oracle for https://github.com/3scale/porta/pull/1841
```
Error:
Tasks::BackendApiTest#test_create_default_metrics:
ActiveRecord::StatementInvalid: OCIError: ORA-00907: missing right parenthesis: SELECT * FROM (SELECT  "BACKEND_APIS".* FROM "BACKEND_APIS" WHERE (NOT EXISTS(SELECT "METRICS"."ID" FROM "METRICS" WHERE "METRICS"."OWNER_TYPE" = 'BackendApi' AND "METRICS"."OWNER_ID" = "BACKEND_APIS"."ID" ORDER BY "METRICS"."ID" ASC)) ORDER BY "BACKEND_APIS"."ID" ASC ) WHERE ROWNUM <= :a1
lib/tasks/backend_api.rake:16:in `block (2 levels) in <top (required)>'
test/test_helpers/rake.rb:12:in `execute_rake_task'
test/unit/tasks/backend_api_test.rb:34:in `block in <class:BackendApiTest>'
```

[Bugfix][ORA-00907] Rake backend_api:test_create_default_metrics

---

app/lib/backend_client/application/utilization.rb
test/integration/api/applications_controller_test.rb
test/unit/backend_client/application/utilization_test.rb

Closes [THREESCALE-3351 - NoMethodError in api/applications#show](https://issues.redhat.com/browse/THREESCALE-3351)
Bugsnag log:
```
app/lib/backend_client/application/utilization.rb:33:in `process_utilization': undefined method `map' for nil:NilClass (NoMethodError)
from app/lib/backend_client/application/utilization.rb:7:in `utilization'
from app/controllers/api/applications_controller.rb:47:in `show'
```
The problem is just that Pisoni can return nil but we weren't contemplating this option here (however, we were covering it in the view already):
https://github.com/3scale/porta/blob/62f27e830b521413b56c984f0f586aec542b3093/app/controllers/api/applications_controller.rb#L46-L48
https://github.com/3scale/porta/blob/62f27e830b521413b56c984f0f586aec542b3093/app/lib/backend_client/applicatio …

[Bugfix][UI] Apisonator Utilization nil => Show message 'This is an unmetered app'

---

app/models/line_item.rb
test/integration/finance/api/line_items_controller_test.rb

Closes [THREESCALE-4953](https://issues.redhat.com/browse/THREESCALE-4953)
`BigDecimal('something-wrong')` in Ruby 2.3 returns `BigDecimal(0)`
`BigDecimal('something-wrong')` in Ruby 2.4 raises `ArgumentError`
We are using Ruby 2.4 in SaaS since a couple of months ago approx.
This PR makes the easy/quick fix, which is making the code behave like few months ago, since it wasn't failing back then.
A better solution would be returning an invalid error instead, but that is not trivial in our case.

[Bugfix] LineItem does not raise an error if the cost cannot be converted to BigDecimal

---

app/models/application_key.rb
test/unit/application_keys_test.rb

Closes [THREESCALE-5139](https://issues.redhat.com/browse/THREESCALE-5139)
We didn't want to send a message when the application is destroyed, but we weren't keeping in mind destroying in background 😄

Do not notify AppKey destroyed if Cinstance is about to be destroyed

---

app/models/deleted_object.rb

Fix Warning: Pass String instead of Class as value in AR query.

---

app/controllers/api/integrations_controller.rb
app/controllers/api/services_controller.rb
test/integration/api/integrations_controller_test.rb
test/integration/api/services_controller_test.rb

Reverts 3scale/porta#1838
Just reverting. It won't be a 2.8 patch and will be for 2.9 only 😉

Revert "[2.8] Do not recreate OIDCConf object from UI IntegrationsController"

---

app/lib/stats/backend_api.rb
app/models/backend_api.rb
test/unit/stats/backend_api_test.rb

The analytics page of API Backends crashes with a 500 in the ajax request to the usage data when the Backend is not used by any Product. This PR fixes the bug.
Closes [THREESCALE-3159](https://issues.redhat.com/browse/THREESCALE-3159)

Fix Analytics for API Backends when not used by any API Product

---

portafly/src/App.tsx
portafly/src/components/util/AlertsContext.tsx
portafly/src/components/util/index.tsx
portafly/src/i18n/locales/en/shared.yml
portafly/src/pages/Overview.tsx
portafly/src/tests/components/util/AlertContext.test.tsx

Introduces a Provider that handles toast-like Alerts. By means of a `useAlertsContext` hook, it is possible to pop an alert up from anywhere in the app, using the same AlertGroup. Each Alert has a lifespan of 8 seconds and can be closed manually.
TODO?: theoretically it should be possible to maintain an alert alive as long as the mouse is on top of it.
A test button has been added to `http://localhost:3000/applications` in order to verify/demo this functionality.

Adds a Provider to handle Toast Alerts in all Portafly

---

app/events/applications/application_deleted_event.rb
app/lib/backend/model_extensions/cinstance.rb
app/models/application_key.rb
app/models/deleted_object.rb
app/models/referrer_filter.rb
app/services/application_association_backend_service.rb
app/services/application_key_backend_service.rb
app/services/referrer_filter_backend_service.rb
app/workers/backend_delete_application_worker.rb
test/events/applications/application_deleted_event_test.rb
test/unit/backend/model_extensions/cinstance_test.rb
test/unit/deleted_object_test.rb
test/unit/services/application_key_backend_service_test.rb
test/unit/services/referrer_filter_backend_service_test.rb
test/workers/backend_delete_application_worker_test.rb

I'm not sure if the way I've done it is a good idea. I definitely need some reviews with suggestions 😄 
This PR intends to improve the code from the reviews I've received in the other PRs of [THREESCALE-4806](https://issues.redhat.com/browse/THREESCALE-4806)
In particular, this is what it does:
1. Add a test to ensure that the ref filters are also removed only belonging to that Application
2. Remove unused method 'delete_backend_cinstance'
3. Use Service Objects instead of rebuilding the model only to call to Pisoni
4. Use service.backend_id instead of service.id.to_s

[Refactor] Service objects for destroy_backend_value in associations of Application

---

config/abilities/provider_member.rb
test/integration/admin/api/services/backend_usages_controller_test.rb
test/integration/api/backend_usages_controller_test.rb

Member users with access to all services were not being given permission to the backend usages endpoints, only when the user had been given explicit permission to the service (with "All current and future APIs" option disabled). This PR fixes this.
Closes [THREESCALE-4489](https://issues.redhat.com/browse/THREESCALE-4489)

Fix member user permission to Backend Usages

---

app/lib/apicast/provider_source.rb
test/unit/apicast/proxy_source_test.rb

`ActiveModel::Serializer::JSON` includes attributes whose corresponding columns are ignored in the model [1][2]. See, for example, in the Rails console,
```ruby
Service.find(2).attributes.keys - Service.column_names
=> ["tech_support_email", "admin_support_email", "act_as_product", "default_end_user_plan_id", "end_user_registration_required"]
```
[1] https://github.com/rails/rails/blob/4642d68d8021893c69bfd16ed6e926ae03a6d777/activemodel/lib/active_model/serializers/json.rb#L88-L101
[2] https://github.com/rails/rails/blob/1fdb98c033f49254394d16ea154c76596d70885b/activemodel/lib/active_model/serialization.rb#L127
This PR makes sure ignored columns of the `Service` model are NOT included in the JSON serialization of the service for the proxy config.
Closes …

Removes ignored columns of Service from JSON serialization with Apicast::ProviderSource

---

portafly/src/components/data-list/DataListContext.tsx
portafly/src/components/data-list/reducers/PaginationReducer.ts

When being in a distant page (say the last one) and adding filters, the collection is updated but not the Pagination state. It is necessary to reset back to the initial state in order to show the filtered results, for example:
```ts
useEffect(resetPagination, [filters])
```
It can be teste and verified in #1820

Action for Resetting Pagination

---

portafly/src/auth/AuthContext.tsx
portafly/src/components/data-list/reducers/PaginationReducer.ts
portafly/src/dal/accounts/getDeveloperAccounts.ts
portafly/src/pages/DeveloperAccounts.tsx
portafly/src/tests/pages/DeveloperAccounts.test.tsx
portafly/src/utils/auth.ts
portafly/src/utils/http.ts
portafly/src/utils/index.ts
portafly/src/utils/reducers.ts

This is refactor that will ease the use of http async requests and managing responses from Porta API
We were using hooks inside the data layer functions that was an anti pattern. Also redefining `Response` type and using async hooks inside components. 
Launch the app with `yarn start` and porta Rails server,  login with a valid token and navigate to dev accounts, it should render a list of dev accounts. It varies depending on the data in your local porta

[Portafly] Porta-wiring refactor

---

app/lib/plan_rules_collection.rb

This was initially introduced in https://github.com/3scale/system/pull/9326, and since the very beginning, this has not being used. This happened because that PR required some refactoring and after doing it, I forgot to remove this line 😄

Remove unused exception class PlanRulesNotLoaded

---

config/initializers/cve-2020-8161.rb

Since we cannot yet upgrade rack to 2.1.3 or 2.2+ due to restrictions related to the Sidekiq version.
Ref.: https://groups.google.com/forum/#!topic/rubyonrails-security/IOO1vNZTzPA

[CVE-2020-8161] Patch Rack directory traversal vulnerability

---

portafly/.stylelintrc.json
portafly/package.json
portafly/src/components/data-list/searchWidget.scss
portafly/yarn.lock

Portafly doesn't have `node-sass` and the build fails locally.
**Verification**
* removes all node_modules from `porta` and `portafly`
* `yarn && yarn start`

Add support for node-sass

---

portafly/src/i18n/locales/en/accounts.yml

Removes `PROPOSED` tags to have a clean file.
[THREESCALE-4836](https://issues.redhat.com/browse/THREESCALE-4836)
* The strings marked as _Proposed_ have been approved in this MR: https://github.com/3scale/porta/pull/1861

4836-Account_Users-cleanup removed PROPOSED tags

---

test/integration/admin/api/accounts_controller_test.rb
test/integration/admin/api/signups_controller_test.rb

Closes [THREESCALE-5207](https://issues.redhat.com/browse/THREESCALE-5207)
It was accidentally implemented for 2.8 when we added https://github.com/3scale/porta/pull/1546/commits/e2e44c797f41784565b8b0b424567b6cd6e4b81e
This PR is to add tests.

[Test] API Account endpoints fire webhook

---

app/controllers/provider/admin/authentication_providers_controller.rb

Closes [THREESCALE-3548](https://issues.redhat.com/browse/THREESCALE-3548)
The title: SSO Integration, in the vertical navigation, under Developer Portal -> Setting-> SSO Integrations, should be highlight when checked.

Highlight SSO Integrations in vertical navigation

---

app/lib/backend/model_extensions/service.rb
app/models/service.rb
lib/tasks/services.rake
test/unit/account_test.rb
test/unit/service_test.rb
test/unit/tasks/services_test.rb

Tested in Preview 
`RAILS_ENV=preview bundle exec rake "services:destroy_default_service[account_id_here service_id_here]"`
We were requested to destroy a default service in [THREESCALE-5238](https://issues.redhat.com/browse/THREESCALE-5238)
That is a very old and deprecated flag. We do not add it anymore in Porta, but in Apisonator it is mandatory and they usually add it for the first service of the provider.
We did all this in the rails console for it is dangerous and we should have a rake task instead.

Destroy a default service through a rake task

---

features/support/hooks.rb

So we can re-enable taking screenshot and getting more browser info on our tests
It was disabled when migrating to rails 5

With cucumber 2+ the line is in scenario.location

---

portafly/src/components/data-list/BulkActionsWidget.tsx

Fixes this console error:
It's caused by wrong use of a prop.

Fix console error in Overview

---

app/controllers/admin/api/services/proxy/policies_controller.rb
app/services/policies_config_params_wrapper.rb
test/integration/user-management-api/services/proxy/policies_test.rb

A policies_config parameter should be an array. If it's an object, it fails on 500. We should validate this scenario and return 422 if possible.
https://issues.redhat.com/browse/THREESCALE-1059

[PoliciesController] InvalidPoliciesConfigError

---

app/controllers/concerns/error_handling.rb
test/integration/developer_portal/login_test.rb

If someone tries to do `POST /session` to login to the dev portal without the `authentication token` it will fail the request as `forbidden` for https://github.com/3scale/porta/pull/1873
It will also log the error in Rails (because `handle_error` does it 😄 ), but we should additionally notify to Bugsnag when it might be a bug on our side, which is not when the authentication token is sent empty.
Related to what I explained [in this comment in JIRA](https://issues.redhat.com/browse/THREESCALE-5240?focusedCommentId=14109051&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14109051).

Do not report error to Bugsnag if Authentication Token is empty

---

portafly/src/components/data-list/reducers/TableReducer.ts
portafly/src/pages/Overview.tsx

Adds sorting to Table's context and implements it in the Overview.
`sortBy` format and behavior is defined by Patternfly's `Table`.
⚠️ A workaround is needed. When a table is "selectable", the sortBy takes into account the first column (checkboxes) but not the row items. The workaround is to add 1 to the sorting index.

Adds Sorting to Data List

---

features/step_definitions/active_docs_steps.rb
features/support/initial_data.rb

Part of [THREESCALE-5261](https://issues.redhat.com/browse/THREESCALE-5261)
This is faster and it can be reused comfortably when doing ssh to CircleCI 😄

Fix ActiveDocs 2.0 Liquid Oracle CircleCI failures & Speed it up

---

portafly/src/components/data-list/reducers/TableReducer.ts
portafly/src/pages/Overview.tsx

Turned out the index correction has to be handled inside the reducer. It depends on the sorted table being "selectable" or not. That means, it has a `onSelect` callback defined.

Fixes sorting index

---

app/models/account.rb
app/models/account/provider_methods.rb
app/representers/account_representer.rb
spec/acceptance/api/account_spec.rb
test/unit/account_test.rb

Introduces two new attributes in the representation of account objects in the admin API responses: `base_url` and `admin_base_url`. These correspond to the existing `domain` and `admin_domain` attributes prepended with the current HTTP scheme of the system (http or https) to make them full URLs, instead of just domain names.
In particular, this change will allow Zync to resolve which TLS configuration to apply to the Kubernetes/OpenShift routes it manages for the accounts, without having to rely on a default.
Related to [THREESCALE-4832](https://issues.redhat.com/browse/THREESCALE-4832).

[api] attributes base_url and admin_url to account

---

app/controllers/admin/api/accounts_controller.rb
app/lib/api_authentication/by_provider_key.rb
app/models/account.rb
app/models/account/master_methods.rb
lib/developer_portal/lib/site_account_support.rb
test/factories/account.rb
test/functional/developer_portal/admin/account/account_plans_controller_test.rb
test/unit/account_test.rb

Just renamed `find_by_provider_key` to `first_by_provider_key`
Because it becomes annoying to have them when looking at the logs for debugging.

Remove Rails deprecation warning find_by_provider_key

---

test/integration/admin/api/buyers_users_controller_test.rb

Extracted from another PR that will change a lot. So this test will be unrelated to that PR now but the test itself is still valid.

Test Admin::Api::BuyersUsersController#create with correct params and token

---

app/controllers/frontend_controller.rb
lib/developer_portal/app/controllers/developer_portal/cms/new_content_controller.rb

Fixes rubocop warnnig
Notes: `throw(:abort)` only works for ActiveRecord and ActiveModel

Fix ensure_provider callback returning false

---

config/application.rb
config/initializers/deprecation.rb
lib/three_scale/deprecation.rb

Just a subclass of `ActiveSupport::Deprecation`
But it has its own `#behavior` and `#silenced` methods
To modify its configurations, edit ./config/initializers/deprecation.rb
See `ActiveSupport::Deprecation` for full usage
```ruby
deprecate :some_method,
another_method: "use #replacement_method instead",
deprecator: ThreeScale::Deprecation.new
```

Custom ThreeScale::Deprecation

---

lib/tasks/proxy.rake
test/unit/tasks/proxy_test.rb

Introduces a rake task to migrate services to configuration-driven gateway. it can be used for hosted and/self-managed services.
Usage:
```
rake proxy:migrate_to_configuration_driven[<services_selector>,<deploy_to>,<update_endpoints>]
<services_selector> ::= <selector> | <selector>","<services_selector> | nil (default: all services)
<selector> ::= service_id | "hosted" | "self_managed"
<deploy_to> ::= "staging" | "production" | "staging,production" | nil (default: no deploy)
<update_endpoints> ::= <truthy> | <falsey> | nil (default: falsey)
<truthy> and <falsey> resolved by ActiveModel::Type::Boolean#deserialize
```
Examples:
| Command                                                                    | Services                                            | Deploy(*)              | Update …

Rake task to migrate services to configuration driven

---

.gitignore
app/controllers/concerns/error_handling.rb
app/controllers/frontend_controller.rb
app/controllers/master/base_controller.rb
app/controllers/provider/passwords_controller.rb
app/lib/authenticated_system.rb
app/lib/three_scale/api/controller.rb
app/models/account/provider_domains.rb
app/presenters/redhat_customer_oauth_flow_presenter.rb
app/presenters/service_discovery_oauth_flow_presenter.rb
app/views/layouts/error.html.erb
config/application.rb
config/examples/domain_substitution.yml
lib/developer_portal/app/controllers/developer_portal/admin/account/passwords_controller.rb
lib/developer_portal/app/controllers/developer_portal/cms/new_content_controller.rb
lib/developer_portal/lib/site_account_support.rb
lib/routing_constraints.rb
lib/three_scale/domain_substitution.rb
test/unit/domain_constraints_test.rb
test/unit/domain_substitution_test.rb
test/unit/site_account_support_test.rb

Do not make features worry about if we are in production or in preview.
We need to prepare of the removal of ThreeScale::Middleware::DevDomain and remove all monkey patching of `request.host`
This first step is to use `request.internal_host` when it is possible
It will deprecate the use of `Account#domain` and `Account#self_domain`
They will be private later
Relates to https://issues.redhat.com/browse/THREESCALE-5265
Partially closes it.
Example:
When enabled you can point your browser to `http://provider-admin.stg-saas.localhost` and it will use the `Account` which `self_domain` is `provider-admin.example.com`

Prepare removing monkey patch on request.host

---

lib/three_scale/middleware/handle_parse_error.rb
test/unit/three_scale/middleware/handle_parse_error_test.rb

My bad 🙈 
Fixes the status of https://github.com/3scale/porta/pull/1914. Part of [THREESCALE-5280](https://issues.redhat.com/browse/THREESCALE-5280)
[This is why](https://www.restapitutorial.com/httpstatuscodes.html):
-  **400 Bad Request**
The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.
- **422 Unprocessable Entity (WebDAV)**
The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions. For example, this error condition may …

'ActionDispatch::ParamsParser::ParseError' is a 400 instead of 422

---

portafly/src/components/Loading.tsx
portafly/src/components/data-list/SearchWidget.tsx
portafly/src/components/data-list/modals/ChangeStateModal.tsx
portafly/src/components/data-list/modals/DataListModal.tsx
portafly/src/components/data-list/modals/SendEmailModal.tsx
portafly/src/components/developer-accounts/DeveloperAccountsTable.tsx
portafly/src/i18n/i18n.tsx
portafly/src/i18n/locales/en/index.ts
portafly/src/i18n/locales/en/shared.yml
portafly/src/i18n/locales/index.ts
portafly/src/pages/DeveloperAccounts.tsx
portafly/src/tests/components/LazyRoute.test.tsx
portafly/src/tests/components/data-list/__snapshots__/SearchWidget.test.tsx.snap
portafly/src/tests/components/developer-accounts/__snapshots__/DeveloperAccountsTable.test.tsx.snap
portafly/src/tests/pages/__snapshots__/DeveloperAccounts.test.tsx.snap

* Removal of all aria-labels that are not being tracked in our translations. They will be added properly when we figure out what we need.
* Proposal for namespaces: since we have so many files inside our translations folder, I came up with the idea of defining a namespace for each page so usage of `t` is less verbose. We no longer have to define `sections` (renamed to `namespaces`) manually because it uses the keys of the exports directly.

Update i18n strings

---

portafly/src/components/data-list/utils/filterRows.ts
portafly/src/tests/components/data-list/utils/filterRows.test.ts

* A more declarative approach
* If a wrong/invalid filter category is passed, it means the context
state was tampered or no longer valid

[portafly] Refactor: filterRows fn

---

app/mailers/account_mailer.rb
app/mailers/data_export_mailer.rb
app/mailers/post_office.rb
app/mailers/provider_invitation_mailer.rb
app/mailers/provider_user_mailer.rb
app/mailers/topic_mailer.rb
lib/developer_portal/app/mailers/invitation_mailer.rb
lib/developer_portal/app/mailers/user_mailer.rb
lib/three_scale/domain_substitution.rb
test/mailers/notification_mailer_test.rb
test/unit/mailers/invitation_mailer_test.rb
test/unit/mailers/post_office_test.rb
test/unit/mailers/provider_user_mailer_test.rb
test/unit/mailers/user_mailer_test.rb

Do not use account.domain or account.admin_domain anymore in mailers
Other url in drops will have to be fixed
Relates to https://issues.redhat.com/browse/THREESCALE-5265

Use domain substitution in mailers

---

features/step_definitions/custom_web_steps.rb

Fixes https://app.circleci.com/pipelines/github/3scale/porta/11868/workflows/200fae06-aa98-41a6-9b69-0f62c8d81f03/jobs/173141/steps
The problem is just that we make an AJAX request by pressing something in the dropdown, and our Oracle CircleCI is a bit slow... so it reaches the 'then blah blah' before the request has been finished.

Fix CircleCI Oracle random failure: press inside dropdown is AJAX and must wait for requests

---

lib/tasks/proxy.rake
test/unit/tasks/proxy_test.rb

(*) Whether the config will be deployed or not is controlled by the values of `Proxy.deployed_at` and `Account.hosted_proxy_deployed_at`.
- If `Proxy.deployed_at` if present, then the config will be deployed to apicast staging
- If `Account.hosted_proxy_deployed_at >= Proxy.created_at`, then the config will be deployed to apicast production
----
Updated instructions:
Introduces a rake task to migrate services to configuration-driven gateway. it can be used for hosted and/self-managed services.
Usage:
```
rake proxy:migrate_to_configuration_driven[<services_selector>,<update_endpoints>]
<services_selector> ::= <selector> | <selector>","<services_selector> | nil (default: all services)
<selector> ::= service_id | "hosted" | "self_managed"
<update_endpoints> ::= <truthy> | <falsey> | nil …
```

[hotfix] Rake task to migrate services to configuration driven

---

portafly/src/components/pages/Overview.tsx
portafly/src/components/shared/data-list/modals/ChangeStateModal.tsx
portafly/src/tests/components/shared/data-list/modals/ChangeStateModal.test.tsx

Since `ChangeStateModal` is a generic component, we have to pass its options as a prop.
Also we weren't using the proper type `CategoryOption`.

Pass Options as a Prop in Change State Modal

---

portafly/src/components/pages/audience/accounts/listing/DeveloperAccountsTable.tsx
portafly/src/components/shared/empty-states/PageEmptyState.tsx
portafly/src/components/shared/empty-states/TableEmptyState.tsx
portafly/src/components/shared/empty-states/index.tsx
portafly/src/components/shared/index.tsx
portafly/src/tests/components/shared/empty-states/PageEmptyState.test.tsx
portafly/src/tests/components/shared/empty-states/TableEmptyState.test.tsx

Adding the EmptyState components that will be used first by Accounts Listing but then for any page/data-list page.
The Page version is meant to occupy the whole page.
The Table version is meant to be inside a table after loading/filtersing and to have a button like "Try again", "Refresh", "Clear all filters", etc.

Add empty state generic components

---

portafly/src/components/shared/data-list/SearchWidget.tsx
portafly/src/components/shared/data-list/modals/ChangeStateModal.tsx
portafly/src/components/shared/data-list/modals/SendEmailModal.tsx
portafly/src/i18n/locales/en/audience/accounts/listing.yml
portafly/src/i18n/locales/en/shared.yml
portafly/src/tests/components/shared/data-list/__snapshots__/SearchWidget.test.tsx.snap

* Moves strings from `accounts/listing` to `shared`
* Rename some strings (`typeahead` for instance is misleading)
* Apply `i18n` to some left hardcoded strings
* Create some aria-labels (accessibility is still to be reviewed more thoroughly)

Update some i18n strings

---

Gemfile.base
Gemfile.lock
Gemfile.prod.lock
app/controllers/provider/admin/dashboards_controller.rb
app/helpers/menu_helper.rb
app/helpers/provider/admin/dashboards_helper.rb
app/lib/logic/provider_settings.rb
app/models/alert.rb
app/models/cinstance.rb
app/models/service.rb
app/views/provider/admin/dashboards/_service_navigation.html.slim
config/webpacker.yml
test/helpers/menu_helper_test.rb
test/unit/logic/provider_settings_test.rb

Performance problems with the dashboard.
https://issues.redhat.com/browse/THREESCALE-3592
Tested with 1K products and backends -> time to load page reduced from 34 seconds(on 3scale 2.8.2) to 14 secconds
Tested with 1.5K backends -> time to load page reduced from 29 seconds(on 3scale 2.8.2) to 9 secconds
Tested with 1.5K products -> time to load page reduced from more than 1 minute/or internal error displayed due to long loading time (on 3scale 2.8.2) to 19 secconds

[Dashboard] optimization

---

portafly/src/components/pages/accounts/AccountsDataListTable.tsx
portafly/src/components/pages/accounts/utils/accountsTableDataFactory.tsx
portafly/src/tests/components/pages/accounts/utils/__snapshots__/accountsTableDataFactory.test.tsx.snap
portafly/src/tests/components/pages/accounts/utils/accountsTableDataFactory.test.ts
portafly/src/tests/components/pages/accounts/utils/accountsTableDataFactory.test.tsx

Right now `isMultitenant` is a hardcoded value.
[THREESCALE-5326: Distinguish multitenant accounts](https://issues.redhat.com/browse/THREESCALE-5326)

Extract isMultitenant as an Env variable
