3scale/porta

- README.md
Fixing the code climate badges
> [codeclimate] Updating badges to use the current repo

- INSTALL.md
Tip to optionally install Spring and how to do it.
> [install] Optional dependencies: Spring

- app/controllers/api/applications_controller.rb
- app/controllers/buyers/applications_controller.rb
- app/helpers/display_view_portion.rb
- app/views/api/applications/index.slim
- app/views/buyers/applications/_listing.html.slim
- app/views/layouts/api/_service.html.slim
- config/routes.rb
- test/decorators/plan_decorator_test.rb
- test/decorators/service_decorator_test.rb
- test/helpers/display_view_portion_test.rb
- test/integration/api/applications_controller_test.rb
- test/integration/buyers/applications_controller_test.rb
Fixes points 1. 2. and 3. of [THREESCALE-1321](https://issues.jboss.org/browse/THREESCALE-1321)
> [2.4 Feature] Service -> Applications menus and navigation

- INSTALL.md
* Make some things more explicit
* Adds some external links
* Restructure a bit dependencies / prereqs
> Improves install instructions

- INSTALL.md
Getting the development environment up on Mac OS X
> [install] Installation on Mac OS X

- app/views/admin/fields_definitions/index.html.erb
- app/views/finance/provider/settings/show.html.slim
- app/views/layouts/_emails.html.erb
- app/views/layouts/provider.html.slim
- app/views/layouts/sites/_developer_portals.html.erb
- app/views/provider/admin/authentication_providers/index.html.slim
- app/views/provider/admin/cms/builtin_legal_terms/new.html.erb
- app/views/provider/admin/cms/email_templates/index.html.erb
- app/views/provider/admin/webhooks/edit.html.slim
- app/views/shared/provider/_page_title.html.slim
- app/views/sites/dns/show.html.erb
- app/views/sites/emails/edit.html.erb
- app/views/sites/forums/edit.html.erb
- app/views/sites/settings/edit.html.erb
- app/views/sites/spam_protections/edit.html.erb
- app/views/sites/usage_rules/edit.html.slim
- test/functional/sites/usage_rules_controller_test.rb
Fixing titles for setting pages
Meta > title must match with text title
closes: https://issues.jboss.org/browse/THREESCALE-1302
> THREESCALE-1302: Page titles of some admin pages are confusing

- test/workers/invoice_friendly_id_sanitization_worker_test.rb
- test/workers/invoice_friendly_id_worker_test.rb
It defines a couple tests for the 2 invoice friendly ID update workers.
Related to [THREESCALE-1348](https://issues.jboss.org/browse/THREESCALE-1348).
I couldn't reproduce the bug reported at [THREESCALE-1348](https://issues.jboss.org/browse/THREESCALE-1348), though the tests should be welcome anyway.
> [billing] Tests for the invoice friendly id workers

- lib/system/database.rb
fixes https://github.com/3scale/porta/issues/75
> [Bugfix] ActiveRecord::StatementInvalid: OCIError: ORA-04043: object SP_INVOICES_FRIENDLY_ID does not exist

- script/stress-test/provider_clicking.rb
> Fix Applications Show path in ProviderClicking

- app/views/notification_mailer/cinstance_plan_changed.html.slim
- app/views/notification_mailer/cinstance_plan_changed.text.erb
- test/mailers/notification_mailer_test.rb
Most urgent part of [THREESCALE-1373](https://issues.jboss.org/browse/THREESCALE-1373)
This is due to the last navigation changes in https://github.com/3scale/porta/pull/47
> [Bugfix] Application url in PlanChanged NotificationMailer

- app/views/api/alerts/index.html.erb
- app/views/notification_mailer/application_created.html.slim
- app/views/notification_mailer/application_created.text.erb
- app/views/notification_mailer/limit_alert_reached_provider.html.slim
- app/views/notification_mailer/limit_alert_reached_provider.text.erb
- app/views/notification_mailer/limit_violation_reached_provider.html.slim
- app/views/notification_mailer/limit_violation_reached_provider.text.erb
- test/integration/api/alerts_controller_test.rb
- test/mailers/notification_mailer_test.rb
Part of [THREESCALE-1373](https://issues.jboss.org/browse/THREESCALE-1373)
This is due to the last navigation changes in https://github.com/3scale/porta/pull/47
> [Bugfix] Change paths/url Application from under buyer to be under service

- .rubocop.yml
* Updated deprecated cop
* Must use version 0.59.2+
> [rubocop] Configuration fix

- Dockerfile
- config/webpacker.ci.yml
- lib/tasks/webpacker.rake
- script/jenkins.sh
We already precompile assets with sprockets, webpacker should follow the same behaviour.
> [ci] Precompile assets before testing

- app/lib/logic/provider_settings.rb
- app/models/service.rb
- app/models/user.rb
- app/models/user/permissions.rb
- app/views/provider/admin/dashboards/_services_filter.html.slim
- app/views/provider/admin/dashboards/_services_navigation.html.slim
- test/unit/logic/provider_settings_test.rb
- test/unit/service_test.rb
- test/unit/user/permissions_test.rb
- test/unit/user_test.rb
fixes https://github.com/3scale/porta/issues/126
this comes from: https://github.com/3scale/porta/pull/122#pullrequestreview-163385421
- Dashboard with multiservice
- Dashboard with a single service
> Refactor User and Account multiservice?

- bin/webpack
- bin/webpack-dev-server
- package.json
- yarn.lock
* This fixes compilation of test assets, sometimes they were stale. As reference: https://github.com/rails/webpacker/issues/1494
> Fix webpack stale assets on test env

- features/old/providers/active_docs.feature
> Fix cucumber feature: old/providers/active_docs

- features/old/api_docs/provider_side.feature
Apply new navigation to the cucumber feature
> Fix Cucumber feature features/old/api_docs/provider_side

- app/controllers/provider/admin/authentication_providers_controller.rb
- app/views/shared/provider/navigation/audience/_accounts.html.slim
- app/views/shared/provider/navigation/audience/_billing.html.slim
- app/views/shared/provider/navigation/audience/_nav.html.slim
- app/views/shared/provider/navigation/audience/_portal.html.slim
- features/old/authorization/provider_settings.feature
- features/step_definitions/navigation_steps.rb
- features/support/paths.rb
fixes tests and code for member users that only have access to settings (which is kind of crazy if you think of it but that's another story)
> Settings authorization feature

- features/old/accounts/service_contracts.feature
- features/old/applications/providers/managing.feature
- features/old/applications/providers/widget.feature
- features/old/menu/provider.feature
- features/old/providers/settings/legal_terms.feature
- features/provider/applications/stats.feature
- features/step_definitions/custom_web_steps.rb
- features/step_definitions/navigation_steps.rb
- features/support/selectors.rb
This PR is meant to make at least all these tests correct:
```
features/provider/applications/stats.feature
features/old/accounts/service_contracts.feature
features/old/applications/providers/widget.feature
```
And fix big part of:
```
features/old/providers/settings/legal_terms.feature
features/old/applications/providers/managing.feature
```
> Fix cucumber features related to 'subsubmenu'

- features/provider/stats/application.feature
- features/step_definitions/stats/application_steps.rb
Fix `features/provider/stats/application` by clicking to the new Applications link in Dashboard by `/\d Apps?/`
> Fix Cucumber Feature provider/stats/application

- app/views/provider/admin/dashboards/show.html.slim
- features/old/authorization/provider_portal.feature
- features/step_definitions/custom_web_steps.rb
- features/support/selectors.rb
> provider portal access test and code fix

- features/step_definitions/custom_web_steps.rb
- features/step_definitions/providers/partners_menu_steps.rb
- features/support/selectors.rb
Since it was not used anywhere 😄
> Remove from Cucumber unused references to old subsubmenu and buyers submenu

- features/old/providers/settings/legal_terms.feature
Fix the cucumber feature in `features/old/providers/settings/legal_terms.feature` 😄
> Manually test and outline cucumber feature old/providers/settings/legal_terms

- features/old/accounts/web_hooks.feature
- features/support/paths.rb
Fix the feature adapted to current implementation
> Fix cucumber feature old/accounts/web_hooks

- features/old/public_site_access.feature
> Fix cucumber feature old/public_site_access

- features/old/authorization/provider_accounts.feature
- features/old/authorization/provider_finance.feature
- features/old/authorization/provider_plans_section.feature
- features/old/authorization/provider_settings.feature
- features/old/authorization/provider_stats.feature
- features/support/paths.rb
Fixes all authorization features
> authorization features

- features/step_definitions/api/plan_steps.rb
- features/step_definitions/usage_limit_steps.rb
As the title says 💪 
It may even fix some other cukes 😍
> Fix Cucumber feature provider/usage_limits/visibility

- features/old/forums/provider_side/basic_administration.feature
Adapt to where 'Forum' is now... in the main menu 😄
> Adapt to the new navigation the Cucumber feature forums/provider_side/basic_administration

- features/old/buyers/accounts/security.feature
- features/old/buyers/users.feature
- features/old/messages/provider_side.feature
- features/step_definitions/buyers_management/user_steps.rb
- features/step_definitions/navigation_steps.rb
Change `I follow "Developers"` for `I navigate to the accounts page`
> Fix cucumber navigation Developers -> X Accounts

- features/step_definitions/provider_steps.rb
> Fix cucumber feature provider/accounts/managing

- features/old/accounts/invitations.feature
One of the cucumber features to fix 😎
> Fix cucumber feature old/accounts/invitations

- features/old/stats/provider/top_applications.feature
Sometimes JS in Cucumber is not out friend... 😝
> Fix Navigation to Top Applications

- features/old/stats/provider_side.feature
> Fix 'Top Applications' with JS in features/old/stats/provider_side

- app/decorators/service_decorator.rb
- app/helpers/menu_helper.rb
- app/javascript/src/Navigation/components/ContextSelector.jsx
- app/javascript/src/Navigation/components/ContextSelector.spec.jsx
- app/views/shared/_api_selector.html.slim
Add 1 new field:
- *audience_link* is the href of the Audience option in the dropdown
Adds a new property to service by means of ServiceDecorator:
- *link* is the href of each individual API in the dropdown.
**TODO**
> Set ContextSelector Audience and APIs link depending on user permissions

- app/views/shared/provider/navigation/_vertical_nav.html.slim
Full reengineering of the delay logic to cope with some glitches.
> Vertical navigation delay improvements

- .circleci/config.yml
- features/master/applications/keys.feature
- features/step_definitions/navigation_steps.rb
> Fix cucumber feature master - applications - keys

- features/old/switches/groups.feature
> Fix Cucumber Feature: DevPortal Groups with Access Denied

- features/old/api/latest_transactions.feature
> Fix Cuke: Service with Backend v1 doesn't have Traffic

- features/old/api/plans/plan.feature
> Fix Cuke: old/api/plans/plan

- app/views/buyers/applications/new.html.erb
- app/views/provider/admin/onboarding/wizard/info/outro.html.slim
- app/views/shared/provider/navigation/audience/_accounts.html.slim
- app/views/shared/provider/navigation/audience/_nav.html.slim
- app/views/shared/provider/navigation/service/_nav.html.slim
- features/old/api/end_user_plans.feature
- features/old/api/latest_transactions.feature
- features/old/applications/providers/bulk_operations.feature
- features/old/menu/audience_menu.feature
- features/old/services/subscriptions/bulk_operations.feature
- features/old/switches/groups.feature
- features/step_definitions/cms/files_steps.rb
> Last failing tests

- app/views/api/services/show.html.slim
Simplify headers and change order of sections on the page to reflect importance & vert nav order
> Api show page improvements

- app/views/api/services/show.html.slim
Make sure all data attributes for bubbles are present
> Bubbles check

- app/views/shared/provider/navigation/_vertical_nav.html.slim
~Existing problem: when navigating to a subsection (for instance Analytics -> Usage) the submenu will remain visible:~
> Replaces hover with click

- test/integration/admin/api_docs/account_api_docs_controller_test.rb
- test/integration/admin/api_docs/service_api_docs_controller_test.rb
Fix the xpath to access the main menu
> Fix Tests for ApiDocs Controllers Xpath on menu

- app/controllers/sites/forums_controller.rb
- app/views/shared/provider/navigation/audience/_portal.html.slim
> Menu for forum settings enabled/disabled

- app/controllers/provider/admin/webhooks_controller.rb
> Fix webhooks menu navigation

- app/controllers/admin/api_docs/account_api_docs_controller.rb
> ActiveDocs under Account scope must have its active menu

- features/old/api/latest_transactions.feature
- features/old/applications/providers/managing.feature
- features/step_definitions/stats/application_steps.rb
- features/support/paths.rb
> Fix some cucumber features

- config/schedule.rb
Fixes
```
var/lib/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/spec_set.rb:95:in `block in materialize': Could not find sidekiq-batch-0.1.5 in any of the sources (Bundler::GemNotFound)
```
> [cron] Whenever should pass the BUNDLE_GEMFILE to all tasks

- app/lib/signup/master_domains_builder.rb
- doc/liquid/drops.md
- features/support/capybara.rb
- lib/developer_portal/lib/liquid/drops/application.rb
- test/unit/account/domains_test.rb
- test/unit/liquid/drops/application_drop_test.rb
- test/unit/signup/master_domains_builder_test.rb
Merging back features to master so master us up to date with all features
Supersedes #272
> Merge saas branch to master

- app/views/buyers/users/edit.html.erb
- app/views/buyers/users/show.html.erb
- features/old/buyers/users.feature
Taking out the word 'buyer' in 2 places
> Buyer is not a term we want to use in the UI

- app/models/account.rb
Step 1 of https://github.com/3scale/porta/issues/290
> Alias Account attribute state_changed_at as the new deleted_at

- app/assets/stylesheets/provider/_menu.scss
- app/views/layouts/provider/login.html.slim
This PR fix miss-alignment in login page menu
**Before:**
**After:**
> Aligning login page menu

- app/views/shared/provider/navigation/audience/_nav.html.slim
- app/views/shared/provider/navigation/audience/_portal.html.slim
closes https://issues.jboss.org/browse/THREESCALE-1466
> no forum if account cannot use forum or user cannot manage forum

- features/step_definitions/metric_steps.rb
- test/unit/liquid/drops/application_drop_test.rb
- test/unit/tasks/impersonation_admin_user_test.rb
Oracle Jenkins has some tests failing in master and this PR means to fix them both 😄
> Fix Oracle tests

- app/assets/stylesheets/provider/admin/_dashboard.scss
FIX Master - Aligning list items using flex
> THREESCALE-1471 Fix Aligning list items using flex

- app/views/provider/admin/dashboards/_service_navigation.html.slim
> integration icon is a wrench

- config/docker/cache_store.yml
Relates to https://github.com/3scale/openshift-templates/pull/352
So it is the same as in openshift/system/config/cache_store.yml
> [config] Correct docker config of memcached

- app/views/provider/admin/dashboards/_service_navigation.html.slim
- app/views/shared/provider/navigation/service/_nav.html.slim
> use paperclip for subscriptions icon

- app/views/api/integrations/apicast/shared/_client_feedback.html.slim
- app/views/api/integrations/plugin/_plugin.html.slim
- app/views/stats/_sparklines.html.erb
Fixes [THREESCALE-1496](https://issues.jboss.org/browse/THREESCALE-1496
)
I must add a cucumber in another PR
> Fix paths to Service->Analytics->Usage

- .circleci/config.yml
Fixes image used by circleci for tests
github repo has been moved from my account to 3scale org. 
new quay.io repo has been created for this image
we should use that over my own
n/a
> moved from own repo (@gsaslis) to 3scale repo

- app/assets/stylesheets/provider/layouts/_login.scss
> fix error message positioning

- app/assets/stylesheets/provider/admin/_dashboard.scss
closes https://issues.jboss.org/browse/THREESCALE-1550
> Don't shorten long API names as customers depend on them

- app/views/buyers/accounts/_menu.html.slim
- app/views/buyers/accounts/_search_results.html.slim
- test/integration/buyers/accounts_controller_test.rb
closes https://issues.jboss.org/browse/THREESCALE-1493
> scope number of applications by developer account

- test/unit/cinstance_test.rb
Fix Jenkins tests on `test/unit/cinstance_test.rb`
> Fix failures on Cinstance Tests

- app/views/payment_gateways/_stripe.html.erb
Warning message:
>/opt/app-root/src/project/app/views/payment_gateways/_stripe.html.erb:54: warning: key :style is duplicated and overwritten on line 55
> Fixes small warning when running Cucumbers

- .github/wip.yml
Reverts https://github.com/3scale/porta/pull/349 for the reasons exposed in https://github.com/3scale/porta/pull/349#issuecomment-440614356
> Revert "Configure the Github app to prevent us for merging PRs to check for certain words in the title"

- app/assets/stylesheets/provider/_tables.scss
- app/views/buyers/applications/_utilization.html.erb
Fix bug in **Current Utilization** tables:
https://issues.jboss.org/browse/THREESCALE-1382
**Fixed:**
> THREESCALE-1382 Adding word break to first child of td's in table.data

- test/unit/tasks/forum/migrate_forum_test.rb
Fixes a random issue due to ids mix-up.
> fixes minitest random error

- .circleci/config.yml
- features/step_definitions/api_docs_step.rb
- features/support/thread_safety.rb
- lib/tasks/ci/db.rake
- lib/tasks/integration.rake
Adds pipeline build against oracle database
pipeline is not running against oracle in circleci
`oracle_build` pipeline on circleci should be green
> Oracle build running on circleci

- features/provider/active_docs.feature
- features/services/active_docs.feature
- features/step_definitions/active_docs_steps.rb
- features/support/paths.rb
- features/support/selectors.rb
- test/integration/admin/api_docs/account_api_docs_controller_test.rb
- test/integration/admin/api_docs/service_api_docs_controller_test.rb
Cucumber features for rendering the ActiveDocs pages under Account/Service scope
> ApiDocs Xpath tests as a Cucumber feature

- app/models/service_discovery/cluster_service.rb
- test/unit/service_discovery/cluster_service_test.rb
Cherry-picking #357 commits
Cannot merge because it will introduce more changes from master
> [service-discovery] Cherry-picking from a master fix

- LICENSE
License was still under Red Hat custom license. This fixes this issue as we are opensourcing the code
> [opensource] Licensing under Apache 2.0

- lib/developer_portal/app/assets/stylesheets/stats.scss
Fixes a bug in the charts displayed on Statistics section on Developer Portal
Fixes https://issues.jboss.org/browse/THREESCALE-1616
1. Visit Statistics in Developer Portal
2. Voilà
Before:
After:
> [stats] Fix developer portal charts

- app/assets/javascripts/provider/create_application.js.coffee
- app/javascript/packs/applications.js
- app/javascript/src/Applications/plan_selector.jsx
- app/views/buyers/applications/new.html.erb
Fixes https://issues.jboss.org/browse/THREESCALE-1636
Fixes https://issues.jboss.org/browse/THREESCALE-1636
Creating a new application
** Notes ** 
This might be an ugly fix, but it was already ugly af. However, this will be replaced totally by https://github.com/3scale/porta/pull/365
> Fixes Application creation

- app/javascript/src/Users/permissions.jsx
Fixes the linting error introduced by https://github.com/3scale/porta/pull/121
No issue was created for this.
> [permissions] Fixes linting error

- config/routes.rb
- lib/routing_constraints.rb
- test/integration/prometheus_test.rb
This way we comply with Auth Basic protocol
> [prometheus] Use Rack::Auth:Basic for routing

- spec/spec_helper.rb
- test/test_helper.rb
Following https://github.com/3scale/porta/pull/354 that introduced some hard random issues
> [test] Resetting User.current after each tests

- app/controllers/provider/admin/dashboards_controller.rb
Fixes JIRA https://issues.jboss.org/browse/THREESCALE-1583
> Do not unset sample data when login to the dashboard

- .codeclimate.yml
- app/javascript/src/Navigation/components/ContextSelector.jsx
- app/javascript/src/Onboarding/Bubble.jsx
- app/javascript/src/Policies/components/PoliciesWidget.jsx
- app/javascript/src/Policies/components/PolicyChain.jsx
- app/javascript/src/Policies/components/Root.jsx
- app/javascript/src/Policies/store/configureStore.jsx
- app/javascript/src/Policies/webpack-public-path.js
- app/javascript/src/Stats/lib/applications_selector.jsx
- app/javascript/src/Stats/lib/applications_table.jsx
- app/javascript/src/Stats/lib/menu.jsx
- app/javascript/src/Stats/lib/methods_table.jsx
- app/javascript/src/Stats/lib/metrics_selector.jsx
- app/javascript/src/Stats/lib/series.jsx
- app/javascript/src/Stats/lib/state.jsx
- app/javascript/src/Stats/lib/store.jsx
- app/javascript/src/Stats/lib/ui.jsx
- app/javascript/src/Stats/provider/stats_response_codes.jsx
- app/javascript/src/Stats/provider/stats_top_apps.jsx
- app/javascript/src/Users/permissions.jsx
Makes codeclimate cover our JavaScript assets and applies our eslint rules
Fixes https://issues.jboss.org/browse/THREESCALE-1675
> [Codeclimate] Analysing new JS and eslint activated

- app/javascript/packs/navigation.js
- app/javascript/src/Navigation/components/ContextSelector.jsx
- app/views/shared/_api_selector.html.slim
- app/views/shared/provider/_header.html.slim
This PR fixes the bug `TypeError: Uncaught TypeError: window.hideAllToggleable is not a function`
This was raised because the event assignation in the header partial sometimes was executed before the function assignation in window
Fixes https://issues.jboss.org/browse/THREESCALE-1674
> [navigation] Refactoring and fixing bug in navigation

- app/javascript/src/Policies/index.jsx
- app/javascript/src/Policies/store/configureStore.jsx
- package-lock.json
- package.json
Cleans some dependencies that weren't used.
No Jira issue was created for this task
> [Task] Policies cleanup

- .circleci/config.yml
- Makefile
- gemfiles/prod/Gemfile
- gemfiles/prod/Gemfile.lock
- openshift/system/Dockerfile
Goals:
- standard naming for the gemfiles (Gemfile and Gemfile.lock)
- Can be detected by dependabot
- useful for rails upgrade (just add another directory and run the tests for rails 4 and rails 5 in circleci)
Needs https://github.com/3scale/deploy/pull/531
> [gemfile] Moving gemfiles to own directory

- package.json
Fixes `repository` and adds missing `license`.
> Fixes in package.json: repo and license

- Gemfile.base
- Gemfile.lock
- app/models/contract.rb
- config/initializers/audited_hacks.rb
- config/jobs.rb
- gemfiles/prod/Gemfile.lock
- lib/tasks/audit_logs.rake
- test/unit/logic/provider_upgrade_test.rb
- test/unit/validate_model_validations_test.rb
Since audited is compatible with rails 4.2+
> Replace audited-activerecord by audited

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
- test/mailers/notification_mailer_test.rb
Changes: https://github.com/rails/jquery-rails/compare/v3.1.4...v4.3.1
So we can be compatible with rails 5.x
> Upgrade jquery-rails to 4.3.1

- test/test_helpers/account.rb
- test/unit/proxy_config_test.rb
* Removes buggy usage of FactoryGirl
* Removes an old reference to FactoryGirl in a todo comment
> Removes all traces of FactoryGirl

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Not really needed but as it is in the rails-5.0 branch and fixes some issues there I want to update it
> [rails-5.0] Update state_machines

- app/models/service.rb
- app/workers/delete_plain_object_worker.rb
- app/workers/destroy_all_deleted_objects_worker.rb
- config/jobs.rb
- lib/tasks/services.rake
- test/unit/tasks/services_test.rb
- test/unit/three_scale/jobs_test.rb
- test/workers/delete_plain_object_worker_test.rb
- test/workers/destroy_all_deleted_objects_worker_test.rb
This PR contains:
* https://github.com/3scale/porta/pull/381 Fixes race condition of deletion a Service and its proxy
* https://github.com/3scale/porta/pull/496 Adding a cron job to automatically purge all deleted services after 1 day
> [2.4.1] Fix Race condition of deletion of a Service

- app/workers/pdf_report_worker.rb
- test/workers/pdf_report_worker_test.rb
Try new notification system for reports first.
https://issues.jboss.org/browse/THREESCALE-1483
> [report] send reports through new notification system

- app/assets/stylesheets/provider/_header.scss
> Master with capital m

- Gemfile.lock
- gemfiles/prod/Gemfile.lock
small updated related to new eneforced ruby version
> bundled with ruby 2.3.6

- Gemfile.base
- Gemfile.lock
- config/application.rb
- gemfiles/prod/Gemfile.lock
> Remove config_for as it is present in Rails

- app/events/applications/application_deleted_event.rb
- app/events/zync_event.rb
- app/models/contract.rb
- test/events/applications/application_deleted_event_test.rb
- test/unit/contract_test.rb
- test/workers/zync_worker_test.rb
Fixes https://github.com/3scale/porta/issues/442
> [Bugsnag] ActiveRecord::RecordNotFoundZyncWorker@low

- app/models/account/search.rb
- test/unit/account/search_test.rb
Fixes [THREESCALE-1797](https://issues.jboss.org/browse/THREESCALE-1797)
> [oracle] Fix THREESCALE-1797: Dashboard/Signups page error

- app/workers/delete_object_hierarchy_worker.rb
- test/workers/delete_object_hierarchy_worker_test.rb
It simplifies a bit the worker and it fixes the tests (which is the actual goal of this PR).
Please notice that this PR comes from https://github.com/3scale/porta/pull/522 and it is pointing there, not master.
> Simplify DeleteObjectHierarchyWorker and fix its tests

- INSTALL.md
Complete the installation instructions by installing the chromedriver for tests
> [doc] Install chromedriver on Mac OS X

- features/step_definitions/buyer_steps.rb
It is not used and it is confusing to have a code graveyard 😝
> Remove unused Cucumber step: account.paid!

- Gemfile
- Gemfile.base
- gemfiles/prod/Gemfile.lock
Until postgresql can be installed in Saas enviroment.
Better alternative to https://github.com/3scale/porta/pull/376#discussion_r251436408.
> pg gem removed from prod Gemfile

- .circleci/config.yml
- app/workers/delete_object_hierarchy_worker.rb
- config/application.rb
- test/integration/service_not_deleted_test.rb
- test/workers/delete_object_hierarchy_worker_test.rb
- test/workers/delete_plain_object_worker_test.rb
Final fix for the service/object deletion issue
This is a cherry-pick of #522 which fixes https://issues.jboss.org/browse/THREESCALE-1194
> THREESCALE-1194 Final fix on 2.4 branch

- .circleci/config.yml
Does not require manual approval when merge to master
> [ci] Run percy on master branch

- app/javascript/src/Stats/buyer/stats_application.jsx
- app/javascript/src/Stats/lib/applications_selector.jsx
- app/javascript/src/Stats/lib/chart_manager.jsx
- app/javascript/src/Stats/lib/metrics_selector.jsx
- app/javascript/src/Stats/lib/source_collector.jsx
- app/javascript/src/Stats/lib/source_collector_chart_manager.jsx
- app/javascript/src/Stats/lib/stats.jsx
- spec/javascripts/Stats/applications_selector.spec.js
- spec/javascripts/Stats/chart_manager.spec.js
- spec/javascripts/Stats/source_collector.spec.js
Fixes the bug in the application selector on the developer portal charts among other bugs.
Fixes: https://issues.jboss.org/browse/THREESCALE-1683
Visit the Statistics section on the developer portal with an account with multiple apps and services, play with the selector and it should work as expected.
> Fix Application selector

- app/indices/account_index.rb
As suggested in https://github.com/3scale/porta/pull/587#discussion_r255916481
> [Refactor][Rubocop] Style/IfUnlessModifier. Inline if mysql DB for group_concat_max_len

- app/controllers/admin/api/service_contracts_controller.rb
I messed up the order in https://github.com/3scale/porta/pull/605 🤦‍♀️
> [Bugfix] Order sapi= ... at the beginning.

- app/views/provider/domains/show.html.erb
Update styles for new 3scale.net site
https://issues.jboss.org/browse/THREESCALE-1749
**Before:**
**After:**
> THREESCALE-1749 Styling recover domain button

- app/controllers/admin/api/services/proxies_controller.rb
- app/controllers/api/integrations_controller.rb
- app/helpers/api/integrations_helper.rb
- app/models/proxy.rb
- app/services/proxy_test_service.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
- app/views/api/integrations/service_mesh/_form.html.slim
- app/views/api/integrations/show.html.slim
- app/views/api/services/forms/_integration_settings.html.slim
- config/locales/en.yml
- test/integration/user-management-api/services/proxies_test.rb
- test/unit/proxy_test.rb
- test/unit/services/proxy_test_service_test.rb
Closes https://issues.jboss.org/browse/THREESCALE-1876
Closes https://issues.jboss.org/browse/THREESCALE-1780
video: https://www.dropbox.com/s/2vt363wtvz602ac/istio-apicast-ui.mov?dl=0
> THREESCALE-1876 istio integration

- openshift/system/config/rolling_updates.yml
It is on tech-preview
Closes https://issues.jboss.org/browse/THREESCALE-1900
TODO:
> THREESCALE-1900 Enable service mesh integration on premises

- app/controllers/admin/api/accounts_controller.rb
- doc/active_docs/Account Management API.json
Documentation for existing functionality. 
https://issues.jboss.org/browse/THREESCALE-1562
> [accounts#find] documentation

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
The gem adds ability to delete statistics from apisonator.
Relates to the Epic https://issues.jboss.org/browse/THREESCALE-1715
> [gem] Update pisoni to 1.25.0

- app/controllers/admin/api/services/proxy/oidc_configurations_controller.rb
- app/models/oidc_configuration.rb
- app/representers/cinstance_representer.rb
- app/representers/oidc_configuration_representer.rb
- config/routes.rb
- doc/active_docs/Account Management API.json
- spec/acceptance/api/oidc_configuration_spec.rb
- test/factories/other.rb
Closes [THREESCALE-1951](https://issues.jboss.org/browse/THREESCALE-1951)
> [api] SHOW/UPDATE for OIDC Configuration

- db/migrate/20190125090030_add_position_to_mapping_rules.rb
- db/migrate/20190221101857_add_last_to_proxy_rules.rb
- db/oracle_schema.rb
- db/postgres_schema.rb
- db/schema.rb
Required by #530
https://issues.jboss.org/browse/THREESCALE-1787
> [1787] proxy rules new attributes last, position

- INSTALL.md
* Remove XQuartz as we launch cucumber tests with chrome-headless
* Update sphinx installation
* Add Postgres and Memcached
> [install] Update installation on Mac OS X

- app/controllers/admin/api/registry/policies_controller.rb
- app/lib/three_scale/policies/specification.rb
- app/models/policy.rb
- config/locales/en.yml
- test/factories/other.rb
- test/unit/policy_test.rb
- test/unit/three_scale/policies/specification_test.rb
So we do not end up with a String that could potentially contain bunch of newlines
> [policy] Serializing policy schema as Hash

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Needed to delete stats in Backend.
I guess it is safer to have it in another PR 🤔
> [Gem Update] Pisoni to 1.26 for Deletion of Stats

- app/representers/pricing_rule_representer.rb
- spec/acceptance/api/pricing_rule_spec.rb
Fixes https://github.com/3scale/porta/issues/671
> [api] pricing rule should include metric_id

- app/workers/backend_delete_stats_worker.rb
- test/workers/backend_delete_stats_worker_test.rb
Fixes [THREESCALE-2035](https://issues.jboss.org/browse/THREESCALE-2035)
> [Bugfix] missing parameter 'deletejobdef'

- app/views/emails/signup_notification_email.text.liquid
- test/unit/mailers/user_mailer_test.rb
fixes https://issues.jboss.org/browse/THREESCALE-1883?focusedCommentId=13705697&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13705697
> remove 3scale from email signature hat-tip: mkudlej@redhat.com

- app/controllers/admin/api/services/mapping_rules_controller.rb
- app/javascript/src/apicast-manifest.js
- app/representers/proxy_rule_representer.rb
- doc/active_docs/Account Management API.json
- spec/acceptance/api/proxy_rules_spec.rb
- test/integration/user-management-api/services/mapping_rules_test.rb
Closes [THREESCALE-1787](https://issues.jboss.org/browse/THREESCALE-1787)
> [proxy_rule] Add last and position to the API

- openshift/system/config/settings.yml
ReCaptcha configuration for openshift environment. 
https://issues.jboss.org/browse/THREESCALE-1108
> [THREESCALE-1108] recaptcha settings for openshift

- app/helpers/application_helper.rb
- config/locales/en.yml
Adjusts doc links in system to new doc URL structure
https://issues.jboss.org/browse/THREESCALE-2087
https://issues.jboss.org/browse/THREESCALE-2078
> Update links to docs to fit new link structure

- test/test_helpers/indexer.rb
- test/unit/account/search_test.rb
This is an ugly attempt to fix a random test failure related to sphinx indexation delay.
Closes [THREESCALE-2130](https://issues.jboss.org/browse/THREESCALE-2130)
> Fix random search test failure

- config/initializers/message_bus.rb
Fixes a bug introduced by https://github.com/3scale/porta/pull/728
> Hotfix monkey patch message bus namespace

- openshift/system/Dockerfile
- openshift/system/Dockerfile.on_prem
docker-build was failing due changes related to our image node version.
> [docker] using node 8

- app/javascript/packs/custom_policies.js
- app/javascript/packs/custom_policy.js
- app/javascript/src/Policies/components/SchemaEditor.jsx
- app/javascript/src/Policies/util.jsx
- app/javascript/src/utilities/json-utils.jsx
This PR simply extracts JSON related methods used in `custom-policies` to the common folder `utilities`, shared throughout all React modules.
It's to be used by #604 .
> extracts json utils to utilities common folder

- spec/javascripts/utilities/json-utils.spec.jsx
A follow-up PR for https://github.com/3scale/porta/pull/747
> [utils] json utils tests

- app/controllers/provider/admin/registry/policies_controller.rb
- app/lib/logic/rolling_updates.rb
- app/views/shared/provider/navigation/account/_integrate.html.slim
- config/abilities/provider_any.rb
- test/integration/provider/registry/policies_controller_test.rb
We could revert this PR when Custom Policies are good to deliver
> [custom policies] Put UI under rolling update

- INSTALL.md
> Suggest increasing unicorns in README

- app/lib/logic/rolling_updates.rb
- config/docker/rolling_updates.yml
- config/examples/rolling_updates.yml
- openshift/system/config/rolling_updates.yml
closes https://issues.jboss.org/browse/THREESCALE-2372
> [rolling update] api as product

- .circleci/config.yml
Sometimes codecov returns 500 for no reason. So retrying 5 times with a delay of 10 seconds between
After 60 seconds fails
> [ci] Retry fetching codecov

- Gemfile.base
- Gemfile.lock
- config/routes.rb
- gemfiles/prod/Gemfile.lock
This is meant to be replaced by Yabeda, but in order to keep changes small for ops, lets keep it for a while
Relates to #778
> [prometheus] Sidekiq::Prometheus::Exporter is back

- app/lib/logic/rolling_updates.rb
- app/views/payment_gateways/_stripe_elements.html.erb
- features/old/finance/billing_address_and_cc_details_order.feature
- lib/developer_portal/lib/liquid/tags/stripe_form.rb
- test/unit/liquid/tags/stripe_form_test.rb
Closes THREESCALE-2434 - [Review and ensure PCI DSS compliance (Stripe)](https://issues.jboss.org/browse/THREESCALE-2434)
Stripe elements is under rolling update with basic styling
> Rolling update using stripe elements instead of Stripejs V2

- app/representers/method_representer.rb
- spec/acceptance/api/method_spec.rb
Include `description` in method representation
> [api] method includes description

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
- test/unit/backend_client/connection_test.rb
To prepare for ruby 2.4 compatibility
> Upgrade gems: stripe, rest-client

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
- test/unit/active_merchant/stripe_fix_test.rb
Extracted from https://github.com/3scale/porta/pull/790
> [gem] Upgrading webmock to 2.3.2 for ruby2.4

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
- test/test_helpers/backend.rb
> Revert "Bump faraday version to 0.12.2"

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
- test/test_helpers/backend.rb
Reverts 3scale/porta#804
Original PR: https://github.com/3scale/porta/pull/797
> Revert "Revert "Bump faraday version to 0.12.2""

- lib/system/database.rb
Related to https://github.com/3scale/3scale-amp-openshift-templates/pull/38 and [THREESCALE-2120](https://issues.jboss.org/browse/THREESCALE-2120)
> Hybrid Oracle readiness check for CDB and non-CDB

- app/events/zync_event.rb
- app/subscribers/zync_subscriber.rb
- app/workers/zync_worker.rb
- test/events/zync_event_test.rb
- test/workers/zync_worker_test.rb
Related to [THREESCALE-2557](https://issues.jboss.org/browse/THREESCALE-2557)
Closes [THREESCALE-1480](https://issues.jboss.org/browse/THREESCALE-1480)
> Try Zync dependency chain in a Sidekiq batch on UnprocessableEntityError

- test/unit/user_test.rb
Improve the test to make sure that it does as @macejmic discovered and told me in [this comment](https://github.com/3scale/porta/pull/808#discussion_r286491635) 😄
> Test User#accessible_services when the user has access to all services

- app/lib/backend/model_extensions/metric.rb
- app/workers/backend_metric_worker.rb
- test/unit/backend/model_extensions/metric_test.rb
- test/workers/backend_metric_worker_test.rb
Closes [THREESCALE-2328](https://issues.jboss.org/browse/THREESCALE-2328)
> Fix hook on backend metric deletion so it's only called once

- app/views/layouts/provider/login.html.slim
Fix functional tests and clean up the code as well 😄
> Fix any? is not a method of nil

- features/step_definitions/password_steps.rb
Fixes `Unable to find css '#request_password_reset_panel'` 😄
> [Bugfix][Cuke] Unable to find css '#request_password_reset_panel'

- app/views/api/services/forms/_integration_settings.html.slim
fixes https://issues.jboss.org/browse/THREESCALE-2435
https://www.dropbox.com/s/0qg47dus4atvfoe/Screen%20Recording%202019-06-05%20at%2020.00.47.mov?dl=0
> remove js that limits auth options for istio

- app/controllers/admin/api/member_permissions_controller.rb
- app/javascript/src/Users/utils/index.jsx
- config/locales/en.yml
- doc/active_docs/Account Management API.json
closes https://issues.jboss.org/browse/THREESCALE-2610
> use generic accounts when talking permissions

- features/old/accounts/accounts.feature
- features/old/accounts/password_change.feature
- features/old/accounts/personal_details.feature
- features/old/menu/account_menu.feature
- features/old/signup/providers.feature
- features/step_definitions/user_steps.rb
> [Cukes] Fix some navigation broken links from JS/ChromeDriver

- config/examples/message_bus.yml
Hey yo, I heard your unicorns are dying when you visit the integration page.
> [config] stop message bus killing unicorn

- app/assets/stylesheets/loginPageFonts.scss
- app/javascript/src/LoginPage/assets/styles/loginPage.scss
- app/views/layouts/provider/login.html.slim
- package-lock.json
Adding Open Sans font for https://github.com/3scale/porta/pull/761
> PF4 Login Page: Adding Open Sans font

- package-lock.json
- package.json
Updating packages for https://github.com/3scale/porta/pull/761
> Updating patternfly packages

- package-lock.json
- package.json
Updates @patternfly/react-core to 3.36.0 for https://github.com/3scale/porta/pull/761
> Pf4 login page update patternfly react

- doc/active_docs/Account Management API.json
> [swagger] oidc_issuer_type documentation in proxies parameters

- features/step_definitions/forum/category_steps.rb
This way it works for any browser/driver and containing or not the `@javascript` tag 😄
> [Cuke] Fix cuke step for I (follow|press) ___ for category ___

- features/old/applications/providers/referrer_filters.feature
> [Cukes] Remove fakeweb for ReferrerFilter

- app/views/payment_gateways/_stripe_elements.html.erb
fix for https://github.com/3scale/porta/pull/862
> give stripe form less width to submit button sits at right

- app/javascript/src/LoginPage/loginForms/Login3scaleForm.jsx
- app/javascript/src/LoginPage/loginForms/RequestPassWordForm.jsx
Adding basic client side validation for https://github.com/3scale/porta/pull/761
> Adding basic client side validation

- features/step_definitions/cms/files_steps.rb
> [Cukes] step 'the file is deleted' confirms dialog box

- features/step_definitions/invitations_steps.rb
> [Cukes] Fix navigation to send a provider invitation

- features/old/api/plans/account_plans.feature
> [Cukes] Fix Navigation of Feature api/plans/account_plans

- features/step_definitions/custom_web_steps.rb
> [Cukes] Fix Feature buyers/accounts/managing

- app/javascript/src/LoginPage/assets/styles/loginPage.scss
Hide old login, restore Request password partial for https://github.com/3scale/porta/pull/761
> Hide old login for PF4 Login Page

- app/lib/backend/storage.rb
- app/lib/three_scale/message_bus_config.rb
- app/lib/three_scale/redis_config.rb
- config/application.rb
- config/docker/backend_redis.yml
- config/docker/message_bus.yml
- config/docker/redis.yml
- config/examples/backend_redis.yml
- config/examples/message_bus.yml
- config/examples/redis.yml
- config/initializers/redis_hacks.rb
- config/initializers/sidekiq.rb
- lib/tasks/boot.rake
- openshift/system/config/backend_redis.yml
- openshift/system/config/message_bus.yml
- openshift/system/config/redis.yml
- test/unit/three_scale/message_bus_config_test.rb
- test/unit/three_scale/redis_config_test.rb
This PR makes possible to use Redis Sentinel. Wherever there is a redis yml config, just add:
- `sentinels` (String) a comma-separated list of sentinel URLs
- `role` (Symbol) either `:master` ot `:slave`
Closes [THREESCALE-1132](https://issues.jboss.org/browse/THREESCALE-1132)
> Support to Redis Sentinel

- db/oracle_schema.rb
- db/postgres_schema.rb
Missing step for https://github.com/3scale/porta/pull/829
> Run migrations update schemas adding Proxies#oidc_issuer_type

- app/views/provider/admin/account/payment_gateways/braintree_blue/edit.html.slim
Auto indent nightmare of edit view 😂
> Auto indent view: payment_gateways/braintree_blue/edit

- app/controllers/provider/admin/account/payment_gateways/braintree_blue_controller.rb
- app/views/payment_gateways/_braintree_customer_form.html.erb
- app/views/provider/admin/account/payment_gateways/braintree_blue/edit.html.slim
- features/developer_portal/admin/account/billing_and_credit_card_details.feature
- features/old/finance/credit_card_details_for_provider.feature
- features/old/providers/wizard_upgrade_plan.feature
- features/old/site/payment_details.feature
- features/step_definitions/credit_card_steps.rb
- features/support/capybara.rb
- lib/developer_portal/app/controllers/developer_portal/admin/account/braintree_blue_controller.rb
- lib/payment_gateways/brain_tree_blue_crypt.rb
- test/functional/developer_portal/admin/account/braintree_blue_controller_test.rb
- test/unit/payment_gateways/brain_tree_blue_crypt_test.rb
Closes THREESCALE-2426
Using the hosted fields as the Drop-In UI does not fit our workflow of 1 card per account
No big changes for styling.
Take into account that unlike stripe there is no rolling update for this change, so everyone will be directly impacted.
<hr>
**Developer portal screenshot**
<hr>
**Admin portal screenshot**
> [braintree] PCI DSS SAQ A compliance

- test/unit/db/seeds_test.rb
@mikz made a mistake in the seeds for https://github.com/3scale/porta/pull/844 and thankfully he ended up noticing and pushed another commit with the fixed version, but since it is not tested anywhere, it is easy to mess up.
Anyway I am not sure if this test is a good idea or not. Although It seems fast.
I leave it as `[WIP]` for now just to wait for opinions 😄 the code itself of this PR is easy, the point is if we should have it or not, and all opinions are welcome 👍
> [Test] The Seeds do not fail

- app/javascript/src/Navigation/components/VerticalNav.jsx
Add unique keys to react items, to prevent error: `Each child in a list should have a unique "key" prop`
> Adding keys to react items

- app/lib/three_scale/analytics/user_tracking.rb
- test/unit/three_scale/analytics/user_tracking_test.rb
Tests working 😄 Although I am not sure if this is a good idea 🤔
> Fix Test for UserTracking (Segment)

- app/assets/stylesheets/provider/_header.scss
`calc` is used with wrong syntax so it is not compiled properly.
> Fix Master Header's height

- app/javascript/src/LoginPage/loginForms/Login3scaleForm.jsx
PF4 Login Page: Fixing typo in prop of input field
> PF4 Login Page: Fixing typo in prop of input field

- package-lock.json
- package.json
Needed for 2.6 ER1, the deploy was failing because several webpack related issues
> Webpack fix

- app/assets/stylesheets/provider/_header.scss
- app/assets/stylesheets/provider/_patternfly_ie11.scss
- app/assets/stylesheets/provider/_pop_navigation.scss
**Provider**
**Master**
**Alignment detail**
> Header fixes: Dropdowns and Icons spacing

- app/controllers/admin/api/services/proxies_controller.rb
- app/controllers/api/integrations_controller.rb
- app/models/proxy.rb
- app/representers/proxy_representer.rb
- app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
- db/migrate/20190617100508_add_limit_exceeded_error_to_proxies.rb
- db/migrate/20190620092211_backfill_add_limit_exceeded_error_to_proxies.rb
- db/oracle_schema.rb
- db/postgres_schema.rb
- db/schema.rb
- doc/active_docs/Account Management API.json
- test/functional/api/integrations_controller_test.rb
Custom HTTP status and header for Usage limit exceeded error
https://issues.jboss.org/browse/THREESCALE-317
> [317-custom-http-response] usage limit exceeded error

- app/lib/three_scale/analytics/user_tracking.rb
This method is not used anymore and can safely be removed.
> Remove unused method `all_traits`

- .circleci/config.yml
After upgrading webpack and babel, jest tests are  costly.
fixes https://issues.jboss.org/browse/THREESCALE-2833
> Jest circleci

- .circleci/config.yml
- config/webpacker.yml
This should (finally) fix the https://circleci.com/gh/3scale/porta/67652#tests/containers/2 (`Net::ReadTimeout (Net::ReadTimeout)`) in our cukes...
Fixes https://issues.jboss.org/browse/THREESCALE-2821
> Fix Net::ReadTimeout For Good.

- features/old/finance/invoices/line_items.feature
Master is failing because of a rogue cuke.
fixes https://issues.jboss.org/browse/THREESCALE-2878
> Fixing cuke in master

- app/javascript/packs/navigation.js
Adding @babel/polyfill to support Promise and other features in IE11
https://issues.jboss.org/browse/THREESCALE-2889
> Adding @babel/polyfill to support Promise and other features in IE11

- db/migrate/20190627103617_backfill_limit_exceeded_defaults.rb
- db/oracle_schema.rb
- db/postgres_schema.rb
- db/schema.rb
Fixes missing parts of https://github.com/3scale/porta/pull/906
> [db] Backfill proxy limit exceeded defaults

- app/workers/zync_worker.rb
> Classify ZyncWorker::UnprocessableEntityError as Bugsnag INFO level

- app/controllers/api/integrations_controller.rb
- app/services/policies/policies_list_service.rb
- config/docker/sandbox_proxy.yml
- config/examples/sandbox_proxy.yml
- features/step_definitions/apicast_steps.rb
- features/support/initial_data.rb
- openshift/system/config/sandbox_proxy.yml
- test/unit/services/policies/policies_list_service_test.rb
Closes [THREESCALE-2698](https://issues.jboss.org/browse/THREESCALE-2698)
Depends on https://github.com/3scale/deploy/pull/578
> Self managed policies registry url - Phase 1

- doc/liquid/drops.html
- doc/liquid/drops.md
- doc/liquid/tags.html
- lib/developer_portal/app/views/developer_portal/_users_menu.html.liquid
- lib/developer_portal/lib/liquid/drops/provider.rb
- test/unit/liquid/drops/provider_drop_test.rb
Closes [THREESCALE-2941 - Developer portal - plan unauthorized page](https://issues.jboss.org/browse/THREESCALE-2941)
Steps to reproduce explained in [this comment](https://issues.jboss.org/browse/THREESCALE-2941?focusedCommentId=13755959&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13755959).
> [Dev Portal] Hide 'Plans' from Accounts Nav when unauthorized

- app/lib/authenticated_system.rb
Closes [THREESCALE-2630](https://issues.jboss.org/browse/THREESCALE-2630)
> Delete user session cookie with HttpOnly option

- app/javascript/src/Navigation/components/VerticalNav.jsx
- spec/javascripts/Navigation/VerticalNav.spec.jsx
Adds `target` prop back.
Also enhance slightly some specs.
> Reverse PR for #954

- test/unit/db/seeds_test.rb
It enforces the test database to be clean before the seeds test (so Master for sure does not exist)
Closes [THREESCALE-2854](https://issues.jboss.org/browse/THREESCALE-2854)
Alternative approach to https://github.com/3scale/porta/pull/964
> Clean db before seeds test

- app/views/payment_gateways/_stripe_elements.html.erb
It was removed by accident
Closes [THREESCALE-2864](https://issues.jboss.org/browse/THREESCALE-2864)
Just a quick revert copy/paste
> THREESCALE-2864 Re-enable the JS toggle for stripe

- app/workers/delete_object_hierarchy_worker.rb
- test/workers/delete_object_hierarchy_worker_test.rb
Closes [THREESCALE-2987 - Delete in background : New loading logic (more efficient)](https://issues.jboss.org/browse/THREESCALE-2987)
- Results of the tests done in preview with the code that we currently have in production: https://github.com/3scale/infrastructure/issues/746#issuecomment-509272493
- Results of the tests done in preview for the same data with the code of this task:
https://github.com/3scale/infrastructure/issues/746#issuecomment-509288005
> [DeleteObjectHierarchyWorker] Speeding up enqueueing job deletion

- app/workers/zync_worker.rb
- test/workers/zync_worker_test.rb
Closes [THREESCALE-2975](https://issues.jboss.org/browse/THREESCALE-2975)
The bug is because when it retries, the event doesn't exist anymore.
What this PR does:
1. If the event doesn't exist, raise `ActiveRecord::RecordNotFound` instead of crashing in `NoMethodError` for `nil`.
2. As @hallelujah realised, it [automatically retries with exponential time](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry), and [we retry up to 25 times](https://github.com/3scale/porta/commit/1622917a37c08633962d9bfdabd30f7481cf3f8d#diff-0fcadbb087d877eb135040bb90798b38), so it takes over a week and the event is destroyed by then. So this PR makes the retry to go 3 times faster to take up to 6 days and some hours 😄
> [Bugfix] Retry faster so the event still exists. Otherwise, raise the proper error

- app/javascript/packs/LoginPage.js
- app/javascript/packs/SignUpPage.js
- app/javascript/src/utilities/ie11Utils.js
- spec/javascripts/utilities/ie11Utils.spec.jsx
Extract IE 11 detection method to a utils file
https://issues.jboss.org/browse/THREESCALE-2992
> Moving IE11 detection to a utils file

- app/models/service.rb
- app/views/api/plans/_metrics.html.erb
Makes sure the methods and metrics of a service with API as a Product enabled are listed in the edit page of application plan as follows:
- Only "Hits" at the Product level
- "Hits" and methods, plus all other top level metrics at the Backend
API level
> [apiap] [fix] Application plan metrics

- app/controllers/api/metrics_controller.rb
- app/controllers/provider/admin/backend_apis_controller.rb
- app/helpers/vertical_nav_helper.rb
- app/views/provider/admin/backend_apis/show.html.slim
Adds a 'Backend' vertical navigation sidebar
> [apiap] "Backend API" sidebar

- app/lib/switches.rb
- app/views/sites/usage_rules/edit.html.slim
- lib/tasks/end_users_switch.rake
- test/unit/settings_test.rb
THREESCALE-2709
Deactivate "End User Plans" for all SaaS accounts
> [2709] disable end user switch

- INSTALL.md
A bit of rewording to *INSTALL.md* file.
> :pencil: rewords install.md

- app/models/service_discovery/cluster_client.rb
- test/unit/service_discovery/cluster_client_test.rb
It fixes Service Discovery's endpoint to connect to the cluster REST API specifically to fetch Openshift projects info.
The old endpoint `https://kubernetes.default.svc/oapi` is no longer an option in Openshift 4: https://github.com/openshift/api/pull/195
Closes [THREESCALE-3114](https://issues.jboss.org/browse/THREESCALE-3114)
> Fix service discovery cluster endpoint for fetching openshift projects

- app/models/account/provider_methods.rb
- app/models/fields_definition.rb
- db/seeds.rb
- features/support/initial_data.rb
- spec/acceptance/api/account_spec.rb
- spec/acceptance/api/account_user_spec.rb
- spec/acceptance/api/user_spec.rb
- test/unit/db/seeds_test.rb
Closes [THREESCALE-2951](https://issues.jboss.org/browse/THREESCALE-2951)
Things that I don't know how to test:
1. The password
2. The values of `APICAST_ACCESS_TOKEN`, `MASTER_ACCESS_TOKEN` and `ADMIN_ACCESS_TOKEN`
> Raise an error and rollback when the seeds don't seed the DB correctly

- MAINTAINERS
Add `duduribeiro` (AKA me) as Maintainer.
> Add duduribeiro as Maintainer

- app/controllers/api/integrations_controller.rb
- app/lib/backend_api_logic/service_extension.rb
- app/models/service.rb
- app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
- app/views/api/plans/_metrics.html.erb
- db/migrate/20190731092006_add_acts_as_product_to_service.rb
- db/migrate/20190731092338_backfill_add_acts_as_product_to_service.rb
- db/oracle_schema.rb
- db/postgres_schema.rb
- db/schema.rb
Service with boolean to act as product.
1. Migrate Service act_as_product
2. Service code for acts_as_product? uses the new boolean
3. Rename acts_as_product? -> act_as_product? for Service
> [APIAP] Service with field to act as product

- app/views/api/integrations/apicast/shared/_authentication_settings.html.slim
- app/views/api/integrations/apicast/shared/_oidc.html.slim
- app/views/api/integrations/service_mesh/_form.html.slim
- config/locales/en.yml
> display oidc config when istio and oidc are selected

- app/javascript/src/NewService/components/NewServiceForm.jsx
- app/views/api/services/new.html.slim
- spec/javascripts/NewService/NewServiceForm.spec.jsx
* When `service_discovery_accesible?` is `true`:
* When `service_discovery_accesible?` is `false`:
* When `service_discovery_enabled?` is `true`:
> :bug: Hides radio buttons when Service Discovery not accesible

- app/models/cinstance.rb
- app/models/metric.rb
- app/models/service.rb
- lib/archive_deletion_belonging_to_service.rb
- test/unit/cinstance_test.rb
- test/unit/metric_test.rb
- test/unit/service_test.rb
> Rename 'achieve as deleted' -> 'archive ...'

- db/migrate/20190802133303_create_triggers_backend_apis.rb
- db/oracle_schema.rb
- db/postgres_schema.rb
- db/schema.rb
Migration of triggers for tables of backend api
> Migrate Triggers for tables of Backend Api

- db/seeds.rb
So we don't need to have Sidekiq running for development 😄
> [Seeds] Run SignupWorker synchronously for dev env and async otherwise

- app/assets/javascripts/mapping_rules.js
- app/assets/stylesheets/provider/_tables.scss
- app/controllers/provider/admin/backend_apis/metrics_controller.rb
- app/models/proxy_rule.rb
In our current APIAP Base PR there is this in CodeClimate:
Some of them are extremely easy to fix, some of them can even be fixed automatically with `rubocop -a` and `sass-lint-auto-fix`.
This PR intends to fix these very simple CodeClimate issues 😄
> CodeClimate simple cleanup for APIAP Base

- app/lib/backend_api_logic/service_extension.rb
Backend APIs should not be destroyed when a service is destroyed
> [apiap] Fix destruction of backend APIs on Service#destroy

- MAINTAINERS
> adding new maintainers

- docker-compose.mk
We are not ready to remove docker-compose.mk. Putting it back until someone can work on https://github.com/3scale/porta/blob/1ffee4935d9ffb1a2bd025c540f7bca7141531a3/openshift/system/Makefile#L26
> docker-compose.mk back for now

- app/assets/stylesheets/provider/_services.scss
- app/views/api/services/show.html.slim
- app/views/provider/admin/backend_apis/show.html.slim
Improves a bit the list of backends for a service, according to mockups.
> List of used backends in Service

- app/controllers/admin/api/services_controller.rb
- app/controllers/master/api/base_controller.rb
- test/integration/admin/api/services_controller_test.rb
- test/integration/user-management-api/services_test.rb
API side of [THREESCALE-2715](https://issues.jboss.org/browse/THREESCALE-2715)
Conclusions in [this comment](https://issues.jboss.org/browse/THREESCALE-2715?focusedCommentId=13770328&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13770328), I've been very conservative to be safe and I did not allow the ones that I am sure of, and I explained why in the Jira issue so you can see the explanation of each one of the ones I am rejecting 👍
> API Service Update/Create with Strong Params

- app/lib/api_authentication/by_access_token.rb
- app/lib/api_authentication/by_provider_key.rb
- app/lib/api_authentication/by_provider_key_and_buyer_username.rb
- app/lib/api_authentication/by_sso_token.rb
- app/lib/api_authentication/http_authentication.rb
- app/lib/api_authentication/suspended_account.rb
- test/functional/developer_portal/admin/account/account_plans_controller_test.rb
This one moves lib/api_authentication
> Move lib/api_authentication into api/lib/api_authentication

- app/lib/forum_support/admin.rb
- app/lib/forum_support/categories.rb
- app/lib/forum_support/deprecated/admin_paths_helper.rb
- app/lib/forum_support/forums.rb
- app/lib/forum_support/posts.rb
- app/lib/forum_support/public.rb
- app/lib/forum_support/topics.rb
- app/lib/forum_support/user_topics.rb
This one moves lib/forum_support
> Move lib/forum_support to app/lib/forum_support

- app/lib/cms/builtin_pages_support.rb
- app/lib/cms/content_for_store.rb
- app/lib/cms/database_file_system.rb
- app/lib/cms/filtering.rb
- app/lib/cms/s3.rb
- app/lib/cms/semantic_form_builder.rb
- app/lib/cms/settings.rb
- app/lib/cms/sidebar.rb
> Move lib/cms into api/lib/cms

- db/migrate/20190716110520_create_the_backend_apis_of_services.rb
- db/migrate/20190731092338_backfill_add_acts_as_product_to_service.rb
- db/migrate/20190801143259_backfill_proxy_rules_owners.rb
- db/migrate/20190805135829_backfill_metric_owners.rb
- lib/progress_counter.rb
So we have at least a bit of information on how our migration is going
> [lib] Add a counter to long migration

- app/lib/service_discovery/authentication_provider_support.rb
- app/models/authentication_provider.rb
- app/models/authentication_provider/auth0.rb
- app/models/authentication_provider/custom.rb
- app/models/authentication_provider/github.rb
- app/models/authentication_provider/keycloak.rb
- app/models/authentication_provider/redhat_customer_portal.rb
- app/models/authentication_provider/service_discovery_provider.rb
- app/models/authentication_providers/custom.rb
- features/support/transforms.rb
- lib/redhat_customer_portal_support.rb
- test/factories/authentication_provider.rb
- test/integration/admin/api/account/authentication_providers_controller_test.rb
- test/integration/admin/api/authentication_providers_controller_test.rb
- test/unit/account/provider_test.rb
- test/unit/authentication_provider_test.rb
- test/unit/liquid/drops/authentication_provider_drop_test.rb
- test/unit/models_test.rb
- test/unit/presenters/provider_oauth_flow_presenter_test.rb
- test/unit/redhat_customer_portal_test.rb
Reverts 3scale/porta#1087
Missing a migration
> Revert "Rename AuthenticationProvider module to AuthenticationProviders"

- app/controllers/provider/admin/backend_apis_controller.rb
- app/views/provider/admin/backend_apis/edit.html.slim
- app/views/provider/admin/backend_apis/forms/_delete.html.slim
- app/views/provider/admin/backend_apis/forms/_naming.html.slim
- config/abilities/provider_admin.rb
- config/locales/en.yml
- test/integration/provider/admin/backend_apis_controller_test.rb
Implements the edit page for backend APIs
Closes [THREESCALE-3276](https://issues.jboss.org/browse/THREESCALE-3276)
> [apiap] Backend API edit page

- app/controllers/admin/api/services/proxies_controller.rb
- spec/acceptance/api/proxy_spec.rb
> [API] Proxy#api_backend should still be available

- Gemfile.base
- Gemfile.lock
- app/controllers/application_controller.rb
- app/lib/logic/rolling_updates.rb
- config/initializers/browser_modern_rules.rb
- gemfiles/prod/Gemfile.lock
- test/integration/application_controller_test.rb
https://issues.jboss.org/browse/THREESCALE-2632
> [modern browser] logout current user if broswer is not modern

- config/initializers/sidekiq.rb
- lib/tasks/apiap.rake
- lib/three_scale/sidekiq_logging_middleware.rb
> Move ThreeScale::SidekiqLoggingMiddleware to /lib

- app/helpers/vertical_nav_helper.rb
- features/old/menu/api_menu.feature
closes https://issues.jboss.org/browse/THREESCALE-3340
> show methods and metrics for both traditional services and products

- package.json
Bootstrap-sass needs to be updated 
https://issues.jboss.org/browse/THREESCALE-3303
> Updating bootstrap-sass

- app/lib/fields/base_field.rb
- app/lib/fields/builtin_field.rb
- app/lib/fields/extensions.rb
- app/lib/fields/extra_field.rb
- app/lib/fields/extra_fields.rb
- app/lib/fields/fields.rb
- app/lib/fields/form_builder.rb
- app/lib/fields/internal_field.rb
- app/lib/fields/provider.rb
- app/lib/fields/signup_extra_field.rb
- app/lib/fields/signup_form.rb
> Move lib/fields to api/lib/fields

- package.json
> Revert "Updating bootstrap-sass"

- package-lock.json
- package.json
> Revert "Updating css-loader to ^2.1.1"

- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Fixing https://issues.jboss.org/browse/THREESCALE-1451
> Update pisoni gem to 1.27.0

- INSTALL.md
This commit reorganize some topics from the doc and also includes
the instruction on how to setup the application using Fedora (29).
> Add Fedora installation instructions into INSTALL.md

- package-lock.json
- package.json
`swagger-tools` must be updated
https://issues.jboss.org/browse/THREESCALE-3303
> Updating swagger-tools to 0.10.4

- app/controllers/provider/admin/backend_apis/metrics_controller.rb
- app/lib/backend/model_extensions/metric.rb
- app/lib/backend_api_logic/metric_extension.rb
- app/models/backend_api.rb
- app/models/metric.rb
- app/views/provider/admin/backend_apis/metrics/_form.html.slim
- app/views/provider/admin/backend_apis/metrics/edit.html.erb
- app/views/provider/admin/backend_apis/metrics/index.html.slim
- app/views/provider/admin/backend_apis/metrics/new.html.erb
- test/integration/provider/admin/backend_apis/metrics_controller_test.rb
- test/unit/backend_api_logic/metric_extension_test.rb
- test/unit/metric_test.rb
- New/create metric/method
- Edit/update metric/method
- Destroy metric/method
Closes [THREESCALE-3089](https://issues.jboss.org/browse/THREESCALE-3089)
**TODOs**
> Backend API metric UI pages

- app/javascript/src/NewService/components/FormElements/BackendApiSelect.jsx
- app/views/api/integrations/apicast/configuration_driven/_configuration.html.slim
- app/views/api/plans/_metrics.html.erb
- app/views/api/services/show.html.slim
- spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
> Remove 'act_as_product' in favor of rolling update check

- app/controllers/api/metrics_controller.rb
- app/controllers/api/pricing_rules_controller.rb
- app/controllers/api/usage_limits_controller.rb
- app/lib/backend_api_logic/service_extension.rb
- app/models/application_plan.rb
- app/models/backend_api_config.rb
- app/models/end_user_plan.rb
- app/models/usage_limit.rb
- test/unit/backend_api_logic/service_extension_test.rb
Closes [THREESCALE-3348](https://issues.jboss.org/browse/THREESCALE-3348)
> Fix links to actions over backend API metrics on app plan page (THREESCALE-3348)

- app/models/service.rb
- app/views/api/metrics/_backend_api.erb
- app/views/api/metrics/_top_level.html.erb
- app/views/api/plans/_metrics.html.erb
Closes [THREESCALE-3408](https://issues.jboss.org/browse/THREESCALE-3408)
----
Before:
After:
> Show all methods and metrics of a product in app plan edit page

- spec/javascripts/LoginPage/FormGroup.spec.jsx
- spec/javascripts/LoginPage/RequestPasswordForm.spec.jsx
- spec/javascripts/LoginPage/SignupPageWrapper.spec.jsx
- spec/javascripts/Navigation/ActiveMenuTitle.spec.jsx
- spec/javascripts/NewService/formElements/BackendApiSelect.spec.jsx
Some errors popping up since #1050 was merged
> Fix lint errors

- config/examples/database.yml
- openshift/system/config/database.yml
Fixes OCIError: ORA-01805: possible error in date/time
It is reproducible by setting local Timezone to +05:00 for example
Then run the application locally
> Closes THREESCALE-2485

- app/assets/stylesheets/provider/admin/_dashboard.scss
Align New Product/New Backend link with search input in Dashboard
https://issues.jboss.org/browse/THREESCALE-3359
**Before:**
*After:**
> Align New Product/New Backend link with search input

- Makefile
Closes [THREESCALE-3262](https://issues.jboss.org/browse/THREESCALE-3262)
> Removing the make test command

- test/integration/api_docs/services_controller_test.rb
This way it tests all APIAP new API endpoints dynamically 😄 
It was originally part of https://github.com/3scale/porta/pull/1184 but that PR is too big now and everything that can be extracted to other PRs, better to do so 😄
> Refactor Test ApiDocs only show APIAP with RU enabled (to be dynamic)

- app/models/metric.rb
- app/representers/metric_links_representer.rb
- app/views/api/metrics/toggle_enabled.js.erb
- app/views/api/metrics/toggle_limits_only_text.js.erb
- app/views/api/metrics/toggle_visible.js.erb
> [Refactor] is_a_method? -> method_metric?

- app/controllers/admin/api/backend_apis/metrics_controller.rb
- app/controllers/admin/api/metrics_controller.rb
- app/representers/backend_api_representer.rb
- app/representers/metric_links_representer.rb
- app/representers/metric_representer.rb
- config/routes.rb
- doc/active_docs/Account Management API.json
- spec/acceptance/api/backend_api_spec.rb
- test/integration/admin/api/backend_apis/metrics_controller_test.rb
Part of [THREESCALE-3209](https://issues.jboss.org/browse/THREESCALE-3209)
Done like we do for metrics of services.
Methods in another PR in https://github.com/3scale/porta/pull/1201 because otherwise this one would be over 1000 lines 😄 
Remember that you need the rolling update called `api_as_product` enabled to be able to test this locally in `{{your-url}}/p/admin/api_docs`
- Request: `curl -v  -X GET "http://provider-admin.example.com.lvh.me:3000/admin/api/backend_apis/2/metrics.json?access_token=2793672eac7366b9e9502de4188d0f40f1b6a3e5144fdc1c3617ad7d3646eae7"`
- Response:
```json
{
"metrics": [
{
"metric": {
"id": 7,
"system_name": "hits.2",
"friendly_name": "Hits",
"description": "Number of API hits",
"unit": "hit",
"created_at": "2019-09-17T21:17:25Z",
"updated_at": …
```
> [API Endpoints] Metrics under Backend API

- features/old/accounts/accounts.feature
- features/old/accounts/invitations.feature
- features/old/accounts/invoices.feature
- features/old/accounts/notifications.feature
- features/old/accounts/personal_details.feature
- features/old/accounts/service_contracts.feature
- features/old/accounts/users.feature
- features/old/api/end_users.feature
- features/old/api/usage_limits.feature
- features/old/applications/buyers/alerts.feature
- features/old/applications/buyers/application_management.feature
- features/old/applications/providers/application_plan.feature
- features/old/applications/providers/search.feature
- features/old/authorization/provider_settings.feature
- features/old/buyers/accounts/searching.feature
- features/old/buyers/invitations/for_admins.feature
- features/old/buyers/users.feature
- features/old/finance/invoices/create_invoice.feature
- features/old/finance/invoices/line_items.feature
- features/old/menu/account_menu.feature
- features/old/menu/audience_menu.feature
- features/old/messages/buyer_side.feature
- features/old/messages/provider_side.feature
- features/old/site/payment_details.feature
- features/old/switches/finance.feature
- features/provider/integration/edit.feature
- features/step_definitions/buyers_management/user_steps.rb
- features/step_definitions/finance/invoicing_steps.rb
- features/step_definitions/plans/plans_steps.rb
- features/step_definitions/web_steps.rb
And in CircleCI it fails particularly [in Oracle](https://circleci.com/gh/3scale/porta/100521#tests/containers/20) 🤷‍♀ 
Just run locally `DATABASE_URL="oracle-enhanced://rails:railspass@127.0.0.1:1521/systempdb" bundle exec cucumber features/old/cms/advanced/groups_and_sections.feature:25` 😄 
But anyway you can see the results in CircleCI in this same PR 👍
> [Bugfix] Cuke Feature cms/advanced/groups_and_sections

- app/controllers/admin/api/backend_apis/metric_methods_controller.rb
- app/controllers/admin/api/backend_apis/metrics_controller.rb
- app/controllers/admin/api/base_controller.rb
- app/controllers/admin/api/metric_methods_controller.rb
- app/representers/method_representer.rb
- app/representers/metric_links_representer.rb
- config/routes.rb
- doc/active_docs/Account Management API.json
- test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
- test/integration/admin/api/backend_apis/metrics_controller_test.rb
Continuation of https://github.com/3scale/porta/pull/1184 and this PR depends on that one.
Part of [THREESCALE-3209](https://issues.jboss.org/browse/THREESCALE-3209)
- Request: `curl -v  -X POST "http://provider-admin.example.com.lvh.me:3000/admin/api/backend_apis/2/metrics/7/methods.json" -d 'access_token=e46d99f8b306adcc18922033ad4f50d0f0a30eee0598b08bd40f59c376e2ba43&friendly_name=friendly+method+1&unit=hit'`
- Response:
```json
{
"method": {
"id": 8,
"system_name": "friendly_method_1.2",
"friendly_name": "friendly method 1",
"created_at": "2019-09-19T18:41:16Z",
"updated_at": "2019-09-19T18:41:16Z",
"links": [
{
"rel": "parent",
"href": "http://provider-admin.example.com/admin/api/backend_apis/2/metrics/7"
},
{
"rel": "self",
"href": …
```
> [API Endpoints] Metric Methods under Backend API

- app/lib/backend_api_logic/routing_policy.rb
- test/unit/backend_api_logic/routing_policy_test.rb
- test/unit/proxy_test.rb
Closes [THREESCALE-3489](https://issues.jboss.org/browse/THREESCALE-3489)
> replace_path property in the routing policies injected for backend APIs

- app/lib/active_record/type/string_not_nil.rb
- app/models/backend_api_config.rb
- test/unit/lib/type_string_not_nil_test.rb
> Cast nil values to empty string

- app/controllers/admin/api/backend_apis/base_controller.rb
- app/controllers/admin/api/backend_apis/mapping_rules_controller.rb
- app/controllers/admin/api/backend_apis/metric_methods_controller.rb
- app/controllers/admin/api/backend_apis/metrics_controller.rb
- app/controllers/admin/api/base_controller.rb
- app/controllers/admin/api/services/mapping_rules_controller.rb
- app/models/proxy_rule.rb
- app/representers/backend_api_representer.rb
- app/representers/proxy_rule_representer.rb
- config/routes.rb
- doc/active_docs/Account Management API.json
- spec/acceptance/api/backend_api_spec.rb
- test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb
- test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
- test/integration/admin/api/backend_apis/metrics_controller_test.rb
Closes [THREESCALE-3208](https://issues.jboss.org/browse/THREESCALE-3208)
The response now contains the link to its mapping rules.
The names in the documentation let clear that they belong to a Proxy.
- Request: `curl -v  -X POST "http://provider-admin.example.com.lvh.me:3000/admin/api/backend_apis/2/mapping_rules.json" -d 'access_token=e46d99f8b306adcc18922033ad4f50d0f0a30eee0598b08bd40f59c376e2ba43&http_method=POST&pattern=%2F&delta=3&metric_id=7&position=4&last=true'`
- Response:
```json
{
"mapping_rule": {
"id": 4,
"metric_id": 7,
"pattern": "/",
"http_method": "POST",
"delta": 3,
"position": 4,
"last": true,
"created_at": "2019-09-21T09:09:33Z",
"updated_at": "2019-09-21T09:09:33Z",
"links": [
{
"rel": "self",
"href": "/admin/api/backend_apis/2/mapping_rules/4"
},
{
"rel": …
```
> [API Endpoints] Mapping Rules under Backend API

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Issue https://github.com/deivid-rodriguez/pry-byebug/issues/69 is fixed in
https://github.com/deivid-rodriguez/pry-byebug/pull/142
> Add pry-byebug back

- app/models/backend_api_config.rb
- features/old/menu/api_menu.feature
- features/step_definitions/provider_steps.rb
- test/models/backend_api_config_test.rb
Improvements for https://github.com/3scale/porta/pull/1156
> [Refactor] Rename cuke step for RU act_as_product + Improve scope BackendApiConfig.with_subpath

- app/controllers/api/services_controller.rb
- app/controllers/frontend_controller.rb
- app/helpers/services_helper.rb
- app/helpers/vertical_nav_helper.rb
- app/views/api/services/forms/_integration_settings_apiap.html.slim
- app/views/api/services/settings_apiap.html.slim
- config/locales/en.yml
- features/old/api/plans/service_plans.feature
- features/old/api/settings.feature
- features/step_definitions/rolling_updates_steps.rb
- test/functional/api/services_controller_test.rb
- test/integration/api/services_controller_test.rb
This is the first iteration of the unified integration settings
Partially fixes https://issues.jboss.org/browse/THREESCALE-3451
TODO
This includes:
* Deployment options
* Authentication just the auth methods selection, missing its settings
> Integration Settings part 1

- app/javascript/packs/settings.js
- app/javascript/src/Settings/authentication-widget.jsx
- app/javascript/src/Settings/styles/authentication.scss
- app/views/api/services/forms/_authentication_settings.html.slim
- app/views/api/services/forms/_integration_settings_apiap.html.slim
- app/views/api/services/forms/_oidc.html.slim
This needs to be merge after https://github.com/3scale/porta/pull/1229
This is the second iteration of the unified integration settings
Partially fixes https://issues.jboss.org/browse/THREESCALE-3451
TODO
> Integration Settings part 2

- app/controllers/api/integrations_controller.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
- app/views/api/integrations/apicast/shared/_deployment_options.html.slim
- features/old/api/settings.feature
This needs to be merge after #1229
This is the third iteration of the unified integration settings, hides the old configuration settings
Partially fixes https://issues.jboss.org/browse/THREESCALE-3451
Verification steps
TODO
Special notes for your reviewer:
> Integration Settings part 3

- app/javascript/packs/settings.js
- app/javascript/src/Settings/authentication-widget.jsx
- app/javascript/src/Settings/styles/authentication.scss
- app/views/api/services/forms/_authentication_settings.html.slim
- app/views/api/services/forms/_integration_settings_apiap.html.slim
- app/views/api/services/forms/_oidc.html.slim
This PR never made it to master, and it needs to be.
https://github.com/3scale/porta/pull/1238
> Threescale 3451/integration settings 2

- app/controllers/api/integrations_controller.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
- app/views/api/integrations/apicast/shared/_deployment_options.html.slim
- features/old/api/settings.feature
This one too: https://github.com/3scale/porta/pull/1242
> Threescale 3451/integration settings 3

- app/views/api/backend_api_configs/index.html.slim
Suggested by @mkudlej at https://issues.jboss.org/browse/THREESCALE-3321?focusedCommentId=13789306&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13789306.
> Links to backend api configs in the index

- test/unit/event_store/event_test.rb
Closes [THREESCALE-2269](https://issues.jboss.org/browse/THREESCALE-2269)
It is not nice having to rerun tests just for this :expressionless: :stuck_out_tongue_closed_eyes: 
The problem could be (guessing) either the 'return' (although I don't think so!) or the comparing timestamps that don't even have a second of difference, so there could be a difference of miliseconds.
I hope this fixes it :woman_shrugging: and worse case scenario, nothing breaks anyway :smile: we know that the `stale` method actually works which is what this means to to test :dancer:
> [Bugfix] [Random test failure] test_stale (EventStore::EventTest) {Expected: X, Actual: Y}

- app/models/account.rb
- app/models/cinstance.rb
- app/models/concerns/counter_cache_callbacks.rb
- app/models/contract.rb
- app/models/plan.rb
- test/unit/abilities/provider_member_test.rb
- test/unit/plan_test.rb
> Replace this comment with references to related issues. This will ensure the issue(s) are closed automatically when the PR gets merged.
> e.g. `fixes #<issue number>(, fixes #<issue_number>, ...)`
> [plan] manual counter cache

- app/controllers/admin/api/backend_apis_controller.rb
- app/controllers/admin/api/base_controller.rb
- app/controllers/admin/api/services/backend_api_configs_controller.rb
- app/controllers/admin/api/services/base_controller.rb
- app/models/backend_api_config.rb
- app/representers/backend_api_config_representer.rb
- app/representers/backend_api_configs_representer.rb
- config/routes.rb
- doc/active_docs/Account Management API.json
- test/integration/admin/api/services/backend_api_configs_controller_test.rb
- test/integration/api_docs/services_controller_test.rb
Closes [THREESCALE-3207 - [API Endpoints] Backend API Configs CRUD](https://issues.jboss.org/browse/THREESCALE-3207
)
- Request: `curl -v  -X POST "http://provider-admin.example.com.lvh.me:3000/admin/api/services/2/backend_apis.json" -d 'access_token=04bddce348f2445c48640ef0918e04b05988c662ae945f0c3aa91ede88b1b7db&backend_api_id=2&path=%2Ffoo'`
- Response:
```json
{
"path": "foo",
"links": [
{
"rel": "service",
"href": "http://provider-admin.example.com/admin/api/services/2"
},
{
"rel": "backend_api",
"href": "http://provider-admin.example.com/admin/api/backend_apis/2"
}
]
}
```
- Request: `curl -v  -X GET "http://provider-admin.example.com.lvh.me:3000/admin/api/services/2/backend_apis.json?access_token=04bddce348f2445c48640ef0918e04b05988c662ae945f0c3aa91ede88b1b7db"`
- Response:
```json …
```
> [API Endpoints] Backend API Configs

- app/javascript/src/Settings/authentication-widget.jsx
- app/views/api/services/forms/_authentication_settings.html.slim
- app/views/api/services/forms/_integration_settings_apiap.html.slim
- app/views/api/services/forms/_oidc.html.slim
This is the final part of the integration settings
Fixes https://issues.jboss.org/browse/THREESCALE-3559
Notes for reviewers:
* This needs to be migrated to React component
* Needs a cuke
> [settings] Auth settings behaviour updated

- app/javascript/src/Settings/authentication-widget.jsx
- app/views/api/services/forms/_authentication_settings.html.slim
Auth settings are shown correctly due integration methods.
Part of https://issues.jboss.org/browse/THREESCALE-3451
* TODO: THIS NEEDS TO BE A REACT COMPONENT. Current implementation is ugly af.
> [settings] Adapted behaviour for OIDC and MESH integration

- lib/tasks/openshift.rake
`openshift:thinking_sphinx:start` rake task broke after we upgraded thinking_spinx from v3.2.0 to v3.4.2: https://github.com/3scale/porta/pull/1239/files#diff-33c867a743c81c1ce1e040ecbb221d39. The reason is because thinking_sphinx changed the API of `ThinkingSphinx::RakeInterface`: https://github.com/pat/thinking-sphinx/compare/v3.2.0...v3.4.2#diff-ec2634b6fd4c4a7faecb98d523a7026e
This is causing `system-sphinx` pod to loop crash on container initialization after throwing the following exception:
```
rake aborted!
NoMethodError: undefined method `stop' for #<ThinkingSphinx::RakeInterface:0x0000000008c12430>
/opt/system/lib/tasks/openshift.rake:40:in `block (3 levels) in <top (required)>'
/opt/system/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bu …
```
> Fix sphinx start/stop/index commands for openshift

- app/javascript/src/Onboarding/Bubble.jsx
[THREESCALE-2724: Onboarding Bubble has a typo](https://issues.jboss.org/browse/THREESCALE-2724)
> Fixes typo "though" -> "through"

- app/models/proxy_config_affecting_change.rb
Closes [THREESCALE-3570](https://issues.jboss.org/browse/THREESCALE-3570)
> ProxyConfigAffectingChange touches the proxy

- app/models/proxy_rule.rb
Closes [THREESCALE-3569](https://issues.jboss.org/browse/THREESCALE-3569)
> Scope ProxyRule's acts_as_list by owner

- app/controllers/api/backend_api_configs_controller.rb
- app/controllers/api/policies_controller.rb
- app/helpers/vertical_nav_helper.rb
- app/models/service.rb
- features/old/menu/api_menu.feature
Hide and unauthorize policies or backends when service can't use them
> APIAP only works with APIcast V2

- app/views/api/services/settings_apiap.html.slim
~`Update Service`~ -> `Update Product`
Only for APIAP.
> Change settings update button title

- .circleci/config.yml
Fixes [THREESCALE-3589 - NoMethodError: undefined method `match?' for "\"4\"":String](https://issues.jboss.org/browse/THREESCALE-3589)
> CircleCI with Ruby 2.4

- app/models/account/provider_methods.rb
- lib/signup/provider_account_manager.rb
- test/integration/admin/api/backend_apis_controller_test.rb
- test/integration/api/backend_api_configs_controller_test.rb
- test/integration/provider/admin/backend_apis_controller_test.rb
- test/unit/db/seeds_test.rb
- test/unit/service_test.rb
- test/unit/signup/account_manager_test.rb
Closes [THREESCALE-3580](https://issues.jboss.org/browse/THREESCALE-3580)
Alternative to https://github.com/3scale/porta/pull/1280.
> Create first backend api of every tenant

- test/integration/api/backend_api_configs_controller_test.rb
Fixes [these tests](https://circleci.com/gh/3scale/porta/113726#tests/containers/5).
> Fix Oracle Tests for the UI Controller of BackendApiConfigs

- app/controllers/api/services_controller.rb
- app/services/api_integration/settings_updater_service.rb
- test/unit/services/api_integration/settings_updater_service_test.rb
> Rename SettingsResult -> SettingsUpdaterService

- features/api/services/settings.feature
- features/old/api/plans/service_plans.feature
- features/old/api/settings.feature
- features/old/menu/dashboard.feature
- features/step_definitions/custom_web_steps.rb
- features/step_definitions/rolling_updates_steps.rb
Test coverage is good.
fixes https://issues.jboss.org/browse/THREESCALE-3636
**Notes to reviewer**
I know it's a simplistic way to test this feature, BUT the new integration settings page will be refactor to a React component and will be fully tested. This is just testing the overall feature and user interaction.
> [cuke] New Integration Settings

- app/controllers/api/services_controller.rb
- app/services/api_integration/settings_updater_service.rb
- config/locales/en.yml
- features/old/services/multiservice.feature
- test/integration/api/services_controller_test.rb
- test/unit/services/api_integration/settings_updater_service_test.rb
Closes [THREESCALE-3640](https://issues.jboss.org/browse/THREESCALE-3640)
> Fix integration settings update no-op for proxy params

- app/lib/proxy_config_affecting_changes.rb
- test/unit/proxy_test.rb
Closes [THREESCALE-3651](https://issues.jboss.org/browse/THREESCALE-3651)
> Fix ProxyConfigAffectingChange race condition

- app/assets/stylesheets/provider/_flash.scss
closes https://issues.jboss.org/browse/THREESCALE-3335
> flash message vertical positioning at top

- app/services/api_integration/settings_updater_service.rb
- lib/tasks/data_migration/fix_backend_config_path.rake
- test/unit/tasks/data_migration/fix_backend_config_path_test.rb
fix_backend_config_path Rake task has .rake extension and make it dependend on environment
> Fix rake task fix_backend_config_path

- app/assets/stylesheets/provider/_forms.scss
- app/helpers/api/integrations_helper.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
- test/functional/api/integrations_controller_test.rb
- test/unit/helpers/api/integrations_helper_test.rb
~~make more clear when staging is out of date~~
wip:
> test curl command + other UI improvements in the proxy config page

- app/workers/delete_object_hierarchy_worker.rb
- test/workers/delete_object_hierarchy_worker_test.rb
Closes [THREESCALE-3779](https://issues.jboss.org/browse/THREESCALE-3779)
> AssociationUnknownPrimaryKey is not raised and the object is removed

- app/assets/stylesheets/provider/_finance.scss
Invoice in admin is not readable.
https://issues.jboss.org/browse/THREESCALE-3791
> [invoice] word break normal

- app/controllers/api/integrations_controller.rb
Render `:show` instead of `:edit` in APIAP.
Redirect to `:show` instead whenever the controller goes to `:edit`.
Normally when navigating to `/edit` an error 404 is thrown, that is not changed.
[THREESCALE-3788: Failing promotion to staging brings user to config edit page](https://issues.jboss.org/browse/THREESCALE-3788)
1. Go to `apiconfig/services/<service_id>/integration`
2. Try to promote in a way that it fails 😅
3. It should not redirect to the config edit page
> Redirect to show when promotion to Staging fails

- app/controllers/admin/api/backend_apis_controller.rb
- doc/active_docs/Account Management API.json
> [api] Add system_name to Backend API swagger

- app/helpers/api/integrations_helper.rb
- app/helpers/proxy_rules_helper.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
Proposed in https://github.com/3scale/porta/pull/1376#pullrequestreview-307712694
> Link to the proxy rules index page in the proxy config show

- app/helpers/api/integrations_helper.rb
- app/helpers/proxy_rules_helper.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
It was merged into a dead branch in https://github.com/3scale/porta/pull/1379.
> Link to the proxy rules index page in the proxy config show page

- app/views/buyers/applications/_listing.html.slim
- app/views/buyers/service_contracts/index.html.slim
closes https://issues.jboss.org/browse/THREESCALE-1001
> show search account string in input fields (applications and subscriptions)

- app/controllers/api/proxy_configs_controller.rb
Closes [THREESCALE-3832](https://issues.jboss.org/browse/THREESCALE-3832)
----
_Before:_
_After:_
> Fix selected sidebar vertical nav for configuration history

- config/locales/en.yml
closes https://issues.jboss.org/browse/THREESCALE-3848
> new doc links

- app/lib/stats/base.rb
- test/unit/stats/base_test.rb
Closes [THREESCALE-3896](https://issues.jboss.org/browse/THREESCALE-3896)
> Fix Stats::Base metrics

- package-lock.json
Fixing handlebars vulnerability issue
> Fixing handlebars vulnerability issue

- app/controllers/api/services_controller.rb
- config/locales/en.yml
- test/integration/api/services_controller_test.rb
> Automatically fetch model error message when fails to create service

- app/controllers/api/services_controller.rb
- app/javascript/src/NewService/components/FormElements/ServiceManualListItems.jsx
- app/javascript/src/NewService/components/NewServiceForm.jsx
- app/javascript/src/NewService/components/ServiceManualForm.jsx
- app/javascript/src/NewService/types/index.js
- app/presenters/service_presenter.rb
- app/views/api/services/new.html.slim
- config/locales/en.yml
- features/old/services/multiservice.feature
- features/step_definitions/flash_steps.rb
- spec/javascripts/NewService/NewServiceForm.spec.jsx
- spec/javascripts/NewService/ServiceManualForm.spec.jsx
- spec/javascripts/NewService/formElements/ServiceManualListItems.spec.jsx
- spec/javascripts/NewService/formElements/__snapshots__/ServiceManualListItems.spec.jsx.snap
- test/integration/api/services_controller_test.rb
**BEFORE**
**AFTER**
It was showing misleading error messages when creating a new Service/Product.
fixes https://issues.jboss.org/browse/THREESCALE-3394
1. Browse to the Dashboard and click on "NEW API / NEW PRODUCT".
2. Use the following sample fields:
```
Name: Invalid API
System name: I am using spaces
Description: Invalid API
```
3. Click in "Add API / Create Producte".
> Service create error messages

- spec/javascripts/Settings/components/Common/__snapshots__/SelectGroup.spec.jsx.snap
Try to fix JS CircleCI jest by doing `npm run jest -- -u` locally :smile:
> JS Snapchot got SelectGroup spec auto-generated

- app/lib/payment/abstract_errors_handler.rb
- app/lib/payment/adyen12_errors_handler.rb
- app/lib/payment/braintree_blue_errors_handler.rb
Extracted from #1396
In order to remove the lib folder from autoload, this commit moves the
lib/payment into app/lib
> Move lib/payment into app/lib

- package-lock.json
- package.json
Updating @rails/webpacker to fix some npm vulnerability issues
```
rm --rf node_modules
npm install
```
> Updating @rails/webpacker to fix vulnerability issues

- Makefile
Those targets should depend on dev-setup
and dev-setup should use db:deploy instead of db:setup
> [Makefile] make bash and make dev-start fix

- features/api/services/settings.feature
- features/step_definitions/settings_steps.rb
Adds new 🥒 features.
[THREESCALE-3762: Create cucumber feature for Apicast custom URLs in Settings](https://issues.redhat.com/browse/THREESCALE-3762)
Tests should pass.
> Add tests for deployment settings

- app/assets/stylesheets/provider/_vertical_nav.scss
- app/javascript/src/Navigation/components/PF4NavProxy.jsx
- app/javascript/src/patternflyStyles/pf4BaseIE11.scss
- app/views/shared/provider/navigation/_vertical_nav.html.slim
- package-lock.json
Updated vertical nav to be dark nav.
> Updated with dark nav 

- app/controllers/application_controller.rb
User is not being logout in `ApplicationController#check_browser`
https://issues.redhat.com/browse/THREESCALE-2632
> [ApplicationController#check_browser] destroy user session

- app/lib/cms/s3.rb
- config/application.rb
- config/docker/amazon_s3.yml
- openshift/system/config/amazon_s3.yml
Closes [THREESCALE-4052](https://issues.redhat.com/browse/THREESCALE-4052)
> AWS S3 hostname and protocol config options

- app/lib/cms/s3.rb
Closes [THREESCALE-4229](https://issues.redhat.com/browse/THREESCALE-4229)
> Hotfix AWS S3 new configs

- app/workers/backend_metric_worker.rb
- test/workers/backend_metric_worker_test.rb
Reverts 3scale/porta#1516
Closes [THREESCALE-4227](https://issues.redhat.com/browse/THREESCALE-4227)
> Revert "Sparse BackendMetricWorker retries by 5 minutes from each other"

- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Upgrade kgio gem from 2.10.0 to 2.11.3
> Upgrade kgio gem from 2.10.0 to 2.11.3

- Gemfile.base
> Removing mri_23 - mri_25
We do not have nay open issue for this.
Adding WIP as in case, there are more ruby 2.3 related stuff which needs to be removed, we can do it on the same PR.
> Removing platform mri 2.3

- .circleci/config.yml
- Dockerfile
Set it where needed instead .circleci/config.yml instead
Makes more community friendly, otherwise everything is running as test if not unset
> [Dockerfile] Do not set RAILS_ENV in the Dockerfile

- lib/developer_portal/lib/liquid/template/fallback_resolver.rb
- lib/developer_portal/lib/liquid/template/resolver.rb
> [Rails 5] find_templates 5th argument is optional

- app/models/web_hook/event.rb
- app/subscribers/after_commit_subscriber.rb
> [Rails 5] before_committed! for AfterCommitSubscriber

- app/models/system_operation.rb
Extracted from rails-5.0 branch
> [rails-5.0] scoped method in relation should be public

- .circleci/config.yml
- .flowconfig
- app/javascript/src/Types/libs/libdefs.js
- config/webpack/production.js
- config/webpack/test.js
- config/webpacker.yml
- doc/dependency_decisions.yml
- features/old/liquid/active_docs.feature
- karma.conf.js
This PR Fixes a couple of error related to CircleCi and its resources. Also, speed up the building process and assets management.
fixes https://issues.redhat.com/browse/THREESCALE-4309
> Swagger ui 3 fix attempt

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
See https://github.com/mislav/will_paginate/commit/2f0b4694b3cc7ffcb265daad13eb95c972fa0bb1
> [Rails 5] Update will_paginate to fix find_last(*args)

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Upgrade some gems to prepare for Rails5
Migrated:
56e255e
453ef8c
4603dde
> [Rails5] Upgrade gems for rails5

- test/workers/delete_plain_object_worker_test.rb
Because ActiveJob really pushes to the Sidekiq queue, it happens a race condition.
The test finished but the job did not run.
> [WIP][Rails 5][test] Fix enqueuing with ActiveJob for DeletePlainObjectWorker

- test/integration/admin/cms/switches_controller_test.rb
Test for JavaScript cms switch
> [Rails5] [TEST] javascript cms switch

- .circleci/config.yml
- config/webpack/production.js
- config/webpack/test.js
- config/webpacker.yml
- karma.conf.js
- lib/developer_portal/lib/liquid/filters/rails_helpers.rb
- lib/tasks/assets.rake
- lib/tasks/webpack.rake
#1524 for some reason makes CircleCI fail miserably. This PR contains a set of changes to fix it.
This unblocks #1594 and #1595 which fix:
[THREESCALE-2725: Start using SwaggerUI 3.18.3 or higher for OAS3 specs](https://issues.redhat.com/browse/THREESCALE-2725)
IMPORTANT:
Once this is merged, it's important to note that this other one needs to be merge https://github.com/3scale/deploy/pull/637in order to be able to deploy(either preview or production)
Also, this PR will decrease build time considerably. 👍
> Fix CircleCI javascript_build errors

- app/lib/api_support/params.rb
Extracted from https://github.com/3scale/porta/pull/4/commits/5c5de4aaab047dbe993b8dd66884fed0710dbd52
> [Rails 5] Use ActionController::Parameters for parameters comparison

- app/models/fields_definition.rb
Extracted from https://github.com/3scale/porta/pull/4/commits/d6888683038f8a7c16b3868a0793da73d6bed2d8
> [Rails 5] FieldsDefinition only_choices_for_text

- app/lib/logic/provider_settings.rb
Extracted: eb4d267c
It was working on Rails 4.2
Fix it by using conditional
> ActiveRecord::Relation#merge(nil) raises an error

- app/models/application_key.rb
- test/unit/application_keys_test.rb
Extracted: 07bd1431
Refactor scope `without`
> [Rails5] Fix ApplicationKey::without scope

- app/controllers/admin/api/services/proxy/policies_controller.rb
- app/lib/three_scale/api/responder.rb
- app/workers/billing_worker.rb
Extract:
81f9a9fd
b8ac7418
13fd8666
> [Rails5] Apply some fixes

- app/lib/finance/billing.rb
- config/locales/en.yml
Add an error if the Line Item type is wrong
> [Rails5] Fix Line Item wrong type

- app/lib/three_scale/filter_arguments.rb
- config/initializers/audited_hacks.rb
- config/initializers/bugsnag.rb
- config/initializers/sidekiq.rb
- lib/three_scale/sidekiq_retry_support.rb
Extracted:
60437527
19d3251d
f58e01df
> [Rails5] Fix initializers for rails5

- app/javascript/src/Settings/authentication-widget.jsx
1. Enable APIAP
2. Go to Service>Settings
3. Select different authentication methods, no error should pop up. Things should hide/show accordingly.
> Fix Service Settings' null pointer exception

- test/test_helpers/backend.rb
Since login means going to dashboard and displaying integration errors widget
> [Rails 5] Mock ThreeScale:::Core::ServiceError

- app/helpers/api/integrations_helper.rb
- app/views/api/integrations/apicast/configuration_driven/_apicast.html.slim
- test/functional/api/integrations_controller_test.rb
closes https://issues.redhat.com/browse/THREESCALE-4399
> keep version to promote in button

- app/models/application_plan.rb
Extracted:
250c83f7
Change scope to use id instead of the object
> Fix acceptance spec for plans

- test/integration/admin/api/accounts_controller_test.rb
- test/integration/admin/api/backend_apis/mapping_rules_controller_test.rb
- test/integration/admin/api/backend_apis/metric_methods_controller_test.rb
- test/integration/admin/api/backend_apis/metrics_controller_test.rb
- test/integration/admin/api/backend_apis_controller_test.rb
- test/integration/admin/api/services/backend_usages_controller_test.rb
- test/integration/provider/admin/cms/layouts_test.rb
- test/unit/concerns/background_deletion_test.rb
Extracted: 9f44b16f
But inflect cms to CMS
We are mistaken if we write Admin::API
It should be Admin::Api
On the other hand  Provider::Admin::CMS is the correct
> Fix not inflected admin/api

- app/lib/three_scale/api/responder.rb
- test/integration/admin/api/account_plans_controller_test.rb
> [Rails5] Fix account_plan_spec.rb related to controller.stale?

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
Extracted: 4192c679
Lock sidekiq version
> Lock sidekiq to ~> 4.2

- config/examples/database.yml
Please review it very carefully.
Extracted from the Rails 5 PR.
> [Rails 5][config] Increase database pool to 25 or use RAILS_MAX_THREADS env

- app/lib/csv/exporter.rb
> Require 'csv' on file using it

- Makefile
- docker-compose.yml
- Adds volume to keep assets and node_modules
- Remove RAILS_ENV=development to allow all db creation
- Remove unused targets
> [Makefile] Produce reproducible docker-compose

- app/models/cms/email_template.rb
- test/unit/cms/email_template_test.rb
Fixes [THREESCALE-4467](https://issues.redhat.com/browse/THREESCALE-4467)
Alternative to https://github.com/3scale/porta/pull/1678
I think we are only fixing this bug but not fixing the root cause of the bug
We should pass Hash or HashWithIndifferentAccess to options and deprecate the usage of ActionController::Parameters
But that means, we need to make to cleanup the Database  ....
> [hotfix] Allow ActionController::Parameters for email template heades

- db/oracle_schema.rb
- db/postgres_schema.rb
- db/schema.rb
> Update schema files based on latest versions of the gems

- config/webpack/production.js
- config/webpack/test.js
Deploying with the latest changes was taking a lot of time due webpack compiling assets. This is an attempt to speed up that process.
Coming soon
deploy to preview/production, it should not take 30' but around 10'
> Speed up lazy webpack

- app/lib/apicast/proxy_rules_source.rb
- test/unit/apicast/proxy_rules_source_test.rb
> [fix] Proxy Rules parameters and querystring_parameters in ProxyConfig

- app/views/buyers/applications/_listing.html.slim
rectifying syntactical error of span tag
fixes #=4310
Follow this flow - Audience > Applications > Listing
Click the multi selector.
You'll see a space between the number of applications and the term applications, which was missing before
> fixing span tag syntax

- gemfiles/prod/Gemfile.lock
> Corrupted gemfiles/prod/Gemfile.lock

- app/controllers/admin/api/services/proxies_controller.rb
- app/controllers/admin/api/services/proxy/policies_controller.rb
- app/controllers/api/integrations_controller.rb
- app/forms/onboarding/request_form.rb
- app/models/proxy.rb
- app/services/apicast_v1_deployment_service.rb
- app/services/proxy_deployment_service.rb
- app/workers/proxy_deployment_worker.rb
- test/functional/api/integrations_controller_test.rb
- test/functional/provider/admin/onboarding/wizard/request_controller_test.rb
- test/integration/api/integrations_controller_test.rb
- test/integration/user-management-api/services/proxies_test.rb
- test/unit/forms/onboarding/request_form_test.rb
- test/unit/proxy_test.rb
- test/unit/services/apicast_v1_deployment_service_test.rb
- test/unit/services/proxy_deployment_service_test.rb
Goes after #1469
[THREESCALE-3751: Tech-Debt: Create a Proxy Deployment Service](https://issues.jboss.org/browse/THREESCALE-3751)
Everything should work the same.
> New Deployment Service for Proxy

- test/unit/finance/billing_strategy_test.rb
- test/unit/mailers/post_office_test.rb
> Fix random test failures

- CONTRIBUTING.md
- app/models/finance/prepaid_billing_strategy.rb
issues.jboss.org has migrated to issues.redhat.com
> Fix JIRA links, migrated to issues.redhat.com

- Gemfile.base
- Gemfile.lock
- gemfiles/prod/Gemfile.lock
* MySQL 8.0 support
* Rails 5.x+ support
See https://github.com/brianmario/mysql2/tree/982dbdb1d521c668547cfd4ab927558c689b8bfd#compatibility
Closes THREESCALE-2012
> [gem] Update to mysql2 0.5.3

- app/models/cinstance.rb
- test/unit/alert/alert_methods_test.rb
Closes https://issues.jboss.org/browse/THREESCALE-3904
> Find the metric generated by an alert on BackendApi metric

- portafly/src/index.tsx
- portafly/tsconfig.json
> [portafly] Fix tsconfig baseUrl path

- lib/developer_portal/config/routes.rb
This route is deprecated in rails 5.2
Lets just already remove it
> [routes] Fix routing deprecation

- app/models/application_key.rb
- test/unit/application_keys_test.rb
As the title says 😄 Related to [THREESCALE-3733](https://issues.redhat.com/browse/THREESCALE-3733)
> Do not audit ApplicationKey#value

- .circleci/config.yml
- Gemfile.base
- Gemfile.prod
- Gemfile.prod.lock
- Makefile
- openshift/system/Dockerfile
We planned to have our Gemfile.prod.lock automatically updated by circleCI. 
This PR implements this pipeline so we don't need to run it manually everytime we add some library.
> Keep production gemfile updated

- app/lib/three_scale/spam_protection/integration/controller.rb
- app/lib/three_scale/spam_protection/integration/model.rb
- app/lib/three_scale/spam_protection/protector.rb
> [Refactor] Rename method is_spam? -> spam?

- app/helpers/vertical_nav_helper.rb
- app/models/user.rb
- app/views/shared/provider/navigation/audience/_billing.html.slim
I came across this while working on another issue and it is easy to clean up so almost a must 😝
> [Refactor] Use impersonation_admin methods

- app/models/proxy.rb
- config/locales/en.yml
- test/integration/api/policies_controller_test.rb
- test/unit/proxy_test.rb
https://issues.redhat.com/browse/THREESCALE-1059
> [Proxy] read_and_parse_policies_config!

- openshift/system/Dockerfile.on_prem
The CBS repo is not found ....
Skipping it
> Fix Dockerfile.on_prem

- portafly/src/i18n/locales/en/analytics.yml
- portafly/src/i18n/locales/en/applications.yml
- portafly/src/i18n/locales/en/integration.yml
- portafly/src/i18n/locales/en/overview.yml
- portafly/src/i18n/locales/en/shared.yml
Docs team asked to use `_description` as suffix instead of `_desc`
https://issues.redhat.com/browse/THREESCALE-4863
> Using description instead of desc in yml files

- .circleci/config.yml
The used key has an unkown owner, I replaced it by 3scale-ninjabot
> [oracle] Fix circleci building

- app/assets/javascripts/ajax_events.js
- app/javascript/src/Dashboard/index.jsx
We will use Bugsnag to track runtime javascript errors so we should get rid of any reference to Errorception in our cod
https://issues.redhat.com/browse/THREESCALE-4355
> Removing errorception code

- config/abilities/provider_member.rb
- test/integration/admin/api/services/backend_usages_controller_test.rb
- test/integration/api/backend_usages_controller_test.rb
Since APIAP was first introduced, only provider admin users have been able to manage backend usages. This PR changes the behaviour so member users can as well manage backend usages (UI and API; list, create, read, update, delete).
Closes [THREESCALE-4489](https://issues.redhat.com/browse/THREESCALE-4489)
> Adds permission to member users to manage Backend Usages

- app/models/cinstance.rb
- app/models/concerns/save_destroy_for_service_association.rb
- app/models/metric.rb
Related to https://github.com/3scale/porta/pull/1815#discussion_r412783360
> Rename & Move app/lib/archive_deletion_belonging_to_service.rb -> app/models/concerns/save_destroy_for_service_association.rb

- Gemfile.base
- Gemfile.lock
- Gemfile.prod.lock
- app/models/metric.rb
- app/workers/backend_delete_stats_worker.rb
- test/test_helpers/backend.rb
- test/workers/backend_delete_stats_worker_test.rb
> Updating pisoni 1.29

- app/representers/method_representer.rb
- app/representers/metric_representer.rb
- spec/acceptance/api/method_spec.rb
- spec/acceptance/api/metric_spec.rb
Closes [THREESCALE-4938](https://issues.redhat.com/browse/THREESCALE-4938)
> [API] Return parent_id for JSON in Metric endpoints

- app/views/provider/admin/dashboards/_list_backends.html.slim
Extracted from https://github.com/3scale/porta/pull/1421
> Fix N+1 Queries on dashboard backend list

- portafly/src/components/data-list/DataListContext.tsx
- portafly/src/components/data-list/SearchWidget.tsx
- portafly/src/components/data-list/Toolbar.tsx
- portafly/src/components/data-list/index.ts
- portafly/src/components/data-list/reducers/FiltersReducer.ts
- portafly/src/components/data-list/searchWidget.scss
- portafly/src/pages/Overview.tsx
- portafly/src/tests/components/data-list/DataListContext.test.tsx
- portafly/src/tests/components/data-list/SearchWidget.test.tsx
- portafly/src/tests/components/data-list/__snapshots__/SearchWidget.test.tsx.snap
This is the search bar (filter) component, which is part of the data list component used by many list components such as Developer Account List
TODO
Visit Overview page example, it should work as expected.
**TODO** :
* [ ] Tests
More testing will be added in following PRs
> [Data List] Search bar component

- portafly/src/pages/Login.tsx
- portafly/src/tests/pages/Login.test.tsx
- portafly/src/tests/pages/__snapshots__/Login.test.tsx.snap
This is very low prio but I did a couple of changes:
**Login**
- Minimal code reformat
- Moves token check at the beginning, seems wrong to execute all when `authToken` makes the Component invalid.
- Adds a test case for an existing auth token
> Login improvement bits

- portafly/src/components/data-list/DataListContext.tsx
- portafly/src/components/data-list/PaginationWidget.tsx
- portafly/src/components/data-list/index.ts
- portafly/src/components/data-list/reducers/FiltersReducer.ts
- portafly/src/components/data-list/reducers/PaginationReducer.ts
- portafly/src/components/data-list/reducers/index.ts
- portafly/src/pages/Overview.tsx
- portafly/src/tests/components/data-list/PaginationWidget.test.tsx
- portafly/src/utils/index.ts
pagination widget is part of the data list component.
TODO
There's an example code in overview page to play with.
> [mob] PaginationWidget

- app/controllers/admin/api/service_plan_features_controller.rb
- doc/active_docs/Account Management API.json
> Fix for [THREESCALE-3922](https://issues.redhat.com/browse/THREESCALE-3922)
> fix THREESCALE-3922 Service Plan Features Delete

- app/controllers/concerns/error_handling.rb
- features/developer_portal/login.feature
- features/support/capybara.rb
- lib/developer_portal/app/controllers/developer_portal/login_controller.rb
- test/integration/developer_portal/login_test.rb
- test/integration/sessions_test.rb
- test/test_helpers/authentication.rb
Fixes [THREESCALE-2922](https://issues.redhat.com/browse/THREESCALE-2922)
For reference: https://github.com/3scale/system/commit/504d8a75d15e6dbf12a235c0f673d2fa6366d795
But most of the work was already done before this PR 😄
> Fix CSRF vulnerability in Login Dev Portal

- portafly/src/i18n/locales/en/accounts.yml
- portafly/src/i18n/locales/en/shared.yml
> Lists UI Strings for Accounts - Users
> `fixes #<4836>`
> None
* UI Strings Jira: [THREESCALE-4836](https://issues.redhat.com/browse/THREESCALE-4836)
* Most of the strings contain text similar to the mockup.
* For strings different to the mockup, you will see this tag: **[PROPOSED]**
> 4836-Account_Users main and modal pages

- portafly/package.json
- portafly/src/components/AppLayout.tsx
- portafly/src/components/Loading.tsx
- portafly/src/components/data-list/SearchWidget.tsx
- portafly/src/components/data-list/Toolbar.tsx
- portafly/src/components/util/AlertsContext.tsx
- portafly/src/pages/Login.tsx
- portafly/src/pages/Overview.tsx
- portafly/src/tests/components/AppLayout.test.tsx
- portafly/src/tests/components/data-list/SearchWidget.test.tsx
- portafly/src/tests/components/data-list/__snapshots__/SearchWidget.test.tsx.snap
- portafly/src/tests/components/developer-accounts/__snapshots__/DeveloperAccountsTable.test.tsx.snap
- portafly/src/tests/pages/__snapshots__/DeveloperAccounts.test.tsx.snap
- portafly/src/tests/pages/__snapshots__/Login.test.tsx.snap
- portafly/yarn.lock
Patternfly/React 4.12.7 is released with some [breaking changes](https://github.com/redallen/patternfly-scripts/blob/master/github/patternfly/patternfly-react/pull_requests/breaking-change-notes.md), we need to update dependencies, some components and tests
None
Go to portafly dir:
```
cd portafly
```
Install dependencies:
```
yarn
```
Start in browser
```
yarn start
```
Run tests:
```
yarn test
```
Notes:
@cntlsn @thomasmaas
This new release introduces some visual changes, please take a look
> [Portafly] Updating PF4 dependencies and fixing tests

- portafly/src/tests/components/AppLayout.test.tsx
> Fixes lint error

- portafly/src/components/data-list/BulkSelectorWidget.tsx
- portafly/src/components/data-list/DataListContext.tsx
- portafly/src/components/data-list/index.ts
- portafly/src/components/data-list/reducers/TableReducer.ts
- portafly/src/components/data-list/reducers/index.ts
- portafly/src/i18n/locales/en/accounts.yml
- portafly/src/i18n/locales/en/shared.yml
- portafly/src/pages/Overview.tsx
- portafly/src/tests/components/data-list/BulkSelectorWidget.test.tsx
- portafly/src/tests/components/data-list/DataListContext.test.tsx
- portafly/src/types/data-list.d.ts
- portafly/src/types/index.d.ts
- portafly/src/utils/reducers.ts
Adds a widget and introduces selections and table data into DataListContext
> [portafly] BulkSelectorWidget

- portafly/src/components/data-list/modals/DataListModal.tsx
We're using the property `title` wrong: we need to add a `header` instead.
> Fix DataList modal

- portafly/src/components/data-list/BulkSelectorWidget.tsx
- portafly/src/components/data-list/DataListContext.tsx
- portafly/src/components/data-list/modals/dataListModal.scss
- portafly/src/tests/components/data-list/BulkActionsWidget.test.tsx
- portafly/src/types/data-list.d.ts
* Fixes some type incongruences
* Fixes test by adding missing mock
* Fixes lint
> Small patch for Data List

- Dockerfile
They are no use anyway, not working
And it is a leak adding them
> Remove credentials from Dockerfile

- portafly/src/auth/AuthContext.tsx
A commit was missed after a rebase.
Original #1906
> Clean up Portafly Login tests (2)

- portafly/src/components/Root.tsx
- portafly/src/i18n/locales/en/accounts.yml
- portafly/src/i18n/locales/en/shared.yml
This is a follow up of https://github.com/3scale/porta/pull/1861, where we introduced bad formatted yaml strings
> [Portafly] Fixing wrong strings in accounts and shared pages

- features/support/capybara.rb
- features/support/hooks.rb
Bonus we also have network logging
> [cucumber] Re-Enable console logging on errors

- .gitignore
- app/lib/currencies_loader.rb
- app/models/finance/billing_strategy.rb
- config/application.rb
- openshift/system/config/currencies.yml
- test/unit/currencies_loader_test.rb
- test/unit/finance/billing_strategy_test.rb
Closes [THREESCALE-3076](https://issues.redhat.com/browse/THREESCALE-3076)
Depends on https://github.com/3scale/deploy/pull/662
> Allow to configure custom list of currencies

- portafly/src/components/data-list/reducers/BulkActionsReducer.ts
- portafly/src/components/data-list/reducers/FiltersReducer.ts
- portafly/src/components/data-list/reducers/PaginationReducer.ts
- portafly/src/components/data-list/reducers/TableReducer.ts
A bit of cleanup and refactoring for the reducers' actions.
(it's based on #1920 so merge only after)
> Refactor / Clean-up of DataList reducers' actions

- .gitignore
> [gitignore] Ignore *.orig files

- portafly/src/i18n/locales/en/audience/accounts/listing.yml
- portafly/src/i18n/locales/en/shared.yml
Includes strings for Audience > Accounts > Listing
[THREESCALE-4834](https://issues.redhat.com/browse/THREESCALE-4834)
* Duplicated content highlighted in `shared.yml`. Not removed, only highlighted.
* Duplicated content is placed under the relevant sections in `listing.yml`
> 4834-AudienceAccountsListing UI Strings

- config/application.rb
- lib/three_scale/middleware/handle_parse_error.rb
- test/test_helpers/api_routing.rb
- test/unit/three_scale/middleware/handle_parse_error_test.rb
Closes [THREESCALE-5280](https://issues.redhat.com/browse/THREESCALE-5280)
> Handle ActionDispatch::ParamsParser::ParseError

- Gemfile.lock
- Gemfile.prod.lock
Closes https://issues.redhat.com/browse/THREESCALE-4675
> Fix CVE-2019-11027
